### ISSUE TITLE
Pull Request CRD: GitLab Support

### ISSUE THREAD

**Issue by wlynch** [tektoncd/pipeline#1000]
Tracking issue for GitLab Pull Request support in the Pull Request CRD.

GitLab API documentation: https://docs.gitlab.com/ee/api/merge_requests.html
Existing Tekton Pull Request support (GitHub): https://github.com/tektoncd/pipeline/tree/master/cmd/pullrequest-init

**Comment by bobcatfish** [comment]
AND ITS ISSUE 1000

![](https://i.chzbgr.com/full/6613858304/h391F6A12/)

woooooo 🎉

**Comment by bobcatfish** [comment]
I think we have this now, is that right @wlynch ?

**Comment by wlynch** [comment]
Yup! This was added in d478e7d6d576d2e309c6a42ecf8da75c536df681

**Comment by dewan-ahmed** [comment]
@wlynch @bobcatfish is there a plan to have a guide showing build taskrun from gitlab?

**Comment by dibyom** [comment]
Gitlab support in Triggers might be related: https://github.com/tektoncd/triggers/pull/434
