### ISSUE TITLE
[question] can the pipeline support non-kubernetes environments

### ISSUE THREAD

**Issue by HusterWan** [tektoncd/pipeline#1012]
# Why I ask this question?

we have two large production environment, which one is an old system that not used the kubernetes, the other one is kubernetes  env.

I want to delivery the components (kubernetes components and non-kubernetes components) by all using the tekton. It this idea is reasonable or do you guys have any suggestion for this situation?

**Comment by vincent-pli** [comment]
Tekton is k8s native, can not run without k8s.
Does the old environment has Docker? you can use `Kind` prepare a build-in k8s, then run Tekton on that.

**Comment by tiger74s** [comment]
We understand that Tekton is k8s native and it must run inside k8s. Can Tekton support a pipeline that release the code to the old environment that is running on VM not k8s?  Many enterprises may have that requirement. Can it be a new feature for Tekton?

**Comment by HusterWan** [comment]
> Tekton is k8s native, can not run without k8s.
> Does the old environment has Docker? you can use `Kind` prepare a build-in k8s, then run Tekton on that.

@vincent-pli our old environment is all running containers,  what do you mean `use Kind prepare a build-in k8s`, does this have docs?

**Comment by vincent-pli** [comment]
😭 So, you have a `Tekton-pipeline` running for some process (checkout, build, whatever), when almost complete, get an output stuff, then you want to deploy(release) these stuff to a no-k8s env? am I right?
 
I think you need a task to do that, you can handle this in that task, no matter the target env is k8s or not.

**Comment by HusterWan** [comment]
> 😭 So, you have a `Tekton-pipeline` running for some process (checkout, build, whatever), when almost complete, get an output stuff, then you want to deploy(release) these stuff to a no-k8s env? am I right?
> 

you are right

> I think you need a task to do that, you can handle this in that task, no matter the target env is k8s or not.

but how can i run tekon-pipeline task with k8s env?  ...

**Comment by vincent-pli** [comment]
You can have two tasks all depends on previous step (task), one for k8s env another for no-k8s
another option is handle both in one task.

**Comment by HusterWan** [comment]
> You can have two tasks all depends on previous step (task), one for k8s env another for no-k8s
> another option is handle both in one task.

got you, 3x

**Comment by paulalex** [comment]
Sorry to jump in but I have a similar use case. Is it possible to run builds that deploy into k8s as our current jenkins set up does for us, but also use tekton pipelines to deploy changes for terraform to roll out infrastructure changes? I cant find any information on this online.

**Comment by vdemeester** [comment]
@HusterWan @paulalex yeah, there is no limitiation on deploying things to the current running cluster (or any k8s cluster to be honest). You can deploy to anything as long as you have (or write) a task for it (see [ansible `tower-cli` task]() for example)

We may need more task of the kind (terraform, …)  and maybe a little bit of documentation or blog posts on the future `tekton.dev` website :angel: 

I am tempted to close this issue in the mean time, wdyt ?

**Comment by bobcatfish** [comment]
This _is_ something we definitely want to support in the long run but we haven't made a lot of movement toward it yet. Anyone interested in getting started with any requirements gathering / design work?

**Comment by bobcatfish** [comment]
@ImJasonH opened https://github.com/tektoncd/pipeline/issues/1826 , also @dlorenc  wrote a blog post experimenting with Tekton + MacStadium (https://medium.com/@dlorenc/tekton-on-mac-ed6ea72d1efb)

I'm gonna assume we can close this issue for now and focus on specific issues such as #1826
