### ISSUE TITLE
Issue : starting container process caused "chdir to cwd (\"/workspace/git\")

### ISSUE THREAD

**Issue by cmoulliard** [tektoncd/pipeline#1013]
## Issue

Version used: `v0.3.1`

I'm facing a strange issue. Project has been cloned correctly (I suppose according to the log of the git step)

`{"level":"info","ts":1561531018.2719452,"logger":"fallback-logger","caller":"git/git.go:105","msg":"Successfully cloned https://github.com/snowdrop/component-operator-demo/  @ master in path /workspace/git"}`

but when the s2i step to generate the dockerfile takes place, I'm getting this error 

`container_linux.go:247: starting container process caused "chdir to cwd (\"/workspace/git\") set in config.json failed: no such file or directory"`

How can we investigate such error/issue ? We should have a debug option able to log more traces ?

**Comment by vincent-pli** [comment]
@cmoulliard  Could you post the `pipeline` definition.

**Comment by cmoulliard** [comment]
Here are the definitions about the `task` and `taskrun`

https://github.com/snowdrop/component-operator/blob/master/pkg/controller/component/taskruns.go
https://github.com/snowdrop/component-operator/blob/master/pkg/controller/component/tasks.go

**REMARK**: The error reported occurs sometimes

**Comment by vdemeester** [comment]
@cmoulliard I am going to close this (as the linked file are not available anymore and there is a lack of activity on this issue). If you face those again, please open a new issue :wink: 

/close
