### ISSUE TITLE
Expose pipelinerun status to taskrun

### ISSUE THREAD

**Issue by dibyom** [tektoncd/pipeline#1016]
# Expected Behavior

The use case is around tasks that can use the pipeline run status e.g. a task that updates github PR status based on the success/failure of a previous pipeline (https://github.com/tektoncd/pipeline/pull/995#issuecomment-505476017). 

# Actual Behavior

Does not exist though there is WIP to expose the pipelinerun status to the conditional container.

**Comment by vdemeester** [comment]
A task could use the kubernetes and Tekton API (given it has access to the cluster and the correct RBAC setup), and get information about the current Pipeline, this would only require that a reference of the current run (taskrun, pipelinerun) can be passed to the container process (as an environment variable, through variable interpolation, …).

**Comment by dibyom** [comment]
@akihikokuroda pointed out that this is already possible in the [design](https://docs.google.com/document/d/1eJBb2VHuSTbrIWfPE3TGdRRfdbJsRCOBIqfTwx9M3H8/edit#) for #1020 : 
 
Each task can know what the pipelinerun and taskrun it is executed under by mapping the label (tekton.dev/pipelineRun) to an environment variable and then using the Kube API to get the necessary information:
```
     env:
        - name: PIPELINERUN
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tekton.dev/pipelineRun']
```

Ref: https://github.com/tektoncd/pipeline/blob/master/docs/labels.md
https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/
https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/
