### ISSUE TITLE
Design: How to Handle Deletion of Referenced Objects

### ISSUE THREAD

**Issue by aaron-prindle** [tektoncd/pipeline#102]
## Expected Behavior
When a referenced object is deleted (TaskRun -> TaskRef -> Task), make sure that each controller has a way for handling that.

## Actual Behavior
It is unclear, this is not expressly handled

## Steps to Reproduce the Problem

  1. Create a Task
  2. Create a TaskRun that references the Task
  3. Delete the Task

**Comment by vdemeester** [comment]
@bobcatfish what should we do there ? I think we are "good" for now as it makes sense, for me, to keep `TaskRun` of deleted Task (and the opposite), but I wonder if we need to do something else still.

This is also a bit related to #279

**Comment by vincent-pli** [comment]
I think we could prepare a `daemon` container in `pod` of `taskrun`.
In that container, watching on the resource (`task`, `pipelineresouce`) referenced, if any change (delete, update), we could send k8s event to related `taskrun`/`pipelinerun`

Similar to this implement:
https://github.com/tektoncd/triggers/pull/174/commits/e10d490fe3faf9dbe170b74a79cee4a76a90ba43

**Comment by bobcatfish** [comment]
Yeah I think we're fine as-is @vdemeester ,  I don't mind resolving this, unless @vincent-pli is this functionality you need?

@vincent-pli your solution it sounds like would also _interrupt_ any currently executing `TaskRuns` that used `Tasks` or `PipelineResources` that were deleted, I'm not sure we'd need to go that far. (Maybe you have a use case where you'd want this tho?)

**Comment by vincent-pli** [comment]
No interrupt, only `watching` -- `notification`

The reference resource (`task`, `pipelineresource`) should not be modified in the period the related resource(`taskrun`) running.
If modify occurred, based on current implements, no body know that, everything looks good, but that's not real, maybe the mistake long before found.

**Comment by bobcatfish** [comment]
I'm not certain this issue is relevant anymore so I'm going to close it but please re-open if I'm wrong!
