### ISSUE TITLE
Usecase: Integration tests task

### ISSUE THREAD

**Issue by ArisBlkkr** [tektoncd/pipeline#1032]
# Expected Behavior
For a simular story like [url](https://itnext.io/running-integration-tests-with-kubernetes-ae0fb71e207b), I would like to run steps/containers in a task at the same time. One container contains a webserver, one a database and one the tests for integrations between the two. I only need to execute a command in the test container, not in the other containers, so I'm more or less looking for a sidecar pattern whereas containers are running within the pod during all steps. They would probably need a readinessProbe configured to make sure they are ready for testing.

# Actual Behavior
Steps within the Task only run concurrently (as far as I know).

# Additional Info
- These kind of containers need ConfigMaps/Secrets and more for configuration
- I am more than happy to help!

**Comment by houshengbo** [comment]
@ArisBlkkr 
This is a lovely use case in terms of concurrency. 
However, it seems to me that we need to build on top of webserver, database, or some other third party services, where we need to take care of the credentials. Is that a scope that goes beyond the integration tests of tekton pipeline?(Concerned, but not quite sure of that)
I hope you can be more generic on a certain aspect about that this case can cover for tekton pipeline, like concurrent task running for pipeline, or something more specific.

**Comment by aristosvo** [comment]
@houshengbo 
Thanks!:) I'm not sure if it is beyond the scope of Tekton to do tests for more than 1 container, as a developer I would like to. Please check [_Running integration tests in Kubernetes_](https://itnext.io/running-integration-tests-with-kubernetes-ae0fb71e207b) for a more elaborate story of the usecase and how it is currently supported with Jenkins.

**Comment by dibyom** [comment]
I think with Sidecars, this use case is now possible? cc @sbwsg

**Comment by vdemeester** [comment]
@sbwsg @dibyom what do you think should be the next step for this ? more documentation (like examples) ?

**Comment by dibyom** [comment]
There are a few sidecar taskrun examples (though not one that is explicitly a integration test example) e.g. https://github.com/tektoncd/pipeline/blob/master/examples/v1beta1/taskruns/dind-sidecar.yaml

We can keep this open as a documentation issue or close it?
