### ISSUE TITLE
Support for global parameter output

### ISSUE THREAD

**Issue by hongchaodeng** [tektoncd/pipeline#1041]
# Use case

Currently we have an etcd storing configuration data. In the deploy pipeline the first task is to read the data from etcd and convert it into pipeline parameters.

This was done using the Argo global parameter output feature: https://github.com/argoproj/argo/blob/7a21adfeb0af18c2452648a8bb3698a687f99b5e/examples/global-outputs.yaml#L27-L30

# Question

Can you provide any guide on how to set global parameters via Tekton? We would like to help if anything is needed.

**Comment by dibyom** [comment]
One way to do this might be to have a task that reads from etcd the param values, and then triggers the next pipelinerun/taskrun with the params (possibly using the tkn cli: https://github.com/tektoncd/catalog/pull/155)

**Comment by dlorenc** [comment]
I think this is handled by the new TaskResults feature.

https://github.com/tektoncd/pipeline/blob/master/docs/tasks.md#storing-execution-results
