### ISSUE TITLE
Http Support for Webhook

### ISSUE THREAD

**Issue by sandrom** [tektoncd/pipeline#1050]
# Expected Behavior

The webhook supports http (80/8080) as configurable option, so that ssl termination can happen in some loadbalancer beforehand.
I would expect https to be default, but still configurable.

# Actual Behavior

http vs https (8080/8443) not configurable

# Steps to Reproduce the Problem

https://github.com/tektoncd/pipeline/blob/master/cmd/webhook/main.go

see here for 8443. Happy to have an env variable that makes this configurable to 8080 without ssl.

# Additional Info

requirement for certain architectures and sufficiently safe in the case I have seen. I would be very happy if we could make Tekton more flexible here in general :)

**Comment by dibyom** [comment]
This would probably be a change in knative/pkg @vdemeester ?

**Comment by vdemeester** [comment]
@dibyom indeed :anchor: 

- we should see if it's already supported in `knative/pkg`
- if not, we need to create an issue there and track the resolution of it :angel:

**Comment by dibyom** [comment]
Looks like its possible? https://github.com/tektoncd/pipeline/blob/master/vendor/knative.dev/pkg/webhook/webhook.go#L65

**Comment by dibyom** [comment]
Actually seems like its already using https by default:
From my webhook service:
```
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8443
 ```

**Comment by sandrom** [comment]
if you serve https on port 80 it is still https. the asked feature here is http, not specifically the port.

**Comment by dibyom** [comment]
Yeah, my bad - I somehow though that the webhook was using http, not https :man_facepalming: 

Looking through the code in knative.dev/pkg/webhook it does seems like its https only (we create the certs if they are not supplied).

**Comment by vincent-pli** [comment]
IIRC the `admissionwebhook` only support `https`:
https://github.com/kubernetes/kubernetes/blob/a6f41a46a54c47e4225adbcca251ce8204f9bb1c/pkg/apis/admissionregistration/types.go#L491

**Comment by vdemeester** [comment]
I think we could close this as as @vincent-pli said, `admissionwebhook` only support `https`

/cc @dibyom @bobcatfish

**Comment by dibyom** [comment]
Fine by me! Feel free to re-open if you feel otherwise!
/close
