### ISSUE TITLE
TestAssets.Logs is not set anymore

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/pipeline#1067]
# Expected Behavior
TestAssets.Logs allows to obtain the controller logs during a test

# Actual Behavior
Since the migration to knative/injection for the taskrun controller, TestAssets.Logs is not set anymore. There is a `TestLogger` that is setup and stored in the context, but it's not linked to TestAssets. We should either fix TestAssets.Logs to use the logger from the context, or we should remove TestAssets.Logs and document how to get logs from the TestLogger.

# Additional Info
https://github.com/tektoncd/pipeline/blob/master/pkg/reconciler/v1alpha1/taskrun/taskrun_test.go#L225

**Comment by afrittoli** [comment]
@vdemeester what do you recommend?

**Comment by afrittoli** [comment]
Since the context is not in the TestAssets, it is not possible to get the logger from here. We could add the context to the TestAssets struct.

**Comment by vdemeester** [comment]
I don't see anything about `TestAssets` in the tests anymore… so assuming we can close this :stuck_out_tongue: 
/close
