### ISSUE TITLE
Configure storage class for PVC of PipelineRuns

### ISSUE THREAD

**Issue by Fabian-K** [tektoncd/pipeline#1101]
Hi, 

when using pipelines, a pvc for each pipeline run is automatically created. I want to be able to configure the storage class used instead of always using the default storage class of the cluster.

**Comment by Fabian-K** [comment]
Looks like this can be added to https://github.com/tektoncd/pipeline/blob/master/pkg/artifacts/artifacts_storage.go#L34-L44 similar to how the size of the pvc can be configured. 

I´m thinking of giving it a try myself, however as this would be my first contribution to tekton and i´m not an experienced go developer this might take some time 🙈

**Comment by vdemeester** [comment]
@Fabian-K https://github.com/tektoncd/pipeline/pull/1087 might be interesting to you :angel:

**Comment by Fabian-K** [comment]
Thx @vdemeester , indeed. However, I think this is still relevant as #1087 targets more complicated setups like chaining pipelines while this is for the basic pipeline case, right? I started working on this in https://github.com/Fabian-K/pipeline/tree/pvc-storage-class

**Comment by bobcatfish** [comment]
I am going to re-open this to make sure that the features in #1087 get this functionality as well!

**Comment by vdemeester** [comment]
I am guessing #1639 would help resolving this issue although not fully if I'm correct.

/kind feature

**Comment by sbwsg** [comment]
Now that we have both storage class configurable in the resources PVC as well as workspaces which allow configuration of the PVC directly in Runs I think we're safe to consider this closed.  If anybody wants to revisit or request more work here I propose starting a new issue.  Cheers!

**Comment by sibelius** [comment]
I've tried to do this

```
workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        storageClassName: ceph-rbd
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 4Gi
```

in our TriggerTemplate, but I got this error on PVC

```
MountVolume.MountDevice failed for volume "pvc-25be588c-7bf5-4781-86c9-43e02e7640ea" : rpc error: code = Aborted desc = an operation with the given Volume ID 0001-0012-rook-ceph-external-0000000000000002-8d4f478b-14af-438c-9da2-affd679b20a0 already exists

```

am I doing something wrong ?
