### ISSUE TITLE
Operator must be restarted to allow a pod created by taskrun to get security privileged

### ISSUE THREAD

**Issue by cmoulliard** [tektoncd/pipeline#1103]
# Info

ocp: 3.11
tekton release: v0.4.0

# Issue

We have an operator responsible to create a `task` and `taskrun` and to deploy them into a namespace. As the `buildah step` part of the task [1] needs privileged access [2], we update the `SecurityContextConstraint` in order to append the `serviceaccount` to the list of the users defined for the SCC/Privileged

Unfortunately, even if the SCC is updated before the taks/taskRun is deployed, then we have to restart our operator before to install the task/taskrun in order to make it work.
Otherwise the `TaskRun status` will report such error 

```
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  creationTimestamp: 2019-07-18T13:41:19Z
  generation: 1
  labels:
    build: http-rest-sb
    component_cr: http-rest-sb
  name: http-rest-sb
  namespace: test7
  ownerReferences:
  - apiVersion: devexp.runtime.redhat.com/v1alpha2
    blockOwnerDeletion: true
    controller: true
    kind: Component
    name: http-rest-sb
    uid: b936c274-a961-11e9-bbd9-107b44b03540
  resourceVersion: "46733220"
  selfLink: /apis/tekton.dev/v1alpha1/namespaces/test7/taskruns/http-rest-sb
  uid: b93ee23c-a961-11e9-bbd9-107b44b03540
spec:
  inputs:
    params:
    - name: moduleDirName
      value: .
    - name: contextPath
      value: ""
    resources:
    - name: git
      resourceRef: {}
      resourceSpec:
        params:
        - name: revision
          value: 2.1.6-1
        - name: url
          value: https://github.com/snowdrop/rest-http-example.git
        type: git
  outputs:
    resources:
    - name: image
      resourceRef: {}
      resourceSpec:
        params:
        - name: url
          value: docker-registry.default.svc:5000/test7/http-rest-sb
        type: image
  serviceAccount: build-bot
  taskRef:
    kind: Task
    name: s2i-buildah-push
status:
  conditions:
  - lastTransitionTime: 2019-07-18T13:41:20Z
    message: 'Missing or invalid Task test7/s2i-buildah-push: pods "http-rest-sb-pod-1effd5"
      is forbidden: unable to validate against any security context constraint: [spec.containers[3].securityContext.privileged:
      Invalid value: true: Privileged containers are not allowed spec.containers[5].securityContext.privileged:
      Invalid value: true: Privileged containers are not allowed spec.containers[3].securityContext.privileged:
      Invalid value: true: Privileged containers are not allowed spec.containers[5].securityContext.privileged:
      Invalid value: true: Privileged containers are not allowed]'
    reason: CouldntGetTask
    status: "False"
    type: Succeeded
  podName: ""
  startTime: 2019-07-18T13:41:19Z
```

**Remark** : We don't have such an issue with our operator when we update SCC for kubeDB operator !

[1] https://github.com/snowdrop/component-operator/blob/d863b8c708350d277da03584333ec4d2b55aba3f/pkg/controller/component/mode-build.go#L40
[2] https://github.com/snowdrop/component-operator/blob/d863b8c708350d277da03584333ec4d2b55aba3f/pkg/controller/component/mode-build.go#L40

**Comment by sbwsg** [comment]
Is this issue ongoing?  No updates on it since July.

Also, possibly more relevant if posted at https://github.com/tektoncd/operator ?

**Comment by vdemeester** [comment]
@sbwsg right, I am not entirely sure. @cmoulliard when you talk about operator, do you refer to the Hayckon operator, the tektoncd|openshift-pipelines operator or the tektoncd/pipeline controller ?

**Comment by cmoulliard** [comment]
> when you talk about operator, do you refer to the Hayckon operator

My use case refers to our operator or let's to an operator creating a Tekton CRD Task, Taskrun

**Comment by bobcatfish** [comment]
I'm going to close this for now, please re-open if needed.
