### ISSUE TITLE
Why do we run imageDigestExporter after each step in a taskrun?

### ISSUE THREAD

**Issue by dibyom** [tektoncd/pipeline#1104]
The imageDigestExporter container writes the digest of any built images to the container's `terminationMessagePath` which is then parsed by the taskrun controller in order to update the taskrun's status with the image digests.

The container only gets added if a task contains an output resource of type image. However, it [gets added after each step](https://github.com/tektoncd/pipeline/blob/master/pkg/reconciler/v1alpha1/taskrun/resources/image_exporter.go#L78) as opposed to being added just once (after all the regular steps). The container itself takes as input all the output images that will be produced in a task, and writes the digest for [all of them](https://github.com/tektoncd/pipeline/blob/master/cmd/imagedigestexporter/main.go#L50). So, it is unclear to me why we need to run it after each step. 

Does anyone know why we need to  run the container after each step? Maybe @nader-ziada  or @ImJasonH ?

/kind question

**Comment by vdemeester** [comment]
Looking into that, I think this is working like that to support multiple image built in different steps. but looking at the code, only one step/container is needed.

/assign
/kind bug
/remove-kind bug
