### ISSUE TITLE
Make sure the webhook is always registered before allowing user to create resources

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/pipeline#1113]
As of today, `knative/pkg`'s code is the one responsible to register the webhook on kubernetes. This means, the following are possible :
- The webhook fails to start (for any reason), it does not get registered, thus it's not applied
- The webhook takes time to start (slow network, …), it's not registered quickly enough, a user can create resources

In all those cases, the user can end up creating resources that are either not valid or not mutated (with defaults values)

There is two way to fix these cases:

1. Move the webhook registration in the `yaml`s, so that the webhook is registered as soon as the CRDs are created, *before* it started, and thus it will fail if the webhook is not running
2. Having the controller validate

I have a **very very high** preference for solution `1.` .

**Comment by bobcatfish** [comment]
@vdemeester are you still working on this or should we throw it in the backlog instead?

**Comment by bobcatfish** [comment]
Throwin it in the backlog :sunglasses: But I added it to the "post beta" milestone so we won't forget it!

**Comment by vdemeester** [comment]
Moving into next release, #1894 with some `knative.dev/pkg` will fix this I think

/assign
