### ISSUE TITLE
Tests from other tekton project on releases

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/pipeline#1121]
Related to latest release (0.5.2) that include few problems, with the one of interest here being #1075, a controller panic.
We decided during the [post-mortem](https://docs.google.com/document/d/1iHbb4Yc5IgcR5UG5BWPM9V1sr1-05tOHaO2VgXCQ-jo/edit) brainstorm, that we need to run other project's tests (as much as possible) while doing the release (or on what commit we are releasing).

In a gist this means:
- Running tektoncd/cli e2e tests
- Running tektoncd/dashboard e2e tests
- Running tektoncd/triggers e2e tests
- More later one ? (maybe something on catalog *if* we have some e2e tests other than validation)

All of this should be using `Task` and `Pipeline` as much as possible.

This issue is here to track that work.

/cc @bobcatfish

**Comment by bobcatfish** [comment]
@afrittoli i've heard a rumor that you are taking this on?

**Comment by bobcatfish** [comment]
Our dogfooding in the "robocat" cluster should get us most of the way to this https://github.com/tektoncd/plumbing/tree/master/robocat!
