### ISSUE TITLE
Define notifications & notificatiers as CRDs

### ISSUE THREAD

**Issue by Leboudin** [tektoncd/pipeline#1128]
Suggest that notifications & notifiers are defined and invoked as CRDs, so that people can easily implement their own notification workflows.

---- 

I'm about to get started on this, any idea is appreciated :D

**Comment by dibyom** [comment]
>I'm about to get started on this, any idea is appreciated :D

That's awesome! I'd recommend writing up a [proposal](https://github.com/tektoncd/community/blob/master/process.md#proposing-features) first and discussing it at a[ working group meeting](https://github.com/tektoncd/community/blob/master/contact.md#working-group). Looking forward to it!

**Comment by dibyom** [comment]
@Leboudin let's continue this discussion for notification design in #49 since that's already been open for a while. I'm going to close this issue.
