### ISSUE TITLE
Noisy log message :O

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#1145]
# Expected Behavior

When looking at logs from running Tasks (e.g. using `tkn pr logs -f` to tail logs from a PipelineRun😉 ) the only output should be:

- Informative logs from the containers inside the executing pods
- Error logs if actual errors occur
- Logs from the user provided pods

# Actual Behavior

Whenever I look at logs from a running Task I see something like this over and over:

```
{"level":"warn","ts":1564628323.275128,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
```

It's not clear to me where exactly this is coming from or what it means.

# Steps to Reproduce the Problem

1. Run a Pipeline or Task, e.g. [apply an example](https://github.com/tektoncd/pipeline/tree/master/examples#examples)
2. Get the name of the run (e.g. [`tkn pipelinerun list`](https://github.com/tektoncd/cli/blob/master/docs/cmd/tkn_pipelinerun_list.md)
3. Look at the logs, e.g. [`tkn pipelinerun logs <pipelinerun name>`](https://github.com/tektoncd/cli/blob/master/docs/cmd/tkn_pipelinerun_logs.md)

**Comment by afrittoli** [comment]
It's the logger we use from knative, it tries to enrich log lines with a commit ID from kodata - see https://github.com/knative/pkg/pull/506.
I understand that we use the knative logger for Tekton services, but perhaps we should be using a different logger for Tasks and Pipelines.

**Comment by tomgeorge** [comment]
I was poking around on this issue, and was able to get rid of the git commit messages by changing the logger in `entrypoint` and `git-init`.  I would be happy to make the change to a different logger and open a PR.  Does the project team have a recommended alternative logger (maybe regular `zap`?)

**Comment by tomgeorge** [comment]
This is also my first time really looking at the tekton codebase.  Am I right in assuming that the other components under `cmd` like `creds-init`, `pullrequest-init`, etc, that use the knative logger, would also introduce some more noise to the logs and need to be changed?  Or is there a better way to do it?

**Comment by bobcatfish** [comment]
Thanks for this @tomgeorge ! I think #2000 solves this issue so I'm going to close it but please re-open if I'm wrong :D
