### ISSUE TITLE
Pipeline status not updated when `runAfter is used with a `condition` 

### ISSUE THREAD

**Issue by dibyom** [tektoncd/pipeline#1173]
Say we have a pipeline with two pipeline tasks A and B. A is a conditional task that only runs if a condition is true while B is dependent on A using either `from` or `runAfter`.

# Expected Behavior
If task A is skipped due to a condition failure, task B should not run. The pipeline status should be set to success since both A and B are skipped 

# Actual Behavior
Task A is skipped due to condition failure and Task B is also skipped due to it being dependent on a condition failure. But the pipeline status is never updated from `Running` to `Successful`

# Steps to Reproduce the Problem

1. Run this pipeline: https://gist.github.com/dibyom/761199a1af98f435951fe1c8c2c8a08c
2. Run `kubectl get prs -o yaml` to see the status is not updated properly even after the first task is skipped.
3.

# Additional Info

/kind bug
/assign

**Comment by vdemeester** [comment]
@dibyom adding this to 0.6 milestone as it will ship conditionals :angel:
