### ISSUE TITLE
cannnot run the example

### ISSUE THREAD

**Issue by MemorySpring** [tektoncd/pipeline#1175]
# Expected Behavior
 run success
# Actual Behavior

invalid input params: param types don't match the user-specified type: [pathToDockerFile pathToContext]

# Steps to Reproduce the Problem

1.compile the controller
2.start controller 
```
./tektonController  --kubeconfig=/root/.kube/config -git-image=tekton/git-init-4874978a9786b6625dd8b6ef2a21aa70 -creds-image=tekton/creds-init-c761f275af7b3d8bea9d50cc6cb0106f  -nop-image=tekton/nop-8eac7c133edad5df719dc37b36b62482 -bash-noop-image=tekton/bash-e1b682803c23c6bfb91968c476bcb2ec -gsutil-image=tekton/gsutil-ade3fdebb791c88e47d4458ec641d9a2 -entrypoint-image=tekton/entrypoint-bff0a22da108bc2f16c818c97641a296 -imagedigest-exporter-image=github.com/tektoncd/pipeline/cmd/imagedigestexporter -pr-image=github.com/tektoncd/pipeline/cmd/pullrequest-init
```
3. kubectl apply -f example/pipelineruns/pipelinerun.yaml

# Additional Info

**Comment by vrutkovs** [comment]
Example params don't have `type: string` specified, so the validation error is misleading

**Comment by vdemeester** [comment]
@MemorySpring does the webhook run and is registered on the cluster you are targeting ?

/kind bug

**Comment by vdemeester** [comment]
As this issue stalled, I'll go ahead and close it. @MemorySpring feel free to comment if this is still an issue

/close
