### ISSUE TITLE
Task Retry Interval

### ISSUE THREAD

**Issue by tylerauerbeck** [tektoncd/pipeline#1209]
# Expected Behavior
I would like to define a task to retry X number of times, but to have a cooldown period of Y seconds between retries. 

# Actual Behavior
I currently haven't found any documentation that shows that this is possible. I would like to know if this is possible.

# Steps to Reproduce the Problem
N/A

**Comment by sbwsg** [comment]
I don't believe we have cool down support for retries. There are manual ways of injecting one if you wrap your step command in a bash script with a `sleep` but it would be hacky.

Could you add a description of the practical use case for this?  What specific purpose would the cool down period serve?  Is this related to a rate-limited API in some way?

**Comment by rvandegrift** [comment]
@sbwsg I'd like to have this for cases when external resources aren't ready yet, and where the required delay isn't well-defined.  Here's the use-case:

We use tekton pipelines to manage deployments into GCP.  GCP requires enabling APIs before they can be used.  But the API enabling behavior is eventually-consistent - even after GCP thinks the enabling is done, it's common to get 403 errors for a few minutes.

We can't use `retries` with a delay - in most cases, we'll probably just get the same failure for all of the attempts.

We could implement our own sleep as suggested above, but then it's silly to use `retries` at all - our retry + backoff lgoic would be split between two locations.  This is too difficult to troubleshoot and maintain.

We could implement retry + backoff in each our tasks, but that's kind of a bummer.  A workflow engine should be able to do that for us.

We don't need exponential backoff for this case - the APIs take long enough that we're happy to wait 30-60s between attempts.  But I suspect it'd be valuable for others, and it would meet our use case.

**Comment by bobcatfish** [comment]
This seems like a reasonable addition to our retry logic - anyone interested in drafting an initial TEP (https://github.com/tektoncd/community/tree/master/teps) e.g. with just the problem description?

/remove-lifecycle rotten
/remove-lifecycle stale

**Comment by tylerauerbeck** [comment]
@bobcatfish I can take a look at getting this started.

**Comment by rporres** [comment]
A very easy way to mitigate this would be to expose the retry number to the task so that implementing growing timeouts is trivial.

**Comment by sbwsg** [comment]
Retry variables were just merged in the past week and should be part of the 0.25 release.  Here are the docs for those vars in latest `main`: https://github.com/tektoncd/pipeline/blob/main/docs/pipelines.md#using-the-retries-and-retry-count-variable-substitutions

**Comment by rporres** [comment]
thx, @sbwsg
