### ISSUE TITLE
The Pipeline tutorial fails with error

### ISSUE THREAD

**Issue by moficodes** [tektoncd/pipeline#1211]
# Expected Behavior
Push image and create deployment
# Actual Behavior
Taskrun fails with
```
Error: asked to process document index 1 but there are only 1 document(s)
```
# Steps to Reproduce the Problem
Run through the pipeline deployment.

# Additional Info
Ran on kubernetes 1.15

# Fix
The issue is that the the `skaffold` folder `deployment.yaml` removed the service yaml from the file. 
https://github.com/GoogleContainerTools/skaffold/commit/3f93642deee42e3ad3dfab741fec88850f14a85b#diff-93aba9ab4664919e9d1c519f6798bf06

So the file has only one document and setting `yqArg` to `-d1` tries to access document 1 instead of 0 which does not exist. I made the change in my fork. Will be Making a PR

**Comment by vdemeester** [comment]
#1212 being merged, I think we can close this issue.
