### ISSUE TITLE
Change serviceAccount to serviceAccountName to be consistent with k8s

### ISSUE THREAD

**Issue by EliZucker** [tektoncd/pipeline#1219]
The `serviceAccount` field name should probably be renamed to `serviceAccountName` to match more closely with the normal k8s API. See `serviceAccountName` under pod [here](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.12/). 

This stems from @bobcatfish 's comment here: https://github.com/tektoncd/triggers/pull/63/files#r314863023

> ugh but it's called `serviceAccountName` in the rest of kubernetes isn't it :S
> 
> ![image](https://user-images.githubusercontent.com/432502/63193455-85afb880-c03b-11e9-92d0-327185497810.png)
> 
> maybe we should leave this and change pipelines after all

**Comment by vdemeester** [comment]
I'm ok with renaming it — I swear I saw `serviceAccountName` somewhere, at some point, in pipeline :angel: 
If we go for it, we need to do it in a backward compatible way :angel:

**Comment by bobcatfish** [comment]
Re-opening b/c afaik we made the backwards compatible change, but not the backwards incompatible one.
