### ISSUE TITLE
Create and maintain release upgrade docs

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#1222]
# Expected Behavior

If a person had an older version of Tekton pipelines installed, e.g. 0.5.2, and they want to upgrade to a newer version such as 0.6.0, they should be able to look at some docs that explain to them how to make any needed updates between the two (e.g. backwards incompatible changes, and backwards incompatible change warnings).

# Actual Behavior

Folks can see what exactly has changed in the release notes https://github.com/tektoncd/pipeline/releases but it still may not be clear what action they should take.

For example, for https://github.com/tektoncd/pipeline/releases/tag/v0.6.0  folks should be taking actions such as:

- Updating uses of `affinity`, etc. with `podTemplate`
- Keeping an eye out for errors resulting from accidentally including unknown fields
- etc.

(But with more detail than that!) 

# Additional Info

We should try to accumulate these docs as we go vs. making the person doing the release add them all at once. We may want to start keeping a running release notes doc in the repo and when we encounter backwards incompatible or soon to be incompatible changes, folks should update those docs.

**Comment by bobcatfish** [comment]
I still think this is a good idea but maybe it makes sense to let it get auto closed if no one is able to engage?

**Comment by vdemeester** [comment]
Also, adding to this that, the operator would have *code* on this (aka upgrading from a version to a new one).

**Comment by bobcatfish** [comment]
Makes sense @vdemeester  - that's even better!

**Comment by bobcatfish** [comment]
I think we could let this go rotten and close if we feel like the docs we provide in the release notes are enough?
