### ISSUE TITLE
GCS resource "dir" field is confusing

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#1234]
# Expected Behavior

As much as possible it should be clear from the names of PipelineResource params what they do and what values they expect.

# Actual Behavior

The [GCS Resource `dir` param](https://github.com/tektoncd/pipeline/blob/master/docs/resources.md#gcs-storage-resource) basically tells the command that grabs the source whether it should grab the source recursively or not, but `dir` doesn't really convey that.

Also it can have literally any value (except ""), which is confusing.

# Additional Info

* `recursive` might be a better name
* Or can we find a way to drop this field entirely?
* Note also #238 is completely changing the PipelineResource spec, we should probably hold off on this until then, when we could make this a boolean field.

**Comment by bobcatfish** [comment]
Marking this as blocked by #238

**Comment by vdemeester** [comment]
@bobcatfish what is the status ? I guess it still is blocked on the PipelineResource design work :angel:
