### ISSUE TITLE
[Question] how to upload dev images to docker hub registry

### ISSUE THREAD

**Issue by gavinfish** [tektoncd/pipeline#1242]
# Expected Behavior

I set `KO_DOCKER_REPO` as my public docker hub registry instead of gcr. I want to install pipeline successfully with it.

# Actual Behavior

When I try to install pipeline with `ko apply -f config/`, it just throws error like `error processing import paths in "config/webhook.yaml": unsupported status code 401; body:`. I have already `docker login`, but it seems that it does not work.

# Steps to Reproduce the Problem

1. Change the `KO_DOCKER_REPO` to public docker registry
2. install pipeline

# Additional Info

**Comment by vdemeester** [comment]
@gavinfish few questions
1. is this still a problem ?
2. on which system are you experiencing that ?

If it's still a problem, I think it's a `ko` issue, most likely linked to docker creds-store :sweat_smile:

**Comment by vdemeester** [comment]
I am going to close this as it seem to have stall and is likely a `ko` + docker-hub issue.

/close
