### ISSUE TITLE
What should be the CRDs categories for Tekton ?

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/pipeline#1246]
As of today, Tekton's CRDs are using `tektoncd-pipeline` and `all` as categories. This means you can do `kubectl get all` or `kubectl get tektoncd-pipeline` and it will display those resources (and others if in the same categorie). For `all`, this might pose a problem if the user has not sufficient rights, see quote below.

>_The problem with this is that if you are operating under expectation that 'all' will only include the original core builtin resources from Kubernetes, if you are using 'oc' from a service account with a basic set of roles which only covers builtin resource types, then you start getting errors:
>
> Error from server (Forbidden): images.caching.internal.knative.dev is forbidden: User "system:serviceaccount:homeroom:portal-homeroom-user1" cannot list resource "images" in API group "caching.internal.knative.dev" in the namespace "portal-homeroom-user1-2"
> Error from server (Forbidden): clustertasks.tekton.dev is forbidden: User "system:serviceaccount:homeroom:portal-homeroom-user1" can not list resource "clustertasks" in API group "tekton.dev" at the cluster scope
>
> Can someone explain the rationale as to why knative/tekton resources are being shoved under the set of resources that 'all' returns when using 'oc get all'. It seems to go against the idea that these are optional resources for an operator that may not even be installed, they are not core builtin resources.

kubectl get all *or* oc get all displays all resources that are in the "all" category.

There used to be a small "best practice" doc on when to add resources to all or not (see https://github.com/thtanaka/kubernetes/blob/master/docs/devel/kubectl-conventions.md#rules-for-extending-special-resource-alias---all) ; which were
- No cluster scoped resources
- No namespace admin level resources (limits, quota, policy, authorization rules)
- No resources that are potentially unrecoverable (secrets and pvc)
- Resources that are considered "similar" to #3 should be grouped the same (configmaps)

Somehow, I can't find this document anymore. I don't think the expectation was "only original core builtin", as a lot of CRDs are adding themselves to "all" (part of istio, …).

That said, I understand that having those errors are not really user friendly. It might also make sense to groups some of those resources in other categories.

I wonder if we really need to have our CRDs adding to the `all` categorie or if we can remove that from the categories and use more *accurate* ones (like `ci`, `pipelines`, …) ?

/kind question

**Comment by GrahamDumpleton** [comment]
Worth also linking here is https://github.com/kubernetes/kubectl/issues/151#issuecomment-410306145

In this, core developers state the intention that `all` would not be extended any further to cover any other resource types. Presumably this is why in oart those guidelines for best practices may have disappeared. It was likely deemed as no longer being a best practice because of the issues including how it could cause around confusion of what `all` meant. It also causes issues as noted when users do not have the roles required to list resource types added by arbitrary operators.

**Comment by vdemeester** [comment]
@bobcatfish @skaegi @afrittoli @dlorenc @ImJasonH @abayer any thoughts on this ? :angel:

**Comment by siamaksade** [comment]
This has undesired consequences. For example when one wants to delete all resources from a single namespace:
```
$ oc delete all --all -n demo

pod "gogs-1-deploy" deleted
pod "gogs-1-fw7q9" deleted
replicationcontroller "gogs-1" deleted
service "gogs" deleted
deploymentconfig.apps.openshift.io "gogs" deleted
imagestream.image.openshift.io "gogs" deleted
clustertask.tekton.dev "buildah" deleted
clustertask.tekton.dev "buildah-v0-8-0" deleted
clustertask.tekton.dev "openshift-client" deleted
clustertask.tekton.dev "openshift-client-v0-8-0" deleted
clustertask.tekton.dev "s2i" deleted
clustertask.tekton.dev "s2i-go" deleted
clustertask.tekton.dev "s2i-go-v0-8-0" deleted
clustertask.tekton.dev "s2i-java-11" deleted
clustertask.tekton.dev "s2i-java-11-v0-8-0" deleted
clustertask.tekton.dev "s2i-java-8" deleted
clustertask.tekton.dev "s2i-java-8-v0-8-0" deleted
clustertask.tekton.dev "s2i-nodejs" deleted
clustertask.tekton.dev "s2i-nodejs-v0-8-0" deleted
clustertask.tekton.dev "s2i-python-3" deleted
clustertask.tekton.dev "s2i-python-3-v0-8-0" deleted
clustertask.tekton.dev "s2i-v0-8-0" deleted
```

It's certainly not expected that the cluster resources too get deleted as a result.
