### ISSUE TITLE
Seems like coverage reporter isn't reporting on all files

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#1248]
# Expected Behavior

Coverage reporting should include all coverage impacted by a PR.

# Actual Behavior

The coverage reports for #1227 [only included `default.go`](https://github.com/tektoncd/pipeline/pull/1227#issuecomment-523474433) but it looks like other files changed, test files - which presumably would increase coverage - and also files that should have their coverage measured, e.g. `pkg/apis/pipeline/v1alpha1/pipelinerun_defaults.go` 

# Steps to Reproduce the Problem

Not sure! Will take some experimenting and/or reading the coverage tool code to understand what's up.

# Additional Info

Alternatively migrate over to a tool like https://coveralls.io

**Comment by bobcatfish** [comment]
Might get fixed by https://github.com/tektoncd/pipeline/issues/1124 🤞 

If so we should file a bug that errors while running coverage might be causing files to get skipped?

**Comment by vdemeester** [comment]
@bobcatfish right, that's the case, when there is errors, the job is marked as green anyway (and it skips the report for that package)

**Comment by bobcatfish** [comment]
Seems like this is working now that we've addressed #1124, plz re-open if not!
