### ISSUE TITLE
[Report] Parameters to support the "Array type"  API compatibility 

### ISSUE THREAD

**Issue by hrishin** [tektoncd/pipeline#1249]
Recently we introduced the `Array type` support in `params` which is really good, however, broke the compatibility with existing API consumer. So existing `pipelines` tools around it (e.g. CLI) need some fix, in order to get it working with `tekton-pipelines v0.6.0`.

After upgrading to new pipeline version user could hit this issue with old CLI versions
```
Failed to list pipelines from pipeline-test namespace
Error:  v1alpha1.Pipeline.Spec: v1alpha1.PipelineSpec.Tasks: []v1alpha1.PipelineTask: v1alpha1.PipelineTask.Params: []v1alpha1.Param: v1alpha1.Param.Value.....
```

It fails while deserializing the `Pipeline/Task` payload in respective golang API structs because payload fields are differing now from struct's fields.

Wondering is there anyway going ahead we should support the both API's for a while and depreciate it over one or two release.

**Comment by dibyom** [comment]
@hrishin is this still an issue?

**Comment by hrishin** [comment]
@dibyom Its not an issue any more. We can close this issue, thank you for following up :bowing_man: 

However can we derive some rules or guideline to ensure API compatibility between different pipeline components.
