### ISSUE TITLE
Run CI's YAML tests as a `go test` instead of bash scripts

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/pipeline#1251]
# Expected Behavior

YAML tests can be run as part of a `go test` suite, maybe with their own build tag. Failures in the tests should be correctly highlighted in the log output / prow error highlighting.

# Actual Behavior

We currently run YAML tests through a series of bash scripts. Their failure isn't reported accurately by the log output / prow error highlighting - the integration suite will show "0 / 29 failures" but grepping through the log output will indicate that the YAML tests failed or did not complete.

# Steps to Reproduce the Problem

1. Make a PR against Tekton Pipelines
2. Wait for the integration suite to fail
3. Grep through the integration logs for "YAML" and find errors

**Comment by thomaschandler** [comment]
I'd like to work on this! This will be my first contribution, so it will take me some time to ramp up!

**Comment by bobcatfish** [comment]
yaaaaaassss!!!!

![image](https://user-images.githubusercontent.com/432502/85412064-2d88f300-b537-11ea-9b11-93b8ad3adce2.png)

Thanks again for this @thomaschandler and for your patience with me duplicating your efforts and the review being prolonged. Really excited to have this in!!!
