### ISSUE TITLE
Feature Request: ClusterConditions

### ISSUE THREAD

**Issue by dibyom** [tektoncd/pipeline#1266]
Currently, `Condition` type is scoped to a namespace. It might be useful to have a `ClusterCondition` type similar to the cluster tasks that we have so that it is easy to share conditions.

From slack thread: https://tektoncd.slack.com/archives/CJ62C1555/p1567480976102300

**Comment by chengjingtao** [comment]
+1
I think namespaced  resource will be treated as resource of one tenant and  cluster scoped resource will be treated as global resources that could be used by all tenants.

We have a CICD product that allow to orchestrate pipeline from UI, and users could complete orchestration by draging the task. We will list all tasks in tenants namespaces's task and all tasks in cluster scope.

In the same way, we'd like to provide `conditions` in UI to help users orchestrating pipeline better.
such as `is-branch-of`, `is-environment-of` and so on.  We will init these built-in `conditions` and  share to all tenants.
For a specific tenant， he could customize his `conditions` in tenant's namespace.

So, I think we could provide `ClusterCondition` to share conditions easily.

**Comment by arzarif** [comment]
@dibyom 

Would it make sense to extend the scope of this request to include something like `ClusterPipelines`? The justification for such an object would be similar to what @chengjingtao described above.
