### ISSUE TITLE
PullRequestResource resource usage

### ISSUE THREAD

**Issue by hrishin** [tektoncd/pipeline#1275]
Looks like users are not able to understand how to use the `PullRequestResource` with secrete configuration. 
Maybe it's a bit confusing with respect to documentation.

**Comment by vincent-pli** [comment]
@hrishin 
Could you supply some example for use `PullRequest Resource` as output, I means update PR status on Github.

**Comment by hrishin** [comment]
@vincent-pli that sounds nice idea. Just wondering where shall we add the example?
Because [example](https://github.com/tektoncd/pipeline/tree/master/examples) `Task` has to pass the CI integration and not sure how to keep the `Github` creds.

**Comment by hrishin** [comment]
A better way we can address it in the followup PR? @vincent-pli @sbwsg

**Comment by sbwsg** [comment]
If a working example is required I'd personally tackle it in a separate PR from #1276. Seems like it's going to need more thought on how exactly to make that work with the YAML tests.

**Comment by hrishin** [comment]
@sbwsg :+1:
