### ISSUE TITLE
Warn about upcoming removal of git outputs

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#1283]
In https://github.com/tektoncd/pipeline/pull/1109  we will remove support for git outputs. We may add support via https://github.com/tektoncd/pipeline/issues/1280 in the same release but even if we do, the functionality of a git output will be radically different from what it is today. We should include a warning in 1 release, via both release notes and via a warning logged by the controller whenever git is used as an output.

**Comment by vdemeester** [comment]
@bobcatfish @dlorenc what is the status for this one ?

/kind api
/area release

**Comment by bobcatfish** [comment]
Looks like the warning was added in https://github.com/tektoncd/pipeline/pull/1310 !
