### ISSUE TITLE
Remove automatic PVC creation

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#1284]
# Expected Behavior

Once we have #1062, users can use the Volume resource whenever they want to use a PVC. We should no longer create and link PVCs for them.

# Actual Behavior

Today whenever an output of one task is linked to an input, we use a volume to share the data between them. Also we create PVCs even when they are not needed, and TaskRuns that are created by PipelineRuns will expect their existence (See #937)

# Additional Info

This will be a backwards incompatible change.

**Comment by bobcatfish** [comment]
(note the volume resource MUST be added before we can remove this)

**Comment by afrittoli** [comment]
Depends-on on what we decide to do with pipeline resources. Removing the priority label for now

**Comment by bobcatfish** [comment]
Closing this seems fair - #1673 should result in us deciding if this is the way to go or not (e.g. do we completely remove this functionality)
