### ISSUE TITLE
Enable PipelineRuns to run multiple Pipelines

### ISSUE THREAD

**Issue by vtereso** [tektoncd/pipeline#1292]
To await the completion of multiple `PipelineRuns` (e.g. multiple `PipelineRun` created from an incoming event), these runs must be uniquely identified (e.g. a label) and then presumably another `PipelineRun` has to handle this. As an alternative and since `PipelineRun` have parameters (not reusable), perhaps allowing multiple `Pipeline` within a `PipelineRun` could be a good idea?

**Comment by vtereso** [comment]
The [notifications proposal](https://docs.google.com/document/d/1ehhGngn2ulnjYX0HUxSyhQGAvcbabSa27UZs3RvZWwU/edit#) probably overlaps this.

**Comment by dibyom** [comment]
Somewhat related to allowing pipelines to trigger other pipelines/named branches that we discussed in today's Beta/Flow control call @skaegi @pritidesai @afrittoli
