### ISSUE TITLE
Dogfood fetching logs from tekton pipelines that triggered by Prow

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/pipeline#1296]
# Expected Behavior

Logs from pipeline runs that are triggered by Prow should be easily reachable by contributors creating PRs against Tekton Pipelines.

# Actual Behavior

Currently the logs are not available for pipeline runs that kicked off by Prow in reaction to PRs.

**Comment by vdemeester** [comment]
@sbwsg I think this is more or less fixed now, right ?

**Comment by sbwsg** [comment]
yeah i think so!
