### ISSUE TITLE
MutatingAdmissionWebhook is not working on OpenShift 3.11

### ISSUE THREAD

**Issue by akihikokuroda** [tektoncd/pipeline#1298]
# Expected Behavior

The type of the Tekton param default is `string`.  So the param type is **optional**.  The mutatingadmissionwebhook set the default type when the custom resource (e.g. task) is created with missing default values.

# Actual Behavior
The taskrun for the task that has some params with unspecified type fails on OpenShift 3.11.  The error is:

`invalid input params: param types don''t match the user-specified
        type: [pathToDockerFile pathToContext]`

The MutatingAdmissionWebhook in the tekton-pipelines-webhook is not called at all on OpenShift 3.11.  So the default values are not set.  Here is some OpenShift system info:

```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-08-26T18:51:37Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

```
```
#kubectl api-versions
admissionregistration.k8s.io/v1beta1
apiextensions.k8s.io/v1beta1
apiregistration.k8s.io/v1
apiregistration.k8s.io/v1beta1
apps.openshift.io/v1
apps/v1
apps/v1beta1
apps/v1beta2
authentication.k8s.io/v1
authentication.k8s.io/v1beta1
authorization.k8s.io/v1
authorization.k8s.io/v1beta1
authorization.openshift.io/v1
autoscaling/v1
autoscaling/v2beta1
batch/v1
batch/v1beta1
build.openshift.io/v1
caching.internal.knative.dev/v1alpha1
certificates.k8s.io/v1beta1
events.k8s.io/v1beta1
extensions/v1beta1
image.openshift.io/v1
metrics.k8s.io/v1beta1
monitoring.coreos.com/v1
network.openshift.io/v1
networking.k8s.io/v1
oauth.openshift.io/v1
policy/v1beta1
project.openshift.io/v1
quota.openshift.io/v1
rbac.authorization.k8s.io/v1
rbac.authorization.k8s.io/v1beta1
route.openshift.io/v1
scheduling.k8s.io/v1beta1
security.openshift.io/v1
servicecatalog.k8s.io/v1beta1
storage.k8s.io/v1
storage.k8s.io/v1beta1
tekton.dev/v1alpha1
template.openshift.io/v1
user.openshift.io/v1
v1 

```

# Steps to Reproduce the Problem

1. clone tekton pipeline on OpenShift 3.11 system
2. install tekton pipeline (I used the ko)
2. run the sample taskrun (kubectl apply -f eamples/taskruns/taskrun.yaml)
The taskrun fails with the error:
`invalid input params: param types don''t match the user-specified
        type: [pathToDockerFile pathToContext]`

# Additional Info

**Comment by abergmeier** [comment]
Is there a chance to extend Tektons CI with OpenShift? We've had quite a few problems in the past with that combination. Would be really good to have a vanilla Tekton tested continously against a vanilla OpenShift.

**Comment by vdemeester** [comment]
So, we need to document this, as : 
- Having MutatingAdmissionWebhook is required for Tekton to work.
- How to enable mutating webhook on OpenShift 3.11, and how to make Tekton work on OpenShift 3.11.

> Is there a chance to extend Tektons CI with OpenShift? We've had quite a few problems in the past with that combination. Would be really good to have a vanilla Tekton tested continously against a vanilla OpenShift.

We have that downstream, aka in [`openshift/tektoncd-pipeline`](https://github.com/tektoncd/pipeline), **but** we only support OpenShift 4.x.

**Comment by vdemeester** [comment]
With the recent move to Kubernetes 1.15 being the lowest version supported, Tekton officially can't run on OpenShift 3.11 (starting at 0.11 release of Tekton), meaning OpenShift 3.11 is officially not supported by Tekton.

/close
