### ISSUE TITLE
Create a buildcop rotation for Tekton Pipelines

### ISSUE THREAD

**Issue by dibyom** [tektoncd/pipeline#1301]
We should have have a regular rotation of folks that take a look at incoming issues, PRs, build failures.

I wrote up a draft runbook here: https://docs.google.com/document/d/1QJV0z2bMXdz_BZOkBwfxIP1BiktUb8c1lcifwqxF5wg/edit#heading=h.6fsxjbh35nu5

Once we have some agreement, we can take the runbook and put it in the repo.

**Comment by vdemeester** [comment]
It's in place (docs is available [here](https://docs.google.com/document/d/1kUzH8SV4coOabXLntPA1QI01lbad3Y1wP5BVyh4qzmk/edit?folder=0AANVzYPs_PItUk9PVA#heading=h.5tf3nt10c89x))
/close
