### ISSUE TITLE
Can't rerun existing completed taskruns or delete completed taskruns automatically

### ISSUE THREAD

**Issue by anxinyf** [tektoncd/pipeline#1302]
# Expected Behavior
There can be some fields that can automatically delete taskruns or completed pods if necessary.

If you don't want to delete existing succeeded taskruns, please allow me to rerun the same name of taskrun, like kubectl apply which can configure the same Deployment and the pod will rerun.

# Actual Behavior
At present, when a taskrun is succeeded and the related pod is completed, they have not been deleted and cannot be re-run. 

Sure, there's other way to delete taskrun and pod, such as kubectl delete, but there may be so many existing completed taskruns to rerun. To do so, first , i have to delete the exising taskruns and pods, then rerun. Even if I only delete related pod, I can't rerun taskRun.

# Steps to Reproduce the Problem

1. When pod is completed, i rerun "kubectl apply -f taskrun.yaml", pod cannot rerun.
2. Delete pod but not related taskrun, apply taskrun.yaml, pod also cannot rerun.
3. Delete taskrun(of course, pod will be deleted), apply taskrun.yaml, pod can rerun.
4. Maybe PipelineRun is same with taskRun.

**Comment by anxinyf** [comment]
@vdemeester Would Pipeline or Operator like to design some fields used in yaml which means that succeeded taskruns can be deleted automatically after ttl time , or they can be deleted in batches?

**Comment by anxinyf** [comment]
see [add taskrun_expired and pipelinerun_expired for deleting taskRuns or pipelineRuns automatically](https://github.com/tektoncd/pipeline/compare/master...anxinyf:master)

**Comment by jlewi** [comment]
In case its helpful here are some links to how this problem has been solved for other resources

* argoproj/argo/issues/911 - TTL for GC'ing Argo workflows
* kubernetes/kubernetes#64470 - Discussion about GC'ing Kubernetes objects and a link to a proposal to solve it in a generic way.
