### ISSUE TITLE
Reserve "tekton/" folder in taskrun filesystem

### ISSUE THREAD

**Issue by dibyom** [tektoncd/pipeline#1304]
We should consider reserving the `tekton/` folder in the taskrun filesystem and perhaps even move stuff from the current `builder/` folder to `tekton/`. 
The tekton folder could contain internal tools as well as things like the proposed JSON file containing the [pipelinerun context](https://docs.google.com/document/d/1eJBb2VHuSTbrIWfPE3TGdRRfdbJsRCOBIqfTwx9M3H8/edit#) and any other filesystem based standards we add in the future

 @ahpook [pointed](https://docs.google.com/document/d/1eJBb2VHuSTbrIWfPE3TGdRRfdbJsRCOBIqfTwx9M3H8/edit?disco=AAAADn5iEJ0) out that Github actions does something similar by reserving the /github folder i.e. the `/github/workflow/event.json` contains the request payload.

**Comment by bobcatfish** [comment]
I really like this idea!!

(related: #1030 )

**Comment by ImJasonH** [comment]
+1000

We could validate that requested TaskRuns don't request any volumeMounts over that path.

**Comment by vdemeester** [comment]
I thought I commented on this issues but I only added *reactions* :stuck_out_tongue: 
I am also +:100: on this idea ! And validating it on the `TaskRun` too

**Comment by abayer** [comment]
+1 from me!

**Comment by bobcatfish** [comment]
+1 from me but might want to do some of this across 2 releases (i.e. support /tekton and /builder for some things if possible?) b/c of features such as https://github.com/tektoncd/pipeline/blob/master/docs/resources.md#surfacing-the-image-digest-built-in-a-task and as @ImJasonH pointed out, many examples using /builder

But also not totally opposed to just going for it, as pointed out in #1030 (which i think this will basically fix!!) this isn't in our [api compatibility policy](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) anyway

**Comment by vdemeester** [comment]
First step is #1440
@dibyom @ImJasonH should I assign one of you on this one ? :stuck_out_tongue:

**Comment by bobcatfish** [comment]
Update from @dibyom : @ImJasonH is waiting to finish his refactoring of pod logic before merging this one
