### ISSUE TITLE
Consider Go module adoption for beta

### ISSUE THREAD

**Issue by skaegi** [tektoncd/pipeline#1315]
I'm looking at versioning for the beta and wondering if we should maybe use the opportunity to move to Go modules before we have to support semantic package versions forever.

In particular I'd like to see if we can do a one time change to avoid having versions in our imports like ... /pkg/apis/pipeline/v1alpha1 and instead just have /pkg/apis/pipeline and then rely on module versioning.

**Comment by skaegi** [comment]
Similar issue in knative serving -- https://github.com/knative/serving/issues/3368
Kubernetes KEP -- https://github.com/kubernetes/enhancements/blob/master/keps/sig-architecture/2019-03-19-go-modules.md

**Comment by khrm** [comment]
When you vendor, you don't import v1alpha1,  you vendor by tektoncd pipeline version.
So v1alpha1 isn't the version of tektoncd/pipeline.
In cli, we would import pipeline like github.com/tektoncd/pipeline v0.8.0 which isn't solving v1alpha1/2 which is inside the package.
Then in case of go modules, we would use it like import "github.com/tektoncd/pipeline/v0.8.0"

**Comment by bobcatfish** [comment]
note @wlynch is doing a lot of the ground work for this in https://github.com/tektoncd/triggers/pull/180
