### ISSUE TITLE
allow environment variables to be added to git-init containers

### ISSUE THREAD

**Issue by jstrachan** [tektoncd/pipeline#1328]
# Expected Behavior

Provide some way (e.g. a ConfigMap?) to be able to add additional environment variables to the `git-init` container step

# Actual Behavior

Some folks are evaluating Jenkins X + tekton on an internal gitlab which doesn't have a proper public certificate and the first git-init step generated by tekton is failing with `SSL certificate problem: unable to get local issuer certificate` errors.

It would be good to be able to configure tekton to add an environment variable to this step - e.g. 
`GIT_SSL_NO_VERIFY=true`. From noodling the code I don't see a way to add environment variables without hacking the go source.

I guess a workaround for now is to build a custom `git-init` image with different env vars inside; but would be nice to make this more easily configurable

**Comment by vdemeester** [comment]
/kind feature

So this is doable using `StepTemplate` in a `Task` but I don't think it applies to internal init container…

**Comment by abayer** [comment]
The git clone step isn't run as an init container, but it is an internal step added by the git resource.

**Comment by berbiera** [comment]
Hi 
Any update on that feature ? Is that feasible to integrate the variable ? We are waiting on that feature. 
Thanks guys

**Comment by ravenchilde** [comment]
Also waiting on this, our Corp uses our own CA to sign the Git repo certificate. Our machines and servers all have this CA loaded, but I can't find a reasonable way to make Jenkins-X work with this.

**Comment by sbwsg** [comment]
For sslVerify specifically we already have that parameterized.  It's the `sslVerify` param mentioned here: https://github.com/tektoncd/pipeline/blob/master/docs/resources.md#git-resource

When `sslVerify` is set to false the git resource will tell `git` to ignore certificate errors.

**Comment by ravenchilde** [comment]
> For sslVerify specifically we already have that parameterized. It's the `sslVerify` param mentioned here: https://github.com/tektoncd/pipeline/blob/master/docs/resources.md#git-resource
> 
> When `sslVerify` is set to false the git resource will tell `git` to ignore certificate errors.

Fantastic news... now... can I figure out where to configure that in Jenkins-X... 🤓

**Comment by sbwsg** [comment]
I'm going to close this as fixed.  I believe it's very closely related to #1663 which is now supported thanks to @pritidesai !
