### ISSUE TITLE
[feature request]Delete pipelinerun and taskrun under 'complete' state using different strategies automatically

### ISSUE THREAD

**Issue by MartinForReal** [tektoncd/pipeline#1334]
# Expected Behavior
Delete pipelinerun and taskrun under 'complete' state using different strategies automatically

# Actual Behavior
pipelinerun and taskrun are not deleted until system admin delete them manually

# Additional Info

related issue: #453  https://github.com/kubernetes/enhancements/issues/592

**Comment by MartinForReal** [comment]
related issue: #1302 , both need to delete pipeline run and task run automatically.

**Comment by vdemeester** [comment]
@MartinForReal I feel this is a duplicate of #1302, should we close this one ?

**Comment by MartinForReal** [comment]
I think this is a little bit different because I want to strengthen that we need different deleting strategies. such as keep a certain number of run records for a certain task.

**Comment by k** [comment]
Whats the status of this?
