### ISSUE TITLE
Export tags of an image resouce

### ISSUE THREAD

**Issue by nlewo** [tektoncd/pipeline#1355]
# Expected Behavior
I would like to have a list of tags exported by the `imageDigestExporter` in the image resource.
I generate a tag at image build time which depends of the build requires, and I would like to reuse this tag in some other tasks.

# Actual Behavior
The image resource only exports a `name` and a `digest`.

# Additional info
The `index.json` file contains the `repoTags` attribute which can contains all tags associated to an image. The idea would be to export this attribute to expose it as an image resource attribute.

**Comment by bobcatfish** [comment]
Note you can now do this kind of thing with the results feature, e.g. like the Kaniko task: https://github.com/tektoncd/catalog/tree/master/task/kaniko/0.1
