### ISSUE TITLE
Beta documentation: write up alternatives to PipelineResources if they remain Alpha

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/pipeline#1369]
# Expected Behavior

Clearly documented approach to passing files, folders, docker images, cluster information, auth information, repo information etc etc without relying on PipelineResources.

# Actual Behavior

At the moment our docs assume that PipelineResources are "the answer" to modelling meaningful resources external to the CI/CD system. In the most recent PipelineResource working group we landed on the idea of keeping PipelineResources as Alpha when the rest of the Tekton resources move to Beta. So with that approach we'll need to make sure that our docs correctly reflect the "right" way to work with external resources.

**Comment by anneqm** [comment]
@vdemeester can we add a must have for Beta to this issue?

**Comment by bobcatfish** [comment]
@vdemeester @afrittoli @dibyom and I discussed today: at the very least we should have a doc explaining the current state and weighing pros and cons of how you do things with and without PipelineResources

**Comment by bobcatfish** [comment]
Note we are also making progress with Task equivalents of PipelineResources in https://github.com/tektoncd/catalog/issues/95

**Comment by sbwsg** [comment]
First version of migration doc now exists: https://github.com/tektoncd/pipeline/blob/master/docs/migrating-v1alpha1-to-v1beta1.md
