### ISSUE TITLE
Allowing for actions to be taken in failure scenarios

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#1376]
I'm creating this as an Epic to generally cover being able to express behaviour that should occur in a Pipeline when some part of the Pipeline fails. At the moment we have Conditions in Pipelines, but afaik you can't express "if previous Task failed" as of yet b/c a Task failing will halt execution (correct me if I'm wrong @dibyom !).

And if a Task fails, any PipelineResource output actions that would have occurred will not happen (see #1149).

**Comment by vdemeester** [comment]
Allowing for actions to be taken in failure scenarios, we should support this with Resources *or* without, so having a way to say "this step needs to be run even if the previous step failed".

**Comment by bobcatfish** [comment]
I think @dibyom expressed a desire to work on this :D 🤞

**Comment by vdemeester** [comment]
Should #1684 and this issue be the same ? (or #1684 be one item of this epic?)

**Comment by sbwsg** [comment]
We should aim to get this functionality (in some form...) into 0.11, prior to the beta release going out.  This is so that people can give it a try and we can work out any bad wrinkles before the beta is cut.

**Comment by dibyom** [comment]
> Should #1684 and this issue be the same ? (or #1684 be one item of this epic?)

#1684 is one item in this epic

**Comment by bobcatfish** [comment]
Removed from milestone - @dibyom to create follow up issues for the work to implement the design :D

**Comment by gpaul** [comment]
I read through the comments and the design doc and I can't find a mention of how timeouts are handled.

My use case: I want to (a) collect task artifacts and (b) report status to github, using Finally tasks. One common reason for pipeline failure is timeout. In the case of a PipelineRun timing out, I would like to do both (a) and (b) once the individual non-final tasks have been stopped.

**Comment by gpaul** [comment]
Ping?

The design doc says:

> Similarly, final tasks can be configured to time out and follow the same default as standard tasks. Default Task and Pipeline Timeout is 60 minutes, documented here. 

I'm still not clear: will my finally task run if my pipelinerun times out after 1h?

**Comment by bobcatfish** [comment]
As mentioned in #1684: I feel like it's fair to consider this closed now that we have [finally](https://github.com/tektoncd/pipeline/blob/master/docs/pipelines.md#adding-finally-to-the-pipeline), tho there are more features to add, and to get the complete set of flexibility someone might want, i think we need to add in #2134 as well
