### ISSUE TITLE
Investigate use of an admission webhook to ease move to beta

### ISSUE THREAD

**Issue by skaegi** [tektoncd/pipeline#1379]
When we go beta we're going to end up with a ton of pre-existing Tekton resources that use `apiVersion: tekton.dev/v1alpha1` where-as our stored versions will now be using `apiVersion: tekton.dev/v1beta1` or similar.

One practice to help ease migration is to use a [MutatingAdmissionWebhook](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#mutatingadmissionwebhook). We should investigate adding one along with a battery of unit tests to validate the handling of `apiVersion` changes and other simple mutations we want to support.

**Comment by vdemeester** [comment]
@skaegi note that we already are using a `MutatingAdmissionWebhook` and we have a slight mechanisms to do conversion… but yeah we need to enhance that and have confidence on it (hence the battery of tests :stuck_out_tongue_closed_eyes:)

**Comment by vdemeester** [comment]
Small update on this: as #1529 shows (if people are not completely dead :skull:  after reading the PR :joy_cat:) that it is definitely possible (and not that hard, thanks to `knative/pkg` code :angel:). It comes with a few "gotchas", but it is doable.

@bobcatfish @skaegi Should we close this issue (as we know what is the status) and focus on #1526 ?
