### ISSUE TITLE
Tutorial recommendation to use Docker Edge for suitable Kubernetes level out of date.

### ISSUE THREAD

**Issue by hhellyer** [tektoncd/pipeline#1384]
The tutorial documentation at:

https://github.com/tektoncd/pipeline/blob/master/docs/tutorial.md#known-good-configuration

suggests installing Docker Edge is required to get a suitable level of Kubernetes on Docker, Kubernetes v1.11 or higher. The latest Docker Stable releases now use Kubernetes v1.14. Additionally I was able to complete the tutorial using the latest version of stable docker installed on my Mac, which I confirmed was using v1.14.6.

The recommendation to use Edge can probably be removed now making it easier for interested users to try out Tekton.

# Additional Info
The release notes for Docker confirm the current Kubernetes levels in stable:
https://docs.docker.com/ee/desktop/release-notes/
https://docs.docker.com/docker-for-mac/release-notes/
https://docs.docker.com/docker-for-windows/release-notes/

**Comment by vdemeester** [comment]
#1385 is merged, we can close :wink: 
/close
