### ISSUE TITLE
Support for TaskRuns that fail but do not then fail the PipelineRun

### ISSUE THREAD

**Issue by skaegi** [tektoncd/pipeline#1394]
It's not uncommon for a development pipeline to run a set of Test Tasks where some might fail however we still might want to promote the build to a manual staging/testing environment. Existing CI/CD tools handle this with a "WARN" or similar state.

**Comment by skaegi** [comment]
Also see https://github.com/tektoncd/pipeline/issues/1376

**Comment by dibyom** [comment]
Related: https://github.com/tektoncd/pipeline/issues/1023

**Comment by dibyom** [comment]
@skaegi can we close this and use #1376 for tracking this feature?

**Comment by vdemeester** [comment]
I think so, let's close it :upside_down_face: 
/close
