### ISSUE TITLE
Users who specify a commitish of "master" may get unexpected behavior

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#1401]
# Expected Behavior

If a user provides a PipelineResource of type git to a PipelineRun and specifies `master` as the commitish, they probably meant that they want the entire Pipeline to run against the lastest commit at the time the PipelineRun starts.

# Actual Behavior

What will actually happen is that every Task will re-fetch master when it executes, meaning that every Task in the Pipeline could end up using a different commit.

# Additional Info

A couple ideas:
- Initialize PipelineResources in some way a the beginning of a PipelineRun
- Do not allow the git PipelineResource to specify master (probably a bad idea)
- Just let it be but make it very clear in our docs and intros what will happen
- ?

In #1392 we add the ability for the PipelineResource to at least record what commit it was used with.

**Comment by vdemeester** [comment]
This needs to get fixed before beta, and should be resolve, by not using `PipelineResource` as of today or with https://github.com/tektoncd/pipeline/issues/1438, or with a re-design of PipelineResource, or a combinaison of those :stuck_out_tongue:

**Comment by bobcatfish** [comment]
TODO before beta release:
1. Document this clearly
2. Make sure our examples do not use master (since it would be a bad practice)

**Comment by bobcatfish** [comment]
With #1673 this has completely changed, going forward folks will likely be using Tasks to checkout from git so:

1. it will be explicit when the pull is happening
2. the results will show the actual commit that was pulled
