### ISSUE TITLE
RFP: Add a health endpoint

### ISSUE THREAD

**Issue by cmoulliard** [tektoncd/pipeline#1419]
## Request for proposal

Currently, if something wrong is happening during the start of the `tekton-pipelines-controller`, then the pod will continue to run even if the pod is not able to process the tasks, taskruns, ... CRs.

This problem could occur, if for any reasons, the k8s go client used by the controller can't access the K8s Api server
```
E1003 15:42:56.573743       1 reflector.go:134]
github.com/tektoncd/pipeline/pkg/client/informers/externalversions/factory.go:114:
Failed to list *v1alpha1.PipelineRun:
Get https://172.30.0.1:443/apis/tekton.dev/v1alpha1/pipelineruns?
limit=500&resourceVersion=0:
dial tcp 172.30.0.1:443: connect: network is unreachable
```

Such error should be trapped and the health endpoint exposed by the controller should report an error code or message in order let k8s to destroy the pod,....

**Comment by ImJasonH** [comment]
That's a great idea. Can you provide steps to reproduce this, so we can more easily get the controller into a state where it should report unhealthy? Ideally we could even make this an e2e test case.

**Comment by cmoulliard** [comment]
This is not reproducible using ocp3, minishift or minikube but if you deploy tekton using AWS + ocp4, you should see this error happening from time to time. We continue to get also this error using ocp3 cluster created with Ravello by RHTE Team
