### ISSUE TITLE
Git Pipeline Resources should allow depth to be specified

### ISSUE THREAD

**Issue by kav** [tektoncd/pipeline#1450]
# Expected Behavior
I can specify a git resource to be more than a shallow clone so I can use `git diff` and `git tag` to drive task behavior.

# Actual Behavior
Git resources are always shallow cloned

# Additional Info
Just to get a proposal on the table; I'd propose an optional `depth` parameter for git resources that matches (and wires to) the `git clone` parameter `--depth`

If that gets a few nods I'll start on a PR

For context `--depth` is documented here: https://git-scm.com/docs/git-clone#Documentation/git-clone.txt---depthltdepthgt

**Comment by nikhil-thomas** [comment]
@vdemeester i can work on this issue this weekend
could you assign this to me
