### ISSUE TITLE
Can we specify a nodeSelector for a given task ?

### ISSUE THREAD

**Issue by eddycharly** [tektoncd/pipeline#1454]
Let's say a task has to run on a specific node, is this possible to add a nodeSelector somewhere to ensure it is scheduled on the correct node ?

**Comment by vdemeester** [comment]
@eddycharly yes this is possible on the runtime types (`TaskRun` and `PipelineRun`), see [here](https://github.com/tektoncd/pipeline/blob/master/docs/taskruns.md#pod-template) or [here](https://github.com/tektoncd/pipeline/blob/master/docs/pipelineruns.md#pod-template).

I think we can close this issue then :angel:

**Comment by eddycharly** [comment]
@vdemeester 👍

**Comment by eddycharly** [comment]
@vdemeester one more question please, it's not yet possible to specify the node selector from the dashboard right ?

**Comment by vdemeester** [comment]
@eddycharly I don't know :sweat_smile: (cc @a-roberts)

**Comment by a-roberts** [comment]
Nah, it's not but it's a good feature request, I'll make an issue for it 👍

**Comment by eddycharly** [comment]
@vdemeester @a-roberts awesome, thanks !
