### ISSUE TITLE
Variable substitution and bracket notation for name encoding

### ISSUE THREAD

**Issue by skaegi** [tektoncd/pipeline#1463]
For Kubernetes names the set of allowable characters is ... digits (`0-9`), lower case letters (`a-z`),`-`, and `.`. We dereference with `$(params.param_name})` so if we have a param name or task name that contains `.` things can get weird (even if they happen to work in some cases).

The [Downward API](https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/#capabilities-of-the-downward-api) has a similar problem with `fieldRef` and handles it by always using bracket notation for name fields ... e.g. `$(params['parm_name'])`. Bracket notation solves the general problem however, I like the convenience of regular dot notation so think we should consider supporting both formats.

**Comment by dlorenc** [comment]
+1 on supporting both.

**Comment by bobcatfish** [comment]
sgtm!

**Comment by bobcatfish** [comment]
@skaegi just wanted to check in - we have this in our 0.10 milestone ~jan 17, do you think its reasonable to finish before then, and/or would you like someone else to work on this as well?

**Comment by skaegi** [comment]
Hopefully should have something this week on this.

**Comment by skaegi** [comment]
Also see https://github.com/tektoncd/triggers/issues/178

**Comment by skaegi** [comment]
[WIP] I was doing work on this here -- https://github.com/skaegi/pipeline/commits/parameterizable_validation
See https://github.com/skaegi/pipeline/commit/3db99e4b1f9f20bf9c27b9e6bcb79f74476f7014

I'll get back to this post-beta

**Comment by bobcatfish** [comment]
@skaegi @dlorenc do we feel strongly about this and want to re-open it?

**Comment by sbwsg** [comment]
Worth noting that there's a maybe more use-case-oriented issue covering similar ground here: https://github.com/tektoncd/pipeline/issues/2958

In that issue we're discussing adding context variables for all the annotations on tasks, pipelines, taskruns and pipelineruns.  Those annotation keys can include characters "/", ".", etc...  Dot-style gets a bit unwieldy and maybe difficult to unambiguously parse both for a human reader as well as a computer: `context.annotations.tekton.dev/pipelinerun-name`.

So, at least from my pov, I think we can safely keep this closed and lean on #2958 to set a syntax precedent.
