### ISSUE TITLE
Port knative-build's pkg/log functionality

### ISSUE THREAD

**Issue by poy** [tektoncd/pipeline#1468]
# Expected Behavior

Be able to stream logs from a Tekton `TaskRun` similar to how I could stream logs from a Knative-Build `Build`.

# Actual Behavior

No way to stream logs (via a library). The docs all suggest CLI options: https://github.com/tektoncd/pipeline/blob/master/docs/logs.md

# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info

**Comment by ImJasonH** [comment]
There used to be a package/binary for this in the Tekton repo, until https://github.com/tektoncd/pipeline/pull/1414

I think the tektoncd/cli repo should have a package you can use to stream logs from the pod, somewhere around https://github.com/tektoncd/cli/blob/master/pkg/cmd/taskrun/logs.go

**Comment by poy** [comment]
Ah perfect! I didn't think to look under the `cmd` package!

**Comment by vdemeester** [comment]
@ImJasonH :angel: we may want to extract that part (logs) from the `tektoncd/cli` project at some point and have it in `tektoncd/pipeline`
