### ISSUE TITLE
[Epic] Migrate from Build to Task

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#147]
## Expected Behavior
By the time we have something like an "official release" we should no longer be wrapping Builds, we should converge the projects in some way.

* BuildTemplates -> Tasks
* Builds -> TaskRuns

Possible futures:
- Fork Build, turn that into Task, leave Build in knative
- Completely replace Build with Task

## Actual Behavior
Currently when you create a TaskRun, it will start a Build and the Build controller will take care of executing it.

## Additional Info
~Should have this figured out before Knative 0.3 release in Q1 sometime. The 0.2 release is on Nov. 11.~ Now we are looking at 0.4 :sweat_smile:

**Comment by bobcatfish** [comment]
Continuing discussions with @ImJasonH who is co-ordinating with other knative/serving folks about the best ways to make these changes.

Meanwhile we can move forward with some of the work required, with the assumption that even if we continue to wrap `Build`, we don't want to expose that to users of `Task`.

**Comment by vbatts** [comment]
In the meantime, I'm personally looking at reusing build-template e.g. buildah for making taskrun HowTos.

**Comment by bobcatfish** [comment]
Related: proposal re. moving knative/build-pipelines https://github.com/knative/build/pull/569

**Comment by vdemeester** [comment]
I think we are good closing this one :angel: 

/close
