### ISSUE TITLE
Question: poll-based change detection for Git?

### ISSUE THREAD

**Issue by evgf** [tektoncd/pipeline#1489]
In a GitOps project, we are trying to implement the poll-based change detection of the Git Repo using Tekton. (We cannot fully rely on WebHooks since they offer no guaranteed delivery)
I scanned through the Tekton Pipeline / Trigger documentation but did not find any sample of this use case.
If this possible, without implementing our own status caching / change-detection?
If yes, could you point me to the right direction?

**Comment by evgf** [comment]
Thank you @dlorenc, what we miss is the change tracking logic like in ArgoCD or Jenkins.
Even with Triggers, I need to keep track of the commits already processed and not processed.
Do you know, if there is anything we can start with?

**Comment by bobcatfish** [comment]
I think it would make sense to have something like this! But I think it would make sense to add this feature to tektoncd/triggers instead - apologies for the delayed response @evgf but would you be open to creating an issue over there? :pray: 

+ @dibyom @wlynch

**Comment by bobcatfish** [comment]
I've opened https://github.com/tektoncd/triggers/issues/480 and am closing this for now.

**Comment by ngtuna** [comment]
Hi this issue hit me. Our system can't receive git webhook thus we need to rely on poll. Do you know the plan for poll-based support ? Any timeline/design made?
