### ISSUE TITLE
Question : does parameter interpolation support function ?

### ISSUE THREAD

**Issue by eddycharly** [tektoncd/pipeline#1490]
Is this possible to use some kind of functions in parameters interpolation ?
Simple things like `tolower` or `replace` are supported or doest it have to be done in bash or something else ?

**Comment by sbwsg** [comment]
There isn't any function support in interpolation. Currently any edits you need to make to the contents needs to happen in the command / args / script of the step.

**Comment by eddycharly** [comment]
@sbwsg thanks.
one more question, how can i retrieve the branch from a `PipelineResource` ? is something like this possible `$(inputs.resources.clone.branch)` ?

**Comment by sbwsg** [comment]
You can use `$(inputs.resources.clone.revision)` i think - this will be the branch / tag / commit SHA or ref that was cloned.

**Comment by eddycharly** [comment]
Just tried it, i have the commit hash in revision, but i guess it is because prow uses the commit hash when creating the `PipelineResource`.
I will have to check how to get the branch information from prow, not related to tekton.
Thanks

**Comment by afrittoli** [comment]
@eddycharly having a way to apply simple functions to parameters would be really handy, so I think we should keep this as a feature in the backlog. @skaegi is this something you started looking into?

**Comment by eddycharly** [comment]
I was about to close it but ok, let's keep it opened if it serves the backlog purpose.
