### ISSUE TITLE
Should evicted pods be retried?

### ISSUE THREAD

**Issue by abayer** [tektoncd/pipeline#1493]
This is as much a question as it is a bug report, so... =)

When a `TaskRun` pod gets deleted while it's running, it'll get automatically recreated, but `Evicted` `TaskRun` pods don't get recreated, so far as I can tell. Should we be handling eviction the same way we do deletion? In practice, they're analogous cases, so it feels like they should be handled in the same way, but I'm not 100% sure.

**Comment by kav** [comment]
I'm seeing this in the wild on a shared cluster and am definitely a yes

**Comment by vincent-pli** [comment]
I think it's definitely needed, but behavior for `Evicted` pod in kubernates seems not stable:
https://github.com/kubernetes/kubernetes/issues/88304
https://github.com/kubernetes/kubernetes/issues/55051

I have tried the case, but the `Evicted` pod has no `.Status.Reason` with `Evicted` value, but the official said it is.

Anybody hit the same issue?

**Comment by afrittoli** [comment]
@abayer @vincent-pli @kav any update on this? I would put this into the backlog for now, unless someone is hit hard by this and wants to step up and fix it?

**Comment by kav** [comment]
I've worked around it for the time being so it's not urgent for me
