### ISSUE TITLE
Why does pipeline bind a PVC when I run it

### ISSUE THREAD

**Issue by bibi520** [tektoncd/pipeline#1496]
![image](https://user-images.githubusercontent.com/42456284/67846479-42de8680-fb3c-11e9-8beb-fc94ca555f77.png)

1.this is my pipeline yaml

apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: demo-pipeline
spec:
  resources:
  - name: source-repo
    type: git
  - name: push-image
    type: image
  tasks:
   - name: skaffold-unit-tests
     taskRef:
       name: build-app
     resources:
       inputs:
       - name: java-demo
         resource: source-repo
       outputs:
       - name: builtImage
         resource: push-image

**Comment by bobcatfish** [comment]
Hey @bibi520 ! This is to support [the `from` syntax](https://github.com/tektoncd/pipeline/blob/master/docs/pipelines.md#from) which lets you provide data from one Task to another Task. There is some bugs such as #1007 which make it so this is always done, even if you don't need it :( but in #1076 we are trying to fix this and you shouldn't see unnecessary PVCs created by the time we go beta :crossed_fingers:

**Comment by bibi520** [comment]
OK   thank you
