### ISSUE TITLE
Inconsistent Types for PipelineRef and TaskRef

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/pipeline#1498]
While working with the Tekton API as part of the cli project, I was adding validation to the `tkn tr describe` and `tkn pr describe` commands to check whether the properties are present on taskrun and pipelinerun specs. For taskruns, I used a nil check to determine if the TaskRef is present. For pipelineruns, I had to used an empty string for PipelineRef.

I am wondering why TaskRef is defined as follows [here](https://github.com/tektoncd/pipeline/blob/fe47335b2dfad4e31e01e09b98fd157f8f84579d/pkg/apis/pipeline/v1alpha1/taskrun_types.go#L48):

TaskRef *TaskRef `json:"taskRef,omitempty"`

And why a different approach was taken with PipelineRef [here](https://github.com/tektoncd/pipeline/blob/fe47335b2dfad4e31e01e09b98fd157f8f84579d/pkg/apis/pipeline/v1alpha1/pipelinerun_types.go#L48):

PipelineRef PipelineRef `json:"pipelineRef,omitempty"`

What was the thought behind using the `*` operator for TaskRef whereas all other Refs do not?

**Comment by vdemeester** [comment]
Both pull-requests are merged, closing
/close
