### ISSUE TITLE
Support go modules

### ISSUE THREAD

**Issue by poy** [tektoncd/pipeline#1538]
# Expected Behavior
Repo uses go modules

# Actual Behavior
Repo uses dep

# Additional Info

Kubernetes has transitioned to go modules and the go community is pushing more things towards this. I think we should consider doing the same.

**Comment by vdemeester** [comment]
This is a duplicate of  #1315 more or less, we should keep only one of those issue

**Comment by bobcatfish** [comment]
@wlynch maybe we can close this issue? @vdemeester mentioned we might want to open another issue re. continuing to vendor or not but otherwise it seems like go module support is done? 🎉

**Comment by bobcatfish** [comment]
Current state:
- CI uses vendor/ dir and doesn't download (~50% faster than pulling)
- We support go modules, but you are still expected to keep the vendor dir in sync

We feel like this is okay for now

**Comment by bobcatfish** [comment]
https://github.com/tektoncd/pipeline/issues/2065 is continuing the vendor directory conversation, closing this issue.
