### ISSUE TITLE
Controller tries to pull down image

### ISSUE THREAD

**Issue by jpds** [tektoncd/pipeline#1539]
# Expected Behavior

Tekton should just launch the pods in a taskrun and let Kubernetes handle invalid images.

# Actual Behavior

I'm doing local dev on a pipeline, and I have a local docker image on the host I'm running Kubernetes on. The tekton controller tries to validate if this image exists against the main Docker repo:

```
$ kubectl describe taskrun
  ...
  Warning  BuildCreationFailed  71m   taskrun-controller  Failed to create build pod "build-docker-image-from-git-source-task-run": couldn't create redirected TaskSpec: failed to add entrypoint to steps of TaskRun build-docker-image-from-git-source-task-run: Failed to fetch remote image : Failed to get container image info from registry task-testing-image:1.0: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/task-testing-image Type:repository]]
```

Kubernetes launches the pod fine with:

```
kubectl run task-testing-image --image=task-testing-image:1.0
```

It's a little tedious that the controller tries to pull it down itself as this hampers local dev with private images.

**Comment by vdemeester** [comment]
@jpds I think this is similar to #1343, I'll submit a fix today :wink: 

/kind feature
/assign

**Comment by vdemeester** [comment]
@jpds actually it is not related to #1343 and it "can" work correctly (although it is tricky).

The entrypoint magic rewrite will query the image registry to get the default command from the image config **if the command is not specified in your step**. This means, if you want your task to work you need to specify the command you want to run on the step that uses `task-testing-image:1.0` :sweat_smile:.

**Comment by MarcusNoble** [comment]
I've managed to work around this issue by mounting the hosts docker config file into the controller using:

```
kubectl patch deployment tekton-pipelines-controller --patch '{"spec": {"template": {"spec": {"containers": [{"name": "tekton-pipelines-controller","volumeMounts": [{"mountPath": "/root/.docker/config.json","name": "docker-creds","subPath": "config.json"}]}],"volumes": [{"hostPath": {"path": "/var/lib/kubelet"},"name": "docker-creds"}]}}}}'
```

I'm not 100% sure if this works in all environments. We're running on EKS here. If this is a universal solution is it something that can be merged into the pipeline manifest?
