### ISSUE TITLE
Official Helm Chart

### ISSUE THREAD

**Issue by MLBMatt** [tektoncd/pipeline#1542]
I can't seem to find an official Tekton Pipelines helm chart. It looks like the JX team has their own implementation of it but it looks tuned to JX. Is there any plan (or one that currently exists) for an officially supported Helm chart?

**Comment by vdemeester** [comment]
There is not plan for an official helm chart that I know of. We are working on providing a operator (see [`tektoncd/operator`](https://github.com/tektoncd/operator)) for installation purpose.

That said, it might make sense to have one ?

/kind question

**Comment by eddycharly** [comment]
@MLBMatt i wrote an helm chart with pipeline and dashboard. My plan was to add triggers before making it public. 

I also wrote an helm chart for prow so that I can set up my full ci/cd solution from helm. 

It’s not official though, but I will be happy to contribute if there is some interest for it.

**Comment by eddycharly** [comment]
@MLBMatt i made the repo public, keep it mind it's still work in progress. Things are subject to change as i work on it.

https://github.com/eddycharly/helm-prow-tekton/tree/master/helm/tekton

**Comment by eddycharly** [comment]
@vdemeester i think having a helm chart is great to simplify installation for the end user. It is also useful for documenting how one can configure/customize the installation, while allowing to provide default values.

Things like adding custom annotations, labels, tuning resources, etc... are so common, that's where helm really shines.

**Comment by MLBMatt** [comment]
What I really need is just a way to apply the CRDs automatically into a cluster...right now we're just leveraging a makefile to run a "setup task" that runs a bunch of `kubectl apply -f`s

**Comment by eddycharly** [comment]
The crds and the controller are tightly coupled. What do you mean by « just a way to apply the crds into a cluster » ?

The chart can deploy only the crds and controller. Dashboard and webhook components are optional and can be disabled.

**Comment by MLBMatt** [comment]
Like I need the `https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml` and `https://storage.googleapis.com/tekton-releases/triggers/latest/release.yaml` applied without running a kubectl apply to work seamlessly in our workflow. Bootstrapping a Tekton cluster still requires these manual steps that could be solved if they were put into and maintained in a standalone Helm chart.

**Comment by eddycharly** [comment]
I agree that an officially maintained chart would be great.

A lot of charts are created and maintained by the community though.

**Comment by adjavaherian** [comment]
I'm also contemplating a chart, but it seems like if its not part of the official repo and build process, it will quickly fall behind as issues / features are implemented and released.  It looks like IBM has a community chart that's already defunct.  https://github.com/IBM/charts/tree/master/community/tekton-pipelines 

An official chart is certainly valuable, and doable, but i think we'd have to come up with a sensible set of parameters that can be adjusted and those would somehow have to be injected in the proper places in the new templates.

But looking at the configs https://github.com/tektoncd/pipeline/tree/master/config it seems as though the are not dynamically generated or compiled into the releases, so it might make sense to just helm-ify those directly suggest users prefer Helm ala GitHub repo.

```
$ helm repo add tekton-official https://raw.githubusercontent.com/tektoncd/pipeline/master/repo/chart
$ helm install tekton-official/tekton-pipelines --name <my-release> [--tls]
```

I think if you take that approach, you can also generate release yaml using Helm dry-run / debug to simply output default values from the templates in their current inline form.

This also seems to be agnostic from the rest of the project concerns, eg, the controller code, etc.  So would be non-disruptive and would allow both a chart based and kubectl based installation from the same codebase.

**Comment by adjavaherian** [comment]
I'm also contemplating a chart, but it seems like if its not part of the official repo and build process, it will quickly fall behind as issues / features are implemented and released.  It looks like IBM has a community chart that's already defunct.  https://github.com/IBM/charts/tree/master/community/tekton-pipelines 

An official chart is certainly valuable, and doable, but i think we'd have to come up with a sensible set of parameters that can be adjusted and those would somehow have to be injected in the proper places in the new templates.

But looking at the configs https://github.com/tektoncd/pipeline/tree/master/config it seems as though the are not dynamically generated or compiled into the releases, so it might make sense to just helm-ify those directly suggest users prefer Helm ala GitHub repo.

```
$ helm repo add tekton-official https://raw.githubusercontent.com/tektoncd/pipeline/master/repo/chart
$ helm install tekton-official/tekton-pipelines --name <my-release> [--tls]
```

I think if you take that approach, you can also generate release yaml using Helm dry-run / debug to simply output default values from the templates in their current inline form.

This also seems to be agnostic from the rest of the project concerns, eg, the controller code, etc.  So would be non-disruptive and would allow both a chart based and kubectl based installation from the same codebase.

**Comment by eddycharly** [comment]
Linking issue in plumbing https://github.com/tektoncd/plumbing/issues/278
Various PRs in the experimental repository are linked to the issue. 

This is WIP.

**Comment by salaboy** [comment]
@vdemeester or someone.. is there any update on this front? 
Is there any public helm chart for pipelines?

**Comment by eddycharly** [comment]
@salaboy we couldn't integrate this in the official repo, i've setup one here https://github.com/eddycharly/tekton-helm but it's not official

**Comment by ibexmonj** [comment]
ended up here by search for issues. +1 for an official helm chart support.

**Comment by salaboy** [comment]
An update on here, I am currently using Jenkins X Helm Charts which include and maintain a Tekton Helm Chart for their deployments, so it is up to date: 
```
- name: tekton
    repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
    version: 0.0.56
```

I hope this helps... 
Jenkins X relies heavily on Tekton, so I trust that these charts are well maintained and regularly updated.

**Comment by ibexmonj** [comment]
@salaboy Is this the chart you are referring to https://github.com/jenkins-x-charts/tekton ?

**Comment by salaboy** [comment]
@ibexmonj yes,Ii think that those are the charts that are published in their public helm chart repository linked above.

**Comment by adjavaherian** [comment]
fwiw, it looks like Helm 3 has made a conscious decision to not fully support CRDs, so its likely not a good idea to pursue a Tekton chart.  [https://helm.sh/docs/chart_best_practices/custom_resource_definitions/](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/)

**Comment by ibexmonj** [comment]
@adjavaherian thats not what i interpret based on the what the docs say. They are handling CRD installs in a separate directory now `crds` dir vs the old `crd-install`. They do not say helm3 won't support CRD installs at all. 

I believe there is value in adding the community chart and let the community maintain it under the official project like other open source projects do. 

FWIW, there are already at least 2 separate work streams i have found that are maintaining the tekton helm charts 
https://github.com/jenkins-x-charts/tekton and https://github.com/eddycharly/tekton-helm

**Comment by salaboy** [comment]
@adjavaherian I do understand that it gets confusing for updates of CRDs, but are Tekton CRDs changing that much? I mean, if they are stable enough for other projects to consume, I think that having a Helm chart is very useful, 
@ibexmonj we might want to push for something like a http://cd.foundation maintained chart as a joint collaboration of multiple open source projects interested in having the charts.. @rawlingsj what do you think about this? I do believe that is a great place for collaboration

**Comment by rawlingsj** [comment]
@salaboy yeah makes sense to me.  FWIW the Jenkins X helm chart is currently a little behind the latest release https://github.com/jenkins-x-charts/tekton/blob/0ead7a1b6d950aedb303df76b0ece90fac66a71d/tekton/values.yaml#L2.  It would be great to setup some automation and keep up-to-date with latest releases including automated testing that could also help provide the tekton project some feedback too.  If the CDF has the infrastructure to be able to do this then that sounds like a win, I'd happily help any way I can.

**Comment by tracymiranda** [comment]
@salaboy @rawlingsj great thinking - I'll take it to the CDF interoperability SIG (https://github.com/cdfoundation/sig-interoperability) and I'm sure we can get this done somehow or the other.

**Comment by bcollard** [comment]
> There is not plan for an official helm chart that I know of. We are working on providing an operator (see [`tektoncd/operator`](https://github.com/tektoncd/operator)) for installation purpose.
> 
> That said, it might make sense to have one ?
> 
> /kind question

To date, the operator looks to be under development and refactoring (for instance, I had a look two days ago, and the 'deploy' dir was renamed to 'config' between 2 pages reload). And, I suppose, this operator would require the OLM (Operator Lifecycle Manager). I guess not everyone has got this OLM installed / available (even if easily installable).

So, in the meantime, I would suggest to rely on a Helm chart. Personally, I succeeded in using the [charts provided](https://github.com/eddycharly/tekton-helm/) by @eddycharly (and could make PR to use the latest version of pipelines and dashboard).

**Comment by vdemeester** [comment]
> To date, the operator looks to be under development and refactoring (for instance, I had a look two days ago, and the 'deploy' dir was renamed to 'config' between 2 pages reload). And, I suppose, this operator would require the OLM (Operator Lifecycle Manager). I guess not everyone has got this OLM installed / available (even if easily installable).

So, the goal of `tektoncd/operator` is to make it usable *without* requiring OLM, so that you can just apply the operator yaml and that takes care of the rest (installing or upgrading tekton, …). cc @nikhil-thomas @sthaha . It is indeed in refactoring to allow such thing (and also to allow having customization per *targets* like openshift, gke, …)

**Comment by willzhang** [comment]
i want helm chat ,so i can add tekton to rancher or kubesphere appstore.

**Comment by salaboy** [comment]
The cd.foundation created a shared chart here: https://github.com/cdfoundation/tekton-helm-chart

**Comment by abdennour** [comment]
Guys! please standarize the app. Helm chart is a must for k8s. In generate package distribution is a must.

**Comment by ImJasonH** [comment]
It sounds like there's a fair amount of demand for this. Is there anybody interested in pushing this forward and making it a reality?

There's partial (abandoned?) helm chart support [in experimental](https://github.com/tektoncd/experimental/tree/master/helm), but it looks like those haven't been updated in quite a while, and they seem to need some website changes to support the charts.tekton.dev vanity domain.

As salaboy [said](https://github.com/tektoncd/pipeline/issues/1542#issuecomment-709896221), there's also charts owned by the CDF repo. If those are solid and kept up-to-date, we could just promote those better.

I don't have any experience with Helm, and I'm not sure any other Tekton contributors do either, so we'll need someone from the community to step up and take on this work (even if that's just promoting the CDF chart). I can offer Tekton stickers to anybody who's interested. 😄

**Comment by rawlingsj** [comment]
The one in the CDF is being maintained, all Jenkins X 3 installs are using it too.  It looks like we should kick off the automation to publish the latest chart for Tekton 0.21.0 from last weeks release, as the chart is currently on 0.20.1.  I can look at that.

**Comment by rawlingsj** [comment]
Just to follow up, version [0.21.0 CDF Tekton helm chart](https://github.com/cdfoundation/tekton-helm-chart) has been released.  

FWIW the process to upgrade with a new Tekton release is relatively simple, anyone can fork the repo, run `make fetch`, review the changes, push and make a pull request.

A merge to the mainline will create a new helm chart release.  FWIW Jenkins X then has automated PRs generated on downstream repos that trigger BDD testing to verify Jenkins X features work before we release it to users.  Ideally we will move some of this BDD testing onto the CDF Tekton helm chart repo itself so we have CI to verify the `make fetch` works and latest release can be verified.

**Comment by salaboy** [comment]
@ImJasonH @rawlingsj what about if I send a PR to the tekton docs with a quick intro about how to install tekton from the CDF charts? So people looking at the tekton docs knows how to get started.. and also google directs people to there instead of to this issue ?

**Comment by ImJasonH** [comment]
> @ImJasonH @rawlingsj what about if I send a PR to the tekton docs with a quick intro about how to install tekton from the CDF charts? So people looking at the tekton docs knows how to get started.. and also google directs people to there instead of to this issue ? 

Yeah I think that'll be a good place to start.

I do want to make it clear to users who owns and updates the charts, since it's not Tekton folks.

But definitely it makes sense to promote them better if users want them and someone wants to support them.

**Comment by salaboy** [comment]
@ImJasonH Jason, can you please point me out to where (which github repo and which section) would be the best place to add that piece of information, I will happily send a PR.

**Comment by ImJasonH** [comment]
> @ImJasonH Jason, can you please point me out to where (which github repo and which section) would be the best place to add that piece of information, I will happily send a PR. 

We could add a paragraph to https://github.com/tektoncd/pipeline/blob/master/docs/install.md

**Comment by salaboy** [comment]
@ImJasonH perfect.. let me send a PR there. 
Thanks

**Comment by vince-franco** [comment]
Would it make more sense for the Operator to have a helm chart instead of just pipelines?

**Comment by vdemeester** [comment]
> Would it make more sense for the Operator to have a helm chart instead of just pipelines?

What do you mean by that ? 🤔 By Operator, I assume you don't mean `tektoncd/operator` as it allows you to install, manage and *kustomize* you pipeline installation as well as other components.

**Comment by vince-franco** [comment]
@vdemeester I do!

There's no easy way to deploy the Tekton Operator yaml and the Config yaml without running kubectl from a local machine.  A really simple helm chart that would install the operator on a cluster and allow you to choose which install config profile you wanted "basic, default, all" would be really helpful.  I could use the HashiCorp Terraform Helm Provider to install the operator rather than what I do now.  Download a local copies of the install yaml and config yaml into my IAC repo then deploy them with a third party Terraform Provider that can apply yaml files.

**Comment by vdemeester** [comment]
> @vdemeester I do!
> 
> There's no easy way to deploy the Tekton Operator yaml and the Config yaml without running kubectl from a local machine. A really simple helm chart that would install the operator on a cluster and allow you to choose which install config profile you wanted "basic, default, all" would be really helpful. I could use the HashiCorp Terraform Helm Provider to install the operator rather than what I do now. Download a local copies of the install yaml and config yaml into my IAC repo then deploy them with a third party Terraform Provider that can apply yaml files.

Yeah that could work tbh.

**Comment by nikhil-thomas** [comment]
> Would it make more sense for the Operator to have a helm chart instead of just pipelines?

@vince-franco 
That makes a lot of sense. 🧑‍💻 👍 

At present, 2 ways to install Tektoncd/operator are:

- kubectl apply <githhub relese.yaml>
- from operatorhub.io (for this a user will have to install [OperatorLifecycleManager](https://github.com/operator-framework/operator-lifecycle-manager) on a cluster first)

I think providing a helm chart for operator will be an improvement compared to the available options, as it would help us leverage an existing popular tool.

However, I think separate helm chart for individual Tektoncd Components (pipeline, triggers, chains) etc, is not good way to solve go. As this could create unnecessary overhead in the release/maitenance of components.

**Comment by nikhil-thomas** [comment]
https://github.com/tektoncd/operator/issues/543

**Comment by rouke-broersma** [comment]
> Just to follow up, version [0.21.0 CDF Tekton helm chart](https://github.com/cdfoundation/tekton-helm-chart) has been released.
> 
> FWIW the process to upgrade with a new Tekton release is relatively simple, anyone can fork the repo, run `make fetch` (you'll need the [jx v3 cli](https://github.com/jenkins-x/jx-cli) on your path), review the changes, push and make a pull request.
> 
> A merge to the mainline will create a new helm chart release. FWIW Jenkins X then has [automated PRs generated on downstream repos that trigger BDD testing](https://github.com/jenkins-x/jx3-versions/pull/2183/files) to verify Jenkins X features work before we release it to users. Ideally we will move some of this BDD testing onto the CDF Tekton helm chart repo itself so we have CI to verify the `make fetch` works and the proposed helm chart changes can be verified.

FYI this chart has not been updated in a while and does not include 0.27.3 which means that the chart currently does not install on k8s 1.22. We found this out the hard way..

**Comment by nikhil-thomas** [comment]
Thank you for the heads up.
At present, we are working on the possibility of providing Helm charts with the tektoncd/operator. 

Initially, our idea is to support customizations such as:
- target namespace: installing Pipelines, Triggers etc in  a namespace other than `tekton-pipelines`
- enable/disable components: install 1 or n components out of Pipelines, Triggers, Dashboard and Results.
