### ISSUE TITLE
Tekton webhook seem does not work in OKD 3.11 Multi-tenant networking

### ISSUE THREAD

**Issue by DanielChuDC** [tektoncd/pipeline#1547]
# Expected Behavior
After created tekton webhook with kabanero that link to github, the webhook successfully trigger and deploy the deployment in OKD 3.11 cluster

# Actual Behavior
Github webhook return 504 service timeout. After I dig down the problem, it seem like the istio istio-egressgateway and istio-ingressgateway have issue with health check and the pods keep redeploy.

# Steps to Reproduce the Problem

1.  Install a OKD 3.11 cluster with multi-tenant networking mode.
2. Install kabanero with tekton webhook (https://kabanero.io/docs/ref/general/tekton-webhooks.html)
3. Insert a webhook connection to github

# Additional Info
I am not sure why the deployment of the pods is at kabanero namespace and istio ingress route expose at istio-system namespace.

I currently look into these two area but not sure if I am on the right track. Any help will do! Thank you.
1. [Application project cannot connect to istio-system namespace in Openshift Container Platform ](https://access.redhat.com/solutions/4500271)
2. [Service Mesh](https://docs.openshift.com/container-platform/3.11/servicemesh-install/servicemesh-install.html)

<img width="1679" alt="Screenshot 2019-11-10 at 8 20 29 AM" src="https://user-images.githubusercontent.com/52316624/68536771-0825eb00-0393-11ea-9190-17bbd85e95f6.png">

**Comment by vdemeester** [comment]
@DanielChuDC given that we don't support OpenShift 3.x (as the kubernetes version is too old for Tekton), and as Kabanero seems to have switch to OpenShift 4.x, I'm not sure what to answer except that it might be a wontfix for now.

I also feel worst case, this is an OpenShift / OpenShift pipelines issues, which then means it shouldn't be reported in here. I'm gonna go ahead and close this but feel free to comment and make me re-open if you think it needs be.

/close
