### ISSUE TITLE
Pipelinerun example fails

### ISSUE THREAD

**Issue by stobias123** [tektoncd/pipeline#1551]
# Expected Behavior
Pipelines example to work in openshift
# Actual Behavior
Pipelines example fails.
# Steps to Reproduce the Problem

1. `k appy -f https://raw.githubusercontent.com/tektoncd/pipeline/master/examples/pipelineruns/pipelinerun.yaml`
2. View results of pipeline run

# Additional Info
Error output from step containers.
```
Error: error resolving dockerfile path: copying dockerfile: open /kaniko/Dockerfile: permission denied
Usage:
  executor [flags]

Flags:
```

**Comment by vdemeester** [comment]
@stobias123 it seems `kaniko` explicitely needs to be run as root. We should update the example to reflect that.

/kind bug
/kind documentation

**Comment by sbwsg** [comment]
@stobias123 @vdemeester for this issue, is it a bug in Tekton or is it simply that kaniko and openshift dont interoperate well?  Is there something more Pipelines could do here or can we close this?

**Comment by vdemeester** [comment]
I think we can close, #1560 should have updated that
/close
