### ISSUE TITLE
Reusable workloads with a DAG

### ISSUE THREAD

**Issue by ncskier** [tektoncd/pipeline#1552]
# Expected Behavior
I expect to be able to easily reuse any consumable workload that I define with Tekton by using it within a larger workload. This reuse is analogous to implementing a function in a library, and reusing this function in different functions/programs.

# Actual Behavior
If my workload requires a DAG, then I must declare it as a Pipeline. There is not an easy way to reuse my workload in a Pipeline, because there's no way to run Pipelines from within other Pipelines. So, I will not be able to easily reuse my workload within a larger workload.

# Additional Info
I don't have a good use-case/scenario for this issue at the moment, this is just a limitation that I noticed.

**Comment by vdemeester** [comment]
> There is not an easy way to reuse my workload in a Pipeline, because there's no way to run Pipelines from within other Pipelines. So, I will not be able to easily reuse my workload within a larger workload.

Using [`tektoncd/triggers`](https://github.com/tektoncd/triggers) alongside some task, it is kinda possible right now. It is not possible through the current `tektoncd/pipeline` API, but I'm not sure if this is something the "core" API should handle (or using several components and have an abstraction layer on top).

**Comment by dibyom** [comment]
Looks like a duplicate of #2134 .
I'm going to close this and track the feature there. Feel free to re-open if you disagree!
