### ISSUE TITLE
Add labels to PipelineRuns/TaskRuns based on PipelineResources

### ISSUE THREAD

**Issue by ncskier** [tektoncd/pipeline#1553]
# Expected Behavior
When I execute PipelineRuns/TaskRuns using different git repositories, I expect to be able to filter my PipelineRuns/TaskRuns by repository, branch, etc.

# Actual Behavior
As far as I know, there is currently no way to filter my PipelineRuns/TaskRuns by the repository or branch they use. I can manually add a label to each PipelineRun/TaskRun, but this doesn't work if something else is creating these resources.

I think that it could be helpful to automatically add some labels to each PipelineRun/TaskRun based on the PipelineResources that it uses. For example, if it uses a git PipelineResource, then Tekton can automatically add a label for the repo, branch, org, etc. Then, I can use these labels to filter my PipelineRuns/TaskRuns based on repository, branch, org, etc. This would be similar to the Pipeline label which lets me filter PipelineRuns by Pipeline (`tekton.dev/pipeline: my-pipeline`).

**Comment by ImJasonH** [comment]
This is a perfect use case for the proposed [Results API project](https://docs.google.com/document/d/1-XBYQ4kBlCHIHSVoYAAf_iC01_by_KoK2aRVO0t8ZQ0/edit#).

One benefit of storing this information outside of the cluster's etcd storage is that the storage engine can index results and enable queries like "what PipelineRuns have executed on this commit of this repo" or "what PipelineRuns have executed on _any_ commit of this repo".

Storing this information in k8s object annotations might be suitable as a short-term solution, but it definitely won't scale once you have tons of queries you'd like to answer. Storing these in annotations also means other users can edit/remove them, which makes them untrustworthy for real forensic use cases.
