### ISSUE TITLE
Make "image digest exporter" as the output "task modifier" of image resource

### ISSUE THREAD

**Issue by vincent-pli** [tektoncd/pipeline#1565]
I'm curious why we treat `image digest exporter` as a specific operator, like this:
https://github.com/tektoncd/pipeline/blob/15e3bd240f38aa77045a498fc6ccb928fefeac00/pkg/reconciler/taskrun/taskrun.go#L479

Any reason do not make it as `InternalTaskModifier` in `image resource`?

**Comment by dibyom** [comment]
I've wondered this too...One reason might be that with the current approach there is only one image digest exporter while if it was part of the Image resource, there would be one post container added per image resource?
