### ISSUE TITLE
Confused timeout in pipelinerun

### ISSUE THREAD

**Issue by vincent-pli** [tektoncd/pipeline#1574]
At the beginning, I define `timeout` in `pipelinerun` and expect the pipeline will end after a certain time and release the resource, but it's not.
After `pipelinerun` mark it as `timeout`, the `task` still keep running for a while.

Now I know the `pipelinerun` will share the `timeout` with `task`s, that's means in a linear scenario, if the `task` is render by `pipelinerun` it will keep running no matter its owner `pipelinerun` is `timeout`.
That's means the really max duration for a `pipelinerun` is `timeout` x 2.

I still have no idea if it's a correct behavior, but at least we need mark it in the document.
Another solution is set `timeout` of child `task` as start-time + timeout - now, but it will make user confuse if he/she is not read the document.

**Comment by dibyom** [comment]
So, is the issue here we do not cancel the taskruns when we cancel a pipelinerun? And so the taskruns keep running until they complete?

**Comment by vincent-pli** [comment]
@dibyom 
Right, it's current behavior.
