### ISSUE TITLE
Missing k8s liveness and readiness probes support

### ISSUE THREAD

**Issue by tomhau01** [tektoncd/pipeline#1586]
# Expected Behavior
Pipeline controller and webhook containers have liveness and readiness probes (https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/) defined.

# Actual Behavior
Probes are missing:
https://github.com/tektoncd/pipeline/blob/v0.8.0/config/controller.yaml
https://github.com/tektoncd/pipeline/blob/v0.8.0/config/webhook.yaml

# Steps to Reproduce the Problem

1. Deploy tekton v0.8.0
2.
3.

# Additional Info
I managed to use `/metrics` endpoint for controller as a fix for now but webhook doesnt seem to support any GET that could be used?

**Comment by xiujuan95** [comment]
Could you have any plan to support liveness and readiness for tekton controller?

**Comment by ywluogg** [comment]
After a bit of research, I think adding liveness and readiness for Tekton webhook is straight forward as there is a port provided and I think can be used for readiness and liveness: https://github.com/tektoncd/pipeline/blob/9b2a92c75d9f635bc933639bf48d9a005eb07a81/config/webhook.yaml#L119

For the controller, we don't have a port setup yet, but I think it is necessary. Asking @bobcatfish if there is any down side for adding it in the controller.

**Comment by ywluogg** [comment]
I'm trying to add the probes to the controller as well, but encountered port issues.
