### ISSUE TITLE
Allow ReadWriteMany mode for PVC of PipelineRun

### ISSUE THREAD

**Issue by jkljf** [tektoncd/pipeline#1587]
# Expected Behavior
For the automatic created PV, allowing AccessMode 'ReadWriteMany' would facilitate the parallel tasks' execution.
# Actual Behavior
It seems 'ReadWriteOnce' is the default value. In fact, it's hardcoded in the source code (./pkg/artifacts/artifacts_storage.go)
# Steps to Reproduce the Problem

1. Run a pipeline with the Input/Output Resource usage
2. Check the K8S PV
3. AccessMode in the output is always RWO

# Additional Info

**Comment by vdemeester** [comment]
/kind feature
Might be a consideration to take for #1438
