### ISSUE TITLE
Use Knative's {Type}StatusFields Pattern

### ISSUE THREAD

**Issue by poy** [tektoncd/pipeline#1590]
# Expected Behavior
I would like to be able to embed Tekton's Status in my own CRD (e.g., for a TaskRun).

# Actual Behavior
I have to recreate Tekton's Status type because I can't embed it due to the included `duck.Status`.

# Additional Info
Knative-Serving solves this by creating a new Type that doesn't embed the `knative.dev/pkg/apis/duck/v1beta1.Status`.

An example of it is their [`ServiceStatus`](https://github.com/knative/serving/blob/e695abb86f319abd7095bb508cebbbf5238d27dc/pkg/apis/serving/v1/service_types.go#L93)

Notice that it embeds both the `ConfigurationStatusFields` and the `RouteStatusFields`.

I would be happy to contribute towards this if this is something we want to do.

**Comment by ImJasonH** [comment]
I'm having some difficulty understanding what we're doing that's causing a problem for you. It sounds like you want to embed `TaskRunStatus` in your own `*Status` struct, is that correct? Like this?

```
type FooStatus struct {
  v1alpha1.TaskRunStatus `json:",inline"`
}
```

And the inclusion of the `knative.dev/pkg/apis/duck/v1alpha1.Status` type is causing problems somehow? Can you give me an example error message you're seeing?

(In general I have no problem rearranging how this type is defined, so long as it doesn't break compatibility, I'm just having difficulty understanding what's wrong with how it's described now)

**Comment by poy** [comment]
You are correct that I'm wanting to do this. Its less of a compilation problem and more that it seems misleading (to me at least).

With Knative's pattern, it's clear what fields will be filled in. However if I embed the `TaskRunStatus` as it is today, it has an unused field `Status`. WDYT?

**Comment by poy** [comment]
@ImJasonH I'm working on a PR for this now. Do you think it would make more sense for v1alpha2 or beta?

**Comment by ImJasonH** [comment]
How much of a breaking change is it to customers who only see YAML? Can you give me an idea of the before/after for especially the YAML diff, and then less so the Go struct diff?

**Comment by ImJasonH** [comment]
Nevermind just saw the PR
