### ISSUE TITLE
Copy output from a previous task, resource is not used ?

### ISSUE THREAD

**Issue by eddycharly** [tektoncd/pipeline#1604]
When a task in a pipeline uses output from a previous task, the resource element is ignored ?
Do the output and input have to share the same name for it to work ?

If i trust the code below :

https://github.com/tektoncd/pipeline/blob/c9a7a35c01aea3ad6cf8b0992e10b0a21535d2a6/pkg/reconciler/pipelinerun/resources/input_output_steps.go#L83-L92

If the output is named `foo` in the previous task and the input is named `bar` in the current task, it looks like it will try to copy from a path like `bucket/previous-task/bar` instead of `bucket/previous-task/foo`.

**Comment by vincent-pli** [comment]
@eddycharly 
Yes, based on current implementation, the next `task` has no idea what's the name of output resource of the previous `task`, only know the name of previous `PipelineTask`.

**Comment by eddycharly** [comment]
@vincent-pli what's the reasoning behind this ? previous task output and current task input must match ?

So there is no way to take an output of a task and use it as input in another task whatever their names ?

The examples in the docs are confusing https://github.com/tektoncd/pipeline/blob/master/docs/pipelines.md#from. Not sure why `resource` and `from` are set here.

```yaml
    inputs:
      - name: image
        resource: my-image
        from:
          - build-app
```

**Comment by vincent-pli** [comment]
I think the reason is the `pipelinerun` will be divide to several `taskrun` in runtime, each `taskrun` has limited knowledge of others.

The `resource` in the sample means `pipelineresource`, it's a refer to a real crd named `pipelineresource`, has no relationship with the location of the resource :)

**Comment by eddycharly** [comment]
Each taskrun has no knowledge at all of other taskruns. The pipeline creates/orchestrates the taskruns, making the glue between them. 

I am trying to understand if an output of a task can be copied as the input of another task, regardless of the output and input names. 

For the copy to work, it looks like the name of the input and output have to be the same, it makes the tasks difficult to reuse as each task name their inputs/outputs independently. 

Could we improve this mechanism to allow copying ouput ˋa` from one task to input ˋb` of another task ?

**Comment by vdemeester** [comment]
I think this is related/duplicate of #1002. This is (imho) one of the limitation of the PipelineResource (as currently designed) and one of the reason why PipelineResource are (so far) not considered to move to beta until they are redesigned (see #1369 and [design doc](https://docs.google.com/document/d/1euQ_gDTe_dQcVeX4oypODGIQCAkUaMYQH5h7SaeFs44/edit#))

**Comment by eddycharly** [comment]
thanks @vdemeester
i don't have access to the google drive.
i was thinking about it, why not introduce an implicit resource, something like `taskstorage` to be used by the pipeline ?
from the task point of view it would be a storage, it doesn't change anything, from the pipeline run point of view, it could be used to pass the `taskstorage` to the task output.

the `taskstorage` would take care of copying from/to the storage as configured (pvc, gcs or s3).

**Comment by vdemeester** [comment]
@eddycharly the current "idea" is to separate this concern from the PipelineResource, see #1438

**Comment by vdemeester** [comment]
You need to be part of `tekton-dev@` or `tekton-users@` to be able to have access to those design document, see [here](https://github.com/tektoncd/community/blob/master/contact.md#mailing-list)

**Comment by dibyom** [comment]
Workspaces are in and can solve this problem: https://github.com/tektoncd/pipeline/blob/master/docs/workspaces.md

@vdemeester ok to close this?

**Comment by eddycharly** [comment]
@dibyom two task running on two different can share a workspace ?

**Comment by eddycharly** [comment]
Closing as it is probably not relevant anymore in regards of workspaces.
