### ISSUE TITLE
Access issue while pushing to Openshift 3.x through pipeline using Kaniko

### ISSUE THREAD

**Issue by maheshwarishikha** [tektoncd/pipeline#1631]
# Actual Behavior
I am trying to build and push an application using Kaniko to openshift cluster. I have written tekton pipelines - configuration yamls.
Created service account and have provided secret as config-map, still kaniko command fails with following error:

"error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "docker-registry-default.xx.xx.xx.cluster.local/default/builtapp:1.0": creating push check transport for docker-registry-default.xx.xx.xx.cluster.local failed: unsupported status code 401"

# Expected Behavior
It should work fine. Tried manually using docker commands - was able to push an image to OC registry.

# Additional Info
Task definition is attached here, let me know if I am missing something here.
[build-src-code.txt](https://github.com/tektoncd/pipeline/files/3896359/build-src-code.txt)

TIA.

**Comment by vdemeester** [comment]
@maheshwarishikha did you find a workaround ? For pushing to a non https registry using `kaniko` I think you need one additional flag (in addition to `"--insecure-registry=…"`

/kind question

**Comment by maheshwarishikha** [comment]
@vdemeester , I'll check this.
Currently I pushed an image into openshift registry and now, creating a new app using a task 'openshift-client' (https://raw.githubusercontent.com/tektoncd/catalog/master/openshift-client/openshift-client-task.yaml)...the container gets created but its CrashLoopBackOff. Not finding any clue for this behaviour.

Same application worked fine when I deployed on Kubernetes using tekton. But not working with Openshift cluster. Any suggestions for this?

**Comment by afrittoli** [comment]
> @vdemeester , I'll check this.
> Currently I pushed an image into openshift registry and now, creating a new app using a task 'openshift-client' (https://raw.githubusercontent.com/tektoncd/catalog/master/openshift-client/openshift-client-task.yaml)...the container gets created but its CrashLoopBackOff. Not finding any clue for this behaviour.
> 
> Same application worked fine when I deployed on Kubernetes using tekton. But not working with Openshift cluster. Any suggestions for this?

Openshift is much more restrictive than a generic kubernetes, so you may be running in issues with the security context. I would check the logs from your container for more clues.
