### ISSUE TITLE
Missing PullRequestPipelineResource steps with artifact PVC

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/pipeline#1632]
# Expected Behavior
When the pull request pipeline resource is used in a Task as both input and output, I expect three steps to be added:
- created dir
- download pr
- upload pr

This should happen regardless of Tekton configuration.

# Actual Behavior

If Tekton is configured to use artifact PVC, only download is added to the POD:
```
$ k get pod/mario-comment-github-5bngk-v2pf4-pod-b741cb -n mario -o jsonpath='{.spec.containers[*].name}' | tr ' ' '\n' ; echo
step-create-dir-image-p7cz5
step-git-source-source-84p6r
step-pr-source-pr-5bngk-wt8pb
step-copy-pr-to-output
step-setup-comment
step-image-digest-exporter-h5g4d
```

With the bucket instead:
```
$ k get pod/mario-comment-github-fs2xp-sgj95-pod-75de28 -n mario -o jsonpath='{.spec.containers[*].name}' | tr ' ' '\n' ; echo
step-create-dir-pr-wk9xh
step-create-dir-image-dqcdf
step-git-source-source-x4984
step-pr-source-pr-fs2xp-wgbp8
step-copy-pr-to-output
step-setup-comment
step-image-digest-exporter-nktfp
step-pr-source-pr-fs2xp-mvhnn
```

# Steps to Reproduce the Problem

I reproduce the output with the mario-bot prototype at https://github.com/afrittoli/plumbing/pull/1/files.

1. The TaskRun is created by the EventListent via a TriggerTemplate
2. The TaskRun embeds the Task definition
3. The PullRequestPipelineResource is created by the EventListent via a TriggerTemplate
4. The PullRequestPipelineResource is used as both input and output resource in the Task 

# Additional Info

**Comment by bobcatfish** [comment]
Are you 100% sure that the behaviour your expect isn't there @afrittoli ? I think it might be easier to understand what's going wrong if you could list exactly what each of the missing steps is intended to be doing.

(I'm just surprised b/c I think both @dlorenc and I have been using the PR resource a bunch, and I know I've got PVC linking turned on, and it was working as I expected)

**Comment by afrittoli** [comment]
I have two clusters, with the exact same version of Tekton deployed, same Tekton resources and the only difference was the PVC vs. Bucket configuration. 
The cluster using bucket works, the one using PVC doesn't. Once I reconfigured the PVC cluster to use bucket is started working as well.

I'm not sure if the description of the issue is as narrow as it can be - it could be that there are other elements involved. e.g. perhaps this behavior happens only if a TaskRun is used as opposed to a PipelineRun, or perhaps it only happens if there is more than one output resource.

**Comment by bobcatfish** [comment]
> e.g. perhaps this behavior happens only if a TaskRun is used as opposed to a PipelineRun, or perhaps it only happens if there is more than one output resource.

oooohhhh you know what, that could be it - @dlorenc and I have definitely seen different behaviour around the PVCs in a TaskRun vs a PipelineRun (or in the case of #1068, when there was just 1 Task vs multiple)

**Comment by vdemeester** [comment]
@afrittoli @bobcatfish is this still an issue ? :upside_down_face:
