### ISSUE TITLE
Remove /builder/home before v0.10

### ISSUE THREAD

**Issue by ImJasonH** [tektoncd/pipeline#1633]
https://github.com/tektoncd/pipeline/pull/1628 added `/tekton/home` as `HOME`, alongside and backed by the same volume as `/builder/home`, for backward-compatibility reasons.

That change will go in for v0.9, and we'll announce that people who depend on the specific path (and not just `$HOME`) will need to move  to `/tekton/home` before v0.10.

**Comment by vdemeester** [comment]
@ImJasonH #1700 being merged, this can be closed, can it ? :angel: 
/assign @ImJasonH
