### ISSUE TITLE
api proposal: delete PipelineStatus

### ISSUE THREAD

**Issue by poy** [tektoncd/pipeline#1636]
# Expected Behavior
`Pipeline` and `Task` would have similar API patterns.

# Actual Behavior
`Pipeline` has a corresponding `PipelineStatus` which is empty. The comments listed with it suggest that a Pipeline can't have a status:
```
// PipelineStatus does not contain anything because Pipelines on their own
// do not have a status, they just hold data which is later used by a
// PipelineRun.
```

`Task` is generated with `+genclient:noStatus`.

I would propose we delete `PipelineStatus`. This may be a breaking change for a user who has decided to use `PipelineStatus` in their Go code, however I'm not sure what they would actually do with it, given its empty.

# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info

A quick grep through github.com/tektoncd/pipeline seems to indicate the type is not used.

**Comment by vdemeester** [comment]
Indeed, it's not used for anything as `Pipeline` (or `Task`) are not reconcilied object. I feel the use *might* be useful whenever we want to validate `Generation` (observed vs real) but I don't think we want to do that for `Pipeline` or `Task`.

/cc @bobcatfish 
/kind cleanup

**Comment by poy** [comment]
Looking through the codebase, it looks like `PipelineResourceStatus` is in a similar position.

**Comment by vdemeester** [comment]
@poy indeed
