### ISSUE TITLE
Sometimes...it's best to just use Go vs Tasks - worked example below (webhooks/Ingress/routes)

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/pipeline#1637]
Sharing this data point (of course it's sometimes faster, but here's a real concrete example)

We were looking to use Tekton Tasks for creating Ingress, Routes and webhooks, specifically for the Tekton Webhooks Extension.

Have a look at the following code changes we made:

https://github.com/tektoncd/experimental/commit/a28cd04d1f352fd24fd3692262149d6c8728a0ad

the Tekton tasks involve pulling images and going through the init containers, whereas we can use Go and get things made reeeeeeeeally quickly.

The same goes for Ingress, have a look at https://github.com/tektoncd/experimental/commit/49b61ed5064f78ccf5c1ac4c05b497d0a17f83a6

It'd be useful to investigate the performance impact of Tekton Pipelines - is there a minimum time for something to actually run due to the init container startup? What happens under the covers that makes them relatively heavyweight in comparison to just using Go code? What makes something good to be a Tekton Task? Maybe this is a paper idea...when's it good to use Tekton vs not?

For the first webhook creation it completed in over a minute, subsequent attempts were around 10 seconds. Using the Go git client completes in less than a second, really it's doing the same http post...

**Comment by afrittoli** [comment]
The benefit of using a Task is it's declarative interface which makes it easily reusable (hopefully), but certainly there are faster ways of achieving things. When the Task execution time is very low, it would be worth considering alternatives. Another case where this can be seen is conditions. For conditions that are simple string matches or something of the sort, spinning up a container might be too much of an overhead, even when the container image is very small and/or cached.

I think it's good to keep this in the backlog.
