### ISSUE TITLE
Tracking pipeline and task execution time as well as controller time

### ISSUE THREAD

**Issue by tanner-bruce** [tektoncd/pipeline#164]
## Expected Behavior
As a developer of build-pipeline, being able to see an entire trace of someones pipeline execution as well as the execution context through the pipeline controller would help diagnose performance issues and give visibility into what is going on

It should be possible to query for metrics around:
* How long Tasks of a particular type are taking
* How long Steps of a particular Task are taking
* Number of TaskRuns and PipelineRuns being created (tied to the corresponding Task/Pipeline)

The mechanism that we use to collect metrics should not hold state globally, i.e. it should be possible to configure the metrics collecting mechanism in one section of the code without affecting other sections (the one currently used in knative/pkg is global, e.g. see [this code](https://github.com/knative/pkg/blob/fcb065651464d2668b5dffbfcdd1792bb732b86f/test/logging/logging.go#L128)).

## Actual Behavior
Some of this data is available via `startedAt` and `finishedAt` in the status fields, however it is not queryable, and we would like more data points.

## Additional Info
Having this information would be extremely valuable as it would quickly highlight points of interest in the pipeline controller and give visibility into the entire system.

**Comment by tanner-bruce** [comment]
After speaking in slack with @aaron-prindle we briefly touched on the possibility of building this in via the same process that will be used for overriding the entrypoint for gathering the build logs.

**Comment by bobcatfish** [comment]
@tanner-bruce can you give some examples of what kind of info you'd want to see exactly, and when you'd use it?

**Comment by bobcatfish** [comment]
I'm guessing this is something more like we want to be monitoring these metrics as the person administering the deployment of the Pipeline CRD, is that right?

**Comment by tanner-bruce** [comment]
The main one for me, as a user, is tracking build times over days and months, as well as various test times. It would also be kind of slick if during the TaskRuns themselves we could be passed in the trace context and add spans to it from there.

As a cluster operator, it could also be useful to be able to see the timings at a global level, to help determine something like if we need to add another node to the pool.

At the same time, having the controller emit metrics could also be useful for things like checking the number of jobs running for something like seeing trends of how often people/teams are running builds. Depending on how the Pipeline CRD goes in the future, if say Pipeline Runs were queued at some point, being able to check and alert on the depth of the queue would be very useful.

Having the startedAt and finishedAt is useful, but being able to visualize them and query on them would be much more useful from an operators standpoint.

**Comment by bobcatfish** [comment]
@tanner-bruce makes sense, thanks for the detailed explanation! I added some requirements to the description, feel free to change these and/or add to them if that's not quite right.

**Comment by bobcatfish** [comment]
Just a note that when we get here, it would be great if we could switch to a metrics collector that isn't global - e.g. see the problem this causes in https://github.com/knative/build-pipeline/pull/211

**Comment by sbwsg** [comment]
We had our first meeting regarding observability, specifically metrics, today and work is now underway. There are a couple of other issues that overlap in theme with this one. I am linking them together here for us to review later and figure out which to keep and which to close.

Related issues:
https://github.com/tektoncd/pipeline/issues/164
https://github.com/tektoncd/pipeline/issues/540
https://github.com/tektoncd/pipeline/issues/855

[Metrics Design Doc](https://docs.google.com/document/d/1NbY3spcNVXqrZHbEp5pfFQbCyGtN8Aj7Y5d4elwM5cI/edit)

[Notes from the initial metrics meeting](https://docs.google.com/document/d/1n-ZJzKMEH31mDSooaCjVV5b3d19zwJkuDm4fmrevoLs/edit)

**Comment by afrittoli** [comment]
[This](https://github.com/knative/pkg/blob/41aec11a3cadd48dbffc3f6671f7c8a95bce6afa/controller/stats_reporter.go#L190) would help to track reconciler [stats](https://github.com/knative/pkg/blob/41aec11a3cadd48dbffc3f6671f7c8a95bce6afa/controller/stats_reporter.go#L55-L91)
