### ISSUE TITLE
Java API support

### ISSUE THREAD

**Issue by jeffmaury** [tektoncd/pipeline#1648]
# Expected Behavior

As part of our effort around IntelliJ Tekton support, we might need a Java representation of the Tekton resources. I've started an effort to get A Tekton Pipeline client based on the Fabric8 kubernetes client. I'm wondering if the community would be interested to get it hosted here.

# Actual Behavior

No Java API provided yet

# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info

**Comment by vdemeester** [comment]
@jeffmaury thanks for the issue :angel: I think it might make sense, most likely in a separate repository. 

/kind question
/kind feature

**Comment by ImJasonH** [comment]
I'm not sure who exactly owns them or keeps them up to date (perhaps @rawlingsj knows?), but there are generated Java clients for Tekton APIs at https://javadoc.io/doc/io.fabric8/tekton-client/latest/index.html which might be useful.

**Comment by jeffmaury** [comment]
Seems they are part of the raw Kubernetes client see https://github.com/fabric8io/kubernetes-client/tree/master/extensions/tekton
