### ISSUE TITLE
Step Script should be compatible with Args

### ISSUE THREAD

**Issue by ImJasonH** [tektoncd/pipeline#1652]
# Expected Behavior

I should be able to specify a step script that takes args, and specify those args to the step (possibly via `stepTemplate`).

# Actual Behavior

If a step specifies `script:` and `args:`, it's rejected as invalid.

# Steps to Reproduce the Problem

```
steps:
- name: example
  image: ubuntu
  script: |
    #!/usr/bin/env bash
    echo passed $# args
    echo first arg is $1
    echo all args are $@
  args: ['first', 'second', third']
```

Should print logs:

```
passed 3 args
first arg is first
all args are first second third
```

`script:` should still be invalid if the step specifies `command:`, since those conflict.

**Comment by afrittoli** [comment]
This would actually make the current param array type super-useful :)
