### ISSUE TITLE
Feature request: Add support for corporate proxies (e.g. in the git PipelineResource)

### ISSUE THREAD

**Issue by jomeier** [tektoncd/pipeline#1663]
Hi,

I'm testing Tekton pipelines in OpenShift4 (OKD4) behind our corporate proxy.

Today I stumbled over Tekton not respecting HTTPS_PROXY environment variables while cloning git repositories in the git PipelineResources.

I'm not able to clone anything.

It would be great If we could define the common proxy env variables in a suited location (maybe as a secret or as environment variables in the Pipeline CR).

Typically the variables are:
- HTTPS_PROXY
- HTTP_PROXY
- https_proxy
- http_proxy
- NO_PROXY
- no_proxy

Go code should be aware of proxy env variables.

This feature request would make Tekton more suitable for enterprise environments where proxies arent unusual.

Thanks and greetings,

Josef

**Comment by wlynch** [comment]
As @ImJasonH mentioned in slack, we should probably have the ability to set arbitrary variables, since there's also [many more environment variables](https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables) someone may want to set (in particular, I find that `GIT_CURL_VERBOSE` is a very useful tool for finding out why you might be getting permission denied when cloning).

**Comment by chmouel** [comment]
Related #1476 #1328 #1294 #1606

**Comment by bobcatfish** [comment]
@ImJasonH I notice you added this to the 0.10 milestone but we're trying to make sure we're really sparing about what we add to the milsetone so I'm gonna remove it for now but lemme know if you strongly disagree!

**Comment by jomeier** [comment]
@bobcatfish 
Without support for corporate proxies, Tekton will be unusable in lots of corporate environments.

**Comment by chmouel** [comment]
Strong +1 on this too...

**Comment by jomeier** [comment]
Any news when this will be available? Tekton doesn't work in OpenShift behind corporate proxies because of that.

**Comment by dsanchor** [comment]
+1 here. Support for corporate proxies is a must in 99% of production environments. Still version 0.x, but this should be part of 1.x version.

**Comment by dvetto** [comment]
+1 . Same problem.
