### ISSUE TITLE
0.9.0 Regression: PullRequestResource missing base PR information

### ISSUE THREAD

**Issue by wlynch** [tektoncd/pipeline#1681]
/kind bug
/assign wlynch

# Expected Behavior

Reported by thauta on Slack.

Full [PullRequest](https://godoc.org/github.com/jenkins-x/go-scm/scm#PullRequest) data is available in the pipeline (in particular merge state and SHA)

# Actual Behavior

The data is not there (only head/base, labels, statuses are there). This is a regression from 0.8.

# Additional Info

If we include the full payload, We'll need to make sure to not conflict with the broken out subresources - e.g. should we have labels in both pr.json and labels/, and how do these interact with each other.

My gut reaction is to omit these from pr.json.

**Comment by vdemeester** [comment]
@wlynch tentatively adding this to the 0.9.1 milestone :angel: :wink:
