### ISSUE TITLE
Need better e2e tests around injected sidecars

### ISSUE THREAD

**Issue by imjasonh** [tektoncd/pipeline#1687]
# Expected Behavior

Handling of injected sidecars is covered by e2e tests, regressions are caught quickly (even proactively) and confidence around changes to this behavior is high.

# Actual Behavior

We have no e2e tests that cover the case of injected sidecars. We can write unit tests and comments, and reason about injected sidecars in theory, but we have no concrete test cases governing their behavior.

# Additional Info

To add this to our e2e test suite, we'd probably have to have some kind of test Mutating Admission Controller that injects sidecars into Pods created during e2e tests, but not during normal operation.

The injector could look for an annotation or label on a Pod and inject containers into Pods based on that. Mutating Admission Controllers require secrets and SSL certs, which knative/pkg thankfully makes somewhat easier.

Cases we could cover if we had better e2e test support:
- waiting to start the first step for an injected sidecar that takes a long time to become Ready (https://github.com/tektoncd/pipeline/blob/master/examples/taskruns/sidecar-ready.yaml, but for injected sidecars)
- gracefully stopping an injected sidecar when steps complete

**Comment by sbwsg** [comment]
I wonder if we could leverage https://github.com/tumblr/k8s-sidecar-injector to make testing this easier.  I think that'll do the hard work of registering the mutating webhook but I haven't used it before and need to read more.

**Comment by vdemeester** [comment]
/remove-lifecycle rotten
/remove-lifecycle stale
/reopen

@ImJasonH still an issue right ? (cc @sbwsg )

**Comment by ImJasonH** [comment]
/remove-lifecycle stale

I think this is still something we'd benefit from.
