### ISSUE TITLE
Proposal: step timeout

### ISSUE THREAD

**Issue by ImJasonH** [tektoncd/pipeline#1690]
It could be nice to augment the `Step` type with a timeout duration, after which time the step fails with some unique status/message.

To support this we could pass the timeout value to the entrypoint binary, which would start a timer when step execution starts, and stop executing and raise a timeout error if execution doesn't finish in time.

If this is interesting to people it should be a pretty good first issue for a new contributor.

/kind feature

**Comment by chengjingtao** [comment]
I am watching changes: https://github.com/tektoncd/pipeline/pull/1722. It provides an ability to retrieve information from taskstep container.

We could set PipelineResourceResult to 
```
[
  {
     "key": "terminatedReason",
     "value" "TimeOut"
  }
]
```
and set `StepState.Terminated.Reason="TaskStepTimeOut"`, So we can get `TimeOut` error of specific step.
I will provide a more deailed  design, and begin to implement it after the PR above merged.

**Comment by bobcatfish** [comment]
Seems reasonable to me! @ImJasonH do you have an example use case where you'd need this? (just wanna understand why the overall task timeout wouldn't be enough)

**Comment by ImJasonH** [comment]
Task authors might want to have one step that _should_ take just a few seconds, to set up the execution environment for instance, followed by a second step that might take a long time.

If the setup step takes longer than expected it might indicate some larger issue and you'd want to fail fast rather than exhaust the TaskRun's timeout waiting for setup.

**Comment by chengjingtao** [comment]
Hi, @ImJasonH   I begin to  work on it .  Can you assign it to me ?

My plan is 

- Changes on cmd `entrypoint`
    * add a flag `timeout` to the cmd `entrypoint` and pass it  to `exec.CommandContext`. If so, the `entrypoint` will return error when times out. 
    * write fields named `Reason` and `Message`  into  `terminationMessage` as PipelineResourceResult. `Reason` will be `TaskStepTimeout`, `Message` will be `timeout more than %s`
- Changes on `controller`
    * append arg `-timeout` when changes `args` of `step container` and pass the value as `step.timeout`.
    * assign  `Reason` to `TaskStepTimeout` when convert `ContainerState` to `StepState` and assign `Message` as value of that returned in `terminationMessage`.
    * assign   `Reason` to `TaskStepTimeout`  in `Condition` of `Succeeded` of TaskRunStatus

**Comment by bobcatfish** [comment]
Hey @chengjingtao sorry we didn't reply sooner! Are you still working on this? Your approach sounds solid.

Adding Reason and Message into the terminationMessage is a nice addition - it might actually be interesting to tackle this first i.e. in a separate PR - seems useful even outside the context of time outs!

**Comment by chengjingtao** [comment]
@bobcatfish  yes, I will work on this  and sorry for my slow action. 
I will submit a PR to  implement `adding reason and message into the terminatioonMessage` this weekend.

**Comment by Peaorl** [comment]
Hi @chengjingtao, are you still working on this issue?
I recently picked up this proposal and got the timeout working.
Is it ok if I go ahead and submit a PR for that?

**Comment by ywluogg** [comment]
I realized my change for #2559 needs to heavily based on [Add timeout setting to Steps](https://github.com/Peaorl/pipeline/commit/ea1f5233dac9e36f8d482e505e0ef8abd58ec432). I saw this commit was held by #3239 Are both issues' commits going to be merged soon?
