### ISSUE TITLE
Simple way to share stuff between Tasks

### ISSUE THREAD

**Issue by vincent-pli** [tektoncd/pipeline#1697]
# Expected Behavior
There should be a simple way to share stuff between `tasks` in `pipeline`
# Actual Behavior
Sorry if I missing something.
The case is simple, two `tasks` in one `pipeline`, the latter want to access stuff generate by the former (files, expect shared by pvc)

I know the `ouputResource` is required in the former `task`, `inputResource` and `from` in the latter  one, and the `resource` must with same name. 

but do we has an appropriate `pipelineresource` for it?
seems only `Storage` and `Git` could trigger `pvc` creation.

I saw lots of discussion in recent months, so how could we cover this case for now, thanks

**Comment by ImJasonH** [comment]
/area api
/kind feature

This seems very related to the ongoing resources redesign work @sbwsg is working on, specifically the fileset resource which would be responsible for just passing files in a filesystem between tasks in a pipeline.

**Comment by sbwsg** [comment]
Also: [workspaces](https://github.com/tektoncd/pipeline/pull/1639) will very soon be supported in tasks/taskruns and then next we plan to work on pipelines support.  (cc @bobcatfish)

**Comment by bobcatfish** [comment]
I think that workspaces + results will handle this? Closing with that assumption but plz re-open if that's not the case @vincent-pli !
