### ISSUE TITLE
pullRequest resource uploading step failing

### ISSUE THREAD

**Issue by castlemilk** [tektoncd/pipeline#1714]
# Expected Behavior

upload step should correctly discover any required information from the given `/workspace/<resource>/` folder and successfully update the given PR.

# Actual Behavior

following error occurs:

```text
{"level":"info","ts":1575932806.2572246,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/refs/heads/pr: no such file or directory"}
{"level":"info","ts":1575932806.257303,"logger":"fallback-logger","caller":"pullrequest-init/main.go:56","msg":"RUNNING UPLOAD!"}
{"level":"info","ts":1575932806.2580793,"logger":"fallback-logger","caller":"pullrequest-init/api.go:107","msg":"Syncing resource: &{PR:0xc000212000 Status:0xc000224420 Comments:[] Manifests:map[comments:map[] labels:map[]]}"}
{"level":"info","ts":1575932806.5881653,"logger":"fallback-logger","caller":"pullrequest-init/api.go:144","msg":"Current labels: map[]"}{"level":"info","ts":1575932806.5882623,"logger":"fallback-logger","caller":"pullrequest-init/api.go:155","msg":"Creating labels [] for PR 10"}{"level":"info","ts":1575932806.8430235,"logger":"fallback-logger","caller":"pullrequest-init/api.go:177","msg":"Setting comments for PR 10 to: []"}{"level":"fatal","ts":1575932807.101696,"logger":"fallback-logger","caller":"pullrequest-init/main.go:62","msg":"1 error occurred:\n\t* Ref not found\n\n","stacktrace":"main.main\n\t/workspace/go/src/github.com/tektoncd/pipeline/cmd/pullrequest-init/main.go:62\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:200"}
```

# Steps to Reproduce the Problem

1. create a pullRequest resource
2. use pullRequest resource as both input and output resource
3. 

# Additional Info
* download step is successful to populate the `/workspace/<resource>/ directory
* tekton v0.9.1

**Comment by bigkevmcd** [comment]
It'd be nice if this could _open_ a PR in addition to updating existing ones.

**Comment by ImJasonH** [comment]
This should be fixed now at head, at in v0.9.2. If you find this not to be the case, please reopen with repro steps.

**Comment by bobcatfish** [comment]
@castlemilk are you able to verify that this fixes your issue? (not to alarm you but I'm asking b/c I saw some odd behaviour when I was trying to use this recently, hoping it was just me 🤞 )

**Comment by castlemilk** [comment]
@bobcatfish this looks to be working for me now on v0.9.2

**Comment by bobcatfish** [comment]
Glad to hear it!! Thanks @castlemilk :D
