### ISSUE TITLE
add getLog function for taskrun and pipelinerun

### ISSUE THREAD

**Issue by zeromsi** [tektoncd/pipeline#1716]
# Expected Behavior
Their should be function to get log of resources
# Actual Behavior
No functions are available

**Comment by vdemeester** [comment]
@zeromsi Thanks for the issue. So far, the way to get logs from a `TaskRun` or a `PipelineRun` is in the [`tektoncd/cli`](https://github.com/tektoncd/cli) repository. We should look into extracting this part into a well defined package and add move it to `tektoncd/pipeline` :angel: 

/kind feature

**Comment by chmouel** [comment]
@vdemeester what woube the use cases? who are the other consumers aside of CLI ?

**Comment by vdemeester** [comment]
@chmouel the `dashboard` might be one :angel: Also with #1709 it might be worth having a small lib to help tools integrating with tekton to easily get logs from runtime types :angel: :stuck_out_tongue_closed_eyes:

**Comment by ImJasonH** [comment]
I'd love to have a single "official" logs-getting method..._somewhere_, because eventually I'd like consumers of that method to be able to migrate to getting logs from a more stable persistent log store (e.g., Stackdriver, Kibana), rather than getting them from the Pod logs directly, where logs can disappear due to GC config.

It'll be easier to migrate folks if ~everyone's using the same code.

**Comment by zeromsi** [comment]
> @zeromsi Thanks for the issue. So far, the way to get logs from a `TaskRun` or a `PipelineRun` is in the [`tektoncd/cli`](https://github.com/tektoncd/cli) repository. We should look into extracting this part into a well defined package and add move it to `tektoncd/pipeline` 👼
> 
> /kind feature

I'm not getting the exact function of getting logs (taskrun/pipeline). Can you help me to find this out.

**Comment by dibyom** [comment]
`tkn taskrun logs`  and `tkn pipelinerun logs` should help get you the logs. You can also use `kubectl logs <with the taskRunPodName>`

/close
