### ISSUE TITLE
git-init: Setting submodules to false has no effect

### ISSUE THREAD

**Issue by silverlyra** [tektoncd/pipeline#1727]
# Expected Behavior

When using a `git` resource, setting the `submodules` param to `false` passes `-submodules false` to `cmd/git-init`.

# Actual Behavior

`GitResource.GetInputTaskModifier` does not inspect `Submodules` at all and does not generate the flag. Submodules are always initialized and fetched.

# Steps to Reproduce the Problem

1. Use a `git` resource with `params` including `{name: submodules, value: 'false'}` in a TaskRun
2. Feast your eyes upon the generated Pod

# Additional Info

#1531 changed `git-init` to fetch submodules. Making this configurable with a resource param was suggested in code review, but not completely implemented. `Test_GitResource_GetDownloadTaskModifier` was not updated to test the new param.

I discovered this while working on implementing #1450; I'll have a fix shortly.

**Comment by vdemeester** [comment]
Ohh :sweat: 

/kind bug
