### ISSUE TITLE
Trigger event or carry out custom shell command after every input and output resource of taskrun get processed

### ISSUE THREAD

**Issue by zeromsi** [tektoncd/pipeline#1733]

**Comment by ImJasonH** [comment]
/kind feature

Can you give some more detail about exactly what you'd like to do? We emit K8s events at every TaskRun completion, but that's only really useful within the cluster.

We've started thinking about configuring Notifications (post to Slack, send an email), which might be what you're looking for?

**Comment by zeromsi** [comment]
> /kind feature
> 
> Can you give some more detail about exactly what you'd like to do? We emit K8s events at every TaskRun completion, but that's only really useful within the cluster.
> 
> We've started thinking about configuring Notifications (post to Slack, send an email), which might be what you're looking for?

That is exactly what I'm looking for. When it'll be added?

**Comment by dibyom** [comment]
Please track it using this issue: https://github.com/tektoncd/pipeline/issues/1740
/close
