### ISSUE TITLE
script mode `set -x` by default when no #! provided

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/pipeline#1735]
# Expected Behavior

When I use script mode without a #! I'd like the "right thing" to happen by default.  For me, the "right thing" is to turn on the shell echo flag and the shell error flag. Shell echo prints the commands executed by a shell script before showing the command's output.  Shell error exits if any command the script calls errors out.

Right now if the user omits the shebang from their script then we insert the following at the start:

```
#!/bin/sh
```

I'd like to propose that we update this default to be:

```
#!/bin/sh
set -e
set -x
```

# Actual Behavior

We don't turn on the shell echo and error flags by default.

# Additional Info

I acknowledge that this might come down to personal preference.  But I want it.

**Comment by vdemeester** [comment]
I think it make sense indeed :angel:

**Comment by skaegi** [comment]
maybe `set -o pipefail` too...

**Comment by skaegi** [comment]
One argument against `set -x` is that we could echo secrets pretty easily. The case could be made it's still a reasonable default as people should be using a hash bang.

**Comment by sbwsg** [comment]
> One argument against set -x is that we could echo secrets pretty easily. The case could be made it's still a reasonable default as people should be using a hash bang.

This is a good point and not something I considered.  I'm torn on this - users presumably would like both ease-of-use (which set -x arguably provides) as well as secure-by-default (served better without set -x).
