### ISSUE TITLE
`tag-images` release task should use crane

### ISSUE THREAD

**Issue by ImJasonH** [tektoncd/pipeline#1746]
`crane` is a CLI tool for interacting with container image registries, built on go-containeregistry and included in that repo. `gcr.io/go-containerregistry/crane` is the CLI packaged as a container image.

[`crane copy`](https://github.com/google/go-containerregistry/blob/master/cmd/crane/doc/crane_copy.md) uses registry API calls to efficiently copy an image from one registry to another, only copying blobs if they're not already present in the destination.

I've observed it to be much faster than `gcloud container images add-tag`, likely due to efficiencies around handling creds, and in being able to avoid Python startup overhead.

**Comment by vdemeester** [comment]
I was gonna propose `skopeo, but `crane` works too.
/cc @afrittoli 

/kind feature
/area test-infra

**Comment by afrittoli** [comment]
> /assign @ImJasonH 

Thanks! I was thinking about this today to build the infra for custom tasks
