### ISSUE TITLE
Allow sidecars to use input params/tekton pod labels

### ISSUE THREAD

**Issue by MLBMatt** [tektoncd/pipeline#1761]
The documentation states that sidecars are ran before tasks but this looks to also mean that input param interpolation isn't performed _and_ the tekton-specific labels aren't available to be mounted as environment variables into the container via the DownstreamAPI.

Is there any plan to support either of these in the near future? Thanks!

**Comment by MLBMatt** [comment]
Our main use case is having a bot report back to Github (using Statuses) during pull requests on step status to pass/fail and provide the link back to the associated pipeline.

**Comment by sbwsg** [comment]
I haven't heard that anyone is actively planning to work on this but I think it would be totally fine to allow tekton variable interpolation in the fields of a sidecar.

**Comment by MLBMatt** [comment]
@sbwsg could you point me in the direction of where interp happens (within the code base) and I can potentially start working on a PR? I started poking around but thought it might be easier to ask :)

**Comment by sbwsg** [comment]
Sure thing!  This is probably a good place to start: https://github.com/tektoncd/pipeline/blob/master/pkg/reconciler/taskrun/resources/apply.go#L100

That function, `ApplyReplacements`, walks over a task spec and switches out instances of `$(foo.bar.baz)` for whatever value `foo.bar.baz` contains.

**Comment by MLBMatt** [comment]
@sbwsg do you know at what point the tekton-specific pod labels are added as well? I'm looking to mount a couple pod labels as environment variables into my sidecar as well, but it looks like the sidecar is started before the tekton-specific labels have been applied to the pod (guessing they're dynamically added by some bootstrapping?)

**Comment by sbwsg** [comment]
That happens in the `makeLabels` func of `pkg/pod/pod.go` I believe.
