### ISSUE TITLE
Add imagePullSecrets to PodTemplate

### ISSUE THREAD

**Issue by ImJasonH** [tektoncd/pipeline#1779]
In K8s, Pods can specify a `imagePullSecrets` which identifies K8s secrets that the container runtime should use to authorize container image pulls when starting a Pod ([K8s docs](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/)). This potentially provides creds to the container runtime (docker, containerd, etc.) in cases when the image is not publicly available.

This isn't exposed in a TaskRun's `podTemplate` ([`PodTemplate` type](https://godoc.org/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1#PodTemplate)), to be added to the underlying Pod's configuration.

Exposing this would allow Tekton users to declare K8s secrets that should be used to pull images specified in `steps`.

/kind feature
/area api

**Comment by ImJasonH** [comment]
On further consideration I don't think we urgently need this, since you can already add pull secrets to the SA that runs the Pod.

**Comment by kevinyu98** [comment]
we have a similar issue, want to have this feature. I have opened an issue on tekton [2339](https://github.com/tektoncd/pipeline/issues/2339)

**Comment by skaegi** [comment]
/reopen
/assign
There is the serviceAccount workaround but I think this is still reasonable to add based on how some teams would like to use Tekton. If not me I'll find someone to work on adding support.

**Comment by animeshsingh** [comment]
@skaegi @afrittoli please take a look

**Comment by NikeNano** [comment]
If it is fine I will look at this and try to make a PR today for it later this evening :)

**Comment by Tomcli** [comment]
Thanks @NikeNano for adding this feature. I think this issue can be closed.
