### ISSUE TITLE
PipelineRun with pipelineSpecs panics

### ISSUE THREAD

**Issue by chmouel** [tektoncd/pipeline#1785]
# Expected Behavior

An error or a working state

# Actual Behavior

A crash : 

<details>
  <summary>Crash log</summary>
<pre>
{"level":"info","logger":"tekton","caller":"metrics/prometheus_exporter.go:37","msg":"Created Opencensus Prometheus exporter with config: &{tekton.dev/pipeline tekton prometheus 5000000000 9090  false false  }. Start the server for Prometheus exporter."}
{"level":"info","logger":"tekton","caller":"metrics/config.go:243","msg":"Successfully updated the metrics exporter; old config: <nil>; new config &{tekton.dev/pipeline tekton prometheus 5000000000 9090  false false  }"}
{"level":"info","logger":"tekton","caller":"sharedmain/main.go:150","msg":"Starting informers."}
{"level":"info","logger":"tekton","caller":"sharedmain/main.go:156","msg":"Starting controllers..."}
{"level":"info","logger":"tekton.pipeline-controller","caller":"controller/controller.go:280","msg":"Starting controller and workers","knative.dev/controller":"pipeline-controller"}
{"level":"info","logger":"tekton.pipeline-controller","caller":"controller/controller.go:290","msg":"Started workers","knative.dev/controller":"pipeline-controller"}
{"level":"info","logger":"tekton.pipeline-controller","caller":"pipelinerun/pipelinerun.go:114","msg":"Reconciling 2019-12-23 12:22:38.271615838 +0000 UTC m=+20.559734881","knative.dev/controller":"pipeline-controller"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1470ca3]

goroutine 370 [running]:
github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun.(*Reconciler).reconcile(0xc00074e370, 0x1bc3840, 0xc000544c30, 0xc000c44fc0, 0x16, 0xc000c69f60)
	/go/src/github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun/pipelinerun.go:297 +0x963
github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun.(*Reconciler).Reconcile(0xc00074e370, 0x1bc3840, 0xc000544c30, 0xc000c883c0, 0x2c, 0xc000c70340, 0x1bc3840)
	/go/src/github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun/pipelinerun.go:179 +0x67b
knative.dev/pkg/controller.(*Impl).processNextWorkItem(0xc0007cb180, 0xc00032c700)
	/go/src/github.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller/controller.go:335 +0x680
knative.dev/pkg/controller.(*Impl).Run.func1(0xc000c4d0a0, 0xc0007cb180)
	/go/src/github.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller/controller.go:285 +0x5b
created by knative.dev/pkg/controller.(*Impl).Run
	/go/src/github.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller/controller.go:283 +0x1ef
</pre>
</details>

# Steps to Reproduce the Problem

1. Import buildah task
2. Create PipelineResource for `git` and `image` output
3. Create a PipelineRun with pipelineSpec like this : 

```yaml
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: pipeline-uno
spec:
  resources:
  - name: git
    resourceRef:
      name: repo-ein
  - name: image
    resourceRef:
      name: image-dois

  pipelineSpec:
    tasks:
      - name: build-ehad
        taskRef:
          name: buildah
```

4. Observe controller output

# Additional Info

This is using last night build from git, available [here](https://raw.githubusercontent.com/openshift/tektoncd-pipeline/release-next/openshift/release/tektoncd-pipeline-nightly.yaml) as well

**Comment by bobcatfish** [comment]
We should fix panics ASAP! Adding this to our current milestone.
