### ISSUE TITLE
TaskRun Pod exceeded available resources 

### ISSUE THREAD

**Issue by zjq123456** [tektoncd/pipeline#1791]
# Expected Behavior
Pod init success
# Actual Behavior
Task Step Resources configuration:
resources:
        limits:
          cpu: '1'
          memory: 1Gi
        requests:
          cpu: 20m
          memory: 10Mi

TaskRun status is 'TaskRun Pod exceeded available resources, reattempted 1 times: pods "hystrix-test-statefulsets-pod-f36c2f" is forbidden: exceeded quota: project1030-quota, requested: limits.memory=9Gi, used: limits.memory=1424Mi, limited: limits.memory=10Gi', why?

**Comment by vdemeester** [comment]
@zjq123456 thanks for the issue. Can you share the whole task yaml ? (or at least a reproductible yaml). It might be a bug on how we handle those limits.

/kind question
/kind bug
/triage needs-information

**Comment by sbwsg** [comment]
Given that this issue is now 4 months old I'm going to close it. @zjq123456 please go ahead and reopen if you want to provide the requested information and we can continue to help from there.  Many thanks!
