### ISSUE TITLE
Expand workspace support to pipelines and pipelineruns

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/pipeline#1802]
# Expected Behavior

Workspaces should be declarable in a pipeline and bindable in a pipelinerun.  Threading a workspace through multiple tasks should allow for files to be shared across those tasks (if using the correct volume source types - PVC, configmap, secret).

We may also want to explore some kind of "from" syntax - a PipelineTask could declare that it wants the workspace "from" a prior pipeline task and Tekton would be responsible for exposing whatever volume source backs that workspace to both tasks.

# Actual Behavior

At the moment we don't have any of the workspace types implemented for pipelines or pipelineruns.

This is a follow-on task from #1438

**Comment by vdemeester** [comment]
@sbwsg  #1866 being merged, I guess this could be closed ?

**Comment by sbwsg** [comment]
:+1: yes indeed!
