### ISSUE TITLE
Config map names should be customizable, or at least prefixable

### ISSUE THREAD

**Issue by abayer** [tektoncd/pipeline#1805]
# Expected Behavior

The various config maps used by Tekton Pipeline (`config-artifact-bucket`, `config-logging`, etc) should be able to be given custom names, to avoid potential collisions with other services.

# Actual Behavior

They can't. =)

# Steps to Reproduce the Problem

1. Change the `name` of one of the config maps.
2. Anything referring to that config map won't work.

# Additional Info

For the standard usage, this isn't a problem, since the config maps go into the `tekton-pipelines` namespace, but in Jenkins X, we put everything in the `jx` namespace along with...lots of other junk. It'd be really handy if we could at the least prefix the config map names to guarantee uniqueness. I haven't thought through the implementation details, but maybe something like an optional argument to the `controller` and `webhook` to provide a prefix for the various config map names would work.

**Comment by abayer** [comment]
Looks like the prefix idea would be a challenge for `config-observability` since that config map is only referenced from `knative.dev/pkg` code...

**Comment by bobcatfish** [comment]
I think we'd be open to this if anyone wants to do the work!

**Comment by jerop** [comment]
@dibyom and I looked into this, and found that all config maps are customizable except for `feature-flags` config map which is fixed in #2363
