### ISSUE TITLE
Tekton should not set task as Succesfull when we have steps OOMKilled 

### ISSUE THREAD

**Issue by chmouel** [tektoncd/pipeline#1806]
# Expected Behavior

Task set as Failed

# Actual Behavior

Tak set as Success

# Steps to Reproduce the Problem

1. Running a task (from the e2e tests) that gets OOMKilled by the controller
2. getting the task status with `kubectl get` :
```
% kubectl get taskrun build-push-run-output-image
NAME                          SUCCEEDED   REASON      STARTTIME   COMPLETIONTIME
build-push-run-output-image   True        Succeeded   104m        103m
```

It says `Succeeded` when it shoudl say `Failed`, 

kubernetes sets the exitCode when OOMKilled as `exitCode 0`

# Additional Infos

<details>
  <summary>Task status with a OOMkilled steps</summary>
<pre>
 {
  "completionTime": "2020-01-06T10:46:43Z",
  "conditions": [
    {
      "lastTransitionTime": "2020-01-06T10:46:43Z",
      "message": "All Steps have completed executing",
      "reason": "Succeeded",
      "status": "True",
      "type": "Succeeded"
    }
  ],
  "podName": "build-push-run-output-image-pod-dvhwr",
  "resourcesResult": [
    {
      "digest": "",
      "key": "commit",
      "name": "",
      "resourceRef": {},
      "value": "6ed7aad5e8a36052ee5f6079fc91368e362121f7"
    },
    {
      "digest": "sha256:05f95b26ed10668b7183c1e2da98610e91372fa9f510046d4ce5812addad86b5",
      "key": "",
      "name": "skaffold-image-leeroy-web-output-image",
      "resourceRef": {},
      "value": ""
    },
    {
      "digest": "",
      "key": "digest",
      "name": "",
      "resourceRef": {
        "name": "skaffold-image-leeroy-web-output-image"
      },
      "value": "sha256:05f95b26ed10668b7183c1e2da98610e91372fa9f510046d4ce5812addad86b5"
    }
  ],
  "startTime": "2020-01-06T10:45:44Z",
  "steps": [
    {
      "container": "step-build-and-push",
      "imageID": "registry.access.redhat.com/ubi8/ubi-minimal@sha256:a5e923d16f4e494627199ebc618fe6b2fa0cad14c5990877067e2bafa0ccb01f",
      "name": "build-and-push",
      "terminated": {
        "containerID": "cri-o://e3bb640db39a6ddece571649517be26b44212da52e41c35c582f901c700e0eb7",
        "exitCode": 0,
        "finishedAt": "2020-01-06T10:46:39Z",
        "reason": "OOMKilled",
        "startedAt": "2020-01-06T10:46:22Z"
      }
    },
    {
      "container": "step-echo",
      "imageID": "registry.access.redhat.com/ubi8/ubi-minimal@sha256:a5e923d16f4e494627199ebc618fe6b2fa0cad14c5990877067e2bafa0ccb01f",
      "name": "echo",
      "terminated": {
        "containerID": "cri-o://5e80a9e852d01086116723ca4fe3f9c2030db9e061bdefc7144281060324558f",
        "exitCode": 0,
        "finishedAt": "2020-01-06T10:46:40Z",
        "reason": "Completed",
        "startedAt": "2020-01-06T10:46:25Z"
      }
    },
    {
      "container": "step-create-dir-builtimage-wt744",
      "imageID": "registry.access.redhat.com/ubi8/ubi-minimal@sha256:a5e923d16f4e494627199ebc618fe6b2fa0cad14c5990877067e2bafa0ccb01f",
      "name": "create-dir-builtimage-wt744",
      "terminated": {
        "containerID": "cri-o://26e01a252641c3c79896f586fa40c7b64fc3d367ed166b2d73814a9215b7ce4c",
        "exitCode": 0,
        "finishedAt": "2020-01-06T10:46:31Z",
        "reason": "Completed",
        "startedAt": "2020-01-06T10:46:18Z"
      }
    },
    {
      "container": "step-git-source-skaffold-git-output-image-wzsrc",
      "imageID": "image-registry.openshift-image-registry.svc:5000/ci-openshift-pipelines/git-init@sha256:b935e507ddd6183999232dc7857dca6408b5648972ed25d85c6a1ce99df16460",
      "name": "git-source-skaffold-git-output-image-wzsrc",
      "terminated": {
        "containerID": "cri-o://c6d3bf400dd9bc863e6d2102bbb8e37e01d07062af1b2ab383f935b19c9c6369",
        "exitCode": 0,
        "finishedAt": "2020-01-06T10:46:38Z",
        "message": "[{\"name\":\"\",\"digest\":\"\",\"key\":\"commit\",\"value\":\"6ed7aad5e8a36052ee5f6079fc91368e362121f7\",\"resourceRef\":{}}]",
        "reason": "Completed",
        "startedAt": "2020-01-06T10:46:20Z"
      }
    },
    {
      "container": "step-image-digest-exporter-5dlgk",
      "imageID": "image-registry.openshift-image-registry.svc:5000/ci-openshift-pipelines/imagedigestexporter@sha256:92c8aca487bb1d19cd059637598dd6c4c42326a83c12636d3423258220391905",
      "name": "image-digest-exporter-5dlgk",
      "terminated": {
        "containerID": "cri-o://d93ff6062cb77e6540c4578ae505bd95625f7dd84e8a5f3c363a70d8e6a5e64d",
        "exitCode": 0,
        "finishedAt": "2020-01-06T10:46:41Z",
        "message": "[{\"name\":\"skaffold-image-leeroy-web-output-image\",\"digest\":\"sha256:05f95b26ed10668b7183c1e2da98610e91372fa9f510046d4ce5812addad86b5\",\"key\":\"\",\"value\":\"\",\"resourceRef\":{}},{\"name\":\"\",\"digest\":\"\",\"key\":\"digest\",\"value\":\"sha256:05f95b26ed10668b7183c1e2da98610e91372fa9f510046d4ce5812addad86b5\",\"resourceRef\":{\"name\":\"skaffold-image-leeroy-web-output-image\"}}]",
        "reason": "Completed",
        "startedAt": "2020-01-06T10:46:26Z"
      }
    }
  ]
}
</pre>
</details>

**Comment by vdemeester** [comment]
#1812 has been merged, we can close this one
/close
