### ISSUE TITLE
Support Internal CA mount

### ISSUE THREAD

**Issue by kasuboski** [tektoncd/pipeline#1814]
# Expected Behavior
I can specify certs to be used by all containers in tekton pipelines

# Actual Behavior
I'm able to add certs in tasks by mounting them in as a configmap in a stepTemplate, but I don't see how to do this for a Condition.

So the condition fails to checkout the git repo that's used as a resource. This could potentially be an issue if we want to connect to other internal services i.e. not just an issue with resources.

# Steps to Reproduce the Problem

1. Create a condition that uses a resource whose cert isn't trusted
2. Have it fail on cert issues.

# Additional Info
I saw there's a way to disable sslVerify for git resources, but I'd rather not and that would only fix this for that specific case. I couldn't find anything listed in the docs and doesn't seem like Conditions support volume mounts.

**Comment by bobcatfish** [comment]
> I'm able to add certs in tasks by mounting them in as a configmap in a stepTemplate, but I don't see how to do this for a Condition.

I'm surprised that Conditions don't have stepTemplates applied to them, that's not what'd I'd expect! Sounds kind of like a bug to me.

@kasuboski if we applied stepTemplates to Conditions would that work for you?

**Comment by kasuboski** [comment]
That would make it workable. I think my ideal would be more of a cluster wide setup similar to how ArgoCD works [example](https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/#repositories-using-self-signed-tls-certificates-or-are-signed-by-custom-ca).

The default podTemplate parameter [in the install configmap](https://github.com/tektoncd/pipeline/blob/master/docs/install.md#customizing-basic-execution-parameters) looks close, but doesn't seem like you can mount anything.

**Comment by kunyan** [comment]
This issue should not be closed !

Mount a file , expectably mount a certificate is really important for the people who is using self-signed certificate git server, maven mirror, npm mirror and images registry

**Comment by nikhil-thomas** [comment]
> This issue should not be closed !
> 
> Mount a file , expectably mount a certificate is really important for the people who is using self-signed certificate git server, maven mirror, npm mirror and images registry

👍 
/reopen

**Comment by nikhil-thomas** [comment]
cc @vdemeester

**Comment by nikhil-thomas** [comment]
@waveywaves Hi, are you active on this issue at present. 😇 🧑‍💻 
if yes, 🏄 🧑‍💻 👍 
if no, could you add a `help-wanted` label 🙂

**Comment by tricktron** [comment]
Still relevant but should be fixed with #9421.
