### ISSUE TITLE
Improve debuggability of PullRequest PipelineResource

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#1818]
# Expected Behavior

If I make simple mistakes in my usage of the PullRequest PipelineResource, I should get an informative error. For example errors like:

- Using the wrong `fieldName` for the secret (#1777)
- Using the wrong format for a file that represents a mutation to make (e.g. a comment)

# Actual Behavior

In some cases, things just succeed silently but do nothing. In other cases you get #1777 where things fail cryptically.

# Steps to Reproduce the Problem

See #1777 to repro the `fieldName` issue (basically use something besides `authToken` for the secret https://github.com/tektoncd/pipeline/blob/master/docs/resources.md#pull-request-resource).

To reproduce an issue where the wrong format is used, you can use the old format (e.g. https://github.com/bobcatfish/catservice/blob/master/tekton/set-status.yaml) for a status update (pre #1550). The old format was:

```bash
        cat <<EOF > /workspace/output/pr/status/tekton.json
        {
          "ID": "tekton",
          "Code": "$(inputs.params.status)",
          "Description": "Tekton is running"
        }
        EOF
```

The new format is:

```bash
        cat <<EOF > /workspace/output/pr/status/poop.json
        {
          "Label": "poop",
          "State": "$(inputs.params.status)",
          "Desc": "Tekton is running"
        }
        EOF
```

When I try to use the wrong format, the Task silently passes and in the logs I can see:

```
{"level":"info","ts":1578434462.1463728,"logger":"fallback-logger","caller":"pullrequest/api.go:284","msg":"Skipping setting  because it already matches","resource_type":"pullrequest","mode":"upload","provider":"github","owner":"bobcatfish","repo":"tekton-lab","pr":"4"}
```

And then I sadly gaze at my open pull request where nothing has happened (true story).

# Additional Info

Since as @wlynch has pointed out that some of the trouble is the way the github api responds (e.g. if you dont specify the token properly, you end up with a 404 from github), one idea for how we can handle this is to add more validation:

- If we see an unexpected fieldname in `secrets`, fail early
- Have pullrequest-init do as much validation as possible on the format of the files on disk

**Comment by adshmh** [comment]
@bobcatfish if there are other validations that would be helpful, I can submit a PR. So far, the `secrets` field and the uploaded `status` are covered.

**Comment by bobcatfish** [comment]
I think it's reasonable to close this for now, esp. since the future of this pipeline resource is uncertain. I think we'll be supporting this logic somewhere regardless of whether it's part of a pipelineresource or not but i think it's fine to close this for now.
