### ISSUE TITLE
Raciness in TestDAGPipelineRun

### ISSUE THREAD

**Issue by chmouel** [tektoncd/pipeline#1820]
I am often getting flakyness in TestDAGPipelineRun, looking at the debug it's seems that the pipelinerun gets created before the pipeline has finished to be created : 

<img width="1365" alt="image" src="https://user-images.githubusercontent.com/98980/71962051-ef05b300-31f8-11ea-8d2d-d210f3774a98.png">

when the Pipeline do exist : 

<img width="1390" alt="image" src="https://user-images.githubusercontent.com/98980/71962086-004ebf80-31f9-11ea-8e4e-4f1c2934520c.png">

I believe adding a small timeout between the creation of the pipeline and the pipelinerun would 'fix' it...

/kind flake
/area testing

**Comment by vdemeester** [comment]
@chmouel we should use the `wait` functionnality (from k8s) to "wait" for the given `Task` or `Pipeline` to be created, instead of a "sleep" timeout :angel:

**Comment by chmouel** [comment]
@vdemeester Yep on it already https://github.com/tektoncd/pipeline/commit/32e3157d3fbf131a12b50cc968a5f8b00d970817 :-D

**Comment by chmouel** [comment]
I don't think i am able to reproduce this properly, i think we can close this

**Comment by JeromeJu** [comment]
Looks like this is recurring:
https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/7524/pull-tekton-pipeline-beta-integration-tests/1740399408094121984
```
   stream.go:305: E 16:11:48.558 tekton-pipelines-controller-ff89c9df6-2zwxv [github.com.tektoncd.pipeline.pkg.reconciler.taskrun.Reconciler] [arendelle-76hfr/d-a-g-pipeline-run-fsiewcmm-pipeline-task-2-parallel-1] Returned an error err=pods "d-a-g-pipeline-run-fsiewcmm-pipeline-task-2-parallel-1-pod" not found
    stream.go:305: E 16:11:48.558 tekton-pipelines-controller-ff89c9df6-2zwxv [github.com.tektoncd.pipeline.pkg.reconciler.taskrun.Reconciler] [arendelle-76hfr/d-a-g-pipeline-run-fsiewcmm-pipeline-task-2-parallel-1] Reconcile error err=pods "d-a-g-pipeline-run-fsiewcmm-pipeline-task-2-parallel-1-pod" not found
    dag_test.go:151: Error waiting for PipelineRun to finish: "d-a-g-pipeline-run-fsiewcmm" failed
