### ISSUE TITLE
test/builder namespace args are largely unnecessary

### ISSUE THREAD

**Issue by ImJasonH** [tektoncd/pipeline#1824]
In e2e tests, clients returned from `setup(t)` are only able to create resources in the namespace created by `setup(t)`. Attempting to create resources in other namespaces results in an error.

Test builders like `tb.Task`, `tb.TaskRun`, etc., take a `namespace` arg that, for e2e tests, must be the `namespace` value returned from `setup(t)`. Passing `""` as the namespace is also valid in e2e tests, since the namespaced clients default to that namespace.

`tb.Task` et al should not require a `namespace` arg, and should instead use the default one. e2e tests will create resources in the test's namespace by default. Unit tests largely don't care what namespace they're defining resources for, and most of them pass some meaningless string like `"banana"` just to appease the required arg.

If a test does care to specify its namespace, we can define a `TaskOp` (etc.) to specify it: `tb.Task("my-task", tb.Namespace("my-namespace"))`

/kind cleanup

**Comment by sbwsg** [comment]
Fixed by #2412
