### ISSUE TITLE
missing fields `error` doesn't give much informations

### ISSUE THREAD

**Issue by chmouel** [tektoncd/pipeline#1844]
# Expected Behavior

Add information about the missing fields

# Actual Behavior

No missing fields displayed..

```
Error from server (InternalError): error when creating "push-images-release.yaml": Internal error occurred: admission webhook "webhook.tekton.dev" denied the request: mutation failed: missing field(s):
```

# Steps to Reproduce the Problem

Create a yaml task with missing fields and try to apply it with `kubectl`

/kind bug

**Comment by vdemeester** [comment]
@chmouel :thinking: Can you share the `yaml` used ? They should be listed, so yeah this is definitely a bug :stuck_out_tongue:

**Comment by chmouel** [comment]
yeah in this case this was a misaligned (so missing) `spec:`
