### ISSUE TITLE
`Reason`  message double quote the quotes

### ISSUE THREAD

**Issue by chmouel** [tektoncd/pipeline#1845]
# Expected Behavior

Just one quote

# Actual Behavior

Double quote, i.e: 

```
      message: 'invalid input params: didn''t need these params but they were provided
```

# Steps to Reproduce the Problem

Get an error in task validation (for eg) and watch the double quotes in all its glory

# Additional Info

It's just cosmetic, but that may get us a strong adoption in the cloud native entreprise ecosystem if fixed..

**Comment by bigkevmcd** [comment]
I don't think this is an issue in Tekton, it's the string being escaped in YAML.

tkn is rendering the message fine

```shell
$ tkn taskrun describe run-test-task
Name:        run-test-task
Namespace:   default
Task Ref:    test-task

Status
STARTED          DURATION    STATUS
12 seconds ago   ---         Failed(TaskRunValidationFailed)

Message
invalid input params: didn't need these params but they were provided anyway: [unknown]
```

and getting it as `-o json` instead of `-o yaml` looks fine too:

```json
    "status": {
        "conditions": [
            {
                "lastTransitionTime": "2020-02-13T17:15:32Z",
                "message": "invalid input params: didn't need these params but they were provided anyway: [unknown]",
                "reason": "TaskRunValidationFailed",
                "status": "False",
                "type": "Succeeded"
            }
        ],
        "podName": "",
        "startTime": "2020-02-13T17:15:32Z"
    }
```

**Comment by chmouel** [comment]
Cool cool I guess there is not much to do with this issue and we can close it, thanks for tracking this down....

/close
