### ISSUE TITLE
PullRequest Resource e2e tests

### ISSUE THREAD

**Issue by wlynch** [tektoncd/pipeline#1867]
I thought there was an issue for this already, but I couldn't find one. If there is another, feel free to close this as a duplicate. :smiley: 

We should add e2e tests for the pull request resource. This should test:

- GitHub, GitLab providers (incl custom domains)
- Should be able to work with the real providers if desired.
- Should have a local, non-authenticated mode as an approximation for local presubmit testing.

/assign wlynch

**Comment by sbwsg** [comment]
Moving to the beta milestone.  We may well introduce this in an RC instead.
