### ISSUE TITLE
Add Versioning Information in README for Examples

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/pipeline#1870]
As described in #1860, examples in this repo are designed to work against [what's in master](https://github.com/tektoncd/pipeline/pull/1860#issuecomment-574102278). However, we should expect that users will be using older versions of pipelines when they come to look for examples.

We should include some information on how examples are versioned. My thought on this is that we should make people aware that examples for specific versions of pipelines are preserved in branches of this repository. This can be included in the [examples README](https://github.com/tektoncd/pipeline/tree/master/examples) as described in this [comment](https://github.com/tektoncd/pipeline/pull/1860#issuecomment-574197888) from #1860.

It may also be nice to communicate in some way how backwards compatible an example is.

/kind documentation

**Comment by bobcatfish** [comment]
One thing that might help here @danielhelfand is that we are in the process of adding versioned docs at tekton.dev (definitely not there yet), https://github.com/tektoncd/website/pull/14 is a step along the way.

Once we have that we can include the examples maybe in those docs as well? I think the next step if we want to do that would be opening an issue in tektoncd/website and/or bringing it up in the tekton docs WG meeting (https://github.com/tektoncd/community/blob/master/working-groups.md#documentation)

(But imo it'll be more clear what the next step is once we have the new website up)

@spomorski 
@michaelawyu

**Comment by danielhelfand** [comment]
@bobcatfish Sounds great! I do agree that the goal should be to eventually have more users come through the website for information than GitHub. So definitely that is a better way to communicate versioning than the examples readme.Perhaps a dropdown similar to what the Knative site amongst others does for allowing the user to select the version from a dropdown and then having corresponding docs appear would be great. 

I do still think it would be helpful to document in the main README itself as a means of meeting people where they are when they find Tekton, but I can definitely open an issue around versioned docs/examples for the website.

**Comment by dibyom** [comment]
The ReadTheDocs section of Readme now has examples for each version. Is that enough or is there more work here @danielhelfand ?

**Comment by danielhelfand** [comment]
Sorry I missed this! Yes, I think the versioned docs makes sense.
