### ISSUE TITLE
Permissions on workspace directory

### ISSUE THREAD

**Issue by kameshsampath** [tektoncd/pipeline#1872]
/kind bug

The permissions on the workspace directory is causing the steps of the Task to fail when using `runAsUser` as part of  securityContext.  As a matter of fact the when using `securityContext`  in stepTemplate is even preventing the git clone to happen because of permission issue.

Tekton version `v0.9.2`

# Expected Behavior
The steps should honour the permissions via `runAsUser`

# Actual Behavior

```[git-source-git-source-kntsc] {"level":"info","ts":1578993616.4258602,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/refs/heads/master: no such file or directory"}
[git-source-git-source-kntsc] {"level":"error","ts":1578993616.4289017,"logger":"fallback-logger","caller":"git/git.go:40","msg":"Error running git [init /workspace/source]: exit status 1\n/workspace/source/.git: Permission denied\n","stacktrace":"github.com/tektoncd/pipeline/pkg/git.run\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:40\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:56\nmain.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:40\nruntime.main\n\truntime/proc.go:203"}
[git-source-git-source-kntsc] {"level":"fatal","ts":1578993616.4289653,"logger":"fallback-logger","caller":"git-init/main.go:41","msg":"Error fetching git repository: exit status 1","stacktrace":"main.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:41\nruntime.main\n\truntime/proc.go:203"}
```

# Steps to Reproduce the Problem

1. Create build resources using https://gist.github.com/kameshsampath/90a2031c0d3b55dc982e3789900dac4f
2. Create a tekton task using https://gist.github.com/kameshsampath/9602210425471d1104e16fb8ad953cdb
3. Run the Tekton task 
`tkn start build-and-list-target --inputresource=git-source `

# Additional Info

The task work works without issue in Tekton v0.8.0

CC: @vdemeester , @hrishin

**Comment by vincent-pli** [comment]
It's because the `init container`s not merge the `stepTemplate` and still run with `root`.
In version 0.8 we do the merge.  

if no specific reason i think it's a bug

**Comment by kameshsampath** [comment]
@vincent-pli  - but then the user I am running with `runAsUser` belongs to group `root` and he should be able to create sub directories under `/workpace` but that is not happening as well .  I used `stepTemplate` as just an aggregation, but the Task step fails after `git-source` as well with same permission issue.

**Comment by vincent-pli** [comment]
@kameshsampath 
The `/workspace` is 777 permission , so your 'git-init' could create folder, that's correct.

but problem is there is `workingDir` in your `step` configuration, this will raise a `working-dir-initializer` in `init container`, this container will run as `root` as I mentioned in last comment, the container will create path `/workspace/source/$(inputs.params.contextDir)` with `drwxr-xr-x root`.

That's will raise permission denied when your `git-init` try to create folder in `/workspace/source/`, since `git-init` is run with user 10001.

**Comment by kameshsampath** [comment]
@vincent-pli  thanks for the explanation . What is the way if it has to be run as underprivileged user ? the whole idea is that I dont want the build to be run as `root` and hence made `10001` part of the `root` group.

**Comment by vincent-pli** [comment]
@kameshsampath 
Try add `podTemplate/securityContext/fsGroup` to your `Taskrun` definition.

**Comment by bobcatfish** [comment]
@kameshsampath did @vincent-pli 's suggestion solve your issue?

**Comment by kameshsampath** [comment]
Yes. It did thanks.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by anandjaisy** [comment]
```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: clone-read-run-
spec:
  pipelineRef:
    name: clone-read
  podTemplate:
    securityContext:
      fsGroup: 65532
```

**Comment by luysantana** [comment]
> > podTemplate:
> > securityContext:
> > fsGroup: 65532
> 
> That still didn't work for me, only happends when i try to use a persistentVolumeClaim
> 
> ```
> apiVersion: triggers.tekton.dev/v1beta1
> kind: TriggerTemplate
> metadata:
>   name: tt-github-pr-trigger-template-{{ .Values.projectName }}
> spec:
>   params:
>     - name: revision
>     - name: deploy
>     - name: repo-url
>     - name: author
>     - name: ref
>     - name: repo-full-name
>     - name: pr-ref
>   resourcetemplates:
>     - apiVersion: tekton.dev/v1beta1
>       kind: PipelineRun
>       metadata:
>         generateName: pr-$(tt.params.pr-ref)-$(tt.params.author)-
>       spec:
>         serviceAccountName: service-account-{{ .Values.projectName }}
>         pipelineRef:
>           name: {{ .Values.projectName}}-pipeline
>         podTemplate:
>           securityContext:
>             fsGroup: 65532
>         workspaces:
>           - name: shared-data
>             persistentVolumeClaim:
>               claimName: pvc-cache-{{ .Release.Name }}
>         params:
>           - name: repo-url
>             value: $(tt.params.repo-url)
>           - name: revision
>             value: $(tt.params.revision)
>           - name: repo-full-name
>             value: $(tt.params.repo-full-name)
>           - name: ref
>             value: $(tt.params.ref)
>           - name: deploy
>             value: $(tt.params.deploy)
> ```

I've the same issue here, trying to run containers with security context but the workspaces are root access.
