### ISSUE TITLE
Ability to skip ssl verification in the pull request pipeline resource

### ISSUE THREAD

**Issue by dibbles** [tektoncd/pipeline#1880]
# Expected Behavior

I should be able to use the pull request pipeline resource in conjunction with a self hosted git server (e.g Gitlab) with a self signed certificate for testing. 

# Actual Behavior

The pullrequest pipelineresource code provides no mechanism by which to create a client with tls insecureSkipVerify set to true.

# Steps to Reproduce the Problem

1. Create and use a pull request pipelineresource against a git server with a self signed certificate
2.
3.

# Additional Info

**Comment by dibyom** [comment]
@dibbles Now what #1881 is merged, can we close this or is there more work remaining?

**Comment by dibbles** [comment]
ah yes.... good spot! Closing.
