### ISSUE TITLE
Allow pullrequest output to create a PullRequest

### ISSUE THREAD

**Issue by bigkevmcd** [tektoncd/pipeline#1883]
# Expected Behavior

When processing the output of a pullrequest resource, if the number is empty, create a new one, and add comments etc to it.

# Additional Info

github.com/jenkins-x/go-scm doesn't seem to have support for creating PRs, to move this forward that would need to be added first.

**Comment by dibyom** [comment]
cc @wlynch

**Comment by bigkevmcd** [comment]
I've made a start on getting go-scm to support this, I'd hope that would land.

But, how should this work? The resource output uses https://github.com/tektoncd/pipeline/blob/master/pkg/pullrequest/api.go#L113 to update the existing PR with changes.

My first thought was that if the loaded `Resource` didn't have a number, then treat it as a new PR, in which case it would create a PR and add the comments etc, but perhaps it should be more explicit?

**Comment by bobcatfish** [comment]
@bigkevmcd thanks for proposing this, this is a feature we've talked about adding but haven't gotten around to! if you find you're not getting responses fast enough here feel free to ping us on slack, and/or we can arrange a video call to talk through the design in real time :D
