### ISSUE TITLE
creds-init: filter a kubernetes secret for a matching pipeline request + GitHub org 

### ISSUE THREAD

**Issue by rawlingsj** [tektoncd/pipeline#1886]
# Expected Behavior
When using GitHub Apps we have multiple tokens (and therefore k8s secrets), one for each GitHub Organisation the App is installed into.  When triggering a pipeline we want to mount the correct token that matches the GitHub org with the git owner of the pipeline request.

# Actual Behavior
Multiple secrets are matched when the creds-init container spec is created so we can have the wrong token mounted for that pipeline.

# Steps to Reproduce the Problem
Have multiple git secrets in a namespace with different tokens used for different GitHub Orgs

# Additional Info
PR that shows an approach that is working well for us on it's way, it might be easier to explain a proposed solution using that

**Comment by bobcatfish** [comment]
> PR that shows an approach that is working well for us on it's way, it might be easier to explain a proposed solution using that

SGTM! @rawlingsj does this mean you'd be okay with taking this on? (no worries if not)

**Comment by rawlingsj** [comment]
> does this mean you'd be okay with taking this on?

great - yeah sure thing @bobcatfish, I've pushed a PR here to show what I was thinking https://github.com/tektoncd/pipeline/pull/1887
