### ISSUE TITLE
$(input.params) not working in task script

### ISSUE THREAD

**Issue by guitcastro** [tektoncd/pipeline#1904]
# Expected Behavior

The script should have the `input.params` replace with the actual value

# Actual Behavior

It seems that the params values are not being set

# Steps to Reproduce the Problem

1. kubectl create -f https://raw.githubusercontent.com/tektoncd/pipeline/master/examples/taskruns/step-script.yaml

Then check the output from the TaskRun from the `params-applied` step:

```
Param values not applied
Got:  $(input.params.PARAM)
```

# Additional Info

obs: I had to remove shebang script and args steps because of the following errors:

`Error from server (BadRequest): error when creating "taskrun.yaml": admission webhook "webhook.tekton.dev" denied the request: mutation failed: script must start with a shebang (#!): steps.script`

`Error from server (BadRequest): error when creating "taskrun.yaml": admission webhook "webhook.tekton.dev" denied the request: mutation failed: script cannot be used with args or command: steps.script`

**Comment by vdemeester** [comment]
Hey @guitcastro, I am guessing your are running `v0.9.2` ? If that's the case, it's normal, this version does require the shebang `#!` in script (see [here](https://github.com/tektoncd/pipeline/blob/v0.9.2/docs/tasks.md#step-script)).

The `docs` folder in master is documentating the `master` branch, not the latest release. You can browser the [`0.9.x`](https://github.com/tektoncd/pipeline/tree/v0.9.2/docs#tekton-pipelines) to make sure you are using the correct documentation version. 

Hopefully, soon we will have a new `tekton.dev` with docs pointing by default to the latest release, it should be less confusing :angel:

**Comment by guitcastro** [comment]
@vdemeester I notice that, although the params still not working :/

**Comment by vdemeester** [comment]
Interested, it should work according to https://github.com/tektoncd/pipeline/pull/1562/files (and that should be in `0.9.x`)

**Comment by guitcastro** [comment]
Ohh, I am using version 0.9.0, I Will try when I get home. Thanks for the help

**Comment by guitcastro** [comment]
Sheband and scripts args did not ship [0.9.2](https://github.com/tektoncd/pipeline/blob/v0.9.2/examples/taskruns/step-script.yaml). However, tasks params example exists and still failing in v0.9.2

**Comment by guitcastro** [comment]
I just update to version 0.10.0 and still goting: 

```
Param values not applied
Got:  $(input.params.PARAM)
```

**Comment by sbwsg** [comment]
I see the issue - the variable needs to be `inputs.params.PARAM`.  Notice `inputs` vs `input`.

**Comment by guitcastro** [comment]
Thanks, @sbwsg, it's working as expected now.
