### ISSUE TITLE
Support Bitbucket Server Pull Request PipelineResource updates

### ISSUE THREAD

**Issue by amlozano** [tektoncd/pipeline#1912]
# Expected Behavior
I am able to update Bitbucket pull request status via PullRequest PipelineResource update
# Actual Behavior
Only GitHub and GitLab are supported in go-scm

# Additional Info
It would be nice to have Bitbucket Pull Request update support in tekton, to complete the tier of most used SCMs.

**Comment by vdemeester** [comment]
Note that `PipelineResource` are going through a [major redesign](https://github.com/tektoncd/pipeline/issues/1673) (and won't make it to the v1beta1 api). But in any case, we are looking into adding support for more provider (be it by PipelineResource or generic Tasks from the catalog).

/kind feature

**Comment by amlozano** [comment]
Oh, I didn't know about that redesign, I am new to the project (as an user) and I didn't find any issue related to the extensibility for BitBucket PR. If you think this can be re-defined in another way or it doesn't make sense anymore after the redesign, feel free to modify or close the ticket.

**Comment by orefalo** [comment]
I am also looking at bitbucket support. that's pretty much a show stopper for me, i can't change scm provider

**Comment by vdemeester** [comment]
@amlozano @orefalo for the time being (aka while PipelineResource are re-designed), you should be able to use *any* provider using a re-usable task. For git, it would be the [`git-clone`](https://github.com/tektoncd/catalog/tree/v1beta1/git) task

**Comment by orefalo** [comment]
Tks,

I gave it another try and I can't figure how to authenticate against my git repo.

**Comment by orefalo** [comment]
nevermind, found this 
https://github.com/tektoncd/pipeline/blob/master/docs/auth.md
