### ISSUE TITLE
Easily access installed version information

### ISSUE THREAD

**Issue by ncskier** [tektoncd/pipeline#1919]
# Expected Behavior
After installing Tekton Pipelines, I expect there to be an easy way to find the version of Tekton Pipelines that I am running.

# Actual Behavior
As far as I know, there is not an easy way to find what version of Tekton Pipelines I have running.

# Steps to Reproduce the Problem

1. Install a version of Tekton Pipelines
2. Try to verify what version of Tekton Pipelines you are running

# Additional Info
According to [these Istio guidelines](https://istio.io/docs/ops/deployment/requirements/), deployments should have an `app` and `version` label. Adding a `version` label to the Tekton Pipelines deployments would make it easy to verify what version of Tekton Pipelines is running.
> The `version` label: This label indicates the version of the application corresponding to the particular deployment.

**Comment by vdemeester** [comment]
/kind feature

We "kinda" have this in https://github.com/tektoncd/pipeline/pull/1758 but I do like the idea of using something that is broadly used in the k8s community :angel:
