### ISSUE TITLE
Update version of knative.dev/pkg

### ISSUE THREAD

**Issue by mattmoor** [tektoncd/pipeline#1940]
I see you are on a fairly old version of Knative's PKG.  There have been some pretty dramatic improvements and fixes to the webhook logic, and I selfishly would like to see Tekton move forward so that I can experiment with pulling into into https://github.com/mattmoor/mink 🤓 

I'd be happy to help wade through some of the breaking changes, but I don't know how to work the go.mod to get started. 😬

**Comment by ImJasonH** [comment]
/kind question

cc @wlynch for go.mod stuff and @vdemeester since he did the last knative/pkg upgrade

**Comment by vdemeester** [comment]
@mattmoor @ImJasonH It's in progress :angel: Just waited for 0.10.0 to be released to re-work on it :wink: 

https://github.com/tektoncd/pipeline/pull/1894

**Comment by vdemeester** [comment]
This can be closed :stuck_out_tongue: 
/close
