### ISSUE TITLE
Failed to create a taskrun

### ISSUE THREAD

**Issue by zeromsi** [tektoncd/pipeline#1941]
Message:
```xml
 Missing or invalid Task default/app-builder1: translating Build to Pod: multiple volumes with same name "tekton-internal-secret-volume-5e2d27b9d5fd052d8cb3c0d6-south-te" 
````

**Comment by ImJasonH** [comment]
/kind bug

Can you give more information about how you got this error? This sounds like a secret was found annotated for Tekton, multiple times?

**Comment by zeromsi** [comment]
Hi @ImJasonH ,
I failed to replay the events. But I think you're right, I removed my secrets and service account, then tried again and it worked.

**Comment by zeromsi** [comment]
Hi @ImJasonH ,
I found the reason, My service account name or secrets name were very large. It throws this weird error message.
