### ISSUE TITLE
Tekton Pipeline Webhook vs Trigger Webhook - what's the differences and how create each of them?

### ISSUE THREAD

**Issue by Dimss** [tektoncd/pipeline#1956]
I'm quite lost with the webhooks configurations. 
So, I'd like to ask  following questions to make things more clear
1. Is it possible to create `Tekton Pipeline Webhook`, and if yes, how? Is there any YAML manifest example? 
2. What is the differences between Tekton **Triggers** Webhooks and Tekton **Pipeline** Webhooks? 
3. I sow the following [issue](https://github.com/tektoncd/pipeline/issues/1832), where guys explains how to create a `Tekton Triggers Webhooks` through Tekton Dashboard Extensions, what if I don't want to use Tekton Dashboard at all to create a `Tekton Triggers Webhooks`, is there any other way to configure it?

**Comment by vdemeester** [comment]
@Dimss :wave: thanks for your question

The notion of `webhook` in this repository (and in `tektoncd/triggers`) is tied to the k8s admission controller (https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/), and has nothing to do with the GitHub webhook or generic webhook. It's an implementation detail that the user shouldn't have to know :stuck_out_tongue:. This repository (`tektoncd/pipeline`) only hold the core objects to define Pipeline and Task and their execution. How they are triggered, is handled by another component (`tektoncd/triggers` in that matter).

But, to create a service that can be registered as a webhook on Github (or Gitlab, …), this is where the [`tektoncd/triggers`](https://github.com/tektoncd/triggers) project comes into place, see the  [getting started](https://github.com/tektoncd/triggers/tree/master/docs/getting-started).

Hopefully, it answers your question :angel: 

/kind question

**Comment by Dimss** [comment]
@vdemeester thanks for your response! 
Just to make sure I understand you correctly 
if I've following deployment 
```
tekton-pipelines-controller   1/1     1            1           3d
tekton-pipelines-webhook      1/1     1            1           3d
tekton-triggers-controller    1/1     1            1           3d
tekton-triggers-webhook       1/1     1            1           3d
```
The `tekton-pipelines-controller` is a Tekton - `K8S Controller` 
The `tekton-pipelines-webhook` is a `K8S Dynamic Admission Webhook` to validate/mutate Tekton `CRs`
The `tekton-triggers-controller` is a Generic/GitHub WebHook  - `K8S Controller`
The `tekton-triggers-webhook` is a `K8S Dynamic Admission Webhook` to validate/mutate Tekton Triggers `CRs'

Am I'm right?

**Comment by vdemeester** [comment]
@Dimss yes, you are almost right :wink: `tekton-triggers-controller` is the controller that manages `tektoncd/triggers` structures (aka `TriggerBinding`, `TriggerTemplate` and `EventListener`) and create services for each `EventListener` (that can be used as GitHub webhook if published, using ingress, openshift routes, or something else)

**Comment by Dimss** [comment]
@vdemeester thank you so much for your help! 
Now everything is clear!
