### ISSUE TITLE
OpenShift install instructions point to Tekton 0.7

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/pipeline#1957]
@Megan-Wright spotted this while working with the Tekton Dashboard, https://github.com/tektoncd/pipeline/blob/master/docs/install.md#installing-tekton-pipelines-on-openshiftminishift mentions `oc apply --filename https://storage.googleapis.com/tekton-releases/latest/release.yaml` which pulls in Tekton 0.7 as evidenced by visiting gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook@sha256:7215a25a58c074bbe30a50db93e6a47d2eb5672f9af7570a4e4ab75e50329131 (an image referenced in that yaml having this information

```
General information
Image type	
Docker Manifest, Schema 2
Media type	
application/vnd.docker.distribution.manifest.v2+json
Virtual size 	
19.7 MB
Created time	
19 September 2019 at 17:19:26 UTC+1
Uploaded time	
19 September 2019 at 17:28:42 UTC+1
Build ID	
—
Container classification
Digest	
sha256:7215a25a58c074bbe30a50db93e6a47d2eb5672f9af7570a4e4ab75e50329131 
Tags	
v0.7.0 
Repository	
github.com/tektoncd/pipeline/cmd/webhook
Project	
tekton-releases
```
)

Instead we should point folks to the release no tags yaml

**Comment by vdemeester** [comment]
The correct link should be https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml and yeah, in that case https://storage.googleapis.com/tekton-releases/pipeline/latest/release.notags.yaml

/kind documentation
