### ISSUE TITLE
Q: Migrate git-init to script mode?

### ISSUE THREAD

**Issue by ImJasonH** [tektoncd/pipeline#1961]
The `git-init` image, used to support `git`-type PipelineResources, invokes a Go binary that drives `git` CLI invocations to clone a repo. 

One of the main benefits of `git-init` was that it made it easy to chain together multiple CLI invocations inside one step, and being Go made it easy to have control flow logic.

However, being a Go binary that wraps the `git` CLI adds a layer of indirection to users interested in understanding/debugging/extending it, since they have to go through the Go code to change its behavior.

Now that we have script mode, `git`-type PipelineResources could simply prepend a step that defines a `script:` to do all the things `git-init` does (i.e., `git init`, `git remote add origin <repo>`, `git fetch origin <revision>`, etc.), removing the indirection. Users could modify the step to add more logging, without having to rebuild the image. The image could simply be the [base image](https://github.com/tektoncd/pipeline/blob/e5d799e176dbde0cc571026cd18cb5ddd4132bf9/images/Dockerfile) we already use for `git-init` to ensure `git` is installed, or an image like [`alpine:git`](https://hub.docker.com/r/alpine/git/).

The disadvantage of this is that `git`-type PipelineResources become dependent on (presumably) Bash scripts, which can grow to unmaintainable sizes. Unit testing is hard in Bash, but `git-init` [has no unit tests](https://github.com/tektoncd/pipeline/tree/e5d799e176dbde0cc571026cd18cb5ddd4132bf9/pkg/git) today anyway.

What do people think about modifying the `git`-type PipelineResource in this way?

/kind question

**Comment by ImJasonH** [comment]
As a concrete example, modify [`GetInputTaskModifier` in `git_resource.go`](https://github.com/tektoncd/pipeline/blob/e5d799e176dbde0cc571026cd18cb5ddd4132bf9/pkg/apis/pipeline/v1alpha1/git_resource.go#L131) to something like [this gist](https://gist.github.com/ImJasonH/99e51197477ee05913519e7dab40fe9e).

**Comment by sbwsg** [comment]
I'm in favor of using script mode. Could we just have it [live as a task in the catalog](https://github.com/tektoncd/catalog/pull/123) instead of committing changes to the pipeline resource?

**Comment by vdemeester** [comment]
As @sbwsg said :angel: I'll update my PR with workspace support and using `script` mode instead :angel: :wink:

**Comment by chmouel** [comment]
Can't be more happy to have one image less to support 👍 

@sbwsg about having it in the catalog, we would need to refer it somehow in release.yaml isnt it ?

**Comment by sbwsg** [comment]
> we would need to refer it somehow in release.yaml isnt it ?

Ahh I hadn't thought of this.  We'd want this to be like a default-installed task that comes along with the tekton controller I expect.

**Comment by bobcatfish** [comment]
@sbwsg I think you mentioned you were working on updating the existing git Task in the catalog - would it make sense to assign this to you?

**Comment by vdemeester** [comment]
@bobcatfish work is happening here : https://github.com/tektoncd/catalog/pull/188
