### ISSUE TITLE
The Controller's Reconciler Files Are Too Long

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/pipeline#1974]
# Expected Behavior

I should be able to (relatively) easily grok the behaviour of a reconciler, figure out where to "cut in" to add new functionality, interpret the code when debugging problems, etc etc.

# Actual Behavior

It can be hard to do this.  The pipelinerun reconciler for example is over 700 lines.  The pipelinerun reconcile func alone is over 200.  It's unclear if or when the sequence of things that happen to a pipeline, its spec, and the eventual pipelinerun, is order-dependent or not without giving the whole file an intensive read-through.  Even after doing this I still find myself jumping around the file trying to remember if I've accidentally stepped on someone else's toes in some other part of the dance.

# Additional Info

It seems like there are at least *some* clear points of refactoring we could attempt (and feel free to add more as you spot them or comment if you disagree that a given part invites a refactor):

* PipelineRun Reconciler has a bunch of funcs related to fetching and creating taskruns with correct labels, annotations, etc etc.  This could be a "taskrun convert" package like we did for pods in the taskrun reconciler.
* PipelineRun Reconciler has a chain of sections that all read essentially as `if err := /* perform some validation / get resources / apply variables */; err != nil { SetCondition(FAILURE) }` that could be made just a tad more abstract/independent/extensible.
* Just in general it feels like there's lots of "mostly isolated" stuff that requires or leaks just a little bit of state that prevents it from being pulled out of the central pipelinerun reconciler package.

**Comment by afrittoli** [comment]
Both for notifications as well for general async actions/hooks, we'll need to clearly identify in the reconcile code the various points of the lifecycle of a resource (pipelinerun/taskrun):
* about to start
* paused
* done (success/failed/timeout/cancelled)

I think it would be nice if the main reconcile loop code could be structure like this:
```
if new:
   run init procedure
if done or paused:
   continue

main reconcile function
  return new status

switch status change:
  run status change specific code
```

**Comment by vdemeester** [comment]
/cc @n3wscott as there is a few movement upstream (knative.dev/pkg), to reduce the same code needed (https://github.com/knative/pkg/pull/947, https://github.com/knative/serving/pull/6714 and https://github.com/knative/sample-controller/pull/167)

But I do agree, the `reconcile` part should be simple, and the rest should be split into several files :stuck_out_tongue_closed_eyes:

**Comment by n3wscott** [comment]
YES!! There is some work needed in knative/pkg reconciler generators to support the crazy serving needs, like the upconvert calls... but knative/serving#6714 totes passes integration 🥇

**Comment by mattmoor** [comment]
We've migrated effectively everything in Knative to use `// +genreconciler` now, and this captures a lot of the best practices we've accumulated over the years in ways that makes it hard to "hold" wrong.  Let us know what support we might provide if you choose to adopt this.

**Comment by bobcatfish** [comment]
I believe it's still true that our reconciler files are longer than we'd like, not sure if it's worth re-opening the issue, but it's definitely something we'd like to see improve!
