### ISSUE TITLE
Is it not using latest docker version to execute tasks?

### ISSUE THREAD

**Issue by maheshwarishikha** [tektoncd/pipeline#1995]
# Expected Behavior
Dockerfile which includes contents like:
FROM maven:3.5.4-jdk-8-alpine **AS builder**
COPY ...
..
...
getting built locally but not through tekton. Ideally it should get built successfully.

# Actual Behavior
Error I get is:
Sending build context to Docker daemon    335MB
Step 1/13 : FROM maven:3.5.4-jdk-8-alpine AS builder
Error parsing reference: "maven:3.5.4-jdk-8-alpine AS builder" is not a valid repository/tag: invalid reference format

why it is so? Got stuck here...Please help.

# More Info
I am using Openshift cluster 3.11 and installed tekton using the following command:
oc apply --filename https://storage.googleapis.com/tekton-releases/pipeline/latest/release.notags.yaml

**Comment by afrittoli** [comment]
Thank you for you bug report @maheshwarishikha .
The error you reported does not come from Tekton itself, it's produced by the tool that you use to build your container image - it looks like it does not support "AS" in the docker file.
What tool do you use? Do you have the YAML of your task to share?

**Comment by vdemeester** [comment]
@maheshwarishikha I am pretty sure that the docker used by openshift 3.11 is a really old version (like docker 1.13, before the swarmkit merge). This means that if you use `docker` (with mounting the docker host volume in your task) to build your dockerfile it won't work as multi-stage wasn't even a thing for docker 1.13.

You should be able to use `kaniko` or `buildah` instead of `docker` to build a multi-stage dockerfile.
As a general rule of thumb, tekton tasks should try to depend as less as possible on what's available in the host of the node they will run in.

**Comment by maheshwarishikha** [comment]
@afrittoli - here is yaml for my task. 

[docker-build-src-code.yaml.zip](https://github.com/tektoncd/pipeline/files/4153126/docker-build-src-code.yaml.zip)

@vdemeester - yes...I am using docker commands directly to build and push the image to registry.

So I need to try kaniko or buildah...as per your suggestion. It was giving some other issues...hence used docker commands. Is there any other way?

**Comment by maheshwarishikha** [comment]
@afrittoli , @vdemeester - I am using kaniko task to build and push as per your suggestion. Now, push is failing with some permissions issue.

Error msg -
error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "docker-registry-default.xx.xxx.appdomain.cloud/tektonpipeline/imagename:latest": UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:tektonpipeline/imagename Type:repository] map[Action:push Class: Name:tektonpipeline/imageapp Type:repository]]

I have created serviceaccount and provided in pipelinerun. Do I need to provide secret somewhere?
I tried creating serviceAccount.yaml file too..but no luck.

For reference files are attached here.
[Code.zip](https://github.com/tektoncd/pipeline/files/4163713/Code.zip)

Kindly suggest. Thanks in advance.

**Comment by maheshwarishikha** [comment]
I understand that I need secret.yaml too....but not understanding that.

apiVersion: v1
kind: Secret
metadata:
  name: pipelinesa-token-7vnnc
  annotations:
    tekton.dev/docker-0: ??
type: kubernetes.io/basic-auth
stringData:
  token: ??
OR username and password is required?

But in case of service account, we login to openshift using token. So not sure which username and password to use.

Please provide your suggestions.

**Comment by dibyom** [comment]
https://github.com/tektoncd/pipeline/blob/master/docs/auth.md#basic-authentication-docker has an example of docker secrets. Not sure about Openshift (perhaps @vdemeester  knows?)
