### ISSUE TITLE
webhook knative.dev/pkg/controller is spitting a lot of error message

### ISSUE THREAD

**Issue by chmouel** [tektoncd/pipeline#1998]
I have seen lately a lot of error mesages due of missing cacert in the webhook logs : 

```
{"level":"info","logger":"webhook","caller":"controller/controller.go:363","msg":"Reconcile failed. Time taken: 115.268µs.","knative.dev/traceid":"5c365bc2-40a6-4e9c-9af6-d6c96d690317","knative.dev/key":"webhook.pipeline.tekton.dev"}
{"level":"error","logger":"webhook","caller":"controller/controller.go:376","msg":"Reconcile error","error":"secret \"webhook-certs\" is missing \"ca-cert.pem\" key","stacktrace":"knative.dev/pkg/controller.(*Impl).handleErr\n\t/workspace/tektoncd-pipeline-git/vendor/knative.dev/pkg/controller/controller.go:376\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\t/workspace/tektoncd-pipeline-git/vendor/knative.dev/pkg/controller/controller.go:362\nknative.dev/pkg/controller.(*Impl).Run.func2\n\t/workspace/tektoncd-pipeline-git/vendor/knative.dev/pkg/controller/controller.go:310"
```

They seem harmless and only shows up at boot time and on webhook but there is quite a few of them (55) and they don't look very nice..

/kind bug

**Comment by vdemeester** [comment]
Right, it creates it at start time, interesting that it prints this 55 times though :sweat: 
/cc @mattmoor

**Comment by afrittoli** [comment]
Dogfooding runs on v0.10.0, however I don't see this error in the logs.
Is this something new in v0.10.1?

**Comment by vdemeester** [comment]
@afrittoli it's on nightlies, and due to the k8s/knative dependency bump #1894

**Comment by mattmoor** [comment]
We should probably quiet the logging, as this is somewhat expected on a fresh install with the Reconciler-based design.  The lifecycle of resources is managed by something external (e.g. operator, addon manager), but the content of those resources is populated dynamically.

Want to open a PR against knative.dev/pkg?

**Comment by chmouel** [comment]
@mattmoor done here! https://github.com/knative/pkg/issues/1047

**Comment by chmouel** [comment]
/close

this is fixed thanks!
