### ISSUE TITLE
How to add imagePullSecrets in a taskSpec?

### ISSUE THREAD

**Issue by zeromsi** [tektoncd/pipeline#2001]

**Comment by dibyom** [comment]
The serviceAccount that the taskrun uses should have access to the imagePullSecret.
Here are a couple of examples:
https://github.com/tektoncd/pipeline/blob/master/examples/taskruns/pull-private-image.yaml
https://github.com/tektoncd/pipeline/blob/master/examples/taskruns/docker-creds.yaml

**Comment by dibyom** [comment]
I'm going to close this issue. Feel free to re-open if it doesn't answer your question.
/close
