### ISSUE TITLE
Deleting PipelineRuns doesn't clean up TaskRuns or pods

### ISSUE THREAD

**Issue by searsaw** [tektoncd/pipeline#2005]
# Expected Behavior
When I delete a PipelineRun, the TaskRuns created for it and the pods for the TaskRuns should be deleted. In addition, deleting the TaskRun should delete the pods associated with it.

# Actual Behavior
Only the PipelineRun is deleted. If I delete a TaskRun, only the TaskRun is deleted.

# Steps to Reproduce the Problem

1. `tkn pr delete some-pipeline-run-name`. The output says it's deleted.
2. `kubectl get pr some-pipeline-run-name`. The output shows it's not found.
3. `kubectl get po -l tekton.dev/pipelineRun=some-pipeline-run-name`. Notice there are still pods.
4. Cry.

TektonCD Pipeline v0.10.1

**Comment by sbwsg** [comment]
Thanks for the report, couple follow-up questions:

1. which version of tkn are you using?
2. Does the same issue occur if you use kubectl to delete the pipelinerun?  i.e. `kubectl delete pipelinerun <name-of-pipelinerun>`?

I recently updated the code of tkn when performing deletes so I'm wondering if I've accidentally broken this behaviour.

**Comment by dibyom** [comment]
What happens if we delete the pipelinerun using kubectl and not tkn? I'd expect the associated taskruns/pods to get deleted too. Is that not the case? Does tkn add additional logic to delete the associated resources?

**Comment by sbwsg** [comment]
> Does tkn add additional logic to delete the associated resources?

No you're right - tkn doesn't add anything to pipelineruns or taskruns to delete the resources created during reconciliation.

I just tested with tkn delete version 0.7.1 against a pipelinerun and I saw the taskruns generated during the pipelinerun deleted as well.  So I'm not sure what's going on here.

**Comment by searsaw** [comment]
Welp, this is embarrassing. I'm not really sure what was happening yesterday, but things seems to be working as intended today. We did some cert rotation and cluster upgrading today. So it's possible something weird was going on, and it got cleared up in the hubbub today.

I'll see myself out...

**Comment by sbwsg** [comment]
All good, thanks for reporting!
