### ISSUE TITLE
tekton yaml linting and dependency scanner, outliner ms-vscode

### ISSUE THREAD

**Issue by gattytto** [tektoncd/pipeline#2019]
there's a tekton pipelines plugin for ms-vscode which also works in eclipse che https://github.com/eclipse/che/issues/15752#issuecomment-582907777

I see there's a ci/cd project called concourse and they have a work in progress for a yaml linter for pipelines and tasks: https://github.com/spring-projects/sts4/tree/master/vscode-extensions/vscode-concourse

right now using the tekton+kubernetes plugin having a ~/.kube/config in the sidecar container and the tekton controller/webhook pods running in the cluster make the plugin work as expected. pressing F1 and using the "kubernetes apply" action over a pipelinerun.yaml offers to create the resource and taskrun can be seen after updating the tekton pipelines section of the IDE.

I hope there's place and time and interest in adding specific linting for the yaml schemas used by tekton. the default yaml plugin already provides outline function
![image](https://user-images.githubusercontent.com/407397/74066519-042b5880-49d6-11ea-97d3-c98a78dd21bb.png)

area/dogfooding

**Comment by vdemeester** [comment]
@gattytto thanks for the issue. There is some started work on that (https://github.com/tektoncd/pipeline/pull/1776) I think :wink: 

/kind feature
/area yamls

**Comment by gattytto** [comment]
ms-vscode extensions can be deployed in eclipse che (Theia web ide that loads ms-vscode extensions) with the help of sidecars to hold the tools, configs and volumes. development environments called workspaces can be defined using yaml devfiles. 

Here is eclipse Che project's issue that follows the adoption of Tekton definitions in the builtin devfile editor. 
https://github.com/eclipse/che/issues/16304

and here is che pr regarding first steps of adoption to Tekton and octant:
https://github.com/che-dockerfiles/che-sidecar-tekton/pull/2
