### ISSUE TITLE
Spam log appearing in step containers

### ISSUE THREAD

**Issue by steveodonovan** [tektoncd/pipeline#2028]
# Expected Behavior

Runtime logs should be clear of tekton related messages, at a glance seems like it would be a controller or init container log message.

# Actual Behavior

A line similar to the one below is appearing at the top of the log for every container created in a taskRun 

`{"level":"info","ts":1581335203.186758,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"KO_DATA_PATH\" does not exist or is empty"}`

# Steps to Reproduce the Problem

1. Create a pipelineRun or TaskRun
2. Check the logs for any container created as a part of this run
3. The log line above appears at the top

# Additional Info
Originally raised in tekton slack by bitsofinfo and alex.sears but I don't see an issue created. 

Happy to take this on if its not already being tracked/tackled elsewhere

**Comment by ImJasonH** [comment]
This comes from https://github.com/knative/pkg/blob/master/logging/config.go#L76 because https://github.com/knative/pkg/blob/master/changeset/commit.go#L37 fails to find the commit SHA which it expects to find symlinked into the kodata directory. I’m not sure why it’s not being symlinked there, but either way pkg should probably just not spam logs in that case anyway.

**Comment by afrittoli** [comment]
This is addressed by https://github.com/tektoncd/pipeline/issues/2028.
knative logger is useful for the Tekton controllers, but not necessarily for the steps themselves.

**Comment by ImJasonH** [comment]
Knative Serving has symlinks set up correctly: https://github.com/knative/serving/tree/master/cmd/controller/kodata

Ours don't: https://github.com/tektoncd/pipeline/tree/master/cmd/controller/kodata

We should add symlinks at cmd/*/kodata/refs to `../../../.git/refs` and confirm this fixes the spam.

**Comment by ImJasonH** [comment]
> This is addressed by #2028.
> knative logger is useful for the Tekton controllers, but not necessarily for the steps themselves.

The entrypoint binary jumps in and spams that for every step, if we get the symlinks in place it should just stop. Using the Knative logger might be useful for that binary if we want to inject more structured logging info.

**Comment by ImJasonH** [comment]
Fixed in #2000
