### ISSUE TITLE
Where is workspaces.md? 

### ISSUE THREAD

**Issue by csantanapr** [tektoncd/pipeline#2036]
In Tekton Slack people pointed out that version 0.10 added support for workspaces, that this is an awesome feature now 🎉 to avoid some of the problems dealing with auto pvc 

So where are the docs?
I can't find them here: https://github.com/tektoncd/pipeline/tree/master/docs

**Comment by AlanGreene** [comment]
Workspaces appear to be documented here:
https://github.com/tektoncd/pipeline/blob/master/docs/pipelines.md#declared-workspaces
https://github.com/tektoncd/pipeline/blob/master/docs/pipelineruns.md #workspaces

**Comment by skaegi** [comment]
There is some more info here -- https://github.com/tektoncd/pipeline/blob/master/docs/tasks.md#workspaces

**Comment by csantanapr** [comment]
Thanks for links @AlanGreene and @skaegi 

I think I'm bit confused

I think there was the concept of "/workspace" directory before tektoncd pipeline version 0.10

Is what's new now is the "Declared workspace" `workspace:` ?

Might be good to have a Note in the docs, stating that something is available on version 0.10+

**Comment by csantanapr** [comment]
Also we should change those markdown anchors `#workspace` they bring zenhub at least for me, better to use `#declared-workspaces`

**Comment by skaegi** [comment]
yes we should use the time honoured `#Workspaces` hack instead

**Comment by bobcatfish** [comment]
> Also we should change those markdown anchors #workspace they bring zenhub at least for me, better to use #declared-workspaces

haha that happens to me too @csantanapr XD

**Comment by bobcatfish** [comment]
> Might be good to have a Note in the docs, stating that something is available on version 0.10+

@csantanapr I think the release notes are probably the best place for the kinds of docs you're describing? The docs we have in the repo are meant to represent the current state.

In this case we've got https://github.com/tektoncd/pipeline/releases/tag/v0.10.0 does that have what you're looking for?

Also note that you can find versioned docs at https://github.com/tektoncd/pipeline#read-the-docs (so the docs pre 0.10.0 won't have workspaces)
