### ISSUE TITLE
Timeout Code Comment for v1alpha2 TaskRunSpec Says Default Timeout is 10 Minutes

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/pipeline#2037]
The code comment for Timeout as part of the TaskRunSpec appears to state the default time of 1 hour incorrectly.

# Expected 

The default timeout is 1 hour as documented [here](https://github.com/tektoncd/pipeline/blob/master/docs/taskruns.md#configuring-default-timeout). 

# Actual 

The [comment](https://github.com/tektoncd/pipeline/blob/52babda84f585fbe4ad6a8dce7a1802d2de513dd/pkg/apis/pipeline/v1alpha2/taskrun_types.go#L46) states the timeout default is 10 minutes.

/kind documentation

**Comment by vdemeester** [comment]
:sweat_smile:
