### ISSUE TITLE
Capture User Information with PipelineRun/TaskRun Creation

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/pipeline#2045]
This [issue](https://github.com/tektoncd/cli/issues/725) was originally opened in the CLI repo for being able to see information about which user started a TaskRun/PipelineRun as part of running a `tkn pipelinerun describe` or `tkn taskrun describe`. 

I am wondering if it makes sense to have a way to capture this information as part of TaskRuns/PipelineRuns by adding this information to the PipelineRunSpec/TaskRunSpec.

As far as how this user information would be captured, the CLI/Dashboard could probably do this fairly easily by capturing the user information and adding it to the PipelineRun/TaskRun, but there would be use cases where it would be difficult to enforce this (e.g., creating a PipelineRun/TaskRun using `kubectl` or events with triggering).

**Comment by bobcatfish** [comment]
@danielhelfand when you say  "user" what would that mean in this case? e.g. would it be the user signed in on the machine that is running the CLI commands?

**Comment by danielhelfand** [comment]
@bobcatfish We had a pretty good explanation in the CLI issue in this [comment](https://github.com/tektoncd/cli/issues/725#issuecomment-585856328). The idea here would be about whoever is authenticated to the cluster and issuing a start of a TaskRun/PipelineRun. In the case of the CLI, it would be whoever is running it locally. 

I think, at the very least, it presents a way for this information to be included if someone wanted to monitor who started certain runs. Whether or not Tekton should actually do all this for whoever is running Tekton, I think is a fair question to ask, but perhaps there should be a way to capture this data.

**Comment by vdemeester** [comment]
This is kinda linked to #2201, or #2100 and part of  #1839 (not the "version" of the resource themselves, but…)

**Comment by vdemeester** [comment]
This is also linked to #994

**Comment by vdemeester** [comment]
@danielhelfand are https://github.com/tektoncd/pipeline/pull/2489 and https://github.com/tektoncd/pipeline/pull/2444 closing this issue ?

**Comment by danielhelfand** [comment]
I think what's missing is how to include user information associated with a TaskRun or PipelineRun. Not sure what the best approach for that would be as far as if an additional property should be specified or maybe labels would be a better approach, and it would fall on client tools to label runs with appropriate user info?
