### ISSUE TITLE
Cloud Event Resource on pipeline completion

### ISSUE THREAD

**Issue by shiyu-dong** [tektoncd/pipeline#2053]
Hello,

This is a follow up on #1922 . I was looking at [Cloud Event Resource](https://github.com/tektoncd/pipeline/blob/master/docs/resources.md#cloud-event-resource) which can send a request to a target `URI` upon `TaskRun` completion.

Is there a similar mechanism for `PipelineRun` completion too? i,e. I want to receive some API call when a pipeline run completes. I could potentially send a cloud event at the end of the "last" task, but if the pipeline run fails in the middle there's no guarantee that the last task will be executed.

Thanks!

/kind question

**Comment by bobcatfish** [comment]
>  I could potentially send a cloud event at the end of the "last" task, but if the pipeline run fails in the middle there's no guarantee that the last task will be executed.

I think that's your best option right now unfortunately! But a couple things are on the way that will make this better:

* https://github.com/tektoncd/pipeline/issues/1684 is in progress and will be adding a syntax that you could use to run on failure / as a "finally" + @dibyom @pritidesai @sbwsg 
* We do want to emit events throughout execution but we don't actually have an issue explicitly about that though it's mentioned in the 2020 roadmap https://github.com/tektoncd/community/pull/77

**Comment by bobcatfish** [comment]
I've added #2082 about emitting events during execution!

**Comment by bobcatfish** [comment]
One more thought, @afrittoli created a demo with the functionality you are describing, and I think what he ended up doing was in the case of a failure, he didn't actually fail the Pipeline, he instead "passed" the pipeline but included information about the failure in the CloudEvent, and then the Pipeline that finally handled it (via triggers) was the one that looked at the data and decided whether to fail or not. Definitely not optimal tho!

**Comment by shiyu-dong** [comment]
> > I could potentially send a cloud event at the end of the "last" task, but if the pipeline run fails in the middle there's no guarantee that the last task will be executed.
> 
> I think that's your best option right now unfortunately! But a couple things are on the way that will make this better:
> 
> * #1684 is in progress and will be adding a syntax that you could use to run on failure / as a "finally" + @dibyom @pritidesai @sbwsg
> * We do want to emit events throughout execution but we don't actually have an issue explicitly about that though it's mentioned in the 2020 roadmap [tektoncd/community#77](https://github.com/tektoncd/community/pull/77)

Thanks for getting back! The demo that @afrittoli had seems to be a little bit hacky and doesn't seems to be a generalizable solution to apply for different pipelines. I think #1684 with a "finally" block will do the trick :)

**Comment by afrittoli** [comment]
This will be addressed as part of https://github.com/tektoncd/pipeline/issues/2082.
We won't be using the pipeline resource for that though.

**Comment by dibyom** [comment]
I'm going to close this in favor of #2082 
/triage duplicate
/close
