### ISSUE TITLE
Add Restful API document

### ISSUE THREAD

**Issue by anxinyf** [tektoncd/pipeline#2055]
# Expected Behavior
Document to describe restful api.

# Actual Behavior
In docs, there's no rest api document.

# Additional Info
I have written the rest api document for Triggers, Dashboard and Pipeline. If need, I will commit these in docs folder.

**Comment by vdemeester** [comment]
Duplicates #1250

**Comment by anxinyf** [comment]
That will be great to generate doc, like swagger or other tools.

**Comment by bobcatfish** [comment]
Note I think this is a duplicate of https://github.com/tektoncd/pipeline/issues/1250

**Comment by anxinyf** [comment]
Yes! I didn't know this issue #1250 before. But These api docs(Pipeline/Dashboard/Triggers) are wrriten manually, maybe some tools are better, like swagger.

**Comment by anneqm** [comment]
Per @anxinyf this item can be closed.

**Comment by shimmerjs** [comment]
Where is the non-go API documentation available?  I'd like to validate my Tekton resources with kubeval.  It isn't clear how this issue was resolved

**Comment by afrittoli** [comment]
It looks like #1250 and #2055 were both closed as duplicate of each other. I think one of the two should stay open? @sbwsg @bobcatfish

**Comment by sbwsg** [comment]
Sorry for the churn but I'm actually going to make #1250 the source of truth here.  The description of that issue aligns more closely with what we want for the project I think - generated documentation from the existing API definition.
