### ISSUE TITLE
Should we keep the vendor directory or not?

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/pipeline#2065]
Since we migrated to go modules a while ago there's been a lingering question of whether we should keep the `vendor` directory or not.  It seems like there are several benefits to keeping it:

1. CI runs faster than if it re-fetches all the deps every time it runs.
2. Some developers are required to include the vendor directory per their company's policies.

This issue is intended to focus the conversation around the vendor directory in one place.

**Comment by dlorenc** [comment]
I just stumbled on this, but I'm in favor of keeping the directory. Without it, it's hard to review the code we're depending on.

**Comment by vdemeester** [comment]
Ah, never commented on this one (but on the go module support, [here](https://github.com/tektoncd/pipeline/pull/1607#issuecomment-558513849)). Overall, I don't see any reason for removing the `vendor` folder.

**Comment by sbwsg** [comment]
I'm going to go ahead and close this.  We can revisit if the question ever arises again in future.
