### ISSUE TITLE
Support Step life-cycle hooks in a "listener" Sidecar

### ISSUE THREAD

**Issue by skaegi** [tektoncd/pipeline#2072]
A frequent request we are hearing from users, is the ability to watch and react as the Steps of a Task proceed without having to necessarily hard-code that logic into Steps. For example firing a Slack message when a particular Step completes or updating a PR as various tests complete.

I wonder if we might re-use a mechanism similar to https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/ to notify a "listener" sidecar. Once notified the sidecar shares the `/workspace` so might run further interesting logic. This might be a way to peel another useful piece of the PipelineResource capability away.

**Comment by sbwsg** [comment]
Relates to https://github.com/tektoncd/pipeline/issues/1460 I think.

**Comment by dibyom** [comment]
Somewhat related to #1740 

Perhaps we can emit CloudEvents that the entrypoint can send to some user defined sink?

**Comment by bobcatfish** [comment]
This does sound to me like what "notifications" are about, what do you think @skaegi ?

To summarize, open issues that might solve this:
* #2082 - Emit events during execution
* #1740 - Notifications and actions

**Comment by skaegi** [comment]
Yes. I guess what I was trying to figure out is if there was some pre-existing approach in Kubernetes that we could use to "act" on the events.
