### ISSUE TITLE
Add e2e Test for PipelineTask Timeout Specified

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/pipeline#2073]
#2038 introduced the ability to define Timeouts for PipelineTasks. There should be an e2e test that covers a PipelineRun failing since a PipelineTask timeout is exceeded for a TaskRun associated with the PipelineRun. 

The TaskRun should fail with a status indicating the Timeout was exceeded, and the PipelineRun should have a failed status due to the TaskRun failing.

**Comment by bobcatfish** [comment]
Just a side note (+ reviewers @sbwsg @vdemeester ) that in general we try to include the tests for the feature we're adding in the same PR as we add the feature (https://github.com/tektoncd/community/blob/master/standards.md#principles)

**Comment by bobcatfish** [comment]
Are you planning to add this as well @danielhelfand aka can I assign it to you?

**Comment by danielhelfand** [comment]
@bobcatfish Apologies for moving a bit too fast on this and will know for the future. Yes, I would be more than happy to pick this up. 

/assign
