### ISSUE TITLE
Embed condition spec into pipeline

### ISSUE THREAD

**Issue by siamaksade** [tektoncd/pipeline#2079]
# Expected Behavior
Allow embedding conditions into the pipeline spec so that a pipeline could contain all relevant task, resource and conditions specs that it uses.

# Actual Behavior
Conditions are currently referenced from a pipeline.

**Comment by bobcatfish** [comment]
We're already embedding everything else so this seems reasonable!

@siamaksade out of curiousity, are you doing a lot of spec embedding? imo for "best practices" (whatever that means: here I think it just means practices Christie likes XD) embedding should be the exception, not the norm (less reusability!)

**Comment by siamaksade** [comment]
@bobcatfish We do. The rationale is that some conditions are intimate details of how a particular task should execute in a particular pipeline. For those, an referenced object is not attractive since it will never be re-used by any other pipeline.

The other aspect of it is `PipelineRun` which should be a snapshot of the execution of a particular pipeline at some point in time. Referenced resources make it difficult to get that snapshot since they can change after the pipeline run is completed and make it impossible to have an accurate view of past pipeline runs. `PipelineRun` can embed the pipeline to solve this but if the `Condition` is still not included in the pipelinerun (in pipeline spec really), then still one won't know what the pipelinerun actually executed if the condition gets modified.

**Comment by bobcatfish** [comment]
Update: @jerop started to work on this and then after discussion with @vdemeester we decided to put it on hold until we decide how to get conditions to beta

**Comment by jerop** [comment]
update: https://github.com/tektoncd/community/blob/master/teps/0007-conditions-beta.md
