### ISSUE TITLE
Set Ready annotation during pod creation for Taskruns with no Sidecars

### ISSUE THREAD

**Issue by dibyom** [tektoncd/pipeline#2080]
## Context

Jason has a really nice description of this in the Problem section of #1569. But in short, today a step in a Taskrun waits to start until it sees a "READY" value that is populated by the Taskrun controller using the Downward API. The controller waits for all sidecars to be up an running setting the annotation.

### Suggestion 

For taskruns without sidecars, the controller should be able to set the ready value when creating the pod. 

This is a performance optimization and should help the taskrun start running faster and the taskrun controller have less overall load.

**Comment by dibyom** [comment]
I was chatting about this with @sbwsg who mentioned that one of the reason the sidecar logic is the way it is today is to support injected sidecars such as istio. Since the TaskRun controller does not know about any injected sidecars until the pod has been created, implementing the suggestion will mean we break support for injected sidecars.

An alternative:
We can make this an option that the operator can control via a configMap. So the clusters that do not use injected sidecars can benefit from the performance gains

**Comment by nishpa214** [comment]
Ah, interesting. I hadn't thought of that use case. 

> We can make this an option that the operator can control via a configMap. So the clusters that do not use injected sidecars can benefit from the performance gains

Yeah, we don't have an istio setup, so controlling this via a configMap sounds like a good path forward.

**Comment by dibyom** [comment]
Yeah, the config can default to the current behavior and those needing better performance and not using injected sidecars can use the config option for this optimization. What do you think @sbwsg

**Comment by sbwsg** [comment]
> Yeah, the config can default to the current behavior and those needing better performance and not using injected sidecars can use the config option for this optimization.

That sounds to me like a solid approach to take!
