### ISSUE TITLE
Make it obvious from the docs that emptyDir workspaces are not passed from task to task

### ISSUE THREAD

**Issue by pierretasci** [tektoncd/pipeline#2081]
The current docs for workspaces mention that `emptyDir` is an option for a volume that can back a workspace. It is implicit in this that the `emptyDir` won't be the same `emptyDir` from one task to another and thus user's should not expect anything placed in there to persist.

I believe this should be made explicit so that people don't get confused.

**Comment by bobcatfish** [comment]
@pierretasci do you think it would be enough to link to the docs on `emptyDir` or do you feel like we should do more?

It's an odd one b/c if you have seen `emptyDir` in kubernetes, you'd know that it's a pod specific thing, but you wouldn't if you aren't as familiar with kubernetes :thinking: 

One thing I definitely think tho is that when we link workspaces (#1936) if a user tries to provide `emptyDir` for workspaces that are linked between Tasks, we should catch that and fail execution.

**Comment by pierretasci** [comment]
Actually I'm going to withdraw this issue around the documentation because I actually think the docs are clear enough here even if you don't know `emptyDir` volumes in Kubernetes:

> An emptyDir volume type is not shared amongst Tasks. Instead each Task will simply receive a new emptyDir of its own from its underlying Pod.

It is perhaps a bit unfortunate that the `PipelineRun` and `TaskRun` docs for workspaces don't match here. Perhaps the real issue is to make Workspaces their own doc.

I think you make a really good point about validation. I wonder if anyone has a use case for attaching an `emptyDir` with the same workspace name to different tasks not to share the volume but just to have a consistently named scratch space. I'm not sure how likely that is though.

**Comment by sbwsg** [comment]
We've [added a `workspaces.md`](https://github.com/tektoncd/pipeline/blob/master/docs/workspaces.md) and included a bit more explicit language [that emptyDir is unsuitable for sharing content between Tasks](https://github.com/tektoncd/pipeline/blob/master/docs/workspaces.md#volumesources-for-workspaces).
