### ISSUE TITLE
Please support build cache in PipelineResources

### ISSUE THREAD

**Issue by zeusro** [tektoncd/pipeline#2088]
# Expected Behavior

Mount build  cache (such as 
`/root/.gradle/caches/modules-2/files-2.1/`
`/root/.m2/repository/`) into build environment

# Actual Behavior

PipelineResources have not such option.

# Steps to Reproduce the Problem

None.

# Additional Info

**Comment by zeusro** [comment]
Sorry,I just found  that `Tasks ` support `volume `,is that what I want ?

**Comment by dibyom** [comment]
A volume or workspace sounds like what you need.
https://github.com/tektoncd/pipeline/blob/master/docs/tasks.md#workspaces

Feel free to reopen this issue (or ask on slack) if it does not solve your use case

**Comment by zeusro** [comment]
> A volume or workspace sounds like what you need.
> https://github.com/tektoncd/pipeline/blob/master/docs/tasks.md#workspaces
> 
> Feel free to reopen this issue (or ask on slack) if it does not solve your use case

Thanks!
