### ISSUE TITLE
Inconsistent pipelineRun visualization

### ISSUE THREAD

**Issue by euprogramador** [tektoncd/pipeline#2100]
when viewing a pipelineRun, the steps that make up the pipeline are presented.

![2020-02-25_09-21](https://user-images.githubusercontent.com/264692/75247252-431c2500-57b0-11ea-825c-26c9fa69da87.png)

When modifying pipeline one by adding a new step, the pipelineRun view is modified by adding the task in previous instances.

![2020-02-25_09-25](https://user-images.githubusercontent.com/264692/75247475-c178c700-57b0-11ea-94cc-9251db0fb627.png)

# Expected Behavior

Modifying the pipeline configuration should not modify past pipelineRun runs.

I believe that a copy of the pipeline configuration should be made when executing a pipelineRun, in order to maintain the integrity of the pipelineRun even after modifications to the original pipeline.

# Actual Behavior

Pipelinerun is modified by pointing only to the reference and not by keeping an internal copy of the original pipeline.

# Steps to Reproduce the Problem

1. create the pipeline
2. create pipelineRun
3. modify this pipeline
4. visualize this pipelineRun 

# Additional Info

Without the implementation of this behavior, it is not possible to guarantee traceability, since the task and the pipeline may undergo modifications. The same goes for TaskRun, which must keep a copy of the task in order to maintain consistency in a re-execution.

**Comment by vdemeester** [comment]
Hey @euprogramador, thanks for the issue.

I think this shouldn't be in this repository as it is about the openshift devconsole, so it should be created under the [`openshift/console`](https://github.com/openshift/console) repository.

That said, it's a know design issue. For the run started from the `cli` we will embedded the specs by default to make sure this doesn't happen. That said, we may need to do something in `tektoncd/pipeline` to fix this.
/cc @siamaksade

**Comment by afrittoli** [comment]
@vdemeester @euprogramador I believe we should close this issue, and open a new one if we need a new feature to help visualization tools doing the right thing.

**Comment by AlanGreene** [comment]
We have the same issue with the dark launched visualization in `tektoncd/dashboard`, and will also have it in the current UI if we attempt to render the complete Task list for a PipelineRun before we have corresponding TaskRun status. The snapshot approach being taken by the cli is interesting but only benefits users where the PipelineRun is created via tkn.
