### ISSUE TITLE
Is it possible to read run time values from file and replace in the tasks or pipeline?

### ISSUE THREAD

**Issue by ssvinoth22** [tektoncd/pipeline#2106]
# Expected Behavior
Like having variables.yaml file in each repositories (key value for deployment eg, resources, env, imageurl, app name etc ) replace during tasks or pipeline

# Actual Behavior

# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info

**Comment by afrittoli** [comment]
You can achieve that in a few ways. A couple of ideas:
- Expose the variables you need as parameters. When you run the pipeline, set the value of the parameters from your YAML file - you'll need a tool to do that. If you trigger the pipeline via `triggers` you can store your variables in a `TriggerBinding`
- Store you variables in a git repo or artifact storage. Mount those using a pipeline resource or a workspace and parse the values you need in your steps

**Comment by ssvinoth22** [comment]
i have my values.yaml file in my repo, but how do i pass in step? i need to create a shell or python script to read and parse it accordingly right? there is no in build functions like helm charts values or jenkins values.yaml file...
