### ISSUE TITLE
Can we disable overriding HOME in v0.10.1 ?

### ISSUE THREAD

**Issue by eddycharly** [tektoncd/pipeline#2116]
Is this possible to prevent tekton from overriding HOME environment variable in tekton 0.10.1 ?

If i'm not mistaken it will be possible the next release but in 0.10.1 i'm not sure if there's a way to do it.

**Comment by sbwsg** [comment]
Unfortunately there's no way to do it in 0.10.1.  0.11 should be released very soon - most likely early next week at this point (I think).

**Comment by dibyom** [comment]
(Please re-open if necessary!)
/close
