### ISSUE TITLE
Investigate whether annotations/labels should be copied from Pipeline to PipelineRun in all circumstances

### ISSUE THREAD

**Issue by jorgemoralespou** [tektoncd/pipeline#2121]
I'm creating some Pipeline and PipelineRun programatically and using [kapp](https://get-kapp.io/) for deploying. Kapp adds some annotations to the generated resources so that it can control how to update them. With Tekton I'm running into a problem as Tekton is copying the annotations from the Pipeline resource into the PipelineRun resource despite I'm creating it programatically, and hence it's overriding the annotations kapp is adding and giving a wrong behaviour in kapp. We have an [issue in kapp](https://github.com/k14s/kapp/issues/77) but was wondering whether it's the right approach for Tekton to override these annotations in any case or not.

@sbwsg mentioned on slack:

> Looks like we do that here: https://github.com/tektoncd/pipeline/blob/master/pkg/reconciler/pipelinerun/pipelinerun.go#L252-L267.  Suggest creating an issue to seed discussion.  Would be curious to see the data that was improperly copied as part of that issue report as well!  Might be that we just want to isolate to specific fields that get copied over or something?  Not entirely sure.

# Expected Behavior
When applied correctly the annotation in the PipelineRun comes from the PipelineRun itself (https://gist.github.com/jorgemoralespou/3134ff308b13139ec9a8a8dac4eebc60#file-pipelinerun_build-and-deploy-ver-1-L7).

# Actual Behavior
Actual behaviouris that the annotation in the PipelineRun comes from the Pipeline (https://gist.github.com/jorgemoralespou/3134ff308b13139ec9a8a8dac4eebc60#file-pipelinerun_build-and-deploy-ver-2-L7).

# Steps to Reproduce the Problem

Execute this command 2 times. The second time it will fail.
```
ytt -f https://gist.githubusercontent.com/jorgemoralespou/35fdddfb1a7a801efed427a8310f9aeb/raw/5c4d8a2cce87567696a7e77be18026e41f9ddc96/example-pipeline.yaml -f https://gist.githubusercontent.com/jorgemoralespou/35fdddfb1a7a801efed427a8310f9aeb/raw/55a9f705b7cd5b26eabaac8e70d5b8173b314be2/values.yaml | kapp deploy -a tekton-example -n default -y -f-
```

**Comment by dibyom** [comment]
Maybe the right behavior here is that if the label/annotation is already set in the Run object, the pipeline/task controller should not overwrite it? If it is not already set, it can set it?
