### ISSUE TITLE
knative.dev/pkg make breaking change to apis.Convertible

### ISSUE THREAD

**Issue by mattmoor** [tektoncd/pipeline#2125]
We've cut release-0.13 of knative.dev/pkg and one of the final changes was a breaking name change to the apis.Convertible interface to clarify the roles of the receiver/argument.

I believe it was ConvertUp/ConvertDown -> ConvertTo/ConvertFrom.

cc @dprotaso @vdemeester

**Comment by mattmoor** [comment]
This should also let you start to take advantage of some of the leader election work @pmorie has been doing.

**Comment by vdemeester** [comment]
/assign

Thanks @mattmoor , I saw that 🤗
