### ISSUE TITLE
Tasks with results fail if when docker containers do not run as root

### ISSUE THREAD

**Issue by kh-sonrai** [tektoncd/pipeline#2131]
The /tekton/results directory is only writable by root, so images that do not run as root fail to create the directory. If any such docker image is included in a task, the task will fail with the following error if a results section is included in the task spec:
`Error creating the results directory: mkdir /tekton/results: permission denied`
 https://github.com/tektoncd/pipeline/blob/97a0c45e2db51942f6b4cb05ced30521977edd7b/cmd/entrypoint/main.go#L60

**Comment by othomann** [comment]
I will be pleased to fix it as soon as I am done with the PR for pipeline results.

**Comment by othomann** [comment]
I have a fix for it, but I am not sure how to add a regression test for it.

**Comment by sbwsg** [comment]
Closing as fixed by #2143
