### ISSUE TITLE
Figure out what needs to change in our release pipeline to support RC releases

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/pipeline#2132]
# Expected Behavior

Our release pipeline should support a version string such as "0.11.0-rc1".  Let's find out if it does.  If it doesn't then what changes need to be made?

**Comment by sbwsg** [comment]
It looks like we didn't need to make any changes.  Release happened with version "v0.11.0-rc1" and everything appears to be fine right now.

**Comment by vdemeester** [comment]
:tada: 
We can close then, right ?

/meow

**Comment by sbwsg** [comment]
oops, i didn't mean to hit submit on that comment yet.  But yeah, everything looks like it worked so closing this.
