### ISSUE TITLE
Pipeline docs do not show how to pass resources to tasks

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/pipeline#2154]
The [pipeline](https://github.com/tektoncd/pipeline/blob/master/docs/pipelines.md) docs show how to declare resources but not how to match those resources to the tasks in the pipeline.

**Comment by tomgeorge** [comment]
@afrittoli are you looking for more than is covered [here](https://github.com/tektoncd/pipeline/blob/master/docs/pipelines.md#pipeline-tasks)?

**Comment by afrittoli** [comment]
Oh, I missed it somehow - thanks!
