### ISSUE TITLE
[Bug] Can't use generateName in pipelineRun

### ISSUE THREAD

**Issue by yuwenma** [tektoncd/pipeline#2170]
# Expected Behavior
a new random pipelinerun name is automatically created. 

# Actual Behavior
raises "resource name may not be empty"

# Steps to Reproduce the Problem

1. Apply the tekton CRDs to my cluster:
```bash
kubectl apply -filename https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml
```
2. Run kubectl apply to create a tekton pipelinerun using "name" (with value "run"), "namespace" (with value "ci-test1") in metadata field
```yaml
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: 'run'
  namespace: 'ci-test1'
spec:
...
```   
2. Make sure the pipeline run succeeds. (kubectl get -n ci-test1 pipelineruns.tekton.dev) 
3. Change metadata.name to metadata.generateName with value "run1-". Got the following error 

```bash
error: error when retrieving current configuration of:
Resource: "tekton.dev/v1alpha1, Resource=pipelineruns", GroupVersionKind: "tekton.dev/v1alpha1, Kind=PipelineRun"
Name: "", Namespace: "ci-test1"
Object: &{map["apiVersion":"tekton.dev/v1alpha1" "kind":"PipelineRun" "metadata":map["annotations":map["kubectl.kubernetes.io/last-applied-configuration":""] "generateName":"run1-" "namespace":"ci-test1"] "spec":map["pipelineRef":map["name":"demo-pipeline"] "resources":[map["name":"source-repo" "resourceRef":map["name":"app-git-repo"]] map["name":"web-image" "resourceRef":map["name":"guestbook-web-image"]] map["name":"app-image" "resourceRef":map["name":"guestbook-app-image"]]] "serviceAccountName":"default"]]}
from server for: "ci/run/pipelinerun.yaml": resource name may not be empty
```

**Comment by danielhelfand** [comment]
@yuwenma You need to use kubectl create -f with generateName. There is an issue open to improve the error message (#2113). Sorry for the confusion.

**Comment by yuwenma** [comment]
I see, thanks!
