### ISSUE TITLE
Pipelines failing on Openshift i.e. non-root environment

### ISSUE THREAD

**Issue by piyush-garg** [tektoncd/pipeline#2172]
# Expected Behavior

Pipeline should work

# Actual Behavior

Pipeline is failing with taskrun pod stuck in podinitializing state. Init container with name `tekton-results-folder-writable` getting error out with logs 

```
chmod: /tekton/results: Operation not permitted
```

This seems to happen after https://github.com/tektoncd/pipeline/pull/2143 because of this command https://github.com/tektoncd/pipeline/pull/2143/files#diff-54a597aad65d997daf41843ebfe53533R253

# Steps to Reproduce the Problem

1. Run latest master pipeline controller on OpenShift
2. execute any pipelinerun/taskrun
3. fails with the above error

# Additional Info

**Comment by vdemeester** [comment]
As commented in #2143 I don't think the `chmod 777` is actually required, the mount should be writable by the rest :crossed_fingers:.
