### ISSUE TITLE
task run support hostnetwork.

### ISSUE THREAD

**Issue by phantooom** [tektoncd/pipeline#2183]
in our env  k8s cluster use evpn  to communicate with vm and bare metal. 
k8s cluster cluster has very few ip. we expect there are about 200+ pipeline producing about 1000+ taskrun in one day.  
when taskrun finished. it doesn't release ip. so we need clear task run every day.

we need task run support hostnetwork.

thx.

**Comment by wlynch** [comment]
> when taskrun finished. it doesn't release ip.

Not sure if this is just a property of pods or an issue with Pipelines itself. Do you have any more information here?

> we need task run support hostnetwork.

Just to make sure I'm understanding this correctly, would adding [hostNetwork](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#podspec-v1-core) to [PodTemplate](https://github.com/tektoncd/pipeline/blob/master/docs/podtemplates.md) address your needs?

**Comment by vdemeester** [comment]
> > when taskrun finished. it doesn't release ip.
> 
> Not sure if this is just a property of pods or an issue with Pipelines itself. Do you have any more information here?

I think this is mainly because we don't delete the pod automatically, thus not deleting the pods means the ip do not get released.

/kind feature

**Comment by phantooom** [comment]
> Just to make sure I'm understanding this correctly, would adding hostNetwork to PodTemplate address your needs?

@wlynch  that's right

**Comment by waveywaves** [comment]
https://github.com/tektoncd/pipeline/issues/2183 fixes this
