### ISSUE TITLE
Bump to Kubernetes 1.15 will kill all OpenShift 3.11/4.2 activities

### ISSUE THREAD

**Issue by disposab1e** [tektoncd/pipeline#2187]
A bump of +4! versions from Kubernetes 1.11 to 1.15 to fix one! bug (#1113) will kill all OpenShift 3.11/4.2 activities.

**Comment by vdemeester** [comment]
@disposab1e thanks for the issue. The bump was not to fix one bug (#1113) ; that bug *happened* to get fixed at the same time. The bump was to be able to bump `knative.dev/pkg`, to benefit enhancements on that, and prepare the use of conversion webhook (that are beta in 1.15).

This *indeed* mean that starting from 0.11, Tekton Pipeline won't work on anything lower than OpenShift 4.2 (The same way Knative does not). OpenShift 3.11 was never really supported either (to have a working webhook you needed to enable some configuration on you cluster, that are not there by default).

I understand this can be frustrating but as a project, we also have to, sometimes make hard choice, keep being up-to-date.

/kind question

**Comment by chmouel** [comment]
OpenShift 3.11 never was properly tested so it may just be by luck that it was working previously.

As 4.2 drop we (tekton upstream) are supporting kubernetes releases minus two which maps to the not yet released openshift 4.4 and the current openshift 4.3. 

Having said that our (as red hat) downstream product [openshift-pipelines](https://www.openshift.com/learn/topics/pipelines) is not yet GA and we are still working out on our support matrices on how to best support different versions.

(and just fyi, it is not just for this only one bug that we updated `knative/pkg`)

**Comment by chmouel** [comment]
(sorry for duplication between vincent and my comment, but basically we are both saying the same thing :) )

**Comment by disposab1e** [comment]
@chmouel @vdemeester Thanks for clarification!

BUT: Have a look at your own documentation at install.md

Headline: Installing Tekton Pipelines on OpenShift/MiniShift

Minishift NEVER was OpenShift 4 ;-)

**Comment by vdemeester** [comment]
@disposab1e yeah… this needs to go :sweat: This was there on the early days (when it was still `knative/build-pipeline` :sweat_smile:)

**Comment by disposab1e** [comment]
@vdemeester times change.. quickly :-)

**Comment by disposab1e** [comment]
Btw.. I was able to install latest tekton release in OpenShift 3.11, everything was fine... but than the workspace in the tasks (pvc) was missing... I think this is because of the different handling with sidecars... so I failed late :-(
