### ISSUE TITLE
Design and implement retries

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#221]
## Expected Behavior
Users may have some Tasks which they know will sometimes fail for reasons which are not worth failing a Pipeline over. In this case the user should be able to specify a number of times to retry the Task for.

If a Task is retried, this should be obvious in the statuses of both the PipelineRun and the resulting TaskRuns.

## Actual Behavior
If a Task fails once, the whole Pipeline will stop and be considered failed.

## Additional Info
@abayer do you have any other requirements we should focus on here?

**Comment by abayer** [comment]
So from discussions coming out of today's meeting and further chatting with @jchesterpivotal on Slack, I think what I'd sketch out as the goal would be:

* By default, nothing retries for any reason. 
* If a `TaskRun` or `PipelineRun` is *manually* aborted through the API/CRD changes, nothing should retry.
* If a `TaskRun` or `PipelineRun` fails (i.e., the `command` returns non-zero, e.g.), it should only be retried if the `Task` or `Pipeline` is configured to retry a set number of times for `failure`.
* If a `TaskRun` or `PipelineRun` errors out (i.e., someone deleted the `TaskRun` CRD via kubectl, or the node the `TaskRun` is on catches on fire and explodes), it should only be retried if the `Task` or `Pipeline` is configured to retry a set number of times for `error`.

Thoughts?

**Comment by abayer** [comment]
I'm going to start working on this once #355 is merged, FYI.
