### ISSUE TITLE
Feature: method to absorb git-source yaml into Pipeline/Task $inputs etc

### ISSUE THREAD

**Issue by bitsofinfo** [tektoncd/pipeline#2219]
I'd like for devs to be able to configure some aspects of the pipeline behavior via YAML that lives in the cloned git source that Tekton treats as an input resource (currently). 

I.E. some way I could"absorb the contents of this yaml file into the Pipeline's scope of available variables that can then by used via some sort of tekton `$inputs.[yamldoc].prop1.subitem2.key`, then you could just reference that data w/ CEL expressions anywhere in Tasks.

Similar to the whole task `results` functionality and task `inputs`. Something that could just source a structure from a yaml file that then becomes useable as `$(yamlsource.parent.list[0].name)` whatever. 

Right now to do this I'm having to manually read this YAML then traverse it and turn it into a bunch of Task result files on the shared volume which seems clunky.

**Comment by sbwsg** [comment]
I'm not entirely clear what's being requested.  Could you show a more complete Pipeline example to demo what you're trying to achieve?  Or sketch out some YAML of the interface you'd like to see?

**Comment by bitsofinfo** [comment]
1. YAML in a git-source
```
x: "dog"
y:
  key: "name"
```

2. Something in tekton that can consume this and assign it to some `varname`

3. Then I can reference it in any task/pipelines via: `$(inputs.varname.x)` and `$(input.varname.y.key)` etc etc

**Comment by jlpettersson** [comment]
I understand your problem. We had the same problem when adopting Tekton, and we created our own `pipeline.yaml` abstraction that can live in the _code repository_ and then we have a `Task` that parse the pipeline.yaml and generate a Tekton `Pipeline` and initiates a `PipelineRun`.
