### ISSUE TITLE
Mirror push failed

### ISSUE THREAD

**Issue by bibi520** [tektoncd/pipeline#2234]
env：
![image](https://user-images.githubusercontent.com/42456284/76738649-fe2f5100-67a5-11ea-9977-d45b81dee4cb.png)
![image](https://user-images.githubusercontent.com/42456284/76738682-0f785d80-67a6-11ea-8f1a-daa3c8a8151c.png)
error：
error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "registry.us-west-1.aliyuncs.com/chocolate/base": UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:chocolate/base Type:repository] map[Action:push Class: Name:chocolate/base Type:repository]]
![image](https://user-images.githubusercontent.com/42456284/76738819-48183700-67a6-11ea-8899-0b95e8888d3a.png)

![image](https://user-images.githubusercontent.com/42456284/76738905-6d0caa00-67a6-11ea-9349-1a988a955aad.png)

**Comment by dibyom** [comment]
Likely an issue with the docker  registry secret...does the service account have access to the secret?

https://github.com/tektoncd/pipeline/blob/master/docs/auth.md#basic-authentication-docker
