### ISSUE TITLE
New Cloud Events SDK changes things significantly

### ISSUE THREAD

**Issue by mattmoor** [tektoncd/pipeline#2240]
Just wanted to give a heads up that the new Cloud Events SDK (v2.0.0-preview3) has significant changes that need to be picked up.

The simplest migration is likely to pick up the new version, and rewrite the current import paths to be rooted at `github.com/cloudevents/sdk-go/legacy`, which contains the older client.  Then the new client can be picked up incrementally.

I looked into doing precisely this, but I wasn't smart enough to get `go mod` to work with some simple tinkering, so I wanted to at least open this to track.

cc @vdemeester @n3wscott

**Comment by n3wscott** [comment]
I will look into making go mod work, there might be some things I need to do to allow pulling the preview release. We will be doing an RC in the next couple weeks as we get closer to 2.0.0

**Comment by n3wscott** [comment]
I have cut a release called `v2.0.0-preview4` that does work with go mod today.

**Comment by mattmoor** [comment]
I may try to give this a shot

**Comment by mattmoor** [comment]
@n3wscott have you bumped eventing contrib?  Looks like they need to bump that to pull in the new CE lib.
