### ISSUE TITLE
Add git credential to git resource

### ISSUE THREAD

**Issue by onesolpark** [tektoncd/pipeline#2246]
# Expected Behavior
git resource should have git credential param like pullRequest
We have a private repo where git credentials are need to clone the git repo.
Currently pullRequest resource supports adding secrets to environment variable 
and it would be great for git resource to support same or similar behavior. 

# Actual Behavior
there is currently no way to add git credential to git resource type

# Additional Info

- Kubernetes version:
  kubernetes version 1.17.3

- Tekton Pipeline version:
  v0.11.0-rc2

**Comment by onesolpark** [comment]
Hmm just read the auth documentation and 
I think you can add credentials by attaching them to serviceaccounts
[https://github.com/tektoncd/pipeline/blob/master/docs/auth.md](url)

It is kind of confusing to have pullRequest have secretRefs and for git to use service-accounts

**Comment by vdemeester** [comment]
> It is kind of confusing to have pullRequest have secretRefs and for git to use service-accounts

I tend to agree. /cc @bobcatfish @wlynch @afrittoli wdyt ?

/kind question
/kind documentation
