### ISSUE TITLE
Reduce duplicated code in release pipeline

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/pipeline#2250]
# Issue
With https://github.com/tektoncd/pipeline/pull/2242 we created a copy of the publish task and release pipeline useful for backport. However much of the code is shared between this task/pipeline and the originals, so we should converge them into one with a parameter to enable/disable writing to "latest"

# Additional Info

We could consider having folder for major versions, and latest/previous subfolders for minor versions, plus an overall latest folder that points to the latest version of the latest major.

**Comment by afrittoli** [comment]
Never mind, I didn't see that the PR was updated before it was merged, this is solved already

**Comment by sbwsg** [comment]
😅 sorry i should've made that clearer
