### ISSUE TITLE
Document all variables available in Tekton in one place

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/pipeline#2267]
# Expected Behavior
Have a single reference document with all variables `$()` available in different context to Tekton resource authors.

# Actual Behavior
Today we have reference to different variables available to resource authors, but there's no clear reference anywhere of what variables can be used where.

**Comment by sbwsg** [comment]
As an exercise I just had a look through to find all the substitutions I could.  These are they:

### Available in Tasks
- `params.<param name>`
- `resources.inputs.<resource name>.path`
- `resources.outputs.<resource name>.path`
- `results.<result name>.path`
- `workspaces.<workspace name>.path`
- `workspaces.<workspace name>.volume`
- `credentials.path`

Each PipelineResource type also defines its own variables that we seem to only really have in code.  Each Resource exposes a `Replacements()` func that returns them:

- [Git PipelineResource Variables](https://github.com/tektoncd/pipeline/blob/master/pkg/apis/resource/v1alpha1/git/git_resource.go#L130)
- [PullRequest Resource Variables](https://github.com/tektoncd/pipeline/blob/master/pkg/apis/resource/v1alpha1/pullrequest/pull_request_resource.go#L102)
- [Image Resource Variables](https://github.com/tektoncd/pipeline/blob/master/pkg/apis/resource/v1alpha1/image/image_resource.go#L70)
- [GCS Resource Variables](https://github.com/tektoncd/pipeline/blob/master/pkg/apis/resource/v1alpha1/storage/gcs.go#L103)
- [GCS Build Resource Variables](https://github.com/tektoncd/pipeline/blob/master/pkg/apis/resource/v1alpha1/storage/build_gcs.go#L123)
- [Cluster Resource Variables](https://github.com/tektoncd/pipeline/blob/master/pkg/apis/resource/v1alpha1/cluster/cluster_resource.go#L124)

(These are all accessed through `resources.inputs.<resource name>.<variable>` or `resources.outputs.<resource name>.<variable>`)

### Available in Pipelines
- `params.<param name>`
- `tasks.<task name>.results.<result name>`
