### ISSUE TITLE
facilitate mount of certs for HTTPS Proxy

### ISSUE THREAD

**Issue by gabemontero** [tektoncd/pipeline#2288]
# Expected Behavior

As a follow on to https://github.com/tektoncd/pipeline/pull/2215 to facilitate tls verify == true when going to an https proxy it would be helpful to minimally have examples of how to make those certs available to the `git` related steps

It could be
a) an example step that does the equivalent of `git config http.sslCert ~/path/to/ssl/cert.pem` that can then be consumed by subsequent `git` operations
b) mounting of a `ConfigMap` that contains the cert and mounts it in the appropriate /etc path for a given operating system

# Actual Behavior

# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

**Comment by gabemontero** [comment]
@piyush-garg @vdemeester I went back and revisited https://github.com/tektoncd/community/pull/232 and see where we had some discussion on the mounting of certs.

Do you all think we still need this tracking item and further augmentation of the work @pritidesai did with https://github.com/tektoncd/pipeline/pull/2215 or do you all think we should close this item in favor of your TEP and the subsequent work that would stem from that?

thanks

**Comment by vdemeester** [comment]
I think we can close this item in favor of @piyush-garg TEP yeah 👼🏼 (and this can be quite easily be handled by the operator)

**Comment by gabemontero** [comment]
making it official then - thanks

/close
