### ISSUE TITLE
Make Pipeline task name available in Task/ClusterTask

### ISSUE THREAD

**Issue by dinup24** [tektoncd/pipeline#2294]
The pipeline task name set in the pipeline definition should be made available in the task as internal param or env variable (or in some other way) during execution. The steps/sidecar in the task should be able to use the pipeline task name which could be useful logging/tracing/debugging purposes.
 
```
tasks:
  - name: build-the-image
    taskRef:
      name: build-push
```
In the above example pipeline task name is `build-the-image`, but it invokes the task `build-push`. If certain contextual info such as the pipeline task name, pipeline name etc is made available in the task `build-push` , this will be helpful in understanding the context in which this task was executed (in our case, the same task is executed multiple times in a pipeline to perform same activities for different set of artifacts).

For eg. `build-push` task will be used to push ui-app image as well api-server image.

**Comment by bobcatfish** [comment]
This may have been somewhat solved by #1522 (thanks @R2wenD2 !)

You can now access [variables like the pipelinerun name and the pipelinename](https://github.com/tektoncd/pipeline/blob/master/docs/variables.md#variables-available-in-a-pipeline) in the pipeline - to make these available to a Task/ClusterTask it could declare them as params.
