### ISSUE TITLE
Update v1beta1 condition examples

### ISSUE THREAD

**Issue by drewbutlerbb4** [tektoncd/pipeline#2314]
The [three v1beta1 examples for conditional pipeline runs](https://github.com/tektoncd/pipeline/tree/master/examples/v1beta1/pipelineruns) should be updated to use v1beta1 Conditions.

**Comment by vdemeester** [comment]
@drewbutlerbb4 `Condition`, as `PipelineResource` are not in `v1beta1` (at least yet). We felt those part of the API weren't *beta* quality, hence they are staying in alpha for now — aka not "supported". That said, they can still be "referered" in the v1beta1 resources

**Comment by sbwsg** [comment]
Per vdemeester's comment just now, conditions haven't moved over to beta.  I'm going to close this issue as the examples are working as expected right now.  Feel free to reopen if there's more to do here though!
