### ISSUE TITLE
Design and implement paused Task execution until condition is met

### ISSUE THREAD

**Issue by abayer** [tektoncd/pipeline#233]
## Expected Behavior
A `Task` can be configured to not commence execution until a condition, such as a particular value being present in the `TaskRun`'s metadata, is true.

* This should be generic enough that the reason for commencing execution can be anything, e.g. it could be triggered by a user pushing a button in a UI, it could be a slack command
* It must be possible to ensure that the mechanism that is commencing execution is authorized to do so (e.g. via a token)

## Actual Behavior
`Task`s always run to completion or failure

## Additional Info
This would enable building features like manual approval or automated quality gates in higher-level applications utilizing Build Pipeline, rather than requiring that any specific "wait until X is true before executing this `Task`" functionality be built directly into the CRDs.

...this is my first attempt at creating an issue here, so feel free to rewrite as needed. =)

**Comment by bobcatfish** [comment]
Thanks for writing this up @abayer !

Would you see yourself expressing this at the level of the Pipeline or the Task itself? (I'm thinking Pipeline?)

**Comment by abayer** [comment]
Hmm. Good question. As part of the Pipeline reference to the Task does feel logical when I think about it. The Task could be used in multiple Pipelines that may not always all want the constraint. Good catch, thanks!

**Comment by bobcatfish** [comment]
@abayer do you see this as being a subtask of https://github.com/knative/build-pipeline/issues/27 or do you think this issue addresses separate concerns?

**Comment by abayer** [comment]
@bobcatfish Feels different to me - #27 is "should this Task execute at all" while this is "*when* should this Task execute". But I could be wrong.

**Comment by bobcatfish** [comment]
> @bobcatfish Feels different to me - #27 is "should this Task execute at all" while this is "_when_ should this Task execute". But I could be wrong.

Makes sense @abayer ! I also updated the description here with some requirements that Andrew Phillips shared with me, i.e. that pausing and resuming is really about async execution in general

**Comment by demobox** [comment]
> I also updated the description here with some requirements that @demobox shared with me

Thanks, @bobcatfish! Happy to elaborate on those if useful

**Comment by bobcatfish** [comment]
> Happy to elaborate on those if useful

Always @demobox :D :D :D

**Comment by hrishin** [comment]
hey @abayer @bobcatfish @demobox 

> Would you see yourself expressing this at the level of the Pipeline or the Task itself? (I'm thinking Pipeline?)

Considering this would be fine to declare "wait until condition" at `pipeline task` (just like `RunAfter`) level rather `task` definition?

Could you please shed some light on this?

**Comment by naiduasn** [comment]
Hey, just want to check if we would see this getting implemented anytime soon.

**Comment by acim** [comment]
Is this going to allow a user interaction like in [Jenkins Input Step](https://jenkins.io/doc/pipeline/steps/pipeline-input-step/)?

For example, I would like to run "helmfile diff" task and then manually approve the continuation of the pipeline. The next task would probably be "helmfile sync", but it would be nice to manually review the diffs before approving it.

**Comment by bobcatfish** [comment]
This is [in our roadmap](https://github.com/tektoncd/pipeline/issues/233)

/lifecycle frozen

**Comment by bobcatfish** [comment]
I believe that https://github.com/tektoncd/pipeline/issues/215 will solve this so I'm inclined to close it in favor of #215
