### ISSUE TITLE
Add workspaces support for the config-artifact-pvc configmap

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/pipeline#2330]
# Expected Behavior

PipelineResources currently use a PVC (or bucket) configured using the config-artifact-pvc configmap to quietly store data when it's shared between tasks. This uses an internal package called artifact_storage that silently mounts the PVC or syncs to a GCS bucket and uses that to transfer files from one task to the next. We'd like to replicate similar behaviour but have it available for the more general purpose workspaces implementation that pipelines now has.

This issue is for discussion of whether we want to support this same mechanism for controlling storage with Workspaces.  The simplest, easiest UX might be for workspaces to just automatically support the configmap and "just work" when the user specifies a "legacyArtifactPVC" workspace, something like this:

```yaml
# in a pipelinerun
spec:
  workspaces:
  - name: code-workspace
    legacyArtifactStorage: {}
```

# Actual Behavior

Workspaces don't currently know about the config-artifact-pvc configmap and each workspace needs its volume to be completely specified as part of the Run it's bound in.

# Additional Info

See [the Workspaces volumeClaimTemplate issue](https://github.com/tektoncd/pipeline/issues/1986) for another approach to this problem.  We may want both that and this, though this is also fair game for discussion here.

**Comment by jlpettersson** [comment]
I am trying to understand / get a clear use case here.

>PipelineResources currently use a PVC (or bucket) configured using the config-artifact-pvc configmap to quietly store data when it's shared between tasks.

Here it sounds like the use case is for handling **cached dependencies/artifiacts**. Or is the use case for using a _workspace_ to pass files between tasks **without a PVC**?

>This uses an internal package called artifact_storage that silently mounts the PVC or syncs to a GCS bucket and uses that to transfer files from one task to the next.

Here it sounds like a use case requiring both **GCS bucket** and a **PVC**. The use case could also be to use **GCS bucket** in the pipeline - have a task that syncs data from bucket to an **existing workspace** in the task/pipeline, and also a task for uploading data?

**Comment by sbwsg** [comment]
Ah, apologies, I see where the confusion comes from.  The intended use case is passing files between Tasks in a Pipeline.  PipelineResources have this existing behaviour: an `output` resource in Task A of a Pipeline can be "linked" to an `input` resource of Task B in the same Pipeline and the files of the PipelineResource will "magically" be copied between the Tasks when the PipelineRun executes.  A PVC **or** a GCS bucket is used as the medium by which the files are transferred between the Tasks in the Pipeline.  The configuration for the PVC or GCS bucket is stored in the `config-artifact-pvc` ConfigMap in the tekton-pipelines namespaces.

This issue exists to discuss whether we provide support in Workspaces for the existing `config-artifact-pvc` to help users transition from PipelineResources to Workspaces. The YAML for a workspace using this legacy copy system might look like this:

```
# in a pipelinerun
spec:
  workspaces:
  - name: code-workspace
    legacyArtifactPVC: {}
```

On seeing this workspace the reconciler could run the same code path as it would were it "linking" PipelineResources, and copy files through that medium.
