### ISSUE TITLE
Build an image and deploy in an external docker registry

### ISSUE THREAD

**Issue by 2020testuser** [tektoncd/pipeline#2345]
# Expected Behavior
I have a build.gradle file which builds a docker image for my  java application using gradle.
Creating a docker image using Tekton Pipeline Task and building the image using gradle and want to push to the company docker registry without any error. The Kubernetes PODS RBAC enabled. 
# Actual Behavior
Getting a security error when the application docker image is pushed to the company's docker registry.
 
# Steps to Reproduce the Problem

1. Create Tekton tasks to build the Java application using gradle
2. The task finally creates an application image
3. The application docker image must get pushed to the company docker registry
4. Getting a security error when the image is pushed.

# Additional Info
Using Tekton Pipeline deployed on-premise in Kubernetes.
- Kubernetes version:

  **Output of `kubectl version`:1.16**

- Tekton Pipeline version:
Client version: 0.8.0
Pipeline version: v0.11.0

**Comment by afrittoli** [comment]
Could you provide a bit more details? The YAML of your task, how is it invoked? What kind of setup do you have in place to authenticate to your private registry?

**Comment by test2016new** [comment]
> Could you provide a bit more details? The YAML of your task, how is it invoked? What kind of setup do you have in place to authenticate to your private registry?

Sorry for the delay. I'm using external image now for testing and unable to copy  the application source code to the image container. I tried using volume/volumemount, gitrepo volume and workingDir and nothing worked. I didn't get any error. But didn't see the application code in the image container when I run the task. Appreciate if you could provide some details on this.
`apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: my-task
spec:
  inputs:
    resources:
      - name: my-repo-git
        type: git
    params:
      - name: pathToContext
        description:
          The path to the build context workspace
        default: .
  steps:
    - name: print-info
      image: image-registry.openshift-image-registry.svc:5000/default/my-task-runner-image:latest
      imagePullPolicy: Always
      command: ["/bin/sh"]
      args:
        - "-c"
        - >
          echo "List the contents of /workspace, expecting to find the Git repository in there" &&
          ls -R /workspace
      volumeMounts:
      - name: workspace
        mountPath: /workspace
 
  volumes:
  - name: workspace
    gitRepo:
      repository: https://github.com/<company>/<my repo>.git
      directory: .



      `

**Comment by test2016new** [comment]
Please close this issue. I used a different approach to get it working. Thanks !
