### ISSUE TITLE
Test TestHelmDeployPipelineRun seems to be a regular flake in PullRequests

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/pipeline#2367]
# Expected Behavior

E2E tests should be, as much as possible, a reliable indicator of regressions in the project.

# Actual Behavior

It seems like `TestHelmDeployPipelineRun` has been flaking out (or is sporadically broken) across a number of PRs recently.  It doesn't always fail though.  This slows down progress of PRs and can result in a lot of comment noise as devs are rerunning the integration test suite.

# Additional Info

Recent examples:
- https://tekton-releases.appspot.com/build/tekton-prow/pr-logs/pull/tektoncd_pipeline/2363/pull-tekton-pipeline-integration-tests/1248497229157634049/
- https://tekton-releases.appspot.com/build/tekton-prow/pr-logs/pull/tektoncd_pipeline/2357/pull-tekton-pipeline-integration-tests/1248496977759440897/

**Comment by sbwsg** [comment]
Should now be resolved since https://github.com/tektoncd/pipeline/pull/2368 is merged.  Thanks @eddycharly !

**Comment by eddycharly** [comment]
Hope it fully solves the issue. Ping me on slack if it comes up again.
