### ISSUE TITLE
Unable to create tekton task with serviceAccountName in task spec

### ISSUE THREAD

**Issue by sravankumar777** [tektoncd/pipeline#2375]
# Expected Behavior

# Actual Behavior
Earlier to tektoncd/pipeline release [v0.9.0](https://github.com/tektoncd/pipeline/releases/tag/v0.9.0), were able to create/configure tekton task with ```serviceAccountName```.
After updating to tektoncd/pipeline release [v0.11.0](https://github.com/tektoncd/pipeline/releases/tag/v0.11.0), creation of same tekton task fails.

# Steps to Reproduce the Problem

1. Update tekton pipelines with latest version release of [v0.11.0](https://github.com/tektoncd/pipeline/releases/tag/v0.11.0)
2. After update of tekton pipelines, create a task by specifying serviceAccountName. 
3. Check error message from webhook validation.

# Additional Info
```admission webhook "webhook.pipeline.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "serviceAccountName"```

- Kubernetes version:
  **Output of `kubectl version`:**
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:
  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**
```
$ kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'
v0.11.0
```

**Comment by bobcatfish** [comment]
Hey @sravankumar777 ! We consider `serviceAccountName` to be "runtime" information, so it's part of the TaskRun (https://github.com/tektoncd/pipeline/blob/master/docs/taskruns.md#service-account) and afaik not part of the Task. It's possible that something changed about how unknown fields were being treated between the version of Tekton Pipelines you were running previously and the one where you started having this error - my guess is that the field was just being ignored previously.

**Comment by sravankumar777** [comment]
@bobcatfish, thanks for your response.
Yes, makes sense with adding serviceAccountName on TaskRun or PipelineRun.
We the current latest version v0.11.0, we were able to run the pipelines by specifying serviceAccountName on pipelinerun. 
Was curious to query whether, there was any issue introduced between the releases 😄
