### ISSUE TITLE
Add more details on "What" Conditions are, with some examples.

### ISSUE THREAD

**Issue by nkakkar81** [tektoncd/pipeline#2376]
# Expected Behavior
The Condition documentation should explain to a new user what conditions are, and what are the various scenarios in which we can use them in Pipelines.

# Actual Behavior
Currently, the docs page on conditions - https://github.com/tektoncd/pipeline/blob/master/docs/conditions.md  provides a detailed view on how to define/create conditions in a pipeline. However, there is NO information on what conditions are, and why should we use them in a Pipeline. 

# Steps to Reproduce the Problem
N/A

# Additional Info
Some of the information from this link can be leveraged to update the conditions.md topic: 
https://github.com/tektoncd/pipeline/blob/master/docs/pipelines.md#conditions

**Comment by bobcatfish** [comment]
@vdemeester since we're completely changing the structure of conditions via https://github.com/tektoncd/community/blob/master/teps/0007-conditions-beta.md i'm not sure this issue is relevant?
