### ISSUE TITLE
PipelineRun enters cancelled state even if cancelling TaskRuns fails

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/pipeline#2381]
# Expected Behavior

Cancelling a PipelineRun should not succeed if the TaskRuns it created were not able to be cancelled.

# Actual Behavior

In our [PipelineRun cancellation code](https://github.com/tektoncd/pipeline/blob/master/pkg/reconciler/pipelinerun/cancel.go#L34-L55) we immediately set the status of a PipelineRun to cancelled regardless of whether the TaskRuns it created were able to be cancelled.

This seems counter-intuitive and like a potential source of confusion for users.  If TaskRuns couldn't be cancelled then that should probably be stored as some kind of error or event on the PipelineRun and the PipelineRun itself should remain in an un-cancelled state to indicate that there are still running processes related to it.

**Comment by bobcatfish** [comment]
🤔

**Comment by jerop** [comment]
✋

**Comment by vdemeester** [comment]
I ran the task manually to update members of the org :angel: We had.. a small issue on it :stuck_out_tongue_closed_eyes:
