### ISSUE TITLE
Decide policy on TaskRun/PipelineRun labelling scheme

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/pipeline#2388]
# Expected Behavior

Tekton Pipelines has a deprecation policy on the labels that get added to PipelineRuns and TaskRuns.  Example of these labels: `tekton.dev/pipeline: volume-from-template` is added when I create a PipelineRun referencing the `volume-from-template` Pipeline.

# Actual Behavior

I don't think we have a policy outlined anywhere that describes when/how these labels could be changed in future.  Tools like CLI already rely on these labels to do things like querying for TaskRuns related to a Task.

In [a recent Pipelines Issue](https://github.com/tektoncd/pipeline/issues/2377) CLI folks requested we replace `tekton.dev/task: foo` with `tekton.dev/clustertask: foo` when a TaskRun references a ClusterTask instead of a Task.  This seems like a reasonable request and a good feature for Pipelines to support.  But I'm not really sure how to approach this from a deprecation standpoint.  It's feasible that platform teams or individual developers are relying on the existing label in their tools.  Do we consider these labels covered by our API Policy?  If not, what should inform our decision-making here?

**Comment by bobcatfish** [comment]
I vote we consider these covered by our deprecation policy!
