### ISSUE TITLE
Improve TaskRun Execution via Supervisor / Conductor Container 

### ISSUE THREAD

**Issue by waveywaves** [tektoncd/pipeline#2391]
# Expected Behavior

Currently TaskRuns have no central execution manager / "runtime" which takes care of the execution of the Steps in the Task (which need to be in a certain order, or a manipulated order in case of debug). This is an issue as the logic necessary to execute the steps lie within the Steps themselves through the Entrypoint Image whereas there should be an external supervisor / conductor which would do the "orchestration". 

Steps in a TaskRun execute based on the instructions given by the controller directly, instead of instructions given by the TaskRun Runtime itself (does not exist yet). This runtime can be provided by the Supervisor Container. Setting order of execution should be delegated to the Runtime and not be done by the controller itself in this case.

It should also be possible to expose a debug port from the Supervisor Container when in Debug Mode so that User Interfaces can attach to it and users can debug the Steps based on their own discretion, in the same way they would debug something like a C Program with GDB.  
Debug Mode for TaskRuns being tracked in https://github.com/tektoncd/pipeline/issues/2069.

# Actual Behavior

Order of execution of the steps is set by the controller through wait-files in a shared volume. A Step will execute if the wait-file it was waiting on comes into existence. This is completelty autonomous behaviour and there it is not possible to manipulate/halt the order of execution during runtime. 

## Checkpoints

- [ ] Enable proper signal forwarding in Entrypoint https://github.com/tektoncd/pipeline/pull/2426 
- [ ] Document and Finalize Supervisor Design

**Comment by waveywaves** [comment]
cc @skaegi @ImJasonH

**Comment by afrittoli** [comment]
Would it be possible to inject the supervisor container only in case of debug, and have Tekton working with entrypoints alone for now?
That would give us the possibility to get to know better the "supervisor mode" so we'd have more data to decide whether we want it for Tekton in normal mode too or not.

**Comment by ImJasonH** [comment]
> Would it be possible to inject the supervisor container only in case of debug, and have Tekton working with entrypoints alone for now?
> That would give us the possibility to get to know better the "supervisor mode" so we'd have more data to decide whether we want it for Tekton in normal mode too or not.

I think I'd actually prefer the opposite: if we think a supervisor will be easier/better, explore and experiment with it _without_ adding debug mode, eventually replace the file-based signalling we do today, and then and only then, start to support pausing/unpausing steps. That separates the infrastructure upgrade work from the feature work, and lets us bail early if the infra change turns out to be not worth doing.
