### ISSUE TITLE
Gradle Image in Step failing 

### ISSUE THREAD

**Issue by 2020testuser** [tektoncd/pipeline#2423]
I'm using Gradle image (from docker repo.) to build my SpringBoot application in my Tekton Step and getting the below error.
Caused by:java.io.IOException:Cannot run program 'docker' (in directory "/workspace/source"} : error=13, Permission denied.
I've mounted the docker socket with mount path as '/var/run/docker.sock' to my host system's '/var/run/docker.sock'. 
I'm getting the below exception in the logs.
``

**Comment by bobcatfish** [comment]
I think this is the same as #2424?
