### ISSUE TITLE
Step using Gradle image Failing with docker issue

### ISSUE THREAD

**Issue by test2016new** [tektoncd/pipeline#2424]
# Expected Behavior
I'm using Gradle image (from docker repo.) to build my SpringBoot application in my Tekton Step . The Tekton Step must be executed without any errors.

# Actual Behavior
Getting the below error.
Caused by:java.io.IOException:Cannot run program 'docker' (in directory "/workspace/source"} : error=13, Permission denied.
I've mounted the docker socket with mount path as '/var/run/docker.sock' to my host system's '/var/run/docker.sock'.
I'm getting the below exception in the logs.
[app-build-step] 20:44:35.075 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > **A problem occurred starting process 'command 'docker''**
[app-build-step] 20:44:35.075 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
[search-service-build-step] 20:44:35.075 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
[app-build-step] 20:44:35.075 [ERROR] [app-internal.buildevents.BuildExceptionReporter]  Run with --scan to get full insights.
[app-build-step] 20:44:35.075 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
[app-build-step] 20:44:35.075 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Exception is:
[app-build-step] 20:44:35.076 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task '<projectname'>
[ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.io.IOException: Cannot run program "docker" (in directory "/workspace/app/build/docker"): error=13, Permission denied

# Steps to Reproduce the Problem

1. In the Tekton Task's step, invoke the Gradle image using Image and Command parameters.
2. Set the docker mount path using volume and volume mount in the Step
3. Execute the Task and TaskRun

4. Check the TaskRun log.

# Additional Info

- Kubernetes version:

  **Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:47:22Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T20:52:22Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}*

- Tekton Pipeline version:

  **Client version: 0.8.0
Pipeline version: v0.11.0**

`apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: app-build-task
spec:
  steps:
    - name: app—build-step 
      image: <org docker registry>/app/gradle:latest
      imagePullPolicy: Always
      workingDir: /workspace/app
      
      script: |
          gradle --no-build-cache -S -i --debug --scan app:docker -x test
      volumeMounts:
      - name: docker-socket
        mountPath: /var/run/docker.sock
      - name: workspace
        mountPath: /workspace
      - name: which-docker
        mountPath: /usr/bin/docker
      securityContext:
        runAsUser: 0
  volumes:
  - name: docker-socket
    hostPath:
      path: /var/run/docker.sock
      type: Socket
  - name: which-docker
    hostPath:
      path: /usr/local/bin/docker
  - name: workspace
    gitRepo:
      repository: "https://887c23565718188eeb7@<github url>i.git"
      revision: 2c793727fb0adfa8d29`

**Comment by bobcatfish** [comment]
That's weird @test2016new ! Is it possible to also include what your `volume` declarations look like?

**Comment by bobcatfish** [comment]
@test2016new please reopen if you'd like to discuss more - I think we'd need to take a look at your volume declarations to be able to figure out what's going on.
