### ISSUE TITLE
Namespace for;  kubectl create secret docker-registry regcred

### ISSUE THREAD

**Issue by JCzz** [tektoncd/pipeline#2432]
Reference [doc](https://github.com/tektoncd/pipeline/blob/master/docs/tutorial.md)

When running:
`kubectl create secret docker-registry regcred... `

Should that be in tekton-pipeline namespace?

Like: `kubectl create secret docker-registry regcred -n tekton-pipeline... `

**Comment by danielhelfand** [comment]
https://github.com/tektoncd/pipeline/blob/master/docs/tutorial.md#configuring-task-execution-credentials

It should be in the namespace where your ServiceAccount is created as it will use the Secret you are creating. 

My recommendation would be to create all your resources for the tutorial in a separate namespace than tekton-pipelines.

**Comment by JCzz** [comment]
Thanks for info
