### ISSUE TITLE
Feature: Pipeline Checkpointing

### ISSUE THREAD

**Issue by pierretasci** [tektoncd/pipeline#2433]
This is a feature request for "checkpointing" built into the Tekton controller to save the state of the pipeline after each Task Step/Task completion.

# Expected Behavior
There are several reasons to want the state saved periodically:
- produces an accurate debug log that can help diagnose failures
- enables restarts of a partial pipeline as described in #50 
- gives you a place to put artifacts that the user could want extracted out of a pipeline without having to first push them somewhere

Examples of things that would exist in a checkpoint:
- status of the pipelinerun/taskrun, current step, timings, eg
- state of workspaces/params/resources
- any artifacts left on disk of the output directory on the task
- container parameters like env variables?

# Actual Behavior
Right now, there isn't really a good built-in way to store the state of a pipeline as it is running and the Tekton controller is in the best position to execute this as a sidecar on each task pod.

**Comment by NikeNano** [comment]
I would be happy to work on this.

**Comment by fenglixa** [comment]
Thanks @NikeNano, this feature is important for us, what's the progress on this item?

**Comment by afrittoli** [comment]
@dlorenc is there any related work from the tektoncd/chains project ?

**Comment by afrittoli** [comment]
I think the work described in https://github.com/tektoncd/community/blob/master/teps/0030-workspace-paths.md would be really useful for checkpointing. It could help limiting the amount of data to be saved, based on the declared paths.

**Comment by vincent-pli** [comment]
Do we consider another solution of `Chekpoint` come from kubeflow: https://github.com/kubeflow/pipelines/tree/master/backend/src/cache

Basically, it's a Pod watcher and a Mutation webhook for Pod.
-  Watch pod which is complete and store the output to remote storage (mysql in kubeflow)
- Webhook will check a new created Pod if it have been run previously, if yes, retrieval previously output from storage, set back to the new created pod and ignore it (by replace it's container).  

@vdemeester @bobcatfish @afrittoli
