### ISSUE TITLE
Include TaskRun Created by Condition in List of TaskRuns Under PipelineRun Status

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/pipeline#2438]
# Expected Behavior

When a TaskRun is created by a Condition that is part of a PipelineRun, the TaskRun created should show up in the [map of TaskRuns that are part of a PipelineRun Status](https://github.com/tektoncd/pipeline/blob/dc0a8b9807b2f0cbe4d5f827098996c39a1124a9/pkg/apis/pipeline/v1beta1/pipelinerun_types.go#L253).

# Actual Behavior

The TaskRun created by the Condition appears as a new TaskRun, but is not available via the PipelineRunStatus TaskRuns.

# Steps to Reproduce the Problem

1. Run a PipelineRun with a Condition (e.g. https://github.com/tektoncd/pipeline/blob/master/examples/v1beta1/pipelineruns/conditional-pipelinerun.yaml)
2. Run a `kubectl describe` on the PipelineRun created and view the TaskRuns under its Status
3. View what TaskRuns have been created using `kubectl get taskrun` or `tkn tr ls` and see the TaskRun from a Condition is created 

# Additional Info

- Kubernetes version:

 ```
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

```
Client version: 0.8.0
Pipeline version: v0.11.1
```

This would help tremendously with development around the CLI for a couple of reasons:
1. As part of the `tkn pipelinerun describe` command, TaskRuns from the PipelineRun are shown. Since these TaskRuns are pulled from the list of TaskRuns under a PipelineRun status, TaskRuns from the Condition are not available. 
2. Logs from TaskRuns from Conditions are not available via the CLI since TaskRuns are pulled from the list of TaskRuns under a PipelineRun status. 

For both situations listed above, it is odd to need to look for information about TaskRuns in two different properties of the PipelineRun: 
* PipelineRunTaskRunStatus
* PipelineRunConditionCheckStatus

If the Condition itself manifests as a TaskRun, then it should be treated as one as part of a PipelineRun.

**Comment by dibyom** [comment]
Worth discussing: Is there a need to differentiate between "regular" taskruns and these conditional taskruns? I believe these taskruns are present in the status under the pipelineTask's `conditionChecks` field

**Comment by danielhelfand** [comment]
I understand the idea of trying to keep the results of Conditions separate from TaskRuns, but I think this mainly comes down to a couple things for me:

1. These aren't being treated as TaskRuns. They are considered to be a ConditionCheck on the PipelineRunSpec, and yet a TaskRun is created as a result of this PipelineRun. This makes it difficult to develop around the idea of Conditions with regard to listing TaskRuns associated with a PipelineRun. You would basically need to look for this information in two different locations. The same is true when trying to aggregate logging information from both Conditions and TaskRuns. 
2. I just find it confusing that a TaskRun is being created and yet it is not treated as a TaskRun by the PipelineRun itself.

My thought mainly focuses around that Conditions aren't the easiest to develop around from an API standpoint. I think it would be different if the expectation was that Conditions create a separate resource all together like a ConditionRun, but the fact that a TaskRun is how a Condition actually runs but is not actually reported as such is strange to me.

**Comment by afrittoli** [comment]
The current syntax would allow for ConditionChecks to keep a similar API even if they were backed by something different than TaskRuns - but I'm not sure this is a huge benefit.

FWIW I recently added a new label to the TaskRun associated to the ConditionCheck that help mapping back to the Condition: https://github.com/tektoncd/pipeline/pull/2579/commits/106ad1e2ff2d7ab2f90e0d5814403cb1c53d08dc.

**Comment by afrittoli** [comment]
I wrote here code that builds back the pipelinerun status from a list of TaskRuns, in case it helps: https://github.com/tektoncd/pipeline/pull/2573

**Comment by danielhelfand** [comment]
I realize that the design of Conditions is pretty far along at this point, but my personal preference would've been to just have TaskRuns represent the execution of a Condition as opposed to having a PipelineRun represent it differently. That being said, I am willing to close this and maybe what the best approach here will be is using a labels approach to retrieve TaskRuns as opposed to relying on the PipelineRun to have that information. Thanks for the discussion and feedback on this though.
