### ISSUE TITLE
Webhook sample - latest kubectl apply?

### ISSUE THREAD

**Issue by JCzz** [tektoncd/pipeline#2440]
installed latest:
`https://tekton.dev/docs/getting-started/`

And I can now see a Webhook running pod, does that mean that webhook extension is in pipelines?

And if so, do you have an example for a Github webhook(Google Kubernetes Engine)?

Thanks in advance

**Comment by wlynch** [comment]
Hi! For running Tekton tasks in response to GitHub webhooks, take a look at the Triggers project at https://github.com/tektoncd/triggers.

In particular, https://github.com/tektoncd/triggers/tree/master/docs/getting-started has steps for getting started.

I'm going to close this, but feel free to reopen if you have more questions! ^_^

/label triage/support
/close
