### ISSUE TITLE
Any plan to develop Python SDK for Tekton?

### ISSUE THREAD

**Issue by jinchihe** [tektoncd/pipeline#2441]
Do we have plan to develop or generate Python SDK for Tekton? There are same user case that would like to use Python (or in notebook) derectly, such as machine learning cases etc ... That would be great if have Python SDK for tokton. Thanks.

**Comment by vdemeester** [comment]
It's not in our plan yet to have an official python sdk for tekton. It could become in our plan but most likely once Tekton is considered GA :wink: 

/kind question
/kind feature

**Comment by 1026908346** [comment]
is there any other SDK for tekton?

**Comment by jinchihe** [comment]
@vdemeester Thanks.  Python SDK client is very import for end user, such as k8s Python SDK ...
May I take this? I already did a prototype for the tekton pipeline SDK. Shall we create a new repo for python SDK? or we can add to this `pipeline` repo and create a directory `sdk/python`? Personally better to create a new repo for SDK. Thanks.

**Comment by terrytangyuan** [comment]
We are currently working on supporting Tekton in [Couler](https://github.com/couler-proj/couler). Couler aims to provide a unified interface for constructing and managing workflows on different workflow engines. See https://github.com/couler-proj/couler/pull/65 for a proposal on Couler's Tekton backend that @FogDong created. We'd appreciated any comments and feedback.

**Comment by jinchihe** [comment]
Already done here https://github.com/tektoncd/experimental/tree/master/sdk/python
