### ISSUE TITLE
Allow volumeClaimTemplate name to be not provided

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#2450]
# Expected Behavior

Since the tekton controller is completely managing the lifecycle of PVCs created with volumeClaimTemplate, as an author of a Run specifying it, i might not care what the name of the PVC is. I'd love it if the controller could automatically generate one for me so I can skip the whole metadata section of the template if I don't need it.

# Actual Behavior

It looks like the PVC created will have a name with this format:

```go
fmt.Sprintf("%s-%s-%s", claimName, workspaceName, pipelineRunName)
```

# Additional Info

The feature was added in https://github.com/tektoncd/pipeline/pull/2326

**Comment by jlpettersson** [comment]
>I'd love it if the controller could automatically generate one for me so I can skip the whole metadata section of the template if I don't need it.

    fmt.Sprintf("%s-%s-%s", claimName, workspaceName, pipelineRunName)

Since there always will be a `workspaceName` and a `pipelineRunName`, the PVC name will be `-<claimName>-<pipelineRunName>` and fail because the k8s compatible name can not start with a _dash_. We could omit the first dash in this case and let the PVC get the name `<claimName>-<pipelineRunName>` ?
