### ISSUE TITLE
PipelineRun cleanup and cancelation

### ISSUE THREAD

**Issue by r0bj** [tektoncd/pipeline#2452]
To be able to cleanup old (finished) PipelineRuns, do I need to create some custom cronjob to do so? Or is there any other native way of cleaning it (some sort of PipelineRun retention policy)?

The same question is for with pipeline cancelation: a PipelineRun triggered by EventListener (let's say it's testing github PR). To cancel first PipelineRun (still running) when another PipelineRun of the same type was triggered, do I need to do it manually (eg. using kubectl from inside task using method from https://tekton.dev/docs/pipelines/pipelineruns/#cancelling-a-pipelinerun)? Or is there some native way using special parameters?
Some Pipelines need to be executed as single at a time (due to eg. shared volumes, etc.).

/kind question
/kind feature

**Comment by jlpettersson** [comment]
Yes, there is an issue about creating such a CronJob in https://github.com/tektoncd/experimental/issues/479

This comes up often. We could document that Tekton does not currently have functionality for this.

Also related #2332
