### ISSUE TITLE
Validate result names in Tasks

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/pipeline#2454]
# Expected Behavior

When a Task is submitted the validation checks that result names are allowable.  E.g. "IMAGE_DIGEST" should be disallowed but does not fail validation when the catalog kaniko task is applied: https://github.com/tektoncd/catalog/issues/285

# Actual Behavior

Validation doesn't check the naming format of result names.

# Steps to Reproduce the Problem

1. Submit a Task with an invalid result name: "IMAGE_DIGEST"
2. Notice that validation does not fail.

**Comment by vincent-pli** [comment]
Fixed by #2495
