### ISSUE TITLE
Image/Task Security

### ISSUE THREAD

**Issue by test2016new** [tektoncd/pipeline#2458]
# Expected Behavior
I'm using Tekton and Maven to build my application and deploy in Kubernetes.
I'm using user:root as using Docker in docker inside my task. 
Is there any way not to use user-root and use my id or any default id for 'docker in docker'. If I deploy in production, this approach will not work as user-root is not allowed in production. 

Need to use user - root in the Task for successful image build and push to docker  registry.
# Actual Behavior
Use a default or non-root user in  the Task for successful image build and push to docker  registry.

Thanks!

**Comment by danielhelfand** [comment]
You can define the securityContext via a Pod template like in the example below:

https://github.com/tektoncd/pipeline/blob/master/docs/taskruns.md#pod-template

**Comment by danielhelfand** [comment]
You can also directly define this securityContext on Steps:

https://github.com/tektoncd/pipeline/blob/9fa211017707c6e7039b54b9cb11012b5d66f186/examples/v1beta1/taskruns/build-push-kaniko.yaml#L55

**Comment by danielhelfand** [comment]
Unfortunately, I did not realize there is a bug with this documented in #2179, so it might not work as expected.

**Comment by dibyom** [comment]
Looks like a duplicate of #2179 
I'll close this out in favor of tracking it in that issue
/triage duplicate
/close
