### ISSUE TITLE
Add named fragments for the headings in our docs

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/pipeline#2488]
# Expected Behavior

Changing the text of a Heading in a doc shouldn't break all links pointing to that heading.

# Actual Behavior

Changing the words of a Heading in one of our docs completely breaks any other docs who were linking to it.  This happens because github automatically generates the "fragment identifier" (#foo-bar-baz) from the text of the heading. `## Getting Started With Workspaces` becomes `#getting-started-with-workspaces`.  Changing this text in any way breaks incoming links.

We can fix this by introducing explicit named anchors to our headings like this:

```html
# Getting Started With Workspaces <a name="workspaces-intro"></a>
```

This will allow links from other docs to point at `workspaces.md#workspaces-intro` regardless of the text in the heading.  It would also allow us to preserve those links even when we completely reorganize the structure of a document.

I've seen this happen a lot in our docs and it sucks up a bunch of cycles fixing, testing+reviewing, lgtm'ing etc.

Latest example: https://github.com/tektoncd/pipeline/pull/2484

@sergetron how would you feel about making this a best practice in our doc guidelines?

**Comment by bobcatfish** [comment]
> # <a name="workspaces-intro"></a> Getting Started With Workspaces

That seems like a pretty big ask for folks to create on their own, and then asking reviewers to catch. @sbwsg what do you think if we had some automation that added these kinds of links automatically?

e.g. a periodic job / post merge job that creates (and merges) a PR that adds these links when they are missing

If that doesn't work, I'd rather explore a different docs format (e.g. ascii doc) than ask every doc writer to add these links manually, but I hope we don't have to do that.

Another avenue to explore would be automation that can look across all our docs and find dead links.

**Comment by sbwsg** [comment]
> That seems like a pretty big ask for folks to create on their own, and then asking reviewers to catch.

I'm a tad confused by this.  Is it more work than also picking up on grammar, spelling, punctuation etc in a doc review?  The named anchors only have to be added once and then preserved when headings are changed or docs are reorganized.

**Comment by sbwsg** [comment]
Just as an example (not planning to make a PR until/unless we reach agreement on best way forward), I've updated workspaces.md to include the named fragments: https://github.com/tektoncd/pipeline/compare/master...sbwsg:name-fragments

It only took a few minutes to add these and the benefit will be that we can keep the same named anchors even if we reorganize the info.  So imagine we rewrote the portion of the doc where we list the supported volumesources: As long as we maintain a `<a name="specifying-emptydir-volumesource"></a>` in the doc at the part where we describe the emptydir source then users will continue to land at the correct updated information regardless of any changes to wording / structure of the document.

**Comment by bobcatfish** [comment]
I'm just having a lot of trouble imagining maintaining this over time - basically the more manual gotchas we rely on, the more we'll miss. Happy to discuss more tho!

In the meantime I'm not sure about having "good first issue" on this until we discuss more - maybe we can discuss in the productivity and/or docs working groups.

**Comment by vdemeester** [comment]
> I'm just having a lot of trouble imagining maintaining this over time - basically the more manual gotchas we rely on, the more we'll miss. Happy to discuss more tho!
> 
> In the meantime I'm not sure about having "good first issue" on this until we discuss more - maybe we can discuss in the productivity and/or docs working groups.

I do agree with @bobcatfish, maintaining this over time might be a tiny headache. I think this might have been a reason why we had the `markdown` linter (although I am not sure it was checking for that). I would rather rely on a linter that is capable of erroring out if an anchor link is pointing to the void than having to add those on all the title.

**Comment by vdemeester** [comment]
> Automation and linting don't account for external links into our docs. Allowing names of fragments to change every single time a word is modified in a heading means linking into our docs from blog posts or articles is pointless: those backlinks are dead the moment we decide to make even a tiny edit. Using named anchors makes the backlinks constant so that outside articles can point into sections of our documentation.
>
> On the subject of maintenance burden I think we need to quantify it rather than speak vaguely.
> 
> Current situation: A word is changed in a heading somewhere in a doc. This gets reviewed, approved, and merged. A user then has to notice that links inside our other docs are now broken. We then waste at least 2 people's time - the person who has to make the PR to fix it and the one who has to lgtm + approve. Multiply that by each broken link, since it's unlikely we catch all of them and fix them in a single PR. There's a lag here as well: humans have to notice the broken links. So we add automation to check our internal docs. But automation will never be able to catch all the broken backlinks from external sites into our pages.
> 
> With named anchors the work is actually reduced: reviewers notice during a docs PR review that the link name is changed or removed and ask for it to be put back / reorganized with the content. Backlinks from external sites remain constant and we can have automation check our internal doc links if we want to.
> 
> So I dunno. I think this is less work, more explicit, and more useful than what we do currently.

This is true, but it's also true any time we will want to refactor our docs (like https://github.com/tektoncd/pipeline/pull/2364). Some of those header might change significantly and thus the name would have to be changed, and you have broken link again. This is a problem that all docs are facing ; how many times do I ran into dead "anchor" links on the k8s doc, openshift doc, gcloud doc, git doc, …. In general I do agree with you but… 

Questions are : When do we account for broken links ? And which ones can we "limit" ?

We can't make sure external links won't be broken (if the doc gets refactored, or moved), **especially** if it's a link targeting the `tektoncd/pipeline` GitHub repository (but any really). There is no guaranteed made that github will always serve the content in a way or another, same for the folder we put our `docs` in, at some point it might change, etc.. The story is a bit different on `tekton.dev`.

We can make sure "local" links are not broken, aka links in the same repository, or maybe in all content served my `tekton.dev`. At least our docs would always be consistent and without dead link.

This put some html tags in a markdown file, this assumes writers know html, this also assumes it will be published as `html`. Those assumption might not always be true, an example, on `tektoncd/cli`, part of our docs in `markdown` becomes a `man` page. Having those means complexifying the code to generate the man page from markdown, *and* remove one benefit of what markdown is supposed to provide (aka having a text-only syntax, not relying on html — or another other "output" implementation detail). [`pandoc`](https://pandoc.org) version of Markdown has a "cleaner" way to do that : [heading identifiers](https://pandoc.org/MANUAL.html#heading-identifiers)

For me forcing those would add burden on the contributors on something that is not fully solvable, that can be limited a little bit (at least on what we control) and that is a tooling limitation (markdown doesn't support this, nor we have a tool that would make us translate old link to new ones, …). I am not entirely against but I don't know if the tradeoff balance is positive or not.

**Comment by sbwsg** [comment]
OK sounds good to me.  Your points about pandoc offering this as a feature, github not guaranteeing our links, and the CLI having to filter out html make sense to me.  I'm going to close this issue now.  I'm not going to argue in favor of named fragments anymore because they're clearly not the right solution.

**Comment by sergetron** [comment]
Since I was out yesterday and Vincent asked for my opinion, my TL;DR is
that while named anchors are a great idea, they only solve the problem if a
heading is slightly reworded. If the section is deleted, moved, or
rewritten and the heading must change completely, the anchor goes out of
sync with the heading meaning-wise and we'll have links like
[Installing Smurfcaptor 9000 On
Debian](#getting-started-with-smurf-catching). Whenever I make edits in a
doc, I check and fix all links it contains. If we do this for all docs
every time we edit them, we'll maintain at least *a* level of link
validation. In Bazel docs, we had a linter that checked links and blocked
the update CL/PR if broken links were detected.

Disclaimer: The above thoughts are mid-coffee.
