### ISSUE TITLE
ServiceAccount

### ISSUE THREAD

**Issue by 2020testuser** [tektoncd/pipeline#2492]
I read the documentation on Pipeline security. Looking for some clarification with deep dive details on the security. This is not an issue. However, trying to get more details on the security side.

1. If user A has access to pipeline A in namespace A and user B has access in pipeline B in namespace B , when the tasks in pipeline A calls the step in pipeline B, how this can be achieved?
 Option 1 is create grant access to user A to namespace B. Option  2 is create a new pipeline in namespace C with access to both user A and B and both pipelines in namespace C. (not a good option). Is there a better solution?
2.  My understanding is  that ServiceAccount can be used to control access at the pipeline level. Can different service accounts be used to control access at the each task or each step level?
I don't want to use user-root in my Tasks and wondering whether Service Account would solve the problem.

3. I believe multi-tenancy can be managed at the namespace level. Are there other options? Thanks in advance!

**Comment by jlpettersson** [comment]
>If user A has access to pipeline A in namespace A and user B has access in pipeline B in namespace B , when the tasks in pipeline A calls the step in pipeline B, how this can be achieved?

A Pipeline can not use Tasks from another _namespace_. But you can use [ClusterTask](https://github.com/tektoncd/pipeline/blob/master/docs/tasks.md#task-vs-clustertask) that is available in all namespaces in the cluster.

>Option 1 is create grant access to user A to namespace B. Option 2 is create a new pipeline in namespace C with access to both user A and B and both pipelines in namespace C. (not a good option). Is there a better solution?

It depends on what you are trying to achieve. When I implement Tekton for an organization, we use some cluster-wide ClusterTasks and some local Tasks in the namespace.

It is also possible to allow users that does not have access to the namespace to initiate `PipelineRuns` or `TaskRuns` through a `Trigger`.

> Can different service accounts be used to control access at the each task or each step level?

Yes, you can you some specific service accounts for some specific tasks, if you want.

> I believe multi-tenancy can be managed at the namespace level. Are there other options?

Yes, that is what I do. In combination with some reusable `ClusterTasks`.

**Comment by 2020testuser** [comment]
Thanks Much ! I will dig into Trigger more .
