### ISSUE TITLE
Document migration from BuildTemplate+Build to Task+TaskRun

### ISSUE THREAD

**Issue by ImJasonH** [tektoncd/pipeline#250]
Related to #147

As a former Build user, it should be straightforward for me to migrate BuildTemplates and Builds I had previously defined to match the new model for Pipelines.

In the new model, a `BuildTemplate` is roughly equivalent to a `Task` (stateless, parameterized resources which are invoked), and a `Build` is roughly equivalent to a `TaskRun` (the running invocation, with state).

There are some differences, particularly around how `Task` parameters are defined and passed into steps, and how currently you can only create a `Task` from a pre-defined `TaskRun` (#249).

At a minimum we should document how to migrate to the new world, and ideally we would be able to write a script that transforms a Build YAML into a TaskRun YAML, likewise for BuildTemplate -> Task.

**Comment by bobcatfish** [comment]
I think this is unblocked now! But @shashwathi I'm guessing you're in a good position to take this on since you've migrated so many examples in #493 🙏 ? No worries tho if you'd rather not take it on :D

**Comment by vdemeester** [comment]
I think we are good closing this one, https://github.com/tektoncd/pipeline/blob/master/docs/migrating-from-knative-build.md is there, and `knative/build` is "long gone" :angel: 

/close
