### ISSUE TITLE
Is the config webhook working ?

### ISSUE THREAD

**Issue by eddycharly** [tektoncd/pipeline#2503]
The namespace selector in the webhook requires that the label `pipeline.tekton.dev/release` exists:
https://github.com/tektoncd/pipeline/blob/a7a4c5da019d630fd0ef7e570369bb4ef218104d/config/500-webhooks.yaml#L77-L80

The label is not set on the namespace definition though:
https://github.com/tektoncd/pipeline/blob/a7a4c5da019d630fd0ef7e570369bb4ef218104d/config/100-namespace.yaml#L15-L18

Do i misunderstand the configuration here ?

**Comment by vdemeester** [comment]
Oh yes, you are right :scream: The label is missing in the namespace :man_facepalming:  

/kind cleanup
/kind question

**Comment by eddycharly** [comment]
Fixed in https://github.com/tektoncd/pipeline/pull/2501
