### ISSUE TITLE
Recommend using `ko apply --strict`

### ISSUE THREAD

**Issue by pierretasci** [tektoncd/pipeline#2509]
# Expected Behavior
The docs under `DEVELOPMENT.md` would call for the user to run `ko apply --strict -f config/` since the ko documentation calls that out as a better way to ensure the right thing happens when you are applying local changes to a cluster.

# Actual Behavior

It doesn't recommend passing the strict flag.

Relevant section here: https://github.com/tektoncd/pipeline/blob/master/DEVELOPMENT.md#redeploy-controller

**Comment by vdemeester** [comment]
Agreed!

/kind feature
