### ISSUE TITLE
Allow PipelineRuns to provide extra parameters

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#2513]
# Expected Behavior

Imagine you have a system creating PipelineRuns automatically, and each PipelineRun uses a different Pipeline which has a different set of parameters. The system has a number of parameters it knows how to provide, e.g. the service account and url of a bucket the Pipelines can push to (but not all Pipelines need to push to a bucket).

It would be very convenient if the system creating the PipelineRuns could provide all the parameters it has available to all PipelineRuns, and the Pipelines could use the ones they need and ignore the rest.

# Actual Behavior

If a PipelineRun provides extra params to a Pipeline, it will fail (99% sure!). This means that the system creating the PipelineRuns described above will need to look at each Pipeline, see what params it needs, and only provide the correct params. This feels like a level of complication that doesn't add much.

# Additional Info

* You can use TriggerBindings + TriggerTemplates to accomplish this today; TriggerBindings can provide params that TriggerTemplates do not use, but you have to involve an EventListener to make it work
* The specific use case which is motivating me to suggest this is designing the test infrastructure fo the Tekton catalog (some details [in this design doc](https://docs.google.com/document/d/1pZY7ROLuW47ymZYqUgAbxskmirrmDg2dd8VPATYXrxI/edit#heading=h.e9bh8qes6kh6)). The proposal is using TriggerBindings + TriggerTemplates because they allow this functionality, but beyond that there is no reason to use Triggers for this and it would be nice to simplify the design by removing that component.
* This might be an incremental improvement of the situation described in https://github.com/tektoncd/pipeline/issues/1294

**Comment by bobcatfish** [comment]
Oh I think this is actually completed! Turns out there was NO validation at all XD in #2708  @jerop improved this so that we now check that AT LEAST the required params are provided, but the current state should be that you can provide extra

/assign jerop

**Comment by jerop** [comment]
Similarly, @bobcatfish does it make sense to allow TaskRuns to provide extra parameters? 
We currently [disallow TasksRuns from providing extra parameters](https://github.com/tektoncd/pipeline/blob/4e99cb84ed624f6d48d9ff28249cda5364cd3358/pkg/reconciler/taskrun/validate_resources.go#L91-L94) -- can open a separate PR for it

**Comment by bobcatfish** [comment]
> We currently disallow TasksRuns from providing extra parameters -- can open a separate PR for it

my personal feeling is to avoid adding that until someone has a compelling use case for it - maybe im wrong to draw a distinction between pipelineruns and taskruns but i feel like the use case we have, where a system is generating pipelineruns, is more likely than taskruns

**Comment by jerop** [comment]
> my personal feeling is to avoid adding that until someone has a compelling use case for it - maybe im wrong to draw a distinction between pipelineruns and taskruns but i feel like the use case we have, where a system is generating pipelineruns, is more likely than taskruns

sounds good 👍
