### ISSUE TITLE
Break Pipelines' dependency on Build

### ISSUE THREAD

**Issue by ImJasonH** [tektoncd/pipeline#252]
Today, when `TaskRun`s are created, they in turn create a `Build`, which creates a `Pod`. As the `Pod` executes, the `Build` status is updated, and in turn the `TaskRun`'s status is updated.

Instead of all of this indirection, creating a `TaskRun` should simply create and watch a `Pod`, and update its status as it goes along.

This is dependent on the work in #243 so that `TaskRunStatus` has all of a `BuildStatus`' fields, and on https://github.com/knative/build/pull/464 which simplifies the `Build` controller uses to create and watch for pod updates, making it simpler to forklift into the `TaskRun` controller.

/assign ImJasonH

**Comment by bobcatfish** [comment]
Copying in @ImJasonH 's sweet image from #326:

![image](https://user-images.githubusercontent.com/432502/50986532-eb433180-14bb-11e9-86b0-547ac4aa06d7.png)

At this point we have gotten to Phase 1, next step will be Phase 2.
