### ISSUE TITLE
Pods status wrong when unnamed step fails (followed by named step)

### ISSUE THREAD

**Issue by praveen4g0** [tektoncd/pipeline#2529]
# Expected Behavior
Pods status should show `error`
```bash
$ oc get pods
NAME                                                     READY   STATUS      RESTARTS   AGE
test-unnamed-correct-jw2nl-pod-4m4lz      0/4       Error                     0          16m
test-unnamed-wrong-6snn5-pod-95cbq     0/4        Error                     0          16m
```
# Actual Behavior
```bash
$ oc get pods
NAME                                                       READY    STATUS      RESTARTS   AGE
test-unnamed-correct-jw2nl-pod-4m4lz     0/4           Completed           0          16m
test-unnamed-wrong-6snn5-pod-95cbq     0/4           Error                    0          16m
```

# Steps to Reproduce the Problem

1. Create `taskrun`
 ```bash
oc create -f https://gist.githubusercontent.com/praveen4g0/cac6134def1034b029c92195495ea824/raw/5ded34dd71fd18b302cf3c160cfa350350d45fe6/unamed-steps-pod-status.yaml
```
2. Wait for `taskrun` to fail 

3. Check for pods status

# Additional Info

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

   **v0.11.3**

**Comment by vincent-pli** [comment]
@praveen4g0 
The `STATUS` of `kubectl get po` is come from `State.Terminated.Reason` of one container of the `pod`, maybe the first not nil one.
So let's back to your sample, the `step-named-step` will go beyond `step-unnamed-x` as the first one(sort by first character), so its `State.Terminated.Reason` will be displayed. That's why the behavior are not consistent.

That's means `tekton` can do nothing about the issue.

**Comment by khrm** [comment]
Yea, as @vincent-pli commented.
It's because Pod status in oc get/kubectl get is status of first container in alphabetical order.
Just change your name here to x-named-step, https://gist.github.com/praveen4g0/cac6134def1034b029c92195495ea824 you will see Completed for both taskrun pod.

**Comment by bobcatfish** [comment]
It sounds like this isn't a bug in Tekton so I'll close this, please re-open if I'm wrong
