### ISSUE TITLE
Remove tekton.dev/task label from ClusterTask TaskRuns

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/pipeline#2533]
# Expected Behavior

TaskRuns started from a ClusterTask should only have the label `tekton.dev/clusterTask=<task name>`. 

# Actual Behavior

TaskRuns started from ClusterTasks currently receive both `tekton.dev/clusterTask=` and `tekton.dev/task=`.

# Steps to Reproduce the Problem

1. Run a TaskRun referencing a Cluster Task
2. View its YAML or its Pod's YAML
3. See `tekton.dev/task` label

- Tekton Pipeline version: 0.12.0

**Comment by sbwsg** [comment]
This was announced as deprecated in 0.12.0 so should be removable from Pipelines on/after Jan 30 2021

**Comment by piyush-garg** [comment]
PR #2527 for it but needs to be merged later

**Comment by sbwsg** [comment]
Can I suggest that we close this until the deprecation window has closed?  I'd prefer not to keep this PR open for 9 months.

What do others think?  I've documented the deprecation of the annotation here: https://github.com/tektoncd/pipeline/blob/master/docs/deprecations.md

**Comment by lee-zhg** [comment]
I got error: 'error: unable to recognize "tekton/tasks/source-to-image.yaml": no matches for kind "Task" in version "tekton.dev/v1beta1"' today and it worked last week.

Is this related to this depreciation?

Thank you
Lee

**Comment by sbwsg** [comment]
@lee-zhg no, this change wasn't merged yet so it's unlikely to be related.  Feel free to create a new issue if your problem persists.  Please include any more information you can - Tekton version, the Task YAML, etc.

**Comment by vdemeester** [comment]
As this is a deprecation "follow-up", let's not mark it as stale

/remove-lifecycle stale
/lifecycle frozen
