### ISSUE TITLE
Cannot install v0.12.0 - release.yaml 404

### ISSUE THREAD

**Issue by wlynch** [tektoncd/pipeline#2550]
# Expected Behavior

Tekton successfully updates using instructions from https://github.com/tektoncd/pipeline/releases/tag/v0.12.0:

```sh
kubectl apply -f https://storage.googleapis.com/tekton-releases/tektoncd/pipeline/previous/v0.12.0/release.yaml
```

# Actual Behavior

```sh
$ kubectl apply -f https://storage.cloud.google.com/tekton-releases/tektoncd/pipeline/previous/v0.12.0/release.yaml

error: error parsing https://storage.cloud.google.com/tekton-releases/tektoncd/pipeline/previous/v0.12.0/release.yaml: error converting YAML to JSON: yaml: line 11: mapping values are not allowed in this context

$ curl http://storage.googleapis.com/tekton-releases/tektoncd/pipeline/previous/v0.12.0/release.yaml
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: tekton-releases/tektoncd/pipeline/previous/v0.12.0/release.yaml</Details></Error>%
```

# Additional Info

Looks like the correct URL should be: http://storage.googleapis.com/tekton-releases/pipeline/previous/v0.12.0/release.yaml

**Comment by afrittoli** [comment]
I fixed the release text with the [correct link](
https://storage.cloud.google.com/tekton-releases/pipeline/previous/v0.12.0/release.yaml), I will update the template in the automation to produce the correct link.

**Comment by afrittoli** [comment]
https://github.com/tektoncd/plumbing/pull/374
