### ISSUE TITLE
Do not fetch pipeline, tasks, resource and run validation once a pipeline is "done"

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/pipeline#2552]
# Expected Behavior
Once the `pr.IsDone()` condition is met in the pipelinerun reconciler, we should not need to fetch all resources the pipelinerun depends on and re-run validation.

# Actual Behavior
`ResolvePipelineResultRefs`, the function that resolves pipeline results to their values, is only applied in the reconcile cycle once we reach the pr.IsDone()`  status. 
Since it takes a `PipelineRunState` as an input, it forces us to rebuild that object, which means fetching pipeline, all tasks, all resources and running validation. The only thing we need is the list of taskruns with their statuses (which include results), I wonder if we could take them from the pipelinerun status which we already have in the `pr` object instead of re-running all that.

# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- Tekton Pipeline version:

`v0.12.0`

**Comment by othomann** [comment]
@afrittoli I provide a first pass on this issue in https://github.com/tektoncd/pipeline/pull/2690. Will refine if necessary.
