### ISSUE TITLE
Write our own helper image to stop sidecars

### ISSUE THREAD

**Issue by ImJasonH** [tektoncd/pipeline#2560]
# Problem

Today, Tekton uses the `tianon/true` image to stop sidecar execution when steps complete. It's a small image that exits successfully immediately. We use it by updating sidecar containers' image to the `true` image, which stops the sidecar execution immediately (successfully).

This image isn't owned or maintained by the Tekton team, and though we expect it to be fairly stable and bug-free, we can't easily fix any bugs or add functionality if we decide we need to. It might also present licensing problems in some circumstances.

# Proposal

Provide our own small Go binary in an image based on `distroless` to perform this functionality. For example, `cmd/stop` simply `os.Exit(0)`s immediately.

This image would be built and released using `ko` alongside all the other Tekton images.

If this seems reasonable, it should be a fairly #goodfirstissue for a potential new contributor.

**Comment by ImJasonH** [comment]
Well don't I feel silly: https://github.com/tektoncd/pipeline/pull/1510 😬

**Comment by dlorenc** [comment]
I think you just fixed this with #3025
