### ISSUE TITLE
Question - is there a way to pass git branch/revision in a task?

### ISSUE THREAD

**Issue by vikas027** [tektoncd/pipeline#2565]
# Problem
I am trying to reuse my git resource which defaults to a `master` branch in different tasks but with different branches.

Is it possible to do something similar to below?

```yaml
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-name
spec:
  params:
  resources:
    inputs:
    - name: workspace
      type: git
      revision: <some-other-branch-than-master>
```
# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
~ $ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2+k3s1", GitCommit:"698e444a03fe3a705849fc8d9ad9e35f1dffe286", GitTreeState:"clean", BuildDate:"2020-05-07T00:18:01Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
~ $
```

- Tekton Pipeline version:

  **Output of `tkn version`**

```
~ $ tkn version
Client version: 0.9.0
Pipeline version: v0.12.0
~ $
```

**Comment by vdemeester** [comment]
You would need to create a new PipelineResource for the branch you want to use (specificying the revision there)
/kind question

**Comment by vikas027** [comment]
Ah, ok. Yeah, I know I can do that. Wouldn't be it nicer to create a `PipelineResource` with a default `revision` (say `master`) and then reuse the resource in `PipelineRun` but with a different `revision`, something like this?

```yaml
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipelinerun-<name>
spec:
  serviceAccountName: <service_account>
  pipelineRef:
    name: pipeline-<name>
  resources:
  - name: source-repo
    resourceRef:
      name: <pipelineresource_name>
      revision: <some-other-branch-than-master>
```

**Comment by vdemeester** [comment]
@vikas027 that's not really how PipelineResource are designed ; they are designed to be swapable "as-is" in a Pipeline/Task (through binding in PipelineRun/TaskRun). You can however use `worksace` and the `git-clone` task from [`tektoncd/catalog`](https://github.com/tektoncd/catalog) to have more control and pass the revision as a param for the `git-clone` task.

**Comment by vikas027** [comment]
Cool, @vdemeester . I will try to use the same. I found an example [here](https://developer.ibm.com/tutorials/build-and-deploy-a-docker-image-on-kubernetes-using-tekton-pipelines/#create-a-task-to-clone-the-git-repository).
