### ISSUE TITLE
Faile: create workspace from volumeclaimtemplate, binding "task-ws" is invalid

### ISSUE THREAD

**Issue by HefeiJoe** [tektoncd/pipeline#2584]
kubectl create -f https://github.com/tektoncd/pipeline/blob/master/examples/v1beta1/pipelineruns/workspace-from-volumeclaimtemplate.yaml

![image](https://user-images.githubusercontent.com/27885579/81368070-76b8eb00-9121-11ea-9ec3-d5c636fc3500.png)

**Comment by jlpettersson** [comment]
The `volumeClaimTemplate` option was introduces in Tekton Pipelines v0.12.0. This example will not work on earlier versions.

**Comment by afrittoli** [comment]
@HefeiJoe thank you for your bug report. 
Could you share your Tekton version and K8s version?

It would be greatly helpful if you could follow the issue template when filing issues in future.

/kind question

**Comment by HefeiJoe** [comment]
> The `volumeClaimTemplate` option was introduces in Tekton Pipelines v0.12.0. This example will not work on earlier versions.
@jlpettersson  Thanks
