### ISSUE TITLE
Wrap `cmp.Diff` to make clear the (want, got) ordering of arguments.

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/pipeline#2587]
# Expected Behavior

In https://github.com/tektoncd/pipeline/pull/2580 we are trying to make test diff formatting uniform.  There is still room for user-error though: if the user did not call `cmp.Diff` with arguments in the expected order `(want, got)`, then the diff they print with `diff.Print` will be incorrect / reversed.

One possible improvement over this would be to wrap `cmp.Diff` with a [B.Helper](https://golang.org/pkg/testing/#B.Helper) called something like `diff.FailIfWantGot(want, got, interface{}, format string)` which clearly indicates the order of arguments in the func's name and could apply the correct formatting.  Usage could look something like this ([suggested by @bobcatfish in this comment](https://github.com/tektoncd/pipeline/pull/2580#discussion_r421788275)):

```go
diff.FailIfWantNotGot(tc.expectedTaskSpec, *ts, "Didn't get expected TaskSpec modifications")
```

# Additional Considerations

1. `cmp.Diff` takes additional options which some of tests utilize to ignore certain fields.

2. Some of our tests use cmp.Diff with `t.Fatalf` and some with `t.Errorf`.  This could be another parameter to the func?  Or we could have two helpers?  Or we could not worry about it and only support one of them?

```go
// Have separate funcs for errorf and fatalf
// Errorf
diff.ErrorIfWantNotGot(tc.expectedTaskSpec, *ts, "Didn't get expected modifications")
// Fatalf
diff.FatalIfWantNotGot(tc.expectedTaskSpec, *ts, "Didn't get expected modifications")
```

```go
// Pass format printer to func
diff.WantGot(tc.expectedTaskSpec, *ts, t.Fatalf, "Didn't get expected TaskSpec modifications")
```

**Comment by 2pai** [comment]
hi @sbwsg, this is my first time looking to tektoncd repository, 
is it okay for a first-timer to have a shot on this?

**Comment by sbwsg** [comment]
@2pai Sure thing, thanks for your interest!  Since this is your first contribution I suggest you write the helper funcs first and make a PR.  Once code reviewers are happy with the helpers you could then replace usages of `cmp.Diff` in a separate commit or PR.

**Comment by sbwsg** [comment]
Also, feel free to reach out to me on [Slack](https://github.com/tektoncd/community/blob/master/contact.md#slack) (user: Scott) if you need any pointers.

**Comment by NikeNano** [comment]
@2pai, @sbwsg is this progressing? I can make a quick fix it this is not moving :)

**Comment by 2pai** [comment]
Hi , i'm sorry for late
I will submit the PR @NikeNano @sbwsg
