### ISSUE TITLE
Add a check to ensure diff.PrintWantGot is used

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/pipeline#2594]
> Can we have a presubmit check to ensure I don't add a new `cmp.Diff` call that bypasses the helper? Otherwise I'm going to make sure we're going to need one of these PRs every few quarters sweat_smile.

In https://github.com/tektoncd/pipeline/pull/2580, we migrated `cmp.Diff` to better functions (simpler to use, using `diff.PrintWantGot()`). To make sure we don't have to do #2580 again in the future, we should add a `presubmit` check to check for this.

This can be done as in a `pre_build_tests` (https://github.com/tektoncd/plumbing/blob/master/scripts/presubmit-tests.sh#L114)

/kind cleanup
/area testing

**Comment by sbwsg** [comment]
Also worth keeping in mind that in future [we might not be using `cmp.Diff` at all](https://github.com/tektoncd/pipeline/issues/2587), and replace it with a helper that does the diffing and formatting together.
