### ISSUE TITLE
Ability to burst builds into cloud as capacity becomes limited

### ISSUE THREAD

**Issue by shuawest** [tektoncd/pipeline#2596]
Alternative tools such as CloudBees have a central operations manager that controls where to schedule builds. As an on-premise cluster reaches capacity the operations manager is able to target builds to an alternative on a scale public cloud cluster. While Tekton tasks can be directed to a specific target, is there a way to have the target be controlled by the build queue depth, cluster capacity, etc?

**Comment by dibyom** [comment]
This would be a cool feature but at the moment, the Tekton controller only schedules on the cluster it is running on. Could be a proxy of some kind that can schedule the calls to the right clusters based on load

/kind feature

**Comment by shuawest** [comment]
At this point, the plan would be to have the user create a Condition for a build task that looks up the build queue length and/or available cluster capacity to target on-prem versus public cloud.
