### ISSUE TITLE
submodule update --recursive failed

### ISSUE THREAD

**Issue by master221** [tektoncd/pipeline#2598]
# Expected Behavior
it should append --depth only once
# Actual Behavior
"Error running git [submodule update --recursive --depth --depth=1]: exit status 1\nfatal: depth --depth=1 is not a positive number
https://github.com/tektoncd/pipeline/blob/master/pkg/git/git.go#L172
# Steps to Reproduce the Problem

1. /ko-app/git-init -url <repo> -revision FETCH_HEAD -refspec +refs/heads/mybranch:refs/remotes/origin/mybranch -path /workspace/output/ '-sslVerify=true' '-submodules=true' -depth 1
2.
3.

# Additional Info

- Kubernetes version:
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-21T01:25:41Z", GoVersion:"go1.13.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.9", GitCommit:"2e808b7cb054ee242b68e62455323aa783991f03", GitTreeState:"clean", BuildDate:"2020-01-18T23:24:23Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

- Tekton Pipeline version:
v0.12.0

**Comment by sbwsg** [comment]
fyi @ad22 this looks possibly related to the refactoring added to git-init?

**Comment by ad22** [comment]
Appears so. I'll attempt to fix it.

**Comment by ad22** [comment]
Fixed in #2602

**Comment by dlorenc** [comment]
This was fixed in https://github.com/tektoncd/pipeline/pull/2602
