### ISSUE TITLE
FR: Document runtime contract and deprecation policy

### ISSUE THREAD

**Issue by ImJasonH** [tektoncd/pipeline#2599]
# Expected Behavior

The runtime contract is documented and well understood. Changes to the contract (incl. additions to the contract that may not have been enforced/documented in the past) adhere to a documented deprecation policy.

# Actual Behavior

🤷‍♂️ Nope.

# Examples

- Environment variables that Tekton adds to steps' env vars
- Volumes/paths available to steps (incl. permissions)
- Any guarantees about task execution within a pipeline that Tekton itself enforces

Please add a comment if you can think of something that's missing!

/kind documentation
/kind feature

**Comment by bobcatfish** [comment]
We do have https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md but maybe there is something still missing?
