### ISSUE TITLE
Using v0.12.0 as a Go module breaks due to a knative/pkg error

### ISSUE THREAD

**Issue by nickgerace** [tektoncd/pipeline#2613]
# Expected Behavior

Using Tekton pipelines v0.12.0 as a Go module should not break due to dependencies not being compatible with 18.X k8s APIs.

# Actual Behavior

Since knative/pkg is not compatible with k8s 18.X APIs, using Tekton pipelines v0.12.0 as a Go module fails.

# Steps to Reproduce the Problem

1. Create a Go project
2. Use Tekton v0.12.0 as a Go module, which uses k8s 18.X APIs
3. Perform a go build using the Tekton API in your code

# Additional Info

- Kubernetes version: n/a (no cluster used)

- Tekton Pipeline version: v0.12.0

Hi all! Thanks for the work you all do on Tekton. I made a note of this breakage in the [knative/pkg](https://github.com/knative/pkg/issues/1280) repository as well. Please let me know if you need anything more.

**Comment by vdemeester** [comment]
@nickgerace thanks for the issue. This is mainly because of https://github.com/tektoncd/pipeline/blob/master/go.mod#L57 (the `replace` section). We might be able to clean that once release-0.15 of knative/pkg is released (as it will use go modules)

/kind cleanup

**Comment by nickgerace** [comment]
Ah I see. Yep, I've commented on the issue there as well. Thank you; I'll keep an eye on this.

**Comment by nickgerace** [comment]
I'll close this issue because I believe I've expressed the symptoms, and not the root issue: client-go (other other Kubernetes APIs) v1.18+ support.
