### ISSUE TITLE
Release notes have incorrect URL for v 0.12.release

### ISSUE THREAD

**Issue by jlewi** [tektoncd/pipeline#2628]
The release notes appear to have an incorrect link for the v0.12 release.

The release notes are here:
https://github.com/tektoncd/pipeline/releases/tag/v0.12.1

Which contain the command 

```
kubectl apply -f https://storage.googleapis.com/tekton-releases/Pipeline/previous/v0.12.1/release.yaml
```

This URL doesn't appear to exist

```
curl  https://storage.googleapis.com/tekton-releases/Pipeline/previous/v0.12.1/release.yaml
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: tekton-releases/Pipeline/previous/v0.12.1/release.yaml</Details></Error>
```

I think the problem is that `pipeline` should not have a capital `p`.

The  following URL exists.

```
curl https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.12.1/release.yaml
```

**Comment by afrittoli** [comment]
Thanks for the report!
I fixed the link - it looks that the URL is case sensitive (?!)

**Comment by vdemeester** [comment]
As it seems to be fixed, let's close this :angel: 
Thanks for the repo @jlewi 
/close
