### ISSUE TITLE
Feedback on Conditions

### ISSUE THREAD

**Issue by jlpettersson** [tektoncd/pipeline#2635]
# Expected Behavior

That "conditions" is easy to use and easy to understand.

# Actual Behavior

Things actually work, the way I expect, almost. But it is not straightforward to understand.

# Proposed improvements

* In the [conditional pipeline example](https://github.com/tektoncd/pipeline/blob/master/examples/v1beta1/pipelineruns/conditional-pipelinerun.yaml), the word `from: [first-create-file]` within a `resource` is _very_ hard to detect. This dictate the task-ordering here. It would be easier to read if the `runAfter`-syntax is used.

* Terminology, "condition" and "conditions" is probably technically correct. But in programming I am used that "conditionals" means _based on this expression do this or else do that_. In Tekton, the "conditions" acts as "guards" for the Task. In programming this **concept** is usually called "Guards", e.g. [Guards in Rust](https://doc.rust-lang.org/stable/rust-by-example/flow_control/match/guard.html), [Guards in Erlang](https://www.tutorialspoint.com/erlang/erlang_guards.htm) but the syntax may be e.g. `when:` as in previous links and in e.g. [Kotlin when expression](https://kotlinlang.org/docs/reference/control-flow.html#when-expression)

  example:
  ```
         (b) 
       / 
   (a) 
       \
         (c) 
  ```
  If called "conditional", I imagine that the _check_ is located in `(a)` and then do `(b)` or `(c)` based on evaluation. But if called "guard" (at least conceptually), I easier understand that it can be on e.g. `(b)` just before the Task executed, as how it works on Tekton today.

* We do not distinguish an _evaluation error_ and when a condition is _evaluated as condition-not-met_. In programming this is fine, because it is just "expression" that is evaluated to `true`  or  `false`. But Tekton is dealing with a _distributed system_ and things will fail. 

  E.g. it may make sense to do a `retry` when an evaluation _fails_, but not when an evaluation of a condition evaluates to _condition-not-met_.

  ***There is still missing pieces here to correctly distinguish between an _evaluation fail_ and _condition-not-met_***

  Can _conditional_-containers write `true` or `false` as _termination message_ and `exit 0` on successful evaluation?

* Be able to _negate_ a `Condition`. I have a use-case were I want to do X (e.g. deploy) when the `PipelineRun` was triggered on _master_ git-branch, OR do Y (e.g. create preview-environment) if the `PipelineRun` was **not** triggered on _master_ git-branch. Here I would like to use the _same_ `Condition` (eg. `conditionRef:` `<name>` in example) on both, but negate it on one. But then it is important to fail both in case of an evaluation error occur, e.g. empty-string as branch-name (that is a configuration error).

  ```
   conditions:                # alternatively "guards:"
     - when:
         conditionRef: <name>
     - whenNot:               # or notWhen
         conditionRef: <other-name>
  ```

* Unclear flow. E.g. what happens after a condition? It is a bit unclear, but I have tested. 

  ```
         (b) — (e)
       / 
   (a) 
       \
         (c) — (d)
  ```

  If "condition" is set on `(c)` - e.g `(c)` is _guarded_ by a "condition". And when _evaluated to false_, the steps in `(c)` is **not evaluated**, also Task `(d)` is **not evaluated**. (as I expected). But `(b)` and `(e)` is evaluated, and the `PipelineRun` successfully completed.

* Add option to continue after a Task-not-evaluated.

  ```
         (b) — (e)
       / 
   (a) 
       \
         (c) — (d)
  ```
  If the "condition" is evaluated to `false` on `(c)`, I may want to execute `(d)` anyway. The `runAfter:`-syntax is very clear and it is good to use _few_ elements to dictate task-ordering (since it must be easyli understood by authors and readers). We could introduce some _twist_ on `runAfter: ['c']` - to execute `(d)` even if the condition on `(c)` evaluates to `false`. (Not if condition-evaluation `fails` e.g. `err`). E.g. `runAfterUnconditionally: ['c']`.

  Related to: https://github.com/tektoncd/pipeline/issues/1023, https://github.com/tektoncd/pipeline/issues/1797#issuecomment-571077462, https://github.com/tektoncd/pipeline/issues/2127

* Waiting for a branch that **may** be executed (in case `(c)` is guarded by a condition not met), as `(f)` does with `runAfter:['d', 'e']`

  ```
         (b) — (e)
       /          \ 
   (a)              (f)
       \          /
         (c) — (d)
  ```
  We should handle this, e.g. with that `(f)` use a `runAfterOneOf:['d', 'e']`

* When a task run after (using `runAfter:`) a task that actually _fail_, a Pipeline author should be able to declare that the failed task wasn't so important, it was [allowedToFail](https://gitlab.com/gitlab-org/gitlab-foss/-/issues/51751). This is different than _condition-not-met_. The task after the failed, should be able to actually check if the previous task failed using a `Condition` (_guard_).

  But we still need a `finally:` pipelineTask, that also can have a `Condition`.

  Related to: https://github.com/tektoncd/pipeline/issues/1023, https://github.com/tektoncd/pipeline/issues/1684#issuecomment-611016087, https://github.com/tektoncd/pipeline/issues/2446

/kind design

**Comment by bobcatfish** [comment]
/reopen
/remove-lifecycle rotten

I think a lot of the points @jlpettersson brought up are being addressed in the new conditions proposal https://github.com/tektoncd/community/blob/master/teps/0007-conditions-beta.md

@jerop if you get a chance could you update this issue re. which of the issues above are being addressed and how?

**Comment by jerop** [comment]
Thank you for the feedback @jlpettersson :)

These are some ways we've addressed the feedback in the[ Conditions Beta](https://github.com/tektoncd/community/blob/master/teps/0007-conditions-beta.md#tep-0007-conditions-beta) work:
> * In the [conditional pipeline example](https://github.com/tektoncd/pipeline/blob/master/examples/v1beta1/pipelineruns/conditional-pipelinerun.yaml), the word `from: [first-create-file]` within a `resource` is _very_ hard to detect. This dictate the task-ordering here. It would be easier to read if the `runAfter`-syntax is used.

In the example in [WhenExpressions](https://github.com/tektoncd/pipeline/pull/3135/files#diff-f7386fff290e39a15d2d82f2c3b8fbcfR1-R225), we reference the resources directly in the `Input` or `Values` using syntax used broadly in tekton, such as `$(params.branch)` or `$(tasks.aTask.results.aResult)`

> * Terminology, "condition" and "conditions" is probably technically correct. But in programming I am used that "conditionals" means _based on this expression do this or else do that_. In Tekton, the "conditions" acts as "guards" for the Task. In programming this **concept** is usually called "Guards", e.g. [Guards in Rust](https://doc.rust-lang.org/stable/rust-by-example/flow_control/match/guard.html), [Guards in Erlang](https://www.tutorialspoint.com/erlang/erlang_guards.htm) but the syntax may be e.g. `when:` as in previous links and in e.g. [Kotlin when expression](https://kotlinlang.org/docs/reference/control-flow.html#when-expression)
>   example:
>   ```
>          (b) 
>        / 
>    (a) 
>        \
>          (c) 
>   ```
>   
>   
>   If called "conditional", I imagine that the _check_ is located in `(a)` and then do `(b)` or `(c)` based on evaluation. But if called "guard" (at least conceptually), I easier understand that it can be on e.g. `(b)` just before the Task executed, as how it works on Tekton today.

Terminology was [clarified in the TEP](https://github.com/tektoncd/community/blob/master/teps/0007-conditions-beta.md#summary) and [used "guard" in the documentation](https://github.com/tektoncd/pipeline/pull/3135/files#diff-db9ac78ce08367ea2b7db8c1412049b6R322-R388)

> * We do not distinguish an _evaluation error_ and when a condition is _evaluated as condition-not-met_. In programming this is fine, because it is just "expression" that is evaluated to `true`  or  `false`. But Tekton is dealing with a _distributed system_ and things will fail.
>   E.g. it may make sense to do a `retry` when an evaluation _fails_, but not when an evaluation of a condition evaluates to _condition-not-met_.
>   _**There is still missing pieces here to correctly distinguish between an _evaluation fail_ and _condition-not-met_**_
>   Can _conditional_-containers write `true` or `false` as _termination message_ and `exit 0` on successful evaluation?

Instead of using `exit` status of `TaskRuns`, conditions beta provides `WhenExpressions` that operate on `Results` from previous `Tasks`. A `Condition` can be translated into a previous `Task` that produces a `Result` (can be `true` or `false`) that subsequent guarded `Tasks` can operate on. Demonstrated using [Conditional PipelineRun](https://github.com/tektoncd/pipeline/blob/master/examples/v1beta1/pipelineruns/conditional-pipelinerun.yaml) that uses `Conditions` vs [Guarded PipelineRun](https://github.com/tektoncd/pipeline/pull/3135/files#diff-f7386fff290e39a15d2d82f2c3b8fbcfR1-R225) that uses `WhenExpressions`. 

> * Be able to _negate_ a `Condition`. I have a use-case were I want to do X (e.g. deploy) when the `PipelineRun` was triggered on _master_ git-branch, OR do Y (e.g. create preview-environment) if the `PipelineRun` was **not** triggered on _master_ git-branch. Here I would like to use the _same_ `Condition` (eg. `conditionRef:` `<name>` in example) on both, but negate it on one. But then it is important to fail both in case of an evaluation error occur, e.g. empty-string as branch-name (that is a configuration error).
>   ```
>    conditions:                # alternatively "guards:"
>      - when:
>          conditionRef: <name>
>      - whenNot:               # or notWhen
>          conditionRef: <other-name>
>   ```

The `Operators` provided in `WhenExpressions` are `In` and `NotIn` which allows for expressing negating by expressing a similar `WhenExpression` using the opposite `Operator` (while operating on the same `Inputs` and `Values` that could could reuse `Results` from previous `Tasks`). 

> * Unclear flow. E.g. what happens after a condition? It is a bit unclear, but I have tested.
>   ```
>          (b) — (e)
>        / 
>    (a) 
>        \
>          (c) — (d)
>   ```
>   
>   
>   If "condition" is set on `(c)` - e.g `(c)` is _guarded_ by a "condition". And when _evaluated to false_, the steps in `(c)` is **not evaluated**, also Task `(d)` is **not evaluated**. (as I expected). But `(b)` and `(e)` is evaluated, and the `PipelineRun` successfully completed.

[Clarified in the documentation](https://github.com/tektoncd/pipeline/pull/3135/files#diff-db9ac78ce08367ea2b7db8c1412049b6R349-R379) that happens when a `WhenExpression` evaluates to `False`

> * Add option to continue after a Task-not-evaluated.
>   ```
>          (b) — (e)
>        / 
>    (a) 
>        \
>          (c) — (d)
>   ```
>   
>   
>   If the "condition" is evaluated to `false` on `(c)`, I may want to execute `(d)` anyway. The `runAfter:`-syntax is very clear and it is good to use _few_ elements to dictate task-ordering (since it must be easyli understood by authors and readers). We could introduce some _twist_ on `runAfter: ['c']` - to execute `(d)` even if the condition on `(c)` evaluates to `false`. (Not if condition-evaluation `fails` e.g. `err`). E.g. `runAfterUnconditionally: ['c']`.
>   Related to: #1023, [#1797 (comment)](https://github.com/tektoncd/pipeline/issues/1797#issuecomment-571077462), #2127

[Added a flexible skipping option](https://github.com/tektoncd/community/blob/master/teps/0007-conditions-beta.md#skipping-1) using `continueAfterSkip` to allow executing of ordering-dependent `Tasks` 

>   But we still need a `finally` pipelineTask, that also can have a `Condition`.

do you have some use cases for this? for now, we've disallowed `WhenExpression` in `finally` (cc @pritidesai)
