### ISSUE TITLE
latest/release.yaml does not point to the latest available release

### ISSUE THREAD

**Issue by AlanGreene** [tektoncd/pipeline#2645]
# Expected Behavior
https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml should point to the latest release (v0.12.1)

# Actual Behavior
It points to v0.12.0

**Comment by bobcatfish** [comment]
@afrittoli are you able to take on fixing this, or should the next build cop do it? I didn't notice this until the end of my day unfortunately!!

**Comment by afrittoli** [comment]
@bobcatfish Checking - somehow I missed it - even with the ping :'(

**Comment by afrittoli** [comment]
Uhm, I think I made a mistake when doing the release - I ran it with the backporting option, which means the latest is not overwritten. It should be ok to fix it manually.

**Comment by afrittoli** [comment]
ok, it's should be fixed now. Feel free to re-open @AlanGreene  if you encounter further issues, and thanks for reporting this!

**Comment by AlanGreene** [comment]
All good now, thanks! 😸
