### ISSUE TITLE
Handle TaskRuns deletion in the PipelineRun controller

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/pipeline#2647]
# Expected Behavior
If a TaskRun generated by a PipelineRun is deleted while the PipelineRun is running, the PipelineRun should fail quickly, as the controller has not way to know a coherent status anymore.

# Actual Behavior
If a TaskRun generated by a PipelineRun is deleted while the PipelineRun is running, the controller does not get any update from that TaskRun anymore, so eventually the PipelineRun will fail.

# Steps to Reproduce the Problem

1. This is my impression of the behaviour by reading the controller code.
2. We need a unit test to cover this case, and once the current behaviour is established for sure, we should change it to match the expected behaviour.
3. 

# Additional Info

It may be not possible to cancel a pipelinerun in this state, sync cancelling the deleted taskrun fails, and the controller will keep trying to cancel unsuccessfully until timeout.
It may even be that a pipelinerun in this state does not timeout.

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- Tekton Pipeline version:
v0.12.1
  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

**Comment by bobcatfish** [comment]
> If a TaskRun generated by a PipelineRun is deleted while the PipelineRun is running, the PipelineRun should fail quickly, as the controller has not way to know a coherent status anymore.

I wonder if this is what we want, or if we would want the controller to re-create the TaskRun in this case?

**Comment by afrittoli** [comment]
I think it would be very difficult to decide what to do, which is why a proposed stopping.
It could be that the taskrun was already complete so it should not be re-run.
It could be that the taskrun was writing to a workspace and left a dirty state there.
The pipeline editor may have put guards / conditions on the execution of the taskrun, that we would need to check again.

**Comment by jlpettersson** [comment]
>It could be that the taskrun was already complete so it should not be re-run.
It could be that the taskrun was writing to a workspace and left a dirty state there.
The pipeline editor may have put guards / conditions on the execution of the taskrun, that we would need to check again.

This is indeed interesting points.

We also have a retry property. Should we recommend Tasks to be designed to be idempotent? That would address most of above points. Resilience is a cloud native property.
