### ISSUE TITLE
Is there a plan to provide a standard way of log collecting for TaskRun and PipelineRun

### ISSUE THREAD

**Issue by mmpei** [tektoncd/pipeline#2648]
# Expected Behavior
a standard way of log collecting intergrated with tekton. 
such as a inline log collector base on object storage.
# Actual Behavior
pod log searching or log collecting base on ELK

**Comment by bobcatfish** [comment]
Hey @mmpei ! We did explore this a bit (https://github.com/tektoncd/pipeline/issues/1155) but ultimately decided we were better off letting folks use whatever kubernetes log collecting they wanted instead - there's a bit more info at https://github.com/tektoncd/pipeline/blob/master/docs/logs.md. That being said we do have a tool we've used for our own dogfooding to collect logs: https://github.com/tektoncd/plumbing/tree/master/pipelinerun-logs and we've been making some progress on https://github.com/tektoncd/pipeline/issues/454 which is all about having a "results store" which goes beyond logs

**Comment by mmpei** [comment]
huge info, thx.
