### ISSUE TITLE
Pipeline resource output

### ISSUE THREAD

**Issue by 2020testuser** [tektoncd/pipeline#2649]
# Expected Behavior
I'm using image pipeline resource. The pipelineresource image url  was set to the gradle build output image after successful build in the task. Expecting the new image in the docker repository url (which is set in the  pipelineresource image url ).
# Actual Behavior
No errors in the pipelinerun log. However, don't see the new image in the docker repository.
# Steps to Reproduce the Problem

1. Set the resource in pipelinerun as shown below.

`resources:`
    - name: docker-image
      resourceSpec:
          type: image
          params:
            - name: url
              value: <my docker repo>/<my project repo>:test `
    
2. Use resource as shown below  in the pipeline.
`  resources:
      outputs:
        - name: docker-image
          resource: docker-image`
3. In the task script, set the built image to the resource image url.
`
script: |
          gradle  myapp:docker -x test
          docker tag myapp:latest  $(resources.outputs.docker-image.url) `
 
4 Check the pipelinerun log for any errors. No errors found.

5. Goto the docker repository and check whether the image is available.

# Additional Info

- Kubernetes version: 1.17
- Tekton Pipeline version: .11

Thanks!

**Comment by bobcatfish** [comment]
Hey @2020testuser ! Unfortunately the image resource doesn't really do very much (https://github.com/tektoncd/pipeline/blob/master/docs/resources.md#image-resource) - i.e. it doesn't push the image 

This is one reason we're not very happy with the current state of the image pipelineresource, you can see a bit more about it in https://github.com/tektoncd/pipeline/blob/master/docs/migrating-v1alpha1-to-v1beta1.md#replacing-an-image-resource and in this WIP doc https://github.com/tektoncd/pipeline/blob/16eea0e6dd6cb0920ac658bb493aa72fa8aa8e79/docs/migrating-v1alpha1-to-v1beta1.md#replacing-pipelineresources-with-tasks

**Comment by 2020testuser** [comment]
@bobcatfish - Thanks for the links! 

Could you please confirm on the below?

So currently we don't have an option to push the image to docker repository from a Tekton task if we use non-kaniko image (Ex: maven image, gradle image etc.) for build? I don't want to use docker push  command to push the image from my task script.

If yes for above, this would be a tekton limitation if I use non-kaniko (or non-buildah or other similar build components) for build. Is than any workaround or solution?

Thanks!

**Comment by bobcatfish** [comment]
hey @2020testuser ! You can use anything that can push to a docker repo from a Tekton Task - kaniko is one option but you can use other tools as well.

Tekton doesn't provide anything to do the pushing for you.

**Comment by 2020testuser** [comment]
@bobcatfish -  Thanks for the confirmation!
I'm using docker login in the task script b4 the docker push command. So, forced to pass the docker credentials in the script. If I have a service account with my docker credentials/secret and include in my task , the docker push command doesn't work. I'm forced to explicitly login using the docker login command b4 the docker push command.

 Let me know if you have any options to resolve the above . I need to look for some other way to build and push the image then.

Thanks!
