### ISSUE TITLE
PipelineRun reports unknown field "taskRunSpecs"

### ISSUE THREAD

**Issue by jpds** [tektoncd/pipeline#2657]
# Expected Behavior

I should be able to specify a `taskRunSpecs` for a `PipelineRun`. This is referenced in:

- https://github.com/tektoncd/pipeline/blob/master/docs/pipelineruns.md#specifying-task-run-specs

# Actual Behavior

Unknown field is returned.

# Steps to Reproduce the Problem

1. Take the example at https://github.com/tektoncd/pipeline/blob/master/examples/v1beta1/pipelineruns/pipelinerun-taskrunspecs.yaml
2. Apply, and receive error: `admission webhook "webhook.pipeline.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "taskRunSpecs"`

# Additional Info

- Kubernetes version:

GKE 1.16.8-gke.15

- Tekton Pipeline version:

v0.12.1

**Comment by danielhelfand** [comment]
I don't believe taskRunSpecs are part of an official release yet. The docs are associated with what is in master, but there are options for using what is in master to try out the feature.

**Comment by jpds** [comment]
Wow, I do appear to have come across a feature I need which indeed isn't in the new 0.12.1 :grin:

**Comment by bobcatfish** [comment]
Note you can also find versioned docs at https://github.com/tektoncd/pipeline#read-the-docs (hopefully soon at tekton.dev as well 🤞 ) You can also install from nightly releases if you want the latest and greatest: https://github.com/tektoncd/pipeline/blob/master/docs/install.md#before-you-begin
