### ISSUE TITLE
Avoid unecessary work within reconciliation loop - LimitRanges

### ISSUE THREAD

**Issue by jlpettersson** [tektoncd/pipeline#2666]
# Expected Behavior

In a larger organization with e.g. 400+ apps using Tekton CI/CD pipelines, and where developers usually do `git-push` to trigger new `PipelineRuns` with typically 10-20 tasks, several times a day, many `TaskRuns` is created.

I expect that Tekton is an efficient CI/CD platform and also is _sound_ with the requests to the Kubernetes control plane, especially _etcd_ that is a critical component in any Kubernetes cluster.

# Actual Behavior

A typical git-to-deploy `Pipeline` will probably consist of 10-20 `TaskRun` pods to be created.
**For every** `TaskRun` to be created we do (at least) these requests to the ApiServer — this is _synchronous_ request-response pairs that also _delay_ `TaskRun` creation:

1. Lookup things for artifact-store — this is mostly related to `PipelineResources` and pre-workspaces - we may rethink this.
2. Lookup serviceAccounts for `creds-init` — this may be redesigned with https://github.com/tektoncd/pipeline/issues/2343
3. Lookup feature configMap — this will be improved by https://github.com/tektoncd/pipeline/pull/2637 (could be more static as well?)
4. Lookup [LimitRanges](https://kubernetes.io/docs/concepts/policy/limit-range/) that is configured for the namespace.

Looking up LimitRanges is a bit strange responsibility for the `TaskRun`-controller within the reconciliation loop. There is a few use-cases:

1. The Namespace does not have an LimitRange specified (I assume this is the most common case)

   In this case a `LIST` operation against ApiServer and `etcd` is **not** needed for every `TaskRun`
2. The Namespace does have a [LimitRange](https://kubernetes.io/docs/concepts/policy/limit-range/) specified, and it contains Default values. (I assume this to be the second most common case)

    >A LimitRange provides constraints that can:
    >* Set default request/limit for compute resources in a namespace and automatically inject them to Containers at runtime.

    This is fine, and this should work without that Tekton need to do any extra job. We even have an [example of this](https://github.com/tektoncd/pipeline/blob/master/examples/v1beta1/taskruns/no-ci/limitrange.yaml).

   In this case a `LIST` operation against ApiServer and `etcd` is **not** needed for every `TaskRun`

3. The Namespace does have a [LimitRange](https://kubernetes.io/docs/concepts/policy/limit-range/) specified, but without Default values. (I assume this to be the rarest case).

   This is the only time our extra request for every TaskRun provide any value. But is this the responsibility of the TaskRun-controller within the reconciliation loop?

   In an environment where operations or platform-team has configured it like this, it probably means that they want the users to specify _resource limit_ explicitly for their workload.

   * A step may declare custom resource limits.
   * A `Task` may declare a [Step template](https://github.com/tektoncd/pipeline/blob/master/docs/tasks.md#specifying-a-step-template) to be used for its steps.
   * There could be a global default configuration for default `Step Template` with this, as pointed out in https://github.com/tektoncd/pipeline/issues/2600
   * There could also be a per `PipelineRun` default `Step template` - specified in a `TriggerTemplate`.

All above is good alternatives to lookup a namespace configuration for every `TaskRun` creation (a very common operation when using Tekton).

**Comment by afrittoli** [comment]
>     1. Lookup things for artifact-store — this is mostly related to `PipelineResources` and pre-workspaces - we may rethink this.
> 
This is addressed by https://github.com/tektoncd/pipeline/pull/2947
