### ISSUE TITLE
Provide lightweight RBAC set for Deployment Pipeline

### ISSUE THREAD

**Issue by jlpettersson** [tektoncd/pipeline#2668]
# Expected Behavior

That Tekton is easy to use in a secure way practicing _least privilege_ principles.

Tekton currently does not have a lightweiht RBAC-rule set for e.g. a Deployment Pipeline, that. e.g. does not need access to e.g. `Secrets`, `PersistentVolumeClaim`. A typical Deployment Pipeline will not have use for workspace and should do most operations using a _ServiceAccount_.

It would be good if Tekton could provide an easy way to just install for Deployment Pipeline, e.g. when CI-build-pipeline is done within another cluster.

A Deployment Pipeline could consist of Deploy -> Canary Analyze -> Decision or also deploy A and B version in case of A/B testing.

# Actual Behavior

Tekton is easy to install with full capabilities.

/kind feature

**Comment by bobcatfish** [comment]
Discussed in pipeline owners meeting, feels like one good option here could be some documentation with some recommendations at the least

/remove-lifecycle rotten
