### ISSUE TITLE
Emit an Event when a set affinity property is overwritten

### ISSUE THREAD

**Issue by jlpettersson** [tektoncd/pipeline#2678]
# Expected Behavior

That it is easy to detect misconfiguration or conflicting configurations

# Actual Behavior

The Affinity Assistant will set `affinity` on TaskRun pods, but not check or warning is done if the `affinity` filed already had a value set. An `Event` should be generated if this happens. Requested in https://github.com/tektoncd/pipeline/pull/2630#issuecomment-630320385

/kind feature
/kind cleanup

**Comment by vdemeester** [comment]
debug1: Trying private key: /tekton/home/.ssh/id_repo-infra-tool-nexus
debug3: sign_and_send_pubkey: RSA SHA256:gXoWndTSU9YlzNAQJ0ILY3uQCVcQtrgGiACFFqwFn6E
debug3: sign_and_send_pubkey: signing using rsa-sha2-512
debug3: send packet: type 50
debug2: we sent a publickey packet, wait for reply
debug3: receive packet: type 52
debug1: Authentication succeeded (publickey).
Authenticated to git.evry.cloud ([62.148.40.201]:22).
