### ISSUE TITLE
Pipelinerun should be able to read value from a configMap

### ISSUE THREAD

**Issue by dewan-ahmed** [tektoncd/pipeline#2688]
# Pipelinerun should be able to read value from a configMap

## Currently, you can specify only `params` but I'm looking to specify `env` for my use case. I have three tasks in pipeline. The final task publishes app externally after appending a specific string to the app-name. This string is coming from a configMap. I am hoping to pass this value to pipelinerun. 

# Steps to Reproduce the Problem

1. Try to reference a configMap key from a pipelinerun

# Additional Info

Client Version: v4.2.7
Server Version: 4.3.18
Kubernetes Version: v1.16.2

- Kubernetes version:

```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.2", GitCommit:"e6f1cd7", GitTreeState:"clean", BuildDate:"2020-04-20T06:30:19Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
 ```

- Tekton Pipeline version:

 Client version: 0.8.0

OpenShift Pipelines Version: openshift-pipelines-operator.v1.0.1

https://tektoncd.slack.com/archives/CJ62C1555/p1590440461457000?thread_ts=1590170177.448200&cid=CJ62C1555

**Comment by dibyom** [comment]
/kind feature

One workaround for now might be to pass in the configMap name and key name as params, and then have a step within the task that fetches the value from the configMap

**Comment by AlanGreene** [comment]
If you only need access to the configMap value from one or a small number of steps in that task you could load the value using env + configMapKeyRef in the step definition: https://github.com/tektoncd/pipeline/blob/9fd0908070ccf8750a99a03fa444ce00e3be6090/examples/v1beta1/taskruns/configmap.yaml#L14-L25
