### ISSUE TITLE
Does pipelinerun support multiple pipelines？

### ISSUE THREAD

**Issue by zzguang520** [tektoncd/pipeline#2699]
# Expected Behavior
pipelinerun can support multiple pipelines
# Actual Behavior
unknown
# Steps to Reproduce the Problem
unknown
1.
2.
3.

# Additional Info
If can，pls share the sample template
- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

**Comment by zzguang520** [comment]
If can，pls share the sample template，thanks

**Comment by dibyom** [comment]
No, at this time we support only a single pipeline per pipeline run. You may be interested in the #2134 which allows one pipeline to nest other pipelines

**Comment by AlanGreene** [comment]
Depending on your requirements you may find [Tekton Triggers](https://github.com/tektoncd/triggers) useful. You could define a TriggerTemplate containing multiple PipelineRuns, one for each Pipeline you would like to run.

Can you share more details about what you're trying to do?

**Comment by sbwsg** [comment]
Closing since this is over a month old now and I think the original question has been largely answered.  Feel free to reopen if you decide you'd like to follow up with further info.

**Comment by tnimni** [comment]
> Depending on your requirements you may find [Tekton Triggers](https://github.com/tektoncd/triggers) useful. You could define a TriggerTemplate containing multiple PipelineRuns, one for each Pipeline you would like to run.
> 
> Can you share more details about what you're trying to do?

Hi,

I defined a TriggerTemplate and used the following inside of it
resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
        ...
   - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun2-$(uid)
        ...

however, only a single pipeline was created

any idea why 2 pipelines weren't created?
