### ISSUE TITLE
task results reassertion

### ISSUE THREAD

**Issue by pritidesai** [tektoncd/pipeline#2701]
* `TaskResultsNotProduced`: TaskRun for a task should result in failure if task results are not populated. Tasks are declared successful today even before initializing task results from container status. `updateTaskRunResourceResult` is executed when a `taskRun` is declared successful. TaskRun is declared complete and successful [here](https://github.com/tektoncd/pipeline/blob/203ff99f1431c2f823221b241f317de49dbd4e91/pkg/pod/status.go#L153), we should add a check on task results even before updating `taskRun.status`.

* `InvalidTaskResultReference`:  Task execution order is set such that the task producing a result is executed before the task referencing that result. In case of a failure of a referenced task, pipeline exits without executing the rest of the pipeline tasks. But when a referenced task succeeds and does not instantiate the result, the task referencing that result is not executed and pipeline results in failure. Pipeline exits with `PipelineValidationFailed` since the result did not exist. Replace `PipelineValidationFailed` with something more specific `InvalidTaskResultReference`.

An example of such task and pipeline execution [here](https://gist.github.com/pritidesai/931936e2bd61c50df29fdc767442b494).

_**I think, we might not even get to this kind of error if `TaskResultsNotProduced` is implemented.**_

* `MissingTaskResultReference`: A task might be set to produce task results but these results are not referenced in any of the pipeline tasks. This scenario is ignored today, does not impact task execution order and does not produce any failure. Pipeline should result in failure if task results are not referenced at all.

Please feel free to suggest better naming if these does not make sense.

**Comment by bobcatfish** [comment]
Hey @pritidesai ! I think I'm missing a bit of context for this one: is this about changing the error "reason" fields in Status conditions?

**Comment by pritidesai** [comment]
yes changing the reason field from generic `PipelineValidationFailed` to specific `InvalidTaskResultReference` and also changing the existing behavior where `taskRun` is marked successful without checking if task results were initialized/populated or not ... change TaskRun reconciler such that, check on task results are done before changing taskRun status to sucess.

**Comment by bobcatfish** [comment]
@pritidesai looking at this more closely would you say this is a duplicate of #3497? It sounds like this issue is about trying to add more validation around expectations for Task results?

**Comment by pritidesai** [comment]
This issue is about documenting and implementing the expected behavior in cases such as `TaskResultsNotProduced` i.e.  a task must fail if the result is not populated (same as issue #3497),  and `InvalidTaskResultReference` which was implemented with PR #2538.

`MissingTaskResultReference` is something not discussed much but does not warrant any changes in pipeline. A task is allowed to produce a number of results but pipeline does not enforce all of them has to be utilized by other tasks.

Yup, we can close this as a duplicate of #3497
