### ISSUE TITLE
Remove tianon/true as the "nop" image

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/pipeline#2714]
# Expected Behavior

The "nop" image that Pipelines uses to stop Sidecars should be available.

Edit: Generally, my hunch here is that we shouldn't be depending on external images for core Pipelines functionality at all but I'm open to dialog on that if it's simply not possible.

# Actual Behavior

It appears that the SHA for tianon/true, our current "nop" image, has changed in Docker Hub and results in errors like this in TaskRun Pod logs:

```
  Normal   Pulling    2s    kubelet, gke-sidecars-default-pool-2579a152-cb5d  Pulling image "tianon/true@sha256:183cb5fd54142948ad88cc986a217465cfe8786cfdd89b1ed1fc49825da413a7"
  Warning  Failed     2s    kubelet, gke-sidecars-default-pool-2579a152-cb5d  Failed to pull image "tianon/true@sha256:183cb5fd54142948ad88cc986a217465cfe8786cfdd89b1ed1fc49825da413a7": rpc error: code = Unknown desc = Error response from daemon: received unexpected HTTP status: 500 Internal Server Error
  Warning  Failed     2s    kubelet, gke-sidecars-default-pool-2579a152-cb5d  Error: ErrImagePull
```

# Steps to Reproduce the Problem

1. Create a fresh cluster to make sure that the tianon/true image isn't cached on a Node
2. Deploy Tekton Pipelines
3. `kubectl create -f ./examples/v1beta1/taskruns/sidecar-interp.yaml`

Notice that the Pod underlying the TaskRun will fail with a `ErrImagePull`

# Additional Info

- Kubernetes version:

1.16.8

- Tekton Pipeline version:

`master` branch, but also affects 0.12 and 0.11 releases.

**Comment by vincent-pli** [comment]
Fixed by #2713 should be closed

**Comment by vdemeester** [comment]
I guess so too but, @sbwsg if not using `tianon/true`, which image would we use ? :thinking:

**Comment by sbwsg** [comment]
we could either bring back our pipeline-owned nop image, or go with a different strategy. i have been wondering what would happen on various platforms if we just replaced the image with a non-existent one, for example.
