### ISSUE TITLE
json: unknown field "subPath"

### ISSUE THREAD

**Issue by bgottfried91** [tektoncd/pipeline#2715]
# Expected Behavior
You should be able to specify a subPath field in a workspace definition of a specific Task within a pipeline.
# Actual Behavior
The v1beta1 api does not recognize the subPath field as a valid field for a workspace.
# Steps to Reproduce the Problem

1. oc apply the example pipeline from the documentation that uses two different subPaths on the same workspace (https://github.com/tektoncd/pipeline/blob/master/examples/v1beta1/pipelineruns/pipelinerun-using-different-subpaths-of-workspace.yaml#L33)
2. It should fail to apply properly, with a message like:
> Error from server (BadRequest): error when creating "pipelines_implementation/manifests/tekton/pipelines/test.yaml": admission webhook "webhook.pipeline.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "subPath"

# Additional Info

- Kubernetes version:
Openshift 4.4
  **Output of `kubectl version`:**
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO
Server https://api.shared-dev4.dev4.openshift.opentlc.com:6443
kubernetes v1.17.1

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**
v0.11.3

**Comment by sbwsg** [comment]
Hi @bgottfried91 thanks for the issue report.  Both `volumeClaimTemplate` workspace types and `subpath` support in PipelineTasks were only introduced starting in 0.12.  If you try the pipeline you linked against 0.12.1 it should work as expected.  Apologies for the confusion here, we're working to improve Tekton's story around task and pipeline versioning and we acknowledge that are currently some pretty rough edges right now.

I'm closing for now but please feel free to reopen if you think there's more to be done here.
