### ISSUE TITLE
The "STATUS" of Pod with sidecar after terminated

### ISSUE THREAD

**Issue by vincent-pli** [tektoncd/pipeline#2724]
# Expected Behavior
After `sidecar` is terminated, the associated pod's STATUS should be `Completed`
# Actual Behavior
`StartError`
# Steps to Reproduce the Problem
kubectl create -f ./examples/v1beta1/taskruns/sidecar-interp.yaml

# Additional Info
For now, we terminate `sidecar` by update original `sidecar` image to `tianon/true`, that will work but will make container of `sidecar` failed like this:
```
        containerID: containerd://cac503b51609b5708f8b1f0be62eccdb9a8e866c5064c225cd0d14e74f2b0fed
        exitCode: 128
        finishedAt: "2020-05-31T09:10:29Z"
        message: 'failed to create containerd task: OCI runtime create failed: container_linux.go:346:
          starting container process caused "exec: \"/bin/bash\": stat /bin/bash:
          no such file or directory": unknown'
        reason: StartError
        startedAt: "1970-01-01T00:00:00Z"
```
I think we cannot avoid this (correct me if I missing sth) based on current implements, since `tianon/true` has nothing, will raise similar exception whatever try to run on it.

But I think we can make it looks better by sort the `pod.containerStatuses`. as your know the `pod.containerStatuses` will sort by name of container, that's means `sidecar-` will beyond `step-`, and the `STATUS` of pod when run `kubectl get po` will finally come from the first container: `containerStatuses[0].state.terminated.reason`.

So could we change `sidecar-` to some `zzzz-sidecar-` to make it behind the `step-`.

**Comment by sbwsg** [comment]
> I think we cannot avoid this (correct me if I missing sth) based on current implements, since tianon/true has nothing, will raise similar exception whatever try to run on it.

That's correct & has been treated as acceptable til now - a TaskRun is still considered succeeded if the Step containers all succeeded.  Sidecar container error states are (mostly? completely?) ignored.

> So could we change sidecar- to some zzzz-sidecar- to make it behind the step-.

I didn't realize that the status of a Pod was dependent on the sort order of its containers - very interesting!

Bear in mind that this won't affect injected sidecars - it's still totally possible that a MutatingAdmissionWebhook adds a sidecar to a Pod with name "aaaaa" and it will be sorted before the Steps, resulting in a Pod terminating in an error state when the `tianon/true` image is swapped in to it.  So I don't think this would actually allow us to remove any logic we have ignoring the Pod's state.
