### ISSUE TITLE
Missing coverage of TaskRun label update

### ISSUE THREAD

**Issue by mattmoor** [tektoncd/pipeline#2728]
I am able to comment out the annotation/label update call in the TaskRun reconciler and the unit testing passes.  Seems like if this is important it should be covered?

/good-first-issue

**Comment by R2wenD2** [comment]
This is currently blocked because patch can't be tested with the existing test infrastructure.  @mattmoor is planning to move back to update for taskRun.

**Comment by mattmoor** [comment]
I can't remember my branch name, so I may just start debugging over.  tl;dr the patch is this:

```
func (c *Reconciler) updateLabelsAndAnnotations(tr *v1beta1.TaskRun) (*v1beta1.TaskRun, error) {
	newTr, err := c.taskRunLister.TaskRuns(tr.Namespace).Get(tr.Name)
	if err != nil {
		return nil, fmt.Errorf("error getting TaskRun %s when updating labels/annotations: %w", tr.Name, err)
	}
	if !reflect.DeepEqual(tr.ObjectMeta.Labels, newTr.ObjectMeta.Labels) || !reflect.DeepEqual(tr.ObjectMeta.Annotations, newTr.ObjectMeta.Annotations) {
		// Note that this uses Update vs. Patch because the former is significantly easier to test.
		// If we want to switch this to Patch, then we will need to teach the utilities in test/controller.go
		// to deal with Patch (setting resourceVersion, and optimistic concurrency checks).
		newTr = newTr.DeepCopy()
		newTr.Labels = tr.Labels
		newTr.Annotations = tr.Annotations
		return c.PipelineClientSet.TektonV1beta1().TaskRuns(tr.Namespace).Update(tr)
	}
	return newTr, nil
}
```

However, when I tried this there was a test failure that I couldn't explain (I think it had to deal with volume claims)

**Comment by mattmoor** [comment]
Alright, so the original change above had a tiny bug that totally screwed things up...

```go
return c.PipelineClientSet.TektonV1beta1().TaskRuns(tr.Namespace).Update(newTr)
```

We were setting up `newTr` and then using `tr`...   🤦
