### ISSUE TITLE
RunningPipelineRun metric is racy

### ISSUE THREAD

**Issue by mattmoor** [tektoncd/pipeline#2729]
I was looking at the PipelineRun controller, and noticed that there is a metric for the number of running PipelineRuns:

https://github.com/tektoncd/pipeline/blob/baf3c725c0f0e4409d935a6bee5c8f3a22695056/pkg/reconciler/pipelinerun/pipelinerun.go#L254-L261

This metric is updated when one of the reconciler's trailing updates modifies the resource (status or labels/annotations), but it bases its metric on the informer's lister cache.  Now, informers are fast, but in all likelihood the lister that is being used to drive this metric hasn't received the updated version of the resource from the API Server, so unless the informer cache's copy is being modified (a no no) then the cache won't reflect what it's clearly (given the `if updated` check) trying to capture.

Perhaps this metric could even be completely decoupled from this reconciler?  It seems like fairly separable logic that's needlessly coupled to reconciliation.  🤷

**Comment by mattmoor** [comment]
I'd probably say `/kind bug`? 😇

**Comment by vdemeester** [comment]
@mattmoor for my defense, I was on PTO, my brain is not completely wired back correctly it seems :joy_cat: 
/kind bug
/unkind feature

**Comment by mattmoor** [comment]
> unless the informer cache's copy is being modified (a no no) 

I am seeing the informer's copy being modified in both `updateStatus` and `updateLabelsAndAnnotations`.

**Comment by mattmoor** [comment]
This modifies a resource fetched from a lister (informer cache): https://github.com/tektoncd/pipeline/blob/be9ac3bf6b27f6beb3f4b7c828ef8388f9b323c3/pkg/reconciler/pipelinerun/pipelinerun.go#L916

**Comment by mattmoor** [comment]
You can watch things explode by adding a line like `pr := pr.DeepCopy()` to the top of each of these loops:
https://github.com/tektoncd/pipeline/blob/be9ac3bf6b27f6beb3f4b7c828ef8388f9b323c3/test/controller.go#L108

**Comment by mattmoor** [comment]
Alright, so https://github.com/tektoncd/pipeline/pull/2736 should address the modifications of the resources in the informer cache, but I didn't touch this code because no tests blew up (yet 🤞 ) and I feel like fixing this race needs a deeper design conversation.

Not sure how folks want to proceed, but that PR will almost certainly make this metric flakier until this issue is fixed.

**Comment by mattmoor** [comment]
One potential solution would be to replace the current logic with a simple periodic scan.  You'd lose sub-`{period}` resolution, but it avoids a full lister scan (`O(n)`) that potentially keys off of updates to any of those `O(n)` resources.

If we launch a go routine with a `for { <-time.After(period) }` in `controller.go` it can key off of the same lister.
