### ISSUE TITLE
Tekton Pipelines Integration with Istio

### ISSUE THREAD

**Issue by jpower432** [tektoncd/pipeline#2732]
# Expected Behavior
To be able to submit a Tekton CR to K8 admission controller through tekton-pipelines-webhook with Istio integrated

# Actual Behavior

The certificate on the tekton-pipelines-webhook secure backend has a no CN and only the SAN is populated with the service name. See the error below.
![Capture](https://user-images.githubusercontent.com/66313384/83522619-ee72ff00-a4ae-11ea-852c-0ca004fcd81d.PNG)

# Steps to Reproduce the Problem

1. Install Istio v1.5
2. Install Tekton-Pipelines with sidecars auto-injection enabled
3. Try to submit a test Taskrun to the controller

# Additional Info

- Kubernetes version:

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:38:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- Tekton Pipeline version: v0.11.0-rc2

- Istio Version: v1.5 - Strict mTLS enabled

**Comment by mattmoor** [comment]
cc @tcnghia

**Comment by afflom** [comment]
Since istio is providing mTLS for tekton in this instance, would it be acceptable for tekton to be deployed plain text comms between services? Is there a flag for that? @mattmoor @tcnghia

**Comment by afflom** [comment]
This is closed by https://github.com/knative/pkg/pull/1384

**Comment by vdemeester** [comment]
@afflom we still need to bump our dependency on knative/pkg :upside_down_face:

**Comment by afflom** [comment]
Understood. I have patience. Thank you.

**Comment by vdemeester** [comment]
https://github.com/tektoncd/pipeline/blob/master/go.mod#L39 we now depend on knative 0.16. This should be fixed in 0.15.x (and on master)
/close
