### ISSUE TITLE
CompletionTime is not set if Succeeded is already True

### ISSUE THREAD

**Issue by mattmoor** [tektoncd/pipeline#2741]
# Expected Behavior

CompletionTime is always updated to reflect the time the task/pipeline was observed to succeed.

# Actual Behavior

CompletionTime is only updated when something else in Status is being touched.  This is because `updateStatus` is guarded by an equivalence check, so if nothing else changes, then this doesn't get set.

# Steps to Reproduce the Problem

I saw this in a unit test where I set the condition but not CompletionTime, and was surprised it wasn't set.

# Additional Info

This is going to be blocking for a transition away from hand-rolled `updateStatus` to `// +genreconciler`.

/kind bug

**Comment by afrittoli** [comment]
Interesting. 
I suppose we never want to have the case where we set the status "True" is set on the "Succeeded" Condition, and the `CompletionTime` is not set.
Would the `+genreconciler` require that separation?

**Comment by mattmoor** [comment]
Well `updateStatus` is now generated, and doesn't do this 😅 

The way we manage this in Knative is to have higher-level functions for manipulating status conditions.  The equivalent here would be to have the function(s) that put Succeeded into a terminal state also update CompletionTime.

I haven't poked around to see how this is set throughout the reconcilers today, but would be happy to advice if someone wants to look 😇 

/good-first-issue

**Comment by mattmoor** [comment]
I may take a look at this next.  It's all over and I think it'll clean things up a bit.
