### ISSUE TITLE
Define compatibility policy for Go libs

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#2748]
# Expected Behavior

We try to minimize the impact of changes to our Go libs on other projects that are using them, for example in https://github.com/tektoncd/pipeline/pull/2717#issuecomment-637164266 when @pritidesai noted the impact of that change on the CLI.

It would make sense to have a clear policy around:
- How to make backwards incompatible changes to the libs and what expectations should be around this for users of the libs
- What is and is not part of the lib (people can currently import anything from tektoncd/pipeline except the builders in internal)

# Actual Behavior

We have our API compatibility policy outlined in https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md but it does not currently include our client libs.

# Additional Info

If we can identify which parts of the code we think it is reasonable for folks to import and use as libs, we can move the rest into [internal](https://golang.org/doc/go1.4#internalpackages) and that would make it very clear which code you can change without impacting other projects.

**Comment by pritidesai** [comment]
/remove-lifecycle stale
Defining such policy is crucial as we are approaching `v1`.

**Comment by wlynch** [comment]
/reopen

Wanted to re-raise this issue for discussion (especially as we near v1) - I think it would be useful to apply deprecation policies to client libraries.

For Go in particular, a breaking change to a minor version best case means that tools like dependabot can break and manual intervention is needed by humans to upgrade, and worst case means that tools build on top of Tekton may be incompatible with each other (i.e. if 2 separate libraries depend on different client versions, [minimal version selection](https://go.dev/ref/mod#minimal-version-selection) may force the selection of a non-compatible dependency). We can still make rapid changes to alpha APIs / clients, but for stable APIs it would be great to have more guarantees around stability.

**Comment by dibyom** [comment]
Planning to incorporate this in #5633
