### ISSUE TITLE
Link to install v0.13.0 on Github release page does not work

### ISSUE THREAD

**Issue by ckadner** [tektoncd/pipeline#2786]
**Installation one-liner**

```
kubectl apply -f https://storage.googleapis.com/tekton-releases/Pipeline/previous/v0.13.0/release.yaml
```

... fails due to the upper-case `P` in `../Pipeline/...`.

This is rather trivial to one who looks more closely at the URL but it may be annoying to some.

**Comment by vdemeester** [comment]
I'll update manually, but I thought we fixed the script doing that ?

/cc @afrittoli @bobcatfish 
/kind bug

**Comment by ckadner** [comment]
> I'll update manually

Thanks @vdemeester 

Now I can install from the copy-pasted command, but after the installation I cannot verify the cluster version using the `tkn` command line:

`tkn version`
```
Client version: 0.9.0
Pipeline version: unknown
```

`$ kubectl describe svc -n tekton-pipelines | grep release`
```
                   pipeline.tekton.dev/release=v0.13.0
                   pipeline.tekton.dev/release=v0.13.0
```

Is that a problem with `tkn`?

**Comment by bobcatfish** [comment]
Created https://github.com/tektoncd/plumbing/pull/412/files to fix the first problem - I don't know enough about the tkn issue to respond, but if the svcs have the right info, maybe @ckadner is right and that's a tkn issue? I know we had problems before with not propagating that info correctly tho.

**Comment by ckadner** [comment]
@bobcatfish -- I created an issue on the `tkn` CLI repo

**Comment by ckadner** [comment]
> Created https://github.com/tektoncd/plumbing/pull/412/files to fix the first problem 

Thanks @bobcatfish

**Comment by ckadner** [comment]
https://github.com/tektoncd/cli/issues/1015
