### ISSUE TITLE
Pipelines Tutorial question

### ISSUE THREAD

**Issue by retgits** [tektoncd/pipeline#2795]
# Steps to Reproduce the Problem

* In [the tutorial](https://github.com/tektoncd/pipeline/blob/master/docs/tutorial.md#specifying-task-inputs-and-outputs) you create a PipelineResource of type `git` which has parameters for `url` and `revision`;
* In the task, you use a git input called `docker-source` (which is referenced in the `TaskRun`, so I kinda get how it gets there)
* In the TaskDefinition there is a parameter substitution for `$(resources.inputs.docker-source.path)` which I thought meant it takes the `path` parameter from whatever ends up as the `docker-source` resource
* The PipelineResource doesn’t have a `path` parameter at all, so I'm not exactly sure where that comes from.

# Additional Info

- Kubernetes version:

v1.18

  **Output of `kubectl version`:**

  ```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-21T14:51:23Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version:

```bash
tkn version
Client version: 0.9.0
Pipeline version: unknown
```

**Comment by vincent-pli** [comment]
@retgits 
Could take a look at this part: https://github.com/tektoncd/pipeline/blob/master/docs/resources.md#using-resources

**Comment by retgits** [comment]
Ah! Okay, that makes sense. I appreciate you pointing that out. Would it be an idea to add that to the tutorial portion? That would help have all information in a single place (at least for the tutorial part).
