### ISSUE TITLE
Feature: expression support in $() 

### ISSUE THREAD

**Issue by bitsofinfo** [tektoncd/pipeline#2812]
Would be great to be able to do something like this in a Task (or anywhere `$()` variable syntax is supported)

```
$(inputs.params.payload.decodeb64().parseJSON().key1)
```

CEL is supported in triggers CEL interceptors, would be great if just globally available in all of tekton.

**Comment by bobcatfish** [comment]
@bitsofinfo could you give some examples of the kinds of things you'd like to use CEL for? Before we add CEL support fullstop we'd want to make sure it's the best solution to meet your needs.

note we are also exploring CEL and JSONPath for conditions: https://github.com/tektoncd/pipeline/issues/2127

If you need CEL mostly for expression evaluation, we've talked before about adding JSONPath support, do you know if JSONPath could meet your needs or do you need functionality provided by CEL that isn't provided by JSONPath?

**Comment by bobcatfish** [comment]
( @ImJasonH maybe another use case for the CEL custom task? :D)

**Comment by bitsofinfo** [comment]
@bobcatfish here is an example:

```
$(inputs.params.payload.decodeb64().parseJSON().key1)
```

Others? well I don't have specifics beyond mine above. But I can just imagine how much i'd use such a capability to do simple string mutations without having to echo the params into shells for further mutation, it gets awkward. Triggers uses CEL and the functions provided by it for string manipulation works for me. Would be consistent to use that, but if JSONPath provides the same + additional functionality + more functions... then use that. I really would just like more capability for expressions, it means I have to write less custom code to do things with these params and other variables.

**Comment by bobcatfish** [comment]
@jerop has been planning to make an issue about having CEL custom task support (in the context of the conditions work she has been doing), maybe it makes sense to close this one in favor of that issue once it exists?

**Comment by bitsofinfo** [comment]
if the new issue covers the feature I'm describing of making CEL expressions available anywhere in tekton where `$()` syntax is already supported sure,  otherwise please leave it open.

**Comment by bitsofinfo** [comment]
CEL, JSONPath, whichever, whatever. Being able to do expressions anywhere `$()` would still be a great addition

**Comment by bobcatfish** [comment]
Hey @bitsofinfo  - we've been working on a set of "design principles" over in the community repo - some of the principles around flexibility apply here: https://github.com/tektoncd/community/blob/master/design-principles.md#flexibility

> When a specific choice (tool, resource, language, etc) has to be made at the Task or Pipeline levels, users should be able to extend it to add their own choices.

Even in triggers when we have support for CEL we try to make sure we can support other languages and tools as well - so I don't think it's likely we'd want to add CEL support directly in the `$()` syntax (unless we revisit those design principles).

I could see _maybe_ jsonpath support? (also touched on in #3255 and #1393) But that would give you quite a bit less than CEL would. But if your use cases are mostly around indexing into maps and arrays, vs. being needing a full expression language, maybe we can pursue that instead?

We also have #3149 which would allow for CEL support via custom tasks (i.e. no extra pod needed, values provided via results).

**Comment by bitsofinfo** [comment]
I've removed CEL from the subject. The particular implementation I guess doesn't matter. But being able to do something like this, whatever the impl, would be great. 

```
$(inputs.params.payload.decodeb64().parseJSON().key1)
```

**Comment by bobcatfish** [comment]
The `decodeb64()` and `parseJSON()` bits are interesting, that'd definitely push more toward an expression language, I'm guessing jsonpath doesn't have support for anything like that :(

I'm not sure how we'd be able to a provide functionality like that while:
a) remaining agnostic and letting ppl use the lang of their choice
b) keeping Tasks and Pipelines conformant (e.g. can use a Task in the catalog on any Tekton based system)

The only way I could imagine that working is maybe if you could provide something to your pipelines controller, like an interceptor, that knows how to parse the expression? But at that point that seems potentially more complicated than using a Custom Task to evaluate the expression.

**Comment by bitsofinfo** [comment]
how is the triggers project currently handling this?

**Comment by bobcatfish** [comment]
In triggers this is being handled with "interceptors" which run as separate services, e.g. [the CEL interceptor](https://github.com/tektoncd/triggers/blob/master/docs/eventlisteners.md#cel-interceptors) which is currently built into the eventlistener but [won't be in the future](https://github.com/tektoncd/community/blob/master/teps/0026-interceptor-plugins.md#proposal)

(I'm hoping that one day our CEL custom task controller and the triggers cel interceptor can be the same thing, i.e. run the same code)

**Comment by afrittoli** [comment]
This is still an open issue. 

I agree with @bobcatfish that we should keep API changes to a minimum, so perhaps it would help us take a step back on this a look at concrete use cases that these would solve, so that we see if there is any alternative solution.

I also feel like this is related to https://github.com/tektoncd/pipeline/issues/1393. 

If we support something like `$(inputs.params.payload.decodeb64().parseJSON().key1)`, the content of `key1` would be marshalled back into JSON? What if it's a list, would it be passed as a parameter of type list? 

One slightly related issue that I'm facing is when trying to use a task loop with a dynamically generated list of inputs.
Example: I want to run a CI job that does a container build on all images touched by a PR. A task can produce such list and store it in a result, but the custom task won't be able to read it because it expects an input parameter of type list, not string.

**Comment by bremme** [comment]
I was looking to use expressions inline to modify some parts of my task. This sound like a solution that could work for me. Just commenting to keep the issue alive.

**Comment by TristonianJones** [comment]
@bitsofinfo @bremme Is there any support you could use from the CEL team to make this happen?
