### ISSUE TITLE
Remove PipelineTask Timeout in Favor of TaskRunSpecs

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/pipeline#2827]
As of #2389, PipelineRuns now support the ability to define runtime settings of TaskRuns associated with a PipelineTask.

Prior to this, #2038 was introduced as a way to specify a timeout for a PipelineTask. Seeing as it seems the design moving forward will be to define these runtime settings all via PipelineRuns/TaskRuns, would it make sense to remove the [Timeout property](https://github.com/tektoncd/pipeline/blob/648cff3dfe1330c5035492437adee6bf1670d941/pkg/apis/pipeline/v1beta1/pipeline_types.go#L139) from PipelineTasks?

/kind question

**Comment by bobcatfish** [comment]
If we want to do this id kind of like to revisit all the PipelineTask fields and make sure we are happy with them. A while ago I tried to categorize them:


Used to instantiate the TaskRun:
* taskref
* taskspec
* resources
* workspaces
* timeout
* params

Used to decide when and how to run (i.e. workflow logic):
* conditions/when
* retries
* runafter

These are modified at runtime via PipelineTaskRunSpecs:
* ServiceaccountName
* PodTemplate

The specific fields you mentioned, one is at Pipeline authoring time, one is at PipelineRun time - if we remove timeout from PipelineTasks, this means Pipeline authors can't set it - which might be frustrating?

I think there are questions around:

* Which make sense to ONLY set at runtime?
* Which make sense to OVERRIDE at runtime but also allow at Pipeline authoring time?
