### ISSUE TITLE
Issues: Internal error occurred: failed calling webhook "webhook.pipeline.tekton.dev": Post https://tekton-pipelines-webhook.tekton-pipelines.svc:443/defaulting?timeout=30s: context deadline exceeded

### ISSUE THREAD

**Issue by zzguang520** [tektoncd/pipeline#2831]
# Expected Behavior
 kubectl apply -f https://raw.githubusercontent.com/tektoncd/catalog/master/kaniko/kaniko.yaml
create successfully
# Actual Behavior
[root@master ~]# kubectl apply -f https://raw.githubusercontent.com/tektoncd/catalog/master/kaniko/kaniko.yaml
Error from server (InternalError): error when creating "https://raw.githubusercontent.com/tektoncd/catalog/master/kaniko/kaniko.yaml": Internal error occurred: failed calling webhook "webhook.pipeline.tekton.dev": Post https://tekton-pipelines-webhook.tekton-pipelines.svc:443/defaulting?timeout=30s: context deadline exceeded

# Steps to Reproduce the Problem
1.kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml
2.kubectl apply --filename https://storage.googleapis.com/tekton-releases/triggers/latest/release.yaml
3.kubectl apply -f https://github.com/tektoncd/dashboard/releases/download/v0.7.0/tekton-dashboard-release.yaml
4.kubectl apply -f https://raw.githubusercontent.com/tektoncd/catalog/master/kaniko/kaniko.yaml

# Additional Info
kubectl get node
```
NAME STATUS ROLES AGE VERSION
master Ready master 29d v1.18.3
node1 Ready 29d v1.18.2
node2 Ready 29d v1.18.2
```
```
kubectl get all -n tekton-pipelines
NAME READY STATUS RESTARTS AGE
pod/tekton-dashboard-5dc59677c9-h8sm2 1/1 Running 0 3h45m
pod/tekton-pipelines-controller-f5945cf7b-gkzck 1/1 Running 0 17h
pod/tekton-pipelines-webhook-859cd5c766-sd4d4 1/1 Running 0 17h
pod/tekton-triggers-controller-788d5f47f4-5rn4n 1/1 Running 0 17h
pod/tekton-triggers-webhook-66dbd655d7-z75w9 1/1 Running 0 17h

NAME TYPE CLUSTER-IP EXTERNAL-IP PORT(S) AGE
service/tekton-dashboard NodePort 10.106.85.130 9097:32428/TCP 3h45m
service/tekton-pipelines-controller ClusterIP 10.96.93.96 9090/TCP 17h
service/tekton-pipelines-webhook ClusterIP 10.97.83.226 9090/TCP,8008/TCP,443/TCP 17h
service/tekton-triggers-controller ClusterIP 10.100.194.28 9090/TCP 17h
service/tekton-triggers-webhook ClusterIP 10.100.206.64 443/TCP 17h

NAME READY UP-TO-DATE AVAILABLE AGE
deployment.apps/tekton-dashboard 1/1 1 1 3h45m
deployment.apps/tekton-pipelines-controller 1/1 1 1 17h
deployment.apps/tekton-pipelines-webhook 1/1 1 1 17h
deployment.apps/tekton-triggers-controller 1/1 1 1 17h
deployment.apps/tekton-triggers-webhook 1/1 1 1 17h

NAME DESIRED CURRENT READY AGE
replicaset.apps/tekton-dashboard-5dc59677c9 1 1 1 3h45m
replicaset.apps/tekton-pipelines-controller-f5945cf7b 1 1 1 17h
replicaset.apps/tekton-pipelines-webhook-859cd5c766 1 1 1 17h
replicaset.apps/tekton-triggers-controller-788d5f47f4 1 1 1 17h
replicaset.apps/tekton-triggers-webhook-66dbd655d7 1 1 1 17h
```

**Comment by vdemeester** [comment]
@zzguang520 can you share more detail on the kubernetes environment you deploy on ? It seems there is an issue with the internal network (and/or internal name resolution).

**Comment by zzguang520** [comment]
@vdemeester, I used flannel for the clustered network, do you have a more detailed view of the network Settings?

[root@master ~]# kubectl get pod -n kube-system
NAME                                               READY   STATUS    RESTARTS   AGE
coredns-66bff467f8-6nk6r                           1/1     Running   7          29d
coredns-66bff467f8-zn25r                           1/1     Running   7          29d
etcd-master.test.com                               1/1     Running   8          29d
kube-apiserver-master.test.com                     1/1     Running   11         29d
kube-controller-manager-master.test.com            1/1     Running   8          29d
kube-flannel-ds-amd64-6nf5v                        1/1     Running   8          29d
kube-flannel-ds-amd64-qr26n                        1/1     Running   3          29d
kube-flannel-ds-amd64-x9668                        1/1     Running   3          29d
kube-proxy-2rc7h                                   1/1     Running   3          29d
kube-proxy-6p8rq                                   1/1     Running   3          29d
kube-proxy-qgttg                                   1/1     Running   7          29d
kube-scheduler-master.test.com                     1/1     Running   8          29d

**Comment by zzguang520** [comment]
and I have checked the NetCard in node server:
[root@node2 ~]# ifconfig
cni0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet 10.244.2.1  netmask 255.255.255.0  broadcast 0.0.0.0
        inet6 fe80::f0ec:25ff:fe46:53e7  prefixlen 64  scopeid 0x20<link>
        ether f2:ec:25:46:53:e7  txqueuelen 1000  (Ethernet)
        RX packets 1069708  bytes 136464466 (130.1 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1032957  bytes 155094457 (147.9 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        ether 02:42:58:14:00:7d  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eno1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.112.160.49  netmask 255.255.255.0  broadcast 9.112.160.255
        inet6 fe80::a9ce:fead:ce00:e82  prefixlen 64  scopeid 0x20<link>
        ether fc:4d:d4:38:77:da  txqueuelen 1000  (Ethernet)
        RX packets 3090508  bytes 1949405077 (1.8 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2857204  bytes 946494049 (902.6 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 20  memory 0xf7f00000-f7f20000

flannel.1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet 10.244.2.0  netmask 255.255.255.255  broadcast 0.0.0.0
        inet6 fe80::80f7:90ff:fea8:f70e  prefixlen 64  scopeid 0x20<link>
        ether 82:f7:90:a8:f7:0e  txqueuelen 0  (Ethernet)
        RX packets 847555  bytes 117454942 (112.0 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 842968  bytes 117208929 (111.7 MiB)
        TX errors 0  dropped 60 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 6310  bytes 434494 (424.3 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 6310  bytes 434494 (424.3 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

veth06640f9e: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet6 fe80::642b:8aff:fe5c:1535  prefixlen 64  scopeid 0x20<link>
        ether 66:2b:8a:5c:15:35  txqueuelen 0  (Ethernet)
        RX packets 1  bytes 42 (42.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 53  bytes 2706 (2.6 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

veth5c3c75af: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet6 fe80::845b:63ff:feb8:4612  prefixlen 64  scopeid 0x20<link>
        ether 86:5b:63:b8:46:12  txqueuelen 0  (Ethernet)
        RX packets 706796  bytes 102250520 (97.5 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 743888  bytes 110349094 (105.2 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

vethb605ad57: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet6 fe80::4073:f0ff:fef3:7a2f  prefixlen 64  scopeid 0x20<link>
        ether 42:73:f0:f3:7a:2f  txqueuelen 0  (Ethernet)
        RX packets 6777  bytes 669438 (653.7 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 6058  bytes 818480 (799.2 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

vethc91bb1cd: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet6 fe80::4c8e:3bff:fec0:b40b  prefixlen 64  scopeid 0x20<link>
        ether 4e:8e:3b:c0:b4:0b  txqueuelen 0  (Ethernet)
        RX packets 637262  bytes 96515493 (92.0 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 596795  bytes 88463666 (84.3 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

vethf4312ee9: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet6 fe80::4094:b0ff:fec2:5fb4  prefixlen 64  scopeid 0x20<link>
        ether 42:94:b0:c2:5f:b4  txqueuelen 0  (Ethernet)
        RX packets 7474  bytes 621064 (606.5 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 6866  bytes 1557336 (1.4 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

vethfa6aa2aa: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet6 fe80::34fe:f1ff:fea7:72d5  prefixlen 64  scopeid 0x20<link>
        ether 36:fe:f1:a7:72:d5  txqueuelen 0  (Ethernet)
        RX packets 7671  bytes 717157 (700.3 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 6363  bytes 686737 (670.6 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by zzguang520** [comment]
BTW, I deployed Flannel in the following way:
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

**Comment by zzguang520** [comment]
@vdemeester Is there any other you would like me to provide?

**Comment by fishingfly** [comment]
I also encountered the same problem。@zzguang520

**Comment by sbwsg** [comment]
See https://github.com/tektoncd/pipeline/issues/2877#issuecomment-654863304 for one suggested fix:

> edit `/etc/kubernetes/manifests/kube-apiserver.yaml` fie in master, add this argument:
> ```
> --enable-aggregator-routing=true
> ```
> it works for me.

Please let us know if this helps.

**Comment by Mage-Sky** [comment]
for me,
deployment.apps/tekton-pipelines-  not ready

I'm thinking about the issue: Internal error occurred: failed calling webhook. Wrong cert-manager hook ID. #2419

'Issues like this are ultimately caused by a mismatch between the webhook's service name configured on the CRD resources (which are not templated as part of the Helm chart, and thus are not updated automatically if the release name is set to something other than cert-manager or if the namespace is also not cert-manager).'

**Comment by jotacamou** [comment]
I'm having a similar issue with a fresh install of the `latest` (`v0.14.0`) release on a fresh GKE cluster, only in my case trying to create a `Task`:

`$ k apply -f hello-world-task.yaml
Error from server (InternalError): error when creating "hello-world-task.yaml": Internal error occurred: failed calling webhook "webhook.pipeline.tekton.dev": Post https://tekton-pipelines-webhook.tekton-pipelines.svc:443/defaulting?timeout=30s: context deadline exceeded`

Installed Tekton Pipelines by:

`kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml`
