### ISSUE TITLE
Pipeline nightly fails on gcloud issue

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/pipeline#2838]
# Expected Behavior
Pipeline nighty works fine

# Actual Behavior

```
[publish-images : run-ko] ERROR: gcloud crashed (AttributeError): 'Credentials' object has no attribute 'private_key'
[publish-images : run-ko] ERROR: gcloud crashed (AttributeError): 'Credentials' object has no attribute 'private_key'

(...)


2020/06/19 02:19:06 error processing import paths in "/workspace/go/src/github.com/tektoncd/pipeline/config/controller.yaml": error resolving image references: error getting credentials - err: exit status 1, out: ``
Step failed
```

# Steps to Reproduce the Problem

1.  https://dashboard.dogfooding.tekton.dev/#/pipelineruns/pipeline-release-nightly-c445r 
2. JOB_NAME=nightly-cron-trigger-pipeline-nightly-release
3. kubectl create job --from=cronjob/$JOB_NAME $JOB_NAME-$(date +%s)

**Comment by afrittoli** [comment]
I run the release in docker on my laptop using the same setup but it worked fine.

**Comment by dibyom** [comment]
Some discussion slack: https://tektoncd.slack.com/archives/CPY3T4YHM/p1592831497130600

**Comment by dibyom** [comment]
Did some digging:
1. I added a `sleep 3600` to the publish-tekton-pipelines task and then `kubectl exec` `d into the `step-run-ko`pod
` k exec -ti  pipeline-release-nightly-cx6gx-publish-images-w8gdw-pod-8ctx7 -c step-run-ko bash`

2. I manually run `gcloud auth activate-service-account --keyfile=/secret/release.json` and `gcloud auth configure-docker`

3.  gcloud info diagnose was still failing:


```
 gcloud info --run-diagnostics
+ gcloud info --run-diagnostics
Network diagnostic detects and fixes local network connection issues.
Checking network connection...done.
Reachability Check passed.
Network diagnostic passed (1/1 checks passed).

Property diagnostic detects issues that may be caused by properties.
Checking hidden properties...done.
ERROR: Hidden Property Check failed.
The following hidden properties have been set:
    [auth/credential_file_override]
Properties files
    User: /tekton/home/.config/gcloud/configurations/config_default
    Installation: /usr/lib/google-cloud-sdk/properties

ERROR: Property diagnostic failed (0/1 checks passed).
```

4. `unset CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE` fixed the gcloud diagnostic

5. Manual ko run seems to succeed. Killed and retrying the job.
