### ISSUE TITLE
TestTaskRunPipelineRunCancel is flakely

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#2840]
# Expected Behavior

TestTaskRunPipelineRunCancel should only fail due to legit bugs (or if there is some kind of transient test infra issue we can't avoid)

# Actual Behavior

The test failed recently on an unrelated PR and passed on a re-run: https://github.com/tektoncd/pipeline/pull/2782 - https://tekton-releases.appspot.com/build/tekton-prow/pr-logs/pull/tektoncd_pipeline/2782/pull-tekton-pipeline-integration-tests/1273990227291017216/

The error is:

```
  TestTaskRunPipelineRunCancel/No_retries: cancel_test.go:123: Failed to cancel PipelineRun `pear`: Operation cannot be fulfilled on pipelineruns.tekton.dev "pear": the object has been modified; please apply your changes to the latest version and try again
```

**Comment by jerop** [comment]
Saw this test flake again in https://tekton-releases.appspot.com/build/tekton-prow/pr-logs/pull/tektoncd_pipeline/4502/pull-tekton-pipeline-alpha-integration-tests/1491815954336714752/#testv1alpha1-testtaskrunpipelineruncancel
