### ISSUE TITLE
Tekton metrics are reporting wrong values

### ISSUE THREAD

**Issue by RafaeLeal** [tektoncd/pipeline#2844]
# Expected Behavior
Tekton metrics coherent with data gather with kubectl

# Actual Behavior
I have two examples, for the `tekton_pipelinerun_count` metric, it's currently reporting 22 failed and 58 success, but the cluster only have 20 PipelineRuns
![image](https://user-images.githubusercontent.com/9096450/85314522-09260b80-b490-11ea-825c-9e364eb301da.png)
```
$ kubectl get pipelinerun --all-namespaces -o json | jq '.items | length'
20
```
The second example, `tekton_pipelinerun_duration_seconds_sum` metric seems to increase indefinitely. I expected to raise until the pipelinerun is completed, than stabilize in the same value as the duration showed with `tkn pr describe <pipelinerun_name>`
![image](https://user-images.githubusercontent.com/9096450/85315102-d0d2fd00-b490-11ea-9161-aa61083169c7.png)

I also noticed that
1. It doesn’t raise at the same rate.
2. Always raises a multiple of the actual duration of the pipeline.

I suspect that every time the controller reconciles it’s adding the duration of the pipeline.

# Steps to Reproduce the Problem

1. Enable tekton metrics
2. Make Prometheus scrape tekton
3. Run some pipelineruns

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**
  ```
  $ kubectl version
  Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-26T06:17:09Z", GoVersion:"go1.14", Compiler:"gc",Platform:"darwin/amd64"}
  Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
  ```
- Tekton Pipeline version: v0.13.2

  **Output of `tkn version`**
  ```
  $ tkn version
  Client version: 0.8.0
  Pipeline version: unknown
  ```
  **Output of `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**
  ```
  $ kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'
  v0.13.2
  ```

**Comment by vincent-pli** [comment]
The `tekton_pipelinerun_count` is incorrect, that's caused by reconcile enter this block more than once:
https://github.com/tektoncd/pipeline/blob/4fb10781528724d329120d9246da80fa39cb8641/pkg/reconciler/pipelinerun/pipelinerun.go#L149

**Comment by RafaeLeal** [comment]
Do you think that could be the case for the duration metrics aswell?

**Comment by vincent-pli** [comment]
@RafaeLeal 
I think so, you could apply my fix and take a try.

**Comment by pritidesai** [comment]
@vincent-pli @RafaeLeal we have similar issue reported for `tekton_taskrun_count`, see #3029

**Comment by pritidesai** [comment]
/remove-lifecycle rotten
@RafaeLeal you still experiencing this issue?

**Comment by ibexmonj** [comment]
hey folks, I am curious if what i reported here #3739 about some of the pipeline metrics is relevant to this discussion.
