### ISSUE TITLE
refactor pipelineRunState and pipelinerunresolution.go

### ISSUE THREAD

**Issue by pritidesai** [tektoncd/pipeline#2852]
With the `finally` implementation PR #2661, we have been identifying various areas where the code can be simplified (based on changes being proposed in PR #2821). This involves mainly two areas:

1) Get the execution queue in the Reconciler so that tasks can be scheduled for execution and `taskRuns` can be created.
2) Simplify `GetPipelineConditionStatus` so that the tasks execution status is not calculated from scratch on every call.

In this issue, I am maintaining a list of changes requested in PR #2661. Its very hard for authors (and reviewers) to implement new feature along with refactor/simplify existing code in single PR: 
  
* Combine `isFinalTasksDone`, `isDAGTasksStopped` and `isDAGTasksDone` into one function, [checkTasksDone](https://github.com/tektoncd/pipeline/pull/2661#discussion_r444537356). 
* Add a function to check if a task is DAG or final task i.e. `state.isPipelineTaskinDag` as attribute to `pipelineRunState`  and/or `task.InDag()` as attribute to `ResolvedPipelineRunTask`. 
* Drop the named return value from `pipelineState.IsDone`, see [comment](https://github.com/tektoncd/pipeline/pull/2661#discussion_r445010798).

**Comment by afrittoli** [comment]
> With the `finally` implementation PR #2661, we have been identifying various areas where the code can be simplified (based on changes being proposed in PR #2821). This involves mainly two areas:
> 
>     1. Get the execution queue in the Reconciler so that tasks can be scheduled for execution and `taskRuns` can be created.
> 
>     2. Simplify `GetPipelineConditionStatus` so that the tasks execution status is not calculated from scratch on every call.

`GetPipelineConditionStatus` is only executed once per reconcile cycle, and the `pipelineState` cannot be persisted across reconcile cycles, however we could build and store the state for each task in `pipelineState` when the state is initially build, and that would simplify the implementation of `GetPipelineConditionStatus`, or at least reduce it's execution time.

> 
> 
> In this issue, I am maintaining a list of changes requested in PR #2661. Its very hard for authors (and reviewers) to implement new feature along with refactor/simplify existing code in single PR:
> 
>     * Combine `isFinalTasksDone`, `isDAGTasksStopped` and `isDAGTasksDone` into one function, [checkTasksDone](https://github.com/tektoncd/pipeline/pull/2661#discussion_r444537356).
> 
>     * Add a function to check if a task is DAG or final task i.e. `state.isPipelineTaskinDag` as attribute to `pipelineRunState`  and/or `task.InDag()` as attribute to `ResolvedPipelineRunTask`.

**Comment by afrittoli** [comment]
> With the `finally` implementation PR #2661, we have been identifying various areas where the code can be simplified (based on changes being proposed in PR #2821). This involves mainly two areas:
> 
>     1. Get the execution queue in the Reconciler so that tasks can be scheduled for execution and `taskRuns` can be created.
> 
>     2. Simplify `GetPipelineConditionStatus` so that the tasks execution status is not calculated from scratch on every call.
> 
> 
> In this issue, I am maintaining a list of changes requested in PR #2661. Its very hard for authors (and reviewers) to implement new feature along with refactor/simplify existing code in single PR:
> 
>     * Combine `isFinalTasksDone`, `isDAGTasksStopped` and `isDAGTasksDone` into one function, [checkTasksDone](https://github.com/tektoncd/pipeline/pull/2661#discussion_r444537356).

In #2821 `isFinalTasksDone` and isDAGTasksDone` will lose the dag parameter and `isDAGTasksStopped` will go away, so this will already be solved there.

> 
>     * Add a function to check if a task is DAG or final task i.e. `state.isPipelineTaskinDag` as attribute to `pipelineRunState`  and/or `task.InDag()` as attribute to `ResolvedPipelineRunTask`.

**Comment by pritidesai** [comment]
Added dropping named return value in the list 🆙 from discussion:

https://github.com/tektoncd/pipeline/pull/2661#discussion_r445010798

**Comment by pritidesai** [comment]
Deleted named return value in PR #2870 
Refactored and deleted `isDAGTasksStopped` in PR #2869
