### ISSUE TITLE
Webhook metrics can have enormous cardinality

### ISSUE THREAD

**Issue by tragiclifestories** [tektoncd/pipeline#2872]
The metrics exported by the tekton-pipelines-webhook service have a label for `resource_name`. This interacts poorly with the `generateName` part of the k8s metadata API, since you will get a new time series for every interaction. This will cause [well known problems](https://www.robustperception.io/cardinality-is-key) with Prometheus, such as drastically degraded query performance and increased storage needs. 

# Expected Behavior

A new time series should not be generated for every ephemeral Tekton resource created, updated etc. 

# Actual Behavior

A new time series is generated for every ephemeral Tekton resource created, updated etc.

# Steps to Reproduce the Problem

1. Enable prometheus metrics
2. Create many Tekton taskruns (or whatever) with `spec.metadata.generateName` set.
3. Observe the mutliplication of time series on the metrics endpoint.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-18T02:59:13Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
  Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-gke.15", GitCommit:"9cabee15e0922c3b36724de4866a98f6c2da5e6a", GitTreeState:"clean", BuildDate:"2020-05-01T21:47:04Z", GoVersion:"go1.13.8b4", Compiler:"gc", Platform:"linux/amd64"}

  ```

- Tekton Pipeline version:

  0.12.0

**Comment by ImJasonH** [comment]
@mattmoor AIUI webhook metrics are defined for us by knative/pkg infra. Is this something Knative has hit as well? Or is Tekton different due to its recommendation to use `generateName`?

**Comment by mattmoor** [comment]
It certainly exacerbates it, but I think that's probably a poor choice of dimension in general since generally metrics systems frown upon the use of any dimension with unbounded cardinality.  Want to raise in `#observability` on slack.knative.dev?

**Comment by tragiclifestories** [comment]
https://github.com/knative/pkg/pull/1464 is merged now so I guess it's a matter of waiting for a new release to be cut and then bumping the dep ... Not sure if this would count as a breaking change, since it's hypothetically possible that somebody is relying on the current behaviour even though they really really shouldn't? 🤔
