### ISSUE TITLE
Replace old version of tekton images with tag :latest in examples

### ISSUE THREAD

**Issue by praveen4g0** [tektoncd/pipeline#2883]
To maintain consistency, in all examples [v1alpha1/v1beta1](https://github.com/tektoncd/pipeline/tree/master/examples) which uses tekton images with specific versions should be replaced with tag `latest`

Example:
- [pipelinerun.yaml](https://github.com/tektoncd/pipeline/blob/master/examples/v1beta1/pipelineruns/pipelinerun.yaml#L83) uses  `gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.11.0`

- [pipelinerun-with-final-tasks.yaml](https://github.com/tektoncd/pipeline/blob/master/examples/v1beta1/pipelineruns/pipelinerun-with-final-tasks.yaml#L60) uses `gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.12.1`

for same task `git-clone`, I guess it's better we remove dependency of tags in our examples

**Comment by vdemeester** [comment]
/area testing

`latest` wouldn't exercise changes in the PR itself though, we need to *dynamically* get the PR's image reference before running the tests. `ko` should help us with that.
