### ISSUE TITLE
get log of task pod failed

### ISSUE THREAD

**Issue by zgfh** [tektoncd/pipeline#2887]
# Expected Behavior
get task pod log when we debug
# Actual Behavior
get task pod log failed
# Steps to Reproduce the Problem

1. create many taskrun
2. when node of disk usage> 85%, kubelet will clean exited pod 
3. `kubectl log <task-pod-name> <step-name>`,  then failed 

![image](https://user-images.githubusercontent.com/11729624/86363332-3f8e3280-bca9-11ea-8fef-b3dfcf751bb3.png)

# Additional Info

- Kubernetes version:
1.15.4

- Tekton Pipeline version:
v0.10.2

**Comment by vincent-pli** [comment]
@zgfh 
Thanks for reporting the issue, I have several questions:
1. Do you mean `eviction` of k8s?
2. Your `taskrun` already complete or not.

Thanks.

**Comment by zgfh** [comment]
> @zgfh
> Thanks for reporting the issue, I have several questions:
> 
> 1. Do you mean `eviction` of k8s?
> 2. Your `taskrun` already complete or not.
> 
> Thanks.
thanks for help
1. pod status is Completed
2. taskrun is already complete

![image](https://user-images.githubusercontent.com/11729624/86441997-a78f5800-bd3f-11ea-97bd-19bdbabc2ad4.png)

**Comment by vdemeester** [comment]
The [results](https://github.com/tektoncd/experimental/tree/master/results) project aims to help with this. In the meantime, there is nothing we can do "against" the eviction policies of some clusters (gke, openshift, …)

I'm gonna go ahead and close as this is not really a bug and we are working towards fixing that through the results project.
If you think we should keep this open, comment here and i'll re-open :wink:
