### ISSUE TITLE
Invalid zap-logger-config in 0.14.0

### ISSUE THREAD

**Issue by Fabian-K** [tektoncd/pipeline#2901]
Hi,

just noticed that the zap-logger-config which is part of the ConfigMap config-logging has some unexpected content in https://github.com/tektoncd/pipeline/releases/download/v0.14.0/release.yaml

```
kind: ConfigMap
metadata:
  name: config-logging
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
data:
  # Common configuration for all knative codebase
  zap-logger-config: |
    {
      "level": "info",
      ""v0.14.0"opment": false,
```

looks like there is too much string replacement ("devel" -> version name) happening somewhere during the release process?

Best regards,
Fabian

**Comment by vdemeester** [comment]
/assign
My bad :sweat:

**Comment by vdemeester** [comment]
@Fabian-K should be fixed now :sweat_smile:

**Comment by vdemeester** [comment]
@Fabian-K I guess we can close the issue now :stuck_out_tongue_closed_eyes:
