### ISSUE TITLE
support variable substitution for params in finally section 

### ISSUE THREAD

**Issue by pritidesai** [tektoncd/pipeline#2906]
`params` in `finally` section should be substituted with actual values. Variables under `params` section is not getting interpolated and holds `$(params.x)` as its value.

/kind bug
/assign

**Comment by bobcatfish** [comment]
If we can fix this quickly, feels worth getting this into a patch release @vdemeester !

**Comment by pritidesai** [comment]
yup its very quick, will create a PR today

**Comment by pritidesai** [comment]
@vdemeester please add this to `Pipelines v0.14` milestone 🙏
