### ISSUE TITLE
Resource request not applied to init and sidecar containers

### ISSUE THREAD

**Issue by vincent-pli** [tektoncd/pipeline#2933]
I get a `ResourceQuota` applied to my namespace, then I cannot make my `taskrun` run success, get 
```
forbidden: failed quota, must specify limits.cpu,limits.memory,requests.cpu,requests.memory. Maybe missing or invalid Task
```
Event I set the `resources` section in my each `steps`, or in `stepTemplate`.
So I guess there is no such section in `initContainer` or Tekton's `sidecar` container.

# Expected Behavior
`Taskrun` run success.
# Actual Behavior
Failed
# Steps to Reproduce the Problem
1. Create `ResourceQuota` in certain namespace.
2. Create `Taskrun` in that namespace

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

**Comment by vdemeester** [comment]
/reopen
/lifecycle frozen

We should support this. I think `stepTemplate` should apply to any steps, even the one that are "dynamically" added by Tekton. For `initContainers`, either we know what it does and we specify sane (and small) defaults, or we could just use what the user requested in the `stepTemplate`

/assign

**Comment by skaegi** [comment]
Ideally Tekton should provide a mechanism to provide resource requirements for those containers it injects however a good workaround here is to use a LimitRange that provides reasonable defaults as those will also be applied to init containers.
