### ISSUE TITLE
PodSecurityPolicy Config problems running Tekton in a restricted environment 

### ISSUE THREAD

**Issue by skaegi** [tektoncd/pipeline#2966]
Until there is a better alternative we're using PodSecurityPolicy to lock down our environment and we did a quick audit of Tekton's default PSP config. We found a couple of fairly simple problems that should be fixed.

1. Tekton's PSP "tekton-pipelines" allows containers to `RunAsAny` user. It is applied to the "tekton-pipelines-controller" SA using a `ClusterRole`. A `ClusterRole` should not be used in this case as the PSP is only required in the "tekon-pipelines" namespace to allow the controller pod to be "created". Instead the PSP rule should be applied with a namespace-scoped `Role`. 

(As it stands, users able to create PipelineRuns and TaskRuns are indirectly permitted to "use" the "tekton-pipelines" PSP "in other namespaces" and in this case run as root since the controller is the "requesting user". See https://kubernetes.io/docs/concepts/policy/pod-security-policy/#authorizing-policies)

2. The  "tekton-pipelines-webhook" SA has no PSP applied to it so fails to start in a restricted environment. Similar to the controller the webhook should have a `RoleBinding` to permit use.

3. Both the controller and webhook pods run as root so need `runAsNonRoot: false` added to their deployment's template to help PSP find the right rule and avoid matching an alphabetically earlier PSP (like '001-restricted-psp') that will not permit them to run.

**Comment by vdemeester** [comment]
/cc @gabemontero 
I think the controller and pods can run as nonroot (and are now using the non-root images) so maybe we should make sure the run as non root instead of adding `runAsNonRoot: false` ?

**Comment by skaegi** [comment]
re: `runAsNonRoot` fix -- Is that WIP or something coming in the next release? If so it still might be worth adding the entry for now as that's what matches the current code and is super easy to undo when we have non-root support.

**Comment by vdemeester** [comment]
> re: `runAsNonRoot` fix -- Is that WIP or something coming in the next release? If so it still might be worth adding the entry for now as that's what matches the current code and is super easy to undo when we have non-root support.

It should be in 0.14.x for sure, but I don't think there is any test that is exercising this (aka running as non root)k

**Comment by skaegi** [comment]
Hmm... so in 0.14.1 I definitely cannot run as non-root. If I try I get...
```
Events:
  Type     Reason     Age                 From                  Message
  ----     ------     ----                ----                  -------
  Normal   Scheduled  <unknown>           default-scheduler     Successfully assigned tekton-pipelines/tekton-pipelines-controller-548c8fb7b5-fgc52 to 10.94.4.205
  Normal   Pulled     1s (x11 over 119s)  kubelet, 10.94.4.205  Container image "gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.14.1@sha256:882ec2239be27084865959089a0c7a82ef4ca681e8685d91040755007261fc6b" already present on machine
  Warning  Failed     1s (x11 over 119s)  kubelet, 10.94.4.205  Error: container has runAsNonRoot and image will run as root
```

**Comment by vdemeester** [comment]
@skaegi I don't this `runAsNonRoot` defined in the [`controller.yaml`](https://github.com/tektoncd/pipeline/blob/release-v0.14.x/config/controller.yaml) though (only in your PR https://github.com/tektoncd/pipeline/pull/2967/files#diff-d56e306ce931c2991f18ef68b6b501a3R109). :thinking:

**Comment by skaegi** [comment]
Right, what's happening in my environment is that I have a restricted psp that matches the pod description. What's happening is that the psp is "adding" the `runAsNonRoot: true` because it is not stipulated. e.g. the psp is mutating the pod definition

**Comment by skaegi** [comment]
I'm trying `runAsUser: 1001` and... so far so good. Let me update the PR.

**Comment by gabemontero** [comment]
> Right, what's happening in my environment is that I have a restricted psp that matches the pod description. What's happening is that the psp is "adding" the `runAsNonRoot: true` because it is not stipulated. e.g. the psp is mutating the pod definition.

On that, allowing the PSP admission controller to mutate the pod is hard coded to true at https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/security/podsecuritypolicy/admission.go#L128

The specific mutation @skaegi references is done at https://github.com/kubernetes/kubernetes/blob/master/pkg/security/podsecuritypolicy/provider.go#L167-L173
> 
> These policies are pretty standard and what we use for testing -- https://kubernetes.io/docs/concepts/policy/pod-security-policy/#example-policies
