### ISSUE TITLE
the website - tekton.dev, the demo on this website,the demo path maybe wrong --- the location is: Interactive Tutorial - step 2 of 6

### ISSUE THREAD

**Issue by gitupxm163** [tektoncd/pipeline#2968]
# Expected Behavior cd tekton-example/getting-started/src

# Actual Behavior cd tekton-examples/getting-started/src

# Steps to Reproduce the Problem

1. please fix the path: tekton-example ---> tekton-examples
2.
3.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

**Comment by pritidesai** [comment]
@gitupxm163 similar to #2969, this is part of website repo, can you please open this issue in that repo with some more details i.e. the exact location of setup file if you have/know?

**Comment by gitupxm163** [comment]
@pritidesai ok,i will do that,thanks.

**Comment by gitupxm163** [comment]
close this issue
