### ISSUE TITLE
tekton.dev -demo,some command may be wrong --- the location is: Interactive Tutorial - step 2 of 6

### ISSUE THREAD

**Issue by gitupxm163** [tektoncd/pipeline#2969]
# Expected Behavior 

when i run : mkdir /mnt/data && kubectl apply -f https://k8s.io/examples/pods/storage/pv-volume.yaml ......
the command Should execute correctly

# Actual Behavior

mkdir: cannot create directory ‘/mnt/data’: File exists
the result like this ,so the next command won`t be execute

# Steps to Reproduce the Problem

1. maybe we should use : mkdir -p /mnt/data && command....       to avoid  the problem
2.
3.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

**Comment by pritidesai** [comment]
@gitupxm163 the interactive tutorial is part of [website](https://github.com/tektoncd/website) repo, can you open this issue in that repo with the exact location of setup file.

**Comment by gitupxm163** [comment]
@pritidesai i will do it ,thanks
