### ISSUE TITLE
Pipeline level sidecar

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#2973]
### Feature request

In addition to letting Tasks specify sidecars https://github.com/tektoncd/pipeline/blob/master/docs/tasks.md#specifying-sidecars, which are containers that run alongside a Tasks's steps and the lifecycle of which is managed by the Tekton controller, we allow Pipelines to specify sidecars as well.

We could implement these as pods, which the Tekton controller starts when execution of the Pipeline starts and stops when the Pipeline completes (probably after the finally Tasks? not sure). It probably doesn't make sense to specify them as Tasks b/c Tasks are designed to run to completion and this would run as long as a Pipeline runs.

If the pod stopped with an error, we'd need to decide if we want to restart it or fail the Pipeline (maybe make that configurable?).

### Use case

In https://github.com/tektoncd/catalog/pull/408 I'm creating Tasks to lease and return Boskos resources. A regular heartbeat needs to be sent to Boskos while the resource is being used; if Boskos doesn't get a heartbeat it will assume the resource is no longer in use, clean it up and return it to its pool.

I've implemented this by having the Task that leases the resource create a pod and the Task the returns the resource stops the pod.

#### Other use cases

A few more use cases were mentioned in the API working group:

* Using “sidecar” to update github
* Use cases: external dependencies or dependency stubs during integration testing (run a DB, messaging platform or else)
* Use case: (pipeline-run-local) docker registry with pipeline run scope

**Comment by bobcatfish** [comment]
+ @chhsia0

**Comment by vdemeester** [comment]
As of today, this can be achieve by using a `Task` — that would do the deploy in the running cluster, … and clean-up in a finally task. There might some rbac issues as this means the service account running the task needs to have some rights on the cluster.
Overall it seems "fine" to me *but* I have the same though as with #2925 — how *required* it is ? how useful it is compared to the "potential" complexity it adds to the API ? (not saying it is complex, just that it adds another feature, etc…)

> Using “sidecar” to update github

I feel this "should" be handled by [*integration*](https://github.com/tektoncd/community/pull/147) like [`commit-status-tracker`](https://github.com/tektoncd/experimental/tree/master/commit-status-tracker).

> Use cases: external dependencies or dependency stubs during integration testing (run a DB, messaging platform or else)

This is indeed a use case that we have / will have with the [hub](https://github.com/tektoncd/hub) (cc @sthaha).

> Use case: (pipeline-run-local) docker registry with pipeline run scope

I am not sure I got this one. The idea would be to make sure a docker registry runs when the pipeline runs ? (so same as the `registry` sidecar we have in the catalog repository (cc @chmouel).

**Comment by bobcatfish** [comment]
+ @skaegi

**Comment by dlorenc** [comment]
Another crazy idea: make pipeline-level heartbeats a first-class thing - maybe through cloudevents.

**Comment by skaegi** [comment]
re: docker / registry sidecar Use Case...

One thing we see frequently is in response to a git commit, a single pipeline is run that splits into into separate Tasks used to both build sub-component images and sanity/unit test them concurrently. A later join Task decides if everything is in order and if so finally tags and pushes the images to a final pre-product image registry. 

We see this done with a Task-level sidecar docker daemon and a remote image registry. It might be good to have one dedicated Sidecar/Task to run a docker daemon the other Tasks share and use a pipeline scope image registry until ready to do the final push.

--

**Comment by chmouel** [comment]
I think a pipeline level sidecar object make sense for those use cases. 

Ideally it would be if we are able to specify a service attached to it so other tasks/pods can access it easily. 
This is in context of the DB or docker registry use case.

**Comment by dlorenc** [comment]
If we go ahead with this, some questions to think through:

- Do we run this as a pod? Or a replicaset for restarts/scaling?
- Do we wait for it to be "ready" before the pipeline starts? How do we know when it's "ready"?
- How do we make it accessible to the pipelinerun? And hopefully only that pipelinerun.
- How much customization do we allow on the created resources? Full Replicaset/service templates?

**Comment by ImJasonH** [comment]
These are useful questions.

I think the level of customization required might make it easier to just recommend that people start a Service at the beginning of a Pipeline and tear it down in a `finally`.

**Comment by dlorenc** [comment]
Yeah I think the only downside to that pattern is then that the Tasks at the start and cleanup have to run with enough RBAC to create the required k8s objects...

**Comment by bobcatfish** [comment]
I wonder if the feature that would work would be less about being a "sidecar" and more about tying the lifecycle of <something that complies with some interface> to a Pipeline - e.g. a kubernetes resource you "create" at the beginning of a pipeline and "delete" at the end?

**Comment by dlorenc** [comment]
That makes sense - stuff using "generateName" could be easily `kubectl create`d repeatedly. We'd need to think of a way to plumb the address/info of that object into the pipeline though. Maybe just make the gvk and name/namespace available via params?

**Comment by coryrc** [comment]
For the boskos leasing, Pipeline-level sidecar is a bit too wide... could we define a sidecar for a subset of Tasks? Effectively, once all of N listed Tasks are complete, Task X should be killed. 

A simpler primitive is to allow an anti-dependency. Today if Task 2 requires input from Task 1, it doesn't start executing until Task 1 is complete. Anti-dependency would be if Task 2 has anti-dependency on Task 1, it would start normally but be killed when Task 1 is complete.

For Boskos heartbeat, there'd be 3 Tasks: acquire, heartbeat, and release
heartbeat depends on acquire
heartbeat anti-depends on release

**Comment by bobcatfish** [comment]
I feel like we haven't had much interest in this one so I'd be happy to close it and re-open it if needed some day in the future @vdemeester
