### ISSUE TITLE
Improve testing around git packages

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/pipeline#2974]
### Feature request

We have a number of packages that work with git in some way.  Examples: `pkg/credentials/gitcreds`, `pkg/git`, `cmd/git-init`. The testing around these packages is not stellar.  In particular, `pkg/git` could really use some good testing since it's heavily utilized by both the Git PipelineResource and the `git-clone` Catalog Task.  We don't have any tests covering its public funcs but they are responsible for quite a lot behind the scenes: creating and moving files, setting ssh configuration options, configuring tls validation, calling out to the `git` binary etc etc.

**Comment by lbernick** [comment]
I was curious why we are not using a git lib like [go git](https://pkg.go.dev/github.com/go-git/go-git/v5@v5.4.2), so I looked into this today. I believe it would support the functionality needed in pipelines except for sparse checkout (https://github.com/go-git/go-git/issues/90).

**Comment by dibyom** [comment]
We have made some improvements. Coverage is up to around 70% now. 
Closing this. Can open a new issue to track further improvements.
