### ISSUE TITLE
the command referenced above is missed

### ISSUE THREAD

**Issue by zhangyunlin** [tektoncd/pipeline#2978]
# Expected Behavior
v0.14.1 pipeline/docs/taskruns.md, "Monitoring Steps" section mentioned a command to monitor steps status, but after ":", the command missed
# Actual Behavior
the command mentioned above is missed

# Steps to Reproduce the Problem

1. url : https://github.com/tektoncd/pipeline/blob/v0.14.1/docs/taskruns.md#monitoring-steps
2. after ":", the command missed
3. need to update the doc.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

**Comment by pritidesai** [comment]
This bug exists on the master as well. We need to rewrite the section on [Monitoring Steps](https://github.com/tektoncd/pipeline/blob/master/docs/taskruns.md#monitoring-steps) to:

```
If multiple Steps are defined in the Task invoked by the TaskRun, you can monitor their execution status in the status.steps field using the following command, where <name> is the name of the target TaskRun:

kubectl get taskrun <name> -o yaml

The exact Task Spec used to instantiate the TaskRun is also included in the Status for full audibility.
```
