### ISSUE TITLE
Provide configuration option to disallow omitting known_hosts 

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/pipeline#2981]
### Current Behaviour

When a [Git SSH secret](https://github.com/tektoncd/pipeline/blob/master/docs/auth.md#configuring-ssh-auth-authentication-for-git) does not include a `known_hosts` field, Tekton will accept any public key that an SSH/Git server returns. This could be a security concern and may not be an organization's desired behaviour.

### Expected Behaviour

Administrators should be able to set a requirement that any Git SSH Secret _must_ have `known_hosts` included. This will mean that the Git/SSH server identity can be validated before code is checked out.

### More Information

In order to implement this feature, multiple areas in Tekton Pipelines will need to be updated:

1. We could provide a configuration option in [`config/config-feature-flags.yaml`](https://github.com/tektoncd/pipeline/blob/master/config/config-feature-flags.yaml), named something like `require-git-ssh-secret-known-hosts` with a default value of `"false"`.  This will also require updating the [feature flag code in our config package](https://github.com/tektoncd/pipeline/blob/master/pkg/apis/config/feature_flags.go) to read the value.

2. If the feature flag is set, then our code in [pkg/pod/creds_init.go](https://github.com/tektoncd/pipeline/blob/3ad60446b77c8f1092055fc3acc94ba2b6fa0f18/pkg/pod/creds_init.go#L60) can reject a TaskRun if it uses secrets without a `known_hosts` entry.  The TaskRun should be rejected with a clear error message telling the user which Secret / service account is missing the `known_hosts` field.

To test this feature we'll need unit tests for changes to the config package and pod package.

### References

1. [Description of the `known_hosts` file](https://en.wikibooks.org/wiki/OpenSSH/Client_Configuration_Files#~/.ssh/known_hosts)

**Comment by yaoxiaoqi** [comment]
I would like to take this issue.
