### ISSUE TITLE
Set knative component consistently for webhook/controller

### ISSUE THREAD

**Issue by eddie4941** [tektoncd/pipeline#2987]
# Expected Behavior

The knative controller framework sets up a lot of infrastructure based on the `component` name. For example, loggers are created with the `component` name, metrics are prefixed with the `component` name, etc. It would be nice to have these set consistently for the controller and webhook. This would allow for metrics to be named consistently.

For example, it would be nice to have consistent metrics like

```
tekton_webhook_work_queue_depth
```
```
tekton_controller_work_queue_depth
```
which clearly identify which component the metrics belongs too.

# Actual Behavior

Currently the webhook and controller are not consistent with how they set their `component` name. The `webhook.component` == `webhook` and `controller.component` == `tekton`. This means that things like metrics(when using default prometheus backend) for the webhook will looks like: 
```
webhook_work_queue_depth
```
whereas for the controller the same metrics will look like:
```
tekton_work_queue_depth
```

This is misleading/confusing. Since some metrics have the `tekton` prefix, one would expect all tekton metrics to use that prefix. Also generic metrics like `webhook_work_queue_depth ` could collide with metrics emitted from other knative based daemons running in a cluster. 

Potential solutions:
 Set `component` based on the actual tekton daemon and add the `tekton` prefix
`webhook.component` == `tekton-webhook`
`controller.compoment` == `tekton-controller` 

# Additional Info

Heres where the component names are set:
webhook: `webhook` at https://github.com/tektoncd/pipeline/blob/v0.14.2/cmd/webhook/main.go#L215
controller: `ControllerLogKey` at https://github.com/tektoncd/pipeline/blob/v0.14.2/cmd/controller/main.go#L74

**Comment by vdemeester** [comment]
Sounds more than good to me to fix those.

**Comment by pritidesai** [comment]
Hey @eddie4941 the webhook logger key was fixed in PR https://github.com/tektoncd/pipeline/pull/3741. We have similar fix for the controller logger key in PR https://github.com/tektoncd/pipeline/pull/3752.
