### ISSUE TITLE
Image Mismatch

### ISSUE THREAD

**Issue by dlorenc** [tektoncd/pipeline#3007]
While (briefly) debugging #2998 with @skaegi, I noticed that the images we set as default flag values in [cmd/controller](https://github.com/tektoncd/pipeline/blob/master/cmd/controller/main.go#L37) differ from the images we set in [config/controller.yaml](https://github.com/tektoncd/pipeline/blob/master/config/controller.yaml).

I'm not sure how much of a problem this is, but it can be confusing. We should probably keep these up to date and matching somehow, but I'm not sure the best way.

**Comment by dlorenc** [comment]
An example of the confusion: the flag for "shell-image' defaults to busybox, while the deployment uses gcr.io/distroless/base:debug

**Comment by ImJasonH** [comment]
I think we should default the flags to "" and log.Fatal if they're unset. Having values in two places is confusing and error prone.

**Comment by ImJasonH** [comment]
Found another one!

[`.ko.yaml`](https://github.com/tektoncd/pipeline/blob/d3ba81d5590c6e5925caa80f5952f86bae438a37/.ko.yaml#L11) configures the base image for the `entrypoint` image to be `gcr.io/distroless/base:debug-nonroot`. But [`tekton/publish.yaml`](https://github.com/tektoncd/pipeline/blob/d3ba81d5590c6e5925caa80f5952f86bae438a37/tekton/publish.yaml#L78) writes a `.ko.yaml` file that configures its base to be `busybox`.

I'm not sure how to catch and fail on that kind of mismatch in the future, but should at least fix it for now.

**Comment by dlorenc** [comment]
Thanks for taking this on! Deleting the other defaults makes sense to me.

**Comment by dlorenc** [comment]
@ImJasonH I think this can be closed now, thanks for sending all those PRs!
