### ISSUE TITLE
Artifacts downloaded from storage resources or output Git resources lose execution permission.

### ISSUE THREAD

**Issue by chhsia0** [tektoncd/pipeline#3026]
# Expected Behavior

When a task consumes storage resources or output Git resources of another task,
the artifacts stored in the resource paths should have all POSIX permissions preserved.

# Actual Behavior

Tekton v0.14.2 uses `google/cloud-sdk:293.0.0-slim`, which doesn't preserve execution permission when fetching artifacts from s3 for storage or output Git resources through `gsutil cp -P -r`. When I manually run `gsutil ls -L` the metadata shows `Goog-Reserved-Posix-Mode:755`.

# Additional Info

- Tekton Pipeline version: v0.14.2

- I've tested a couple versions for `google/cloud-sdk`, and the last version that preserves execution permission is `276.0.0`

**Comment by dlorenc** [comment]
I think @vdemeester is picking up this update in https://github.com/tektoncd/pipeline/pull/3002

**Comment by chhsia0** [comment]
@dlorenc If v302 was cut before I reported this issue, then unfortunately no. I tested all recent versions before reporting this bug. See https://tektoncd.slack.com/archives/CLCCEBUMU/p1595950905046500?thread_ts=1595950905.046500&cid=CLCCEBUMU
