### ISSUE TITLE
"available available" would be "available"

### ISSUE THREAD

**Issue by kobaji** [tektoncd/pipeline#3036]
I was browsing https://github.com/tektoncd/pipeline/blob/master/docs/tasks.md and found the following sentence.

```
volumes - Specifies one or more volumes that will be available available to the Steps in the Task.
```

"available available" would be just "available".

---

This is the first time for me to publish an issue.
If this issue was inappropriate, I'd apologize for it.

**Comment by jlpettersson** [comment]
Hi, thanks for this.

You are right, it should be only "available".

Do you mind sending a PR for this? (if you want)

**Comment by kobaji** [comment]
Hi, thank you very much for your answer.
I'd be happy to send a PR for this.

This is the first time for me to send a PR, but anyway I'll try it!

**Comment by kobaji** [comment]
Unfortunately there are some trouble with my network, I haven't sent a PR yet.
I'll keep trying but might need a few more days.

I don't think this is an serious issue and I do not mind if someone sends a PR instead of me.

**Comment by rlandesman** [comment]
I'll help out :)

/assign @rlandesman

**Comment by pritidesai** [comment]
PR #3040 fixed this, thanks @jlpettersson @rlandesman @kobaji 🙏🏻

**Comment by kobaji** [comment]
I apologize for my mistake.
I posted assigning me by mistake. (it already has been deleted.)
