### ISSUE TITLE
Variable Substitution documentation does not explain how it works

### ISSUE THREAD

**Issue by jlpettersson** [tektoncd/pipeline#3039]
The [main doc page](https://github.com/tektoncd/pipeline/tree/master/docs) has a title "Understanding Tekton Pipelines" and under that, there is a link to [Variable Substitutions](https://github.com/tektoncd/pipeline/blob/master/docs/variables.md).

I expect that link to _explain how variable substitutions work_.

From [discussions on Slack](https://tektoncd.slack.com/archives/CLCCEBUMU/p1596130404055400), I now know that there is also:
* arrays
* star-operator to expand arrays (explained in [specifying params](https://github.com/tektoncd/pipeline/blob/master/docs/tasks.md#specifying-parameters))

Also 
* how it works within the `script:` field is not documented. It should be noted that variable substitution can be used within the middle of a _script_ and is executed before (?)
* that it can be expanded in `steps.args` list is not documented

* It would also be good to describe how I can _debug_ variable substitution? e.g. how I quickly can see to what values was inserted. (or maybe this is obvious?)

I expect those things to be explained on the docs, when I follow the doc-flow described initially.

**Comment by dbazhal** [comment]
Also "variable substitution" works as script-injection, I can make something like
![Screenshot_20200915_150140](https://user-images.githubusercontent.com/2122630/93207926-5dc1e580-f764-11ea-995c-0d3a84796391.png)
and it works. But not everywhere. It would be also cool to find description for that in doc.
