### ISSUE TITLE
Error count "failed" taskrun for metric of Prometheus

### ISSUE THREAD

**Issue by vincent-pli** [tektoncd/pipeline#3045]
# Expected Behavior
Count correct the number
# Actual Behavior
Incorrect
# Steps to Reproduce the Problem
Create a `taskrun` which cannot find `task` refer to.
check the `tekton_taskrun_count{status="failed"}`

# Additional Info
When such exception happened, 
https://github.com/tektoncd/pipeline/blob/c1852961039d0cd05def5e05cb1d180db8a72344/pkg/reconciler/taskrun/taskrun.go#L240-L245
a `PermanentError` was raised, the `knative/pkg` will `forget` the `taskrun` from `workqueue`, I guess that we expected.
but we also update the `.status`, that's will enqueue another `taskrun` object (same but with different .status), and it will enter :
https://github.com/tektoncd/pipeline/blob/c1852961039d0cd05def5e05cb1d180db8a72344/pkg/reconciler/taskrun/taskrun.go#L109-L110
directly, then count as `tekton_taskrun_count{status="failed"}` if any error in this section (`if tr.IsDone()`), a normal error will be raised, that's means the `taskrun` will re-enqueue again and again based on implements of this:
https://github.com/kubernetes/client-go/blob/00dbcca6ee44c678754d3f5fda1bd0e704b26fe2/util/workqueue/default_rate_limiters.go#L89

A candidate solution is wrapper all error in this section as `PermanentError` to let workqueue forget it.

**Comment by vincent-pli** [comment]
#3029 
@pritidesai

**Comment by pritidesai** [comment]
thanks @vincent-pli 

I am debugging into metrics. When I run a sample invalid TaskRun, Tekton logs has `taskrun done : <taskrun-name>` 12 times based on the default retry attempts with each TasRun instance having different addresses. TaskRun count it set to 1:

```
(stats.Measurement) {
 v: (float64) 1,
 m: (*stats.Float64Measure)(0xc000138a90)({
  desc: (*stats.measureDescriptor)(0xc000306dc0)({
   subs: (int32) 1,
   name: (string) (len=13) "taskrun_count",
   description: (string) (len=18) "number of taskruns",
   unit: (string) (len=1) "1"
  })
 }),
 desc: (*stats.measureDescriptor)(0xc000306dc0)({
  subs: (int32) 1,
  name: (string) (len=13) "taskrun_count",
  description: (string) (len=18) "number of taskruns",
  unit: (string) (len=1) "1"
 })
}
```

And each TaskRun status has exact same status:

```
Status: (v1beta1.TaskRunStatus) {
  Status: (v1beta1.Status) {
   ObservedGeneration: (int64) 0,
   Conditions: (v1beta1.Conditions) (len=1 cap=1) {
    (apis.Condition) {
     Type: (apis.ConditionType) (len=9) "Succeeded",
     Status: (v1.ConditionStatus) (len=5) "False",
     Severity: (apis.ConditionSeverity) "",
     LastTransitionTime: (apis.VolatileTime) {
      Inner: (v1.Time) 2020-08-03 23:19:43 +0000 UTC
     },
     Reason: (string) (len=23) "TaskRunResolutionFailed",
     Message: (string) (len=97) "error when listing tasks for taskRun taskrun-failure: tasks.tekton.dev \"does-not-exist\" not found"
    }
   },
```

I am not able to reproduce it, will give it a one more try.

**Comment by pritidesai** [comment]
I am debugging this with:

```
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: taskrun-failure
spec:
  taskRef:
    name: does-not-exist
```

**Comment by pritidesai** [comment]
May be in case of `Permanent Error`, controller should not try to exhaust the number of retries and just declare failure 🤔

**Comment by vincent-pli** [comment]
@pritidesai , so you reproduce it?

I means in section: `if tr.IsDone()`, if any exception occurred, it raise normal error rather than `Permanent` one, this cause repeat reconcile.
Actually, with your case, this line will raise `resource name should not nil` exception, since `r.Status.PodName` is nil.
https://github.com/tektoncd/pipeline/blob/28d13472156fcf2ceef4b0ae409fe368b73f96dc/pkg/reconciler/taskrun/taskrun.go#L124

The error is normal error, will cause the issue.

**Comment by pritidesai** [comment]
Yes, it raises error with `resource name should not be nil` which is causing the reconciler to fail with `Reconcile error` . The failed reconciled run tries to exhaust the number of retries in case of such failure.

After raising `Permanent error` from `prepare` or `reconcile`, reconciler should not return any error from within `tr.IsDone()` so that the controller can declare `Reconcile succeeded` and exit the `taskRun`.

The following unit test also does not catch this, it verifies the Permanent Error but does not validate whether its not requeued again, will add that test:

https://github.com/tektoncd/pipeline/blob/cb85f1d9d3c6acfdf08cc3fdb3424a10ced3a4cb/pkg/reconciler/taskrun/taskrun_test.go#L1698-L1705

I have changes in place, will create a PR.
