### ISSUE TITLE
taskServiceAccountName doesn't work

### ISSUE THREAD

**Issue by pciazynski** [tektoncd/pipeline#3063]
# Expected Behavior
When using following `PipelineRun`:
```yaml
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: run-pipeline-ci
  namespace: tekton-bug
spec:
  taskRunSpecs:
    - pipelineTaskName: task-1
      taskServiceAccountName: service-account-1
    - pipelineTaskName: task-2
      taskServiceAccountName: service-account-2
  pipelineRef:
    name: pipeline-ci
  timeout: 1h0m0s
```
I would expect to have `taskRuns` with a correct `serviceAccountName` assigned.

# Actual Behavior
No `serviceAccountName` is assigned. Look at the following `TaskRun`:
```yaml
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"tekton.dev/v1beta1","kind":"Task","metadata":{"annotations":{},"name":"task-1","namespace":"tekton-bug"},"spec":{"steps":[{"image":"node:dubnium","name":"task-1","script":"#!/bin/bash\necho \"Task 1\"\n"}]}}
    pipeline.tekton.dev/release: devel
  creationTimestamp: "2020-08-05T13:34:31Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: tekton-pipelines
    tekton.dev/pipeline: pipeline-ci
    tekton.dev/pipelineRun: run-pipeline-ci
    tekton.dev/pipelineTask: task-1
    tekton.dev/task: task-1
  name: run-pipeline-ci-task-1-p9xb5
  namespace: tekton-bug
  ownerReferences:
  - apiVersion: tekton.dev/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: PipelineRun
    name: run-pipeline-ci
    uid: bfc2c17f-882f-4e12-81ef-a4aac6b87c2c
  resourceVersion: "23642933"
  selfLink: /apis/tekton.dev/v1beta1/namespaces/tekton-bug/taskruns/run-pipeline-ci-task-1-p9xb5
  uid: 273bf2f6-9c7d-41eb-bfce-517dd4a18bb7
spec:
  resources: {}
  serviceAccountName: ""
  taskRef:
    kind: Task
    name: task-1
  timeout: 1h0m0s
status:
  completionTime: "2020-08-05T13:34:42Z"
  conditions:
  - lastTransitionTime: "2020-08-05T13:34:42Z"
    message: All Steps have completed executing
    reason: Succeeded
    status: "True"
    type: Succeeded
  podName: run-pipeline-ci-task-1-p9xb5-pod-478zq
  startTime: "2020-08-05T13:34:32Z"
  steps:
  - container: step-task-1
    imageID: docker-pullable://node@sha256:02a5fd0329277d081e65ccb5964a82dd5d735c2a8a92f089656486b32c29da49
    name: task-1
    terminated:
      containerID: docker://d345dce62d3d45e656f2aedc016d1c21e435da32358fe71b65469847b29d298e
      exitCode: 0
      finishedAt: "2020-08-05T13:34:42Z"
      reason: Completed
      startedAt: "2020-08-05T13:34:41Z"
  taskSpec:
    steps:
    - image: node:dubnium
      name: task-1
      resources: {}
      script: |
        #!/bin/bash
        echo "Task 1"

```

Service account is empty:
`  serviceAccountName: ""`
# Steps to Reproduce the Problem

1. Create a `tekton-bug` namespace.
2. Apply the following YAML:
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-account-1
  namespace: tekton-bug
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-account-2
  namespace: tekton-bug
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-1
  namespace: tekton-bug
spec:     
  steps:
    - name: task-1
      image: node:dubnium
      script: |
        #!/bin/bash
        echo "Task 1"
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-2
  namespace: tekton-bug
spec:     
  steps:
    - name: task-2
      image: node:dubnium
      script: |
        #!/bin/bash
        echo "Task 2"
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-ci
  namespace: tekton-bug
spec:
  tasks:
  - name: task-1
    taskRef:
      name: task-1

  - name: task-2
    taskRef:
      name: task-2
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: run-pipeline-ci
  namespace: tekton-bug
spec:
  taskRunSpecs:
    - pipelineTaskName: task-1
      taskServiceAccountName: service-account-1
    - pipelineTaskName: task-2
      taskServiceAccountName: service-account-2
  pipelineRef:
    name: pipeline-ci
  timeout: 1h0m0s

```
3. Look at created `taskRuns`. Check the line with `serviceAccountName`.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

 ```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T14:19:25Z", GoVersion:"go1.13.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"d94a81c724ea8e1ccc9002d89b7fe81d58f89ede", GitTreeState:"clean", BuildDate:"2020-03-12T21:00:06Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
 ```

- Tekton Pipeline version:

  **Output of  `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**:

 `v0.14.2`

**Comment by sbwsg** [comment]
i've just tested on `master` and haven't been able to reproduce this. I used https://github.com/tektoncd/pipeline/blob/master/examples/v1beta1/pipelineruns/no-ci/pipelinerun-taskrunspecs.yaml and updated [the taskServiceAccountName](https://github.com/tektoncd/pipeline/blob/master/examples/v1beta1/pipelineruns/no-ci/pipelinerun-taskrunspecs.yaml) field to be something other than "default".  When I ran the pipeline I got a TaskRun with my custom service account name in its `serviceAccountName` field.

I'll test with the 0.14 tag now.

**Comment by sbwsg** [comment]
Same result on the `release-0.14.x` tag in the repo: my custom serivce account name was propagated to my taskrun. @pciazynski could you try updating to 0.14.3 to see if that resolves your issue?

**Comment by chmouel** [comment]
Just in case off, are you running a kubernetes distro (i.e: openshift, microk8 or others) or on minikube/pure kubernetes?

**Comment by pciazynski** [comment]
Thank you for the fast asnwers!

@sbwsg I updated tekton to v0.14.3 and tested again - I've got the same result, service account being not propagated...
@chmouel I run it on our company internal Kubernetes. It's unfortunately quite old - `v1.15.11`, and yes, maybe there is some strange configuration there which I'm not aware of. But anyway I thought it's rather a tekton bug, because this happens only when I try to use `taskServiceAccountName`, when I set a `serviceAccountName` for the whole pipeline, then it works fine.

Do you have any tip how can I debug it, why tekton is not populating this service account?

**Comment by pciazynski** [comment]
OK, it works even for me when I try directly example from here:  https://github.com/tektoncd/pipeline/blob/master/examples/v1beta1/pipelineruns/no-ci/pipelinerun-taskrunspecs.yaml with updating the `taskServiceAccountName` field to be something other than `default`. 

So I need to examine what is wrong in my example...

**Comment by pciazynski** [comment]
Sorry guys for bothering you - my mistake. I've used `apiVersion: tekton.dev/v1alpha1` for the `kind: PipelineRun`...
After changing to `apiVersion: tekton.dev/v1beta1` things works as expected :) 

Thanks a lot for help. I'm closing this one.

**Comment by sbwsg** [comment]
Ah, great catch!  Thanks for getting back to us with the update.
