### ISSUE TITLE
Proxy support for Pipeline *and* tasks

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/pipeline#3090]
### Feature request

*This is probably worth splitting into two issues, but here goes.*

As an admin, I want the tekton controllers installed to use users network proxy settings defined for the platform so that both the tekton controllers as well as the Task or Pipeline steps / user workloads can access images, git repos, etc through our organizations proxy and with custom certificates.

**Why is this important?**
 To enable customer installs of the tekton to have network communications using the to use global proxy settings 

*Note*: this is only for `tektoncd/pipeline` but it does affect other components (`tektoncd/triggers`, …). It also, most likely, need to be a **TEP** I guess.

/cc @sbose78 @afrittoli @bobcatfish 

### Use case

A user sets up tekton in a cluster that uses a global proxy for network communications. It should work : aka tasks should be able to communicate with the outside world through the proxy (if what is in the tasks supports that of course), the different tekton components should go through the proxy too when doing network query ; for `tektoncd/pipeline`, it might be when querying the oci registry for the image config, …

### Parts

There is actually few parts for that issue : 

- How the user can provide the proxy configuration ? (through a configmap seems the best)
- Support for proxy's environment variables inside `tektoncd/pipeline` code (`cmd/controller`, `cmd/webhook`, …)
- How the controller/admission webhook can add those at runtime ? (this requires #1606 to work)

**Comment by bobcatfish** [comment]
Note we have a start to a TEP about this in https://github.com/tektoncd/community/pull/232
