### ISSUE TITLE
Inconsistent naming of container in release.yaml

### ISSUE THREAD

**Issue by piyush-garg** [tektoncd/pipeline#3113]
The container name is `tekton-pipelines-controller` in Controller Deployment while the name of the container in Webhook Deployment is `webhook`

Link for controller deployment: https://github.com/tektoncd/pipeline/blob/master/config/controller.yaml#L56

Link for webhook controller: https://github.com/tektoncd/pipeline/blob/master/config/webhook.yaml#L59

Is there any specific reason for this? Or is this left by some mistake?

/kind question
/kind bug

**Comment by vdemeester** [comment]
/close
I think this is fixed now.
