### ISSUE TITLE
I feel to build a long time

### ISSUE THREAD

**Issue by bibi520** [tektoncd/pipeline#3127]
Each building will be stuck here for a long time have what way can a bit faster
![image](https://user-images.githubusercontent.com/42456284/91038698-c7574400-e63d-11ea-97f9-4114f53c651f.png)

**Comment by withlin** [comment]
Are you using kaniko？ @bibi520

**Comment by bibi520** [comment]
yes

**Comment by bibi520** [comment]
![image](https://user-images.githubusercontent.com/42456284/91047445-a77b4c80-e64c-11ea-85cc-c1cc6a4dc325.png)

**Comment by withlin** [comment]
i think that you can upgrade kaniko version.

**Comment by bibi520** [comment]
Do you use the latest version?

**Comment by withlin** [comment]
we use v0.24. which is faster. we open source dashboard in [compass](https://github.com/yametech/compass)

**Comment by bibi520** [comment]
Thank you. I'll try.

**Comment by bibi520** [comment]
I switched to kaniko's version, but the more projects he builds, the longer he gets stuck
![image](https://user-images.githubusercontent.com/42456284/91376294-59826680-e84f-11ea-86d5-307e2b47e442.png)
Stuck for three minutes

**Comment by bibi520** [comment]
This happens from time to time

**Comment by bibi520** [comment]
It's been nine minutes and we haven't started building yet

![image](https://user-images.githubusercontent.com/42456284/91411987-b4ca4e00-e87b-11ea-9d0f-407cdacd5f51.png)
