### ISSUE TITLE
lack of validation (runAfter)

### ISSUE THREAD

**Issue by Miguel-Otero-IBM** [tektoncd/pipeline#3129]
runAfter does not do validation on its value. If it is not an array, it silently ignores it.

This has got me several times, when dealing with a runAfter dependency on just one task.

I would invariably tend to write it as:

    runAfter: otherTask

instead of

    runAfter:
      - otherTask

Tekton will accept the first form, then proceed to happily ignore it, so the otherTask will be fired concurrently with the task at hand and I will be left scratching my head about it.

# Expected Behavior

Either runTask accepts the first form (it honours the dependency) or throws an error.

# Actual Behavior

runAfter accepts the first form, but ignores it (no dependency on otherTask being finished).

**Comment by vdemeester** [comment]
@Miguel-Otero-IBM can you share the version of tekton pipeline that is deployed ? Also, can you list the deployments in `tekton-pipelines` ?

```
kubectl -n tekton-pipelines get deployment
```

Tried it out and it does validates : 

```
Error from server (BadRequest): error when creating "workspaces.yaml": admission webhook "webhook.pipeline.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: cannot unmarshal string into Go struct field PipelineTask.spec.tasks.runAfter of type []string
```

So my guess is that the webhook doesn't seem to run on your cluster :thinking:

**Comment by Miguel-Otero-IBM** [comment]
Tekton Pipeline is version 0.14.1 running on a private node on IBM Cloud.

```
kubectl -n tekton-pipelines get deployment
NAME                          READY   UP-TO-DATE   AVAILABLE   AGE
private-worker-agent          1/1     1            1           3d1h
tekton-pipelines-controller   1/1     1            1           3d1h
tekton-pipelines-webhook      1/1     1            1           3d1h
```
