### ISSUE TITLE
Implement Custom Tasks

### ISSUE THREAD

**Issue by ImJasonH** [tektoncd/pipeline#3133]
See [TEP-0002](https://github.com/tektoncd/community/blob/master/teps/0002-custom-tasks.md)

- Allow `TaskRef`s in `PipelineTask`s that specify an `apiVersion` and  `kind`
- Create `Run`s for those `Ref`s owned by the `PipelineRun`
- Collect `RunStatus`es in the `status` of the owning `PipelineRun`
- Simple end-to-end test demonstrating a `Run` being created from a `PipelineRun`
- Document Custom Task controller protocol and best practices
- Provide a sample Custom Task controller (based on knative/pkg? kubebuilder?)

/assign @ImJasonH

**Comment by sbwsg** [comment]
Moving to 0.18 as there's still some work being made towards this goal.

**Comment by dibyom** [comment]
Ref: https://github.com/tektoncd/pipeline/pull/3463

**Comment by vdemeester** [comment]
#3463 has been merged, should we close this ?

**Comment by afrittoli** [comment]
Closing this as it has been implemented. Follow up work can be treated separately.
