### ISSUE TITLE
Urgent required inputs_With istio side car enabled tekton pods are in CrashLoopBackOff status

### ISSUE THREAD

**Issue by vidheer** [tektoncd/pipeline#3148]
# Expected Behavior
As per this doc https://github.com/tektoncd/dashboard/blob/master/docs/walkthrough/walkthrough-istio.md 
Tekton pipelines should be up running with istio sidecar injected (manual/automatic).
# Actual Behavior
Tekton pipeline pods(controller and webhook) are NOT coming up and are in **CrashLoopBackOff** status
# Steps to Reproduce the Problem

1. istioctl kube-inject -f (<No internet access to Google APIs', so local path for tekton_release.yaml>) > tkn_release_inject.yaml
2. kubectl apply -f .\tkn_release_inject.yaml
3.  kubectl get pods -n tekton-pipelines

NAME                                           READY   STATUS             RESTARTS   AGE
tekton-pipelines-controller-7d6d999bdc-xvkt5   1/2     **CrashLoopBackOff**   11         33m
tekton-pipelines-webhook-94b55f9db-75bx6       1/2     **CrashLoopBackOff**   11         33m

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  PS C:\windows\system32> kubectl version
Client Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.7-eks-bffbac", GitCommit:"bffbacfd13a805a12d10ccc
0ca26205ae1ca76e9", GitTreeState:"clean", BuildDate:"2020-07-08T18:30:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platfor
m:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d
56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platfor
m:"linux/amd64"}

  ```

- Tekton Pipeline version:

 PS C:\windows\system32> tkn version
Client version: 0.11.0
Pipeline version: v0.15.2
Triggers version: unknown

**Please note:** 
1) Tekton pipelines are running fine without enabling istio sidecar. Issue is happening ONLY when istio is enabled.
2) Since our EKS cluster doesnt have internet access, i downloaded latest yaml file from "Google API endpoint"
3) Since our EKS cluster doesnt have internet access, i pulled all images from "**gcr**", uploaded to our "**ecr**" and updated tekton_release.yaml file with appropriate image locations from our local **"ecr"**
4) To rule out any image copy/paste or pull/push issues, same yaml file was used to install tekton without enabling istio and it was successful. Our ci/cd pipelines also ran successfully (without enabling istio)
5) Attached files are : i) release.yaml file after **kube-inject** ii) controller **pod describe**  iii) controller **pod logs
[tkn_controller_image_describe_pod.txt](https://github.com/tektoncd/pipeline/files/5150051/tkn_controller_image_describe_pod.txt)
[tkn_controller_pod_logs.txt](https://github.com/tektoncd/pipeline/files/5150056/tkn_controller_pod_logs.txt)
[tkn_release_inject.txt](https://github.com/tektoncd/pipeline/files/5150057/tkn_release_inject.txt)

**

**Comment by bobcatfish** [comment]
It looks like you are running this on a windows based system, is that right?

Would be great if someone could try to reproduce this on a linux system.

**Comment by ywluogg** [comment]
I wasn't able to reproduce the error. I was doing:
```
kubectl label namespace tekton-pipelines istio-injection=enabled
kubectl delete pods --all -n tekton-pipelines
istioctl kube-inject -f  release.yaml
kubectl apply -f release.yaml 
kubectl get pods -n tekton-pipelines                                                        
NAME                                           READY   STATUS    RESTARTS   AGE
tekton-pipelines-controller-74556b896c-lv9j4   2/2     Running   0          2m14s
tekton-pipelines-webhook-d66c98b7-dph7s        2/2     Running   0          2m14s
```

Are you still able to reproduce the error? (release.yaml was using [https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml](https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml)) I'm suspecting that your [https://github.com/tektoncd/pipeline/files/5150057/tkn_release_inject.txt](https://github.com/tektoncd/pipeline/files/5150057/tkn_release_inject.txt) is having issues.

**Comment by sbwsg** [comment]
Given the radio silence on this issue I'm going to call it closed for now.  Please feel free to reopen or create a new issue if the problem persists.

/close
