### ISSUE TITLE
Deploying TektonCD in an air gap environment

### ISSUE THREAD

**Issue by mfuxi** [tektoncd/pipeline#3155]
I'm trying to deploy TektonCD in an air gap environment (no internet) and i'm getting the following errors from both the controller and the webhook pods.

Controller:
```
flag provided but not defined: -kubeconfig-writer-image usage of /ko-app/webhook: 
-kubeconfig string
path to a kubeconfig. only required if out-of-cluster.
-master string 
the address of the kubernetes API server. Overrides any value in kubeconfig. only required if out-of-cluster
```
Webhook:
`found unset image flags: [build-gcs-fetcher creds entrypoint git gsutil imagedigest-exporter kubeconfig-writer nop pr shell]`

Any idea how to solve these issues? 

To start with I already brought all the necessary images to my private registry, and changed in the release.yaml all the calls to the images in the right places.

**Comment by GregDritschler** [comment]
Regarding the controller error, it sounds like there's a version mismatch between the deployment and the image.

The controller deployment passes a list of images as flags to the controller container.

```
$ kubectl get deploy tekton-pipelines-controller -n tekton-pipelines -o yaml
    . . .
    spec:
      containers:
      - args:
        - -kubeconfig-writer-image
        - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/kubeconfigwriter:v0.15.2@sha256:fafe062ebf497187b3ce7b47573580b4330f78b4924fb38e4c1e8db128711720
        - -creds-image
        - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/creds-init:v0.15.2@sha256:23387311d42bc6290645a864b2c967b857c531e4178fd5b79e31b2b8eb1ffa5c
        - -git-image
        - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.15.2@sha256:c6cb2257d718bbd6281f0d028c801c26333221a2c38ce85ae8e23b24bf20e781
        - -entrypoint-image
        - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint:v0.15.2@sha256:51037dc2b572748ef2f42e8e0f2d55e67a4dbc014cdaecba083de6280f422f2d
        - -nop-image
        - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/nop:v0.15.2@sha256:e418612699877caba09cae4ed8c73cfaf84aa8840a3c09aadda8c7c4934b857a
        - -imagedigest-exporter-image
        - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/imagedigestexporter:v0.15.2@sha256:e8cc95b323e85788dc82398cd37a259aff1a0bf2ca5489d5af4201aa4eca3743
        - -pr-image
        - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/pullrequest-init:v0.15.2@sha256:af9aea0ccca79b26e60e8f02ad0d46a20772bcb447201f21d477729c01d8e71e
        - -build-gcs-fetcher-image
        - gcr.io/tekton-releases/github.com/tektoncd/pipeline/vendor/github.com/googlecloudplatform/cloud-builders/gcs-fetcher/cmd/gcs-fetcher:v0.15.2@sha256:6b008c9eded786360ccc7bbc8d18f21a3ae049ff4604072c38763205346ca14c
        - -gsutil-image
        - google/cloud-sdk@sha256:37654ada9b7afbc32828b537030e85de672a9dd468ac5c92a36da1e203a98def
        - -shell-image
        - gcr.io/distroless/base@sha256:60f5ffe6fc481e9102747b043b3873a01893a5a8138f970c5f5fc06fb7494656
```

These flags must match what the code in the controller image expects to receive:

https://github.com/tektoncd/pipeline/blob/master/cmd/controller/main.go#L37

The list of flags does change occasionally.  It sounds like you might be mixing a controller deployment from one release with a controller image from a different release.

Regarding the webhook error, this looks like a different problem.  The error is complaining about missing image flags.  However it is the controller, NOT the webhook, that requires image flags.  I suspect your webhook deployment is pointing to the controller image, not the webhook image.

**Comment by mfuxi** [comment]
When I pushed the images to my private registry I pushed them with a version and without the digest, this might be the problem.

But I can't tag the image with the digest as it's written in the release.yaml file, so how can I solve this situation?

**Comment by mfuxi** [comment]
My bad, I accidentally tagged the controller as the webhook 

Changed it and everything worked
