### ISSUE TITLE
v1alpha1 e2e tests not being updated along with v1beta1 tests

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#3163]
# Expected Behavior

* When I look at the way an end to end test exercising the v1beta1 API compares to the same test for the same functionality against the v1alpha1 API, the test functionality should be the same
* When problems are found and fixed in end to end tests, they same fixes should be propogated to v1beta1 and v1alpha1 tests
* This should be made sustainable such that if we add another api version (e.g. v1beta2 or v1) we don't compound this issue

# Actual Behavior

The tests have diverged and updates are happening to v1beta1 and not v1alpha1.

For example compare [v1beta1 timeout_test.go](https://github.com/tektoncd/pipeline/blob/master/test/timeout_test.go) and [v1alpha1 timeout_test.go](https://github.com/tektoncd/pipeline/blob/master/test/v1alpha1/timeout_test.go) and recent fixes such as https://github.com/tektoncd/pipeline/commit/fb613dc6b7b56685394ec0883bd2e79e5e462e0a

# Additional Info

I wonder if we could set up these tests such that the same tests (when appropriate) can be run for both (all) api versions by passing the types in or creating some kind of agnostic builders.

**Comment by bobcatfish** [comment]
/remove-lifecycle stale

i think we should find a way (if possible) to write our e2e tests such that the same test can be run for multiple API versions instead of having to duplicate the tests for each API

**Comment by vdemeester** [comment]
@bobcatfish I am not sure to entirely follow. `v1alpha1` is "frozen" in that, we don't update it anymore. I don't really see any easy way to write e2e tests that can run multiple API versions as there is *no* guarantee (especially with `v1alpha1`) that a type can be convert from on to another. 

The "framework" of test can make it as simple as possible to write test (aka removing *any* noise) — https://github.com/tektoncd/pipeline/pull/3550 is a first step attempt at doing that — but other than "we should update tests in both `v1beta1` and `v1alpha1` if the fix on tests applies to both", I don't see what else to do.

**Comment by bobcatfish** [comment]
ah whoops, let this get rotten and close XD

> v1alpha1 is "frozen" in that, we don't update it anymore

the API is frozen, but the logic in the tests may still need updates as we maintain them over time

/reopen
/remove-lifecycle rotten
