### ISSUE TITLE
error：init containers: [working-dir-initializer place-tools]

### ISSUE THREAD

**Issue by bibi520** [tektoncd/pipeline#3170]
Is this error normal
![image](https://user-images.githubusercontent.com/42456284/92296998-305b8780-ef6d-11ea-8e55-323cb6100b4c.png)

**Comment by vdemeester** [comment]
Hi @bibi520 :wave:. This is normal, this is how `kubectl` acts with `pods` that have multiple containers (it has nothing to do with tekton :sweat_smile: aside the fact that we do create pods with multiple containers).

If you want to look at the logs of all containers in the pod, you need to use the `--all-containers` flags of `kubectl logs`. If you want to look at a specific container logs, you need to specify it with `-c/--container`.

/kind question

**Comment by sbwsg** [comment]
Thanks for the issue, I'm going to close this as answered!
