### ISSUE TITLE
Skip a task if previous task succeeded using when expressions

### ISSUE THREAD

**Issue by bharathvenkatrajan** [tektoncd/pipeline#3187]
I want to skip Task 2 if Task 1 was successful. If Task 1 fails, then I want Task 2 to execute. I read the documentation about when expressions, but I am not able to find a way to read the result (success or failed) of the previous task.

Basically, something like the below `when` expression. Execute Task when the previous failed. Check the previous Task's status (success or failed).

      when:
        - input: take_previous_tasks_result_status_as_input
          operator: in
          values: failed

Pipeline:

    apiVersion: tekton.dev/v1beta1
    kind: Pipeline
    metadata:
      generation: 10
      managedFields:
        - apiVersion: tekton.dev/v1beta1
          fieldsType: FieldsV1
          fieldsV1:
            'f:spec':
              .: {}
              'f:params': {}
              'f:resources': {}
              'f:tasks': {}
              'f:workspaces': {}
      name: new-pipeline
      namespace: pipelines-test
    spec:
      params:
        - description: the vmname from the POST data
          name: json-extract
          type: string
        - description: url of the git repo for the code of deployment
          name: git-url
          type: string
        - description: revision to be used from repo of the code for deployment
          name: git-revision
          type: string
      tasks:
        - name: fetch-repository
          params:
            - name: url
              value: $(params.git-url)
            - name: deleteExisting
              value: 'true'
            - name: revision
              value: $(params.git-revision)
            - name: sslVerify
              value: 'false'
          taskRef:
            kind: ClusterTask
            name: git-clone
          workspaces:
            - name: output
              workspace: shared-workspace
        - name: execute-script
          params:
            - name: vmname
              value: $(params.json-extract)
          runAfter:
            - fetch-repository
          taskRef:
            kind: Task
            name: execute-script
          workspaces:
            - name: source
              workspace: shared-workspace
        - name: execute-when-previous-fails
          when:
            - input: take_previous_tasks_result_as_input
              operator: in
              values: failed
          params:
            - name: vmname
              value: $(params.json-extract)
          taskRef:
            kind: Task
            name: execute-script
          workspaces:
            - name: source
              workspace: shared-workspace
      workspaces:
        - name: shared-workspace

Please help in pointing me to the right documentation?

**Comment by bharathvenkatrajan** [comment]
Hi @vdemeester et all,

To give a more detailed example. Let's say I have:
2 tasks - `task_one` and `task_two`. 
1 pipeline - `pipeline_one`
1 pipelinerun - `pipelinerun_one`

When the pipeline executes, I want to check if `task_one` was successful. If yes,`task_two` should be skipped. If `task_one` was not successful, then I want to execute `task_two`.

**Comment by jerop** [comment]
@bharathvenkatrajan to clarify, `WhenExpressions` uses `Results` which are string results emitted by tasks, as explained here: https://github.com/tektoncd/pipeline/blob/master/docs/tasks.md#emitting-results -- they're not the status (succeeded or failed) of the previous task -- so `task_one` will have to produce some string result that `task_two` would operate on 

in the [when expressions docs](https://github.com/tektoncd/pipeline/blob/master/docs/pipelines.md#guard-task-execution-using-whenexpressions), we have this snippet on using previous task's results:

```yaml
when:
- input: "$(tasks.check-file.results.status)"
  operator: in
  values: ["exists"]
```
you can view the extended version of this in the [when expressions examples](https://github.com/tektoncd/pipeline/blob/master/examples/v1beta1/pipelineruns/pipelinerun-with-when-expressions.yaml#L47-L68)

passing results between tasks happens via variable substitution using this variable structure `$(tasks.<task-name>.results.<result-name>)`, as described in [here](https://github.com/tektoncd/pipeline/blob/master/docs/pipelines.md#using-results)

just opened a pr to add more details on using results in when expressions: https://github.com/tektoncd/pipeline/pull/3194

**Comment by bharathvenkatrajan** [comment]
Hi @jerop thanks! 
The reason I wanted this was because I want to be notified when a `pipelinerun` fails. For eg: POST to a webhook like PagerDuty. Is `cloudevents` the only way I can configure it? If so, how to go about configuring it to only push notifications when a `pipelinerun` fails? 

[Here](https://github.com/tektoncd/pipeline/blob/master/docs/events.md) I can see CloudEvents sends notifications for all statuses. But I only want to send events that are Failed. I am not able to find a suitable example in the repo. Any help is much appreciated.

**Comment by bobcatfish** [comment]
hey @bharathvenkatrajan ! cloudevents is one way to do it, the other would be to have a `finally` task that does this - the caveat is that your finally task currently has no good way to check if other tasks in the pipeline have failed, which is one of the features we really need for finally ( #1020  + @pritidesai ) so at the moment you'd have to do something a bit hacky like use kubectl to check (with variable substitution you can get the name of the pipelinerun at least https://github.com/tektoncd/pipeline/blob/master/docs/variables.md#variables-available-in-a-pipeline)

**Comment by pritidesai** [comment]
Its been getting delayed but its time now, will start working on a TEP for it next week.

**Comment by pritidesai** [comment]
/reopen 

@bharathvenkatrajan are you still looking for solution or able to design your pipeline with `finally`?
