### ISSUE TITLE
Pass log level to Stackdriver

### ISSUE THREAD

**Issue by coryrc** [tektoncd/pipeline#3211]
### Feature request

Currently the JSON in error reports has a "level" field, with "error", "info", etc., but this does not go up to Stackdriver, so the UX is worse.

### Use case

It is much easier to view and filter logs when debugging if the level is reported in a way Stackdriver can use natively.

I think Boskos recently fixed this, so the authors of that tool might be able to help if you do not know what is wrong.

**Comment by sbwsg** [comment]
@coryc where abouts are you seeing the "level" output?  Is it in the controller logs or in our test runner output (you mention boskos, so wondering if this is an issue with our prow setup?)

**Comment by coryrc** [comment]
(this was a while ago, so pulling from memory):

This wasn't running on Prow or anything, this was me just applying Tekton TaskRuns and PipelineRuns to a cluster with `tkn`.

When things are logged, the Severity in Stackdriver is always `Info` level, so queries are slightly harder to write/UX a little worse.

![warning and error severity](https://user-images.githubusercontent.com/3232522/134214808-5821233f-e9fd-437a-b817-c50c059c38c0.png)

![only info severity](https://user-images.githubusercontent.com/3232522/134214833-862515e0-6040-46da-bc25-d307ed195b96.png)

**Comment by coryrc** [comment]
(I don't have any more Tekton things running, so have no pertinent logs to share; sorry. For all I know it's been fixed).

**Comment by sbwsg** [comment]
No worries, really appreciate the quick response on a year old thread! :D Thanks
