### ISSUE TITLE
Use the status of step as a parameter in the next step

### ISSUE THREAD

**Issue by nmousouros** [tektoncd/pipeline#3220]
Is it possible to get the status of the task ( success/ failure) as a result or as a variable or parameter?

I am trying to configure secured branches in github and I want to notify it only if the tests in the pipeline succeed or notify failure if it fails

**Comment by bobcatfish** [comment]
Hey @nmousouros  - if a Task in a pipeline fails, the whole pipeline stops. The exception is "finally" tasks, which run after the rest of the pipeline, regardless of failure, and for those we are planning to add #1020 which would allow finally tasks to see the state of the rest fo the pipeline

**Comment by bobcatfish** [comment]
I think this request is very similar to https://github.com/tektoncd/pipeline/issues/2800 and also https://github.com/tektoncd/pipeline/issues/1559, gonna close this issue for now, but please reopen or comment in those issues (or the WIP TEP https://github.com/tektoncd/community/pull/302) if we are missing something!
