### ISSUE TITLE
Slightly better sidecar technique

### ISSUE THREAD

**Issue by skaegi** [tektoncd/pipeline#3224]
The istio team has moved to a slightly improved mechanism for sidecar support (while we wait and see what happens in K8). I'm opening this issue more for awareness as the approach is elegant if a bit clever hacky -- https://medium.com/@marko.luksa/delaying-application-start-until-sidecar-is-ready-2ec2d21a7b74

**Comment by bobcatfish** [comment]
Thanks @skaegi ! Any chance you'd be willing to summarize the approach and how we might take it on? 🙏

**Comment by skaegi** [comment]
Actually I'll just add a note to #1569 and close this one to keep thing together.
