### ISSUE TITLE
Image source for zip utility

### ISSUE THREAD

**Issue by abudavis** [tektoncd/pipeline#3227]
Any ideas as to what are the available image sources for having a zip utility (functions such as zip -r) that can be used in a step task to zip files as part of a pipeline?

**Comment by bobcatfish** [comment]
Hey @abudavis - I don't know of any off the top of my head, our slack might be a good place to ask about that: https://github.com/tektoncd/community/blob/master/contact.md#slack

**Comment by abudavis** [comment]
Is there anywhere else I could ask about it, like bugzilla may be ?
