### ISSUE TITLE
Incorrect TaskRun status due to different Steps having the same StartedAt and FinishedAt times

### ISSUE THREAD

**Issue by Peaorl** [tektoncd/pipeline#3239]
# Preface
Users expect that the `status.conditions.message` field of a failed `TaskRun` is based on the first terminated `Step`.
For that reason, pod container statuses are sorted [#1905](https://github.com/tektoncd/pipeline/issues/1905).

Tekton sorts pod container statuses based on *FinishedAt* and *StartedAt* times.
Initially, sorting happened solely based on *FinishedAt* times.
This is troubling if the *FinishedAt* times of different `Steps` are the same.
Therefore, #2455 introduced sorting based on *StartedAt* times in case *FinishedAt* times are equal.

This issue is about the case when both *FinishedAt* and *StartedAt* times are the same.

# Expected Behavior
I have observed situations where two `Steps` have the same *FinishedAt* and *StartedAt* timestamps.
Notably in the [logs](https://tekton-releases.appspot.com/build/tekton-prow/pr-logs/pull/tektoncd_pipeline/3087/pull-tekton-pipeline-integration-tests/1304116333608177667/) for #3087 of which the relevant snippet is shown here:

<pre>
          steps:
          - container: step-timeout
            imageID: docker-pullable://busybox@sha256:2ca5e69e244d2da7368f7088ea3ad0653c3ce7aaccd0b8823d11b0d5de956002
            name: timeout
            terminated:
              containerID: docker://9ad19a910be8fd188b47cafebb57b6508c66da3317ac13dff7a605f27cdc9448
              exitCode: 1
              <b>finishedAt: "2020-09-10T18:10:46Z"</b>
              reason: Error
              <b>startedAt: "2020-09-10T18:10:46Z"</b>
          - container: step-canceled
            imageID: docker-pullable://busybox@sha256:2ca5e69e244d2da7368f7088ea3ad0653c3ce7aaccd0b8823d11b0d5de956002
            name: canceled
            terminated:
              containerID: docker://178b305cdbd4fe05b4df2d4d02c3242c664ec8d0fb0d3476680a533832b93c9f
              exitCode: 1
              <b>finishedAt: "2020-09-10T18:10:46Z"</b>
              reason: Error
              <b>startedAt: "2020-09-10T18:10:46Z"</b>
</pre>

What we would expect in the `status.conditions.message` field (before #3087 is actually merged) is :

<pre>
        status:
          completionTime: "2020-09-10T18:11:00Z"
          conditions:
          - lastTransitionTime: "2020-09-10T18:11:00Z"
            message: |
              <b>"step-timeout" exited with code 1 (image: "docker-pullable://busybox@sha256:2ca5e69e244d2da7368f7088ea3ad0653c3ce7aaccd0b8823d11b0d5de956002"); for logs run: kubectl -n arendelle-c5fjk logs run-timeout-pod-ttgfq -c step-canceled</b>
            reason: Failed
            status: "False"
            type: Succeeded
</pre>

# Actual Behavior

Instead what we get is:

<pre>
        status:
          completionTime: "2020-09-10T18:11:00Z"
          conditions:
          - lastTransitionTime: "2020-09-10T18:11:00Z"
            message: |
              <b>"step-canceled" exited with code 1 (image: "docker-pullable://busybox@sha256:2ca5e69e244d2da7368f7088ea3ad0653c3ce7aaccd0b8823d11b0d5de956002"); for logs run: kubectl -n arendelle-c5fjk logs run-timeout-pod-ttgfq -c step-canceled</b>
            reason: Failed
            status: "False"
            type: Succeeded
</pre>

I.e., not the output of the first terminated `Step`.

# Suggestion

**Potential solutions:**

1. Sort pod container statuses based on the following priority:
    i. FinishedAt time
    ii. StartedAt time
    iii. TaskSpec `Step` order

OR

2. Sort pod container statuses based on the TaskSpec `Step` order.

OR

3.  `Steps` write their own higher resolution (i.e. use milliseconds) *FinishedAt* times as results.
Then, sort pod container statuses based on these results. These results are easily filtered from user exposed task results after #3138 is merged.

I'm leaning towards option 3 because it seems like the most reliable solution to always base the logs on the the first terminated `Step`. Option 3 has briefly been mentioned [before](https://github.com/tektoncd/pipeline/issues/2415#issuecomment-616556315) but lost traction, seemingly because of the somewhat higher complexity.
With option 3, the `Step` statuses in the `TaskRun` could either show the K8s or the Tekton written *StartedAt* and *FinishedAt* times.

## Sorting just once?
Additionally, after the pod container status have been sorted, the `Steps` displayed under the`TaskRun` status are [sorted](https://github.com/Peaorl/pipeline/blob/ea1f5233dac9e36f8d482e505e0ef8abd58ec432/pkg/pod/status.go#L141) according to the original `Step` order in the TaskSpec, regardless of *FinishedAt* or *StartedAt* times. Indeed, if Tekton properly serializes `Steps`, this should be the correct `Step` order anyway.

In short: 
- Tekton populates the`status.conditions.message` field for a terminated `TaskRun` based on the first terminated `Step` by sorting pod container statuses based on *FinishedAt* and *StartedAt* times.
- The ordering of `Steps` displayed under the `TaskRun` is based on the original `Step` order in the TaskSpec regardless of *FinishedAt* or *StartedAt* times.

Perhaps it would make sense to only sort the pod container statuses (based on one of the proposed solutions) and also use this order to display `Step` statuses in the `TaskRun`.

# Steps to Reproduce the Problem

1. Install #3087 
2. Run the TestStepTimeout integration test until this situation occurs.

Alternatively, a test could mock `Steps` with the same *StartedAt* and *FinishedAt* times which should confirm this bug.

# Additional Info

- Tekton Pipeline version:
```
 #3087 
```

**Comment by bobcatfish** [comment]
Thanks for the thorough investigation @Peaorl !

I like option 2 personally; unless we're including sidecars (and maybe we are? maybe that's why this is a problem? looking at https://github.com/tektoncd/pipeline/blob/76aff13938220d66ab91e517bbbe7dffb1eb9a9f/pkg/pod/status.go#L111-L137 i dont think we are tho) i would expect the order the steps are evaluated in to reflect the actual order the containers run in.

Option 3 makes a lot of sense too, but it seems like we should already know the order the steps are supposed to run in 🤔  Maybe a pro of option 3 is that that would reflect the actual reality, in the case that something went wrong?

One con of option 3, im not sure how much control we have over the format of those fields, i.e. if they are expected to match the format of similar fields in pod status (https://github.com/tektoncd/pipeline/blob/76aff13938220d66ab91e517bbbe7dffb1eb9a9f/vendor/k8s.io/api/core/v1/types.go#L2335)

**Comment by Peaorl** [comment]
Of course! Thanking @sbwsg for the leads too.

>   unless we're including sidecars (and maybe we are? maybe that's why this is a problem?

Exactly, `Sidecars` are not included for formulating a `TaskRun` status. See the NB section [here](https://github.com/tektoncd/pipeline/tree/master/cmd/nop) or the [code](https://github.com/tektoncd/pipeline/blob/a65704a95f62f4f44757b113a9427f21849a48d7/pkg/pod/status.go#L219).
I'm not entirely sure how that would affect this situation though?

> Option 3 makes a lot of sense too, but it seems like we should already know the order the steps are supposed to run in 🤔 Maybe a pro of option 3 is that that would reflect the actual reality, in the case that something went wrong?

Indeed I think option 3 supports actual reality as is the case now too (just not at a high enough resolution 😄). I think it would be interesting to know if this is why the timestamp solution was chosen in the first place. 
Otherwise I agree that option 2 should work as well assuming Tekton always schedules the `Steps` correctly.

> One con of option 3, im not sure how much control we have over the format of those fields, i.e. if they are expected to match the format of similar fields in pod status

I was thinking to write a `Task` result right around [here](https://github.com/tektoncd/pipeline/blob/d18e94fbb2c8ff2d368eb87da6c3996699717755/pkg/entrypoint/entrypointer.go#L123). Tekton could then use this result only to order pod containers while the timestamp in the pod status could stay the lower resolution K8s provided timestamp.

**Comment by GregDritschler** [comment]
> Option 3 makes a lot of sense too, but it seems like we should already know the order the steps are supposed to run in 🤔 Maybe a pro of option 3 is that that would reflect the actual reality, in the case that something went wrong?

When I investigated this logic before, I think one of my concerns about using taskspec step order is that it wouldn't handle a failure of an internal step (i.e. the ones inserted by tekton).  I thought that's why the timestamp approach was needed.

**Comment by Peaorl** [comment]
I see, would these internal `Steps` be initContainers? Because it seems like there's a separate container statuses field for initContainers.

**Comment by bobcatfish** [comment]
> I see, would these internal Steps be initContainers? Because it seems like there's a separate container statuses field for initContainers.

I _think_ there might be an init container or 2 but they are definitely not all init containers, e.g. PipelineResources add containers before and after.

> using taskspec step order is that it wouldn't handle a failure of an internal step (i.e. the ones inserted by tekton).

If we went this route, we'd need to take into account the order of all steps, including internal steps - we actually added the order of these "internal" steps to our api compatibility policy and tried to make it deterministic in https://github.com/tektoncd/pipeline/pull/970

**Comment by Peaorl** [comment]
Thanks all! I went ahead with option 2 in #3256
