### ISSUE TITLE
`script:` doesn't error when /bin/sh is dash

### ISSUE THREAD

**Issue by coryrc** [tektoncd/pipeline#3253]
Introduced in #1735, scripts will default to have `set -ex`, in that if any line returns a non-zero exit code, the entire Task will fail (errexit) and every line is printed before being executed (xtrace). Unfortunately the behaviour is inconsistent depending on which shell the image has `/bin/sh` symlinked to and should not allow execution if `set -e` does not work.

I believe errexit should be consistent; if I write a `script:` without shebang, 99.9%+ of images should either have errexit or not work at all. I believe this could be done by adding more to the prelude to detect if the actual shell is not one of the whitelisted ones (sh, bash, busybox, more?), and terminating; or choosing `#!/bin/bash` as the default shell, but this would break existing Tasks that are otherwise using busybox or real sh, both of which implement errexit AFAICT.

# Expected Behavior
```
[unnamed-0] + '[['  '=='  ]]
[unnamed-0] + exit 0
```

# Actual Behavior
```
[unnamed-0] + [[  ==  ]]
[unnamed-0] /tekton/scripts/script-0-zxmx7: 3: /tekton/scripts/script-0-zxmx7: [[: not found
[unnamed-0] + echo Should not print
[unnamed-0] Should not print
```

# Steps to Reproduce the Problem

Execute this TaskRun:

```
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: repro-danger-
spec:
  taskSpec:
    steps:
      - image: google/cloud-sdk:slim@sha256:27b2c22bf259d9bc1a291e99c63791ba0c27a04d2db0a43241ba0f1f20f4067f
        script: |
          if [[ "" == "" ]]; then
            exit 0                                                                                                                                                                        
          fi                                                                                                                                                                              
          echo Should not print                                                                                                                                                           
```

To see the passing case, change the image to `alpine`, which uses busybox.

# Additional Info

- Tekton Pipeline version:
Client version: 0.12.0
Pipeline version: v0.15.2
Triggers version: unknown

**Comment by vdemeester** [comment]
> Introduced in #1735, scripts will default to have `set -ex`, in that if any line returns a non-zero exit code, the entire Task will fail (errexit) and every line is printed before being executed (xtrace). Unfortunately the behaviour is inconsistent depending on which shell the image has `/bin/sh` symlinked to and should not allow execution if `set -e` does not work.
> 
> I believe errexit should be consistent; if I write a `script:` without shebang, 99.9%+ of images should either have errexit or not work at all. I believe this could be done by adding more to the prelude to detect if the actual shell is not one of the whitelisted ones (sh, bash, busybox, more?), and terminating; or choosing `#!/bin/bash` as the default shell, but this would break existing Tasks that are otherwise using busybox or real sh, both of which implement errexit AFAICT.

Thanks for the issue @coryrc. From my point of view, this is a problem of the image and not on tekton. As documented, not using any shebang in script, will default to `#!/bin/sh` (and `set -xe`). This means, the assumption a user should do in that case is that it is gonna be `/bin/sh` and not `/bin/bash` or something else. The fact that the `/bin/sh` in the image is `/bin/sh` or is a link to another shell, that may or may not support `/bin/sh` syntax, is a problem on the image. 

I don't think the tekton controller should be smart about this. Looking into the image for the shells and have a whitelist seems to be a complex task for very little gain, as the user being more or less *in control* of the image to run.

Also, using `[[` is, from what I think I know, a bash feature, so it might not be available when using `/bin/sh` or at least a user shouldn't make that assumption, and should be explicit about using `bash` (by having the shebang `#!/bin/bash`, or even better `#!/usr/bin/env bash`).

**Comment by chmouel** [comment]
I think what we are authoring in `script:` should only be consistent with regard to the image you are running in your current task, not with other images from other tasks.

i.e: if the  task author choose a image that only works on /bin/dash the author should ensure it works by other means than relying on the error catching of `set -e`.

**Comment by coryrc** [comment]
> I don't think the tekton controller should be smart about this. Looking into the image for the shells and have a whitelist seems to be a complex task for very little gain, as the user being more or less _in control_ of the image to run.

Agreed, I don't think the *controller* should be smart about it, but I think we could be injecting something along with `set -e` which will abort the script if the intended `set -e` behavior is not functional.

**Comment by coryrc** [comment]
> I think what we are authoring in `script:` should only be consistent with regard to the image you are running in your current task, not with other images from other tasks.

As a naive user, I was surprised by this not working -- I anticipate others will copy from examples but be tripped up by this same problem. Even the Task catalog has [Tasks](https://github.com/tektoncd/catalog/blob/5cf3952aedee17745b35d1b2ad75235821c41e57/task/gke-cluster-create/0.1/gke-cluster-create.yaml) which could easily "pass" despite all gcloud commands failing!

OTOH, I didn't know this about dash and I could just have easily written #!/bin/sh and expected `set -e` to work.

In my personal order of preferences, safe is no1, consistent is no2, concise is no3. If we're going to provide a default shell and a preamble with `set -xe`, then it should be a shell guaranteed to implement `set -xe`. If it uses `#!/bin/bash`, I'm guaranteed safety.

**Comment by coryrc** [comment]
Ah, I see now -- it only didn't abort because the error occurred in an `if`. If I use an invalid command in an `if` in bash it also doesn't fail. If a command fails in `dash` it still aborts the script.

The real issue is `sh` isn't guaranteed to have `[[` and that's reasonable and totally my fault!

Sorry for distraction.
