### ISSUE TITLE
Config option to skip downward API for some Tasks/Pipelines/Runs

### ISSUE THREAD

**Issue by dibyom** [tektoncd/pipeline#3257]
### Feature request

In #2080, we added a flag to skip the downward API step during TaskRun which can lead to faster startup times for TaskRuns without sidecars.

Today, the [flag](https://github.com/tektoncd/pipeline/blob/master/config/config-feature-flags.yaml#L60) is for the entire Pipelines installation i.e there is no way to selectively enable it for only some Pipeline/TaskRuns.

This feature request is to allow setting this option on a per task/pipeline/run perhaps using a custom annotation.
 
### Use case

From @pierretasci on Slack:

> Several of the clusters we run selectively inject sidecars. Some of the time, some pipelines may have injected sidecars and some of the time they don’t. We don’t have an all or nothing cluster.

**Comment by vdemeester** [comment]
Would it make sense to use `annotation` for this on the resources ?

**Comment by dibyom** [comment]
> Would it make sense to use annotation for this on the resources ?

Yes, that's what I was thinking of too.
