### ISSUE TITLE
Cleanup: multiple unnecessarily exported methods

### ISSUE THREAD

**Issue by imjasonh** [tektoncd/pipeline#3262]
Repurposing a script used to find unused test builder methods from https://github.com/tektoncd/pipeline/issues/3178#issuecomment-695158605 to try to find exported method names that aren't invoked from outside their package.

```
$ git grep -o "^func [A-Z][^(]*" pkg/ | grep -v "pkg/client" | grep -v " Test" | cut -d' '  -f 2 | sort | uniq | xargs -n 1 -I{} sh -c "git grep -c '\.{}(' > /dev/null || echo {}"
ApplyResourceSubstitution
ConvertErrorf
DagFromState
EmitErrorEvent
EmitEvent
EventForObjectWithCondition
EventForPipelineRun
EventForTaskRun
GetPVCSpec
GetPersistentVolumeClaim
HasDefaultConfigurationName
IsPodHitConfigError
MarkStatusFailure
MarkStatusRunning
MarkStatusSuccess
NeedsPVC
NewArtifactBucketFromConfig
NewFakeClient
NewPipelineRunTest
NewTektonCloudEventData
ResolvePipelineTaskResources
ShowRef
SubmoduleFetch
ValidateDeclaredWorkspaces
ValidateResults
WithDefaultConfigurationName
```

This greps for exported function names like `Foo` which aren't found in the codebase `.Foo(`, which would indicate that it's called by another package -- callers in the same package wouldn't need to reference the package name with a `.`

This also:
- ignores funcs in `pkg/client` since those are generated
- ignores funcs with `Test` in the name, since those are test methods called by `go test`

Spot-checking some of these:
- `SubmoduleFetch` is exported in `pkg/git/git.go` and only ever called in that package. It could be unexported.
- `ValidateDeclaredWorkspaces`, same story.
- `NeedsPVC` is exported and only called in its corresponding test, it could be unexported.
- `DagFromState` is defined in a `_test.go` file and only called from other tests, it could be unexported. (If it stays exported it should also be renamed to `DAGFromState` to adhere to Go style advice for [initialisms](https://github.com/golang/go/wiki/CodeReviewComments#initialisms)

I have a strong suspicion we could rename all these methods to be unexported (e.g., `ValidateResults` becomes `validateResults`) and check that tests still pass and images still build.

-----

Exported methods present a potential maintenance burden on Tekton contributors, since some external user might come to depend on the method, and could be broken if we change or remove the method.

Exported methods are effectively part of our Go library API, and while we don't have any support/deprecation policy around that, that wouldn't stop users from depending on it and being upset when we change it.

In general, methods should not be exported unless they need to be.

/kind cleanup

**Comment by vigneshashokan** [comment]
@ImJasonH If no one is working on this, I can take a stab at this issue.

**Comment by ImJasonH** [comment]
> @ImJasonH If no one is working on this, I can take a stab at this issue.

Great! It should be pretty straightforward, let me know if you have any questions or find any difficulties.

**Comment by vigneshashokan** [comment]
Hi @ImJasonH, I created this PR https://github.com/tektoncd/pipeline/pull/3327 for this issue. Let me know what you think.

**Comment by chmouel** [comment]
I think it still there : 

```
% git grep -o "^func [A-Z][^(]*" pkg/ | grep -v "pkg/client" | grep -v " Test" | cut -d' '  -f 2 | sort | uniq | xargs -n 1 -I{} sh -c "git grep -c '\.{}(' > /dev/null || echo {}"
ApplyResourceSubstitution
ConvertErrorf
EmitErrorEvent
EmitEvent
EventForObjectWithCondition
EventForPipelineRun
EventForTaskRun
GetPersistentVolumeClaim
GetPVCSpec
GetRunName
HasDefaultConfigurationName
IsPodHitConfigError
MakeLabels
MarkStatusFailure
MarkStatusRunning
MarkStatusSuccess
NeedsPVC
NewArtifactBucketFromConfig
NewFakeClient
NewPipelineRunTest
NewTektonCloudEventData
ResolvePipelineTaskResources
ShowRef
SubmoduleFetch
ValidateDeclaredWorkspaces
ValidateGitSSHURLFormat
WithDefaultConfigurationName
```

the PR on https://github.com/tektoncd/pipeline/pull/3327 is still open @vigneshashokan would you like to rebase it ?

/remove-lifecycle rotten

/assign @vigneshashokan
