### ISSUE TITLE
Sections out of order in DEVELOPMENT.md

### ISSUE THREAD

**Issue by AlexReiff** [tektoncd/pipeline#3263]
1. The `Checkout your fork` section cannot be completed before the `Set up your shell environment` and `Install requirements` which are listed after it in on the page (and in the ordering at the top of the page).

1. Neither the `Set up your shell environment` nor the `Install requirements` sections can be completed without making partial progress in the other.
`Set up your shell environment` needs Go to be installed first, and `Install requirements` needs `GOPATH` and `$GOPATH/bin` configured to install Ko.

**Comment by bobcatfish** [comment]
I think this was fixed in #3264, thanks @AlexReiff !
