### ISSUE TITLE
The Tekton Pipelines webhook service does not work with Istio mTLS

### ISSUE THREAD

**Issue by jpower432** [tektoncd/pipeline#3276]
# Expected Behavior
Try to create a new Tekton custom resources resources with Istio mTLS set to STRICT
Resource is created

# Actual Behavior

Try to create a new Tekton custom resources resources with Istio mTLS set to STRICT
Webhook service X509 cert failure

Error from server (InternalError): error when creating "maven/": Internal error occurred: failed calling webhook "webhook.pipeline.tekton.dev": Post "https://tekton-pipelines-webhook.tekton-pipelines.svc:443/defaulting?timeout=30s": x509: certificate is not valid for any names, but wanted to match tekton-pipelines-webhook.tekton-pipelines.svc

# Steps to Reproduce the Problem

1. Install Istio 1.5.4 on demo profile
2. Set default Peer Authentication policy to STRICT mTLS
3. Install Tekton 0.16.3 with istio-injection=enabled on the tekton-pipelines namespace
4. Try to create a new Tekton Task resources
5. Set Peer Authentication to PERMISSIVE mTLS
5. Try to create the same task

# Additional Info

- Kubernetes version:
1.19

- Tekton Pipeline version:
0.16.3

When checking the Tekton Pipelines Webhook certificate with OpenSSL it show an CN being set and the an SAN being set on the set correctly
subject=O = knative.dev, CN = tekton-pipelines-webhook.tekton-pipelines.svc
DNS:tekton-pipelines-webhook, DNS:tekton-pipelines-webhook.tekton-pipelines, DNS:tekton-pipelines-webhook.tekton-pipelines.svc, DNS:tekton-pipelines-webhook.tekton-pipelines.svc.cluster.local

**Comment by skaegi** [comment]
The tekton pipelines controller and webhook both talk to the kubernetes api server. I don't specifically use Istio in my clusters where I run Tekton workloads but this might help... https://istio.io/latest/faq/security/#accessing-non-istio-services as it specifically has an example for the api server.

**Comment by jpower432** [comment]
Thanks @skaegi. Seems like it is an issue with the exchange between Envoy and the webhook service over 8443. If I put an exclude 8443 annotation on the webhook deployment, everything work normal with STRICT mTLS. Could it be that the webhook service doesn't trust the Istio certificates or they are not in format expected?

**Comment by skaegi** [comment]
The traffic to the webhook comes directly from the API Server (sometime through a kube-system vpn pod). I'm not sure the "source" in this case will go through Envoy at all but really not sure.

**Comment by jpower432** [comment]
@skaegi I think you are right. We are just trying to get non-Istio services and Istio service to communicate with mTLS which just won’t work unless the Kube-API server was communicating with the Istio certs. We can go ahead and close this. Thanks for your help!
