### ISSUE TITLE
Webhook log has repeated TLS handshake error EOF messages

### ISSUE THREAD

**Issue by GregDritschler** [tektoncd/pipeline#3303]
# Expected Behavior

The webhook log does not contain errors during normal operation.

# Actual Behavior

The webhook log contains the following error repeated every few seconds:

```
2020/09/29 19:14:53 http: TLS handshake error from 10.104.2.1:57866: EOF
2020/09/29 19:15:01 http: TLS handshake error from 10.104.2.1:57884: EOF
2020/09/29 19:15:03 http: TLS handshake error from 10.104.2.1:57888: EOF
```

# Steps to Reproduce the Problem

* Find the `tekton-pipelines-webhook` pod and display its log.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
    Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", 
    GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", 
    GoVersion:"go1.11.2", Compiler:"gc", Platform:"windows/amd64"}
    Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.15+IKS", 
    GitCommit:"a7ace239946d71c9305593eacf74b9a9efa25e3b", GitTreeState:"clean", BuildDate:"2020-09-09T00:11:53Z", 
    GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version:

    ```
    Pipeline version: v0.16.3
    ```

The error is caused by the liveness and readiness probes that were added by PR #3162.  Manually removing those probes from the webhook deployment and restarting the webhook pod stops the errors.

From the client perspective, the probe is working.  It is a tcp socket probe so it is connecting to the socket successfully and then disconnecting.  From the server perspective, it appears that the golang tls library is complaining that a client connected and then did not perform the tls handshake, hence the "EOF" message.

Although the probes are working, the logs are filling up with messages that make it appear like something is wrong with the webhook.

**Comment by GregDritschler** [comment]
Hi  @ywluogg.   As the original contributor of the liveness and readiness probes can you please investigate and resolve this issue?  Thank you.

**Comment by ywluogg** [comment]
Taking a look now

**Comment by ywluogg** [comment]
This happens because the probes are using https ports, but only establishing TCP connections, so no HTTPS protocol handshake is done, causing TLS to throw error. I'm planning to switch to a normal http port and separate the ports for probes from webhook https ports.
