### ISSUE TITLE
Regression in master: Cannot pass array variable from pipelinerun to task

### ISSUE THREAD

**Issue by GregDritschler** [tektoncd/pipeline#3307]
# Expected Behavior

I can define an array parameter value in my PipelineRun and pass it to a Task that declares that parameter to be array type.

# Actual Behavior

```
Error from server (BadRequest): error when creating "arraysample.yaml": admission webhook "validation.webhook.pipeline.tekton.dev" denied the request: validation failed: variable type invalid in "$(params.pipeline-words)": spec.pipelinespec.tasks[0].params[task-words].value[0]
```

# Steps to Reproduce the Problem

The problem can be recreated with the following yaml.  I have run this yaml successfully before.

```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: array-sample-
spec:
  params:
    - name: pipeline-words
      value:
        - eggs
        - sugar
        - flour
  pipelineSpec:
    params:
      - name: pipeline-words
        type: array
    tasks:
      - name: echoit
        params:
          - name: task-words
            # Note: The value has to be expressed as a list so it thinks of it as an array. 
            value: 
              - $(params.pipeline-words)
        taskSpec:
          params:
            - name: task-words
              type: array
          steps:
            - name: echo
              image: ubuntu
              command: ["echo"]
              args: ["$(params.task-words[*])"]
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
    Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", 
    GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", 
    GoVersion:"go1.11.2", Compiler:"gc", Platform:"windows/amd64"}
    Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.15+IKS", 
    GitCommit:"a7ace239946d71c9305593eacf74b9a9efa25e3b", GitTreeState:"clean", BuildDate:"2020-09-09T00:11:53Z", 
    GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version:

    Master (`commit 1722db72ed0444c70220cb5a736f7e942a07fac9`)

I believe the problem was introduced in PR #3277 in changes to `pkg/apis/pipeline/v1beta1/param_types.go`.

The function `validateArrayVariableInTaskParameters` used to look like this:

```
func validateArrayVariableInTaskParameters(name, value, prefix string, stringVars sets.String, arrayVars sets.String) *apis.FieldError {
	if err := substitution.ValidateVariable(name, value, prefix, "task parameter", "pipelinespec.params", stringVars); err != nil {
		return err
	}
	if err := substitution.ValidateVariableIsolated(name, value, prefix, "task parameter", "pipelinespec.params", arrayVars); err != nil {
		return err
	}
	return nil
```

Now it looks like this:

```
func validateArrayVariableInTaskParameters(value, prefix string, stringVars sets.String, arrayVars sets.String) *apis.FieldError {
	errs := substitution.ValidateVariableP(value, prefix, stringVars)
	return errs.Also(substitution.ValidateVariableProhibitedP(value, prefix, arrayVars))
}
```

The function used to prohibit using string values in array variables.  Now it's also prohibiting using array values.  It also seems to have lost the "ValidateVariableIsolated" check.

**Comment by GregDritschler** [comment]
@vdemeester ^^^

**Comment by vdemeester** [comment]
> The function `validateArrayVariableInTaskParameters` used to look like this:
> 
> ```
> func validateArrayVariableInTaskParameters(name, value, prefix string, stringVars sets.String, arrayVars sets.String) *apis.FieldError {
> 	if err := substitution.ValidateVariable(name, value, prefix, "task parameter", "pipelinespec.params", stringVars); err != nil {
> 		return err
> 	}
> 	if err := substitution.ValidateVariableIsolated(name, value, prefix, "task parameter", "pipelinespec.params", arrayVars); err != nil {
> 		return err
> 	}
> 	return nil
> ```
> 
> Now it looks like this:
> 
> ```
> func validateArrayVariableInTaskParameters(value, prefix string, stringVars sets.String, arrayVars sets.String) *apis.FieldError {
> 	errs := substitution.ValidateVariableP(value, prefix, stringVars)
> 	return errs.Also(substitution.ValidateVariableProhibitedP(value, prefix, arrayVars))
> }
> ```
> 
> The function used to prohibit using string values in array variables. Now it's also prohibiting using array values. It also seems to have lost the "ValidateVariableIsolated" check.

It always did both though (or should have). Looking into why it fails now but…

**Comment by vdemeester** [comment]
Oh I see :facepalm:
