### ISSUE TITLE
Entrypoint cache should expire items

### ISSUE THREAD

**Issue by imjasonh** [tektoncd/pipeline#332]
When we lookup entrypoints for remote images, we cache it for later lookups. Items are never removed from the cache, so if the controller runs for long enough and sees enough unique builder images, it will consume more and more memory. This could present a risk of DoS, since a malicious user can craft valid build requests that fill the cache, especially with large values for entrypoints.

We should use a LRU cache ([here](https://godoc.org/github.com/hashicorp/golang-lru)'s a popular one in Go) that will only keep the most recently-used entrypoints cached and drop entrypoints we haven't used recently.

**Comment by afrittoli** [comment]
Since https://github.com/knative/build-pipeline/pull/350 is merged, I think this could be closed?

I added https://github.com/knative/build-pipeline/pull/418 as a follow-up, the deps update pops up when running ./hack/update-deps.sh
