### ISSUE TITLE
Upgrade Kubernetes dependencies to 0.19.2

### ISSUE THREAD

**Issue by rawlingsj** [tektoncd/pipeline#3324]
We're using the Tekton client in a couple of places and are currently upgrading all our golang Kubernetes dependencies to 0.19.2.  This includes an upgraded Kubernetes client-go which requires fixing up code due to breaking API changes.

I've just noticed there's a similar PR https://github.com/tektoncd/pipeline/pull/3319 although that doesn't go all the way to 0.19.2 so I wonder if we should combine the two efforts or keep them separate?  

Right now I have made these changes on a fork https://github.com/rawlingsj/pipeline/tree/k8s_0.19.2

I'm not sure I've done everything that's needed to upgrade:
- updated the [go.mod file](https://github.com/rawlingsj/pipeline/commit/cc8569605eeab9204fff337df02ffdeecb6bcc3b#diff-37aff102a57d3d7b797f152915a6dc16)
- `make vendor`
- `go mod vendor`
- `clientgofix ./...` to fix breaking API changes from client-go https://github.com/kubernetes-sigs/clientgofix/
- `make generated`
- manually fixed up breaking API changes from generated clients
- `make all`

A couple of questions
1. Not sure if there are other steps that are needed above?
2. Did you want a PR for these changes and if so should I look to combine with https://github.com/tektoncd/pipeline/pull/3319 or just keep them separate?

**Comment by afrittoli** [comment]
Does this require an update to the minimum version?

**Comment by sbwsg** [comment]
It looks as though this will happen naturally when we upgrade to knative 0.21.

**Comment by dprotaso** [comment]
The above PR bumped the k8s deps

**Comment by dprotaso** [comment]
Right now `knative.dev/pkg` is tracking the main branch instead of the 0.20 release.

**Comment by afrittoli** [comment]
This is closed by https://github.com/tektoncd/pipeline/pull/3724
