### ISSUE TITLE
Duplicate 'pipelinerun.successful' cloudevent 

### ISSUE THREAD

**Issue by wwu-cx** [tektoncd/pipeline#3336]
# Expected Behavior

A single 'dev.tekton.event.pipelinerun.successful.v1' event after a successfull pipelinerun.

# Actual Behavior

Two 'dev.tekton.event.pipelinerun.successful.v1' events with different id's and different timestamps referencing the same run:

First:

"ce-type": "dev.tekton.event.pipelinerun.successful.v1"
"ce-time": "2020-10-06T05:19:26.898238287Z",
"ce-subject": "tekton-builds-wwu-p2v8b-r-7bgc4",
"ce-id": "c7a26faa-a825-4a0f-8c2d-9ce192a9a5b8",
"ce-source": "/apis/tekton.dev/v1beta1/namespaces/tekton-builds/pipelineruns/tekton-builds-wwu-p2v8b-r-7bgc4",

Second:

"ce-type": "dev.tekton.event.pipelinerun.successful.v1",
"ce-time": "2020-10-06T05:19:26.952135384Z",
"ce-subject": "tekton-builds-wwu-p2v8b-r-7bgc4",
"ce-id": "fe652d4a-53fc-4bd7-9bbc-cc41f6953f86",
"ce-source": "/apis/tekton.dev/v1beta1/namespaces/tekton-builds/pipelineruns/tekton-builds-wwu-p2v8b-r-7bgc4",

# Steps to Reproduce the Problem

1. Create a Listener for the CloudEvents
2. Filter for header.match('ce-type', 'dev.tekton.event.pipelinerun.successful.v1')
3. Log the invocations

# Additional Info

- Kubernetes version:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

```
Client version: 0.12.1
Pipeline version: v0.16.3
Triggers version: v0.8.1
```

**Comment by afrittoli** [comment]
Hello @wwu-cx, thanks for this bug report.
I was able to reproduce the issue and I'm working on a fix
