### ISSUE TITLE
Missing version in pod annotations

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/pipeline#3338]
# Expected Behavior
The annotation in the pod shows the version of pipeline it was created by

# Actual Behavior

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    pipeline.tekton.dev/release: ""
```

# Steps to Reproduce the Problem

1. Install latest Tekton (v0.17.0)
2. Run a task `k create -f https://raw.githubusercontent.com/tektoncd/pipeline/master/examples/v1beta1/taskruns/task-result.yaml`

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

 ```
$ k version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-21T14:51:23Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

```
$ tkn version
Client version: 0.12.1
Pipeline version: v0.17.0
Triggers version: v0.8.1
```

It looks like things are a bit mixed up with versions.
If I look at the deployment:
```
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/name: controller
    app.kubernetes.io/part-of: tekton-pipelines
    app.kubernetes.io/version: v0.17.0
    pipeline.tekton.dev/release: v0.17.0
    version: v0.17.0
```

and in the pod template:
```
      labels:
        app: tekton-pipelines-controller
        app.kubernetes.io/component: controller
        app.kubernetes.io/instance: default
        app.kubernetes.io/name: controller
        app.kubernetes.io/part-of: tekton-pipelines
        app.kubernetes.io/version: v0.17.0
        pipeline.tekton.dev/release: v0.17.0
        version: v0.17.0
    spec:
      containers:
      - args:
        - -version
        - devel
```

The `version` arg is supposed to be used by the taskrun controller to set the version annotation on the taskrun and thus on the pod.

/kind bug

**Comment by vdemeester** [comment]
@afrittoli interesting… I think I missed updating the `publish` task :thinking: (although I was pretty positive I did.. :thinking: )
/assign

**Comment by vdemeester** [comment]
Oh I know why… I forgot to apply the latest `publish.yaml` task before doing the release :facepalm: …
Should be taken care of on 0.17.1 …

**Comment by afrittoli** [comment]
Thanks!
Still I wonder, version `devel` should have resulted in an annotation `devel`, not an empty string?

**Comment by vdemeester** [comment]
> Still I wonder, version `devel` should have resulted in an annotation `devel`, not an empty string?

Good point… it might be.. more than this.. :sweat:
