### ISSUE TITLE
Starts pipeline from image refresh on external hub registry

### ISSUE THREAD

**Issue by andradedpg** [tektoncd/pipeline#3354]
### Feature request

In last sunday, Jeferson Fernando (https://github.com/badtuxx) from LinuxTips, promotes a livestream about how Tekton is helpfull in devops k8s life cycle. -> https://www.youtube.com/watch?v=adFl-4A4fX4 <-
At a moment, was discuss about how the pipeline can be started from image update on external registry (DockerHUB, AWS ECR, ...) public or private. Afterwords, we thought will be looks good if the Tekton Pipelines offer some hook or integration that this functionallity. 

Let me know if is already possible or if is a good ideia and make sense 💡

### Use case

- The user has a CI on own project (GitHUB, Bitbucket, AWS PipeLines,...) and are published (CD) image results on registry (DockerHUB, AWS ECR, ...)
- The Tekton Pipeline - for some way - its called from previous operation (from a hook?) 
- tkn Pipeline starts a new deploy into Cluster. 

--------

Tag of images on registry can be used to deploy on differents namespaces or this is can be managed into yml files.

I hope this suggest make sense and thank you in advance!

**Comment by devwander** [comment]
Up!

**Comment by msmagnanijr** [comment]
Up

**Comment by vdemeester** [comment]
@andradedpg this is *already* possible using the [`tektoncd/triggers`](https://github.com/tektoncd/triggers) project by configuring the registry to notify the webhook (created by an event-listener in triggers) on image push or some other events (or all events really). If the registry doesn't support webhook on events, then, there is still the possibility to do a cron-job that would "poll" the list of tags and trigger a PipelineRun in case of changes.

There might be the need to add some "helper" to auto configure thoses (just as some helper to auto configure the github/gitlab/… webhook configuration), but it's definitely doable already. In any case, this is something in the scope of the Tekton project (`tektoncd/*` component), but not in the scope of `tektoncd/pipeline` :angel:.

**Comment by vdemeester** [comment]
*quick note*: :+1: on the issues description are enough to notify to the community your interests, no need for an `Up` comment :wink: :pray:

**Comment by tirelibirefe** [comment]
Hello @andradedpg 
Were you able to push images to private ECR repo? If yes, could you please confirm it is possible to push images  private ECR repo by using apiVersion: tekton.dev/v1 ? 

Because there are several issues not answered regarding to the pushing images to private ECR repo and I am totally lost.

Thanks & Regards
