### ISSUE TITLE
Bump copyright year

### ISSUE THREAD

**Issue by raballew** [tektoncd/pipeline#3408]
In general the guidance I've seen is to bump the year if you're touching the file. Bulk commits to update the year everywhere aren't great for history/blame tracking, but keeping it up to date is slightly better than not.

_Originally posted by @dlorenc in https://github.com/tektoncd/pipeline/pull/3391#discussion_r507724933_

**Comment by FogDong** [comment]
The truth is that we don't bump the year after touching the file since I see no `2021 copyright` in the repo 😅
I wonder if we should update all the files in a once, if so, I can help
