### ISSUE TITLE
tekton e2e tests regressed against clusters with non-standard suffix

### ISSUE THREAD

**Issue by mattmoor** [tektoncd/pipeline#3429]
# Expected Behavior

Bundle tests pass on clusters without `.cluster.local` suffix.

# Actual Behavior

Bundle tests do not pass on clusters without the default suffix.

```
--- FAIL: TestTektonBundlesUsingImproperFormat (604.05s)
    init_test.go:132: Create namespace arendelle-bm27z to deploy to
    init_test.go:148: Verify SA "default" is created in namespace "arendelle-bm27z"
    tektonbundles_test.go:494: Failed to create image. Pod logs are: 
        Getting image source signatures
        time="2020-10-22T01:17:31Z" level=fatal msg="Error trying to reuse blob sha256:f8100eb13895118e18d3d2de52aa84950308bb3c9deb65379758b0cb1e353053 at destination: error pinging docker registry registry.arendelle-bm27z.svc.cluster.local:5000: Get http://registry.arendelle-bm27z.svc.cluster.local:5000/v2/: dial tcp: lookup registry.arendelle-bm27z.svc.cluster.local: no such host"
```

# Steps to Reproduce the Problem

Start kind with a random suffix: https://github.com/mattmoor/mink/blob/eea5fcbfc387a5b40c2c7dd5769e085a2ac2e147/.github/workflows/minkind.yaml#L170

**Comment by mattmoor** [comment]
cc @pierretasci

**Comment by pierretasci** [comment]
Ah good catch. I can drop a new change really quick to fix this. Should just be a matter of removing the redundant suffix.

**Comment by ImJasonH** [comment]
I think this is closed now.

**Comment by mattmoor** [comment]
Yep!  I removed my downstream workaround, so I'll let y'all know if it regresses again 😉
