### ISSUE TITLE
Creating a PipelineRun with Go code

### ISSUE THREAD

**Issue by evyros** [tektoncd/pipeline#3450]
Hi :)
I'm trying to create a PipelineRun programatically with Go code.
I followed the [tutorial](https://github.com/tektoncd/pipeline/blob/master/docs/tutorial.md) and created a task, pipeline and a pipelinerun.
Now I want to create another PipelineRun for an existing pipeline. So I have this:

```go
pr := &v1beta1.PipelineRun{
     ObjectMeta: metav1.ObjectMeta{
         Name: "tutorial-pipeline-run-1",
     },
     Spec: v1beta1.PipelineRunSpec{
          PipelineRef: v1beta1.PipelineRef{
               Name: "tutorial-pipeline",
          },
     },
}
```

What is the **recommended way** to send it to Tekton / k8s?
Is there such a way at all? I couldn't find it anywhere in the code.

Thank you very much and I hope it's okay to ask this question here.

**Comment by dibyom** [comment]
You can use the generated pipeline go client to create the resource: https://pkg.go.dev/github.com/tektoncd/pipeline@v0.17.0/pkg/client/clientset/versioned/typed/pipeline/v1beta1#PipelineRunInterface

example from our e2e tests: https://github.com/tektoncd/pipeline/blob/0df5c32e3b473b11fb91c9f5b7c2ea7f39630d0e/test/clients.go#L68

Another good place to ask these type of questions would be in our Slack: https://github.com/tektoncd/community/blob/master/contact.md#slack
