### ISSUE TITLE
Need an example of mentioning my docker host in a task.

### ISSUE THREAD

**Issue by zeromsi** [tektoncd/pipeline#3483]

**Comment by jerop** [comment]
@zeromsi here's one example:
https://github.com/tektoncd/pipeline/blob/50212455bfaa22165a887104e3f6f6c862a4213c/examples/v1beta1/taskruns/dind-sidecar.yaml#L1-L65

/kind question

**Comment by zeromsi** [comment]
hey @jerop thank you!

**Comment by Manikanta-Reddy-Pasala** [comment]
@jerop 
 i tried the above example but i am not able to mount a workspace folder as volume for the docker image. can you please help me on this.
 
 exmplae: 
       docker run -v "$(workspaces.source.path):/workspace" --rm use-case-configuration-updater:latest
 template -i /workspace/overlays/distributor-template -o /workspace/overlays -d /workspace/example-distributor.yaml
 
 
 above command is failling
