### ISSUE TITLE
unit test build failed: t.Cleanup undefined

### ISSUE THREAD

**Issue by Vstural** [tektoncd/pipeline#3512]
# Expected Behavior

expect build success/test passed

# Actual Behavior

```shell
note: module requires Go 1.14
# github.com/tektoncd/pipeline/pkg/apis/config_test [github.com/tektoncd/pipeline/pkg/apis/config.test]
pkg/apis/config/artifact_bucket_test.go:83:11: t.Cleanup undefined (type *"testing".T has no field or method Cleanup)
pkg/apis/config/artifact_pvc_test.go:81:11: t.Cleanup undefined (type *"testing".T has no field or method Cleanup)
pkg/apis/config/feature_flags_test.go:84:11: t.Cleanup undefined (type *"testing".T has no field or method Cleanup)
```

# Steps to Reproduce the Problem

run `go test ./...`
or see [build log](https://tekton-releases.appspot.com/build/tekton-prow/logs/post-tekton-pipeline-go-coverage/1325933069860868096/?log#log)

- Tekton Pipeline version:

master branch

consider upgrade go version to go 1.14 and run `go mod vendor`?

**Comment by vdemeester** [comment]
@Vstural right, we need to update the coverage image.
/assign

**Comment by dibyom** [comment]
Do we need to re-apply the prow config after this image change?
I still see issues with missing `Cleanup` methods for some Triggers PRs: https://tekton-releases.appspot.com/build/tekton-prow/pr-logs/pull/tektoncd_triggers/828/pull-tekton-triggers-go-coverage/1327349908058935296/?log#log
