### ISSUE TITLE
allow parameter replacement in TriggerTemplate.spec.resourceTemplates.metadata.*

### ISSUE THREAD

**Issue by itewk** [tektoncd/pipeline#3516]
### Feature request

I would like to be able to use the git ref name in the generated PipelineRun name (and lables) that triggered the TriggerTemplate but currently the TriggerTemplate.spec.resourceTemplates.metadata.* fields don't allow TriggetTemplate parameter replacement.

### Use case
1) would allow us to be able to make it so that PipelineRuns created from TriggerTempaltes have human useable names in the UI, ie, include the triggering Git ref in the name to be able to easly visual sort which runs were for which branch
2) be able to use parameters on labels on the triggered PipelineRun (like the git ref) to allow for easy kubectl filtering commands based on those labels.

**Comment by dibyom** [comment]
Hmm...this should already work. We allow replacements anywhere within a resourceTemplate.

Is it not working for you? In that case, what is the error message that you get?

**Comment by itewk** [comment]
@dibyom my appologies. i could have sworn i tried this a couple weeks ago and it didn't work, but i just tried it and it worked fine. when i first tried it i was on an older tekton, and i had no clue what i was doing. appologies for the noise.
