### ISSUE TITLE
[Question] Proper way to define role so tkn can have access to tekton.dev objects? 

### ISSUE THREAD

**Issue by itscatherinelam** [tektoncd/pipeline#3543]
Good morning, friends! Another question from a tekton newb. 

I created a super basic image with the tkn cli (housed in /tmp) curled onto an ubi8 image. But if I try to run tkn commands from it, I get the error: **Error: failed to list Pipelines from namespace coco: pipelines.tekton.dev is forbidden: User "system:serviceaccount:coco:default" cannot list resource "pipelines" in API group "tekton.dev" in the namespace "coco"**

I think my next approach would be to define a role that can somehow have additional access to tekton.dev - would this access have to be appended to an existing role or a brand new one that I then associate to the service account? If anyone has an example role YAML, that'd blow my socks! 

Thanks in advance :) 

- Cat

**Comment by itscatherinelam** [comment]
Hey! I figured out a way to fix it. Instead of using the default SA, I used the pipeline SA that's created in every OpenShift namespace as part of the Tekton operator - '**_oc set sa dc/<dcName> pipeline_**'. 

However, I am still curious what the alternative way as I suggested in original post would be carried out. How would I edit the default SA so that its permissions matched the pipeline SA? Is it a role thing? Policy?

**Comment by dibyom** [comment]
hi @itscatherinelam 

one way to do this would be to create a Role that has the right RBAC rules, and then associate it with a SA using a RoleBinding. You can either append to an existing SA or create a new one.

Not exactly what you'd need but you can look at  https://github.com/tektoncd/triggers/blob/master/examples/github/role.yaml

You'd probably need "get", "list", "watch", "create" verbs for all tekton resources (such as pipelines, pipelineruns etc.: https://github.com/tektoncd/triggers/blob/master/examples/github/role.yaml#L34-L36
