### ISSUE TITLE
Tekton is duplicating task runs that make up a pipeline run

### ISSUE THREAD

**Issue by alan-ghelardi** [tektoncd/pipeline#3557]
I noticed recently that around 10% of our pipeline runs have duplicated task runs.

Initially, I thought that there was a relation between this issue and the fact that we're running a replicated Tekton controller as explained [here](https://github.com/tektoncd/pipeline/issues/3404), but after looking into logs and historical data, I've figured out that the issue was already happening before we've replicated the controller. Also, the duplicated tasks are always being created by the same controller instance. One thing that came to me attention is that the duplicated tasks are being created in a Go routine that has a different traceid from the original ones:

|msg                                                                                 |knative.dev/key                   |knative.dev/traceid                 |pod                          |
|------------------------------------------------------------------------------------|----------------------------------|------------------------------------|-----------------------------|
|Creating a new TaskRun object rewards-ledger-run-mb4pl-lint-m964j                   |pipelines/rewards-ledger-run-mb4pl|990295d7-b79d-4353-ba75-20ba7df2945d|tekton-pipelines-controller-0|
|Creating a new TaskRun object rewards-ledger-run-mb4pl-unit-tests-zzfkw             |pipelines/rewards-ledger-run-mb4pl|990295d7-b79d-4353-ba75-20ba7df2945d|tekton-pipelines-controller-0|
|Creating a new TaskRun object rewards-ledger-run-mb4pl-integration-tests-62bwb      |pipelines/rewards-ledger-run-mb4pl|990295d7-b79d-4353-ba75-20ba7df2945d|tekton-pipelines-controller-0|
|Creating a new TaskRun object rewards-ledger-run-mb4pl-sachem-cb6l6                 |pipelines/rewards-ledger-run-mb4pl|990295d7-b79d-4353-ba75-20ba7df2945d|tekton-pipelines-controller-0|
|Creating a new TaskRun object rewards-ledger-run-mb4pl-toxic-combination-check-wrdn2|pipelines/rewards-ledger-run-mb4pl|990295d7-b79d-4353-ba75-20ba7df2945d|tekton-pipelines-controller-0|
|Creating a new TaskRun object rewards-ledger-run-mb4pl-build-kj4bg                  |pipelines/rewards-ledger-run-mb4pl|990295d7-b79d-4353-ba75-20ba7df2945d|tekton-pipelines-controller-0|
|Creating a new TaskRun object rewards-ledger-run-mb4pl-sachem-gdz6m                 |pipelines/rewards-ledger-run-mb4pl|568735de-6014-448a-a515-b41b591b6ed8|tekton-pipelines-controller-0|
|Creating a new TaskRun object rewards-ledger-run-mb4pl-toxic-combination-check-6rvqw|pipelines/rewards-ledger-run-mb4pl|568735de-6014-448a-a515-b41b591b6ed8|tekton-pipelines-controller-0|
|Creating a new TaskRun object rewards-ledger-run-mb4pl-build-dnqs2                  |pipelines/rewards-ledger-run-mb4pl|568735de-6014-448a-a515-b41b591b6ed8|tekton-pipelines-controller-0|
|Creating a new TaskRun object rewards-ledger-run-mb4pl-push-vs8qg                   |pipelines/rewards-ledger-run-mb4pl|58217b80-bbe2-4e93-af04-7eb8485626ff|tekton-pipelines-controller-0|
|Creating a new TaskRun object rewards-ledger-run-mb4pl-deploy-staging-br-rqnrc      |pipelines/rewards-ledger-run-mb4pl|804b004f-b2dd-49a2-beae-c2a14f9ac0bb|tekton-pipelines-controller-0|
|Creating a new TaskRun object rewards-ledger-run-mb4pl-deploy-staging-br-kzhcv      |pipelines/rewards-ledger-run-mb4pl|1561c9cb-0432-4599-8049-0f9724cf5d19|tekton-pipelines-controller-0|
|Creating a new TaskRun object rewards-ledger-run-mb4pl-deploy-prod-br-z7dpl         |pipelines/rewards-ledger-run-mb4pl|bddbfc00-64c6-406a-85c7-a231709ca946|tekton-pipelines-controller-0|

The above output is a piece of logs generated by the controller for a pipeline run with duplicated task runs. The tasks named sachem, toxic-combinations-check and build were duplicated. By looking at data, I confirmed that they started almost simultaneously in the same seconds as the original ones.

If you have ideas about how I could collect relevant information to help in the debugging process of this issue, I'd be very grateful.

# Expected Behavior
Task runs that make up a pipeline run must run once.
# Actual Behavior
Tekton is duplicating certain task runs randomly. 
# Steps to Reproduce the Problem
The issue seems to be a race condition. I've been debugging the problem in the last days, but I didn't find any pattern that help me to reproduce it. Around 10% of our pipeline runs are having this problem and looks like that there are no common characteristics among them. Some are complex pipelines with relations of dependency between task, some are very simple ones with a couple of tasks that run in parallel. 

# Additional Info
   
- Kubernetes version:

  **Output of `kubectl version`:**

  ```
Client Version: v1.19.3
Server Version: v1.18.9-eks-d1db3c
  ```

- Tekton Pipeline version: 0.18.1

**Comment by pritidesai** [comment]
@alan-ghelardi, @GregDritschler has documented his analysis in this [doc](https://docs.google.com/document/d/1AwBTnf4e-9XFXE3Wuh4XqUwUbptyCY4Jb9eb9J-wGtA/edit?ts=5fbbad23#) on similar issue, please check if it's applicable to the issue you are experiencing.

**Comment by alan-ghelardi** [comment]
Thank you @pritidesai. I've requested access to the doc.

**Comment by tnixa** [comment]
I'm hitting this same problem of duplicate taskruns from a single pipelinerun on my Openshift 4.6 cluster. I tried to recover by deleting all the pods and deployments in the `openshift-pipelines` namespace and then uninstalling/reinstalling the Openshift Pipelines operator but this did not resolve the problem. Can someone tell me how to recover from this problem? @GregDritschler

**Comment by tnixa** [comment]
My tekton is working again after following the guide below for uninstalling and then reinstalling:
https://medium.com/@nikhilthomas1/right-way-to-uninstall-openshift-pipelines-fromopenshift-4-x-fb2a7b7c492c

**Comment by mhubig** [comment]
I'm having the same issue here. Sometimes the task runs are duplicated. Not sure how to debug this further ... i've also requested access to the above document. I'll try reinstalling tekton and see if that helps.

**Comment by sbwsg** [comment]
@alan-ghelardi does this issue remain for you with more recent releases of Tekton?

**Comment by bobcatfish** [comment]
@alan-ghelardi and others, please re-open if you are still seeing this with more recent releases 🙏

**Comment by Rand01ph** [comment]
> @alan-ghelardi and others, please re-open if you are still seeing this with more recent releases 🙏

I have found this in version v0.25.0

**Comment by pritidesai** [comment]
Reopening as this is seen in recent releases 😞

PR #4361 must fix this issue 🤞
