### ISSUE TITLE
Use list options in pod informer

### ISSUE THREAD

**Issue by HeavyWombat** [tektoncd/pipeline#3561]
### Feature request

Currently, the pod informer seems to cache details about all pods in the cluster. Use the `WithTweakListOptions` function to tune the pod informer to only cache pods that are relevant for Tekton.

### Use case

We recently ran into a problem using Tekton with our [build operator](https://github.com/shipwright-io/build) in a multi-tenant  cluster setup. A component created a large amount of pods that each contained relatively large annotations. With almost 10000 completed pods in the system our Tekton controller pods started to consume a lot of memory. This eventually led to Kubernetes killing the Tekton controller pods. When they came back, they immediately started to consume all the available memory again. This could only be fixed by deleting completed pods with their large pod resource YAML from the system.

The problem seems to be the [Knative based pod informer cache](https://github.com/tektoncd/pipeline/blob/master/pkg/reconciler/taskrun/controller.go#L55) that is in use in Tekton. To reproduce the problem, I created a vanilla Kube 1.17 cluster with just Tekton and our build operator. In the idle state, there are roughly 40 pods in the system and the single Tekton controller uses around 20 MiB memory. I then created 2000 pods with each having 11 KiB worth of resource YAML through a random string that is stored in an annotation. For the tests, I used relatively moderate load as we learned that with too many pods and large YAML content the underlying `etcd` could end up in a weird state. With 2000 pods alone the Tekton controller tripled the memory usage without any work to be done. A Tekton controller pod restart quickly led to roughly the same memory utilization again.

In order to verify the theory, I changed the `v0.17.1` based Tekton controller we use to [create a custom pod informer](https://github.com/HeavyWombat/pipeline/commit/470531447264d16713074d60eb8d3f5175115b00) using the `client-go` packages rather than using the Knative based packages. It is using the `managed-by` label to select only pods that I assume to be relevant for Tekton. Running the test with this patched version led to no measurable increase in the memory usage. Ideally, I would have liked to tweak the Knative based pod informer that is in use to apply the list options, but I failed to find a suitable entry point to implement this.

We might have a special use case here, but I think generally speaking it would be beneficial for the memory usage of the Tekton controller pods if they only cache details about pods that are managed by Tekton.

This is why I would to reach out to you to ask for feedback on this idea. Thanks in advance.

**Comment by zhangtbj** [comment]
Another update is in the issue https://github.com/knative/serving/issues/10098

To see if we can add `TweakFilterOption` in the knative pkg. If it is accepted, maybe Tekton can also leverage in the new release.

FYI

**Comment by zhangtbj** [comment]
Here is any update from our another team: try to label selector for the context, so the upstream component can define the ctx with label setting by using `TweakFilterOption`:
https://github.com/knative/serving/issues/10098#issuecomment-738553604

This is the PR: https://github.com/knative/pkg/pull/1940

cc @afrittoli

**Comment by qu1queee** [comment]
@vdemeester @afrittoli any opinions on this issue?

**Comment by zhangtbj** [comment]
The PR https://github.com/knative/pkg/pull/1940 is merged in Knative pkg repo.

If no other objection, Once the new Knative pkg release is published, I will submit a PR on Tekton side to use the new `FilteredInformer` in Knative pkg and use Tekton selector for the Pod informer cache.

**Comment by zhangtbj** [comment]
This issue is solved by the PR: https://github.com/tektoncd/pipeline/pull/3725

Hi @HeavyWombat , I think we can close this issue.

Thanks!

**Comment by HeavyWombat** [comment]
Yes, it was solved with #3725.
