### ISSUE TITLE
docker image connot run properly under Task context

### ISSUE THREAD

**Issue by zhangyunlin** [tektoncd/pipeline#3565]
I made an helm image to build  and push charts package to registry, and helm push plugin has been installed. when I run this image with docker run command, the helm push command can work properly. But when I use the image uder Tekton pipeline Task yaml, the helm push command cannot work, and the helm push plugin has already installed in /root/.local/share/helm/plugins/helm-push.git/bin dir.
# Expected Behavior
the helm push command could work.

# Actual Behavior
when run helm push command, the follewing message received:
Error: unknown command "push" for "helm"

# Steps to Reproduce the Problem

1. build a helm image, and intall helm push plugin
2. use “docker run -it ... /bin/bash” command to run the image, and run "helm push"command
3. use the image in Task yaml template, and run Task, the error message received

# Additional Info

- Kubernetes version: v1.18.3

  **Output of `kubectl version`:**

 ```
  (paste your output here)
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**
Client version: 0.10.0
Pipeline version: v0.18.1

**Comment by afrittoli** [comment]
@zhangyunlin thank for your report. 
Could you provide details about the error that you're getting? 
Could you share the docker file of your image?

**Comment by zhangyunlin** [comment]
@afrittoli thks for your reply, the Dockerfile as follow:
`FROM centos:7.9.2009

#ENV LC_ALL zh_CN.utf8
ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en' LC_ALL='en_US.UTF-8'

#安装必要软件
RUN yum install -y tzdata openssl curl wget ca-certificates fontconfig gzip tar git \
    && yum update -y; yum clean all

#设置时区
ENV  TIME_ZONE Asia/Shanghai
RUN ln -sf /usr/share/zoneinfo/${TIME_ZONE} /etc/localtime

#安装kubectl
ARG kubectlVERSION=v1.18.3
#COPY kubectl /usr/local/bin/kubectl
RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/${kubectlVERSION}/bin/linux/amd64/kubectl && \
    chmod +x ./kubectl && \
    mv ./kubectl /usr/local/bin/kubectl

#安装helm3
ARG helmVERSION=v3.2.0
#COPY helm /usr/local/bin/helm
RUN curl -LO https://get.helm.sh/helm-${helmVERSION}-linux-amd64.tar.gz && \
    tar -zxf helm-${helmVERSION}-linux-amd64.tar.gz && \
    mv ./linux-amd64/helm /usr/local/bin/helm && \
    rm -rf linux-amd64 && \
    rm -rf helm-${helmVERSION}-linux-amd64.tar.gz
#安装helm push插件
RUN helm plugin install https://github.com/chartmuseum/helm-push.git
#COPY .helm /root/.helm
#ADD helm-push.tar.gz /root/.helm/plugins/`
