### ISSUE TITLE
[flaky] TestReconcile_FeatureFlags Unit test failed in pipeline nightly job

### ISSUE THREAD

**Issue by savitaashture** [tektoncd/pipeline#3587]
# Expected Behavior
Pipeline nightly unit test passes

# Actual Behavior
Pipeline nightly unit test failed:
PipelineRun: https://dashboard.dogfooding.tekton.dev/#/namespaces/default/pipelineruns/pipeline-release-nightly-fjmmj?pipelineTask=unit-tests&step=unit-test

Failure:
Testcase: TestReconcile_FeatureFlags/disable-home-env-overwrite

```
    taskrun_test.go:754: Pod spec doesn't match, (-want, +got):   v1.PodSpec{
          	Volumes:        {{Name: "tekton-internal-workspace", VolumeSource: {EmptyDir: &{}}}, {Name: "tekton-internal-home", VolumeSource: {EmptyDir: &{}}}, {Name: "tekton-internal-results", VolumeSource: {EmptyDir: &{}}}, {Name: "tekton-internal-tools", VolumeSource: {EmptyDir: &{}}}, ...},
          	InitContainers: {{Name: "place-tools", Image: "override-with-entrypoint:latest", Command: {"/ko-app/entrypoint", "cp", "/ko-app/entrypoint", "/tekton/tools/entrypoint"}, VolumeMounts: {{Name: "tekton-internal-tools", MountPath: "/tekton/tools"}}, ...}},
          	Containers: []v1.Container{
          		{
          			... // 5 identical fields
          			Ports:   nil,
          			EnvFrom: nil,
          			Env: []v1.EnvVar{
        + 				{Name: "HOME", Value: "/tekton/home"},
          				{Name: "foo", Value: "bar"},
          			},
          			Resources:    {Requests: {s"cpu": {s: "0", Format: "DecimalSI"}, s"ephemeral-storage": {s: "0", Format: "DecimalSI"}, s"memory": {s: "0", Format: "DecimalSI"}}},
          			VolumeMounts: {{Name: "tekton-internal-tools", MountPath: "/tekton/tools"}, {Name: "tekton-internal-downward", MountPath: "/tekton/downward"}, {Name: "tekton-creds-init-home-9l9zj", MountPath: "/tekton/creds"}, {Name: "tekton-internal-workspace", MountPath: "/workspace"}, ...},
          			... // 12 identical fields
          		},
          	},
          	EphemeralContainers: nil,
          	RestartPolicy:       "Never",
          	... // 29 identical fields
          }
```

# Additional Info
Test passed locally
Tried on minikube as well as dogfooding cluster several time
```
go test -race -cover -v ./...
```

- Kubernetes version:

  **Output of `kubectl version`:**

```
  kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-gke.401", GitCommit:"eb94c181eea5290e9da1238db02cfef263542f5f", GitTreeState:"clean", BuildDate:"2020-09-09T00:57:35Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:
```
tkn version
Client version: 0.13.1
Pipeline version: v0.18.1
Triggers version: v0.8.1
Dashboard version: v0.11.0

```

**Comment by savitaashture** [comment]
Cannot reproduce the issue locally
Will keep an eye closely for few days if it doesn't reproduce on nightly will close it

**Comment by sbwsg** [comment]
Looking at the logs for the test we see that, first, the configmap store does report that the feature flags were updated correctly:

```
2020-12-03T02:06:16.487Z	INFO	TestReconcile_FeatureFlags/disable-home-env-overwrite.config-store	configmap/store.go:154	defaults/features/artifacts config "feature-flags" config was added or updated: &config.FeatureFlags{DisableHomeEnvOverwrite:true, DisableWorkingDirOverwrite:false, DisableAffinityAssistant:false, DisableCredsInit:false, RunningInEnvWithInjectedSidecars:true, RequireGitSSHSecretKnownHosts:false, EnableTektonOCIBundles:false}
```

This log line comes from https://github.com/tektoncd/pipeline/blob/d702ca1cef1d156887e9306dd3739690b0ceb599/vendor/knative.dev/pkg/configmap/store.go#L154 which is executed on a line just before an atomic `Store` operation is performed with the updated data.

Note `DisableHomeEnvOverwrite:true` in the output.

Some amount of time later (not possible to tell how long I don't think; the test's log line isn't timestamped) we then see the erroneous diff reported:

```
          			Env: []v1.EnvVar{
        + 				{Name: "HOME", Value: "/tekton/home"},
          				{Name: "foo", Value: "bar"},
          			},
```

What this suggests to me is that our code did not see the updated configmap from the passed context in https://github.com/tektoncd/pipeline/blob/d702ca1cef1d156887e9306dd3739690b0ceb599/pkg/apis/config/store.go#L47 

So perhaps there's a race somewhere between the atomic store of the updated config and the execution of the Reconcile method happening in the test?

**Comment by sbwsg** [comment]
@bobcatfish described a similar-sounding problem and potential resolution in https://github.com/tektoncd/pipeline/issues/2815#issuecomment-733207368

**Comment by bobcatfish** [comment]
Created https://github.com/tektoncd/pipeline/issues/3720 to describe what I _think_ is the root cause of this and some of our other flakey tests.
