### ISSUE TITLE
How to use different passwords in taskrun or pipeline

### ISSUE THREAD

**Issue by tom20180101** [tektoncd/pipeline#3598]
When I was writing taskrun and pipelinerun, the password of my gitlab was different from the password of harbor. I don't know how to use it. I only saw that gitlab and docker used the same password in the document. Does anyone know how to use it, can you give me an example, thanks a lot

**Comment by sbwsg** [comment]
Hi @tom20180101, I don't have enough context to answer your question yet.

> When I was writing taskrun and pipelinerun, the password of my gitlab was different from the password of harbor. I don't know how to use it.

Could you clarify what you are using?  It it a Catalog Task?  Which one?  What does your TaskRun YAML look like?

> I only saw that gitlab and docker used the same password in the document. 

Which document are you referring to and where in that document does it describe using passwords?

> Does anyone know how to use it, can you give me an example, thanks a lot

- What platform are you running on?  (bare metal? minikube? gke? openshift?  eks?  aks?)
- What version of Tekton Pipelines are you using?

**Comment by tom20180101** [comment]
> Hi @tom20180101, I don't have enough context to answer your question yet.
> 
> > When I was writing taskrun and pipelinerun, the password of my gitlab was different from the password of harbor. I don't know how to use it.
> 
> Could you clarify what you are using? It it a Catalog Task? Which one? What does your TaskRun YAML look like?
> 
> > I only saw that gitlab and docker used the same password in the document.
> 
> Which document are you referring to and where in that document does it describe using passwords?
> 
> > Does anyone know how to use it, can you give me an example, thanks a lot
> 
> * What platform are you running on?  (bare metal? minikube? gke? openshift?  eks?  aks?)
> * What version of Tekton Pipelines are you using?

sorry，i use kubernetes 1.18.8  and pipelines version is  v0.18.1  . maybe i'm not clear，let me explain. i have a gitlab and  harbor，they all have to be authenticated to login, and their login account and password are different.  if i want clone code from gitlab , make mirror ,push image to harbor in same pipelinerun or taskrun , i must login, but i don't know how to achieve it in the same pipelinerun or taskrun . I only know the secret and serviceaccount  association that contains the only one account and password.

**Comment by nikhil-thomas** [comment]
@tom20180101 the **Understanding credential section** section in https://tekton.dev/docs/pipelines/auth/ might help you.

**Comment by tom20180101** [comment]
> https://tekton.dev/docs/pipelines/auth/
thanks a lot ,I've already seen it , I changed the accounts and passwords of Git and Harbor, and now their accounts and passwords are the same. so i can  achieved it. but I still don't know how to implement it with different Git and Harbor accounts.

**Comment by nikhil-thomas** [comment]
you can try 2 things
1. create separate secrets, and list them in the serviceaccount
2. mount the secretes directly in you Tasks on a path where you need it, like how we would do it in a Kubernetes Pod. 

The Taskruns are fundamentally pods which execute the steps (containers) in sequence, instead of starting the steps (containers) all at once.

**Comment by tom20180101** [comment]
> you can try 2 things
> 
> 1. create separate secrets, and list them in the serviceaccount
> 2. mount the secretes directly in you Tasks on a path where you need it, like how we would do it in a Kubernetes Pod.
> 
> The Taskruns are fundamentally pods which execute the steps (containers) in sequence, instead of starting the steps (containers) all at once.

ok，I'll try. thanks

**Comment by tom20180101** [comment]
> > you can try 2 things
> > 
> > 1. create separate secrets, and list them in the serviceaccount
> > 2. mount the secretes directly in you Tasks on a path where you need it, like how we would do it in a Kubernetes Pod.
> > 
> > The Taskruns are fundamentally pods which execute the steps (containers) in sequence, instead of starting the steps (containers) all at once.
> 
> ok，I'll try. thanks

i find this in pipelineruns  , i think this is useful 

spec:
  serviceAccountName: sa-1
  serviceAccountNames:
    - taskName: build-task
      serviceAccountName: sa-for-build
