### ISSUE TITLE
pipelineRun serviceAccount not restricting securityContexts on OpenShift

### ISSUE THREAD

**Issue by namloc2001** [tektoncd/pipeline#3625]
# Expected Behavior
I expect the serviceAccount associated with the pipelineRun to have SCC controls applied to it. If it is a new serviceAccount (or any serviceAccount that hasn't been explicitly granted alignment to other SCCs elsewhere), I expect these to be in line with the restricted SCC.

# Actual Behavior
I am deploying a pipelineRun script via `oc create -f pipeline-run.yaml` after having logged into the cluster with my (cluster-admin) personal account. Config is:
```
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: demo-sysdig-inline-permission-
spec:
  pipelineRef:
    name: sysdig-pipeline
  podTemplate:
    securityContext:
      runAsUser: 1005
  serviceAccountName: 'new-pipelinerunner'
  resources:
  - name: container-image
    resourceRef:
      name: container-image
  taskRunSpecs:
    - pipelineTaskName: sysdig-scan-inline-new
      taskServiceAccountName: 'new-pipelinerunner'
      taskPodTemplate:  
        securityContext:
          runAsUser: 1001
          fsGroup: 1001
```
The resultant pod is deployed with UID=1005, however I have not granted the `new-pipelinerunner` serviceAccount the capabilities of any SCCs, therefore by default it should be only able to function in line with the restricted SCC settings, one of which is that the runAsUser is the project UID range (`openshift.io/sa.scc.uid-range: 1005450000/10000`).

And yet if I run the `id` command on my pipeline pod, I get:
```
oc exec -it demo-sysdig-inline-permission-gzwn9-sysdig-scan-8r5hx-pod-52rbz -- sh -c "id"
uid=1005(1005) gid=0(root) groups=0(root)
```

# Steps to Reproduce the Problem
1. Create a serviceAccount on OpenShift in the tekton-pipelines namespace:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: new-pipelinerunner
```

2. Run any pipelineRun with this serviceAccount attached, either do or don't specify podTemplate.securityContext on the pipelineRun. 

3. With the pod running, confirm the UID of the user, it should be in the project range (`oc exec -it <pod-name> [-c container_name] -- sh -c "id"`).

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.2+853223d", GitCommit:"853223d", GitTreeState:"clean", BuildDate:"2020-10-14T15:02:59Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

  **Output of `oc version`:**
```
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server <I've redacted>
kubernetes v1.16.2+853223d
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
v0.15.2
```

This is running on IBM Cloud Red Hat (ROKS), version: 4.3.40_1546:
```
System Info:
 Kernel Version:                                         3.10.0-1160.6.1.el7.x86_64
 OS Image:                                               Red Hat
 Operating System:                                       linux
 Architecture:                                           amd64
 Container Runtime Version:                              cri-o://1.16.6-18.rhaos4.3.git538d861.el7
 Kubelet Version:                                        v1.16.2+853223d
 Kube-Proxy Version:                                     v1.16.2+853223d
```

**Comment by namloc2001** [comment]
**Update:** it would appear that my user is influencing the SCC being used as the `anyuid` SCC is being prioritised over `restricted` SCC as, in line with what is explained here:
> By default, the anyuid SCC granted to cluster administrators is given priority in their SCC set. This allows cluster administrators to run pods as any user by without specifying a RunAsUser on the pod’s SecurityContext. The administrator may still specify a RunAsUser if they wish.

(https://docs.openshift.com/container-platform/3.6/architecture/additional_concepts/authorization.html#scc-prioritization)

I've never encountered this before because I have always created deployments which create pods for me, and do this via Helm as well. If I create a deployment, which in turn creates my pod, the serviceAccount on the deployment dictates the SCC selected and thus will use `restricted` SCC unless I permit the serviceAccount access to a less restrictive SCC.

So my question is can Tekton be configured to use the same relationship deployment serviceAccount has over pod for SCCs? Can the pipelineRun (onto which we declare a serviceAccount) serve as the "deployment" to create the pod and thus the pipelineRun serviceAccount dictates the SCC selected, rather than this changing based on the human user that instigated it?

**Comment by gabemontero** [comment]
Hey @namloc2001 

Upstream tekton would never employ such openshift/SCC correlations 

That said, you ought to engage the openshift pipelines team downstream (we have the same set of folks working both upstream in https://github.com/tektoncd as well as downstream in openshift pipelines.

Reopen this issue at https://github.com/openshift/tektoncd-pipeline-operator and we can explore these type of integrations.  If it turns out some subset of a solution would benefit from tweaks here in https://github.com/tektoncd/pipelines, the team will work with the upstream community to see if there is general agreement).

Otherwise, at first blush, I could see a (potentially optional) openshift pipelines admission webhook(s) possibly achieving what you want.

@vdemeester @siamaksade @sbose78 FYI

**Comment by gabemontero** [comment]
fwiw I would close this out in favor of a https://github.com/openshift/tektoncd-pipelines-operator issue, but don't have permission to do so

**Comment by vdemeester** [comment]
> Reopen this issue at https://github.com/openshift/tektoncd-pipeline-operator and we can explore these type of integrations. If it turns out some subset of a solution would benefit from tweaks here in https://github.com/tektoncd/pipelines, the team will work with the upstream community to see if there is general agreement).

Actually, this would work in `tektoncd/operator` too now, because we have some platform specific pieces there (for openshift, …)

**Comment by namloc2001** [comment]
@gabemontero @vdemeester happy to reopen this at https://github.com/openshift/tektoncd-pipeline-operator but will this not also impact K8s as the relationship between deployment creating pod and user creating the pod is surely subject to the same implications regarding PSPs (and SCCs in OpenShift)?

**Comment by gabemontero** [comment]
> @gabemontero @vdemeester happy to reopen this at https://github.com/openshift/tektoncd-pipeline-operator I believe this would also impact K8s as the relationship between deployment creating pod and user creating the pod is surely subject to the same implications regarding PSPs (and SCCs in OpenShift)?

Maybe .... yeah let's leave this open for now then here, and as we study the scenario further, if we can translate what you said back to more precise PSP terms, we can see.

But remember, both the current SCC and PSP contracts are "if either requesting user or SA has permissions, it is allowed".

So I suspect to employ policy such that only the SA's permissions count translates into either baked in additional controls like you note with deployment/pod, or additional validation admission webhooks, where in tekton's case, there has been an explicit choice to not provide additional admission webhooks out of the box, but defer to policy engines like OPA to construct policies that enforce such behavior.

We are currently trying to wrap our hand around such things in a Tekton Enhancement Proposal I currently have up at https://github.com/tektoncd/community/pull/152 ... but the high level gist there is the help tekton users consume thrid party policy engines to achieve goals such as this, as isolate such things from the tekton project itself.

This could be such a scenario.  The SAR example in my TEP could be a step for this, though you would also have to map the pod security context to an analogous pod security policy or scc.  Then do a SAR with the use verb, the SCC/PSP, where only the service account is used as the subject for the SAR instead of the requesting user.  Involved / tricky for sure.

We can see about crafting such OPA examples as part of the catalog of OPA/Tekton examples we are trying to curate as part of this issue.

More "baked in" or "provided" solutions (like say providing an admission webhook along with a tekton deployment that handles all this like a black box) would be something to discuss in a downstream tekton provider solution / issue.

**Comment by namloc2001** [comment]
@gabemontero (or anyone else!) is there documentation that explains which SA does what in tekton pod creation (or would you please be able to confirm it)? I've been investigating further and have created a serviceAccount without any access to SCCs (other than the default restricted SCC allocation) to perform the pipelineRun creation via.
```
kind: ServiceAccount
apiVersion: v1
metadata:
  name: tekton-pipelinerunner
  namespace: tekton-pipelines
```

I've provided the following role and roleBinding:
```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-pipelinerunner
  namespace: tekton-pipelines
rules:
  - verbs:
      - get
      - watch
      - create
      - watch
      - list
    apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
      - taskruns
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-pipelinerunner
  namespace: tekton-pipelines
subjects:
  - kind: ServiceAccount
    name: tekton-pipelinerunner
    namespace: tekton-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-pipelinerunner
```

I then perform:
```
oc create -f taskrun.yaml --as=system:serviceaccount:tekton-pipelines:tekton-pipelinerunner
```
or
```
oc create -f pipelinerun.yaml --as=system:serviceaccount:tekton-pipelines:tekton-pipelinerunner
```

and I am ending up with a pod being created that is using `anyuid` SCC:
```
oc get pod demo-sysdig-task-cksb9-pod-pnptx -o yaml | grep scc
    openshift.io/scc: anyuid
```
The serviceAccount specified in the taskRun and pipelineRun is another basic account that has been granted no rolebinding, nor added to SCCs (other than default `restricted`).

Given that `tekton-pipelinerunner` can only create taskRuns or pipelineRuns, something else is creating the pod and so I'm wondering if the "thing" creating the pod is therefore having its permissions applied to SCC selection.

When I check which accounts can use `anyuid` I see the following (along with human user IAM accounts I've removed from display):
```
oc adm policy who-can use scc anyuid
Namespace: tekton-pipelines
Verb:      use
Resource:  securitycontextconstraints.security.openshift.io

Users:  system:admin
        system:serviceaccount:tekton-pipelines:tekton-dashboard

Groups: system:cluster-admins
        system:masters
```
and when I do `oc get scc anyuid -o yaml` I see:
```
groups:
- system:cluster-admins
users:
- system:serviceaccount:tekton-pipelines:tekton-pipelines-controller
- system:serviceaccount:tekton-pipelines:tekton-pipelines-webhook
```

As you can see here, the obvious candidates are tekton-dashboard, tekton-pipelines-controller and tekton-pipelines-webhook or an account that is granted system:admin or system:cluster-admin.

tekton-pipelines-controller and tekton-pipelines-webhook were added to anyuid scc in line with the instructions [here](https://github.com/tektoncd/pipeline/blob/master/docs/install.md#installing-tekton-pipelines-on-openshift):
>Set up the namespace (project) and configure the service account:
>```
>oc new-project tekton-pipelines
>oc adm policy add-scc-to-user anyuid -z tekton-pipelines-controller
>oc adm policy add-scc-to-user anyuid -z tekton-pipelines-webhook
>```

tekton-pipelines-controller is only granted list & watch pods via tekton-pipelines-controller-cluster-access ClusterRole & ClusterRoleBinding.

tekton-pipelines-webhook isn't granted any verbs on pods.

tekton-dashboard is the subject in a number RoleBindings/ClusterRoleBindings:
 - tekton-dashboard-pipelines (roleBinding)
 - tekton-dashboard-dashboard (roleBinding)
 - tekton-dashboard-triggers (roleBinding)
 - tekton-dashboard-tenant (ClusterRoleBinding)
 - tekton-dashboard-extensions (ClusterRoleBinding)

None of which are granted permissions over pods. And it is via ClusterRole `tekton-dashboard-backend` that is is permitted to use "securitycontextconstraints" - but I presume this is related to the deployment of dashboard itself.

Another role I see (via https://storage.googleapis.com/tekton-releases/pipeline/latest/release.notags.yaml) is tekton-pipelines-controller-tenant-access, which can get, list, create, update, delete, patch and watch pods, secrets, events, serviceAccounts, configmaps etc. But it's not referenced in anyuid SCC...

**Comment by gabemontero** [comment]
@namloc2001 - I'll need to go back and parse your entire comment (won't have time today), but I did catch this piece I can answer (which I think is you ultimate question  there at the end):  when Tekton API are ultimately translated into pods, two SAs factor into the PSP/SCC calculations on permissions.

1) the SA associated with TaskRun / PipelineRun ... if one is not specified, then the `default` SA in the namespace of the TaskRun/PipelineRun is used
2) the SA of the controller as you have surmised (it is the requesting user)

Now, wrt instructions and permissions, some of this is in flight (in fact @sbose74 made recent changes downstream for this, and @vdemeester is in the process of updating some upstream doc / catalog), long term you should *NOT* be told to add the `anyuid` SCC to the controller SA.  You should only be using adding non restricted permissions like anyuid SCC to SA's associated with your PipelineRuns and TaskRuns

In fact, the latest levels of downstream openshift pipelines OLM stuff now removes anyuid from the controller SA, and adds it the the `pipelines` SA that OLM operator creates.

@vdemeester and @sbose74 can clarify which versions of all that are where.

**Comment by namloc2001** [comment]
Thanks @gabemontero that is really useful. I'm still finding my way around upstreams and downstreams - I can't find the changes made by @sbose74 (nor the username), could you please point me at them (and those being made by @vdemeester) so I can see what is being changed (and potentially provide some input if I can be of use)? Thanks in advance.

**Comment by vdemeester** [comment]
@namloc2001 https://github.com/openshift/tektoncd-pipeline-operator/pull/503 and https://github.com/openshift/tektoncd-pipeline-operator/pull/504 for the operator (this is being ported to `tektoncd/operator`).

**Comment by namloc2001** [comment]
Thanks @vdemeester. Is there a reason why privileged wasn't downgraded to restricted? That way the pipeline pods are implemented with minimal SCC permissions and if additional permissions are required above restricted SCC, we apply these to the SA we attach to the pipeline- or taskRun? With the current method, I don't believe I can deploy using the restricted SCC.

**Comment by gabemontero** [comment]
Hey @namloc2001 and @vdemeester  .... I'm circling back to both this and the related downstream issues ... hitting this one first.

FWIW, and perhaps you all were already aware now, though based on @namloc2001 's https://github.com/tektoncd/pipeline/issues/3625#issuecomment-744331334 maybe that was not the case back then,

But I was able to run master branch of tektoncd/pipelines where I manually assigned the `restricted` SCC to the controller and webhook SA's after just creating the namespace and SAs, but before creating any of the other config.

The controllers came up in the same state I observed when the `restricted` SCC was *NOT* assigned to those SAs.  And I was able to create simple Tasks and TaskRuns when restricted was applied.

Note @namloc2001, as is always the case when running tektoncd/pipelines in openshift, I have to comment out https://github.com/tektoncd/pipeline/blob/bff0ba00ed0c1d3461947cdd02d5fb7e63c04df7/config/controller.yaml#L118-L119 and https://github.com/tektoncd/pipeline/blob/bff0ba00ed0c1d3461947cdd02d5fb7e63c04df7/config/webhook.yaml#L109-L110 as well, though that is the case regardless if you are using the `restricted` SCC or not (in fact, you need to have `anyuid` minimally to manually set those fields vs. deferring to openshift and cri-o setting those for you).

Also note @namloc2001 the pipeline operator removes those lines when deploying on openshift

**Comment by sbose78** [comment]
> But I was able to run master branch of tektoncd/pipelines where I manually assigned the restricted SCC to the controller and webhook SA's after just creating the namespace and SAs, but before creating any of the other config.

nice!

**Comment by namloc2001** [comment]
Great news. I've asked [this question](https://github.com/openshift/tektoncd-pipeline-operator/pull/492#issuecomment-756712883)  for clarification on PR492. Looks like things are moving in the right direction.
