### ISSUE TITLE
Feature request: Add a condition to a pipeline run to detect completion

### ISSUE THREAD

**Issue by jceresini** [tektoncd/pipeline#3645]
### Feature request

I'd like to see a new condition on pipelineruns that indicates if they are completed. I'd like this to be boolean. Right now to see if a pipelinerun is complete, i need to check if the `Succeeded` condition is either `True` or `False`. `kubectl wait` doesn't handle multiple possible values for a condition, it defaults to true or optionally accepts a desired value.

### Use case

I'd like to use `kubectl wait --for=condition` to wait for a pipelinerun to complete. The only condition exposed by tekton is `Succeeded`. I could use `kubectl wait --for=condition=Succeeded --timeout=10m`, but if it fails in the first 5 seconds, my code will wait 10 minutes for that wait to timeout (the value in my example), and then i need to see if it failed or if its still running.

For my use case, i had to write my own shell functions to check for completion, but using `kubectl wait...` is desired. Example shell functions:

```bash
tkn_pr_status() {
  namespace=$1
  name=$2
  kubectl -n $namespace get pipelinerun $name -o jsonpath='{.status.conditions[?(@.type == "Succeeded")].status}'
}

tkn_pr_done () {
  status=$(tkn_pr_status "$@")
  [ "$status" == "True" ] || [ "$status" == "False" ]
}

function tkn_pr_wait {
  # usage: wait_for_pr <timeout_secs> <namespace> <name>
  timeout=$(($1 + $(date +%s)))
  shift

  while :; do
    if [ $(date +%s) -gt $timeout ]; then
        echo "Timeout exceeded waiting for pipeline run to complete"
        return 1
    fi

    if tkn_pr_done "$@"; then
        echo "Pipelinerun has finished"
        return 0
    fi

    echo "Waiting..."
    sleep 30
  done
}
```

**Comment by vdemeester** [comment]
I think this could also be implemented on `tkn`.

cc @tektoncd/core-maintainers @tektoncd/cli-maintainers

**Comment by jceresini** [comment]
/remove-lifecycle stale

This is a pretty standard way to track completion of jobs/tasks/etc in kubernetes. As an application that runs on kuberenetes, it would be reasonable to expect tekton to work with the native kubernetes tools. 

https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#wait
