### ISSUE TITLE
Support "git-init" for arm32v7 platform

### ISSUE THREAD

**Issue by atmosx** [tektoncd/pipeline#3647]
# Expected Behavior

I would expect the image to run properly, as all other resources worked with minimal effort.

# Actual Behavior

```
build step "step-clone" is pending with reason "rpc error: code = NotFound  desc = failed to pull and unpack 
image \"gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init@sha256:db3e7431b11917f21c6978f478298dcb5b2b4048e9f1ec5c0246d72b66c820c7\":
failed to unpack image on snapshotter overlayfs: no match for platform in 
manifest sha256:db3e7431b11917f21c6978f478298dcb5b2b4048e9f1ec5c0246d72b66c820c7: not found"
```

# Steps to Reproduce the Problem

```
root@rpi3-node2:~# docker run --rm -it gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init
Unable to find image 'gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:latest' locally
latest: Pulling from tekton-releases/github.com/tektoncd/pipeline/cmd/git-init
docker: no matching manifest for unknown in the manifest list entries.
```

# Additional Info

```
root@rpi3-node2:~# head -n 9 /proc/cpuinfo
processor	: 0
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4
```

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6+k3s1", GitCommit:"6f56fa1d68a5a48b8b6fdefa8eb7ead2015a4b3a", GitTreeState:"clean", BuildDate:"2020-07-16T20:44:01Z", GoVersion:"go1.13.11", Compiler:"gc", Platform:"linux/arm"}
```

- Tekton Pipeline version:

```
tkn version
Client version: 0.14.0
Pipeline version: v0.19.0
Triggers version: v0.10.2
Dashboard version: v0.12.0
```

The installation is k3s running on rpi3 arm32v7 with containerd:
```
 crictl version
Version:  0.1.0
RuntimeName:  containerd
RuntimeVersion:  v1.3.3-k3s2
RuntimeApiVersion:  v1alpha2
```

~It's not clear to me if arm32v7 is supported for all images. I can see the platform in the Makefile but did not dig deeper yet.~

update: I cross compiled the `git-init` binary on macOS intel, put it in a container and works fine. I'm guessing there's something missing in the CI system.

**Comment by vdemeester** [comment]
We are using `ko` during release to build image, with `--platform=all`. This means it will build for all platform the base image supports. Because we are using `baseImageOverrides` (see https://github.com/tektoncd/pipeline/blob/master/.ko.yaml#L6), this means we need to build and publish `gcr.io/tekton-nightly/github.com/tektoncd/pipeline/build-base:latest` for all platform.

/cc @afrittoli

**Comment by vdemeester** [comment]
So quick update on this, for now, we do not build (nor support) arm32v7 for pipeline. But this issues, thus, it is still open
/remove-lifecycle stale

**Comment by vdemeester** [comment]
/remove-lifecycle rotten
Might be fixed by https://github.com/tektoncd/pipeline/pull/4758
