### ISSUE TITLE
Allow task results to be published on failure

### ISSUE THREAD

**Issue by jmcshane** [tektoncd/pipeline#3649]
### Feature request

Update the taskrun status calculation to provide all the task results that have been calculated in the output

### Use case

For scans and tests that may fail, it may be helpful to publish scan failure results as a task result before erroring out the build. Then both successful and error cloud events can be parsed to locate the scan information and provide that back as a status.

The code that currently filters that out is here: https://github.com/tektoncd/pipeline/blob/master/pkg/pod/status.go#L162. Is this if statement necessary? Could that logic be removed to provide results even in case of failure?

**Comment by vincent-pli** [comment]
@jmcshane 
Already has discussion here: https://github.com/tektoncd/pipeline/issues/3439
