### ISSUE TITLE
Question: Does tekton track the success/failure of cronjobs triggered by it

### ISSUE THREAD

**Issue by yashvardhan-kukreja** [tektoncd/pipeline#3650]
Seemingly, tekton does not have any dedicated support for "running" cronjobs. (It can only trigger them apparently but not be responsible for running them periodically per se) (correct me if I am wrong).
The way it looks here - https://github.com/tektoncd/triggers/pull/162 ,
one can setup a "trigger" via tekton for starting the execution of a cronjob but still, the cronjob runs and re-runs as a responsibility of kubernetes (apiVersion: batch/v1beta1).

(**Question**) I wanted to know whether tekton can keep track of and display (say, on my tekton dashboard) the cronjobs (triggered initially by tekton only) about how many times they succeeded or failed or ran?

**For example**, say a tekton pipeline of mine triggered a cronjob yesterday and since then, that cronjob ran 30 times of which 20 times it succeeded and 10 times it failed.

So, I just wanted to confirm that does tekton track that info and is it capable of displaying me these stats of the cronjob on my tekton dashboard or not?

**Comment by vincent-pli** [comment]
@yashvardhan-kukreja 
You can leverage [custom task](https://github.com/tektoncd/pipeline/blob/master/docs/runs.md) to implements it.

**Comment by dibyom** [comment]
> one can setup a "trigger" via tekton for starting the execution of a cronjob but still, the cronjob runs and re-runs as a responsibility of kubernetes (apiVersion: batch/v1beta1).

It's the other way around -- you configure a CronJob to call a Trigger at specific intervals, the Trigger then triggers a pipelinerun.
