### ISSUE TITLE
Can I set remove old log automatically?

### ISSUE THREAD

**Issue by Hokwang** [tektoncd/pipeline#3651]
### Feature request
Hi,

I installed tekton pipeline, triggers, dashboard, and
create one task, one pipeline, one trigger,
and it runs over 7000 times during 1 week.

It makes kubernetes cluster saves too many logs,
and don't know exactly but also api-server's something.

So I wonder tekton has a old(or over specific number of) log remove automatically feature. 

### Use case

user who run pipeline, task in enterprise level need this feature.

**Comment by chmouel** [comment]
We are discussing this in https://github.com/tektoncd/catalog/pull/572
