### ISSUE TITLE
release.yaml is conflicted

### ISSUE THREAD

**Issue by gaoyajun01** [tektoncd/pipeline#3670]
release.yaml is conflicted
![image](https://user-images.githubusercontent.com/71871477/104113752-8b482580-5337-11eb-8c97-c65c227c392f.png)

kubectl apply -f https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.19.0/release.yaml

**Comment by sbwsg** [comment]
Thanks for the issue report @gaoyajun01 - those are [YAML anchors](https://blog.daemonl.com/2016/02/yaml.html).  Not artifacts of a merge conflict.
