### ISSUE TITLE
git clone error

### ISSUE THREAD

**Issue by bibi520** [tektoncd/pipeline#3672]
my tekton version
![image](https://user-images.githubusercontent.com/42456284/104154012-bfe2dc80-541e-11eb-8a78-1b01e08b41d7.png)

ERROR
![image](https://user-images.githubusercontent.com/42456284/104154048-de48d800-541e-11eb-8df9-caf01d988b8b.png)

It's been working fine and all of a sudden there's this error and there's no problem pulling code from other projects

**Comment by sbwsg** [comment]
The git error says that one of the submodules in your repo isn't configured with a valid URL.

Can you try cloning the repo locally and running `git submodule init`?  What happens?

Does your repo include a `.gitmodules` file?  Does that file have a `url` for the `education-html` entry?

**Comment by bibi520** [comment]
Thank you,  I use git rm --cached education-html and then upload the code to pull it

**Comment by sbwsg** [comment]
@bibi520 am I right in understanding that `git rm --cached education-html` fixed the issue?  I will close this issue if so.
