### ISSUE TITLE
Configuring ssh-auth authentication for Git

### ISSUE THREAD

**Issue by inaxium** [tektoncd/pipeline#3673]
I have now tried to connect to github via ssh for about 8 hours without success. Standard authentication with username and password work.

I tried ssh-keygen -t ed25519 as well as ssh-keygen -t rsa -b 4096.

https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

I have the client key like in the file **git-ssh-creds-without-known_hosts.yaml** with **cat id_rsa | base64 -w 0** created.

I used different computers.

But in the end I always get the same error:

{
   "level": "warn",
   "ts": 1610361389.387573,
   "caller": "git / git.go: 271",
   "msg": "SSH credentials have been provided but the URL (\" https: //github.com/orctek/hello \ ") is not a valid SSH URL. This warning can be safely ignored if the URL is for a public repo or you are using basic auth "
}
{
   "level": "error",
   "ts": 1610361389.7080023,
   "caller": "git / git.go: 54",
   "msg": "Error running git [fetch --recurse-submodules = yes --depth = 1 origin --update-head-ok --force master]: exit status 128 \ nfatal: could not read Username for 'https: //github.com ': No such device or address \ n ",
   "stacktrace": "github.com/tektoncd/pipeline/pkg/git.run\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:54\ngithub.com/tektoncd/pipeline/pkg/git .Fetch \ n \ tgithub.com/tektoncd/pipeline/pkg/git/git.go: 145 \ nmain.main \ n \ tgithub.com/tektoncd/pipeline/cmd/git-init/main.go: 52 \ nruntime .main \ n \ truntime / proc.go: 204 "
}

Maybe someone has an idea.

**Comment by sbwsg** [comment]
It would be helpful to see the TaskRun / PipelineRun / PipelineResource you're using.  The error you're seeing says `SSH credentials have been provided but the URL (" https: //github.com/orctek/hello \ ") is not a valid SSH URL.`.  If your repo URL starts with `https://` then it is not an SSH-compatible URL.  This is not a Tekton issue - it's just how Git recognizes which credential to use.

**Comment by inaxium** [comment]
You're absolutely right. It was the URL.

The right one:

apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: pr-git-hello-world
spec:
  type: git
  params:
    - name: url
      value: git@github.com:orctek/hello.git
    - name: revision
      value: master
