### ISSUE TITLE
Missing imagePullSecret configurations guidance for a developer in DEVELOPMENT.md doc 

### ISSUE THREAD

**Issue by xiujuan95** [tektoncd/pipeline#3693]
Now, I am deploying tekton-pipeline locally according to this guide: https://github.com/tektoncd/pipeline/blob/master/DEVELOPMENT.md#install-pipeline

I set up a kubernetes cluster and run `ko apply -f config/` to deploy it. Everything looks good. But when I check `tekton-pipelines-controller`'s status, it showed me below error:
```
failed to authorize: failed to fetch anonymous token: unexpected status: 401 Unauthorized
```
So I create a secret for pulling image and add it to `tekton-pipelines-controller` and `tekton-pipelines-webhook` serviceAccount accordingly. Then everything is fine.

I am saying this because `DEVELOPMENT.md` doc is missing this guidance. It only tells us should configure authentication for pushing images:
```
Make sure to configure authentication for your KO_DOCKER_REPO if required.
```
But it doesn't tell us, we also need to configure authentication for pulling images. I think we should add this part to `DEVELOPMENT.md` part.

If my understanding is wrong, pls correct me. Thanks in advance!

**Comment by vdemeester** [comment]
@xiujuan95 hey 👋🏼 indeed, I think this is missing, mainly because, I think we tend to use public image repository by default, and thus imagePullSecret is not required. But yeah, it would be nice to add a little something in the doc about this.

/kind documentation

**Comment by xiujuan95** [comment]
@vdemeester Thanks for your attention! Maybe I will submit a PR about this later.

**Comment by xiujuan95** [comment]
@vdemeester PR is submitted: https://github.com/tektoncd/pipeline/pull/3699, please help review it, thanks a lot!

**Comment by xiujuan95** [comment]
PR is merged, I will close this issue, thanks!
