### ISSUE TITLE
support hostPath as VolumeSources in Workspaces

### ISSUE THREAD

**Issue by soulseen** [tektoncd/pipeline#3695]
### Feature request

support hostPath as VolumeSources in Workspaces

### Use case

Workspaces support the using hostPath as VolumeSource

**Comment by sbwsg** [comment]
Can you go in to a bit more detail why you want this support?

`hostPath` is supported through the persistent volume interface and Tekton supports that in workspaces: https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/#create-a-persistentvolume
