### ISSUE TITLE
image exists condition

### ISSUE THREAD

**Issue by mancubus77** [tektoncd/pipeline#3713]
According to documentation
https://github.com/tektoncd/pipeline/blob/master/docs/pipelines.md#guard-task-execution-using-whenexpressions
There is a possibility to configure "when" condition based on image existence in registry.  Unfortunately, I can not find an example in the documentation. 
I'm wondering if anyone can advise how to run a task if an image is no in the registry.

**Comment by zhouhaibing089** [comment]
IMHO, you can achieve this by creating a Task which checks the image existence, and write into [Results][1], then using the Results in when expression in the next Task.

[1]: https://github.com/tektoncd/pipeline/blob/master/docs/pipelines.md#using-results

**Comment by mancubus77** [comment]
Thank you @zhouhaibing089 
Could you please advise what's the best way to check image availability. Is there a standard task for that?

**Comment by chmouel** [comment]
skopeo should be help you achieving this https://github.com/containers/skopeo
