### ISSUE TITLE
Is there any way to tell whether any of the finally tasks failed?

### ISSUE THREAD

**Issue by riceluxs1t** [tektoncd/pipeline#3715]
I have a pipeline that has
task1 -> task 2 -> ... -> taskN | singleFinallyTask.

When `singleFinallyTask` fails for whatever reasons, is there an easy way to use `kubectl` or `tkn` to tell?

**Comment by chmouel** [comment]
I believe there is a TEP in the work for this :

https://github.com/tektoncd/community/pull/240

In the meantime this gets discussed/implemented, I have done something like this to get slack notifications, the main code detection is here which returns the list of the failed tasks :  

https://github.com/chmouel/tekton-asa-code/blob/47bd39d/misc/send-slack-notifications.py#L37-L57

You can get the current `pipelinerun` that is executing in a environement variable of a task like this :

https://github.com/chmouel/tekton-asa-code/blob/47bd39d/README.md#L287-L290

Not straightforward, but hopefully the TEP would make all of this obsolete and easier to work with results. 

/kind question

**Comment by pritidesai** [comment]
@riceluxs1t would tagging taskRun of `singleFinallyTask` help your use case? We could classify taskRun created for `finally` tasks by adding a label to it. (something similar to #3721).

**Comment by pritidesai** [comment]
We do not have any solution to this yet.
/lifecycle frozen
