### ISSUE TITLE
Suggest of variable substituting

### ISSUE THREAD

**Issue by supershll** [tektoncd/pipeline#3718]
### Feature request

when use  `variable substituting` Substituting parameters

When using the `variable substitution` function, if the value corresponding to the expression cannot be evaluated, then **`Tekton` will do nothing** and remain it as it is . It meas that if I use the example as follow , I would get an error because `$()` in shell has its own meanings of get the output of the command executes  : 

```
apiVersion : tekton.dev/v1beta1
kind: Task
metadata:
  name : use-workspace
spec:
  description: "use-workspace"
  workspaces:
  - name: messages
  steps:
  - name: step-use-workspace
    image: ubuntu
    args:
    - $(workspaces.messages.name)
    script: |
      #!/usr/bin/env bash
      set -ex
      echo $1

```

Although I can use `args` to avoid exceptions, obviously the parameters passed in are not what I expect,  the real `workspaces.messages.name` is obviously not `$(workspaces.messages.name)`

### Feature Suggest

when the value corresponding to the expression cannot be evaluated or the result of evaluate is empty , then the expression can be evaluated to `empty string` or a default value, just like in the shell 
-  `$(workspaces.messages.name)`  => empty string
-  `$(workspaces.messages.name:<default value>)` => <default value> when cannot evaluate
-  `$(workspaces.messages.name:-<default value>)` => <default value> when cannot evaluate or the result of evaluate is empty

**Comment by sbwsg** [comment]
As you mention, shell also uses the same syntax.  I'm not sure Tekton would be able to correctly determine in all cases whether a `$(foo)` is intended for tekton pipelines to replace or for the shell to handle.  This could lead to cases where Pipelines replaces an instance of `$(foo)` with an empty string but the user wanted the literal `$(foo)` characters to be sent to the shell.  The `script` block in a Task is somewhere this would become very ambiguous I think?

Is there a way to guarantee that Tekton Pipelines isn't replacing content intended for the shell?

**Comment by supershll** [comment]
This is just another topic I want to talk about, the `variable substitution` function lacks `character escape`  

Just like the scene you described,  when user  want the literal `$(foo)`  , may be he can use `\$(foo)` to `escape $ symbol` , and `\` itself can be escaped by `\\`  ,just like in the shell

> As you mention, shell also uses the same syntax. I'm not sure Tekton would be able to correctly determine in all cases whether a `$(foo)` is intended for tekton pipelines to replace or for the shell to handle. This could lead to cases where Pipelines replaces an instance of `$(foo)` with an empty string but the user wanted the literal `$(foo)` characters to be sent to the shell. The `script` block in a Task is somewhere this would become very ambiguous I think?
> 
> Is there a way to guarantee that Tekton Pipelines isn't replacing content intended for the shell?

**Comment by sbwsg** [comment]
/unassign

/remove-lifecycle rotten

I think there is definitely some desirable changes here - the variables being left verbatim in the fields when they don't resolve to values can be quite confusing. Unfortunately I don't have the bandwidth to pick this up, but I would definitely be interested in helping someone taking this on. It would likely involve backwards-incompatible changes unfortunately so we'd have to feature flag it in v1beta1.  But it would be great to have it fixed for v1.

/add-label help-wanted

**Comment by jkdihenkar** [comment]
This same problem exists when writing Jenkinsfile.

when writing under stage -> sh """ ... """

If there is `$(something)` -> is interpreted as groovy variable.
If there is `\$(something)` -> is treated as bash variable.
If there is `\\\$(something)` -> is treated as a string.
