### ISSUE TITLE
Feature request to detect whether executed TaskRun is part of finally section

### ISSUE THREAD

**Issue by anshulpatel25** [tektoncd/pipeline#3721]
### Feature request

Ability to fetch/differentiate TaskRuns executed as part of Finally section in the PipelineRun

### Use case

Currently, there is no way to detect whether executed TaskRun is part of Finally section directly. Adding this feature can help external systems via SDK to directly query the TaskRuns which are part of Finally without applying complex logic.

**Comment by vdemeester** [comment]
/lifecycle frozen
We could add a label to the taskrun (and thus the pod too) when it's a finally one, right ?

**Comment by pritidesai** [comment]
> /lifecycle frozen
> We could add a label to the taskrun (and thus the pod too) when it's a finally one, right ?

yes, that would be the best way, I will have a PR with changes in a couple of days.
