### ISSUE TITLE
Tekton Taskrun Metrics are not accurate

### ISSUE THREAD

**Issue by ibexmonj** [tektoncd/pipeline#3739]
# Expected Behavior

Tekton metrics should match the data provided by kubectl.

# Actual Behavior

I have been trying to gather the taskrun duration using `tekton_taskrun_duration_seconds_sum` and `tekton_taskrun_duration_seconds_count`by doing 

`
sum(rate(tekton_taskrun_duration_seconds_sum{cluster_name="dev",namespace="tekton",taskrun="task-run-tekton5g444"}[1h])) / sum(rate(tekton_taskrun_duration_seconds_count{cluster_name="dev",namespace="tekton",taskrun="task-run-tekton5g444"}[1h])) 
`

I am seeing the value being reported twice in prometheus. Sometimes the value is reported 2-3 times resulting in duplicate values for taskrun duration seconds. 

![image](https://user-images.githubusercontent.com/526798/106509962-462d9400-649c-11eb-8b63-aee4d17381e8.png)

Here is another example where the duration_seconds value is being reported multiple times. As if the controller is resetting and then incrementing the value again ? 

The query used here is `sum (rate(tekton_taskrun_duration_seconds_sum{namespace="tekton",cluster_name="dev",taskrun="task-run-tektonhfvhq"}[5m])) `

![image](https://user-images.githubusercontent.com/526798/106511776-b3422900-649e-11eb-85ac-fae8ccef6157.png)
 

Another issue is the timestamp being reported.

Here is the taskspec 

`
status:
  completionTime: "2021-02-01T15:00:32Z"
  conditions:
  - lastTransitionTime: "2021-02-01T15:00:32Z"
    message: All Steps have completed executing
    reason: Succeeded
    status: "True"
    type: Succeeded
  podName: task-run-tekton5g444-pod-cwbvx
  startTime: "2021-02-01T15:00:27Z"
`

As per above the job ran at `15:00` GMT but based on the prometheus screenshot above the timestamp being reported is `16:36` which does not quiet add up to the time being reported in `kubectl get taskrun taskrun_name -o yaml`

# Steps to Reproduce the Problem

1. Enable Tekton metrics.
2. Enable prom scrape.
3. Use the above `sum/count` method to track taskrun duration.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:*

`
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-14T05:13:35Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.12-gke.20", GitCommit:"0ac5f81eecab42bff5ef74f18b99d8896ba7b89b", GitTreeState:"clean", BuildDate:"2020-09-09T00:48:20Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}
`

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

`
$ tkn version
Client version: 0.15.0
Pipeline version: v0.10.2
Triggers version: v0.3.1
`

**Comment by bobcatfish** [comment]
Seems like a legit bug - we should at least investigate if we can reproduce before closing.

/remove-lifecycle rotten

**Comment by lbernick** [comment]
/priority important-soon
/remove-lifecycle rotten
There's a [TEP](https://github.com/tektoncd/community/blob/main/teps/0073-simplify-metrics.md) for improving our metrics, this should be addressed there

**Comment by wlynch** [comment]
/assign @khrm 

Should be fixed with https://github.com/tektoncd/pipeline/pull/4468

**Comment by ibexmonj** [comment]
Thank you for working on this.

**Comment by pritidesai** [comment]
Both the PRs with the fixes are merged:

* https://github.com/tektoncd/pipeline/pull/4468
* https://github.com/tektoncd/pipeline/pull/4469

/close
