### ISSUE TITLE
Provide non-root user in pullrequest-init image

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/pipeline#3746]
### Feature request

Similarly to supporting `nonroot` in `git-init`'s image ([PR here](https://github.com/tektoncd/pipeline/pull/3727)) we should also add support for a non-root user in the `pullrequest-init` image.

### Use case

Users would like to be able to run pipelines without root permissions inside Task containers.  See request [here](https://github.com/tektoncd/pipeline/pull/3727#issuecomment-772199907) and similar motivation for `git-init` [here](https://github.com/tektoncd/pipeline/issues/3712) for examples.

### Additional Info

Unlike `git-init`,  `pullrequest-init` doesn't need the dependencies contained in `build-base` so it's built from `distroless:static`.  If possible we should keep the `pullrequest-init` image as equally svelte as it is today.  But, importantly, we should continue to support both `root` as well as `nonroot` users in the `pullrequest-init` image (unless we can categorically prove that no users would be harmed by switching to a pure `nonroot` image... in which case we can presumably just use `distroless:nonroot`.)

**Comment by ImJasonH** [comment]
From [.ko.yaml](https://github.com/tektoncd/pipeline/blob/1b7a37f0d21d8e8114a96f3d061a15dc24d6782f/.ko.yaml#L9-L10):

> PullRequest resource needs root because in output mode it needs to access pr.json which might have been copied or written with any level of permissions.

Could we document that if you use the PR resource in output mode, that `pr.json` must be readable by all users?

**Comment by sbwsg** [comment]
We could probably do that yeah, though it's technically backwards incompatible?  Luckily PipelineResources are still alpha...  We'd also need to do this if we want to provide the nonroot user in the `pull-request` catalog task: https://github.com/tektoncd/catalog/blob/master/task/pull-request/0.1/pull-request.yaml#L38

**Comment by zhangtbj** [comment]
Thanks for the info, Scott!

A quick question, how about the `gcs-fetcher` in here:
https://github.com/tektoncd/pipeline/blob/v0.20.1/.ko.yaml#L7-L8

It says: `# GCS fetcher needs root due to workspace permissions`, is that possible to switch them all to `non-root` in the .ko.yaml?

Thanks!

**Comment by ImJasonH** [comment]
> A quick question, how about the `gcs-fetcher` in here:
> https://github.com/tektoncd/pipeline/blob/v0.20.1/.ko.yaml#L7-L8
> 
> It says: `# GCS fetcher needs root due to workspace permissions`, is that possible to switch them all to `non-root` in the .ko.yaml?

gcs-fetcher will be deprecated in the next release (v0.21) and removed in the following release (v0.22). I believe nobody uses it. If you believe your users don't use it, you can effectively disable it by modifying your Tekton installation to reference a non-existent (or any) image. For example, replace [this line](https://github.com/tektoncd/pipeline/blob/98507859fa961f2152b65ad911defc2f0a2ef804/config/controller.yaml#L69):

```
"-build-gcs-fetcher-image", "image-does-not-exist",
```

**Comment by zhangtbj** [comment]
Oh, thanks Jason!

That is awesome for us! We will try to replace a non-existent image for gcs-fetcher in the later release.

Thanks for the good news!

**Comment by zhangtbj** [comment]
A quick question about this requirement.

I did a test, to use the same non-root build-base image for pullrequest init image and run the Tekton e2e tests. It passed.

So about the solution:
> But, importantly, we should continue to support both root as well as nonroot users in the pullrequest-init image (unless we can categorically prove that no users would be harmed by switching to a pure nonroot image... in which case we can presumably just use distroless:nonroot.)

If prefers to support both `root` and `nonroot` users, and use a more lightweight base image than build-base image.

Should introduce a new image/Dockerfile to add non-root USER for distroless then for pullrequest? (I can provide a PR for that)

Or there is any plan for this issue?

Thanks!

**Comment by sbwsg** [comment]
I don't have any immediate plan to work on this in the next few weeks so a PR would be great.

Personally I do think we should be able to support both root and non-root uses for the time being. Adding an optional nonroot user to pullrequest-init's base image makes sense to me.

**Comment by zhangtbj** [comment]
Cool, got it. Let me think about it.

Thanks Scott!

**Comment by zhangtbj** [comment]
I provided a PR to add a new Dockerfile for pullrequest-init image:
https://github.com/tektoncd/pipeline/pull/3810

Please review and hope the build process can be verified by the CI/CD process.

**Comment by sbwsg** [comment]
Closing, fixed by https://github.com/tektoncd/pipeline/pull/3810

/close
