### ISSUE TITLE
webhook pod blocking node drain

### ISSUE THREAD

**Issue by abhinavkhanna-sf** [tektoncd/pipeline#3774]
Hi,

I am trying to drain a node to update the kubectl version, however keep getting this error

`error when evicting pod "tekton-pipelines-webhook-747547fc7c-qg556" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.`
Is there a way to avoid it?

**Comment by ImJasonH** [comment]
This is https://github.com/tektoncd/pipeline/issues/3654
