### ISSUE TITLE
[question] How does tekton control the order of the steps in task

### ISSUE THREAD

**Issue by garyyang85** [tektoncd/pipeline#3782]
Hello Team

As I know, containers in a pod don't have a sequence for start or stop. But how does tekton achieve this? I can search the result in the doc "The order in which the Steps appear in this list is the order in which they will execute." 

Take the **buidah** task for example. How does tekton control step-build before step-push. Is there a design doc?  Thanks

**Comment by chmouel** [comment]
/kind question

Using entrypoint binary see: https://github.com/tektoncd/pipeline/blob/master/cmd/entrypoint/README.md

**Comment by bobcatfish** [comment]
@ImJasonH and I did a talk at kubecon on this a while back too: https://www.youtube.com/watch?v=iz9_omZ0ctk

And recently argo workflows (+ @alexec) took a similar approach with their Emissary executor: https://github.com/argoproj/argo-workflows/blob/22f4d26ec059ad86b9c409ffe25392261a22afba/docs/workflow-executors.md#emissary-emissary

**Comment by bobcatfish** [comment]
oh yeah and for more history, i think this would be the issue to look at https://github.com/tektoncd/pipeline/issues/224 (we used to use init containers for this functionality)

**Comment by garyyang85** [comment]
Thank you guys. I got the answer.
