### ISSUE TITLE
Adding a manifest/ folder

### ISSUE THREAD

**Issue by djfinnoy** [tektoncd/pipeline#3785]
Would it be possible to include the `release.yaml` you distribute via your Google Storage bucket to this github repository, perhaps under a `manifest/` dir?

**But why?**

Installing Tekton via kubectl is easy, but installing Tekton via an Infrastructure as Code approach is super tedious.
There is no official Helm chart (#1542), and the Terraform `kubernetes-alpha` provider is not mature enough to utilize your release yaml.

The reason I would find it helpful if you included `manifests/release.yaml` to this repository, is that I could use ArgoCD, or other GitOps tools to install Tekton. It seems like Tekton is often paired with ArgoCD, so I'm probably not the only one who would be happy to find an official installation yaml within this repository.

**Comment by ImJasonH** [comment]
I'm weakly inclined not to include generated content in the repo, since this can drift out of sync with the repo contents, or at the very least, require a new commit to add the generated content. For example, if we tag commit `abcde` as `v0.X.Y`, then automation adds a new commit `f1234` with updated `manifest/release.yaml`, should `v0.X.Y` move to point to the new commit? :thinking:

Maybe I'm not understanding your use case well enough, that's definitely been known to happen before 🙃 

In any case, if you need a Git repo that contains the generated release.yaml, you can automate this yourself outside of the Tekton org, iterate on it until it's stable and meets your needs, then propose we add it as an official thing. The benefit there is that you're not blocked waiting on us to approve it, and even if we don't accept the proposal, you get unblocked just by relying on your own repo.

**Comment by bobcatfish** [comment]
> if you need a Git repo that contains the generated release.yaml, you can automate this yourself outside of the Tekton org, iterate on it until it's stable and meets your needs, then propose we add it as an official thing

I wonder if storing a copy of the release.yaml in your own repo might be the best solution for your needs in the long run - then you'd be in complete control of what version you're using and when you want to upgrade.

**Comment by djfinnoy** [comment]
> I wonder if storing a copy of the release.yaml in your own repo might be the best solution for your needs in the long run - then you'd be in complete control of what version you're using and when you want to upgrade.

Yeah that's what we're doing now. If we get around to it, we may use Github Actions to track releases from this repository and pull the yaml's into our own repo. Just though I'd ask if there was any interest in doing this centrally for the benefit of users who prefer an IaC approach to setting up their clusters.

**Comment by vdemeester** [comment]
Note that it is also available from github.com (in the release pages, e.g. https://github.com/tektoncd/pipeline/releases/download/v0.21.0/release.yaml)

I agree with @bobcatfish and @ImJasonH, I don't see a reason to include a generate file in the repository. It could easily drift and thus not be the source of truth.

**Comment by nikhil-thomas** [comment]
how about publishing an OCI non-executable image which contains our release.yaml (for pipelines, triggers ...).

This is help us eliminate delays in operaors release process. At present, we need to make a pr each for every reelase of pipeline, triggers ... to get the respective release.yaml inside operator's kodata directory.

If we can publish the release.yaml as an image in addition to gcs bucket, then operator can use these images as init containers to inject the release manifest in to the operators controller deployment. From operator's prespective, these release.yaml is like big config files. 😇 🤓 🧑‍💻

**Comment by vdemeester** [comment]
> how about publishing an OCI non-executable image which contains our release.yaml (for pipelines, triggers ...) with each release of pipelines, triggers ...
> 
> This will help us eliminate delays in operaors release process. At present, we need to make a pr each for every reelase of pipeline, triggers ... to get the respective release.yaml inside operator's kodata directory.
> 
> If we can publish the release.yaml as an image in addition to gcs bucket, then operator can use these images as init containers to inject the release manifest in to the operators controller deployment. From operator's prespective, these release.yaml is like big config files. innocent nerd_face technologist

That's an idea indeed 😝
