### ISSUE TITLE
PipelineRun and TaskRun Status

### ISSUE THREAD

**Issue by jerop** [tektoncd/pipeline#3792]
## Overview
As discussed in API working group on 02/22 ([notes](https://docs.google.com/document/d/17PodAxG8hV351fBhSu7Y_OIPhGTVgj6OJ2lPphYYRpU/edit#heading=h.f8cfqihbg88y) | [recording](https://drive.google.com/file/d/1N3iXRqxlb8ju3BD5V8EKA9DnOomXBi9D/view)), we need to revisit the design of the `Status` sections of `PipelineRuns` and `TaskRuns`

We agreed that we need to rework the `Status` sections to be at par with the `Spec` sections of the API as we work towards [V1 release](https://github.com/tektoncd/pipeline/issues/3548)

## Problems
Problems in the `Status` sections include:
- [excessive updates](https://github.com/tektoncd/pipeline/issues/3140)
- embedding the `TaskRun` and `Run` status in the `PipelineRun` status
   - takes up a lot of space
   - concern when supporting [`Pipelines` in `Pipelines`](https://github.com/tektoncd/experimental/pull/705)
   - figure out how [`Results`](https://github.com/tektoncd/results) can help
- lack of documentation of the `Status`; few details in [`PipelineRun`](https://github.com/tektoncd/pipeline/blob/master/docs/pipelineruns.md#monitoring-execution-status) and [`TaskRun`](https://github.com/tektoncd/pipeline/blob/master/docs/taskruns.md#monitoring-execution-status) docs

Please share other issues you may have with `Status`

## References
- [PipelineRun Status bloat and excessive updates #3140](https://github.com/tektoncd/pipeline/issues/3140)
- [Design result reporting to to Result Store #454](https://github.com/tektoncd/pipeline/issues/454)
- [Towards v1 API #3548](https://github.com/tektoncd/pipeline/issues/3548)
- [API working group meeting notes ](https://docs.google.com/document/d/17PodAxG8hV351fBhSu7Y_OIPhGTVgj6OJ2lPphYYRpU/edit#heading=h.f8cfqihbg88y)

/cc @tektoncd/core-maintainers

**Comment by vdemeester** [comment]
> embedding the `TaskRun` and `Run` status in the `PipelineRun` status
> 
>     * takes up a lot of space
> 
>     * concern when supporting [`Pipelines` in `Pipelines`](https://github.com/tektoncd/experimental/pull/705)
> 
>     * figure out how [`Results`](https://github.com/tektoncd/results) can help

One thing to consider here is that having the spec used in the status allows us to have a finite source of truth of what was used for that run. Without it, we have no way, while looking back at some runs, to know *for sure* what what the definition of the pipeline or the task executed. In addition, even though we are not taking advantage of this today, this could allow us to reduce the number of "fetching the definiton spec" (from the cluster, from the oci image, …) as the information is already available in the `status`.

**Comment by jerop** [comment]
/lifecycle frozen

in the 1.0 roadmap - https://github.com/tektoncd/pipeline/issues/3548

**Comment by lbernick** [comment]
/close

TEP-0100 has now been implemented, and documentation of status is being tracked in #4660.
