### ISSUE TITLE
Add pending/pause task in pipeline

### ISSUE THREAD

**Issue by FogDong** [tektoncd/pipeline#3796]
### Feature request

Right now we have pending status in pipeline, with which we can pause the pipeline at any time. But when it comes to pause the pipeline before a specific task, we can not pause the pipeline automatically.
That's the reason why I think we need a pending/pause task in pipeline, we could:
1. Add a pending/pause task in pipeline like the way argo do: https://argoproj.github.io/argo-workflows/examples/#suspending
2. Or we can add some `spec.taskstatus` in task, in which we can define the status as `pending` when create the task, when the taskrun is created, the status of it will be pending and so the controller knows how to deal with it like the way the pipeline pending do. 

### Use case

In my case, there's some situation that the task need to be approved by admin before it get executed. So before the admin approver the step, the task need to be paused.
Or maybe I should write a TEP for the feature? 🤔

**Comment by sbwsg** [comment]
It sounds like this could be implemented initially as a Custom Task to prove out the concept?  There's an existing [`Wait Task`](https://github.com/tektoncd/experimental/tree/master/wait-task) in the experimental repo - I wonder if you could take that and modify it to look for an approval signal before it is allowed to continue.

**Comment by FogDong** [comment]
> It sounds like this could be implemented initially as a Custom Task to prove out the concept? There's an existing [`Wait Task`](https://github.com/tektoncd/experimental/tree/master/wait-task) in the experimental repo - I wonder if you could take that and modify it to look for an approval signal before it is allowed to continue.

Thanks! That's exactly what I need, I'll see if I can add the approval signal in wait task.

**Comment by zhaoxiangyu** [comment]
> approval

Hi, have you added the approval signal in wait task?

**Comment by zhaoxiangyu** [comment]
@FogDong 
Hi, have you added the approval signal in wait task?

**Comment by kerthcet** [comment]
Revisit this issue, it seems like suspend/resume is still not supported in Tekton. Do we have any alternative method, or we're not going to support this, at least now? cc @vdemeester

**Comment by pritidesai** [comment]
[TEP-0123 - Specify on-demand-retry in a pipelineTask](https://github.com/tektoncd/community/pull/823) does not solve pending/pause use case specified in this issue but addresses the use case to retry a failed task on-demand if you are interested.
