### ISSUE TITLE
Allow to inject custom "RateLimiter" when implements "custom task" controller

### ISSUE THREAD

**Issue by vincent-pli** [tektoncd/pipeline#3804]
### Feature request

When implements new `controller` based on `custom task` mechanism, a reconcile for `Run` will be created.
in our case, the `DefaultControllerRateLimiter` in client-go could not satisfy us, so we expect adopt our `rateLimiter`.

but I found there is no chance to do that, since controller of `custom task` will leverage:
https://github.com/tektoncd/pipeline/blob/master/pkg/client/injection/reconciler/pipeline/v1alpha1/run/controller.go

but see this line:
https://github.com/tektoncd/pipeline/blob/ca26ea83aba58aa0313f1a5bb81fbd686a6acb01/pkg/client/injection/reconciler/pipeline/v1alpha1/run/controller.go#L98

the `controller.NewImpl` can not make a custom `rateLimiter` as parameters, although in `knative` there is:
https://github.com/knative/pkg/blob/2bc944bb68d0342884e8794e58033b92dbcc993c/controller/controller.go#L239
`func NewImplFull(r Reconciler, options ControllerOptions) *Impl {`

which allow use a custom `ratelimiter`, i know the code is generated, so any suggestion for it?

**Comment by souleb** [comment]
The `func NewImpl(r Reconciler, logger *zap.SugaredLogger, workQueueName string) *Impl` is deprecated and NewImplFull must be used. What about opening an issue on knative to have it changed on the injection controller?

**Comment by vincent-pli** [comment]
Thanks @souleb , have submit issue on `knative/pkg` side.
