### ISSUE TITLE
Broken release.yaml file on ppc64le.

### ISSUE THREAD

**Issue by Siddhesh-Ghadi** [tektoncd/pipeline#3820]
This issue is in reference to https://github.com/tektoncd/plumbing/pull/762#discussion_r591316378 to track `pipelines` failure on `ppc64le`.

The `distroless/base` image in `tekton-pipelines-controller` deployment doesn't work on `ppc64le` due to incorrect `busybox` binary. 

We are working on having a permanent fix. https://github.com/GoogleContainerTools/distroless/pull/622#issuecomment-795077067
Until then, workaround to get deployment working on `ppc64le` is to replace `distroless/base` image with `ubi8/ubi-minimal:latest`

**Comment by ImJasonH** [comment]
Apologies for coming to this late, if this has already been discussed, but can we fix this by using `distroless/static:nonroot` instead of `distroless/base`? That image should have support for ppc64le as well and not have any BusyBox issues. The controller shouldn't depend on anything in the base image anyway.

**Comment by afrittoli** [comment]
@ImJasonH That's the image we use as `shell-image` https://github.com/tektoncd/pipeline/blob/10870dfaa0c6c4213b9dd8418275cc61e401475e/config/controller.yaml#L72-L75, which is used for things like `script` - it needs to have a shell inside.

**Comment by ImJasonH** [comment]
Oh I see from https://github.com/tektoncd/plumbing/pull/762#discussion_r590501357 this is in reference to the shell image, which indeed does use busybox

**Comment by ghatwala** [comment]
@vdemeester @ImJasonH @afrittoli  - Busybox failures in distroless image for power has been resolved with https://github.com/GoogleContainerTools/distroless/pull/723
