### ISSUE TITLE
Active/active HA

### ISSUE THREAD

**Issue by vincent-pli** [tektoncd/pipeline#3835]
I saw the [ha of tekton](https://github.com/tektoncd/pipeline/blob/main/docs/enabling-ha.md) said: 
> HA is achieved by following an active/active model, where all replicas of the Controller can receive and process work items

I tried it with branch master, but I found only one replicas really works, and seems all `lease` hold by one controller(tekton-pipelines-controller-6f66f86b9f-8dqh5):
```
root@rentz1:~/go/src/github.com/pipeline# kubectl -n tekton-pipelines get po
NAME                                           READY   STATUS              RESTARTS   AGE
tekton-pipelines-controller-6f66f86b9f-8dqh5   0/1     Running             0          15s
tekton-pipelines-controller-6f66f86b9f-gdfdj   0/1     Running             0          15s
tekton-pipelines-controller-6f66f86b9f-hlj5j   0/1     Running             0          15s
tekton-pipelines-webhook-7d8748697f-bfcsz      0/1     ContainerCreating   0          15s
root@rentz1:~/go/src/github.com/pipeline# kubectl -n tekton-pipelines get lease
NAME                                                                                                      HOLDER                                                                              AGE
tekton-pipelines-controller.github.com.tektoncd.pipeline.pkg.reconciler.pipelinerun.reconciler.00-of-03   tekton-pipelines-controller-6f66f86b9f-8dqh5_54fb7d78-80b5-4bca-be31-ccf87ce58759   7s
tekton-pipelines-controller.github.com.tektoncd.pipeline.pkg.reconciler.pipelinerun.reconciler.01-of-03   tekton-pipelines-controller-6f66f86b9f-8dqh5_54fb7d78-80b5-4bca-be31-ccf87ce58759   7s
tekton-pipelines-controller.github.com.tektoncd.pipeline.pkg.reconciler.pipelinerun.reconciler.02-of-03   tekton-pipelines-controller-6f66f86b9f-8dqh5_54fb7d78-80b5-4bca-be31-ccf87ce58759   7s
tekton-pipelines-controller.github.com.tektoncd.pipeline.pkg.reconciler.taskrun.reconciler.00-of-03       tekton-pipelines-controller-6f66f86b9f-8dqh5_1cac6f7a-81bf-4210-b886-34c966adf757   7s
tekton-pipelines-controller.github.com.tektoncd.pipeline.pkg.reconciler.taskrun.reconciler.01-of-03       tekton-pipelines-controller-6f66f86b9f-8dqh5_1cac6f7a-81bf-4210-b886-34c966adf757   7s
tekton-pipelines-controller.github.com.tektoncd.pipeline.pkg.reconciler.taskrun.reconciler.02-of-03       tekton-pipelines-controller-6f66f86b9f-8dqh5_1cac6f7a-81bf-4210-b886-34c966adf757   7s
```

So, is that by design or i missing something?

**Comment by zhangtbj** [comment]
Hi,

I remember the `lease` is related to the bucket for reconcile queues.

We did some investigation, the `lease` and `bucket` are introduced from `knative/pkg` package, but it is a new feature and is not design very well, I think.

By default, tekton controller has one bucket, so the `HOLDER` should be the bucket name. And if you have three pods, and you want to use three buckets to average the reconcile queues, you can configure leader-election configMap to change the number of bucket to 3.

But even you change the bucket to 3, by default, the bucket will not be re-balanced, you have to delete the leader pod, then buckets will be reassigned. (So that is why we think it is not implemented well now)


But I think this `lease` is not related to the HA, just related how the bucket is used and balance the reconcile.

We did some investigation, you can also have a try, run multiple taskruns, then view the three pod logs, then you can find, the three controller pods will serve these multiple taskrun requests together, NOT just leader.

also cc @xiujuan95

**Comment by xiujuan95** [comment]
@vincent-pli 

As @zhangtbj said, by default, tekton controller sets [the number of bucket is one](https://github.com/tektoncd/pipeline/blob/main/vendor/knative.dev/pkg/leaderelection/config.go#L89-L106). 

And also tekton controller HA is `active/active`. The reconcile queue is sharded into multiple buckets, and  one bucket only can be held by one leader (one replicas/pod). And ideally, different buckets should be assigned to across different controller pods.

But, now, controlller only have one bucket, so you find all buckets are held by one controller pod. If you want to assign lease across pods, then you first should configure bucket number in leader-election configmap (there has a [doc](https://github.com/tektoncd/pipeline/blob/main/docs/enabling-ha.md#configuring-leader-election) you can follow). Then check bucket allocation. 

Maybe you still find all buckets are held by one pod. In this situation, you can try to delete related pod. Then buckets will be re-assigned until the  distribution of buckets is uniform.

Another method about re-assigning buckets is edit the lease you want to move it to another pod, delete `holderIdentity` key-value and save it:
```
kubectl -n tekton-pipelines edit lease ${lease_name}
```

Yep, thest two soultions may be stupid, so for our side, we still try to investigate how to assign them more uniform form tekton controlller code level, but I am stuck by other work, sorry! If you have some findings, pls let me know, thanks in advance!

>But I think this lease is not related to the HA (load balance), just related how the bucket is used and balance the reconcile.
>
BTW, @zhangtbj maybe this part is not 100% correct.

**Comment by vincent-pli** [comment]
Thanks @zhangtbj @xiujuan95 
It's interesting, I guess I need dig in to the `knative/pkg` for more details, thanks again, I'd like keep the issue open see if others have more idea.

**Comment by vincent-pli** [comment]
I checked some code of `knative/pkg`, the lead selection is totally random.
Every `controller` will try to be the leader of all buckets.
https://github.com/knative/pkg/blob/dfeeb1817679df6d29737a6c9a61ea9c4860d91a/leaderelection/context.go#L123-L171
