### ISSUE TITLE
PipelineRun Deleted Event

### ISSUE THREAD

**Issue by abdiali9617** [tektoncd/pipeline#3837]
After deleting the pipelinerun there are no further events that can be captured. What events if any are supposed to trigger when a pipelinerun is deleted?

**Comment by afrittoli** [comment]
We do not have any event at the moment, we don't really use the pipelinerun finalizer.
Do you refer to k8s events or `CloudEvents`? 
I would be interested to know about your use cases about this - this shouldn't be too difficult to implement.
