### ISSUE TITLE
The reason limit marking "PipelineRunPending"  before "pipelinerun" started

### ISSUE THREAD

**Issue by vincent-pli** [tektoncd/pipeline#3845]
I saw `tekton` introduce feature [pending pipelinerun](https://github.com/tektoncd/pipeline/blob/main/docs/pipelineruns.md#pending-pipelineruns), it's very useful, but I wonder to know why we limited the feature could only marked before the `pipelinerun` is started.

Just from the view of its implements, I think it could work after `pipelinerun` started.
So I guess I missing something, any idea? thanks. 

@ImJasonH @jbarrick-mesosphere

**Comment by ImJasonH** [comment]
Mainly to limit the scope of the feature initially, IIRC.

If a PipelineRun is updated to `Pending` while it's ongoing, what should happen? Ongoing TaskRuns can't be easily paused today, and pausing ongoing steps is even harder. Should `Pending` mean "don't start any new work until I tell you" then?

I'm open to discussing it, but I think there's some complexity involved in the answers.

**Comment by vincent-pli** [comment]
@ImJasonH 

I agree with you we cannot get a exactly `pending` since pause ongoing pod(means pause 'step') is a problem.
but with current implements we can at lease pause `taskrun`, I mean leave the ongoing `taskrun` there and stop creating new `taskrun`, it's valuable, at lease I have such case in my project.

so, could we remove the limitation?

**Comment by sbwsg** [comment]
Also related I think, a request for supporting pending taskruns: https://github.com/tektoncd/pipeline/issues/3796

Maybe placing an executing pipelinerun into pending state would mean any newly-created taskruns from that point on will be started with a pending state, effectively pausing the pipeline until those are allowed to continue?

**Comment by ImJasonH** [comment]
> so, could we remove the limitation?

I think I'd like to have a TEP to discuss the limitations and user expectations. Otherwise, I agree it should be relatively straightforward to implement.
