### ISSUE TITLE
What the gsutil-image and shell-image images for?

### ISSUE THREAD

**Issue by zhangtbj** [tektoncd/pipeline#3846]
Hi all,

When I viewing the tekton deployment, I found there are two images that are NOT built/managed by `.ko.yaml`:
https://github.com/tektoncd/pipeline/blob/main/config/controller.yaml#L70-L75
- "-gsutil-image", "gcr.io/google.com/cloudsdktool/cloud-sdk@sha256:27b2c22bf259d9bc1a291e99c63791ba0c27a04d2db0a43241ba0f1f20f4067f",
- "-shell-image", "gcr.io/distroless/base@sha256:92720b2305d7315b5426aec19f8651e9e04222991f877cae71f40b3141d2f07e"

I have two basic questions:
- What are these two images for? And When they will be used?
- Can these two images is managed by `.ko.yaml`, so we can controll how to build these images? At least root based image is not acceptable in our env.

Thanks!

**Comment by ImJasonH** [comment]
The gsutil image is used to fetch objects from GCS when you use the gcs type PipelineResource.

The shell-image is used to support the `script` feature.

In both cases if you don't need these features you can set the flag values to any valid image ref to pass validation. Even an image that doesn't exist (`example.com/doesn't/exist`) should work.

**Comment by zhangtbj** [comment]
Thanks @ImJasonH ,

We care about more about the `The shell-image is used to support the script feature.`.

It is a little different from what we see.

From our test, the `gcr.io/distroless/base` image is used for just one container:

| Container | Command |
| -- | -- |
| create-dir-image (for the image resource) | `mkdir -p /workspace/output/image` |

It means the `shell-image` is used in the first init-container in ALL of tekton taskrun pod WITH output resource to create the  folder of `/workspace/output/image` ?

cc @SaschaSchwarze0

**Comment by SaschaSchwarze0** [comment]
> It means the `shell-image` is used in the first init-container in ALL of tekton taskrun pod WITH output resource to create the folder of `/workspace/output/image` ?

@zhangtbj, this step is specific to how Shipwright Build creates the TaskSpec. We have the [output resource of type=image and name=image](https://github.com/shipwright-io/build/blob/c0861901860f867697a46c638788ddbd0f7d942a/pkg/reconciler/buildrun/resources/taskrun.go#L240-L253). To my best knowledge, for each output resource, Tekton creates the directory `/workspace/output/{RESOURCE_NAME}`. Without that resource, the container `create-dir-image` would not be there.

**Comment by ImJasonH** [comment]
Working dir initialization is also done using the shell-image ([here](https://github.com/tektoncd/pipeline/blob/0593c7bef395505fae8b2e611cf4632e2e980e1d/pkg/pod/workingdir_init.go#L34)).

In that case you can update the `-shell-image` value passed to controller.yaml to any image you want:

https://github.com/tektoncd/pipeline/blob/0593c7bef395505fae8b2e611cf4632e2e980e1d/config/controller.yaml#L72-L75

That image should have `sh` and `mkdir` to work properly. I'm not sure if the comment about needing root is necessary to `mkdir /workspace`, testing might be required.

**Comment by zhangtbj** [comment]
Yes, but I have to update the `-shell-image` value in the controller deployment yaml after I build and generate the yaml files by using `ko`.

We followed the official build process, but we still miss these two images, and it is hard to control during my custom build process.

I am thinking can Tekton use a unified way to build and manage these init or tool images (such as use ONE build-base image for them, etc...) or simplify it, so that we don't miss any of the images. Now we have to build each small tool image by using a different Dockerfile or image.

**Comment by ImJasonH** [comment]
I understand it's not ideal, but you can accomplish this with `sed`:

```
ko resolve -R -f deploy/` | sed -e 's/gcr.io\/distroless\/base.*"/my-base-image"/g' > release.yaml
```

Or

```
ko resolve -R -f deploy/` | sed -e 's/gcr.io\/distroless\/base.*"/my-base-image"/g' | kubectl apply -f -
```

`my-base-image` could be any image that has `sh` and `mkdir`, including `busybox`, `alpine`, Red Hat's UBI, etc.

Longer term, this might make sense as a configuration on the Tekton operator, rather than making people muck with flags.

**Comment by zhangtbj** [comment]
How about provide a base image property in `.ko.yaml` like `git-init` or `pullrequest-init` and also configure these two image by using ko, so that we can control them by using a same way as other images?

**Comment by ImJasonH** [comment]
> How about provide a base image property in `.ko.yaml` like `git-init` or `pullrequest-init` and also configure these two image by using ko, so that we can control them by using a same way as other images?

The shell-image and gsutil-image images aren't built by `ko`, so `.ko.yaml` isn't involved in the building of those images.

It's conceivable that `ko` could also take a mapping of input->output images to perform replacements, but I think you'd probably just have a better time using a single-purpose string replacement tool (`sed`, maybe `kustomize`) to replace these strings in your release pipeline, rather than relying on magic internal to `ko`.

**Comment by zhangtbj** [comment]
Thanks Jason, yes, we are doing the string replacement in our release process now.
