### ISSUE TITLE
Cloud Events for Runs

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/pipeline#3862]
### Feature request

Cloud events should be sent Runs.

It needs to be identified whether we want this to be a responsibility of the custom task controllers, the pipeline controller or a dedicated one. 

### Use case

We support cloud events for taskruns and pipelineruns, we should support them for runs too.

**Comment by ImJasonH** [comment]
I like the idea of basic cloudevents for Run start/success/failure that everybody gets out of the box, and documentation/samples for Custom Task authors to add their own if they want.

The pipelines controller doesn't currently do anything with Runs, I'm not even sure it has a no-op reconciler for them, so if we decide we want to support this we'd add one and do it there.

**Comment by jerop** [comment]
moved it to milestone for v0.31

**Comment by afrittoli** [comment]
The `PipelineRun` controller creates the `Run` so it could send that event. 
The `PipelineRun` controller also watches for changes to `Runs` so it would need to check if there was a change between the local copy of the status and the one reported by the informer. This could be done in `updateRunsStatusDirectly` - however since we plan on removing the local copy of the status, I think it would not be wise to implement a new feature that relies on that.

My proposal here would be to implement this in the external controller instead. This would then be implemented once the external controller replaced the inbuilt one for sending events.

**Comment by vdemeester** [comment]
I tend to agree on the external controller 👼🏼

**Comment by pritidesai** [comment]
thanks @afrittoli!

Yup implementing as part of an external controller sounds reasonable. This can give freedom to the external controller in designing the events based on their requirements.

**Comment by afrittoli** [comment]
Implemented in three PRs:

- [x] #4658
- [ ] #4659
- [ ] #4663
