### ISSUE TITLE
Incomplete annotations in the taskrun start cloud events

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/pipeline#3864]
# Expected Behavior

The annotations taskrun sent in a cloud event are always complete.

# Actual Behavior

In annotations are set in the `Task`, they have not been inherited to the `TaskRun` when the start cloud event is sent.
This causes missing annotations. The `PipelienRun` controller must resolve the tasks in the pipeline, however it does not use the resolved `Task` to set `TaskRun` annotations. That is only done by the `TaskRun` controller later on, not not soon enough to show up in the start event.

# Versions

Pipelines v0.22.0

**Comment by afrittoli** [comment]
The same issue will exists for annotations on `PipelineRuns` inherited from `Pipeline`.

**Comment by svmundada** [comment]
We are using cloudevents for notifications and not inheriting `annotations/labels` for `started` type of events is causing to us miss the context of those cloudevents. `started` events are useful to acknowledge whether a process has started or not, so it's a bit important to us while moving entire notification to cloudevents. It'd be great to have some solution to this.

For now, we are manually adding annotations/labels to get away with this.
