### ISSUE TITLE
tekton/tools/entrypoint permission denied troubleshooting help

### ISSUE THREAD

**Issue by ericsgagnon** [tektoncd/pipeline#3867]
Just trying tekton and can't get a successful taskrun on the hello world task in the getting started guide.

I'm running kubernetes 1.20 on rhel 7 selinux permissive mode.
Installed tekton by: kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml
kubectl apply the hello world task from the tutorial:
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello
spec:
  steps:
    - name: hello
      image: ubuntu
      command:
        - echo
      args:
        - "Hello World!"

tkn task start hello
tkn taskrun logs hello-run-xxxxx -f -n default
[hello] standard_init_linux.go:211: exec user process caused "permission denied"
container step-hello has failed

kubectl get po hello-run-xxxxx-pod-xxxxx -o yaml > output.yaml
edit output.yaml to run ls -alh /tekton/tools
the pod runs the ls command successfully and shows: 
--wx--x--x 1 65532 65532  28M Apr  4 08:47 entrypoint

I've also run it on my ubuntu 18.04 homelab cluster with no issue. I've compared the two pod specs between the clusters and can't find a difference.

I'm at a loss. The only think of is maybe I need to enable some flags. Does anyone have any ideas where I should look?
Thank you,
Eric

**Comment by sbwsg** [comment]
hey @ericsgagnon I'm not familiar with running pipelines on rhel but the fact that this is a permissions issue implies to me that maybe the TaskRun needs to be executed with a different `securityContext`.  It could be that containers are not allowed to run as root in your cluster or it might be that the uid / gid is being set to something unexpected by another component (e.g. an admission webhook).

Either way, it would be helpful if you could share the failing TaskRun YAML.  `kubectl get -o yaml taskrun hello-run-xxxxx` should net you that.

**Comment by ericsgagnon** [comment]
@sbwsg it looks like trying tekton may have exposed an underlying issue with my cluster. I tried using ubuntu images for both init and container, copying "ls"  from the init to /tekton/tools/ and running /tekton/tools/ls in the container and got the same permission denied error. You're probably right - it seems like it might be an issue with permissions on files copied to emptydir. I'll scrape the kubernetes forums to see if this is a common issue on rhel.
