### ISSUE TITLE
Pipelines in bundles do not go through defaulting before validation

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/pipeline#3874]
# Expected Behavior

Pipelines can be stored in bundles in the same format they are stored in git - i.e. with default not specified.

# Actual Behavior

Pipelines must have default specified, specifically the type must be specified for all parameters, otherwise validation errors are triggered at execution time:

```
Pipeline /zero2cd can't be Run; it has an invalid spec: invalid value: : tasks[2].taskSpec.params.image.type
```

# Steps to Reproduce the Problem

1. Create a pipeline with implicit param type
2. Store it in a bundle
3. Enable OCI in the feature flags
4. Run the pipeline from the bundle

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-21T14:51:23Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"} 
```

- Tekton Pipeline version:

```
Client version: 0.17.0
Pipeline version: v0.23.0
Triggers version: v0.12.1
Dashboard version: v0.15.0
```

**Comment by jerop** [comment]
/remove-lifecycle stale we still need to default pipelines in bundles

**Comment by nikhil-thomas** [comment]
Im unassiging myself. At present, Im stretched too thin. 🧑‍💻 🐎
If I take this on, this might continue to starve. 🤓 
Kindly excuse this delayed change.
