### ISSUE TITLE
failed to create task run pod in namespace with resource quotas

### ISSUE THREAD

**Issue by eniomachado** [tektoncd/pipeline#3879]
I'm doing an simple test with tekton, I'm using in openshift but i can't deploy in any namespace that has resource quotas.

$ oc get taskruns.tekton.dev -o yaml

apiVersion: v1
items:
- apiVersion: tekton.dev/v1beta1
  kind: TaskRun
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"tekton.dev/v1beta1","kind":"Task","metadata":{"annotations":{},"name":"socketclient","namespace":"oxt-dev"},"spec":{"steps":[{"args":["echo test git app\ncurl https://git.app.com.br -I\necho -----------------------------------\n\necho test github\ncurl https://github.com/tektoncd -I\necho -----------------------------------"],"command":["/bin/bash","-c"],"image":"quay.io/openshift/origin-cli:latest","name":"apply","resources":{"limits":{"cpu":"800m","memory":"1Gi"},"requests":{"cpu":"60m","memory":"256Mi"}},"workingDir":"/workspace/source"}],"workspaces":[{"name":"source"}]}}
      pipeline.tekton.dev/release: devel
    creationTimestamp: "2021-04-14T12:54:04Z"
    generation: 1
    labels:
      app.kubernetes.io/managed-by: tekton-pipelines
      tekton.dev/pipeline: socketclient-pipeline
      tekton.dev/pipelineRun: socketclient-pipeline-run-xtv4m
      tekton.dev/pipelineTask: socketclient
      tekton.dev/task: socketclient
    managedFields:
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
            f:pipeline.tekton.dev/release: {}
          f:labels:
            .: {}
            f:tekton.dev/pipeline: {}
            f:tekton.dev/pipelineRun: {}
            f:tekton.dev/pipelineTask: {}
            f:tekton.dev/task: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"662d7c4e-dda1-47b8-8313-3a584298f328"}:
              .: {}
              f:apiVersion: {}
              f:blockOwnerDeletion: {}
              f:controller: {}
              f:kind: {}
              f:name: {}
              f:uid: {}
        f:spec:
          .: {}
          f:resources: {}
          f:serviceAccountName: {}
          f:taskRef:
            .: {}
            f:kind: {}
            f:name: {}
          f:timeout: {}
          f:workspaces: {}
        f:status:
          .: {}
          f:conditions: {}
          f:podName: {}
          f:startTime: {}
          f:taskSpec:
            .: {}
            f:steps: {}
            f:workspaces: {}
      manager: openshift-pipelines-controller
      operation: Update
      time: "2021-04-14T12:54:05Z"
    name: socketclient-pipeline-run-xtv4m-socketclient-9frl2
    namespace: oxt-dev
    ownerReferences:
    - apiVersion: tekton.dev/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: PipelineRun
      name: socketclient-pipeline-run-xtv4m
      uid: 662d7c4e-dda1-47b8-8313-3a584298f328
    resourceVersion: "215213826"
    selfLink: /apis/tekton.dev/v1beta1/namespaces/oxt-dev/taskruns/socketclient-pipeline-run-xtv4m-socketclient-9frl2
    uid: bbedf4c2-ce29-4198-9cef-618b0bbd7feb
  spec:
    resources: {}
    serviceAccountName: pipeline
    taskRef:
      kind: Task
      name: socketclient
    timeout: 1h0m0s
    workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: source-pvc
  status:
    conditions:
    - lastTransitionTime: "2021-04-14T12:54:05Z"
      message: 'failed to create task run pod "socketclient-pipeline-run-xtv4m-socketclient-9frl2":
        pods "socketclient-pipeline-run-xtv4m-socketclient-9frl2-pod-5z8bl" is forbidden:
        failed quota: resource-quota-oxt: must specify limits.cpu,limits.memory,requests.cpu,requests.memory.
        Maybe missing or invalid Task oxt-dev/socketclient'
      reason: CouldntGetTask
      status: "False"
      type: Succeeded
    podName: ""
    startTime: "2021-04-14T12:54:05Z"
    taskSpec:
      steps:
      - args:
        - |-
          echo test git app
          curl https://git.app.com.br -I
          echo -----------------------------------

          echo test github
          curl https://github.com/tektoncd -I
          echo -----------------------------------
        command:
        - /bin/bash
        - -c
        image: quay.io/openshift/origin-cli:latest
        name: apply
        resources:
          limits:
            cpu: 800m
            memory: 1Gi
          requests:
            cpu: 60m
            memory: 256Mi
        workingDir: /workspace/source
      workspaces:
      - name: source
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

**Comment by eniomachado** [comment]
$ oc apply -f socketclient-task.yaml
task.tekton.dev/socketclient created
$ oc apply -f pipeline.yaml
pipeline.tekton.dev/socketclient-pipeline created
$ oc get task
NAME           AGE
socketclient   5m51s
 $ oc get pipeline
NAME                    AGE
socketclient-pipeline   9m26s
 $ oc get pipelinerun
NAME                              SUCCEEDED   REASON   STARTTIME   COMPLETIONTIME
socketclient-pipeline-run-xtv4m   False       Failed   8m53s       8m53s

$ cat socketclient-task.yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: socketclient
spec:
  workspaces:
  - name: source
  steps:
    - name: apply
      image: quay.io/openshift/origin-cli:latest
      workingDir: /workspace/source
      command: ["/bin/bash", "-c"]
      args:
        - |-
          echo test git app
          curl https://git.app.com.br -I
          echo -----------------------------------

          echo test github
          curl https://github.com/tektoncd -I
          echo -----------------------------------
      resources:
          requests:
            memory: 256Mi
            cpu: 60m
          limits:
            memory: 1Gi
            cpu: 800m

$ cat pipeline.yaml
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: socketclient-pipeline
spec:
  workspaces:
  - name: shared-workspace
  tasks:
  - name: socketclient
    taskRef:
      name: socketclient
    workspaces:
    - name: source
      workspace: shared-workspace

**Comment by vdemeester** [comment]
@eniomachado are you setting up `LimitRange` too with your `ResourceQuota` ?
The error is `failed quota: resource-quota-oxt: must specify limits.cpu,limits.memory,requests.cpu,requests.memory`, which means using `ResourceQuota` forces you to set those values. Those can be set by step and/or using `LimitRange` on the namespace. 
Note that I think there is gap here, as documented a bit in https://github.com/tektoncd/pipeline/issues/2986. We need to enhance/fix how we handle resources requests/limits.
