### ISSUE TITLE
Add `enable-api-fields: alpha` to pipeline's CI runs

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/pipeline#3896]
### Feature request

Once https://github.com/tektoncd/pipeline/pull/3881 is merged we'll be in a good position to start testing `alpha` fields in our CI. In order to exercise new alpha features we'll need to add an additional round of integration tests and example runs in a cluster with `enable-api-fields: alpha` set in the feature-flags configmap.

### Use case

Contributors to Tekton Pipelines should be able to observe the effects of their changes in environments with both "alpha" and "stable" feature gates during CI runs.

**Comment by pritidesai** [comment]
thanks @sbwsg yup, we need this to validate any new alpha features being added. I have bumped up the priority for the same reason.
