### ISSUE TITLE
TaskRun fails with CouldntGetTask reason when API server returns retryable error on pod creation

### ISSUE THREAD

**Issue by SaschaSchwarze0** [tektoncd/pipeline#3902]
# Expected Behavior

When a TaskRun creates a pod, all kind of things can go wrong. There might be reasons for the creation to be blocked if limitranges or resourcequotas or permissions or any validating webhook says "no". In that case it makes sense that the TaskRun is immediately marked as failed and not anymore considered.

But, there can also be temporary failures where a retry would make sense. I observed a TaskRun with this message:

`failed to create task run pod "kaniko-wzc5f-7xq7k": Post "https://172.21.0.1:443/api/v1/namespaces/3ap0ooqhb24/pods": http2: server sent GOAWAY and closed the connection; LastStreamID=285, ErrCode=NO_ERROR, debug="". Maybe invalid TaskSpec`

The [`handlePodCreationError`](https://github.com/tektoncd/pipeline/blob/v0.21.0/pkg/reconciler/taskrun/taskrun.go#L516-L543) function atm is not considering many kinds of errors. Is there some consideration to perform retries for certain failures? (Whether CouldntGetTask is a good reason for this "catch-all" is another bot not so important question.)

# Actual Behavior

TaskRun is marked failed if the pod creation fails with a potentially retryable error.

# Steps to Reproduce the Problem

The root cause is an intermittent error that has no specific steps for reproduction.

# Additional Info

- Kubernetes version: 1.19.7
- Tekton Pipeline version: 0.21.0

**Comment by SaschaSchwarze0** [comment]
Hit a similar error which would have been worth a retry as the root cause was a network hickup:

> {"level":"error","ts":"2021-07-29T18:55:28.323Z","logger":"tekton-pipelines-controller","caller":"taskrun/taskrun.go:430","msg":"Failed to create task run pod for taskrun \"buildrun-consumption-q2wph-j7mt9\": failed to create task run pod \"buildrun-consumption-q2wph-j7mt9\": **translating TaskSpec to Pod: rpc error: code = Unavailable desc = transport is closing.** Maybe invalid TaskSpec","commit":"18aa510","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.taskrun.Reconciler","knative.dev/kind":"tekton.dev.TaskRun","knative.dev/traceid":"b47d8cf9-18f2-4bf1-80d1-0ced41af0bbb","knative.dev/key":"bufes7u1dzd/buildrun-consumption-q2wph-j7mt9","stacktrace":"github.com/tektoncd/pipeline/pkg/reconciler/taskrun.(*Reconciler).reconcile\n\tgithub.com/tektoncd/pipeline/pkg/reconciler/taskrun/taskrun.go:430\ngithub.com/tektoncd/pipeline/pkg/reconciler/taskrun.(*Reconciler).ReconcileKind\n\tgithub.com/tektoncd/pipeline/pkg/reconciler/taskrun/taskrun.go:194\ngithub.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1beta1/taskrun.(*reconcilerImpl).Reconcile\n\tgithub.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1beta1/taskrun/reconciler.go:237\ngithub.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tgithub.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller/controller.go:522\ngithub.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller.(*Impl).RunContext.func3\n\tgithub.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller/controller.go:460"}

**Comment by SaschaSchwarze0** [comment]
Stumbled over yet another error. When there is a webhook in place for pod creations and this - for whatever reason - is not responsive:

> {"level":"error","ts":"2021-07-30T13:45:07.810Z","logger":"tekton-pipelines-controller","caller":"taskrun/taskrun.go:430","msg":"Failed to create task run pod for taskrun \"buildrun-consumption-qxrmb-7998b\": failed to create task run pod \"buildrun-consumption-qxrmb-7998b\": **Internal error occurred: failed calling webhook \"*WEBHOOK*\": Post \"https://*WEBHOOK*.svc:443/inject?timeout=30s\": context deadline exceeded**. Maybe invalid TaskSpec","commit":"18aa510","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.taskrun.Reconciler","knative.dev/kind":"tekton.dev.TaskRun","knative.dev/traceid":"c38c2377-ad98-41d9-8962-b67e8bc221df","knative.dev/key":"7ppq5adj7qg/buildrun-consumption-qxrmb-7998b","stacktrace":"github.com/tektoncd/pipeline/pkg/reconciler/taskrun.(*Reconciler).reconcile\n\tgithub.com/tektoncd/pipeline/pkg/reconciler/taskrun/taskrun.go:430\ngithub.com/tektoncd/pipeline/pkg/reconciler/taskrun.(*Reconciler).ReconcileKind\n\tgithub.com/tektoncd/pipeline/pkg/reconciler/taskrun/taskrun.go:194\ngithub.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1beta1/taskrun.(*reconcilerImpl).Reconcile\n\tgithub.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1beta1/taskrun/reconciler.go:237\ngithub.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tgithub.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller/controller.go:522\ngithub.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller.(*Impl).RunContext.func3\n\tgithub.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller/controller.go:460"}

Also something that is worth a retry rather than failing the TaskRun.

**Comment by afrittoli** [comment]
Thanks for this report @SaschaSchwarze0. 

The only error that we consider as a temporary one today is the [quota exceeded](https://github.com/tektoncd/pipeline/blob/49244c66b1a15cd6d104ec4a0f8a2104c3aa571a/pkg/reconciler/taskrun/taskrun.go#L693). It may be difficult for other errors to know whether they are permanent ones or not. But there may be other cases where a retry is a valid option.

The issues you mentioned in this ticket might be related to either the API or the webhook service being unresponsive. 
They could be broken, in which case a retry would not help, or the could be under load, in which case again a retry might not be the best alternative.

In general, if Tekton has no specific knowledge about the error returned, it feels ok to me to stop.
But I'd be happy to retry for issues that we can agree are transient. 
If an issue is not transient, we risk retrying forever, or we would have to introduce a retry counter.

**Comment by afrittoli** [comment]
@tektoncd/core-maintainers thoughts? ^^^
