### ISSUE TITLE
Starting PipelineRun in Pending Or Cancelled State Doesn't Add Pipeline Label

### ISSUE THREAD

**Issue by andrewballantyne** [tektoncd/pipeline#3903]
# Expected Behavior

When I create a PipelineRun against a `pipelineRef.name` to an existing Pipeline I have on my OpenShift cluster, a label is added for me `tekton.dev/pipeline = <pipelineName>`. I'd expect this to happen for `spec.status` of `PipelineRunPending` and `PipelineRunCancelled` as well, when they are included.

# Actual Behavior

However, when I create the same PipelineRun with the same configuration (pipelineRef, name, labels, etc) but with an added `spec.status` to either `PipelineRunCancelled` or `PipelineRunPending`, it starts and omits the label I used to find all related PipelineRuns to my Pipeline. I'm no longer able to find related PipelineRuns, especially those in pending state to start them.

# Steps to Reproduce the Problem

1. Create any PipelineRun (Pipeline spec or ref) that has no labels and see the controller/operator adds them

2. Repeat the process but add `status: PipelineRunCancelled` or `status: PipelineRunPending` to the spec and push that PipelineRun

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.0-rc.0+6143dea", GitCommit:"6143dea8e6a5046b467a67f7d1fda8e63833a2e7", GitTreeState:"clean", BuildDate:"2021-04-25T16:18:28Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
OpenShift Pipelines Operator 1.4.0
Pipeline version: v0.22.0
Triggers version: v0.12.1
```

**Comment by jerop** [comment]
Thank you for the issue report @andrewballantyne!

Fixing it in https://github.com/tektoncd/pipeline/pull/4163
