### ISSUE TITLE
Question regarding sidecar exit code 137

### ISSUE THREAD

**Issue by badamowicz** [tektoncd/pipeline#3906]
Hi Tekton team!
There's one thing when working with Tekton pipelines that always confuses me a bit. If a Pod which has been created by a TaskRun ends, alle the sidecars of the Pod will end with this status:
```
    State:          Terminated
      Reason:       Error
      Exit Code:    137
```
This will also make the Pod fail with status ERROR though actually no errors occured at all. This is not the OOM issue mentioned in many other posts here!
So I digged down the source code and found this in file _pkg/pod/entrypoint.go_:
```
...
217                 for j, c := range newPod.Spec.Containers {
218                     if c.Name == s.Name && c.Image != nopImage {
219                         updated = true
220                         newPod.Spec.Containers[j].Image = nopImage
221                     }
222                 }
...
```
In line 220 the container's image is replaced with a nopImage. I assume that this will sooner or later lead to a SIGKILL signal (=137) maybe issued by the _kubelet_.
Please allow me to aks these questions:
1. Is my assumption right?
2. Is this intentional behaviour by Tekton or is it worth a closer look?
3. Should I file a bug report on this issue providing more detailed information?

Thanks in advance!
Bernd

**Comment by sbwsg** [comment]
This is indeed how Tekton stops sidecars once a Task's steps are complete.  We document the approach to sidecars in [our dev docs here](https://github.com/tektoncd/pipeline/tree/main/docs/developers#handling-of-injected-sidecars).

The `nop` image is unlikely to have the command which the sidecar ran with, so it will immediately fail when it attempts to start up. This is one possible source of the error code. Another possible source is that the `nop` image _does_ include the command which the sidecar ran with. This can happen, for example, when the `nop` image is something other than the default shipped with Pipelines. The image is overrideable via the `-nop-image` flag on the Tekton Pipelines deployment: https://github.com/tektoncd/pipeline/blob/main/config/controller.yaml#L66  In this case the command may have run inside the `nop` image and errored out with its own exit code.

**Comment by badamowicz** [comment]
Obviously I missed exactly that part of the dev docs. So many thanks for clarifying things!
