### ISSUE TITLE
Schedule pipelines to be run on a specific time

### ISSUE THREAD

**Issue by bharathvenkatrajan** [tektoncd/pipeline#3925]
### Feature request

Define cron like schedules for running pipelines. 

### Use case

Jenkins and other major CI/CD tools have scheduling capabilities for pipelines. I guess this is a major feature that is missing in Tekton. Currently, as a workaround, I am using the tkn cli in a kubernetes cron job to trigger the pipeline. But if this can be built into the pipeline controller, it'll be very helpful. Reduces dependencies and technical debt.

**Comment by vdemeester** [comment]
> Jenkins and other major CI/CD tools have scheduling capabilities for pipelines. I guess this is a major feature that is missing in Tekton. Currently, as a workaround, I am using the tkn cli in a kubernetes cron job to trigger the pipeline. But if this can be built into the pipeline controller, it'll be very helpful. Reduces dependencies and technical debt.

Hey @bharathvenkatrajan, thanks for the issue. On "Reduces dependencies and technical debt", I am not sure I follow. `cronjob` are a k8s construct, and tekton run on k8s, so it's not a dependency, it's something we can rely on, just like we rely on `pods` to be a construct. I think it even make more sense to not have it in the core of tekton at least (aka `tektoncd/pipeline`) as then, it can be implemented in anyway by external construct — a parallel here, in k8s, would be `pod`, `job` and `cronjob`, a `pod` doesn't have a capability to run at a given time, you use cronjob and job for that. As @souleb said, I am eager to have more detail on how k8s cronjob do not fit your use case.

**Comment by vdemeester** [comment]
@bharathvenkatrajan right, the `tkn` documentation is lacking and we need to provide way better helping pages, but it is possible to provide workspace spec in a non-interactive way: som exmaples from https://github.com/tektoncd/cli/blob/main/docs/reference/cmd/pipeline_start.md#examples:

```
	--workspace name=my-secret,secret=secret-name \
	--workspace name=my-config,config=rpg,item=ultimav=1 \
	--workspace name=my-empty-dir,emptyDir="" \
	--workspace name=my-pvc,claimName=pvc1,subPath=dir
```

**Comment by bharathvenkatrajan** [comment]
@vdemeester Oh, great! Exactly what I wanted. Yeah, if possible, also update the CLI’s man page :)

**Comment by vinamra28** [comment]
hi @bharathvenkatrajan, recently a PR https://github.com/tektoncd/cli/pull/1354 got merged which might fix your issue. This will be available in the latest release [0.19](https://github.com/tektoncd/cli/releases/tag/v0.19.0) which will soon be announced.

**Comment by vinamra28** [comment]
@bharathvenkatrajan can we close this issue if it's resolved?

**Comment by bharathvenkatrajan** [comment]
@vinamra28 sure thanks!
