### ISSUE TITLE
Split / Join in Pipelines

### ISSUE THREAD

**Issue by wkulhanek** [tektoncd/pipeline#3929]
### Feature request

It appears there is currently no way to split / join a Pipeline. This is a basic feature that is missing - and will prevent broad adoption of Tekton Pipelines. Almost every Pipeline that I build (besides simple demo ones) requires this capability.

Note that this is different from parallel execution of tasks where all tasks will run.

### Use case

The use case is actually quite simple.

In my pipeline I have Task A.

After Task A I either need to execute Task B1 or Task B2 - but not both -> Split. This could also be B1/B2/B3/B4/... In my example I have a mutually exclusive when condition on tasks B1 and B2 (is condition / is not condition) guaranteeing that one task gets executed.

After either task finishes I would like to continue the pipeline with task C -> Join.

I tried to set this up with runAfter clauses on the tasks - but the pipeline just ends after either Task B1 or B2 is executed - Task C is never reached.

**Comment by vdemeester** [comment]
/cc @pritidesai @jerop 
I think it might be covered by [TEP-0059](https://github.com/tektoncd/community/blob/main/teps/0059-skip-guarded-task-only.md) but I wasn't sure as I didn't see described in the motivation/use cases.

**Comment by wkulhanek** [comment]
@jerop The simple case that I fell over was that I built a pipeline that builds and deploys a Java based application.

But the actual deployment was happening either via a "Deployment" or via a "Knative Service" based on a boolean flag on the PipelineRun. 

So all my steps in the pipeline are the same (git checkout, maven build, image build, tag, ...). The only thing that's different is how to update the "application" in my namespace.

**Comment by wkulhanek** [comment]
@afrittoli This is exactly what I had. Except I would suggest that just using the "condition" on Task A would be too narrow. In my case the condition is a boolean input parameter on the PipelineRun itself rather than being generated by Task A.

**Comment by pritidesai** [comment]
Hi @wkulhanek the simple use case you have provided in the description is now supported with branch scoped `when` expressions (released in `0.27`). Please refer to the release [notes](https://github.com/tektoncd/pipeline/releases/tag/v0.27.0) or the documentation on how to configure it. 

We have introduced a new feature flag `scope-when-expressions-to-task` (set to `false` by default). Setting it to `true` will enable branch scoped when expressions i.e. task `C` will be executed after either `B1` or `B2`.

`when` expressions guards `C` (and never reached) if it relies on the result of either `B1` or `B2`, a new feature is coming to address this use case where `C` can continue executing without actual results - demoed in the [API WG](https://docs.google.com/document/d/17PodAxG8hV351fBhSu7Y_OIPhGTVgj6OJ2lPphYYRpU/edit#heading=h.qq31rcli4y3f).

Hope it helps, let me know if you there is anything missing 🙏
