### ISSUE TITLE
Emit Warning Events for Deprecated Features

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/pipeline#3947]
### Feature request

Emit events when a TaskRun( / Task) or PipelineRun( / Pipeline) utilizes a feature that we intend to deprecate.

### Use case

As a person administering a Tekton cluster I would like to query that cluster to see if any of the Tekton resources my teams have created contain deprecated features. I would like to be able to do this either 1) by querying the cluster in-the-moment or 2) through ongoing monitoring / alerts.

As a developer on the Tekton Pipelines project I would like a uniform way to communicate deprecations to operators during day-to-day operation of a Tekton cluster. This would be in addition to out-of-band communications like posting to the google group, making announcements in WGs, etc.

As a developer of an alpha feature (behind the "alpha" feature gate) I want a way to alert operators when my alpha feature is being removed or changed in a backwards-incompatible way during its development.

Example usage:

1. I run the comand `kubectl get events --field-selector involvedObject.kind=TaskRun,type=Warning,reason=Deprecation` and get a summary of all the taskruns that have involved deprecated features recently.

2. I check my monitoring dashboard and search for the equivalent of "involvedObject.kind=PipelineRun,type=Warning,reason=Deprecation" and get the history of deprecation warnings emitted by my cluster from the last month.

### Developer Experience

We could provide a function similar to `EmitError` in `pkg/reconciler/events/event.go`. E.g. `EmitDeprecationWarning(runtime.Object, message string)` that is called if a deprecated feature is detected in use. We'd likely want some way to limit the event emission to only the first (or last?) reconcile of a given taskrun/pipelinerun to avoid spamming deprecation warnings.

**Comment by sbwsg** [comment]
A couple immediate problems with this idea:

1. It won't help users who don't upgrade to later versions: if an operator pins to 0.21.0 but a deprecation warning is added in 0.25.0 then this user won't receive it.
2. Some operators may not want to expose deprecation warnings to their teams / users.  (Who?  And Why?)
3. Some deprecations aren't as easily detected programatically (for example removing `HOME` default isn't related to specific detectable feature of Tasks).

A different approach would be to emit the events on the Pipelines deployment itself rather than individual TaskRuns / PipelineRuns.

**Comment by jerop** [comment]
/remove-lifecycle stale

would be helpful with migration when features are deprecated
