### ISSUE TITLE
Building and publishing Windows images

### ISSUE THREAD

**Issue by aiden-deloryn** [tektoncd/pipeline#3951]
Currently Ko is not able to build images for Windows (see https://github.com/google/ko/issues/361) and adding support for this is potentially a complicated problem to solve. In the interest of progressing development on Windows support for Tekton, I think it would be beneficial to investigate alternatives for building and publishing Windows images until this functionality is supported by Ko. 

A possible workaround would be to build images using Docker. I have an example of a Dockerfile for the entrypoint binary which I have been using for testing here: https://github.com/TensorWorks/pipeline/blob/7286fc699d4585ecbf87eedc9e00688f7b0daf5c/images/windows/entrypoint/Dockerfile

Some pros:
- This does not impact the current workflow for Linux development
- Dockerfiles are easy to read and understand

Some cons:
- Building Windows images will depend on Docker and a Windows host machine
- There would be some additional upkeep required to maintain Windows images

I'm keen to get some feedback on this approach and also encourage others to share ideas if you think there might be a better alternative. 

Related TEP: https://github.com/tektoncd/community/pull/383
Related Issue: https://github.com/tektoncd/pipeline/issues/1826

**Comment by imjasonh** [comment]
+1 to unblocking development however you can. I don't know if we should include a windows-mode to the release plumbing, ideally we'd be able to get ko working before that becomes necessary 🤞 , but if you're able to build an entrypoint image and configure Tekton to use it, that'll help us find out about whatever the next thing is that breaks and give us more time to fix it. 👍
