### ISSUE TITLE
Git credentials are not available between steps in the same task

### ISSUE THREAD

**Issue by cybul7** [tektoncd/pipeline#3953]
# Expected Behavior

Git config should be "visible" in all steps.
I don't have this error when I use **v0.20.1**.

# Actual Behavior

I have few steps in task. 1st one is a git setup and the next one is git add and commit.
I have a problem with second task, it doesn't see the git config setup from the previous one.

First step output:
```
...
credential.https://git.XXXXXX
user.email=tekton-bot@mail.com
user.name=Tekton bot
...
```

In the "git commit step" output we have:

```
[ERROR] The git-commit command failed.
[ERROR] Command output:
[ERROR] 
[ERROR] *** Please tell me who you are.
[ERROR] 
[ERROR] Run
[ERROR] 
[ERROR]   git config --global user.email "you@example.com"
[ERROR]   git config --global user.name "Your Name"
```

# Additional Info

- Kubernetes version:
1.18.8

- Tekton Pipeline version:
0.24.1

**Comment by sbwsg** [comment]
It could be helpful to see the TaskRun and Pod YAML, are you able to share those?  Make sure to double-check and remove any sensitive info before posting. Cheers!
