### ISSUE TITLE
Timeout support for custom tasks.

### ISSUE THREAD

**Issue by ScrapCodes** [tektoncd/pipeline#3962]
### Feature request

Timeout support is already discussed in brief in the [TEP-0002](https://github.com/tektoncd/community/blob/main/teps/0002-custom-tasks.md#timeout), but not yet implemented. 

### Use case

Custom tasks, does not know that pipeline running has a configured timeout. If timeout information is propagated to custom tasks, then they have the opportunity to cleanly release the resources and behave in a predictable manner.

**Comment by ScrapCodes** [comment]
This will require an addition of API fields, we will update the TEP with the appropriate details.

**Comment by imjasonh** [comment]
I think there are two separate timeout issues we should address and support as best we can, separately:

1. A Pipeline configuring that a Custom Task Run contained within it should have a timeout (`.task.timeout: 10m`)
2. A Pipeline configuring a pipeline-wide timeout, which when hit, cancels any ongoing Custom Task Runs that might be ongoing. I think this is really just a sub-case of Custom Task cancellation, which we should also support.

In either case, the actual cancellation or timeout handling isn't up to Tekton to enforce -- it can tell the Run "please stop if you haven't finished within 10m" or "the PipelineRun containing you has timed out; please stop now", but those signals can only be sent to the Custom Task controller, which can still ignore them. It's possible the operation is not stoppable, or that stopping just isn't implemented yet.

In any case, Tekton controllers should never forcibly update the .status.conditions of a Run directly, that responsibility belongs to the Custom Task controller.

(Having Tekton share responsibility for this was discussed in the original TEP, but we ended up deciding that Tekton creates Runs, and Custom Task controllers manage them after that, alone. We could always revisit this decision.)

For (1), it'd be up to the Custom Task CRD type to express a `.spec.timeout` field that the user can set to express the intent "please stop after 10m", and for their controller to respect that and act accordingly.

For (2), the Run type can include a `.spec.status = "Cancelled"` field (possibly with future status values like `Paused`) like TaskRuns and PipelineRuns have, and when the containing PipelineRun times out, it would update that `.spec.status` to `"Cancelled"`, and the Custom Task controller would notice and take action if possible, then update `.status.conditions` to report whether cancellation has worked. This matches how TaskRuns work within a PipelineRun that gets cancelled or times out.

**Comment by ScrapCodes** [comment]
@imjasonh it makes sense to me. Presently we do not update custom task status field to `Cancelled`. For example, it has to go through all the custom tasks and see if there is any one timed out and then update the `.spec.status` to `cancelled`. WDYT?

**Comment by imjasonh** [comment]
Yeah that change looks like it's going in the right direction. End-to-end tests demonstrating how the Pipelines controller works with a properly implemented (and maybe improperly implemented?) Custom Task controller would be very helpful as well.
