### ISSUE TITLE
In Openshift for "affinity-assistant" getting permission problem

### ISSUE THREAD

**Issue by skaegi** [tektoncd/pipeline#3968]
What's happening is in pod we're getting... `"chdir to cwd (\"/home/nonroot\") set in config.json failed: permission denied"` because we're getting assigned `openshift.io/scc: restricted`. 

Looking at the securityContext I see...
"securityContext": {
      "fsGroup": 1000660000,
      "seLinuxOptions": {
        "level": "s0:c26,c5"
      }
    }
Presumably the `nonroot` scc would work fine.

I'm wondering if we can make it so this pod can either run restricted or failing that provide a securitycontext that sets a runasuser so scc will have some basis to prefer nonroot if it can -- or perhaps something else clever.

**Comment by nikhil-thomas** [comment]
In understand the pain. 🧑‍💻 

tektoncd/operator, creates additional ClusterRole and Rolebinding, https://github.com/tektoncd/operator/blob/main/cmd/openshift/operator/kodata/tekton-pipeline/0.22.0/01-clusterrole.yaml.

With these added, the controller works without additional modifications.

**Comment by skaegi** [comment]
Right - we have something similar for the controller -- the issue is for the affinity assistant. Even if we set a policy where all authenticated users can `use nonroot`   there's no "hints" in the pod definition to steer towards `nonroot` vs `restrictive` even if that is something. I guess a bit of a hammer approach is to create a new SCC clone of `nonroot` with higher priority.

**Comment by nikhil-thomas** [comment]
cc @chmouel

**Comment by seanmmills** [comment]
Could this be related to #3748 ?

**Comment by seanmmills** [comment]
Upgrading to OpenShift 4.7.11+ will resolve the issue.  RedHat upgraded the runc version to pick up this fix: https://github.com/opencontainers/runc/commit/5e0e67d76cc99d76c8228d48f38f37034503f315
