### ISSUE TITLE
Reference repo support for large repos in git pipeline resource

### ISSUE THREAD

**Issue by hokadiri** [tektoncd/pipeline#3969]
I see there's currently no support for reference repo. https://github.com/tektoncd/pipeline/blob/b7fa888082bd20e08edc3b89b6b4d52ed4f00651/pkg/git/git.go#L61

My CI use case uses a large repo which requires a the use of a reference repo to clone it quickly. shallow clone is not sufficient for my use case.   

Jenkins under the hood provides reference repo access by doing this:  
```
$ git init <repo>
$ cd <repo>
$ echo "/path/to/reference/repo/.git/objects" > .git/objects/info/alternates
$ git config remote.origin.url  <repo url e.g https://github.com/gocd/somerepo>
$ git config --add remote.origin.fetch +refs/heads/master:refs/remotes/origin/master
$ git fetch --no-tags --progress <repo url e.g https://github.com/gocd/somerepo> +refs/heads/master:refs/remotes/origin/master
$ git checkout master
```

How much appetite is there for adding reference repo support for git pipeline resources?

**Comment by nikhil-thomas** [comment]
I think, https://github.com/tektoncd/catalog/issues/735 could be the immediate fix.

Do you prefer using PipelineResource (type: git) more than the git-clone task.
if yes, why? 🧑‍💻 🙂

**Comment by hokadiri** [comment]
@nikhil-thomas , No preference. just need something with robust git options.
