### ISSUE TITLE
initial `git fetch` will fail if no master branch exists

### ISSUE THREAD

**Issue by raul-gherman** [tektoncd/pipeline#3975]
# Expected Behavior
`master` and `main` branch should be treated the same

# Actual Behavior
{"level":"error","ts":1622011863.8723476,"caller":"git/git.go:54","msg":"Error running git [fetch --recurse-submodules=yes --depth=1 origin --update-head-ok --force master]: exit status 128\nfatal: couldn't find remote ref master\n","stacktrace":"github.com/tektoncd/pipeline/pkg/git.run\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:54\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:145\nmain.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:52\nruntime.main\n\truntime/proc.go:204"}
{"level":"fatal","ts":1622011863.872459,"caller":"git-init/main.go:53","msg":"Error fetching git repository: failed to fetch [master]: exit status 128","stacktrace":"main.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:53\nruntime.main\n\truntime/proc.go:204"}

# Steps to Reproduce the Problem
try to follow the steps at https://katacoda.com/tektoncd/scenarios/dashboard ...

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

tried w/ v0.20.0 and v0.24.0

**Comment by vdemeester** [comment]
@raul-gherman hum, in the katacode, the branch used is `master`. In recent version of tekton, if you don't specify a revision, it should use the remote HEAD (and thus be main, master, or anything that is set as the default on the remote) — but if you specify a revision, it will try it.

**Comment by AlanGreene** [comment]
Thanks for reporting this @raul-gherman. I've opened a PR to update the Katacoda tutorials to use the latest releases of both Pipelines and Dashboard as well as updated some of the instructions to match the latest functionality.
https://github.com/tektoncd/website/pull/275

**Comment by AlanGreene** [comment]
Thanks again for reporting this @raul-gherman. I've confirmed the change above is now live.

/close
