### ISSUE TITLE
Dynamic number of tasks

### ISSUE THREAD

**Issue by skk2142** [tektoncd/pipeline#3991]
Feature request
Creating tasks at runtime.

Use case
I want to run certain number of tasks in images that are determined at the runtime. Each task is a command that needs to run in some container who image is also determined at runtime. The number of these tasks are unknown at the time the pipeline is created: all we know is the command that needs to run in each of these containers. One way is to enumerate the lists of all tasks and create a pipeline with it and determine the tasks that actually need to run at runtime. However, as we add more of these tasks, we need to updated the pipeline. Is it possible to add tasks to the pipeline at runtime?

**Comment by AlanGreene** [comment]
The experimental [Task loop custom task](https://github.com/tektoncd/experimental/tree/main/task-loops) allows for running a Task in a loop with varying parameter values, seems like that might be of interest.

**Comment by skk2142** [comment]
This is exactly what I was looking for!
