### ISSUE TITLE
Improve run objects garbage collection

### ISSUE THREAD

**Issue by dbazhal** [tektoncd/pipeline#3993]
### Feature request

When i delete pipeline, I'd like all it's pipelineruns to be also removed. Same for tasks.
That could be easily done by mutating hook, adding ownerReferences field to all run objects https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#owners-and-dependents

### Use case

I create pipelines often, and I remove them often. So when I remove pipelines, there are many run objects left in my cluster, and if I leave it for some time, tekton controller just starts freezing on reconciles(reconciling few thousands of run objects).

**Comment by vdemeester** [comment]
A related work is tracked on the operator: https://github.com/tektoncd/operator/issues/209. We do not add ownerReferences on PipelineRun as a user might want to keep them (for history/log purpose) even if/when the Pipeline is gone.

**Comment by dbazhal** [comment]
Oh, thank you for your reply, will watch for that issue in operator repo.
