### ISSUE TITLE
Have a run history tracking

### ISSUE THREAD

**Issue by dbazhal** [tektoncd/pipeline#3994]
### Feature request

If I have pipeline, and I run it frequently, my cluster soon gets flooded with(often not much useful) old run objects.
What I need is to keep last X successfull runs, and Y failed, and other runs to be removed.
I'd like to have run history controlled by tekton operator.
As an example of such behaviour - in openshift buildconfigs you can set .spec.successfulBuildsHistoryLimit and .spec.failedBuildsHistoryLimit.

### Use case

I have a cluster with dozens of pipelines in different namespaces, they run multiple times a day each, and there would be trouble running new pipelines soon if we wouldn't write some simple garbage collector for that.
What would be great is to have such feature built in tekton operator.

**Comment by vdemeester** [comment]
This feature should most likely be targetting the `tektoncd/operator` as I think this is something that should be handled by the operator or by an external component than the core tektoncd/pipeline. We do have https://github.com/tektoncd/operator/issues/209 to track work on this too.

**Comment by dbazhal** [comment]
Thanks, will watch for that issue in operator repo :)
