### ISSUE TITLE
Implement initial update timeout for custom tasks.

### ISSUE THREAD

**Issue by ScrapCodes** [tektoncd/pipeline#3997]
### Feature request

Implement initial update timeout for custom tasks.

REF: [TEP-0002](https://github.com/tektoncd/community/blob/main/teps/0002-custom-tasks.md#initial-update-timeout)
Verbatim paste:
#### Initial Update Timeout

It's possible that, though the Custom Task author has defined their CRD type, there's no controller watching for Runs of that type and updating their statuses as expected (e.g., it's crash-looping, it has been uninstalled, or it was never provided).

In this case, a PipelineRun that depends on that type may wait uselessly for the execution to complete, until its configured timeout, which might be hours later. To save users' time and fail fast, the PipelineRun controller will enforce a short timeout for initial updates to Run objects. If a Run hasn't been updated to the condition `.status.conditions[@type=Succeeded]=Unknown` after a certain (configurable) amount of time, say 30 seconds, then the PipelineRun controller should fail the PipelineRun with a descriptive error message. This simple update indicates that the execution is running, and at least something is consuming new Run creations and updating statuses.

### Use case

Currently a pipeline run will wait uselessly if the Custom task controller is not responding or does not exist. This initial update is one plausible way of solving it.

**Comment by imjasonh** [comment]
cc @bobcatfish I don't remember where we landed on this, even though the text ended up making it into the merged TEP.

On the one hand this guards against badly behaving custom task controllers and fails PipelineRuns fast, on the other hand we could just expect/require operators to vet the custom task controllers they install and expect them not to behave badly in the first place.

For right now it's a nice separation of concerns to be able to unambiguously state that the PipelineRun control loop will never update a Run object, only create them -- we could even enforce this with RBAC 🤔

**Comment by ScrapCodes** [comment]
> For right now it's a nice separation of concerns to be able to unambiguously state that the PipelineRun control loop will never update a Run object, only create them -- we could even enforce this with RBAC 🤔

Can we implement this and still maintain the nice separation of concern as above. 

Also consider from the point of view, that at some point we would like to move towards a custom task controller SDK.

**Comment by imjasonh** [comment]
> Also consider from the point of view, that at some point we would like to move towards a custom task controller SDK.

Putting this into an SDK for custom task controllers to build around seems like a good compromise to me. Tekton components still won't ever update Runs themselves, but the SDK makes it easy to write a well-behaved custom task controller. 👍

**Comment by ScrapCodes** [comment]
So the current situation is like, even if the custom controller does `return nil` as the first statement in `ReconcileKind`. The conditions are set to `.status.conditions[@type=Succeeded]=Unknown`. 
Why is it like that, is still a mystery for me. 

To solve this, may I propose:

1.  Set `.status.conditions[@type=Succeeded]=False` and reason as `NotStarted` and human readable message as : `This Run instance has not been processed by its controller yet`. Before creating the Run instance and then create it.
2. Start a timer of say 30 seconds (may be using a go routine ) and Mark the PipelineRun as failed incase it's status does not get updated after the timer expired.
```go
go func () {
// wait for 30 seconds
// pr.MarkFailed
}
```

WDYT?

**Comment by imjasonh** [comment]
1. "has not been processed yet" makes it sound like we expect something to process it, which leads us to the original separation-of-concerns point: if the controller picks it up and updates it to `Succeeded=Unknown` 31s after being created, what should happen?
    - Should the update fail, blocked by a an admission controller webhook that prevents False->Unknown transitions?
    - Should the update succeed but have no effect on the PipelineRun? The PipelineRun might have already failed, or the Run retried.
    - Should the update succeed but somehow try to encourage the PipelineRun to keep going after all? It may have started its `finally` steps, etc.
    
1. A `go wait && fail` makes sense conceptually, but is brittle in cases where the controller crashes while waiting. Instead, we should `EnqueueAfter(30*time.Second)` (configurable) and check if it's older than 30s without an update. That `EnqueueAfter` ensures that if the controller dies during those 30s that its restarted replacement will pick it up.

**Comment by ScrapCodes** [comment]
For 2. since the default value for condition is set as `.status.conditions[@type=Succeeded]=Unknown`, it will be difficult to say, that a controller has updated the condition or not. Checking `startTime` may be brittle too, as some controller may not start immediately but want us to think that they have received the task and are working "on it".

**Comment by imjasonh** [comment]
Correct me if I'm wrong, I thought the PipelineRun controller initially set _no_ conditions, and it was the responsibility of the custom task controller to set it to `Unknown` to signal "I've seen this, and I've started working". If the PipelineRun controller already immediately sets `status=Unknown`, how should a controller signal that actual work has started?

**Comment by ScrapCodes** [comment]
Actually, this is what I found.

>So the current situation is like, even if the custom controller does return nil as the first statement in ReconcileKind. The conditions are set to .status.conditions[@type=Succeeded]=Unknown.
Why is it like that, is still a mystery for me.
