### ISSUE TITLE
more than one PersistentVolumeClaim is bound

### ISSUE THREAD

**Issue by illeatmyhat** [tektoncd/pipeline#4000]
# Expected Behavior
Create a PipelineRun with more than one PersistentVolumeClaim, runs fine
# Actual Behavior
PipelineRun fails with error `more than one PersistentVolumeClaim is bound`

[Disabling the Affinity Assistant](https://tekton.dev/docs/pipelines/install/#customizing-the-pipelines-controller-behavior) resolves the issue.

This is a completely undocumented limitation. Nowhere in the [Workspaces documentation](https://tekton.dev/docs/pipelines/workspaces/) does it say that you are not allowed to use more than one PVC in a single Task when the Affinity Assistant is enabled.

# Additional Info

- Kubernetes version:
  ```
  Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1-5-g76a04fc", GitCommit:"c66c03f", GitTreeState:"clean", BuildDate:"2021-02-03T17:45:18Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
  Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0+d856161", GitCommit:"d8561614ec39e7dc33ef531690b919178010226c", GitTreeState:"clean", BuildDate:"2021-04-23T13:59:46Z", GoVersion:"go1.15.7", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version: v0.24.1

**Comment by 13567436138** [comment]
I face the same problem，how to solve
