### ISSUE TITLE
add kubectl explain crd  ，how can I know all fields in crd

### ISSUE THREAD

**Issue by 13567436138** [tektoncd/pipeline#4001]
### Feature request

add kubectl explain crd

**Comment by nikhil-thomas** [comment]
some context:
- https://github.com/tektoncd/pipeline/pull/1179
- https://github.com/tektoncd/pipeline/pull/1776

At present, we can use our examples and docs as reference. 🙂 
- https://github.com/tektoncd/pipeline/tree/main/examples/v1beta1
- https://tekton.dev/docs/pipelines/tasks/

**Comment by 13567436138** [comment]
not good enough

**Comment by afrittoli** [comment]
@13567436138 Would you care to provide a bit more context? 
Why is the answer from @nikhil-thomas not sufficient? 
What are your use cases (they are missing in the feature request)?
Thank you

**Comment by 13567436138** [comment]
ok,I surrender.but I still hope somebody will provider explain command's content.

**Comment by vdemeester** [comment]
@13567436138 the problem we have right now is that, `kubectl explain` looks at the embedded openapi schema in the CRD. *But*, if we add those in our CRD, we are hitting the object limit of `etcd` (in most/default kubernetes setup).

**Comment by liangyuanpeng** [comment]
> @13567436138 the problem we have right now is that, `kubectl explain` looks at the embedded openapi schema in the CRD. _But_, if we add those in our CRD, we are hitting the object limit of `etcd` (in most/default kubernetes setup).

So we just no idea to let tekton working for `kubectl explain`,right?
