### ISSUE TITLE
Dynamically retrieving Result Parameters

### ISSUE THREAD

**Issue by tlawrie** [tektoncd/pipeline#4016]
### Feature request

At the moment, you have to define result parameters (with a reasonable amount of boiler plate), however we know that result parameters are in `/tekton/results/<param` and can assume that file in `/tekton/results` should be a result parameter.

We could then implement a simpler mechanism that instead of looping through [e.Results](https://github.com/tektoncd/pipeline/blob/9de68e31c25f5587588f74be88784073a861562f/pkg/entrypoint/entrypointer.go#L164) we could actually loop through the files present in that directory and turn into result parameters.

For example, in Node this would be something like the following, and we could even filter out specific files if necessary. Then still append that to the output.
```
const resultParamFiles = fs.readdirSync(lifecyclePath);
const resultParams = resultParamFiles
    .filter((file) => file !== "env" && file !== "lock")
    .reduce((accum, file) => {
      const contents = fs.readFileSync(`${lifecyclePath}/${file}`, "utf8");
      log.debug("  Param: " + file + " Value: " + contents);
      accum[file.replace(".", "_")] = contents;
      return accum;
    }, {});
```

### Use case

The idea being that we would dynamically allow any parameter (still meeting naming conventions) to result. This would allow less boiler plate yaml definition, and allow better usage of off the shelf tasks from a task hub, particular when added via a UI that may or not provide YAML input. It reduces the barrier.

It also would help when dynamically creating output from a shell script (or similar) and not having to know the result parameter names to start with.

**Comment by afrittoli** [comment]
Thanks for this @tlawrie.

I think that the main advantage of having results declared in the spec is that a user of the Task/Pipeline knows which results to expect, without having to dig into the code of the task.  

Params + results define the interface of a Task, which is very much needed.
We could allow for dynamic results too, as I can imaging they could be useful in certain cases, but it would be good to have an example of where having such dynamic params would be beneficial, apart from reducing the amount of YAML in the definition.

**Comment by tlawrie** [comment]
Hi @afrittoli the use case I have is mainly for a system that is integrating with Tekton.

Let's say I offer end-users the ability to run a shell script/container and all they have to do is provide the script/container (not any declarative YAML) or in fact, they could even write the script in a UI. 

Without our system knowing anything about what it's running, it runs a workflow task. If our end users only know they have to output a result to /tekton/results/<parameter> (ideally we could configure that location too) they can go ahead and do that without needing to tell us what they are putting there, or in fact our system offering any capability for defining them.

Essentially it's about abstracting Tekton to an engine and our application abstracts things away to which an end-user is just providing us an object to execute. If we can then dynamically retrieve whatever they have put in the default output location, then there is nothing further needed from the user.

**Comment by tlawrie** [comment]
Hey @afrittoli checking in on this one. Did my example make sense?

**Comment by tlawrie** [comment]
Hi @afrittoli checking in on this one? did the above example make sense? or should we leave this issue closed?

**Comment by uqix** [comment]
> ### Feature request
> At the moment, you have to define result parameters (with a reasonable amount of boiler plate), however we know that result parameters are in `/tekton/results/<param` and can assume that file in `/tekton/results` should be a result parameter.
> 
> We could then implement a simpler mechanism that instead of looping through [e.Results](https://github.com/tektoncd/pipeline/blob/9de68e31c25f5587588f74be88784073a861562f/pkg/entrypoint/entrypointer.go#L164) we could actually loop through the files present in that directory and turn into result parameters.
> 
> For example, in Node this would be something like the following, and we could even filter out specific files if necessary. Then still append that to the output.
> 
> ```
> const resultParamFiles = fs.readdirSync(lifecyclePath);
> const resultParams = resultParamFiles
>     .filter((file) => file !== "env" && file !== "lock")
>     .reduce((accum, file) => {
>       const contents = fs.readFileSync(`${lifecyclePath}/${file}`, "utf8");
>       log.debug("  Param: " + file + " Value: " + contents);
>       accum[file.replace(".", "_")] = contents;
>       return accum;
>     }, {});
> ```
> 
> ### Use case
> The idea being that we would dynamically allow any parameter (still meeting naming conventions) to result. This would allow less boiler plate yaml definition, and allow better usage of off the shelf tasks from a task hub, particular when added via a UI that may or not provide YAML input. It reduces the barrier.
> 
> It also would help when dynamically creating output from a shell script (or similar) and not having to know the result parameter names to start with.

Same situation here.

**Comment by uqix** [comment]
> Hi @afrittoli the use case I have is mainly for a system that is integrating with Tekton.
> 
> Let's say I offer end-users the ability to run a shell script/container and all they have to do is provide the script/container (not any declarative YAML) or in fact, they could even write the script in a UI.
> 
> Without our system knowing anything about what it's running, it runs a workflow task. If our end users only know they have to output a result to /tekton/results/ (ideally we could configure that location too) they can go ahead and do that without needing to tell us what they are putting there, or in fact our system offering any capability for defining them.
> 
> Essentially it's about abstracting Tekton to an engine and our application abstracts things away to which an end-user is just providing us an object to execute. If we can then dynamically retrieve whatever they have put in the default output location, then there is nothing further needed from the user.
> 
> And Tekton in itself would just be able to find all files in the location and turn into result parameters.

Same situation here.
