### ISSUE TITLE
0.24.2 is missing a change from 0.24.1

### ISSUE THREAD

**Issue by tlawrie** [tektoncd/pipeline#4017]
# Expected Behavior

0.24.2 to build on 0.24.1 and only revert what was needed

# Actual Behavior

Looking at https://github.com/tektoncd/pipeline/blob/v0.24.1/pkg/apis/pipeline/v1beta1/when_types.go shows a May 8 commit for **Remove deprecated PascalCase fields in WhenExpressions**. When looking at the 0.24.2 version its reverted back to December 2.

# Additional Info

I am not sure if this is an actual problem but it does some like an unnecessary revert, which subsequently broke the Tekton generation with the Fabric8 client.

**Comment by vdemeester** [comment]
@tlawrie thanks for the report ; indeed something is wrong here. Seems like 0.24.1 was released from `main` and not from the release branch, so some stuff were not cherry-picked.

Those 3 commits are in 0.24.1 and not in 0.24.2 because they were not cherry-picked

```
d3666c26 * Remove deprecated PascalCase fields in WhenExpressions
bf511ddb * Fix issue where AddSidecarVolumeMount unit tests did not actually run
b31327bd * Add links to v0.24.0 docs and examples
```

We probably need to do a 0.24.3 with those 3 cherry-picked and "note" somewhere that 0.24.2 shouldn't be used... 😓 

/cc @jerop @sbwsg

**Comment by afrittoli** [comment]
> @tlawrie thanks for the report ; indeed something is wrong here. Seems like 0.24.1 was released from `main` and not from the release branch, so some stuff were not cherry-picked.
> 
> Those 3 commits are in 0.24.1 and not in 0.24.2 because they were not cherry-picked
> 
> ```
> d3666c26 * Remove deprecated PascalCase fields in WhenExpressions
> bf511ddb * Fix issue where AddSidecarVolumeMount unit tests did not actually run
> b31327bd * Add links to v0.24.0 docs and examples
> ```
> 
> We probably need to do a 0.24.3 with those 3 cherry-picked and "note" somewhere that 0.24.2 shouldn't be used... 😓

Once v0.24.3 is released it will automatically override previous minor ones, but we can add a not to the release notes anyways

> 
> /cc @jerop @sbwsg

**Comment by afrittoli** [comment]
> @tlawrie thanks for the report ; indeed something is wrong here. Seems like 0.24.1 was released from `main` and not from the release branch, so some stuff were not cherry-picked.
> 
> Those 3 commits are in 0.24.1 and not in 0.24.2 because they were not cherry-picked
> 
> ```
> d3666c26 * Remove deprecated PascalCase fields in WhenExpressions
> bf511ddb * Fix issue where AddSidecarVolumeMount unit tests did not actually run
> b31327bd * Add links to v0.24.0 docs and examples
> ```

These three commits should not have been in v0.24.1 to begin with, I made some mistake when creating the release 😅 
So in that sense the revert from v0.24.2 to v0.24.1 is not unnecessary, and the content of v0.24.2 is what should be.

> 
> We probably need to do a 0.24.3 with those 3 cherry-picked and "note" somewhere that 0.24.2 shouldn't be used... 😓
> 
> /cc @jerop @sbwsg

**Comment by jerop** [comment]
fixed in https://github.com/tektoncd/pipeline/pull/4024

thanks @tlawrie for the quick report

**Comment by tlawrie** [comment]
Thanks everyone!
