### ISSUE TITLE
Tekton Prometheus Exporter isn't discoverable by Instana

### ISSUE THREAD

**Issue by tylerstanczak** [tektoncd/pipeline#4047]
# Expected Behavior
[Instana Prometheus Plugin](https://www.instana.com/docs/ecosystem/prometheus/) automatically discovers the [Tekton Prometheus Exporter](https://tekton.dev/docs/pipelines/metrics/) (tekton-pipelines-controller pod) metrics endpoint on port 9090
# Actual Behavior
Instana's Prometheus sensor fails to discover the Tekton Prometheus Exporter endpoint
# Steps to Reproduce the Problem

1. Set the Tekton Metrics backend to "prometheus" in the observability configmap
2. Configure Instana's Prometheus Sensor to monitor all '/metrics'
 endpoints (automatically discovers port and host)

# Additional Info
- Instana looks at the pod YAML to determine what ports to check for available metrics sources. Currently, the **tekton-pipelines-controller** pod YAML does not include port 9090 in the ports array after configuring the Prometheus Exporter.
- Customers of Red Hat OpenShift and Instana are directly impacted by this issue
- Kubernetes version: v1.20.0+df9c838

  **Output of `kubectl version`:**

     ```
    oc version
    Client Version: 4.5.0-202005291417-9933eb9
    Server Version: 4.7.12
    Kubernetes Version: v1.20.0+df9c838
    ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
kubectl get pods -n openshift-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'
v0.22.0
```

Additional Info:
Instana is able to pull in the prometheus metrics after adding 9090 to the tekton-pipelines-controller pod port array:
```yaml
ports:
  - name: metrics
    containerPort: 9090
    protocol: TCP
  - name: probes
    containerPort: 8080
    protocol: TCP
```

**Comment by afrittoli** [comment]
@tylerstanczak thanks for the bug report, I'm not sure why the port is not exposed on the pod directly (only on the service) - it definitely looks like something that we should fix.

**Comment by chenbh** [comment]
Specifying a port on the pod is [good practice and informationally only](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#:~:text=Exposing%20a%20port%20here%20gives%20the%20system%20additional%20information%20about%20the%20network%20connections%20a%20container%20uses%2C%20but%20is%20primarily%20informational.%20Not%20specifying%20a%20port%20here%20DOES%20NOT%20prevent%20that%20port%20from%20being%20exposed.), it looks like the same will also need to be done for the triggers controller (both pipeline and triggers webhooks already has it)

I'm willing to work on this.

**Comment by jerop** [comment]
@tylerstanczak @chenbh looks like this was fixed in https://github.com/tektoncd/pipeline/pull/4233

(feel free to reopen if not)
