### ISSUE TITLE
How to modify imagePullPolicy of image in "spec:containers:args"

### ISSUE THREAD

**Issue by 011d** [tektoncd/pipeline#4052]
Example：spec:containers:args:"-shell-image", "gcr.io/distroless/base:latest"
I want imagePullPolicy: IfNotPresent.  I don't want default--"imagePullPolicy: Always"
Because of the network,I have modify it this way.
I tried spec:containers:args:"-imagePullPolicy", "IfNotPresent", but no.
How to modify it. Thanks.

**Comment by jan0112d** [comment]
![image](https://user-images.githubusercontent.com/42208084/122694585-6eae0300-d270-11eb-9bf3-652ff63dffe6.png)

**Comment by sbwsg** [comment]
Interesting, in my local development cluster the `imagePullPolicy` for the `place-tools` and `place-scripts` init containers are both `IfNotPresent` by default.

@jan0112d can you confirm what kubernetes / platform you are running on?

**Comment by sbwsg** [comment]
As far as I'm aware there's no way currently to configure the image pull policy of the containers that the tekton controller injects.

**Comment by jan0112d** [comment]
> As far as I'm aware there's no way currently to configure the image pull policy of the containers that the tekton controller injects.

thinks, I put the image in the private image respository, get from private respository.
