### ISSUE TITLE
No more arm32v7 images available after v0.21.0

### ISSUE THREAD

**Issue by grunlab** [tektoncd/pipeline#4059]
Until release v0.21.0, arm32v7 images were available.
See manifests here: https://console.cloud.google.com/gcr/images/tekton-releases/GLOBAL/github.com/tektoncd/pipeline/cmd/controller@sha256:972ee9c3f43c88495b074bfc0a8350eb34131355ab9ddc5da63c59f64d74e83d/details?tab=info
Available platform architectures were: amd64, arm, arm64, ppc64le, s390x

Starting from v0.22.0, no more arm32v7 images were available.
See manifests here: https://console.cloud.google.com/gcr/images/tekton-releases/GLOBAL/github.com/tektoncd/pipeline/cmd/controller@sha256:8f89bbdcb6230c903d887a3fa0bb8e32134598fef6de775979dfa39e59c32e3b/details?tab=info
Available platform architectures: amd64, arm64, ppc64le, s390x

So arm32v7 users are currently blocked in v0.21.0, not possibility to upgrade to next releases.

**Comment by vdemeester** [comment]
Right, we remove it as part of https://github.com/tektoncd/pipeline/pull/3717 (or we didn't add it to the list we build). We didn't add in the list because of https://github.com/tektoncd/pipeline/pull/3664#issuecomment-756203274 (some issue with alpine on arm32). We should probably revisit that, if the alpine issue is fixed or if the base image we use now support arm32.

**Comment by vdemeester** [comment]
Also, the reason we did not list it is because `git-init` wasn't build properly for arm32 (see https://github.com/tektoncd/pipeline/issues/3647) and thus we were doing a broken release on this platform.

**Comment by grunlab** [comment]
Effectively, I've also faced the issue with the ```git-init``` image not available for arm32. A quick workaround was to build my own arm32 ```git-client``` image launched  by a custom ```git-clone``` task.
At that time, this issue was not really a showstopper using tekton on arm32 architecture.

Now, it is much more problematic, not been able to upgrade tekton make me think about migrating to another tool ... I hope it won't be the case, tekton is so nice !

It would be great if you could reconsider that issue and try to make arm32 images available again.
Thank you

**Comment by vdemeester** [comment]
@grunlab note that to generate a `arm32` version of Tekton, the current workaround is to *build* it using the `--platform` flag.

```bash
$ git clone https://github.com/tektoncd/pipeline.git
$ cd pipeline
$ ko apply --platform=linux/arm -f config/ # or resolve
```

To be able to actually *release* ourselves it for `arm32`, we need to be able to provide the `git-init` image for `arm32` too.
Also note that *officially*, tektoncd/pipeline is only supported on x86_64 😅. The rest of the build is provided as a *best effort* for now. But yes, we need to find some time to try to unblock this `git-init` image problem on `arm32`.

**Comment by grunlab** [comment]
tekton images for arm32v7 arch still not yet available when writing this comment.
I gave up and migrated all my pipelines to gitlab-runner.

**Comment by imjasonh** [comment]
> tekton images for arm32v7 arch still not yet available when writing this comment. I gave up and migrated all my pipelines to gitlab-runner.

I'm sorry to hear that.

FWIW, [the fix](https://github.com/tektoncd/pipeline/pull/4331) was submitted within a day of your last comment, and arm32v7 images should be available in nightly builds today. They'll be included in the next released version of Tekton, which I believe is scheduled within the next few days.

**Comment by jerop** [comment]
> tekton images for arm32v7 arch still not yet available when writing this comment

@grunlab it's now available in https://github.com/tektoncd/pipeline/releases/tag/v0.30.0

**Comment by imjasonh** [comment]
Hmm, I actually don't see it in the released image:

```
crane manifest gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint:v0.30.0@sha256:34ee7658bb8a657584e1ada8e84121758cc5d067c1f0740873d614d07423886f | jq '.manifests[].platform'
{
  "architecture": "amd64",
  "os": "linux"
}
{
  "architecture": "arm64",
  "os": "linux"
}
{
  "architecture": "ppc64le",
  "os": "linux"
}
{
  "architecture": "s390x",
  "os": "linux"
}
{
  "architecture": "amd64",
  "os": "windows",
  "os.version": "10.0.17763.2300"
}
```

Investigating...

**Comment by imjasonh** [comment]
It is present in the latest nightly release however:

```
$ crane manifest gcr.io/tekton-nightly/github.com/tektoncd/pipeline/cmd/entrypoint@sha256:6f5400400326d82032fa3343b1e782d6b7a8bf61be03d3f73a6274235e71dfc5 | jq '.manifests[].platform'
{
  "architecture": "amd64",
  "os": "linux"
}
{
  "architecture": "arm",
  "os": "linux"
}
{
  "architecture": "arm64",
  "os": "linux"
}
{
  "architecture": "ppc64le",
  "os": "linux"
}
{
  "architecture": "s390x",
  "os": "linux"
}
{
  "architecture": "amd64",
  "os": "windows",
  "os.version": "10.0.17763.2300"
}
```

**Comment by imjasonh** [comment]
Looking into this again, it looks like this discrepancy might be happening because the pipeline config in the `tekton/` directory hasn't been applied to the regular release namespace (`default`), only to the namespace where the nightly release runs (`tekton-nightly`)

Compare (ctrl+f for `platforms` and look at the defaults):
- [nightly release pipeline](https://dashboard.dogfooding.tekton.dev/#/namespaces/tekton-nightly/pipelines/pipeline-pipeline-release?view=yaml)
- [release pipeline](https://dashboard.dogfooding.tekton.dev/#/namespaces/default/pipelines/pipeline-release?view=yaml)

/reopen
/assign @afrittoli 

We should apply the repo's CI config to `default` before the next release to ensure this gets picked up and `linux/arm` images get built.

In the meantime, any of the nightly releases since ~late October should work fine on `linux/arm`.

**Comment by pritidesai** [comment]
@imjasonh please confirm this is fixed with v0.31 and close this issue. Thanks 🙏 

```
crane manifest gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint:v0.31.0@sha256:97139f59df7c6e2b3d22e75191be653f4202143859d3937e2bafa7a8a7a44822 | jq '.manifests[].platform'
{
  "architecture": "amd64",
  "os": "linux"
}
{
  "architecture": "arm",
  "os": "linux"
}
{
  "architecture": "arm64",
  "os": "linux"
}
{
  "architecture": "ppc64le",
  "os": "linux"
}
{
  "architecture": "s390x",
  "os": "linux"
}
```

**Comment by pritidesai** [comment]
Interestingly `windows` is missing from v0.31 🤔  is that expected?

**Comment by jerop** [comment]
fixed in https://github.com/tektoncd/pipeline/pull/4331

windows issue tracked in https://github.com/tektoncd/pipeline/issues/4457
