### ISSUE TITLE
`ko delete -f config/` cleans up everything regarding Tekton, including dashboard, trigger, and so on?

### ISSUE THREAD

**Issue by kobaji** [tektoncd/pipeline#4064]
Hi there, thank you very much for all your kindness.

Executing the following command can delete every component whose namespace is `tekton-pipelines`, right?

https://github.com/tektoncd/pipeline/blob/main/DEVELOPMENT.md#delete-pipeline

> #### Delete Pipeline
>
>You can clean up everything with:
>
```shell
ko delete -f config/
```

Basically other tekton components like dashboard or triggers are using namespace `tekton-pipelines` and [config/100-namespaces.yaml](https://github.com/tektoncd/pipeline/blob/main/config/100-namespace.yaml) defines the same namespace, thus I am thinking that executing the above command cleans up every component whose namespace is `tekton-pipelines`.

Therefore I think the title `Delete Pipeline` could be confusing for developers not getting used to developing or English, and could be in danger of deleting dashboard, triggers and so on.
Furthermore I think that we could improve the description.

**Comment by vdemeester** [comment]
@kobaji Indeed, it does because it deletes the `tekton-pipelines` namespace 😅 . We should document that this is the case at least for sure.
/kind documentation

**Comment by kobaji** [comment]
> @kobaji Indeed, it does because it deletes the `tekton-pipelines` namespace 😅 . We should document that this is the case at least for sure.
> /kind documentation

Thank you very much @vdemeester for your kindness!
Honestly I deleted all resources whose namespace is `tekton-pipelines` by mistake 😅

Could my team or I deal with this issue??

We will solve this issue by doing the following two things.

1. Change the structure of a folder [config](https://github.com/tektoncd/pipeline/tree/main/config) like below in order to avoid unintentional deletion of a namespace `tekton-pipelines`

[config](https://github.com/tektoncd/pipeline/tree/main/config)
├ namespace
│ └ [100-namespace.yaml](https://github.com/tektoncd/pipeline/blob/main/config/100-namespace.yaml)
├ [101-podsecuritypolicy.yaml](https://github.com/tektoncd/pipeline/blob/main/config/101-podsecuritypolicy.yaml)
├ [200-clusterrole.yaml](https://github.com/tektoncd/pipeline/blob/main/config/200-clusterrole.yaml)
└ :

2. Add a documentation in [DEVELOPMENT.md#delete-pipeline](https://github.com/tektoncd/pipeline/blob/main/DEVELOPMENT.md#delete-pipeline)
I will add the description like below. (Some of English should be improved 😅)

``````
#### Delete Pipeline

You can clean up everything with:

```shell
# If you should not delete the namespace of a pipeline component
ko delete -f config/

# If you also can delete the namespace of a pipeline component
ko delete -R -f config/
```

**Note:** if you use a pipeline component in the same namespace as other components such as dashboard or triggers, executing `ko delete -R -f config/` deletes these other components too.
``````

**Comment by vdemeester** [comment]
@kobaji that could indeed work, I think it makes a lot of sense even 👼🏼 (here and in other Tekton components)

**Comment by kobaji** [comment]
Thank you @vdemeester our team will be dealing with this issue unless someone else committed.

> here and in other Tekton components

Yeah I agree, if I could find other Tekton components have the same command with deleting a namespace `tekton-pipelines`

/assign @kobaji

**Comment by kobaji** [comment]
/assign @kobaji 

I re-assign myself but Fujiishi-san, my fellow, is contributing with this issue.

**Comment by jerop** [comment]
@hidehitof and @kobaji are actively working on this in https://github.com/tektoncd/pipeline/pull/4093 -- thank you 😀 

/assign @hidehitof
/assign @kobaji

/remove-lifecycle rotten
