### ISSUE TITLE
[Question] Interactive Step During Pipeline Execution

### ISSUE THREAD

**Issue by raffamendes** [tektoncd/pipeline#4074]
Hi Guys,

Just a quick question, I have a scenario where we're migrating from Jenkins to Tekton(Openshift Pipelines actually) but the Jenkins pipelines for the main branch(production) have a interactive step, for the user to authorize the build to for for production.

Do we have any example on this? 

Thanks in advance

Regards

**Comment by bobcatfish** [comment]
Hey @raffamendes ! 2 options for how you can handle this:

1. The easiest option is to make a Task that waits - e.g. a script or tool in a container that waits for some state to become true (e.g. via a configmap, or via an HTTP endpoint, whatever works best for you) - the downside is that this would be a running pod, consuming resources
2. The better option is to use a custom task - however i dont think we have one that does exactly what you need ( + @imjasonh ) [our experimental wait task](https://github.com/tektoncd/experimental/tree/main/wait-task) _almost_ does what you need but it looks like it waits for some duration of time to pass; what you need is to wait for some state to become true 🤔   (i definitely think we should be providing better support for this, maybe something to add to the roadmap 🤔  - making this as a custom task could be relatively easy if you use the existing wait-task as a starting point - or wait-task could be extended to wait until some value is provided in the spec or status...)

**Comment by raffamendes** [comment]
Hi @bobcatfish Yeah, I will take a look at the wait-task and try to make a example work.

If this works, I will post here the results.

Meanwhile at the case that I'm actually working right now, I'm delegating the responsibility to gitlab, They're taking the merge-request acceptation as a deploy to production authorization.

Will try to make this work and will get back here to tell the results.

Thanks for the Answer!!!!!

**Comment by bobcatfish** [comment]
sound great @raffamendes :D looking forward to seeing the results!!

**Comment by jerop** [comment]
fyi adding an approval custom task was also discussed in https://github.com/tektoncd/experimental/issues/728
