### ISSUE TITLE
Pipeline controller shouldn't retry creating pod when the error cannot be mitigated by retry

### ISSUE THREAD

**Issue by jialindai** [tektoncd/pipeline#4092]
# Expected Behavior

When executing one pipelinerun, sometimes the pod creation will fail due to error which cannot be mitigated by retrying. In this case, pipeline controller should simply fail the pipelinerun without retrying creating pod.

In my case, such error is pod creation failure due to not enough quota in namespace.

# Actual Behavior

Pipeline controller keep trying to create pod even there is no enough quota in namespace.

# Steps to Reproduce the Problem

1. Create one namespace with limited resource quota
2. Create one pipeline which will consume more resource than allowed in the namespace
3. Pipeline controller will retry to create the pod

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
1.18
  ```

- Tekton Pipeline version:
v0.22.0

**Comment by bobcatfish** [comment]
hey @jialindai !

> Pipeline controller keep trying to create pod even there is no enough quota in namespace.

I'm wondering, how would the pipeline controller know if that situation couldn't be mitigated? i.e. what if more quota became available in the namespace later? It sounds like that won't happen in your case, but I think it could for someone else (if I'm wrong maybe you can provide some more details about your setup - e.g. is there some way to conclusively know that quota won't be available?)

You might also fine https://github.com/tektoncd/pipeline/issues/734 interesting, which is all about scheduling in resource constrained environments - in that case we intentionally retry and backoff, waiting until resources are available.

For your specific case, it might make sense for you to create a controller (or maybe even cron?) which observes PipelineRuns in the state you are describing and cancels them.
