### ISSUE TITLE
Docker config.json "credsStore" value ignored.

### ISSUE THREAD

**Issue by walkline** [tektoncd/pipeline#4107]
# Expected Behavior

When I'm passing docker config.json file through `kubernetes.io/dockerconfigjson` secret, I expect to see content from that file including `credsStore` values.

# Actual Behavior

At first I tried to pass docker config.json file with the next content:
```
{
  "credsStore": "ecr-login"
}
```
But I didn't find `~/.docker/config.json` file inside of the the pod. 

Then I looked inside of the code and [found out](https://github.com/tektoncd/pipeline/blob/main/pkg/credentials/dockercreds/creds.go#L206) that Tekton works only with `auth` field.

# Steps to Reproduce the Problem

1. Create secret using [this](https://github.com/tektoncd/pipeline/blob/main/docs/auth.md#configuring-docker-authentication-for-docker) guidance but use config.json file with the next content:
```
{
  "credsStore": "ecr-login"
}
```
2. Run pipeline.
3. There is no `~/.docker/config.json` file inside of the running pod.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
  Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version:

  ```
  Client version: 0.19.0
  Pipeline version: v0.25.0
  Triggers version: v0.14.2
  Dashboard version: v0.18.0
  ```

**Comment by chmouel** [comment]
Hello @walkline, having the credsStore kept is the first part of the problem, right? having a way to pass a credentials helper binary/script is the other part of the issue?

**Comment by sbwsg** [comment]
Hey @walkline while Tekton Pipelines does have limited support for docker auth with the secrets+annotations approach we typically advise users to migrate to using Workspaces to accept credentials in Secrets instead - it's a more flexible approach that allows you to put any content you want in the Workspace and lets the Task author decide how to use it. The `git-clone` Task in the catalog is an example that uses this approach: https://github.com/tektoncd/catalog/blob/main/task/git-clone/0.5/git-clone.yaml#L27-L33

If the Task you're using is one that you own then I definitely suggest going this way in place of the secrets+annotations.
