### ISSUE TITLE
Tekton pipeline and PersistentVolumes with accessMode ReadWriteMany

### ISSUE THREAD

**Issue by peteyako** [tektoncd/pipeline#4137]
# Description 
You wonder if this bug report belongs here, but I think it does, so bear with me. 

When we first set up the Tekton pipelines on OpenShift, we were using EBS storage for our Persistent Volumes. Cleaned up the pipeline code and made sure each pipeline run would use a folder based on the api/app name so that two separate pipeline runs wouldn’t overwrite each other when they run at the same time. This obviously didn’t work since EBS doesn’t support ReadWriteMany. After some digging around, we installed a the EFS community operator for RWX support (ReadWriteMany). And here is where our issues began.

It seems that when Tekton creates the `/workspace/app-workspace` directory (or whatever you choose to call your workspace dir) with EBS as a PV, it sets the permissions to:

```
>ls /workspace
drwxrwsr-x 7 root 1000760000 4096 Aug 1 23:30 app-workspace
```

When we switch it out to EFS, the same directory that gets created gets the following permissions/owner:

```
>ls /workspace
 drwxr-xr-x 7 root root 6144 Aug 1 18:32 app-workspace`
```

No changes to the pipeline code, only the storage backend is different between the two runs (EBS vs EFS). 

I've tried running as root, chown/chmod the folder (just to see if we could get past this step), custom jobs to chmod/chown, but no matter what we do, it seems like no files can get created in that app-workspace directory that gets created by Tekton. Even as root, we get permission denied on anything we try to do to the directory.

One final note that leads me to believe that this issue belongs here and not in the EFS operator Github page. 

When writing to any other part of the EFS storage, such as:

`/workspace/somefolder`

there are no permission issues whatsoever and it allows us to create folders and files. Only `/workspace/app-workspace` is affected.

I guess what I'm wondering is: what is going on under the hood in Tekton when the workspace folder gets created that it acts differently when underlaying storage types vary and create workspaces with different permissions. 

# Steps to Reproduce the Problem

### EBS
1. Create a PersistentVolumeClaim
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tekton-cicd-pvc-1
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
``` 
2. Use this PVC in your Tekton pipeline, it will create a PV by having one provisioned by AWS EBS

### EFS
1. Use the following steps to create an [EFS](https://github.com/openshift/aws-efs-operator) volume in AWS 
2. Use it in your Tekton pipeline
3. Anything created within the /worspace/app-workspace folder will give Permission Denied errors.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

 ```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:08:32Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0+df9c838", GitCommit:"df9c8387b2dc2308da01706ff89982c6b7ad9c48", GitTreeState:"clean", BuildDate:"2021-05-15T22:35:16Z", GoVersion:"go1.15.7", Compiler:"gc", Platform:"linux/amd64"}
 ```

- Tekton Pipeline version:

  **Output of `tkn version`**

```
Client version: 0.11.0
Pipeline version: v0.16.3
Triggers version: v0.8.1
```

**Comment by bobcatfish** [comment]
Hey @peteyako ! Apologies for the delayed response, quick question, could you verify that you see the permissions you expect if you mount the same volume into a pod (i.e. remove Tekton from the equation completely)?

Seeing if the permissions are any different with a plain old pod might give us a signal about whether or not this is something Tekton is doing or something outside of our control.

( also + @vdemeester since this might be relevant specifically to OpenShift interests)

**Comment by vdemeester** [comment]
👋🏼 @peteyako, 

Is tekton deployed using OpenShift Pipelines ? What version of OpenShift is it running on ?
OpenShift may do some work before attaching PVC to pods, and I am not clear if that's something that happens here or not.

**Comment by bobcatfish** [comment]
@peteyako I'm going to close this one for now but please re-open if you'd like to continue discussing 🙏
