### ISSUE TITLE
Inconsistent results hitting metrics endpoint for tekton_pipelines_controller_pipelinerun_duration_seconds_ metric

### ISSUE THREAD

**Issue by hokadiri** [tektoncd/pipeline#4141]
# Expected Behavior
Hitting the `/metrics` endpoint to get `tekton_pipelines_controller_pipelinerun_duration_seconds_` should be consistent and have data 
# Actual Behavior
Hitting the `/metrics` endpoint to get `tekton_pipelines_controller_pipelinerun_duration_seconds_` is inconsistent 

# Steps to Reproduce the Problem
Hit the `/metrics` gets inconsistent results. Sometimes it has data, other times it does not. 
```
bash-4.2$ curl -s -i   http://tekton-pipelines-controller.tekton-pipelines.svc.cluster.local:9090/metrics | grep tekton_pipelines_controller_pipelinerun_duration_seconds_ | wc -l
0
bash-4.2$ curl -s -i   http://tekton-pipelines-controller.tekton-pipelines.svc.cluster.local:9090/metrics | grep tekton_pipelines_controller_pipelinerun_duration_seconds_ | wc -l
0
bash-4.2$ curl -s -i   http://tekton-pipelines-controller.tekton-pipelines.svc.cluster.local:9090/metrics | grep tekton_pipelines_controller_pipelinerun_duration_seconds_ | wc -l
5970
bash-4.2$ curl -s -i   http://tekton-pipelines-controller.tekton-pipelines.svc.cluster.local:9090/metrics | grep tekton_pipelines_controller_pipelinerun_duration_seconds_ | wc -l
0
bash-4.2$ 
bash-4.2$ curl -s -i   http://tekton-pipelines-controller.tekton-pipelines.svc.cluster.local:9090/metrics | grep tekton_pipelines_controller_pipelinerun_duration_seconds_ | wc -l
5970
bash-4.2$ curl -s -i   http://tekton-pipelines-controller.tekton-pipelines.svc.cluster.local:9090/metrics | grep tekton_pipelines_controller_pipelinerun_duration_seconds_ | wc -l
5970
bash-4.2$ curl -s -i   http://tekton-pipelines-controller.tekton-pipelines.svc.cluster.local:9090/metrics | grep tekton_pipelines_controller_pipelinerun_duration_seconds_ | wc -l
0
```
1.
2.
3.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-dirty", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"dirty", BuildDate:"2021-03-15T10:03:32Z", GoVersion:"go1.16.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.8-gke.900", GitCommit:"28ab8501be88ea42e897ca8514d7cd0b436253d9", GitTreeState:"clean", BuildDate:"2021-06-30T09:23:36Z", GoVersion:"go1.15.13b5", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
Client version: 0.17.1
Pipeline version: v0.24.1
Triggers version: v0.14.0
Dashboard version: v0.17.0
```

**Comment by lbernick** [comment]
/priority important-soon
/remove-lifecycle rotten There's a [TEP](https://github.com/tektoncd/community/blob/main/teps/0073-simplify-metrics.md) for improving our metrics, this should be addressed there

**Comment by wlynch** [comment]
/assign @khrm 

Should be fixed with https://github.com/tektoncd/pipeline/pull/4468

**Comment by lbernick** [comment]
@khrm I saw that #4468 fixes the metric tekton_pipelines_controller_pipelinerun_count; does it also fix tekton_pipelines_controller_pipelinerun_duration_seconds, or does that need to be fixed in a separate PR?

**Comment by khrm** [comment]
Yes, it also fixes `tekton_pipelines_controller_pipelinerun_duration_seconds`.

**Comment by lbernick** [comment]
Great thanks Khurram!
