### ISSUE TITLE
Allow variables in generateName field

### ISSUE THREAD

**Issue by hokadiri** [tektoncd/pipeline#4143]
### Feature request

Allow variable names in `generateName` field of pipelinerun. Allows one to set useful variables so its more apparent at a tkn or dashboard level 

### Use case
Our pipelines are triggered from git events based off `git sha`. I want to know set git sha in the pipelinerun name 

```
apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: pr-$(params.git-sha)-run-
    spec:
      pipelineRef:
        name: some-pipeline
```

it would be nice to be able to see what pipelineruns map to what git sha at the dashboard view of pipelineruns.
 
![Screen Shot 2021-08-07 at 1 33 24 PM](https://user-images.githubusercontent.com/678342/128613231-ed8071fc-00f1-48c9-9c72-28a89b2b6df1.png)

Or from tkn 
```
$ tkn pipelinerun list -n android
NAME                        STARTED        DURATION     STATUS
commit-verify-p-run-zb422   16 hours ago   16 minutes   Failed
commit-verify-p-run-4c5tl   17 hours ago   17 minutes   Failed
commit-verify-p-run-cqq5l   18 hours ago   16 minutes   Failed
commit-verify-p-run-gztrb   19 hours ago   18 minutes   Succeeded(Completed)
commit-verify-p-run-t67q6   19 hours ago   16 minutes   Failed
commit-verify-p-run-mq2d7   20 hours ago   13 minutes   Succeeded(Completed)
commit-verify-p-run-jdx69   20 hours ago   14 minutes   Succeeded(Completed)
commit-verify-p-run-bn55l   20 hours ago   13 minutes   Succeeded(Completed)
commit-verify-p-run-w6qbh   20 hours ago   25 minutes   Failed
commit-verify-p-run-cw4fs   20 hours ago   18 minutes   Succeeded(Completed)
commit-verify-p-run-m8phj   20 hours ago   5 minutes    Succeeded(Completed)
commit-verify-p-run-t22sv   21 hours ago   5 minutes    Succeeded(Completed)
commit-verify-p-run-rbrlx   21 hours ago   24 minutes   Failed
commit-verify-p-run-pdh2l   21 hours ago   27 minutes   Failed
commit-verify-p-run-4gd7d   21 hours ago   19 minutes   Succeeded(Completed)
commit-verify-p-run-twwmw   21 hours ago   5 minutes    Succeeded(Completed)
commit-verify-p-run-5wqm2   21 hours ago   8 minutes    Succeeded(Completed)
commit-verify-p-run-fcjx2   21 hours ago   18 minutes   Succeeded(Completed)
commit-verify-p-run-zdg9c   22 hours ago   8 minutes    Failed
commit-verify-p-run-nbvkb   22 hours ago   16 minutes   Failed
```

**Comment by hokadiri** [comment]
/remove-lifecycle stale
Still needed please !

**Comment by vdemeester** [comment]
Hey @hokadiri, 
I think this is possible if you use `tektoncd/triggers` and/or an external tool that would "generate" the `generateName` 😅 (cc @dibyom @savitaashture). 

It is technically very difficult to *impossible* to have variable interpolation in the `metadata` part of our object as this is not something we control (it's the common part of all kubernetes objects). Variable interpolation is done at "runtime", aka once the object are already created (and stored) in kubernetes, and thus, we cannot mutate the name once it's already created.

**Comment by dibyom** [comment]
You can do this in Triggers for sure in a triggerTemplate:

```
metadata:
  generateName: pr-$(tt.params.git-sha)-
```

**Comment by lbernick** [comment]
/close

based on explanations from @vdemeester and @dibyom

**Comment by arturia-ci-service** [comment]
> You can do this in Triggers for sure in a triggerTemplate:
> 
> ```
> metadata:
>   generateName: pr-$(tt.params.git-sha)-
> ```

Have you tried this? For me it is not working...

Thanks

**Comment by elysian-gc** [comment]
> > You can do this in Triggers for sure in a triggerTemplate:
> > ```
> > metadata:
> >   generateName: pr-$(tt.params.git-sha)-
> > ```
> 
> Have you tried this? For me it is not working...
> 
> Thanks


I tryed,it`s working good
