### ISSUE TITLE
Update `publish-release` task to support release signing

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/pipeline#4153]
### Feature request

Sign the images that we publish during a release.

### More Info

Over in the Plumbing repo we now have [a documented guide to signing Tekton releases](https://github.com/tektoncd/plumbing/blob/main/docs/signing.md) in the dogfooding cluster.

In order to support signing we need to update our image publishing machinery to emit a result with name `IMAGES` and a given format. I believe this is the task we'll need to update: https://github.com/tektoncd/pipeline/blob/main/tekton/publish.yaml

**Comment by priyawadhwa** [comment]
Awesome! Yup, `IMAGES` will work -- basically it expects a comma-separated list of images built in that TaskRun, qualified by digest.

The [chains publish.yaml](https://github.com/tektoncd/chains/blob/main/release/publish.yaml#L51) might be a helpful example.
