### ISSUE TITLE
Is it possible to install Tekton in a different namespace

### ISSUE THREAD

**Issue by huang195** [tektoncd/pipeline#4172]
I searched the opened/closed issues, so hopefully I'm not creating a duplicate issue. In my case, I want to install Tekton in a different namespace than `tekton-pipeline`. However, the install yaml file seems to hard code this namespace, as in 

```shell
kubectl apply -f https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.16.3/release.yaml
```

There doesn't seem to be an option that allows me to install this in a different namespace. Any workarounds?

**Comment by sbwsg** [comment]
Pipelines should work in another namespace but you'll need to manually edit the release.yaml so that the namespace + all references to it are updated.

/kind question
