### ISSUE TITLE
Allowing to run tekton on a kubernetes cluster installed on a raspberry pi

### ISSUE THREAD

**Issue by julweber** [tektoncd/pipeline#4202]
### Feature request

It would be great to be able to run tekton on top of a kubernetes installation on a raspberry pi (e.g. with k3s installed)

### Use case

Being able to run kubernetes on a raspberry pi can be pretty useful to host tiny test environments.
It would be even better if we could automate workloads with tekton on top of that.

### Current state
Right now, when i try to install tekton on top of my k3s installation i get the following errors:
```
$> k get pods -n tekton-pipelines
NAME                                           READY   STATUS             RESTARTS   AGE
tekton-pipelines-controller-756477cd4b-6rfkn   0/1     ImagePullBackOff   0          7m38s
tekton-pipelines-webhook-75545447dd-c2rw7      0/1     ImagePullBackOff   0          7m37s

$>k describe pods -n tekton-pipelines

Name:         tekton-pipelines-controller-756477cd4b-6rfkn
....
  Warning  Failed     6m43s (x4 over 8m6s)  kubelet            Failed to pull image "gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.27.3@sha256:364e0fde644f39a8e2c622d545bc792831270e2fb2076a97363b5cc38446138c": rpc error: code = NotFound desc = failed to pull and unpack image "gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller@sha256:364e0fde644f39a8e2c622d545bc792831270e2fb2076a97363b5cc38446138c": no match for platform in manifest: not found
```

same goes for tekton-pipelines-webhook

It seems there are no compiled docker images for the arm platform available right now.
Would it be a big task to create arm compatible images for the tekton-pipelines-controller and tekton-pipelines-webhook images?

Kind regard,
Julian

**Comment by julweber** [comment]
On a further search i found this related topic: https://github.com/tektoncd/pipeline/issues/856

**Comment by vdemeester** [comment]
@julweber is this arm or arm64/aarch64 ? We do ship arm64 images but we don't do on arm yet, mainly due to a problem with `alpine` on this platform (that might have been fixed now, we should try it back)

**Comment by julweber** [comment]
@vdemeester thanks for the super fast reply. I am currently using the arm version of raspbian. So i will check with arm64 version sometime this week when i find a free time window and report back. In addition it would anyways be nice to also support arm, as then a raspberry pi 2 will also be supported i guess.

**Comment by julweber** [comment]
@vdemeester I found some time this morning and reinstalled the pi with the 64bit raspbian version and the k3s installation and the tekton-pipelines-controller and tekton-pipelines-webhook run fine on this 👯 

So i expect we can mark this feature request as closed. @vdemeester Maybe we could add that a 64bit arm kernel is required for tekton on raspberry pis somewhere in the documentation?

Kind regards,
Julian

**Comment by julweber** [comment]
For people stumbling over this:

Tekton requires a 64bit OS for running on a raspberry pi (Sept 2021)

Here you can find the 64bit raspbian images for example: https://downloads.raspberrypi.org/raspios_lite_arm64/images/
