### ISSUE TITLE
curl is a insecure pattern for downloading dependencies 

### ISSUE THREAD

**Issue by naveensrinivasan** [tektoncd/pipeline#4214]
curl is an insecure pattern for downloading dependencies 

https://github.com/tektoncd/pipeline/blob/f041ef5d644c72e88689e079a8e3ea96718891fc/Makefile#L167

https://about.codecov.io/security-update/

One of the recommended approaches to solving this issue is using something like `tools.go` https://github.com/ossf/scorecard/blob/main/tools.go where the external tools are tracked and are part of the go.mod which provides specific SHA. Also having a make target like this to install these tools https://github.com/ossf/scorecard/blob/f55b86d6627cc3717e3a0395e03305e81b9a09be/Makefile#L36

**Comment by naveensrinivasan** [comment]
Similar to this https://github.com/sigstore/rekor/tree/main/hack/tools

**Comment by vdemeester** [comment]
That make sense, thanks @naveensrinivasan. Looking at the link, I think using a separate `go.mod` and using `GOBIN` in the `Makefile`, we could make this work.

**Comment by naveensrinivasan** [comment]
I can work on this.

**Comment by nikhil-thomas** [comment]
/remove-lifecycle stale

this improvement  still relevant.

**Comment by nikhil-thomas** [comment]
@naveensrinivasan Hi, are you working on this at present 🧑‍💻 🧰 
if yes, 💯 👍 
if no, could you add a `help-wanted` label to this issue (also `good-first-issue`)

**Comment by naveensrinivasan** [comment]
I apologize I am not working on this.

**Comment by nikhil-thomas** [comment]
no problem 🧑‍💻 
do you mind if we open this for others who might be interested in working on this.

**Comment by naveensrinivasan** [comment]
> no problem 🧑‍💻 
> 
> do you mind if we open this for others who might be interested in working on this. 

Please do.

**Comment by nikhil-thomas** [comment]
Thank you @naveensrinivasan 

@vdemeester @bobcatfish 👆

**Comment by smaftoul** [comment]
I think this one can be close #4411 fixes it !
