### ISSUE TITLE
fix a few links in the development file under adding New CRD types

### ISSUE THREAD

**Issue by pritidesai** [tektoncd/pipeline#4219]
The [Adding New Types](https://github.com/tektoncd/pipeline/blob/main/DEVELOPMENT.md#adding-new-types) section under the DEVELOPMENT.md has a reference to `alpha` APIs instead of `beta`. We are now adding a new CRD to `beta` APIs. No changes being done in `alpha` APIs.

Please change this note:

```
Add go structs for the types in pkg/apis/pipeline/v1alpha1 e.g condition_types.go This should implement the Defaultable and Validatable interfaces as they are needed for the webhook in the next step.
```

to:

```
Add go structs for the types in pkg/apis/pipeline/v1beta1 e.g task_types.go This should implement the Defaultable and Validatable interfaces as they are needed for the webhook in the next step.
``` 

Change the links to v1beta1 APIs, such as:

```
Add go structs for the types in
    [pkg/apis/pipeline/v1beta1](./pkg/apis/pipeline/v1beta1) e.g
    [task_types.go](./pkg/apis/pipeline/v1beta1/task_types.go) This
    should implement the
    [Defaultable](./pkg/apis/pipeline/v1beta1/task_defaults.go) and
    [Validatable](./pkg/apis/pipeline/v1beta1/task_validation.go)
    interfaces as they are needed for the webhook in the next step.
```

And add the new types to `v1beta1`:

```
Add the new type to the
    [list of known types](./pkg/apis/pipeline/v1beta1/register.go)
```

**Comment by nbaudis** [comment]
I would be happy to work on the change, looking into this..

**Comment by afrittoli** [comment]
When we add new fields to a beta API we add them in the beta folders, not in the alpha - even though we still need to make sure that the beta API can roundtrip to alpha and back to beta. The new fields will be considered of "alpha" level stability, even if defined in the beta API.

When adding brand new CRDs however, they would be alpha, not beta. We never enforced having the same level of API stability across CRDs (see `PipelineResources` and `Conditions`) and I don't think we should.

@pritidesai @vdemeester wdyt?

**Comment by pritidesai** [comment]
yup, CRDs are added as `alpha`.  My bad,  was reading this section in context of `new fields` in `beta` API 😜
