### ISSUE TITLE
Broken documentation link for LimitRange

### ISSUE THREAD

**Issue by R2wenD2** [tektoncd/pipeline#4248]
# Expected Behavior
I click 'LimitRange code example' on https://tekton.dev/docs/pipelines/taskruns/#specifying-limitrange-values and I get to a useful page that provides a code example.

# Actual Behavior
404
# Steps to Reproduce the Problem

1. Navigate to https://tekton.dev/docs/pipelines/taskruns/#specifying-limitrange-values
2. click 'LimitRange code example'

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

**Comment by R2wenD2** [comment]
the PipelineRuns LimitRange code example on https://tekton.dev/docs/pipelines/pipelineruns/#specifying-limitrange-values has the same issue.

**Comment by sbwsg** [comment]
@R2wenD2 @vdemeester It looks like this might be fixed? At least the text of the section no longer matches the initial report and we can't seem to find the broken link any more.

**Comment by dibyom** [comment]
/close

Looks like the docs have been fixed
