### ISSUE TITLE
task source-lister create has not started yet or pod for task not yet available

### ISSUE THREAD

**Issue by JCzz** [tektoncd/pipeline#4259]
This [tutorial](https://redhat-scholars.github.io/tekton-tutorial/tekton-tutorial/tasks.html#_run_clustertask_echoer)

`kubectl apply -n tektontutorial -f source-lister.yaml`

Gives the following error: `task source-lister create has not started yet or pod for task not yet available`
```
 tkn task start source-lister \ 
  --showlog \
  --inputresource='source=git-source'
? Value for param `contextDir` of type `string`? (Default is `quarkus`) quarkus
TaskRun started: source-lister-run-mqpvj
Waiting for logs to be available...
task source-lister create has not started yet or pod for task not yet available
```

**Comment by JCzz** [comment]
Not an issue, found it to be a missing step on my part

**Comment by Alejandro9917** [comment]
What was the missing step?
