### ISSUE TITLE
Document developing the pipeline locally

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/pipeline#426]
## Expected Behavior
It should be real simple to hack around with build-pipeline on one's laptop

## Actual Behavior
A few gotchas as the steps assume we want to use gcr.io

## Steps to Reproduce the Problem

1. Follow build-pipeline's developing docs
2. Realise the need to fiddle with a few properties
3. Perhaps trip up with using `ko` so really stress the need for a proper Gopath

## Additional Info
https://github.com/knative/build-pipeline/pull/425 please 👼

**Comment by bobcatfish** [comment]
Looks like we'll get some of this with https://github.com/knative/build-pipeline/pull/430 but this issue I think is more focused on the developer experience, while #430 is about following along with the tutorial specifically (correct me if I'm wrong @a-roberts !)

**Comment by a-roberts** [comment]
Yep @bobcatfish, exactly 😄

**Comment by dibyom** [comment]
Done in https://github.com/tektoncd/pipeline/pull/495 I think
/close
