### ISSUE TITLE
When PVC used in pipeline run is deleted before any tasks start, task run will be just stuck

### ISSUE THREAD

**Issue by rcerven** [tektoncd/pipeline#4303]
When pipeline run uses pvc, either with volumeClaimTemplate or pre-created persistentVolumeClaim,
and you run the pipeline run and right after PVC is created (bound) you delete it (before any tasks start), it will be in 'terminating' state, and the task run will be just stuck.

**Comment by sbwsg** [comment]
@rcerven could you give a bit more context on the situation that results in a PVC being deleted just as a Task is starting?

**Comment by rcerven** [comment]
@sbwsg it was just for my testing, but it can happen if you will have PVC pruner

**Comment by jerop** [comment]
> the task run will be just stuck

@rcerven does this mean that the taskrun will not timeout, or is it stuck until timeout?

**Comment by rcerven** [comment]
> > the task run will be just stuck
> 
> @rcerven does this mean that the taskrun will not timeout, or is it stuck until timeout?

how long is the timeout? I was waiting just for few minutes

**Comment by wlynch** [comment]
> how long is the timeout? I was waiting just for few minutes

By default PipelineRuns timeout after 60 min - https://github.com/tektoncd/pipeline/blob/main/docs/pipelineruns.md#configuring-a-failure-timeout. The default value can be modified in [`config-defaults`](https://github.com/tektoncd/pipeline/blob/46d332c2aedef45a0c4b4d3d30f2f44cbb071709/config/config-defaults.yaml#L42).
