### ISSUE TITLE
import github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1 error

### ISSUE THREAD

**Issue by towithyou** [tektoncd/pipeline#4320]
# error
# github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1
../../../../../../go/pkg/mod/github.com/tektoncd/pipeline@v0.28.2/pkg/apis/pipeline/v1beta1/openapi_generated.go:117:3: cannot use "github.com/go-openapi/spec".Schema{...} (type "github.com/go-openapi/spec".Schema) as type "k8s.io/kube-openapi/pkg/validation/spec".Schema in field value
../../../../../../go/pkg/mod/github.com/tektoncd/pipeline@v0.28.2/pkg/apis/pipeline/v1beta1/openapi_generated.go:146:11: cannot use ref("k8s.io/api/core/v1.Toleration") (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
../../../../../../go/pkg/mod/github.com/tektoncd/pipeline@v0.28.2/pkg/apis/pipeline/v1beta1/openapi_generated.go:155:8: cannot use ref("k8s.io/api/core/v1.Affinity") (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
../../../../../../go/pkg/mod/github.com/tektoncd/pipeline@v0.28.2/pkg/apis/pipeline/v1beta1/openapi_generated.go:161:8: cannot use ref("k8s.io/api/core/v1.PodSecurityContext") (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
../../../../../../go/pkg/mod/github.com/tektoncd/pipeline@v0.28.2/pkg/apis/pipeline/v1beta1/openapi_generated.go:178:11: cannot use ref("k8s.io/api/core/v1.Volume") (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
../../../../../../go/pkg/mod/github.com/tektoncd/pipeline@v0.28.2/pkg/apis/pipeline/v1beta1/openapi_generated.go:208:8: cannot use ref("k8s.io/api/core/v1.PodDNSConfig") (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
../../../../../../go/pkg/mod/github.com/tektoncd/pipeline@v0.28.2/pkg/apis/pipeline/v1beta1/openapi_generated.go:240:11: cannot use ref("k8s.io/api/core/v1.LocalObjectReference") (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
../../../../../../go/pkg/mod/github.com/tektoncd/pipeline@v0.28.2/pkg/apis/pipeline/v1beta1/openapi_generated.go:254:11: cannot use ref("k8s.io/api/core/v1.HostAlias") (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
../../../../../../go/pkg/mod/github.com/tektoncd/pipeline@v0.28.2/pkg/apis/pipeline/v1beta1/openapi_generated.go:277:3: cannot use "github.com/go-openapi/spec".Schema{...} (type "github.com/go-openapi/spec".Schema) as type "k8s.io/kube-openapi/pkg/validation/spec".Schema in field value
../../../../../../go/pkg/mod/github.com/tektoncd/pipeline@v0.28.2/pkg/apis/pipeline/v1beta1/openapi_generated.go:320:3: cannot use "github.com/go-openapi/spec".Schema{...} (type "github.com/go-openapi/spec".Schema) as type "k8s.io/kube-openapi/pkg/validation/spec".Schema in field value
../../../../../../go/pkg/mod/github.com/tektoncd/pipeline@v0.28.2/pkg/apis/pipeline/v1beta1/openapi_generated.go:320:3: too many errors

**Comment by towithyou** [comment]
## go version
go version go1.16.7 darwin/amd64

## go mod pipeline version
github.com/tektoncd/pipeline v0.28.2

**Comment by ycyxuehan** [comment]
how to fix this?
my cluster is 0.23.0

**Comment by sbwsg** [comment]
@ycyxuehan we updated our version of knative in tekton pipelines. Could you try again and see if the problem is fixed for you?

**Comment by wlynch** [comment]
Confirmed this is fixed with the latest version of pipelines + deps:

```
require (
        github.com/tektoncd/pipeline v0.32.0
        k8s.io/apimachinery v0.23.2
        k8s.io/client-go v0.23.2
)
```
