### ISSUE TITLE
Support specifying resource requests at the TaskRun level

### ISSUE THREAD

**Issue by jsravn** [tektoncd/pipeline#4326]
### Feature request

Currently resource requests can only be done at the Task level. However this is limiting when trying to reuse generic tasks. It would make more sense to me to have resources specified in the TaskRun, with the Task providing a set of defaults.

### Use case

An example that came up recently is using the [kaniko hub task](https://hub.tekton.dev/tekton/task/kaniko). The resources required will vary widely based on the contents of the Dockerfile. As is, I have to redefine this Task based on each build, making the shared task fairly useless.

Possibly related to https://github.com/tektoncd/pipeline/issues/2986.

**Comment by lbernick** [comment]
Hi @jsravn, I think this use case would be addressed by #4080, which I'm currently working on, so I'm going to close this as a duplicate issue. Please feel free to reopen if needed.

triage/duplicate
/close

**Comment by vdemeester** [comment]
> Hi @jsravn, I think this use case would be addressed by #4080, which I'm currently working on, so I'm going to close this as a duplicate issue. Please feel free to reopen if needed.
> 
> triage/duplicate /close

Although it might be addressed by #4080, I wonder if it should be the way it gets solved. For example, I want to use a Task from the Hub/Catalog, where I do not have any control, and this Task doesn't have any *parametrized* resource limits/requirements setup, then I want to be able to provide this at runtime.
Hence I would like to keep this one open for now.

**Comment by jsravn** [comment]
I agree that it makes sense to do this generically at the TaskRun level. I think conceptually it makes sense to consider resources as an instance/run level attribute rather than that of the task.

**Comment by lbernick** [comment]
Sorry this took some time, but [TEP-0094: Configuring Resources at Runtime](https://github.com/tektoncd/community/blob/main/teps/0094-configuring-resources-at-runtime.md) is now implementable.
