### ISSUE TITLE
Update skaffold revision to resolve example test failures on ppc64le

### ISSUE THREAD

**Issue by Siddhesh-Ghadi** [tektoncd/pipeline#4334]
Below 2 example tests fail on `ppc64le` architecture due to issue in `golang:1.12.5-alpine3.9` docker image used by [GoogleContainerTools/skaffold](https://github.com/GoogleContainerTools/skaffold/blob/v0.32.0/examples/microservices/leeroy-web/Dockerfile#L1) `v0.32.0`
> TestExamples/v1alpha1/taskruns/build-push-kaniko
TestExamples/v1alpha1/pipelineruns/pipelinerun

Image build of revision `v0.32.0` of `GoogleContainerTools/skaffold` during test fails on `ppc64le` architecture with 
```bash
# _/go
/usr/local/go/pkg/tool/linux_ppc64le/link: running gcc failed: exec: "gcc": executable file not found in $PATH
error building image: error building stage: failed to execute command: waiting for process to exit: exit status 2
```

From revision `v1.20.0` onwards, the `skaffold` code is update to use `golang:1.15` which is working on ppc64le.

Here is the patch I used to update skaffold revision to resolve test failures 

```diff
diff --git a/examples/v1alpha1/pipelineruns/pipelinerun.yaml b/examples/v1alpha1/pipelineruns/pipelinerun.yaml
index 36e65a8f..dac2a70a 100644
--- a/examples/v1alpha1/pipelineruns/pipelinerun.yaml
+++ b/examples/v1alpha1/pipelineruns/pipelinerun.yaml
@@ -44,7 +44,7 @@ spec:
   type: git
   params:
   - name: revision
-    value: v0.32.0
+    value: v1.32.0
   - name: url
     value: https://github.com/GoogleContainerTools/skaffold
 ---
@@ -103,6 +103,7 @@ spec:
     - --dockerfile=$(inputs.params.pathToDockerFile)
     - --destination=$(outputs.resources.builtImage.url)
     - --context=$(inputs.params.pathToContext)
+    - --build-arg=BASE=alpine:3
 ---
 # This task deploys with kubectl apply -f <filename>
 apiVersion: tekton.dev/v1alpha1
@@ -235,7 +236,7 @@ spec:
     - name: path
       value: /workspace/workspace/examples/microservices/leeroy-web/kubernetes/deployment.yaml
     - name: yqArg
-      value: "-d1"
+      value: "-d0"
     - name: yamlPathToImage
       value: "spec.template.spec.containers[0].image"
 ---
diff --git a/examples/v1alpha1/taskruns/build-push-kaniko.yaml b/examples/v1alpha1/taskruns/build-push-kaniko.yaml
index fe01ed47..a89a5204 100644
--- a/examples/v1alpha1/taskruns/build-push-kaniko.yaml
+++ b/examples/v1alpha1/taskruns/build-push-kaniko.yaml
@@ -16,7 +16,7 @@ spec:
   type: git
   params:
   - name: revision
-    value: v0.32.0
+    value: v1.32.0
   - name: url
     value: https://github.com/GoogleContainerTools/skaffold
 ---
@@ -53,6 +53,7 @@ spec:
     - --destination=$(outputs.resources.builtImage.url)
     - --context=$(inputs.params.pathToContext)
     - --oci-layout-path=$(inputs.resources.builtImage.path)
+    - --build-arg=BASE=alpine:3
     securityContext:
       runAsUser: 0
   sidecars:
```

I see the skaffold `revision` was changed from `master` to `v0.32.0` in #1038. 
Can we **bump** it up to `v1.20.0` or higher or should we just **skip** these tests on ppc64le architecture?

**Comment by Siddhesh-Ghadi** [comment]
Did you get a chance to look at it? - @vdemeester @afrittoli

**Comment by afrittoli** [comment]
@Siddhesh-Ghadi thank you for reporting this and offering a solution too. 
The reason the version is pinned is to avoid random CI breakages caused by Skaffold changes.
If `v1.32.0` works well with `ppc64le` I guess it will work well with other arch's too, so updating it sounds like a very good idea.

Would you like to propose a PR to fix this, since you prepared a solution already?
Thank you!

**Comment by Siddhesh-Ghadi** [comment]
Sure. Will create a PR soon.
