### ISSUE TITLE
ImagePullSecrets for "system" images

### ISSUE THREAD

**Issue by chenbh** [tektoncd/pipeline#4339]
### Feature request

Add a controller flag or configuration option to specify which secret(s) to use for pulling "system" images like entrypoint, nop, shell-image, etc.

### Use case

In a firewalled or air gapped environment where the cluster can't reach gcr.io, images can be mirrored into a private registry behind the firewall. While it's trivial to update the deployment yaml for the controller and webhook, there's no way to specify `imagePullSecrets` for the [images passed to the controller via args](https://github.com/tektoncd/pipeline/blob/6ac0cbc81d7df69cf163e3c980c76efc559afc96/pkg/apis/pipeline/images.go#L24-L47). This breaks tekton as pods like `affinity-assistant` and init containers are unable to start.

I'm willing to work on this feature.

**Comment by imjasonh** [comment]
Is there some reason you can make the mirrored Tekton images available for unauthenticated users within the internal registry? That might be easier than plumbing through `imagePullSecrets` to access otherwise publicly-available, non-sensitive Tekton images that happen to have been mirrored into the internal registry.

If that's not possible (e.g., due to limitations in the internal registry, or broad policies against unauthenticated images access), we can probably solve this a few different ways, but I wanted to make sure we considered the easiest one first 😄

**Comment by imjasonh** [comment]
> 2. Extend the podTemplate functionality to affinity-assistant pods. default-pod-template can be used to propagate imagePullSecret to all TaskRuns and get the init containers working, but only the tolerations and node selector from the PipelineRun pod template are propagated to the affinity-assistant pod.

I think it might be confusing to conflate the `default-pod-template` that gets applied to workload pods and the configuration of Affinity Assistant pods. I might prefer to have a separate `affinity-assistant-pod-template` config option, to separate these configs.

This also lets us be more diligent about which PodTemplate fields we support in `default-pod-template` vs for Affinity Assistant. AFAIK nobody has expressed a need to set the `runtimeClassName` on AA, and I'd like to be able to consider adding it explicitly, as well as future fields we support for `default-pod-template`.

**Comment by chenbh** [comment]
> broad policies against unauthenticated images access
Unfortunately this is the case. Technically this can be solved by attaching the imagePullSecret to the ServiceAccount, but we're operating in an environment with a clear distinction between users (i.e. Pipeline/Task authors) and cluster operators (i.e. ability to configure/deploy Tekton) and I would prefer this functionality to be the responsibilities of the operators.

> I think it might be confusing to conflate the `default-pod-template` that gets applied to workload pods and the configuration of Affinity Assistant pods.
Personally, I consider the AA pods to be "invisible" to the user - they shouldn't have to think about them, they are there just to make the other parts of the system work. But I don't have too strong of an opinion either way and am happy to update the PR if y'all are in agreement with it.

> AFAIK nobody has expressed a need to set the `runtimeClassName` on AA
Fair enough, I was over-eager on bringing the AA PodTemplate to parity with the workload PodTemplate.

**Comment by imjasonh** [comment]
> Personally, I consider the AA pods to be "invisible" to the user - they shouldn't have to think about them, they are there just to make the other parts of the system work. But I don't have too strong of an opinion either way and am happy to update the PR if y'all are in agreement with it.

I definitely agree. I'd say the existence and configuration of AA is an operator's concern and not a user's, and in general a user of Tekton on the cluster shouldn't have to care at all about the default ConfigMap, etc.

It sounds like we have a good path forward with adding `affinity-assistant-pod-template` which supports only `imagePullSecrets` for now, and we can add more when/if/however we need to in the future.

Thanks for proposing this, I think this is going to be really useful for other users like yourself who are mirroring Tekton images into their clusters.

**Comment by chenbh** [comment]
> which supports only `imagePullSecrets` for now

The current implementation also supports `nodeSelector` and `tolerations`, just confirming that we shouldn't remove that functionality.

> It sounds like we have a good path forward with adding `affinity-assistant-pod-template`

This should also mean creating a new PipelineRun.spec.affinityAssistantPodTemplate field as well right? Since the current PipelineRun podTemplate functionality will be split into 2 separate fields, would that be considered a backwards incompatible API change?
