### ISSUE TITLE
metrics retention: it is good to have 3 new metrics per taskrun?

### ISSUE THREAD

**Issue by guillaumerose** [tektoncd/pipeline#4340]
I am looking at performance tests for the pipeline controller. I see good metrics but I am worry that we have too many of them.
The controller is expected to stay up and running for months. With the current impl, I see it keeps 3 metrics / taskruns forever.
If it runs a lot of taskruns, it can grow a bit too much and for sure might slow down the /metrics endpoint.

Underneath, I think we miss something in the opencensus API to avoid that. We have only Gauge, and I think, Prometheus Histogram would better fit (esp for pod latency). 

# Expected Behavior

No new metric, or short-lived metrics are created?

# Actual Behavior

3 new metrics are created per taskrun.

Example:
```
tekton_pipelines_controller_cloudevent_count{namespace="default",pipeline="",pipelinerun="",status="success",task="anonymous",taskrun="home-volume-6nl68"} 0
tekton_pipelines_controller_taskrun_duration_seconds{namespace="default",status="success",task="anonymous",taskrun="home-volume-6nl68"} 11
tekton_pipelines_controller_taskruns_pod_latency{namespace="default",pod="home-volume-6nl68-pod-9h69l",task="anonymous",taskrun="home-volume-6nl68"} 0
```

# Steps to Reproduce the Problem

1. count metrics exported by the pipeline controller
2. create bunch of taskruns
3. recount metrics.

**Comment by sbwsg** [comment]
@guillaumerose we have a TEP in proposed state that looks designed to tackle the issues you mention: https://github.com/tektoncd/community/blob/main/teps/0073-simplify-metrics.md

I'm going to close this issue as a dupe given that we have this existing design.  If you review that TEP and find that your use-case isn't accounted for then please feel free to reopen this issue and we can look into it a bit more. Cheers!

/close

**Comment by sbwsg** [comment]
I've added a link to this issue as a reference to the TEP: https://github.com/tektoncd/community/pull/552
