### ISSUE TITLE
Duplicated pod for a single TaskRun

### ISSUE THREAD

**Issue by RafaeLeal** [tektoncd/pipeline#4358]
# Expected Behavior
To have a single pod for each TaskRun

# Actual Behavior
Two or more pods for a single TaskRun

# Steps to Reproduce the Problem

We are noticing that on our cluster, but we didn't manage to reliably reproduce it.
We noticed that happens when the task fails.

# Additional Info

- Kubernetes version:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:11:29Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.20-eks-8c579e", GitCommit:"8c579edfc914f013ff48b2a2b2c1308fdcacc53f", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:13Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version: v0.22.0

- Other info 

I checked the logs from the controller, there are no errors related, but we can see two `Successfully reconciled taskrun ...` messages for each pod.

**Comment by afrittoli** [comment]
@RafaeLeal thank you for your bug report!

We discussed about the issue of duplicate `TaskRuns` at a recent API WG - see https://docs.google.com/document/d/17PodAxG8hV351fBhSu7Y_OIPhGTVgj6OJ2lPphYYRpU/edit#heading=h.jfxo8cbjfecz (search for duplicate). 

A solution to the issue we would like to attempt is to generated unique but reproducible `TaskRun` names, so that any attempt to create a duplicate `TaskRun` would fail.

**Comment by RafaeLeal** [comment]
I don't have access to this document right now. 
But this case we are duplicating pods, not TaskRuns.. Since the relationship between pods and TaskRuns should be 1:1 we could even consider use the same name of the TaskRun instead of using some generated name, AFAIK. I'm not sure if we have some reason to use generated names.

**Comment by afrittoli** [comment]
> I don't have access to this document right now. 

That document are the meeting notes from the Tekton API Working Group. If you would like to access it, or any other meeting notes, you could join the [tekton-dev](https://groups.google.com/g/tekton-dev) or [tekton-users](https://groups.google.com/g/tekton-users) google groups.

> But this case we are duplicating pods, not TaskRuns. Since the relationship between pods and TaskRuns should be 1:1 we could even consider use the same name of the TaskRun instead of using some generated name, AFAIK. I'm not sure if we have some reason to use generated names.

I suppose the same issue (informer cache not updated) that may lead to duplicate `TaskRun` may also lead to duplicate `Pods` - in both cases we have no reason to use randomly generated names like today so we could change both.

**Comment by RafaeLeal** [comment]
This one thing caught my attention. We are ignoring NotFound errors when the TaskRun.Status.PodName is not empty, which makes the reconciler create a new pod (line 459 of the same file). Why do we need this? It seems to me that we could have duplicated pods if we have read-after-write inconsistency.
https://github.com/tektoncd/pipeline/blob/main/pkg/reconciler/taskrun/taskrun.go#L415-L416

**Comment by RafaeLeal** [comment]
> I suppose the same issue (informer cache not updated) that may lead to duplicate `TaskRun` may also lead to duplicate `Pods` - in both cases we have no reason to use randomly generated names like today so we could change both.

Since we are calling the API, not using Listers, I think it might be a different problem.
