### ISSUE TITLE
Extend breakout logic in stopSidecars

### ISSUE THREAD

**Issue by SaschaSchwarze0** [tektoncd/pipeline#4373]
### Feature request

This is a follow-on issue to [this slack thread](https://tektoncd.slack.com/archives/CK3HBG7CM/p1636965530045300?thread_ts=1636722092.041100&cid=CK3HBG7CM) and pull request [Breakout sidecar stopping if TaskSpec has no sidecar #4372](https://github.com/tektoncd/pipeline/pull/4372). The pull request only optimizes for TaskRuns that have no sidecar in their TaskSpec. There is potentially also an optimization possible if the TaskSpec has sidecars and the TaskRun's `status.Sidecars` indicates that all stop logic did already run.

This would further reduce the need to retrieve the pod which can potentially fail if the pod has already been deleted.

### Use case

As Tekton seems to run periodic reconciliations for all TaskRuns, any optimization that prevents pod retrievals that can potentially fail (and therefore imo involve the API server), is a reasonable improvement for systems with many TaskRuns.

**Comment by imjasonh** [comment]
The logic to stop sidecars is here: https://github.com/tektoncd/pipeline/blob/26176ce931b98ea22d3260be23d07dc117112509/pkg/pod/entrypoint.go#L224

It should be fairly simple to have a check that at least one of the `tr.Status.Sidecar` elements has a `Running` element (indicating that it's still running and needs to be stopped). A subsequent problem is that `stopSidecars` returns the `pod`

https://github.com/tektoncd/pipeline/blob/26176ce931b98ea22d3260be23d07dc117112509/pkg/reconciler/taskrun/taskrun.go#L144

This is apparently used for recording metrics, which indicates that a global resync will also re-emit latency metrics, which can be very misleading.

I have a partial WIP PR here that might help: https://github.com/imjasonh/pipeline/pull/new/avoid-stop-sidecars -- I'll add more tests and send it out.
