### ISSUE TITLE
Replace `PipelineResources` in examples and documentation

### ISSUE THREAD

**Issue by jerop** [tektoncd/pipeline#4375]
Today, some [examples](https://github.com/tektoncd/pipeline/tree/main/examples) and references in documentation use `PipelineResources`. However, we recently deprecated `PipelineResources`. For more information about the deprecation, see [TEP-0074](https://github.com/tektoncd/community/blob/main/teps/0074-deprecate-pipelineresources.md).

We need to update the examples and references in documentation to use `Tasks` and other replacement features instead of `PipelineResources`. 

Related Issues:
- https://github.com/tektoncd/pipeline/issues/1673
- https://github.com/tektoncd/pipeline/issues/3705

**Comment by vdemeester** [comment]
> Today, some [examples](https://github.com/tektoncd/pipeline/tree/main/examples) and references in documentation use `PipelineResources`. However, we recently deprecated `PipelineResources`. For more information about the deprecation, see [TEP-0074](https://github.com/tektoncd/community/blob/main/teps/0074-deprecate-pipelineresources.md).
> 
> We need to update the examples and references in documentation to use `Tasks` and other replacement features instead of `PipelineResources`.
> 
> Related Issues:
> 
> * [Pipeline Resources Redesign #1673](https://github.com/tektoncd/pipeline/issues/1673)
> * [Replacing PipelineResources in tutorial #3705](https://github.com/tektoncd/pipeline/issues/3705)

Few things.

1. the TEP is in `proposed` state. To be fully "deprecated" we need to have a release that state they are deprecated with a timeline ?
2. The examples are.. not really example as they are used for testing purpose. In that case, as long as the feature is in the code, it needs to be tested. We should probably separate examples (for documentation purposes) from test data in yaml 👼🏼 

Other that this +:100: 🎉

**Comment by bobcatfish** [comment]
Just freezing this in advance b/c we need to do this even if it goes stale:

/lifecycle frozen

**Comment by geriom** [comment]
Commenting so I can be assigned to this issue.

**Comment by vdemeester** [comment]
@geriom you should be able to comment ´/assign´ and be directly assigned at the same time I think.
/assign @geriom

**Comment by geriom** [comment]
We no longer have the reference to `PipelineResources` in the tutorial. About the examples, quoting @vdemeester reply:

> 2\. The examples are.. not really example as they are used for testing purpose. In that case, as long as the feature is in the code, it needs to be tested. We should probably separate examples (for documentation purposes) from test data in yaml

@jerop  Does that mean we close this issue?

**Comment by jerop** [comment]
@geriom sounds good, thank you for working on this issue!

**Comment by lbernick** [comment]
Maybe we can move examples with pipelineresources out of examples and into test/yamls -- this way they will still be tested but not act as documentation of how to do things

**Comment by lbernick** [comment]
There are still some examples in docs that are using pipelineResources: https://github.com/tektoncd/pipeline/blob/main/docs/tasks.md#code-examples

We might also want to change the examples used for tests that we recommend people look at: https://github.com/tektoncd/pipeline/blob/main/examples/README.md#examples
