### ISSUE TITLE
Task Image Caching

### ISSUE THREAD

**Issue by baileyn** [tektoncd/pipeline#4377]
Hello,

We use Tekton for our CICD pipelines, and we ran in to a strange issue today. When we executed our pipeline, the TaskRun that came up was using an `ImageID` that didn't match any tag that was in our Azure Container Registry. The sha was actually later found to be an image that was uploaded yesterday.

Is there a way we can enforce the TaskRun's to always use the latest version of whatever tag is passed? I'm not sure if it was a caching issue, but everywhere I've looked the image tag was correctly set to our appropriate tag for the environment.

**Comment by imjasonh** [comment]
You should be able to configure `imagePullPolicy` in the step container spec to accomplish this:

```
steps:
- image: my.registry/image:tag
  imagePullPolicy: Always
```

The defaulting behavior for `imagePullPolicy` is a bit confusing, depending on whether the image tag is `:latest`: https://kubernetes.io/docs/concepts/containers/images/#imagepullpolicy-defaulting

**Comment by baileyn** [comment]
Ah okay! I think that is exactly what it is. This is the first time we moved from `latest` to a different tag so I bet that's what happened. Thanks!
