### ISSUE TITLE
Documentation on Pipeline Controller Metrics seems to be outdated

### ISSUE THREAD

**Issue by photoni-137** [tektoncd/pipeline#4381]
# Expected Behavior
The documentation provides the correct metric names.
# Actual Behavior
The documented metric names seem to be outdated; `tekton` needs to be replaced by `tekton_pipelines_controller`. 

For example: `tekton_pipelinerun_count` is now called `tekton_pipelines_controller_pipelinerun_count`.
# Steps to Reproduce the Problem
Curl the metrics endpoint of the pipelines controller.
# Additional Info
Running tektoncd/pipeline v0.22.0.

**Comment by afrittoli** [comment]
[ ] v0.22: https://github.com/tektoncd/pipeline/pull/4382
[ ] v0.23: 
[ ] v0.24:
[ ] v0.25:

**Comment by afrittoli** [comment]
This is now fixed. It will take a nightly sync to get the latest version live.

**Comment by afrittoli** [comment]
I triggered it manually - fixes are live!
https://tekton.dev/vault/pipelines-v0.25.0/metrics/
