### ISSUE TITLE
Webhook is extremely noisy

### ISSUE THREAD

**Issue by ludydoo** [tektoncd/pipeline#4389]
# Expected Behavior

tekton-pipeline-webhook to not be called for every config map update in the cluster

# Actual Behavior

every time there is a leader election in any namespace, the tekton-pipeline-webhook gets called, since it configures the validatingwebhookconfiguration (`config.webhook.pipeline.tekton.dev`) to trigger the webhook for ALL configmaps in ALL namespaces.

# Steps to Reproduce the Problem

1. Install tekton using the recommended method
2. Install cert-manager
3. Check tekton-pipeline-webhook logs

# Additional Info

- Kubernetes version: 1.21.2

  **Output of `kubectl version`:**

  ```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:34:20Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"881d4a5a3c0f4036c714cfb601b377c4c72de543", GitTreeState:"clean", BuildDate:"2021-10-21T05:13:01Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
  ```

**Comment by mattmoor** [comment]
In knative upstream we limit to configmaps in Knative namespaces with this `namespaceSelector`:
https://github.com/knative/serving/blob/cd175b5d376027f659ce13960e79470878f59ba1/config/core/webhooks/configmap-validation.yaml#L33-L36

It looks like Tekton is making use of an `objectSelector` here: https://github.com/tektoncd/pipeline/blob/123c78a33857f79e95a93b628aadde9aab60b7d2/config/500-webhooks.yaml#L88

IDK why the webhook would get invoked for configmaps without these `labels`.

**Comment by ludydoo** [comment]
My guess is that the webhook component updates the validating/mutating webhooks, it requires update permission on mutate/validate hooks in its clusterrolebinding… perhaps it’s not updating it correctly (not keeping the object selector)?

**Comment by mattmoor** [comment]
@ludydoo you are probably right.  The logic to preserve `namespaceSelector` may blow away the `objectSelector`.

**Comment by vdemeester** [comment]
The `objectSelector` matches all objects that have `app.kubernetes.io/part-of: tekton-pipelines` label right ? If that the case (aka if we don't "filter" configmaps), this can be anything shipped my tektoncd/pipeline, the deployment, service, pods. That might be *why* it gets very spammy ?

/cc @imjasonh @afrittoli

**Comment by imjasonh** [comment]
The initial report says it was spamming logs for ConfigMap changes, "for ALL configmaps in ALL namespaces." -- but _only_ for ConfigMaps, seemingly. I'm trying this now to see if I can reproduce.

**Comment by imjasonh** [comment]
@ludydoo what version of Tekton are you using? I'm not able to reproduce this with the latest release ([v0.30.0](https://github.com/tektoncd/pipeline/releases/tag/v0.30.0)) installed.

FWIW I'm also not seeing the `namespaceSelector` getting set, or the `objectSelector` being unset, as part of webhook reconciliation:

```
$ k get validatingwebhookconfigurations.admissionregistration.k8s.io config.webhook.pipeline.tekton.dev -oyaml     
...
  namespaceSelector: {}
  objectSelector:
    matchLabels:
      app.kubernetes.io/part-of: tekton-pipelines
```

**Comment by ludydoo** [comment]
@imjasonh hmm this is strange, I'll have a double check to make sure that I didn't just plainly remove it for some reason..
