### ISSUE TITLE
error: no kind "PipelineRun" is registered for version "tekton.dev/v1beta1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"

### ISSUE THREAD

**Issue by ipirva** [tektoncd/pipeline#4403]
# Expected Behavior
I am using Pipeline v0.30.0, Triggers 0.17.1
PipelineRun registered for version "tekton.dev/v1beta1" 
# Actual Behavior
```
❯ kubectl get pipelinerun -n tekton-pipelines
NAME                                       SUCCEEDED   REASON   STARTTIME   COMPLETIONTIME
pipeline-productcatalogservice-run-xl4z5   False       Failed   11s         7s

❯ kubectl logs pipelinerun/pipeline-productcatalogservice-run-xl4z5 -n tekton-pipelines
error: no kind "PipelineRun" is registered for version "tekton.dev/v1beta1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"

❯ kubectl get customresourcedefinition | grep -i pipeline
pipelineresources.tekton.dev                                                   2021-12-03T00:07:19Z
pipelineruns.tekton.dev                                                        2021-12-03T00:07:19Z
pipelines.tekton.dev                                                           2021-12-03T00:07:19Z
```
# Steps to Reproduce the Problem

GitHub calls a webhook on Tekton and a pipeline is running.

`apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: github-trigger-template
  namespace: tekton-pipelines
spec:
  params:
  - description: The git repository url
    name: gitUrl
  - description: The docker image
    name: image
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: pipeline-run-
    spec:
      pipelineRef:
        name: pipeline
      params:
      - name: gitUrl
        value: $(tt.params.gitUrl)
      - name: image
        value: $(tt.params.image)
      serviceAccountName: tekton-triggers-sa
      workspaces:
        - name: source-dir
          persistentVolumeClaim:
            claimName: tekton-workspace
`

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:41:42Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2+vmware.1", GitCommit:"54e7e68e30dd3f9f7bb4f814c9d112f54f0fb273", GitTreeState:"clean", BuildDate:"2021-06-28T22:12:04Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
❯ kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'
v0.30.0
```

**Comment by ipirva** [comment]
I installed the tekton components as such:
`kubectl apply -f https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.30.0/release.yaml -f https://storage.googleapis.com/tekton-releases/triggers/previous/v0.17.1/release.yaml -f https://storage.googleapis.com/tekton-releases/triggers/previous/v0.17.1/interceptors.yaml`
I could try the installation on a fresh GKE cluster. I ran into the same error:
`❯ kubectl logs pipelinerun/pipeline-productcatalogservice-run-dqc2d -n tekton-pipelines
error: no kind "PipelineRun" is registered for version "tekton.dev/v1beta1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"`

I have not figured out from where it comes.

**Comment by ipirva** [comment]
I have just tried to run a TaskRun - I experience the same error:
`❯ kubectl logs taskrun/build-docker-image-from-git-source-productcatalogservice-t9xmnl -n tekton-pipelines
error: no kind "TaskRun" is registered for version "tekton.dev/v1beta1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"`

**Comment by ipirva** [comment]
It seems to have been caused by a mistake in one of the secrets I am using.

**Comment by vdemeester** [comment]
Hey @ipirva,
this actually comes from the fact, given the command you wrote, because you are trying to run `kubectl logs` on Tekton objects. This is not supported, we cannot add a `log` sub-resource on CRDs (yet ?) in kubernetes, hence the command failing.
