### ISSUE TITLE
Refactor reconciler events package to separate events and cloudevents

### ISSUE THREAD

**Issue by lbernick** [tektoncd/pipeline#4404]
The /pkg/reconciler/events package is [responsible](https://github.com/tektoncd/pipeline/blob/07adee706154ce7b79045dd109f1382e997b3163/pkg/reconciler/events/event.go#L45-L49) for functionality related to events and functionality related to cloudevents. However, there is a separate cloudevents sub-package in the events package, which contains test code for both cloudevents and [events](https://github.com/tektoncd/pipeline/blob/main/pkg/reconciler/events/cloudevent/testing.go#L27-L28). These should either be refactored to separate responsibilities or combined into one package, avoiding circular dependencies in tests.

cc: @sbwsg 
/kind cleanup

**Comment by vdemeester** [comment]
cc @afrittoli 
One of the goal here is to extract the cloudevent functionnality outside of pipeline, see [here](https://github.com/tektoncd/experimental/tree/main/cloudevents)
