### ISSUE TITLE
Tekton Pipelines v0.30.0 requires k8s 1.20 as its minimum version

### ISSUE THREAD

**Issue by adambkaplan** [tektoncd/pipeline#4412]
# Expected Behavior

Tekton pipelines should be able to run on k8s 1.19, per the current installation guidance.

# Actual Behavior

The pipelines controller reports an error that it does not support k8s 1.19.

# Steps to Reproduce the Problem

1. Install Tekton Pipelines on a k8s 1.19 cluster
2. View the logs of the pipelines controller

# Additional Info

- Kubernetes version: 1.19.x

- Tekton Pipeline version: 0.30.0

It appears that the knative dependency update to v1.0 is the root cause of this issue. See https://github.com/tektoncd/pipeline/pull/4354

**Comment by adambkaplan** [comment]
Note that k8s 1.19 is no longer supported by the upstream Kubernetes community - updating relevant documentation to require k8s 1.20 would make the most sense in my opinion.

FYI @nikhil-thomas this perhaps will have an impact on the Tekton operator as well.

**Comment by jerop** [comment]
@adambkaplan thank you for the issue report! 

updated both the release notes and documentation 
- release: https://github.com/tektoncd/pipeline/releases/tag/v0.30.0
- documentation: https://github.com/tektoncd/pipeline/pull/4414
