### ISSUE TITLE
update-openapigen.sh must be run in GOPATH

### ISSUE THREAD

**Issue by imjasonh** [tektoncd/pipeline#4430]
# Expected Behavior

In a non-`GOPATH` directory, run `./hack/update-openapigen.sh` and have the resulting code pass CI checks.

# Actual Behavior

Example (from https://github.com/tektoncd/pipeline/pull/4420):
https://tekton-releases.appspot.com/build/tekton-prow/pr-logs/pull/tektoncd_pipeline/4420/pull-tekton-pipeline-build-tests/1470859112957874182/

The result is tons of CI-blocking diffs because paths don't match the expected paths, which have the full absolute import path prepended.

# Steps to Reproduce the Problem

1. `cd $(mktemp -d) && git clone https://github.com/tektoncd/pipeline && cd pipeline`
2. `go build ./cmd/... && go test ./pkg/...` (works, as it should)
2. `./hack/update-openapigen.sh`
3. Push a PR and see CI failures like above ☝️

**Comment by vdemeester** [comment]
Similar but different: https://github.com/tektoncd/pipeline/issues/3884
