### ISSUE TITLE
affinity-assistant statefulset's podTemplate not set imagePullSecrets

### ISSUE THREAD

**Issue by tomonight** [tektoncd/pipeline#4431]
# Expected Behavior
  affinity-assistant pod set imagePullSecret and pull image correct when in a private docker hub.
# Actual Behavior
  affinity-assistant pod pull image authorization failed.
# Steps to Reproduce the Problem

1.normal step and every times

# Additional Info

- Kubernetes version:
  ```
  1.20
  ```

- Tekton Pipeline version:

   ```
   0.30
   ```

**Comment by sbwsg** [comment]
Thanks for the issue report! As you noted on PR #4348 this is the same issue as #4339 .  I'm going to close this one as a duplicate of #4339 since the work for that one is already in progress. Cheers!
