### ISSUE TITLE
Tekton Pipelines DSL 

### ISSUE THREAD

**Issue by lengrongfu** [tektoncd/pipeline#4453]
### Feature request

At present, the Tekton project needs to create various CRD resource files, which is not user-friendly. Is there any plan to introduce Tekton Pipelines DSL, similar to the description file in GitHub Aciton.

### Use case

CI

**Comment by jerop** [comment]
@lengrongfu there's ongoing related work in a new project called Workflows
 
- https://github.com/tektoncd/community/issues/464
- [Experimental Project](https://github.com/tektoncd/experimental/tree/main/workflows) 
- [TEP-0098: Workflows](https://github.com/tektoncd/community/pull/569)
 
> The goal is to provide a way for users to set up and manage end to end CI/CD workflow configuration in a single place by relying on other Tekton primitives like Pipelines and Triggers.

They have a working group if you're interested in joining: https://github.com/tektoncd/community/blob/main/working-groups.md#workflows

cc @dibyom

**Comment by lengrongfu** [comment]
Thank you very much, I am interested, I will first understand the current situation and see what I can contribute to it. @jerop
