### ISSUE TITLE
When a task of a pipeline run timeout , the finally tasklist will not be implemented?

### ISSUE THREAD

**Issue by NEUerYZY** [tektoncd/pipeline#4458]
As the title told, when I use the feature "finally" keyword as the documents expound  with the Tekton version 0.25.0.
I write the pipelinerun yaml  as follows.
------------------------------------------------------------------------------------------
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: pipelinerun-
spec:
  pipelineSpec:
    tasks:
      - name: task1
        taskRef:
          name: task1
    finally:
      - name: clean-task
        taskRef:
          name: clean-task

I found that the finally task  "clean-task"  does not execute, when the task1 run exceed  the time limits of tekton.
The main requirement of my usage is that I want to do some clean task  at the end of the pipelinerun  even if some task is out of time limit.  
I want to figure out how to  resolve this scene or I can access my purpose  with some other substitution.
THANKS

**Comment by lbernick** [comment]
Hi @NEUerYZY, [this section](https://tekton.dev/docs/pipelines/pipelineruns/#configuring-a-failure-timeout) of the Tekton docs may be helpful. It looks like you aren't specifying any timeouts in your pipelinerun, so the global timeout of 60 mins applies. You can set a timeout for your pipeline and reserve some of it for finally tasks, as shown in the docs, or you can choose to set 0 (for no timeout) for your pipelinerun.

**Comment by jerop** [comment]
We may need to update the documentations to make it clear

**Comment by NEUerYZY** [comment]
@lbernick Thank you for your  reply ,I tried the solution as the doc illustrated and it works

**Comment by NEUerYZY** [comment]
@jerop That's great ,Thank you very much

**Comment by lbernick** [comment]
We should also consider changing the default timeout behavior to reserve some time for finally tasks.

**Comment by major1201** [comment]
> We should also consider changing the default timeout behavior to reserve some time for finally tasks.

@lbernick Has this feature been implemented? Finally tasks should always be run even if the main pipeline has timeout.
