### ISSUE TITLE
Can a pipeline support Non-K8's Cluster?

### ISSUE THREAD

**Issue by catfish1225** [tektoncd/pipeline#4501]
I have a Tekton project which is running CICD pipeline in that there is one step which is basically wants to trigger a service that is not running in a K8's cluster (Containerization way) & it is running outside of cluster can I do that? 
                                                                  (OR)
Consider If I have a step which needs to execute a service on a remote machine can I do that?

**Comment by nikhil-thomas** [comment]
https://hub.tekton.dev/tekton/task/sonarqube-scanner

this an example might help you 🧑‍💻  

also
- https://hub.tekton.dev/?category=CLI
- https://hub.tekton.dev/tekton/task/prometheus-gate
- https://hub.tekton.dev/tekton/task/argocd-task-sync-and-wait
- https://hub.tekton.dev/tekton/task/trigger-jenkins-job

**Comment by nikhil-thomas** [comment]
cc @vinamra28

**Comment by vinamra28** [comment]
thanks @nikhil-thomas for pointing :+1: 
@catfish1225 do you want to run something in a remote VM? If so, there is already a task available in tektoncd/catalog which might help you right ➡️ https://hub.tekton.dev/tekton/task/remote-ssh-commands
