### ISSUE TITLE
Include Pod Reasons in TaskRun API reasons?

### ISSUE THREAD

**Issue by wlynch** [tektoncd/pipeline#4513]
Noticed this as a part of https://github.com/tektoncd/pipeline/issues/4512.

We describe [`TaskRunReason`](https://pkg.go.dev/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1#TaskRunReason) as:

> TaskRunReason is an enum used to store all TaskRun reason for the Succeeded condition that are controlled by the TaskRun itself. Failure reasons that emerge from underlying resources are not included here

But really, this does not include **all** reasons - there's a separate set of Pod related Reasons that can show up here - https://github.com/tektoncd/pipeline/blob/92746a2362117c729ad865717dd0dab5ec3d326b/pkg/pod/status.go#L35-L66

This makes the API documentation a bit misleading. Should we include the Pod reasons in the v1beta1/v1alpha1 Task/Pipeline reasons?

**Comment by lbernick** [comment]
/close

I think this is a duplicate of #4802
