### ISSUE TITLE
      Is there  kubernetes agent in Tekton pipeline 	

### ISSUE THREAD

**Issue by chekly** [tektoncd/pipeline#4516]
Hello, I am new to Tekton pipeline. I am migrating Jenkins file from Tekton pipeline

I do have the follow jenkinsfile codes

pipeline {
    libraries {
      lib 'operator-pipeline-library'
    }
    parameters {
      string(name: 'OPERATOR_CATALOG_REPO', description: ' operator images that are in the catalog', defaultValue: 'operator-3rdparty-dev-local.net')
      string(name: 'OPERATOR_INDEX', description: 'Artifactory ', defaultValue: 'operator-3rdparty-catalog-dev-local.net')
    }
    agent {
        kubernetes {
            cloud 'openshift'
            yamlFile 'operator-mirror-pod.yaml'
        }
    }
    }

I do want to know  how do I re-write the following 

agent {
        kubernetes {
            cloud 'openshift'
            yamlFile 'operator-pod.yaml'
        }
    }

in Tekton pipelines

**Comment by waveywaves** [comment]
https://github.com/tektoncd/catalog/tree/main/task/kubernetes-actions is what you're looking for I suppose
