### ISSUE TITLE
Design a Simple Result Store API for Pipeline CRD Results

### ISSUE THREAD

**Issue by tejal29** [tektoncd/pipeline#452]
## Expected Behavior
Right now we do not have a result store for Pipeline and Task Runs. We have complex API available and looks like it is difficult to adapt in our case. 
This is a tracking issue and @pmbethe09 will be working on this

## Steps to Reproduce the Problem

1.
2.
3.

**Comment by bobcatfish** [comment]
Gonna close this for now, will revisit result handling later.
