### ISSUE TITLE
Termination message getting updated twice

### ISSUE THREAD

**Issue by pritidesai** [tektoncd/pipeline#4545]
Updating the termination message for a container was moved under `defer` ([reference](https://github.com/tektoncd/pipeline/pull/2429/files#diff-4f4c36fd479ff7f6bc3a251fe425563a9270cef95a9ea157060b67a8d9b63503R88)) such that the `startedAt` is updated in case of a step being `skipped`. (I think an alternate discussion point here can be - whether `startedAt` should be even set to anything since that container was not even started.) The changes were done in PR https://github.com/tektoncd/pipeline/pull/2429.

https://github.com/tektoncd/pipeline/blob/7a0a988cafaa64ff3e08969fa66f8521638d9b52/pkg/entrypoint/entrypointer.go#L109-L114

When we introduced task `results` two years back, we implemented such that the task results are written to the termination message file as a separate [call](https://github.com/tektoncd/pipeline/commit/07c6201057177626741aafcdfd77042a08374d03#diff-4f4c36fd479ff7f6bc3a251fe425563a9270cef95a9ea157060b67a8d9b63503R143).

https://github.com/tektoncd/pipeline/blob/7a0a988cafaa64ff3e08969fa66f8521638d9b52/pkg/entrypoint/entrypointer.go#L215-L219

With my little understanding of how/when the termination message is being written to `etcd` and made available as part of the `taskRun` status, would it make sense to update the termination message just once as part of the `defer` instead of having these two separate calls. Logically, it does make sense to combine both these calls and update the termination message once.  

/kind question

**Comment by afrittoli** [comment]
@pritidesai is this question still valid?
