### ISSUE TITLE
Document  fields for Task run and Pipeline Run state.

### ISSUE THREAD

**Issue by tejal29** [tektoncd/pipeline#455]
## Expected Behavior
Document the fields which can describe a pipeline run state and task run state.
@tejal29 has already started a document here https://docs.google.com/document/d/1CUAsqgk_7PM_g8XKfXbvbqUnHnY3ujZegnI7H3IbMns/edit

Iterate over this and fix all the fields.

## Actual Behavior
Does not exist right now.
## Steps to Reproduce the Problem

1.
2.
3.

**Comment by bobcatfish** [comment]
@tejal29 when you get a chance could you update this with some details about why this doc is needed?

Also as a side note, the fields in those CRDs change pretty regularly so it might be hard to keep a doc in sync with them 🤔 One thing you could do is decide to document just the fields from a major release, i.e. the 0.1 release we have coming up - but also it might be better to point anyone who needs to the fields to a reliable way they can check the fields themselves (e.g. looking at the go code, or the docs, or running a kubectl command)

**Comment by bobcatfish** [comment]
Gonna close this for now, will revisit results handling later.
