### ISSUE TITLE
Write a user-friendly introductory setup guide.

### ISSUE THREAD

**Issue by geriom** [tektoncd/pipeline#4553]
### Feature request

As part of the [docs strategy](https://github.com/tektoncd/website/pull/337) to provide better educational content, create a straightforward reproducible local environment setup to use in the introductory tutorials. 

### Use case

This setup guide can be referenced everywhere else in the documentation as a first step to test a feature locally. The most likely runtime at this moment would be [minikube](https://minikube.sigs.k8s.io/docs/start/) , because it's multi-platform and easy to install.

**Comment by lbernick** [comment]
Some content on minikube already at https://github.com/tektoncd/pipeline/blob/main/docs/developers/local-setup.md#using-minikube

**Comment by jerop** [comment]
@Yongxuanzhang adding docs for using kind: https://github.com/tektoncd/pipeline/pull/4606

**Comment by geriom** [comment]
The new Introductory docs are available in the "Getting Started" section of the docs page: https://tekton.dev/docs/getting-started/
