### ISSUE TITLE
Write "Getting started with pipelines" doc

### ISSUE THREAD

**Issue by geriom** [tektoncd/pipeline#4555]
Write and introductory tutorial for users who are completely new to Tekton to create their first pipeline.

This tutorial would be the natural second step for new users that already read how to create a single task. It should be a straightforward reproducible tutorial, that can be run locally and doesn't include more information that necessary.

**Comment by bryceyang** [comment]
> This was [merged](https://github.com/tektoncd/website/commit/d42039557375ab42aa45f39c5d056770c192b1b9) and the tutorial is now [available on the website](http://localhost:1313/docs/getting-started/pipelines/).

nice work!  but the tutorial link is a localhost url.

**Comment by geriom** [comment]
> nice work! but the tutorial link is a localhost url.

Well, it works on my machine 😅

Sorry about that, I just updated my comment with the correct link.
