### ISSUE TITLE
Document real-life examples

### ISSUE THREAD

**Issue by geriom** [tektoncd/pipeline#4559]
This is an open-ended issue to hear ideas about real-life scenarios that we would like to find in the documentation.

**Comment by lbernick** [comment]
A Tekton user (Avinash Upadhyaya K R) wrote [this article](https://hashnode.com/post/tekton-ci-simplified-ckzleauyw0n6beks1diq6ejvv) about getting started with Tekton, using an example node js pipeline.

**Comment by lbernick** [comment]
Lots of good examples as well in https://github.com/tektoncd/pipeline/tree/main/examples

**Comment by geriom** [comment]
We finally have a couple of howtos:  a [git clone how-to](https://tekton.dev/docs/how-to-guides/clone-repository/) and currently a [build-push with Kaniko how-to is being reviewed](https://github.com/tektoncd/website/pull/394).

I'm closing this issue since it's goal was not well-scoped. It's probably better to open issues with specific examples in mind. Thank you for the links.
