### ISSUE TITLE
Task skipped when parallel task fails

### ISSUE THREAD

**Issue by DragD** [tektoncd/pipeline#4571]
## Intro
I have simple pipeline consisting of 4 instances of the same task. The task just exits with the value provided as parameter.

![snap01243](https://user-images.githubusercontent.com/17828303/153747032-abe5ced4-0e93-41c3-8666-f7bb704a05d9.jpg)

## Expected Behavior
When running the pipeline with exit code `1` for task-2, the parallel `task-4` should run and complete.

## Actual Behavior
When running the pipeline with exit code `1` for task-2, **the parallel `task-4` is skipped**.

![snap01244](https://user-images.githubusercontent.com/17828303/153747292-c8de12c4-467e-422d-ad49-7d67fe1fdb67.jpg)

## Steps to Reproduce the Problem

1. Create the example pipeline and task from the attached yaml manifests.
2. Create a pipelinerun with value for param `exit-code-2` of "1" with the attached `example-pipeline-run.yaml`

[task-skipped.zip](https://github.com/tektoncd/pipeline/files/8055282/task-skipped.zip)

## Additional Info

- The value of `scope-when-expressions-to-task` in configmap `feature-flags` in namespace `openshift-pipelines` is `true`.

Additional checks:
  1. When a 'finally' task is added to the above pipeline and the `exit-code-2` is "1", the `task-4` runs and completes.
  2. When the 'finally' task is removed from the above pipeline and the `exit-code-2` is "1", the `task-4` again runs and completes.
  3. When the last pipelinerun above is repeated with the `exit-code-2` is "1", the parallel `task-4` is skipped.

The above additional checks leads me to believe there might be a deeper issue here.

### Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2+c8538fc", GitCommit:"013336330731c6e987b6486ad779721bf3aebe97", GitTreeState:"clean", BuildDate:"2021-11-17T14:59:36Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```

### Tekton Pipeline version:

**Output of `tkn version`:**

```shell
Client version: 0.21.0
Pipeline version: v0.28.2
Triggers version: v0.16.1
```

### Reproduced on:
  - Openshift 4.8 on IBM Cloud
  - Openshift CodeReady Containers

### Context:
The example pipeline above mimics a CI/CD pipeline where
- task-1 is git-clone
- task-2 is some security scan of the clone repo
- task-3 is container image build
- task 4 is deploy to the cluster

**Comment by pritidesai** [comment]
thank you @DragD for reporting this issue 👍 

Based on the pipeline definition, `task-2` and `task-3` are starting to execute right after `task-1` is done (`runAfter: [task-1]`). And `task-2` exiting with failure is causing the pipeline to stop executing anything further. 

There is also a timing factor which plays role, if `task-3` finishes before `task-2` fails, `task-4` will be scheduled and executed. 

There is an option to handle this kind of failure with `onError`. You can set `onError` to `continue` in `task-2` to continue executing the rest of the pipeline. But this will cause the pipelineRun to result in `success` instead of `failure`. What is the expected pipelineRun status for your pipeline?

**Comment by pritidesai** [comment]
> The value of scope-when-expressions-to-task in configmap feature-flags in namespace openshift-pipelines is true.

This flag only applies to `when expressions`. It does not impact your pipeline in any way without any when expressions. Reference: https://github.com/tektoncd/pipeline/blob/main/docs/pipelines.md#guard-task-execution-using-when-expressions

**Comment by pritidesai** [comment]
> Additional checks:

> When a 'finally' task is added to the above pipeline and the exit-code-2 is "1", the task-4 runs and completes.

Are you adding a `finally` task in addition to the four tasks specified in the pipeline definition? Or `task-4` is moved under `finally`? 

> When the 'finally' task is removed from the above pipeline and the exit-code-2 is "1", the task-4 again runs and completes.
> When the last pipelinerun above is repeated with the exit-code-2 is "1", the parallel task-4 is skipped.

I am confused by these two checks, what is the difference between them?

**Comment by DragD** [comment]
@pritidesai 
Thank you for the explanation!

It appears I misunderstood or omitted part of the documentation. To clarify: Any failing task on a parallel branch will block the execution of the consequent tasks (except for the final tasks) and thus will fail the pipeline run. Correct?

About the `scope-when-expressions-to-task`: I included its value just in case it is relevant.

About the "Additional checks" section above: the three numbered steps are executed one after another in addition to the four tasks specified in the pipeline definition, i.e. the final task is fifth.

**Comment by pritidesai** [comment]
> Any failing task on a parallel branch will block the execution of the consequent tasks (except for the final tasks) and thus will fail the pipeline run. Correct?

Yup, that's correct. Once a task fails, the pipeline will not schedule any new tasks but will wait for the already executing tasks to finish before exiting with an error.

**Comment by pritidesai** [comment]
> the difference between the step 2 and 3 is the outcome. With step 2, task-4 runs and completes. With step 3, task-4 is skipped.

Yup thats my confusion, how can the outcome be different 🤔  without having any difference in the definition unless there is anything else different or I am not reading it right 🙃 

Without any finally task and setting exit-code-2 to 1, the task-4 runs and completes but sometimes the task-4 is skipped 🤔

**Comment by DragD** [comment]
... "how can the outcome be different"... That's confusing to me too.

**Comment by DragD** [comment]
There is no need to test. I am not able now to reproduce every time the steps above from the section "Additional checks". You were correct about the timing factor which also plays role. If `task-4` occasionally starts before `task-2`, then `task-4` completes even though `task-2` fails but that is not always the case.

About the `onError`: I can't use it because our OpenShift cluster is provider-managed and there is a feature flag value, which is `stable`. It should be `alpha` in order to use the `onError`.

**Comment by pritidesai** [comment]
> About the `onError`: I can't use it because our OpenShift cluster is provider-managed and there is a feature flag value, which is `stable`. It should be `alpha` in order to use the `onError`.

`onError` was promoted to the latest stable API (`v1beta1`) with Pipelines 0.29:

https://github.com/tektoncd/pipeline/commit/41192338e661b9dc7bceb845255221db89b5e082 

I notice you are using `v0.28.2` 😞

**Comment by vdemeester** [comment]
> About the `onError`: I can't use it because our OpenShift cluster is provider-managed and there is a feature flag value, which is `stable`. It should be `alpha` in order to use the `onError`.

@DragD also, if you are using 1.6, you can enable alpha feature-flags from the operator options (need to have the rights to change the operator configuration though)
