### ISSUE TITLE
How to define ServiceAccount to run task without defining TaskRun or PipelineRun

### ISSUE THREAD

**Issue by mzaikin** [tektoncd/pipeline#4585]
Hi all:
On the project we use some **Pipeline**s, and **Task**s, but we don't have/use explict **TaskRun** or **PipelineRun**.
We simply start via web UI.
In the past, all PipelineRuns  used by default "pipeline"ServiceAccount (see screenshot), and after some update the default ServiceAccount name became "default", therefore all security settings (e.g. Git access) broke. (see screenshot)
The questions are:
1) Can we control which ServiceAccount to use when we start Pipeline via web UI ? I have not noticed any field or option to provide. We don't use CLI and don't create PipelineRun, as user provides required inputs in web UI.
2) If we don't provide explicitly ServiceAccount name, how can we configure Tekton Pipelines to use "pipeline" ServiceAccount by default instead of "default"?
3) Maybe we can configure a new field in start pipeline UI to enter ServicveAccount name?

Thank you

old TaskRun
![image](https://user-images.githubusercontent.com/278199/154275292-0b5eb8e5-95c9-49e9-9679-91106e093300.png)

recent TaskRun
![image](https://user-images.githubusercontent.com/278199/154275537-e66523f3-ff78-4a68-94d3-14f165f6044b.png)

how we start a pipeline:
![image](https://user-images.githubusercontent.com/278199/154276584-bc76eb9b-2712-4595-8743-393a0dbc838b.png)

**Comment by vdemeester** [comment]
Hey @mzaikin, thanks for the issue. This is most likely an OpenShift Pipelines and OpenShift console issue than on tektoncd/pipeline. What version of OpenShift are you running ?

From your report it seems, somehow the `pipelines` SA is not created anymore on new namespaces, which could mean it was disabled **or** something is going wrong on the OpenShift Pipelines operator side. I think there also might be an issue to bring up to openshift/console to not be able to set a ServiceAccount on PipelineRun / Taksrun ?

**Comment by mzaikin** [comment]
Hi @vdemeester 
Sorry for the delayed reply.
We use OpenShift 4.8.26_1542
I cannot tell if `pipeline` SA not created for new namespaces, as I don't create new projects, just use old ones.
For old projects the `pipeline` SA exists, and all secrets are fine (e.g. to push to internal Image Registry)
And I can run Pipeline under `pipeline` SA, but only if I assign it in PipelineRun object explicitly.
If I run via simple Web UI, then Pipeline runs under `default` SA.
So, I gave up, and granted `default` SA all required roles, and use it from now on.
But I should admit that in the past by default was used `pipeline` SA if I strat via Web UI.
