### ISSUE TITLE
Add array of all tasks' results as variable

### ISSUE THREAD

**Issue by HildaHay** [tektoncd/pipeline#4589]
### Feature request

Right now, each task's result is available as an individual variable. I'd like to have another variable that contains all of the tasks' results as an array.

### Use case

When my pipeline fails, I'd like to send the programmer a message telling them which task it failed on, to help them figure out what went wrong without having to check the dashboard if it was a simple problem. Right now, it's possible to do this by passing all the individual task result variables to the message task, but combining them into a single array would make this simpler and easier to maintain.

**Comment by jerop** [comment]
@HildaHay - Thank you for opening this feature request. We already have a proposal to support array `Results`: [TEP-0076: Expanded array support: results and indexing](https://github.com/tektoncd/community/blob/main/teps/0076-array-result-types.md).

cc @bobcatfish @wlynch

**Comment by lbernick** [comment]
Array results have been released! They are available starting in v0.38.0.
