### ISSUE TITLE
Debug scripts are not mounted to steps with no scripts

### ISSUE THREAD

**Issue by dgaffuri** [tektoncd/pipeline#4613]
# Expected Behavior
Adding breakpoint to a TaskRun running any task will cause debug scripts volume to be mounted on each step
# Actual Behavior
If a step in Task doesn't define script but specify command and args the debug scripts volume is not mounted
# Steps to Reproduce the Problem

1. Define a TaskRun including breakpoints for a task with a step not defining scripts, like kn/0.1 from catalog, including parameters that will cause the step to fail
```
kubectl apply -f - <<EOF
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: kn
spec:
  debug:
    breakpoint: ["onFailure"]
  taskRef:
    name: kn
  params:
    - name: ARGS
      value: [ "invalid" ]
EOF
```
2. Login to the pod
`kubectl exec -it kn-pod -- /bin/sh`
3. Check that no debug scripts are mounted
```
/ $ ls /tekton/
bin            creds          creds-secrets  downward       home           results        run            steps          termination
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

 ```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:32:32Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
Client version: 0.22.0
Pipeline version: v0.33.0
Triggers version: v0.18.0
Dashboard version: v0.24.1
```

**Comment by yuzp1996** [comment]
Hi! I am interested in this issue and want to take this one. If I need any help I will mention it here.

**Comment by yuzp1996** [comment]
I have reproduced the same error in my local environment then I will try to find the related code and find why this happened

**Comment by yuzp1996** [comment]
I have reproduced the same error in my local environment  and I will check the code and find out how this happened

**Comment by yuzp1996** [comment]
<img width="1656" alt="image" src="https://user-images.githubusercontent.com/23007448/163960513-e012e011-e781-4af1-b40e-66f4d96a02fa.png">

maybe this is the cause of this bug
