### ISSUE TITLE
update task API defintion

### ISSUE THREAD

**Issue by pritidesai** [tektoncd/pipeline#4615]
Thank you @jerop for updating the `pipeline` API definitions in https://github.com/tektoncd/pipeline/pull/4601. 

We need similar updates to the `task` API:

https://github.com/tektoncd/pipeline/blob/main/docs/tasks.md#configuring-a-task

Please update the required and optional sections to include all the fields we support.

/help-wanted
/good-first-issue
/kind documentation

**Comment by cpanato** [comment]
Can I take this one? If i have questions can follow up here? Thanks

**Comment by vdemeester** [comment]
@cpanato of course 👍🏼 and yeah, any question, please follow-up in this issue 😉 
/assign @cpanato

**Comment by vsinghai** [comment]
All the fields in the `Tasks` spec are present in the docs. This can be closed.
