### ISSUE TITLE
What are config-artifact-pvc and config-artifact-bucket configured for 

### ISSUE THREAD

**Issue by shenqinb-star** [tektoncd/pipeline#4621]
when I'm reading https://tekton.dev/docs/pipelines/install/#configuring-pipelineresource-storage, I'm not quite understand `config-artifact-pvc` and `config-artifact-bucket`.
Are they only configured for pipelineResource, Do they have any relationship with Workspace PV?
Since pipelineResource is deprecated, Do I need to configure them if I'm not use pipelineResource?

**Comment by vdemeester** [comment]
Hey @shenqinb-star 

> Are they only configured for pipelineResource, Do they have any relationship with Workspace PV?

Yes, they are only for PipelineResources.

> Since pipelineResource is deprecated, Do I need to configure them if I'm not use pipelineResource?

Nope, if you don't use PipelineResources, you don't need to configure them.

**Comment by shenqinb-star** [comment]
Thanks alot @vdemeester. it helps
