### ISSUE TITLE
Update PipelineRun API documentation

### ISSUE THREAD

**Issue by lbernick** [tektoncd/pipeline#4657]
Similar to #4601. We should update the [PipelineRun API docs](https://github.com/tektoncd/pipeline/blob/main/docs/pipelineruns.md#configuring-a-pipelinerun) to reflect all existing fields.

/kind documentation
/help-wanted
/good-first-issue

**Comment by ssunitaa** [comment]
Hi there,

Thank you so much for your reply and for giving me an opportunity to
contribute and learn here. Please give me some time to go through the
requirements and understand the process. I shall soon be coming up with my
list of questions. 🙂
However, to start with -
1. How can I communicate with the team - through this email or GitHub? I am
a novice in GitHub, so quite a lot to learn.
2. Is this a REST API that we have to document?

I'm ready and excited!

Thanks and Regards,
Sunita Arora
