### ISSUE TITLE
ServiceAccount Token Mount Violates FHS 5.13. /var/run

### ISSUE THREAD

**Issue by spencerrung** [tektoncd/pipeline#4666]
Referencing these two closed tickets as well 

https://github.com/tektoncd/pipeline/issues/2738
https://github.com/tektoncd/pipeline/issues/2726
# Expected Behavior
FHS
https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch05s13.html

ServiceAccount Token should mounted to `/run` and not `/var/run`

# Actual Behavior
The service account tokens are mounted to `/var/run`

# Steps to Reproduce the Problem

1.  Reference a service account
```
spec:
    serviceAccountName: build-bot
```
2. Check pod for mount `/var/run/secrets/kubernetes.io/serviceaccount from build-bot-token`

# Additional Info
This majorly impacts alpine based images as well as other installs that use the `/var/run` location as tmpfs.

- Tekton Pipeline version:
```
Client version: 0.21.0
Pipeline version: v0.32.0
Triggers version: v0.18.0
Dashboard version: v0.23.0
```

**Comment by vdemeester** [comment]
Hey @spencerrung, thanks for the issue. As fare as I know, this is kubernetes behavoior (see https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/). I don’t think there is too much tekton can do there.

**Comment by lbernick** [comment]
Closing, I don't think there's anything for Tekton to do here.
