### ISSUE TITLE
Multi-cluster pipeline?

### ISSUE THREAD

**Issue by ileixe** [tektoncd/pipeline#4673]
Hi,

We're currently using three Pipelines among the two clusters like below

```
Pipeline A (Cluster 1) -> Pipeline B (Cluster 1)
                       -> Pipeline C (Cluster 2)
```

Since Pipeline C has CPU intensive tasks while Pipeline B has some requirements which make us to run the pipeline at specific cluster, we could not avoid to separate the tasks into two different pipelines (which will run on two different clusters)

I could not find right way to make a Pipeline which allow us to meet the requirement above, so we leveraged github status API and trigger only when the status of pipeline A is finished. It's quite breakable and unmaintainable so I am looking for the native way to deploy pipelines among the two clusters.

Any advice will be appreciated.

Thanks

**Comment by jbpratt** [comment]
Hi @ileixe, I don't believe there is a native way to achieve this currently, but I think you could build something utilizing [`kcp`](https://github.com/kcp-dev/kcp), gleaming insights from this neat project: https://github.com/openshift-pipelines/pipelines-service maybe @guillaumerose or @bnallapeta have some thoughts on this :cat:

**Comment by bnallapeta** [comment]
@ileixe Yes! we are currently working on Pipelines/Tasks deployed/managed on multiple clusters using kcp as @jbpratt pointed out - [pipelines-service](https://github.com/openshift-pipelines/pipelines-service)

But, the management of workload (pipelines) on different physical clusters is handled by kcp. So, I am not sure if it directly supports your requirement i.e., control which pipeline runs on which cluster.

@vdemeester thoughts? :)
