### ISSUE TITLE
Which version of client-go provides build pack support?

### ISSUE THREAD

**Issue by zeromsi** [tektoncd/pipeline#4675]
I was using the following versions of client-go, apimachinery, and k8s-api to create tekton objects. 
```
//go get k8s.io/api@kubernetes-1.12.9
//go get k8s.io/apimachinery@kubernetes-1.12.9
//go get k8s.io/client-go@kubernetes-1.12.9
```

Now I want to create task, taskrun and pipeline, but failing due to version conflicts among these libs. Can anyone provide me the relevant versions of these clients.

**Comment by jbpratt** [comment]
Hi @zeromsi , you can find the versions tekton uses here: 

https://github.com/tektoncd/cli/blob/df0da5dec5f7dc08a18ce28a8d8a43f206a7adea/go.mod#L61-L64

https://github.com/tektoncd/pipeline/blob/6738db7a179dd93adef40ac29a375cdfdf8823ee/go.mod#L6-L8

**Comment by zeromsi** [comment]
@jbpratt Thanks man!
