### ISSUE TITLE
Unit Tests for Custom Task Retries

### ISSUE THREAD

**Issue by lbernick** [tektoncd/pipeline#4686]
Custom Task restries were added in #4327; however, some parts of the code base were missed and addressed in #4625 and #4647. We should test Custom Task retries E2E, fix any bugs if necessary, and increase our test coverage of this functionality.

**Comment by yuzp1996** [comment]
Hi @lbernick it is my first time writing an e2e test. I went through the custom task document and the e2e test existing in the code base. And I want to sync with you about what I want to do and looking forward to your suggestion!

I read the document [Tekton runs](https://tekton.dev/docs/pipelines/runs/) [IBM introducing about custom task](https://developer.ibm.com/articles/introducing-tekton-custom-tasks/) and the [e2e retry test](https://github.com/tektoncd/pipeline/blob/main/test/retry_test.go). I want to write an e2e test like [e2e retry test](https://github.com/tektoncd/pipeline/blob/main/test/retry_test.go) but will first create the [custom task controller and pipeline with ko](https://github.com/tektoncd/experimental/tree/main/task-loops) and then check the run's status.

I am not good at English now if there is any offence please tell me and forgive me. Thanks!

**Comment by yuzp1996** [comment]
> Thanks so much @yuzp1996, I appreciate the enthusiasm!
> 
> I know I said "test E2E in the original issue", but I think the best place here to start would be to add some more test coverage of custom task retries to the pipelinerun reconciler. [This existing test case](https://github.com/tektoncd/pipeline/blob/c938ee5667fb64ddcf6e6c26e7732b68dde82104/pkg/reconciler/pipelinerun/pipelinerun_test.go#L591) is the closest thing we currently have, but we could really use a test case that reconciles a pipelinerun with a custom task with retries, and verify that if the most recent attempt failed, the pipelinerun reconciler restarts the custom task if it has retries remaining (and does not restart the custom task if there are no retries remaining).
> 
> If you'd like to also add E2E tests that run on a cluster, I would recommend against using the task-loops custom task controller you've linked. Instead, I think it would be useful to have a custom task controller that is meant just for testing. The controller could set the custom task status based on the custom task [spec](https://github.com/tektoncd/pipeline/blob/c938ee5667fb64ddcf6e6c26e7732b68dde82104/pkg/apis/pipeline/v1alpha1/run_types.go#L44) (or just set the status to succeeded to start). I think a controller like this would be generally useful for developers adding features to runs who want to test things out on their cluster.
> 
> I'm at a conference this week but I am happy to help more next week if needed! Also feel free to contact me on the [tekton slack](https://github.com/tektoncd/community/blob/2c479e73125e1bc8ced536f4698ad9665379a776/contact.md#slack).

Thanks for your reply, your suggestion is very important to me. I will do as you suggest. If I need any help, I will try to contact you. Thanks again!

**Comment by pritidesai** [comment]
All pipeline `e2e` tests and examples run against a common configuration of the tekton controller. This will help a lot if we can enable custom task `e2e` tests or examples in our CI (dogfooding cluster). 

One option is to work with @afrittoli to enable custom configurations for these kind of tests where an `alpha` feature can be enabled (custom task is still alpha) and a custom controller is deployed. See: https://github.com/tektoncd/plumbing/issues/1017

Until we have `e2e` tests, will be great to add more unit tests for the controller.

**Comment by pritidesai** [comment]
@afrittoli @imjasonh Can we treat the tekton controller as a `custom task controller` instead of writing and deploying a `test custom controller`? In a long run, it will be great to have a dedicated test custom controller but just to unblock the testing for now.

**Comment by vdemeester** [comment]
@pritidesai I tend to agree with @imjasonh, and I don't really think it would make sense to make the main controller act as a custom task controller just for the tests (if we want to provide "default built-in" custom task, maybe we could do that, but even, it would probably make sense to extract it in another deployment).

**Comment by lbernick** [comment]
Created https://github.com/tektoncd/pipeline/issues/5120 to track a custom Task controller; this issue can just be to track unit tests.

**Comment by JeromeJu** [comment]
This comment summarizes the findings after digging into  [TEP-69](https://github.com/tektoncd/community/blob/main/teps/0069-support-retries-for-custom-task-in-a-pipeline.md#test-plan) and checking the possibilities of test coverage improvement, suggesting that this can be closed.

TEP69 related summaries:
The implementation of [TEP-69: Support retries for custom task in a pipeline](https://github.com/tektoncd/community/pull/491) passes down the `retries` field. 

Thanks to the discussions of @bobcatfish and @ScrapCodes:
> * Try to use the same approach used for retrying TaskRuns (using [retriesstatus](https://github.com/tektoncd/pipeline/blob/f041ef5d644c72e88689e079a8e3ea96718891fc/pkg/apis/pipeline/v1beta1/taskrun_types.go#L201-L204)) - it would be a bit weird b/c it would mean the PIipelines controller would be changing the status of the Run which I think up until this point we've avoided (i.e. it's the custom task controller's responsibility to deal with status)
The test plan changed according to the above reference for controller’s cohesiveness. And therefore, the current test cases regarding `retries` are sufficient on the level of unit-tests.

- Test Coverage:
[getRetryableTask](https://github.com/tektoncd/pipeline/blob/main/pkg/reconciler/pipelinerun/resources/pipelinerunstate.go#L313) is worth notifying and it has been covered by its caller and tested in [pipelinerunstate](https://github.com/tektoncd/pipeline/blob/main/pkg/reconciler/pipelinerun/resources/pipelinerunstate_test.go/#L945)
For possible improvements, this function could be decoupled as retries-related. Further refactorization would be required.

- Follow up:
#5182 as a follow up issue, addresses the cases where the custom controller does not support retries and it could be further improved. 

Thanks to cc@ llllll for the guidance.
