### ISSUE TITLE
Add Tekton CRD Schema to JSON Schema Store for YAML extension used in VS Code

### ISSUE THREAD

**Issue by Lucifergene** [tektoncd/pipeline#4688]
### Feature request

When using the [YAML extension by Red Hat](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml) in VSCode during the writing YAML files, the files are showing errors when the `kind` is set to  `Task`, `Pipeline`, etc, which are specific to Tekton. This extension fetches all the schemas from [JSON Schema Store Website](https://www.schemastore.org/json/) and matches our input with them. On this website, most of the schemas of the current CNCF tools are present, apart from Tekton.  
Since the Tekton schema is not present in the database, it is not fetched by the extension, and therefore throws an error, when such keywords are mentioned.  
This makes writing Tekton files difficult when working with VS Code and having the YAML extension installed. The workaround is to disable the extension to continue writing Tekton YAML files.  

Therefore it would be great if the Tekton JSON schema is made available on the [JSON Schema Store Website](https://www.schemastore.org/json/) so that the YAML extension can save it in the database and can provide IntelliSense while writing Tekton files.

### Use case

Creating the JSON schema for all the CRDs of Tekton Pipelines and uploading it to the JSON Schema Store Website](https://www.schemastore.org/json/), will help developers work on Tekton files without disabling the YAML extension by Red Hat](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml).   
This will aid users with IntelliSense and other code completion features that the YAML Extension provides.

**Comment by abayer** [comment]
This feels related to #1461, but it's not exactly the same thing - I don't think structural OpenAPI schemas can actually be used as "true" JSON schemas. That said, I think generating a "true" JSON schema probably wouldn't hit the weird edge case problems we've had with auto-generating structural OpenAPI schemas, so this should be easier to pull off.

**Comment by abayer** [comment]
Ah, another hassle - file type mapping. schemastore maps specific filenames/patterns to specific schemas - since we don't have any consistent requirement for Tekton-related CRD filenames, there isn't really a way to say "oh, you're writing a Tekton `Pipeline`, here's the schema for that".

**Comment by kamok** [comment]
This was done? I don't see Tekton CRD related schemas on the [JSON Schema Store Website](https://www.schemastore.org/json/)

**Comment by ppitonak** [comment]
`v1beta1` manifests are validated correctly when I install `Tekton Pipelines` extension but `v1` fails.

**Comment by lslavkov** [comment]
Is there any progress on this issue? Based on the status it seems it is closed.

**Comment by avinal** [comment]
Added schema to JSON Schema Store: https://github.com/SchemaStore/schemastore/pull/5178

**Comment by afrittoli** [comment]
> Added schema to JSON Schema Store: [SchemaStore/schemastore#5178](https://github.com/SchemaStore/schemastore/pull/5178)

Thanks @avinal - how do we maintain the schema up to date over time? Do we need at least some doc for contributors that if the schema is changed it should be updated on schema store too?

**Comment by avinal** [comment]
Hey Andrea,

> Do we need at least some doc for contributors that if the schema is changed it should be updated on schema store too?

As long as the changes are in the main branch with the same path of https://github.com/redhat-developer/vscode-tekton, no updates are required; Schemastore will automatically fetch the latest one. 

I can add a note in the repository that if the path is changed or the schema is moved, please open a PR in the schemastore repository. WDYT?
