### ISSUE TITLE
Failed to create pipeline resource by tektoncd client

### ISSUE THREAD

**Issue by zeromsi** [tektoncd/pipeline#4691]
I have update my client version. Now I don't see any function to create pipeline resource . May be Pipeline resource has been deprecated. If so, then what is the workaround?

**Comment by jbpratt** [comment]
Hey @zeromsi , you are correct, [PipelineResources have been deprecated](https://github.com/tektoncd/pipeline/blob/main/docs/resources.md#pipelineresources) in [`v0.30.0`](https://github.com/tektoncd/pipeline/blob/main/docs/deprecations.md#deprecation-table). Here is the [TEP](https://github.com/tektoncd/community/blob/main/teps/0074-deprecate-pipelineresources.md) in which you can find reasoning on the deprecation. You can find a document [here](https://github.com/tektoncd/pipeline/blob/main/docs/migrating-v1alpha1-to-v1beta1.md#replacing-pipelineresources-with-tasks) on migrating from `PipelineResources` to `Tasks`.

**Comment by vdemeester** [comment]
@zeromsi you can look at what the CLI does. In the code, the PipelineResource are in a different package, meaning different versionedClient, …
- https://github.com/tektoncd/cli/blob/main/pkg/cmd/pipelineresource/list.go#L29
- https://github.com/tektoncd/cli/blob/main/pkg/cmd/pipelineresource/list.go#L130

**Comment by zeromsi** [comment]
@jbpratt and @vdemeester  Thanks bro.
