### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0 on PipelineLoop custom tasks

### ISSUE THREAD

**Issue by rafalbigaj** [tektoncd/pipeline#4729]
# Expected Behavior

Tekton Pipelines Controller should skip Runs that are indirectly created by the PipelineRun (e.g. by custom tasks).

# Actual Behavior

Tekton Pipelines Controller panics with:

```
panic: runtime error: index out of range [0] with length 0

goroutine 250 [running]:
github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun.updatePipelineRunStatusFromRuns(0xc000e78060, 0xc000cfa000, {0xc000d12010, 0x1, 0x0})
	github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun/pipelinerun.go:1278 +0x2b1
github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun.(*Reconciler).updatePipelineRunStatusFromInformer(0xc0004946e0, {0x21b2f08, 0xc000c580c0}, 0xc000cfa000)
	github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun/pipelinerun.go:1171 +0x288
github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun.(*Reconciler).ReconcileKind(0xc0004946e0, {0x21b2f08, 0xc0010180f0}, 0xc000cfa000)
	github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun/pipelinerun.go:218 +0x11f7
github.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1beta1/pipelinerun.(*reconcilerImpl).Reconcile(0xc00032ebe0, {0x21b2f08, 0xc000a39650}, {0xc0008a1440, 0x20})
	github.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1beta1/pipelinerun/reconciler.go:235 +0x6a2
github.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller.(*Impl).processNextWorkItem(0xc0004d22a0)
	github.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller/controller.go:542 +0x5a5
github.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller.(*Impl).RunContext.func3()
	github.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller/controller.go:478 +0x68
created by github.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller.(*Impl).RunContext
	github.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller/controller.go:476 +0x2de
kubectl -n tekton-pipelines get deployment tekton-pipelines-controller -o yaml | grep image
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"controller","app.kubernetes.io/instance":"default","app.kubernetes.io/name":"controller","app.kubernetes.io/part-of":"tekton-pipelines","app.kubernetes.io/version":"v0.33.2","pipeline.tekton.dev/release":"v0.33.2","version":"v0.33.2"},"name":"tekton-pipelines-controller","namespace":"tekton-pipelines"},"spec":{"replicas":1,"selector":{"matchLabels":{"app.kubernetes.io/c
```

# Steps to Reproduce the Problem

1. Enable custom tasks feature flag
2. Deploy https://github.com/kubeflow/kfp-tekton/tree/master/tekton-catalog/pipeline-loops custom controller
3. Run example: https://github.com/kubeflow/kfp-tekton/blob/master/tekton-catalog/pipeline-loops/examples/loop-example-with-parallelism.yaml

# Additional Info

- Kubernetes version:

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:30:48Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:34:54Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version: v0.33.2

**Comment by abayer** [comment]
So the immediate problem is the `&&` at https://github.com/tektoncd/pipeline/blob/76d39b3886588c1fc62a107f966138f8bb10443b/pkg/reconciler/pipelinerun/pipelinerun.go#L1300, though I feel like something's not right in that the `Run` triggering the panic doesn't have any owner references? If that `Run` was created from a `PipelineRun`, it sure feels like it should have owner references...

**Comment by afrittoli** [comment]
> So the immediate problem is the `&&` at
> 
> https://github.com/tektoncd/pipeline/blob/76d39b3886588c1fc62a107f966138f8bb10443b/pkg/reconciler/pipelinerun/pipelinerun.go#L1300
> 
> , though I feel like something's not right in that the `Run` triggering the panic doesn't have any owner references? If that `Run` was created from a `PipelineRun`, it sure feels like it should have owner references...

@rafalbigaj do you have any input on this?

**Comment by rafalbigaj** [comment]
@abayer it is the case described by @afrittoli. I'm testing `Run` created by a user, which is of type `PipelineLoop`.
Here is the example: https://github.com/kubeflow/kfp-tekton/blob/master/tekton-catalog/pipeline-loops/examples/pipelinespec-with-run-arrary-value.yaml

**Comment by afrittoli** [comment]
This bug has been introduced in Oct 2020, so I'm not sure its fix warrants a minor release - as it's not a regression.
That said, I'd not be so not happy about having this issue lying around in recent versions.
@rafalbigaj which version of Tekton are you on?

**Comment by abayer** [comment]
Aaaah - the `Run` in the example has https://github.com/kubeflow/kfp-tekton/blob/master/tekton-catalog/pipeline-loops/examples/pipelinespec-with-run-arrary-value.yaml#L36, suggesting it was originally created as part of a full `Pipeline` and then copy-pasted into the example as a standalone. That explains how this happened!
