### ISSUE TITLE
PipelineRun in running state even if PipelineTask with retries is failed

### ISSUE THREAD

**Issue by vinamra28** [tektoncd/pipeline#4747]
# Expected Behavior

A PipelineRun with PipelineTask having `x` retries should fail if all the retries are exhausted and the failure is still there.

# Actual Behavior

PipelineRun is in running state even after all the retries are exhausted and eventually the TaskRun fails. Below is what controller says
```
{"level":"error","ts":"2022-04-11T10:08:40.782Z","logger":"tekton-pipelines-controller","caller":"controller/controller.go:566","msg":"Reconcile error","commit":"e46259e","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.pipelinerun.Reconciler","knative.dev/kind":"tekton.dev.PipelineRun","knative.dev/traceid":"b503258a-2212-4aa1-859c-cf287b497c04","knative.dev/key":"default/output-pipeline-run-ch8l6","duration":0.003710875,"error":"1 error occurred:\n\t* invalid list of done tasks; some tasks were indicated completed without ancestors being done: [then-check]\n\n","stacktrace":"github.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller.(*Impl).handleErr\n\tgithub.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller/controller.go:566\ngithub.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tgithub.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller/controller.go:543\ngithub.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller.(*Impl).RunContext.func3\n\tgithub.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller/controller.go:491"}
{"level":"info","ts":"2022-04-11T10:08:40.782Z","logger":"tekton-pipelines-controller.event-broadcaster","caller":"record/event.go:285","msg":"Event(v1.ObjectReference{Kind:\"PipelineRun\", Namespace:\"default\", Name:\"output-pipeline-run-ch8l6\", UID:\"ad87f70a-ffba-4ffa-a727-f5d52e6f7d24\", APIVersion:\"tekton.dev/v1beta1\", ResourceVersion:\"759950\", FieldPath:\"\"}): type: 'Warning' reason: 'InternalError' 1 error occurred:\n\t* invalid list of done tasks; some tasks were indicated completed without ancestors being done: [then-check]\n\n","commit":"e46259e"}
```

# Steps to Reproduce the Problem

1. Install the pipelines from current main branch on your cluster
2. Apply the following
    ```
     kubectl apply --filename https://gist.githubusercontent.com/vinamra28/54216bdc1901bb4ec964cb5ca9f0a562/raw/5d332e606200b542995b483b33449dadc8aa5513/failed-git-resource.yaml
     kubectl apply --filename https://raw.githubusercontent.com/tektoncd/cli/main/test/resources/pipeline.yaml
3. Start the Pipeline by running
    ```
     tkn p start output-pipeline -r=source-repo=skaffold-git-1 -p=FILEPATH=docs -p=FILENAME=README.md
    ```
After some time you'll see something like

```
$ tkn pr ls                                                                                                       
NAME                        STARTED       DURATION   STATUS
output-pipeline-run-ch8l6   2 hours ago   ---        Running

$ tkn tr ls
NAME                                          STARTED       DURATION     STATUS
output-pipeline-run-ch8l6-first-create-file   2 hours ago   10 seconds   Failed

$ tkn pr logs output-pipeline-run-ch8l6 -f
task first-create-file has failed: "step-git-source-workspace-bbwbm" exited with code 1 (image: "gcr.io/tekton-nightly/github.com/tektoncd/pipeline/cmd/git-init@sha256:d0d152572b1fd4aa5639f602c27201925fa099e57bdbc9f42c5d440c0eeaae8b"); for logs run: kubectl -n default logs output-pipeline-run-ch8l6-first-create-file-pod-retry3 -c step-git-source-workspace-bbwbm

[first-create-file : git-source-workspace-fm99p] {"level":"error","ts":1649671687.15101,"caller":"git/git.go:55","msg":"Error running git [fetch --recurse-submodules=yes --depth=1 origin --update-head-ok --force main]: exit status 128\nfatal: could not read Username for 'https://github.com': No such device or address\n","stacktrace":"github.com/tektoncd/pipeline/pkg/git.run\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:55\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:150\nmain.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:53\nruntime.main\n\truntime/proc.go:255"}
[first-create-file : git-source-workspace-fm99p] {"level":"fatal","ts":1649671687.1512659,"caller":"git-init/main.go:54","msg":"Error fetching git repository: failed to fetch [main]: exit status 128","stacktrace":"main.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:54\nruntime.main\n\truntime/proc.go:255"}

failed to get logs for task first-create-file : container step-git-source-workspace-fm99p has failed  : [{"key":"StartedAt","value":"2022-04-11T10:08:06.750Z","type":3}]

[first-create-file : git-source-workspace-lb7ww] {"level":"error","ts":1649671698.19204,"caller":"git/git.go:55","msg":"Error running git [fetch --recurse-submodules=yes --depth=1 origin --update-head-ok --force main]: exit status 128\nfatal: could not read Username for 'https://github.com': No such device or address\n","stacktrace":"github.com/tektoncd/pipeline/pkg/git.run\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:55\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:150\nmain.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:53\nruntime.main\n\truntime/proc.go:255"}
[first-create-file : git-source-workspace-lb7ww] {"level":"fatal","ts":1649671698.1922023,"caller":"git-init/main.go:54","msg":"Error fetching git repository: failed to fetch [main]: exit status 128","stacktrace":"main.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:54\nruntime.main\n\truntime/proc.go:255"}

failed to get logs for task first-create-file : container step-git-source-workspace-lb7ww has failed  : [{"key":"StartedAt","value":"2022-04-11T10:08:17.792Z","type":3}]
.......logs trimmed off
``` 

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:30:48Z", 
GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-03-06T21:39:59Z",
GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/arm64"}
```

- Tekton Pipeline version:

```
Client version: 0.23.1
Pipeline version: v20220411-e46259eb9d
```

For more info you can refer to the logs produced by tektoncd/cli integration tests [here](https://tekton-releases.appspot.com/build/tekton-prow/pr-logs/pull/tektoncd_cli/1554/pull-tekton-cli-integration-tests/1513442895972012032/) as they use the nightly build of pipelines.

**Comment by grigorev-lm** [comment]
I'm having the same issue.
- Tekton versions
```
Client version: 0.21.0
Pipeline version: v0.35.0
Triggers version: v0.19.1
Dashboard version: v0.25.0
```
- Kubernetes version
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.11", GitCommit:"0000000000000000000000000000000000000000", GitTreeState:"archive", BuildDate:"2022-04-07T10:27:33Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by afrittoli** [comment]
Fix was released in https://github.com/tektoncd/pipeline/releases/tag/v0.35.1
@vinamra28 could you confirm if we can close this?

**Comment by vinamra28** [comment]
thanks @afrittoli for reminding me on this. Yeah the issue is now fixed and can be closed.
/close
