### ISSUE TITLE
Failed to run tekton task

### ISSUE THREAD

**Issue by marco210** [tektoncd/pipeline#4767]
# Expected Behavior
Run task or Pipeline `git-clone`
# Actual Behavior
Can not run any task. Error:
`Error from server (InternalError): error when creating "hello-world.yaml": Internal error occurred: failed calling webhook "webhook.pipeline.tekton.dev": Post "https://tekton-pipelines-webhook.tekton-pipelines.svc:443/defaulting?timeout=10s": dial tcp 172.17.36.80:8443: connect: no route to host`
# Steps to Reproduce the Problem

1. kubectl apply -f https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.29.1/release.yaml
2. kubectl apply -f https://storage.googleapis.com/tekton-releases/dashboard/v0.25.0/tekton-dashboard-release.yaml
3. kubectl apply -f https://raw.githubusercontent.com/tektoncd/catalog/main/task/git-clone/0.5/git-clone.yaml
4.  kubectl apply -f hello-world.yaml

# Additional Info

- Kubernetes version: 1.19.15

  **Output of `kubectl version`:**

  ```
  Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.15", GitCommit:"58178e7f7aab455bc8de88d3bdd314b64141e7ee", GitTreeState:"clean", BuildDate:"2021-09-15T19:23:02Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.15", GitCommit:"58178e7f7aab455bc8de88d3bdd314b64141e7ee", GitTreeState:"clean", BuildDate:"2021-09-15T19:18:00Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

    Client version: 0.22.0
    Pipeline version: v0.29.1
    

- I check all  component in namespace `tekton-pipelines`: 
`kubectl -n tekton-pipelines logs tekton-pipelines-webhook-568b89d96f-ls8v7`
```
NAME                                                           REFERENCE                             TARGETS          MINPODS   MAXPODS   REPLICAS   AGE
horizontalpodautoscaler.autoscaling/tekton-pipelines-webhook   Deployment/tekton-pipelines-webhook   <unknown>/100%   1         5         1          95m
```

- And some error in logs pod `webhook`
```
E0418 09:07:42.932642       1 leaderelection.go:301] Failed to release lock: resource name may not be empty
I0418 09:07:42.932672       1 leaderelection.go:243] attempting to acquire leader lease tekton-pipelines/tekton-pipelines-webhook.webhookcertificates.00-of-01...
{"level":"info","ts":"2022-04-18T09:07:42.937Z","logger":"tekton-pipelines-webhook","caller":"leaderelection/context.go:156","msg":"\"tekton-pipelines-webhook-568b89d96f-ls8v7_5205ac93-08a7-4c8f-a8d6-96ee15eac753\" has stopped leading \"tekton-pipelines-webhook.conversionwebhook.00-of-01\"","commit":"a3bb451"}
E0418 09:07:42.937616       1 leaderelection.go:325] error retrieving resource lock tekton-pipelines/tekton-pipelines-webhook.conversionwebhook.00-of-01: Get "https://10.96.0.1:443/apis/coordination.k8s.io/v1/namespaces/tekton-pipelines/leases/tekton-pipelines-webhook.conversionwebhook.00-of-01": context deadline exceeded
I0418 09:07:42.937633       1 leaderelection.go:278] failed to renew lease tekton-pipelines/tekton-pipelines-webhook.conversionwebhook.00-of-01: timed out waiting for the condition
```

**Comment by wsszh** [comment]
@marco210 Hi, why did you closed this issue? I've got the similar problem.

**Comment by marco210** [comment]
> @marco210 Hi, why did you closed this issue? I've got the similar problem.

I cant run `git-clone` task from tekton hub, I rewrite a new task.
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone-test
spec:
  params:
  - name: repo
    type: string
    description: Git repository to be cloned
    default: https://github.com/
  workspaces: # define workspace
  - name: source
  steps: # define steps for a task
  - name: clone
    image: alpine/git
    workingDir: $(workspaces.source.path) # using workspace to store data.
    command:
      - /bin/sh
      - -c
      - git clone -v $(params.repo) .
 ```

**Comment by wsszh** [comment]
> > @marco210 Hi, why did you closed this issue? I've got the similar problem.
> 
> I cant run `git-clone` task from tekton hub, I rewrite a new task.
> 
> ```
> apiVersion: tekton.dev/v1beta1
> kind: Task
> metadata:
>   name: git-clone-test
> spec:
>   params:
>   - name: repo
>     type: string
>     description: Git repository to be cloned
>     default: https://github.com/
>   workspaces: # define workspace
>   - name: source
>   steps: # define steps for a task
>   - name: clone
>     image: alpine/git
>     workingDir: $(workspaces.source.path) # using workspace to store data.
>     command:
>       - /bin/sh
>       - -c
>       - git clone -v $(params.repo) .
> ```

I see. I have a little bit different problem. I can run my pipeline successfully in the most time, the error logs occur occasionally...
