### ISSUE TITLE
Some *useful* Pod status do not bubble up in TaskRun status

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/pipeline#4802]
Sligtly related to #4801, when a `Pod` doesn't fail but is in a "long-term" un-reconciliable state, such as `InvalidImageName`, the `TaskRun` controller ignore those and wait forever (aka timeout). 

This happens because it a fixable error from the `Pod` standpoint (you can mutate the `image` of a container in a `Pod`), and thus doesn't seem to be considered as a "terminal" error.

The `TaskRun` controller should pickup these kind of error (at least `InvalidImageName`, but most likely there might be a few other status that make sense) and fail with a clear message/reason based on it.

**Comment by yuzp1996** [comment]
Hi, I am interested in this issue. May I take this one?

If I need any help I will mention it here. Thank you!

**Comment by yuzp1996** [comment]
<img width="618" alt="image" src="https://user-images.githubusercontent.com/23007448/166193850-acac405c-a7d6-42a1-aac1-ba6b54f90066.png">

<img width="648" alt="image" src="https://user-images.githubusercontent.com/23007448/166193874-370605d3-6e1e-461d-8346-72cf069dd55e.png">

I think I have reproduced the error here. The pod is in the status of ImagePullBackOff while the related Taskrun is pending.

I think the expected result is that the taskrun should be failed with the message or reason of ImagePullBackOff.

If  I misunderstand something please tell me. Thank you!

**Comment by yuzp1996** [comment]
Hi, I check the code and find maybe we can do some improvement here. 
<img width="1462" alt="image" src="https://user-images.githubusercontent.com/23007448/166230714-839de56f-3d1f-48d4-85a9-da71d8e46968.png">

I think this is not a bug fix but a new feature. Maybe I need to provide a TEP to describe the goal that we want to achieve and the code change that I need to make.

I will be very happy if you can give me some advice. @vdemeester  Thanks!

**Comment by yuzp1996** [comment]
OK, thanks!  I will do it this week.

**Comment by yuzp1996** [comment]
This is all the [image Error](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/images/types.go#L26) I found in the k8s kubelet code. 

<img width="814" alt="image" src="https://user-images.githubusercontent.com/23007448/167320277-9fe3c4d7-d549-422c-9931-23fe4ab790c0.png">

**Comment by lbernick** [comment]
/close

fixed in #4846, thanks @yuzp1996!
