### ISSUE TITLE
Conversion webhook is constantly failing conversions to v1 types

### ISSUE THREAD

**Issue by mattmoor** [tektoncd/pipeline#4812]
# Expected Behavior

No failing conversion webhooks in the steady state.

# Actual Behavior

With a single task installed, I see about 1 QPS (judging from log lines with "Failed conversion") of failed conversion webhook attempts converting to a `desiredAPIVersion` of `tekton.dev/v1`:

```
# kubectl logs -n tekton-pipelines tekton-pipelines-webhook-76477c4df5-wbn76 | tail -1 | jq -r .error
conversion not supported for type [kind=Task group=tekton.dev version=v1]
```

# Steps to Reproduce the Problem

1. Install tekton at HEAD
2. Install any task
3. Check webhook logs (they should quickly fill with failed conversions)

# Additional Info

- Kubernetes version:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:31:32Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

HEAD

**Comment by mattmoor** [comment]
I believe the "offending" change is https://github.com/tektoncd/pipeline/pull/4702 (cc @lbernick @pritidesai @dibyom), which introduces the `v1` types in the config, BUT...  the types aren't stored or served, so these conversion webhook calls contradict my own mental model here, and we have very possibly uncovered an upstream bug 🤔 

Letting "Dr. Empirical" guide our understanding more...  As soon as I delete the "v1" stanza from `Task` the log lines stop.

While this is very likely an upstream bug, I'm not sure why these stanzas were added without `served: true` or the supporting Go types with conversion methods registered.  **Would it be worth reverting #4702 to reduce this unexpected load on the webhook until the new version is meaningfully added?**. 👍 👎 

cc @bobcatfish @vdemeester @imjasonh

**Comment by vdemeester** [comment]
I would definitely think it is worth. Adding v1 early is only worth if it doesn’t affect the normal behavior / performance.

**Comment by lbernick** [comment]
Opened #4817 to revert. However I think it would be good to fix this issue upstream somehow since we're using this doc [How to add new API versions to your CRD](https://docs.google.com/document/d/1omfO0O4yoUuM1Fk2E6wjfdVNK6XFSmxI3pb13xQ3rys/edit?resourcekey=0-vfKbXJHbVCVhmK98kNhssA) and it's a bit easier to be able to add in multiple steps like this.

**Comment by lbernick** [comment]
Matt, when you say the issue is upstream, do you think is this a knative issue or a k8s issue? How challenging would it be to fix?

**Comment by mattmoor** [comment]
@lbernick I think it is a Kubernetes issue.
