### ISSUE TITLE
ArrayorString UnmarshalJSON unsupported type value into string

### ISSUE THREAD

**Issue by Yongxuanzhang** [tektoncd/pipeline#4820]
### Feature request

Right now for ArrayorString's UnmarshalJSON, by default we will  Unmarshal as array. For structured results, users can write different types of data to results path,  cases like int, []int will not be supported by current UnmarshalJSON. Since in [tep75](https://github.com/tektoncd/community/blob/main/teps/0075-object-param-and-result-types.md#proposal) we decided to support string, []string and object type. I think for all other types we can unmarshal them to string.

Int Example:
https://github.com/tektoncd/pipeline/blob/main/examples/v1beta1/pipelineruns/ignore-step-error.yaml

Affected Code:
https://github.com/tektoncd/pipeline/blob/2777b19d6486e66e9e97f94b7078b0f129e0ee52/pkg/apis/pipeline/v1beta1/param_types.go#L114-L121

**Comment by ywluogg** [comment]
> Since in [tep75](https://github.com/tektoncd/community/blob/main/teps/0075-object-param-and-result-types.md#proposal) we decided to support string, []string and object type. I think for all other types we can unmarshal them to string.

Can you elaborate a bit more on this? I'm not sure if I understand.

**Comment by Yongxuanzhang** [comment]
already done
