### ISSUE TITLE
Tekton pipeline should support a task with an drop-down option

### ISSUE THREAD

**Issue by sagaraivale** [tektoncd/pipeline#4884]
### Feature request

There will be an option in tekton pipeline where users can select a particular task option based on a drop-down menu. 

### Use case

Suppose, my tekton pipeline consists of cascade connection of multiple builds and deploy tasks. Now, I need to build/deploy only one task from the pipeline, then there should be a drop-down task option. Where users can select one specific build app and next deploy that app to a specific env etc.

**Comment by imjasonh** [comment]
This sounds like a feature request for the [Tekton Dashboard](https://github.com/tektoncd/dashboard) project, or some other UI on top of the Tekton Pipelines API. Have you given the Dashboard a try, and does it meet your needs?

**Comment by sagaraivale** [comment]
Hey @imjasonh : Yes, this feature has to be on the [Tekton Dashboard ](https://github.com/tektoncd/dashboard)site. I will open up a feature requests there. Thanks!

Closing it.
