### ISSUE TITLE
creat taskrun failed if does not have name

### ISSUE THREAD

**Issue by gyliu513** [tektoncd/pipeline#4900]
# Expected Behavior

# Actual Behavior

# Steps to Reproduce the Problem

`tr.yaml` was get from https://github.com/tektoncd/pipeline/blob/release-v0.14.x/examples/v1beta1/taskruns/workspace.yaml

```console
root@gyliu-dev311:~/tekton# kc apply -f tr.yaml
persistentvolumeclaim/my-pvc created
configmap/my-configmap created
secret/my-secret created
error: error when retrieving current configuration of:
Resource: "tekton.dev/v1beta1, Resource=taskruns", GroupVersionKind: "tekton.dev/v1beta1, Kind=TaskRun"
Name: "", Namespace: "default"
Object: &{map["apiVersion":"tekton.dev/v1beta1" "kind":"TaskRun" "metadata":map["annotations":map["kubectl.kubernetes.io/last-applied-configuration":""] "generateName":"custom-volume-" "namespace":"default"] "spec":map["taskSpec":map["steps":[map["image":"ubuntu" "name":"write" "script":"echo $(workspaces.custom.volume) > $(workspaces.custom.path)/foo"] map["image":"ubuntu" "name":"read" "script":"cat $(workspaces.custom.path)/foo | grep $(workspaces.custom.volume)"] map["image":"ubuntu" "name":"write2" "script":"echo $(workspaces.custom2.path) > $(workspaces.custom2.path)/foo"] map["image":"ubuntu" "name":"read2" "script":"cat $(workspaces.custom2.path)/foo | grep $(workspaces.custom2.path)"] map["image":"ubuntu" "name":"write3" "script":"echo $(workspaces.custom3.path) > $(workspaces.custom3.path)/foo"] map["image":"ubuntu" "name":"read3" "script":"cat $(workspaces.custom3.path)/foo | grep $(workspaces.custom3.path)"] map["image":"ubuntu" "name":"readconfigmap" "script":"cat $(workspaces.custom4.path)/my-message.txt | grep \"hello world\""] map["image":"ubuntu" "name":"readsecret" "script":"#!/usr/bin/env bash\nset -xe\ncat $(workspaces.custom5.path)/username | grep \"user\"\ncat $(workspaces.custom5.path)/message | grep \"hello secret\"\n"]] "workspaces":[map["name":"custom"] map["mountPath":"/foo/bar/baz" "name":"custom2"] map["name":"custom3"] map["mountPath":"/baz/bar/quux" "name":"custom4"] map["mountPath":"/my/secret/volume" "name":"custom5"]]] "workspaces":[map["name":"custom" "persistentVolumeClaim":map["claimName":"my-pvc"] "subPath":"my-subdir"] map["name":"custom2" "persistentVolumeClaim":map["claimName":"my-pvc"]] map["emptyDir":map[] "name":"custom3" "subPath":"testing"] map["configMap":map["items":[map["key":"message" "path":"my-message.txt"]] "name":"my-configmap"] "name":"custom4"] map["name":"custom5" "secret":map["secretName":"my-secret"]]]]]}
from server for: "tr.yaml": resource name may not be empty
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

**Comment by imjasonh** [comment]
In this case, you have to `kubectl create -f tr.yaml` (`create`, not `apply`), because the TaskRun YAML includes `generateName: custom-volume-`. This will create a TaskRun resource with a generated name with the given prefix, like `custom-volume-xybdy`.

**Comment by gyliu513** [comment]
Thanks @imjasonh , yes, `create` works, but `delete` failed due to no name, so for `delete`, I need to delete the exact taskrun, but cannot delete via the yaml file, right? If so, I think we need to highlight this in document, thoughts?

```console
root@gyliu-dev311:~/tekton# kc delete -f tr.yaml
persistentvolumeclaim "my-pvc" deleted
configmap "my-configmap" deleted
secret "my-secret" deleted
error: error when deleting "tr.yaml": resource name may not be empty
```

**Comment by imjasonh** [comment]
When you create a Kubernetes resource with a generated name, you have to delete it by that name as well. This means you can't use `kubectl delete -f resource.yaml`, since the YAML file doesn't include the generated name.

This might be something worth calling out in the docs, but to be honest I'm not sure how many users use `kubectl` to delete TaskRuns directly, as opposed to using `tkn` or waiting for PipelineRuns to complete and using the pruning features of the Tekton Operator.

If you find a spot in the docs you think it would be helpful to call this behavior out, feel free to send a PR and @ me so I can review.

**Comment by afrittoli** [comment]
Based on @imjasonh response, I will close this one. Feel free to re-open if required.
