### ISSUE TITLE
[Breaking Change] Change TaskRunResult.Value and PipelineRunResult.Value from string to ArrayOrString

### ISSUE THREAD

**Issue by Yongxuanzhang** [tektoncd/pipeline#4907]
This PR(https://github.com/tektoncd/pipeline/pull/4818) and following PR(will update this issue once opened) will change TaskRunResult.Value and PipelineRunResult.Value from string to ArrayOrString and this will be breaking changes for cli as pointed out by @pritidesai.

Background:
This is a requested feature in [TEP0076](https://github.com/tektoncd/community/blob/main/teps/0076-array-result-types.md)

Please be aware of this change. 🙏  

/cc @tektoncd/cli-maintainers

**Comment by abayer** [comment]
Is this done? Can this be closed?

**Comment by Yongxuanzhang** [comment]
> Is this done? Can this be closed?

yeah, this is done.
