### ISSUE TITLE
Regression: PipelineTaskRunSpec.Metadata incompatible with older webhooks

### ISSUE THREAD

**Issue by wlynch** [tektoncd/pipeline#4913]
# Expected Behavior

PipelineTaskRunSpec should be safely passed to older webhooks.

# Actual Behavior

```
    serviceaccount_test.go:163: Failed to create PipelineRun `pipeline-run-with-service-accounts-dsofxybx`: admission webhook "defaulting.webhook.pipeline.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "metadata"
    panic.go:661: ############################################
    panic.go:661: ### Dumping objects from arendelle-7ntt4 ###
    panic.go:661: ############################################
```

# Steps to Reproduce the Problem

1. Install Tekton < https://github.com/tektoncd/pipeline/pull/4834
2. Create PipelineRun using client >= https://github.com/tektoncd/pipeline/pull/4834

# Additional Info

We think we've found the root cause (shout out to @n3wscott for finding it):

https://github.com/tektoncd/pipeline/blob/b19a9abdb81ac0d7608a0457348ccb24afa65316/pkg/apis/pipeline/v1beta1/pipelinerun_types.go#L605

should be:

```go
Metadata *PipelineTaskMetadata `json:"metadata,omitempty"` 
```

Will send a PR!

cc @austinzhao-go in case you have any thoughts

/kind bug

**Comment by austinzhao-go** [comment]
thanks this catch! 

applied this update in another field addition PR for TEP-0104 
https://github.com/tektoncd/pipeline/pull/4877
