### ISSUE TITLE
exit status 128\nerror: RPC failed; curl 56 OpenSSL SSL_read: No error information\nfatal: the remote end hung up unexpectedly

### ISSUE THREAD

**Issue by xauthulei** [tektoncd/pipeline#4979]
The details :
 CHECKOUT_DIR=/workspace/output/mesh-for-data
+ '[[' true '==' true ]]
+ cleandir
+ '[[' -d /workspace/output/mesh-for-data ]]
+ test -z
+ test -z
+ test -z
+ /ko-app/git-init -url ${myrepo} -refspec  -path /workspace/output/mesh-for-data '-sslVerify=true' '-submodules=true' -depth 1
{"level":"error","ts":1655271727.709314,"caller":"git/git.go:54","msg":"Error running git [fetch --recurse-submodules=yes --depth=1 origin --update-head-ok --force master-internal]: exit status 128\nerror: RPC failed; curl 56 OpenSSL SSL_read: No error information\nfatal: the remote end hung up unexpectedly\nfatal: early EOF\nfatal: index-pack failed\n","stacktrace":"github.com/tektoncd/pipeline/pkg/git.run\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:54\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:149\nmain.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:53\nruntime.main\n\truntime/proc.go:204"}
{"level":"fatal","ts":1655271727.7094462,"caller":"git-init/main.go:54","msg":"Error fetching git repository: failed to fetch [master-internal]: exit status 128","stacktrace":"main.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:54\nruntime.main\n\truntime/proc.go:204"}

**Comment by afrittoli** [comment]
@xauthulei is this issue still reproducible? If so, could you please provide some details about your setup and how to recreate the issue?
