### ISSUE TITLE
Jenkins Interactive User Input but for Tekton

### ISSUE THREAD

**Issue by nicodmt** [tektoncd/pipeline#5041]
Hi,

Me and my team are building two tkn pipelines. 
One is for creating an image of the build and the other to change the deployment config depending on which environment we want to deploy the image created to (Production, Test, and sub-test env.).

We are running in OpenShift v.3 with Jenkins where the pipelines wait for a User Input and are now working towards OpenShift v.4 with Tekton but I've not been able to recreate the "Waiting for UserInput" part.

We are wishing to get some sort of dropdown menu (or even just a Yes/No box) with the name of our environments to add as a param. Code example below:

params:
  - name: environment
     value: [Value1, Value2, n]
...
tasks:
  - name: choose_environment
    when:
      - input: "$(params.environment[*])"
        operator: in

How can we go ahead to take a UserInput into our tkn pipeline?

Not an issue, more of a feature proposition.

**Comment by nicodmt** [comment]
Not an issue, more of a feature proposition.

**Comment by toxsick** [comment]
Same question here, how can something like this achieved with tekton:

![KN macOS 10 14 2022-08-25 20-34-36](https://user-images.githubusercontent.com/951466/186742542-7bb27c6e-f16b-4ae9-b131-1b7af3e567a6.png)

In the jenkins world this is an **interactor**

**Comment by vdemeester** [comment]
Hey @toxsick @nicodmt.
As of today, this is not possible with tekton components alone. To achieve this behavior you might need to use a CustomTask (like [`automatiko-io/automatiko-approval-task`](https://github.com/automatiko-io/automatiko-approval-task)) or a product / tooling that wraps Tekton (jenkins-x maybe, …).
@nicodmt Related to "OpenShift", we have an [Epic](https://issues.redhat.com/browse/SRVKP-1711) around this that we are working on 👼🏼.

A side note, as of today, as stated on the [website](https://tekton.dev), "Tekton is a powerful and flexible open-source framework for creating CI/CD systems", where Jenkins is a CI/CD systems. Today, Tekton is very generic and might not be able to fully compare with a complete CI/CD systems. That said, as time passes, more components and tools will come to make this gap smaller.

Cheers

**Comment by toxsick** [comment]
Hey @vdemeester, thanks for clarifying. I can imagine that this is not an easy thing to implement. For me this is preventing me to migrate my deployment pipelines from jenkins (Openshift v3) to tekton (Openshift v4) and I will go with jenkins for now.

Thanks and keep up the exciting work!
