### ISSUE TITLE
Authenticating a private git repository 

### ISSUE THREAD

**Issue by akhil97** [tektoncd/pipeline#5052]
I am trying to use tekton triggers for a private git repository instead of forking the mentioned repository (https://github.com/iancoffey/ulmaceae) in the example. I have already tried steps mentioned in these links:-
https://github.com/tektoncd/pipeline/blob/main/docs/auth.md#ssh-authentication-git
https://github.com/tektoncd/pipeline/blob/release-v0.35.x/examples/v1beta1/taskruns/authenticating-git-commands.yaml
I keep getting an error saying error fetching git repository. Below is the screenshot
![image](https://user-images.githubusercontent.com/19953362/173647751-97f7801e-3d10-44c8-939d-425c2d6aff66.png)
I am using GKE (Google Kubernetes Engine ) based cluster running on google cloud and a GCS (Google Cloud Source) repository. Are there any different steps to be followed apart from the mentioned links please do let me know

**Comment by pritidesai** [comment]
Pipelines WG - We might want to document the settings and configurations needed for GCS.

**Comment by pritidesai** [comment]
@akhil97 please provide further troubleshooting if you have done so beyond Tekton Pipelines 0.35. Thanks!

**Comment by dibyom** [comment]
from the error message it seems like this has more to do with some kind of network restrictions - source.developers.google.com - Address not available
