### ISSUE TITLE
[TEP 0075, 0076] More ways of referencing params and results

### ISSUE THREAD

**Issue by ywluogg** [tektoncd/pipeline#5056]
### Feature request

There are certain ways of referencing params and results, either as a whole or accessing keys, are implemented and tracked in #4723, but there are other ways that should be considered for accessing params and results.

Thanks for @chuangw6 and @Yongxuanzhang 's summary, the following are supported:
- String Types
  - $(tasks.myTask.results.myStringResult)
  - $(tasks.myTask.results[‘my.String.Result’])
  - $(tasks.myTask.results["my.String.Result"])
- Array Types
  - $(tasks.myTask.results.myArrayResult[*])
  - $(tasks.myTask.results.myArrayResult[i])
- Object Types
  - $(tasks.myTask.results.myObjectResult[*])
  - $(tasks.myTask.results.myObjectResult.key1)

Below are few other ways are listed below that are not supported but should be considerred:
- Array Types
  - $(tasks.myTask.results[‘myArrayResult’][*])
  - $(tasks.myTask.results[“myArrayResult”][*])
  - $(tasks.myTask.results[‘myArrayResult’][i])
  - $(tasks.myTask.results[“myArrayResult”][i])
- Object Types
  - $(tasks.myTask.results[“my.Object.Result”][*])
  - $(tasks.myTask.results[“my.Object.Result”].key1)
  - $(tasks.myTask.results[“my.Object.Result”][“my.key1”])

### Use case

Stated above.

**Comment by chuangw6** [comment]
> $(tasks.myTask.results[“my.Object.Result”].key1)
> $(tasks.myTask.results[“my.Object.Result”][“my.key1”])

Object param/result name and its keys shouldn't contain dots. see more details [here](https://github.com/tektoncd/community/pull/711/files)
