### ISSUE TITLE
Make validateObjectKeys() Public for Tekton Chains to Use

### ISSUE THREAD

**Issue by ywluogg** [tektoncd/pipeline#5072]
### Feature request

[validateObjectKeys](https://github.com/tektoncd/pipeline/blob/eca056e14a3777a865ae2b8c7e6c4e5d34886f40/pkg/apis/pipeline/v1beta1/task_validation.go#L409) is validating properties against a ArrayOrSting, which is needed in Tekton Chains. To avoid code duplication, this worths becoming a public function

### Use case

See above

**Comment by ywluogg** [comment]
Hi Chuang, I'm wondering if you have time to make the function public? Thanks

**Comment by chuangw6** [comment]
sg! done #5073 !
