### ISSUE TITLE
Support for batch/merging commits

### ISSUE THREAD

**Issue by pmuir** [tektoncd/pipeline#508]
## Expected behaviour

We'd like to be able to support "batch testing", which is a Prow feature (see https://github.com/kubernetes/test-infra/tree/master/prow#functions-and-features). It's not well documented in Prow how batch testing works, but I'll try to explain my understanding of it:

When a PR arrives, it is tested using something like `/test this` or perhaps automatically. Once it is passing and has a `/approve` or a `/lgtm` it then enters the merge pool (you'll see this status in tide quite a lot). However tide (the part of Prow responsible for doing merges) won't actually do the merge until it has a clean run against `HEAD` of the branch it is merging too. It will automatically restest your PRs for you against `HEAD`. This can obviously get very slow if you have a busy repo with long test runs. In order to make this process efficient, Tide will attempt to batch up your PRs into a single merge by taking the `HEAD` of the branch you want to merge to, and adding all the PRs to it.

This is not currently supported in either build-pipeline or knative-build which means that Prow just picks the first PR in the batch and tests that against `HEAD` but claims it has tested all of the PRs.

## Actual behaviour

We can only specify commit/revisions one at a time in [our git resource](https://github.com/knative/build-pipeline/blob/master/docs/resources.md#git-resource).

-----

@pmuir 's original description (above added by @bobcatfish from @pmuir 's comments below)

See #506 

This is a feature supported by Prow. Multiple
branch:commits pairs can be specified in the env
var `PULL_REFS`. The first pair is the
branch:commit base, any subsequent pairs are
commits to merge into the first pair. Prow uses
this to batch up multiple commits for testing, and
also to test PRs which are opened against older
revisions of a branch against the `HEAD` of a
branch.

This PR parses the `PULL_REFS` env var, and then
uses the git CLI to fetch any refs and then merge
them in.

Test coverage is about 80% - the success paths are
covered, error paths are not.

**Comment by pmuir** [comment]
Initial questions and comments from @bobcatfish and @pmuir copied from PR:

> Hey there @pmuir !! Thanks for the contribution, this is very exciting :D
> 
> Before we merge this, can you explain a bit more about your use case and what you would want to do with this functionality?

One of the features of prow is batch testing (see https://github.com/kubernetes/test-infra/tree/master/prow#functions-and-features). It's not well documented in Prow how batch testing works, but I'll try to explain my understanding of it:

When a PR arrives, it is tested using something like `/test this` or perhaps automatically. Once it is passing and has a `/approve` or a `/lgtm` it then enters the merge pool (you'll see this status in tide quite a lot). However tide (the part of Prow responsible for doing merges) won't actually do the merge until it has a clean run against `HEAD` of the branch it is merging too. It will automatically restest your PRs for you against `HEAD`. This can obviously get very slow if you have a busy repo with long test runs. In order to make this process efficient, Tide will attempt to batch up your PRs into a single merge by taking the `HEAD` of the branch you want to merge to, and adding all the PRs to it.

This is not currently supported in either build-pipeline or knative-build which means that Prow just picks the first PR in the batch and tests that against `HEAD` but claims it has tested all of the PRs. 

This PR adds support for that.


> It's not clear to me how this `PULL_REFS` approach fits into our [git resource model](https://github.com/knative/build-pipeline/blob/master/docs/resources.md#git-resource), which is what we use to control what source code is provided to Tasks. 

Doesn't seem to fit very well to me at all. That model looks like it won't support batching (or indeed merging a PR into `HEAD` for testing, so I guess the config format would need revisiting if we want to handle these prow features via that method. As an example of some potential config we would need (this is really just a sketch, not a suggestion!):

```spec:
  type: git
  params:
    - name: url
      value: https://github.com/wizzbangcorp/wizzbang.git
    - name: revisions
    - values:
      - refs/pull/52525/head
      - refs/pull/52526/head
      - abcdef124
    - name: baseBranch
      value: master
    - name: baseSha
      value: abcdef123
```

> Some other ways to approach this:
> 
> * A pipelinerun + corresponding resource for each pull request?

That doesn't address the Prow feature - as it's

> * A git resource type that allows multiple commits to be specified

Yeah, as sketched above, that would work.

In this case we would need the prow build-pipeline controller (which I think @rawlingsj is working on?) to take the code that parses `PULL_REFS` and have it create the relevant git resource.

Though note you also need to be able specify the branch and revision to merge the commits from the PR into. This is very important as if a PR is against a 20 day old version of master, and new tests have been added to master since then (which the PR happens to break) a clean run of the PR is NOT sufficient to merge it.

> (What does it actually mean to "batch commits"?)

Hopefully explained above. Let me know if not clear :-D

> 
> Also it would probably help in reviewing to include [some docs](https://github.com/knative/build-pipeline/tree/master/docs) in the PR so reviewers can get a sense of how this would be used.

Will do, though let's address the configuration format 

> 
> (We'll probably want to discuss this feature and the implications a bit before we merge anythings, so you might also find it easier to open an issue first we were can have some discussion before merging this.)

**Comment by bobcatfish** [comment]
( @pmuir I moved some of your above comment into the initial description, just to make it more clear at a glance what this is about)

Thanks for all the details and links @pmuir , I really appreciate it and I can see now why you need this functionality!!!

(sorry for the delayed response also!)

So as discussed in #506, I think we probably don't want to go ahead with that exact solution, but the Resource based solution sounds pretty decent.

Or one other idea, which you may not like as much, would be to create a Task that knows how to merge multiple branches into a git repo. So something like:

```
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: batch-git-task
spec:
  inputs:
    resources:
    - name: repo # users/automation could specify the "base" to merge into using this resource
      type: git
    params:
      - name: git commits # we don't have a list type yet (#207) so this would be a string that contains multiple commits probably
  outputs:
    resources:
     - name: repo # making this an output means that downstream Tasks (e.g. tests) can take this as an input and will get the version that has all the merged branches in it
       type: git
  steps:
  - name: merge
    image: <some kind of image with git installed>
    args: <commands here to loop and merge each of the param git branches>
```

But also a custom resource type would be cool too :)

**Comment by bobcatfish** [comment]
( @pmuir I assume we can consider this one assigned to you? do you mind if we close #506 for now? )

**Comment by pmuir** [comment]
Yep, assign to me :-)

**Comment by pmuir** [comment]
Just to set expectations - it will take me a couple of weeks to get to this one - maybe late March.

**Comment by bobcatfish** [comment]
Sounds good, thanks for the info @pmuir :D

**Comment by afrittoli** [comment]
In my opinion the batching of PRs should be something implemented on prow/tide side. It can be implemented or wrapped in a Tekton Task in the catalog, but I don't think the code for the merge should live in the tekton/pipeline repo.

All of our input/output resources transfer the state/payload of a resource from outside into a Task or the other way around, but they usually don't do any modification to the resource itself, that is responsibility of the Task. Having a resource that collates multiple PRs together would be an exception to this model - I'm interested to get more opinions on this @bobcatfish @dlorenc @vdemeester .

If I understood the issue correctly we won't be able to use the prow->tekton functionality until this is solved, because we wouldn't be testing really what we need to test. Given the relative low volume of patches on Tekton we could consider a strict serial merge pipeline (i.e. on patch at the time only) until this implemented, does this option exist in tide?

**Comment by vdemeester** [comment]
> In my opinion the batching of PRs should be something implemented on prow/tide side. It can be implemented or wrapped in a Tekton Task in the catalog, but I don't think the code for the merge should live in the tekton/pipeline repo.
> 
> All of our input/output resources transfer the state/payload of a resource from outside into a Task or the other way around, but they usually don't do any modification to the resource itself, that is responsibility of the Task. Having a resource that collates multiple PRs together would be an exception to this model - I'm interested to get more opinions on this @bobcatfish @dlorenc @vdemeester .
> 
> If I understood the issue correctly we won't be able to use the prow->tekton functionality until this is solved, because we wouldn't be testing really what we need to test. Given the relative low volume of patches on Tekton we could consider a strict serial merge pipeline (i.e. on patch at the time only) until this implemented, does this option exist in tide?

I do agree :angel: This shouldn't be in the "core" of tekton but in another component (using pipeline and triggers and … ?), either by hooking it up to `tide`, or having our own component.

**Comment by ad22** [comment]
I've been evaluating Tekton and was looking for a discussion and a solution around batched gating of changes.

For context, we use Zuul + Gerrit with a trunk based development model. Zuul automatically either merges/cherry-picks the change under test on its base or target branch, and in addition provides for an option to enable batched speculative execution of changes. You can read more about the concepts here. https://zuul-ci.org/docs/zuul/discussion/gating.html. 

A full fledged change orchestrator such as zuul will be better off as a separate resource definition, but one thing that this PR could borrow from zuul is the ability to provide user selectable change merge strategy onto the base branch, which should be fairly simple to implement and provides for more use cases for tools above tekton.
git merge -s recursive, git merge -s resolve, cherry-pick and squash-merge

**Comment by sbwsg** [comment]
Now that https://github.com/tektoncd/catalog/pull/273 is implemented I think we can close this issue.  I encourage anyone requiring this feature to exercise the new catalog entry and report problems with it there.  Also, please feel free to reopen this issue if there's more work to be done here.
