### ISSUE TITLE
Add digest to object status when referencing a task bundle

### ISSUE THREAD

**Issue by bcaton85** [tektoncd/pipeline#5091]
### Feature request

Currently a task can be referenced through a bundle in a pipelinerun/taskrun.[1] This can either use a tag or digest of an image. When the task bundle reference is a tag and added to the status fields of the taskrun and pipelinerun it should also store the exact digest of the bundle used. This removes ambiguity on which version of the task bundle was ran in the pipeline.

[1] https://tekton.dev/docs/pipelines/pipelines/#tekton-bundles 

### Use case

The use case is related to Tekton Chains proposal TEP-84.[1] Recording which specific version of a task bundle was used allows for concretely verifying the source of that bundle. Relying on only the tag is insufficient since tags can be updated. 

[1] https://github.com/tektoncd/community/blob/main/teps/0084-endtoend-provenance-collection.md

**Comment by vdemeester** [comment]
/cc @imjasonh 
I am 💯% fo rthis 👼🏼

**Comment by imjasonh** [comment]
+1, we should also consider adding an admission controller warning when someone references a bundle by tag: https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#response

**Comment by vdemeester** [comment]
Note that with https://github.com/tektoncd/pipeline/issues/3661, we need to make sure this happens on the bundle resolver side instead of here.

**Comment by lcarva** [comment]
/remove-lifecycle stale

This is an important feature that increases reproducibility when using Tekton Pipelines.

**Comment by vdemeester** [comment]
Note on this: we should look into this in the "lens" of the bundle resolver. cc @abayer to know if it already does that or not 🙃
