### ISSUE TITLE
TaskRun results in 'Defaulted container "step-echo" out of: step-echo, place-scripts (init), place-tools (init)'

### ISSUE THREAD

**Issue by 95rade** [tektoncd/pipeline#5092]
# Expected Behavior
I am trying to deploy a RobotFramework task from tekton HUB:
https://hub.tekton.dev/tekton/task/robot-framework

Running the task as:
```
kubectl apply -f robot-task.yaml
kubectl apply -f robot-task-run.yaml
```
kubectl logs returns:
```
kubectl logs --selector=tekton.dev/taskRun=robot-task-run
Defaulted container "step-robot-tests" out of: step-robot-tests, place-scripts (init), working-dir-initializer (init), place-tools (init)
```
Deleted all the crud from yaml files and tried bare bones, no luck. I am guessing the issue is with the container, so I tried 'alpine' 'docker.io/python:3.10.5', 'python', I always get that 'Defaulted container' error. Tried both work OCP cluster as well as local minikube. 

The pod status is 'Pending':
```
NAME                       READY   STATUS      RESTARTS   AGE
hello-task-run-pod-7xwmw   0/1     Completed   0          15m
robot-task-run-pod-snp7t   0/1     Pending     0          4m9s
```
This goes on for 1 hr and it Times Out.

# Actual Behavior

# Steps to Reproduce the Problem

1. Install the task using the above URL: kubectl apply -f <URL>
2. Run the task: kubectl apply -f <run-file.yaml>
3. Check the taskrun log and the pod status:  eg  
```
kubectl logs --selector=tekton.dev/taskRun=robot-task-run
kubectl get pods
```
# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:14:10Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**
```
Client version: 0.24.0
Pipeline version: v0.24.3
```

**Comment by lbernick** [comment]
hi @95rade thanks for filing! I think the message `Defaulted container "step-robot-tests" out of: step-robot-tests, place-scripts (init), working-dir-initializer (init), place-tools (init)` that you are seeing is not really an error-- this just means that you asked kubernetes for the logs in some pod but didn't specify which container in that pod you wanted logs from, so it chose one for you. (In this case, the container running a step instead of the init containers injected by tekton.)

It looks like your pod hasn't produced any logs because it is still running. Is this something you expect to take a long time before producing output? If so, you may want to just increase the timeout. If not, you might want to take a look at the taskrun's status to see what's going on. the Tekton CLI might make that a bit easier!

**Comment by 95rade** [comment]
Hi @lbernick and thanks for the comment. The task in question has only one step so there should only be one container running in that pod. The pod is stuck in 'Pending' state and the timeout is set to 1hr which is enough. The expectation is that when this task runs it should scan rf-test directory for any .robot files and when it finds them execute them. Then stop. This is not happening. If you could please take a look at the task (link at the top) and help me figure out whats broken with it I would be grateful. I am a tekton newbie coming up to speed.  thanks a lot

**Comment by AlanGreene** [comment]
The container `step-robot-tests` is the container for the step defined in your Task. The other 3 containers are part of the Tekton machinery and are automatically added, this is expected. As Lee stated above, the 'Defaulted container' message is not an error, it is normal behaviour when you request logs from a Pod with multiple containers without specifying the container name.

If you inspect the pending pod you should find more information to explain why it is pending, for example `kubectl describe pod robot-task-run-pod-snp7t` and check the events field. The Kubernetes documentation contains some useful information for debugging pods that are stuck in pending state, including links to additional resources that may be relevant: https://kubernetes.io/docs/tasks/debug/debug-application/debug-pods/#my-pod-stays-pending

**Comment by 95rade** [comment]
As commented, this is _not_ a bug, but just the way tekton reports its output.
