### ISSUE TITLE
Encorporate k8s documentation style guidelines

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#51]
## Expected Behavior
The k8s project has a [solid set of documentation guidelines](https://kubernetes.io/docs/contribute/style/style-guide/). It would be great if the docs in this project followed them. This means two things:

1. We should review our existing docs (specifically READMEs) and fix any issues
2. We should add a link to these standards to our CONTRIBUTING.md

If possible we should consider adding some markdown linting as part of our 

## Actual Behavior
We did not follow any kind of standard when we wrote these :S

**Comment by zhyuri** [comment]
Hi, is there anyone working on this issue right now?
If not, I'm happy to do some document work.

**Comment by vdemeester** [comment]
@zhyuri I started a branch on that (https://github.com/vdemeester/build-pipeline/tree/51-take-1) but only started on `Concept.md`, and the more the better on docs, we may want to divide work in several pieces so different person can work on them in parallel :angel:

**Comment by zhyuri** [comment]
@vdemeester Cool! I just checked out a branch for this issue: https://github.com/zhyuri/build-pipeline/tree/issue-51 but haven't done any work yet.

Maybe we can update&check this issue before start working on new document and see if it has been worked on?

**Comment by bobcatfish** [comment]
I think we can consider this done for now.
