### ISSUE TITLE
Sporadic failures with `etcdserver: request timed out` on Kind Prow tests

### ISSUE THREAD

**Issue by abayer** [tektoncd/pipeline#5118]
An example is https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/5077/pull-tekton-pipeline-kind-alpha-yaml-tests/1546485026143604736 (link will quite possibly go away).

https://github.com/kubernetes-sigs/kind/issues/717 is a similar issue, which was resolved by adding a daemonset to their Prow cluster much like the one we added in https://github.com/tektoncd/plumbing/pull/1129. https://github.com/kubernetes-sigs/kind/issues/1922 seems relevant as well - which suggests the issue may be disk I/O-related. The person who opened that issue ended up moving kubevirt's Kind-in-Prow tooling to use in-memory etcd at https://github.com/kubevirt/kubevirtci/pull/478/commits/393d0cdec256196b26ccd84e929ab5a3ea671e9c, which could be helpful.

In general, I'm wondering if there are optimizations we can make to the local, non-persistent disks on our GKE nodes to improve IO...

/kind flake

**Comment by alequint** [comment]
Just want to register here that I have same type of problems. In my case, in the middle of a pipeline execution, while tasks are still running, suddenly the PipelineRun status changes to "Failed" with the following message:

```
Pipeline mas-fvtairgap-pipelines/mas-fvt-pipeline can't be Run; it contains Tasks that don't exist: Couldn't retrieve Task "mas-devops-ibm-catalogs": etcdserver: request timed out
```

None tasks failed and note that the task message above is complaining about it does exist (and have already been executed btw); the last part of the error message seems where the problem really is: `etcdserver: request timed out`. Wondering if it is lack of resource that make etcdserver not accessible, maybe local storage issues, not sure.

**Comment by l-qing** [comment]
@Yongxuanzhang I often encounter this error, and I find that the latest code in the main branch still has this issue.
I've noticed that you've recently made some changes to the code here as well.

https://github.com/tektoncd/pipeline/blob/6cc22545060a5480a2755f8bc3c64126eed62163/pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go#L645-L649

https://github.com/tektoncd/pipeline/blob/6cc22545060a5480a2755f8bc3c64126eed62163/pkg/reconciler/pipelinerun/pipelinerun.go#L364-L374

https://github.com/tektoncd/pipeline/blob/6cc22545060a5480a2755f8bc3c64126eed62163/pkg/reconciler/taskrun/resources/taskref.go#L283-L286

https://github.com/tektoncd/pipeline/blob/6cc22545060a5480a2755f8bc3c64126eed62163/pkg/reconciler/taskrun/resources/taskref.go#L40-L44

Can we tolerate this temporary exception of "request timed out" within a certain time frame, allowing the error to occur?

**Comment by Yongxuanzhang** [comment]
> Can we tolerate this temporary exception of "request timed out" within a certain time frame, allowing the error to occur

🤔 I don't think I have changed anything related? Did you mean that we don't return this error for a time frame?

**Comment by l-qing** [comment]
> 🤔 I don't think I have changed anything related? 

Yes, I'm aware that this part of the code has been like this since version 0.41.0; it wasn't changed recently by you.
I thought of your comments in other issues, I mentioned you here. 😆
https://github.com/tektoncd/pipeline/issues/7392#issuecomment-1850438622

> Did you mean that we don't return this error for a time frame?

Yes, We need to be able to tolerate this mistake for a period of time, but we cannot tolerate it indefinitely.

**Comment by Yongxuanzhang** [comment]
> > 🤔 I don't think I have changed anything related?
> 
> Yes, I'm aware that this part of the code has been like this since version 0.41.0; it wasn't changed recently by you. I thought of your comments in other issues, I mentioned you here. 😆 [#7392 (comment)](https://github.com/tektoncd/pipeline/issues/7392#issuecomment-1850438622)
> 
> > Did you mean that we don't return this error for a time frame?
> 
> Yes, We need to be able to tolerate this mistake for a period of time, but we cannot tolerate it indefinitely.

Do you want to reopen this issue or open a new one?

**Comment by l-qing** [comment]
> Do you want to reopen this issue or open a new one?

This issue already contains a lot of context information, how about we just reopen it?

If it's just ignoring the timeout error, I know how to deal with it.
But if there needs to be a time limit, I'm not sure if there is any referable code in the current framework?
