### ISSUE TITLE
Custom Task controller for testing

### ISSUE THREAD

**Issue by lbernick** [tektoncd/pipeline#5120]
In order to write better integration/e2e tests for custom Tasks, it would be useful to have a controller that watches for Runs of some kind we just use for testing, and install this controller when running e2e tests. This controller could do any of:
- wait indefinitely
- set the status to "succeeded"
- set the status to match some boolean succeeded/failed set in the spec.

This controller shouldn't be packaged with Tekton releases.

**Comment by jerop** [comment]
planning to reuse https://github.com/tektoncd/experimental/tree/main/wait-task for this

**Comment by XinruZhang** [comment]
Thanks for writing the issue Lee! I may need some extra clarifications:

> set the status to match some boolean succeeded/failed set in the spec.

Do you mean we define some boolean fields in the `spec` and set those fields in `status` as what are set in the `spec`. 

> This controller shouldn't be packaged with Tekton releases.

Will codes under `test/` be packaged with Tekton release?

**Comment by XinruZhang** [comment]
Hi @lbernick what do we need for the `wait infinitely`?  Is the current `wait-task` controller enough?

**Comment by lbernick** [comment]
This was just a suggestion of what we could write the controller to do-- I was just brainstorming simple behaviors that are easy to understand for testing. It really depends on what tests we want to add and what controller behavior would be most helpful for those tests. It seems to me like the wait task has given us what we need? So I'm going to close this as completed in #5332.

**Comment by XinruZhang** [comment]
Thanks for the quick reply! I guess we still need the second and third to simulate the behavior of a the controller with CRD defined, Let's keep this issue open and mark it closed after finishing tasks in https://github.com/tektoncd/pipeline/issues/5156#issuecomment-1221042052. wdyt?
