### ISSUE TITLE
Behavior between git-init v0.29.0 and latest (v0.37.2) breaks non-root clones

### ISSUE THREAD

**Issue by spstarr** [tektoncd/pipeline#5122]
# Expected Behavior
When cloning with non-root using security context
```
      securityContext:
        runAsUser: 65534
        runAsNonRoot: true
        allowPrivilegeEscalation: false
```
When using v0.29.0 this works fine, even though `/workspace/output` is owned by:

`drwxrws--x    2 root     40000         6144 Jul 11 18:33 /workspace/output`

# Actual Behavior
When using `v0.3x.x` of `git-init` I get different results:

```
{"level":"error","ts":1657564881.708721,"caller":"git/git.go:55","msg":"Error running git [remote add origin https://github.com/MyCompany/myRepo]: exit status 128\nfatal: unsafe repository ('/workspace/output' is owned by someone else)\nTo add an exception for this directory, call:\n\n\tgit config --global --add safe.directory /workspace/output\n","stacktrace":"github.com/tektoncd/pipeline/pkg/git.run\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:55\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:111\nmain.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:53\nruntime.main\n\truntime/proc.go:250"}
```

# Steps to Reproduce the Problem

1. Use https://github.com/tektoncd/catalog/blob/main/task/git-clone/0.7/git-clone.yaml but modify to use latest `git-init`

Though, this is not 'released', I haven't checked `/ko-app/git-init` to see if there's a safedirectory option to pass or not

**Comment by spstarr** [comment]
Workaroundable closing

**Comment by vdemeester** [comment]
cc @abayer @imjasonh @mattmoor

**Comment by vdemeester** [comment]
@mattmoor If you mean adding the `securityContext` to `runAsRott`, we did it in the tests that runs in the repository. It is not necessary added to the catalog, nor to users Tasks that want to use the latest git image.

@abayer I thought we added a small "hack" to have a `git` safe directory configured so that this wouldn't fail, but maybe I am wrong ? Something like `git config --global --add safe.directory '*'`, like I did [here](https://docs.openshift-pipelines.xyz/pipeline/auth.html#git-clone).

**Comment by vdemeester** [comment]
@abayer then I *think* we need to add more than just `spec.Path` *but* all the folder on top (`/workspace/`, …), maybe ?

**Comment by abayer** [comment]
@vdemeester Perhaps? I may have been too conservative - it may just make sense to do it for `/` regardless of whether `spec.Path` is given or not.

**Comment by spstarr** [comment]
I had to override by this:

```
       git config --global --add safe.directory /workspace/output

        /ko-app/git-init \
          -url="${PARAM_URL}" \
          -revision="${PARAM_REVISION}" \
          -refspec="$refs" \
          -path="${CHECKOUT_DIR}" \
          -sslVerify="${PARAM_SSL_VERIFY}" \
          -submodules="${PARAM_SUBMODULES}" \
          -depth="${PARAM_DEPTH}" \
          -sparseCheckoutDirectories="${PARAM_SPARSE_CHECKOUT_DIRECTORIES}"
```

So within the `git-batch-merge` catalog task

**Comment by spstarr** [comment]
Though, I note the catalog for both `git-batch-merge` and `git-clone` do not use git-init 0.37.x at the moment

**Comment by vdemeester** [comment]
https://github.com/tektoncd/catalog/pull/1012
