### ISSUE TITLE
Developer docs for Tekton's use of CRDs, knative, webhooks, reconcilers, etc

### ISSUE THREAD

**Issue by lbernick** [tektoncd/pipeline#5126]
Right now, our docs for developers link to the k8s docs on CRDs, but don't explain things like:
- which parts of the codebase are run by the webhook vs the reconciler (and what webhooks vs reconcilers actually do)
- the fact that we use knative generated code for the reconciler and webhook, and how our code implements the interfaces (such as validatable, defaultable, and reconcileKind) that knative requires
- how a reconcile loop is actually triggered and what it does

I have found myself explaining these things to multiple new joiners on Google's tekton team so it would be good to just have developer docs on them.

**Comment by dibyom** [comment]
I've found https://book.kubebuilder.io/introduction.html to be helpful as well as https://github.com/knative/pkg/tree/main/injection
