### ISSUE TITLE
HorizontalPodAutoscaler v2beta1 is deprecated in v1.22+

### ISSUE THREAD

**Issue by Ijmcclung** [tektoncd/pipeline#5128]
# Expected Behavior
A released deployment manifest that does not use the deprecated HorizontalPodAutoscaler.
# Actual Behavior
tekton-pipelines uses HorizontalPodAutoscaler in the deployment manifest
# Steps to Reproduce the Problem
1. Download latest release yaml or v0.27.3 yaml
# Additional Info
- Kubernetes version: 1.23

- tkn version :
  Pipeline version: v0.27.3
  Triggers version: v0.16.0
  Dashboard version: v0.20.0

 - Full warning: autoscaling/v2beta1 HorizontalPodAutoscaler is deprecated in v1.22+, unavailable in v1.2
5+; use autoscaling/v2 HorizontalPodAutoscaler

**Comment by vdemeester** [comment]
From #5130 

> Alright, this fails because `apiVersion: autoscaling/v2, kind: HorizontalPodAutoscaler` is available starting with 1.23. So `v2beta1` is, weirdly enough, deprecated in 1.22+ but the `v2` is only available in 1.23.
>
> Bumping to `autoscaling/v2` would effectively mean we require a minimum version of kubernetes to be 1.23. We, most likely, will have to do this before or at the same time as kubernetes 1.25 goes out or is "widely" available.
>
> See https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/ and https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/

**Comment by abayer** [comment]
/priority important-soon

Since we haven't even yet moved to k8s 1.22 minimum, I don't think we can bump straight to 1.23 in v0.39. Maybe v0.40?

**Comment by pritidesai** [comment]
Can we start testing on 1.23 and record any outstanding items?

**Comment by abayer** [comment]
Related knative/serving issue - https://github.com/knative/serving/issues/12806. Looks like Knative will be moving to k8s 1.23 as minimum version in October: https://github.com/knative/community/blob/main/mechanics/RELEASE-SCHEDULE.md. Whether that's a blocker for us moving to requiring 1.23, I don't know.

**Comment by pritidesai** [comment]
We can test but I am thinking it could be a blocker

**Comment by pritidesai** [comment]
@dprotaso mentioned 1.23 is not in GKE regular channel - https://github.com/knative/community/pull/1140 😞

**Comment by pritidesai** [comment]
> Since we haven't even yet moved to k8s 1.22 minimum, I don't think we can bump straight to 1.23 in v0.39. Maybe v0.40?

I though the minimum was already 1.22 but that's not the case as per our documentation. But the default minimum version needed for knative is 1.22 as per https://github.com/tektoncd/pipeline/blob/main/vendor/knative.dev/pkg/version/version.go#L36 And the PR - https://github.com/tektoncd/pipeline/pull/4928.

I missed this action-required in the release notes 😞
