### ISSUE TITLE
TEP0107 - Parameter propagation doesn't work for `taskSpec-steps-args`

### ISSUE THREAD

**Issue by chuangw6** [tektoncd/pipeline#5141]
# Expected Behavior
If users want to propagate parameters that are defined in taskrun to variable replacements, all [places](https://github.com/tektoncd/pipeline/blob/d3b8017e652115ac102a5d10fc455240c1331a49/pkg/reconciler/taskrun/resources/apply.go#L253-L323) where param references can be used should be replaced with the actual value of parameters.

# Actual Behavior
Currently, parameter propagation only works for steps-script field, not other fields i.e. steps-args.

# Steps to Reproduce the Problem
1. Try the following yaml file - a modified version of this [example](https://github.com/tektoncd/pipeline/blob/main/examples/v1beta1/taskruns/alpha/propagating_params_implicit.yaml).

```yaml
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: hello-
spec:
  params:
    - name: message
      value: "hello world!"
  taskSpec:
    # There are no explicit params defined here. They are derived from the TaskRun.
    steps:
    - name: default
      image: ubuntu
      args: [
        "echo",
        "$(params.message)",
      ]
```

2. You will see the following error

```
validation failed: non-existent variable in "$(params.message)": spec.taskSpec.steps[0].args[1]
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.11-gke.1900", GitCommit:"1f775cfbf564daf2c8f0ba548eff09f58045c4a4", GitTreeState:"clean", BuildDate:"2022-04-13T09:36:54Z", GoVersion:"go1.16.15b7", Compiler:"gc", Platform:"linux/amd64"}
  WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
Client version: 0.21.0
Pipeline version: devel (latest main)
```

**Comment by jerop** [comment]
@chitrangpatel thank you for fixing this issue!

- https://github.com/tektoncd/pipeline/pull/5143
- https://github.com/tektoncd/pipeline/pull/5291
