### ISSUE TITLE
flake: TestRealRunnerStdoutAndStderr* unit tests

### ISSUE THREAD

**Issue by abayer** [tektoncd/pipeline#5152]
I've seen a couple of these fail a few times recently on CI with this output:

```
=== RUN   TestRealRunnerStdoutAndStderrPaths
hello world
    runner_test.go:51: stderr: got: , wanted: hello world
--- FAIL: TestRealRunnerStdoutAndStderrPaths (0.02s)
```

...and...

```
=== RUN   TestRealRunnerStdoutAndStderrSamePath
    runner_test.go:78: got: 0, wanted: 24
--- FAIL: TestRealRunnerStdoutAndStderrSamePath (0.01s)
```

I have not been able to reproduce locally.

/kind flake

**Comment by lbernick** [comment]
Seeing this as well, I think it was added recently in #4882; @bradbeck would you mind taking a look at this? It might help to use a fake clock ([example in taskrun reconciler tests](https://github.com/tektoncd/pipeline/blob/3f539724f27a6add8b64d0712e056e4479750975/pkg/reconciler/taskrun/taskrun_test.go#L420)) as opposed to a real one

**Comment by abayer** [comment]
From @dibyom on #5250 
> TestRealRunnerStdoutAndStderrPaths is testing out the expected stdout and stderr strings are written out to files. However, the writes happen [asynchronously](https://github.com/tektoncd/pipeline/blob/94055d92c120a6010f3d61a821e45dea4f893a74/cmd/entrypoint/runner.go#L139) which means that sometimes the output that we get is empty leading to the test being flaky.

**Comment by dibyom** [comment]
One fix might be to have the test wait in a loop till the file has content before comparing (with a time limit of a few seconds say)

**Comment by wlynch** [comment]
Took a crack at this in https://github.com/tektoncd/pipeline/pull/5261 since this blocked one of my other PRs 🙃 - would appreciate any feedback, in particular since this is going against what a comment in the original PR said not to do (but I think it's fine anyway?)
