### ISSUE TITLE
TEP-0114: Custom Tasks Beta - Documentation

### ISSUE THREAD

**Issue by jerop** [tektoncd/pipeline#5158]
In [TEP-0114: Custom Tasks Beta][tep-0114], we proposed migrating `Custom Tasks` and `Runs` to beta. 

Ahead of the promotion, we agreed to expand the documentation for `Custom Tasks` and `Runs`. This issue tracks the documentation work. 

[tep-0114]: https://github.com/tektoncd/community/blob/main/teps/0114-custom-tasks-beta.md

**Comment by XinruZhang** [comment]
To extend the TODOs listed above, we need to
- [ ] Migration guide for v1alpha1.Run --> v1beta1.CustomRun
  - [ ] Prepare a migration doc, refer to the migration doc in the runs.md and pipelines.md
  - [ ] Remove illustration about how to use alpha run
  - [ ] Add illustration about how to use beta customrun
    - [ ] Update [runs.md](https://github.com/tektoncd/pipeline/blob/main/docs/runs.md) e.g. adding missing fields in "configuration" section
    - [ ] Update [pipelines.md#using-custom-tasks](https://github.com/tektoncd/pipeline/blob/main/docs/pipelines.md#using-custom-tasks) e.g. providing practical examples with references to end-to-end examples that use wait custom task
- [ ] UX improvement
  - [ ] Add a table of known Custom Tasks to [runs.md](https://github.com/tektoncd/pipeline/blob/main/docs/runs.md) for visibility - can get started with the list of eight in [TEP-0114](https://github.com/tektoncd/community/blob/main/teps/0114-custom-tasks-beta.md#motivation)
