### ISSUE TITLE
Parameters should default to type string

### ISSUE THREAD

**Issue by jerop** [tektoncd/pipeline#5175]
# Expected Behavior

`Pipelines` with `Parameters` that have no `"type"` specified work with the default value of `"string"`.

# Actual Behavior

`Pipelines` with `Parameters` that have no `"type"` fail. 

Example failures in dogfooding are here: https://dashboard.dogfooding.tekton.dev/#/namespaces/default/pipelineruns

# Steps to Reproduce the Problem

1. Create a `Pipeline` with a `Parameter` without a default value specified.
2. Run the `Pipeline`
3. Observe the `PipelineRun` logs.

# Additional Info

Ran into this error when running the release `Pipeline` which uses the default types for `Parameters` - https://github.com/tektoncd/pipeline/blob/94055d92c120a6010f3d61a821e45dea4f893a74/tekton/release-pipeline.yaml

This was also observed in other `Pipelines` in dogfooding - https://github.com/tektoncd/plumbing/pull/1148

A related issue with `types` in `Results` was fixed in https://github.com/tektoncd/pipeline/pull/5043 and patched in release [v0.37.1](https://github.com/tektoncd/pipeline/releases/tag/v0.37.1)

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  Client Version: v1.24.1
  Kustomize Version: v4.5.4
  Server Version: v1.21.12-gke.1500
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

  ```
  Client version: 0.24.0
  Chains version: v0.8.0
  Pipeline version: v0.37.1
  Triggers version: v0.20.1
  Dashboard version: v0.27.0
  ```

cc @Yongxuanzhang @chuangw6 @lbernick @dibyom @afrittoli @abayer

**Comment by abayer** [comment]
For what it's worth, I would suggest we add a commit on the release-v0.37.x branch adding types to `tekton/publish.yaml` and `tekton/release-pipeline.yaml` so that we can actually release the branch with the fix for this cherry picked.

**Comment by abayer** [comment]
@jerop Ok, now you shouldn't actually need to worry about changing `release-pipeline.yaml` etc - it turns out that they were getting updated properly during the release process, but defaulting wasn't happening because the `webhooks.knative.dev/exclude: "true"` label was on the `default` namespace, skipping the webhooks entirely. 🤦 I just fixed that and existing `Pipeline`s without param types properly got types added.

**Comment by Yongxuanzhang** [comment]
So can we close this issue? Very glad that we can find out the reason eventually. 😄

**Comment by abayer** [comment]
We still need the validation/defaulting/etc to kick in for _unchanged_ `Pipeline`s and `Task`s, so no, the PR still needs to be done. =)

**Comment by Yongxuanzhang** [comment]
> We still need the validation/defaulting/etc to kick in for _unchanged_ `Pipeline`s and `Task`s, so no, the PR still needs to be done. =)

Could you elaborate more on unchanged Pipelines and Tasks? We're planing to add SetDefaults to reconcile so even without mutating webhook, we can also add missing values. 
For OCI bundle resources when they are fetched, we don't call SetDefaults for them, I'm updating the PR to address that

**Comment by dibyom** [comment]
> We still need the validation/defaulting/etc to kick in for unchanged Pipelines and Tasks, so no, the PR still needs to be done. =)

Yes, we do. But the type defaulting behavior is not new and has been around for more than a release. So I don't think this issue needs to block the release

**Comment by Yongxuanzhang** [comment]
> I think this can be closed now right @Yongxuanzhang @abayer ?

Yeah I think so.

**Comment by abayer** [comment]
Agreed
