### ISSUE TITLE
CI build tests should use combined build image and build Windows images

### ISSUE THREAD

**Issue by abayer** [tektoncd/pipeline#5177]
As revealed by #5174, we're not actually build Windows images in `pull-tekton-pipeline-build-tests`, which resulted in code that can't compile on Windows slipping through in a PR. We should be setting Windows-supporting combined build images in `ko_resolve` in `test/presubmit-tests.sh` in the same sort of way we are in https://github.com/tektoncd/pipeline/blob/94055d92c120a6010f3d61a821e45dea4f893a74/tekton/publish.yaml#L96-L113

We can probably just use `gcr.io/tekton-releases/github.com/tektoncd/pipeline/combined-base-image:latest` for that combined base image, rather than generating a new one each time.

/kind bug

**Comment by abayer** [comment]
I'm going to wait to open a PR until #5174 is dealt with, since the build would fail anyway.

**Comment by abayer** [comment]
...ok, yeah, I didn't wait to open a PR. 🤷

**Comment by vdemeester** [comment]
cc @imjasonh
