### ISSUE TITLE
Update nightly release pipeline to match release pipeline

### ISSUE THREAD

**Issue by dibyom** [tektoncd/pipeline#5191]
# Expected Behavior

Nightly release pipeline should execute the same logic as the actual release pipeline

# Actual Behavior

The nightly release pipeline looks very old (still uses pipeline resources)

Nightly: https://dashboard.dogfooding.tekton.dev/#/namespaces/default/pipelines/pipeline-release-nightly?view=yaml
Release: https://dashboard.dogfooding.tekton.dev/#/namespaces/default/pipelines/pipeline-release?view=yaml

I think we might be able to just replace the old pipeline with a new one. The work would be around identifying and making changes in our Nightly trigger to update the inputs for the new pipeline.

**Comment by imjasonh** [comment]
Where does pipeline-release-nightly.yaml even come from?

I only see a pipeline-release.yaml in the repo, and publish-release-nightly.yaml was deleted in https://github.com/tektoncd/pipeline/pull/3788 (Feb 2021)

cc @afrittoli

**Comment by dibyom** [comment]
I was wrong - looks like we are using an updated pipeline but that is in the tekton-nightly namespace
