### ISSUE TITLE
Improve upgrade tests

### ISSUE THREAD

**Issue by lbernick** [tektoncd/pipeline#5193]
Recently, we have had a few issues of regressions that were not detected by CI.

For example, https://github.com/tektoncd/pipeline/pull/4834 introduced changes that caused a new client to be incompatible with an old server.

In addition, some breaking changes were introduced where resources already stored on a cluster became invalid when the server version was upgraded. https://github.com/tektoncd/pipeline/pull/4779 added new defaults via the mutating webhook, and then https://github.com/tektoncd/pipeline/pull/4818 validated the existence of these defaults. However, existing resources didn't receive these defaults, so they failed validation.

We already have some [upgrade tests](https://github.com/tektoncd/pipeline/blob/main/test/e2e-tests-upgrade.sh).
These tests have two parts:
1. Install a new version on a cluster with an older server version, and run integration tests (using the newer version client) on this newer version server
2. Create some resources on a cluster with an older server version, then upgrade the cluster to use a newer server version. Run integration tests on this cluster.

We should add a step where we run integration tests on the older server version (before upgrading the server). This will address the first type of regression detailed here. When we do make a breaking change purposefully (after deprecating a field), I would imagine we'd remove tests for this functionality, so I don't think adding this check would stop us from removing deprecated fields.

The second type of regression (existing resources becoming invalid) seems like it should have been caught by the upgrade tests. I'm not sure why these tests didn't catch this issue-- maybe upgrading the server reapplies the webhook defaults.

**Comment by yuzp1996** [comment]
Hello!  I run e2e on my machine and try to figure out how the e2e test works. Now I think I am a little familiar with this e2e test. But when I run the e2e test I found some weird things and was not sure if it is a bug.

First, there is some unnormal log and I find the related issue https://github.com/tektoncd/pipeline/issues/4777 but seems like the bug is not resolved. But I think it is a good chance to fix it and happy to do this.
<img width="1166" alt="image" src="https://user-images.githubusercontent.com/23007448/181417541-42393c7e-a554-4637-a756-29f8e50aad7b.png">

Second I did not find the function apply_resources in the repository  tektoncd/pipeline or tektoncd/plumbing, I guess maybe the function is deleted but forget to delete the reference here ?https://github.com/tektoncd/pipeline/blob/c1d4702d64a23c4661f0afcf7efccd265b7d7aab/test/e2e-tests-upgrade.sh#L69

**Comment by yuzp1996** [comment]
I noticed that in the e2e-tests-upgrade.sh the older version is v0.5.2.  https://github.com/tektoncd/pipeline/blob/c1d4702d64a23c4661f0afcf7efccd265b7d7aab/test/e2e-tests-upgrade.sh#L28

I think maybe v0.5.2  is too old that is not suitable to be the older version in the upgrade e2e test? I guess maybe no one will upgrade the server to the latest from the oldest version in their production environment?

The above are some of my humble opinions, not sure if it is reasonable. 😂

**Comment by yuzp1996** [comment]
I find that the e2e-tests-upgrade.sh script is referenced here as a cron job but I don't find the related runned job in tektoncd/pipeline github actions. https://github.com/tektoncd/plumbing/blob/main/prow/config.yaml#L1829

Could you help show me where can I get the related runned job? @lbernick  Thanks very much!

**Comment by afrittoli** [comment]
Upgrade testing is something we've been discussing with @abayer in the productivity WG.
It's definitely something that we need to implement, we should have solid tests before v1.0.

We also need to make sure we have enough visibility on periodic jobs. If an upgrade job is running it has not been maintained or seen by anyone for a long time afaik.

We where discussing perhaps we should include it in the release process.

**Comment by dibyom** [comment]
@yuzp1996 Nice detective work! I agree pipeline v0.5.2 is too old and we should definitely make sure the cron job is 1) running and 2) sending notifications somewhere when it fails

**Comment by lbernick** [comment]
Looking at our [prow dashboard](https://prow.tekton.dev/?type=periodic&job=ci-tekton-pipeline-upgrade-tests), upgrade tests have been failing with `fatal: destination path '/home/prow/go/src/github.com/google/licenseclassifier' already exists and is not an empty directory.` I'm guessing they've been broken for some time and we haven't noticed

**Comment by yuzp1996** [comment]
> Looking at our [prow dashboard](https://prow.tekton.dev/?type=periodic&job=ci-tekton-pipeline-upgrade-tests), upgrade tests have been failing with `fatal: destination path '/home/prow/go/src/github.com/google/licenseclassifier' already exists and is not an empty directory.` I'm guessing they've been broken for some time and we haven't noticed.
> 
> Since these tests appear to be broken anyway, might be a good opportunity to move them to Tekton :)

I am sorry I don't understand what moving them to Tekton means. Is it something like dogfooding? Another CI system based on Tekton?

**Comment by yuzp1996** [comment]
Hi, @lbernick @afrittoli  looks like there will be a large change for the e2e upgrade test. I am interested in e2e upgrade test. Is there anything I can do to help now? 😁

**Comment by lbernick** [comment]
> I am sorry I don't understand what moving them to Tekton means. Is it something like dogfooding? Another CI system based on Tekton?

What I meant here is that instead of having this test run on prow, we can run it on our dogfooding kubernetes cluster via a Tekton TaskRun or PipelineRun. One of our medium-term goals is to move Tekton test infrastructure away from using prow and use Tekton to test Tekton instead.

> I am interested in e2e upgrade test. Is there anything I can do to help now? 😁

A great first step would be seeing if you can get the existing scripts working on a k8s cluster! It looks like the tests are currently broken with the error message I've pasted above. Once we have a working script we can get started on adding this as a recurring TaskRun/PipelineRun in our dogfooding cluster.

**Comment by yuzp1996** [comment]
> > I am sorry I don't understand what moving them to Tekton means. Is it something like dogfooding? Another CI system based on Tekton?
> 
> What I meant here is that instead of having this test run on prow, we can run it on our dogfooding kubernetes cluster via a Tekton TaskRun or PipelineRun. One of our medium-term goals is to move Tekton test infrastructure away from using prow and use Tekton to test Tekton instead.
> 
> > I am interested in e2e upgrade test. Is there anything I can do to help now? 😁
> 
> A great first step would be seeing if you can get the existing scripts working on a k8s cluster! It looks like the tests are currently broken with the error message I've pasted above. Once we have a working script we can get started on adding this as a recurring TaskRun/PipelineRun in our dogfooding cluster.

OK!  I commented the `initialize $@` to avoid creating GCP cluster when I run the script locally and found the e2e upgrade test worked well.
https://github.com/tektoncd/pipeline/blob/main/test/e2e-tests-upgrade.sh#L32

Looks like something went wrong in `initialize` I will try to find out why. https://github.com/tektoncd/plumbing/blob/main/scripts/e2e-tests.sh#L357

**Comment by yuzp1996** [comment]
<img width="1220" alt="image" src="https://user-images.githubusercontent.com/23007448/183573701-61de225c-e19c-4993-8b3f-36b79108d631.png">

**Comment by yuzp1996** [comment]
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/23007448/183791422-a3fc0530-d7af-4128-b15f-2f81246cb6fc.png">

**Comment by lbernick** [comment]
I noticed our unit tests also clone the license classifier but don't run into the same problem-- check out the first log line [here](https://storage.googleapis.com/tekton-prow/pr-logs/pull/tektoncd_pipeline/5204/pull-tekton-pipeline-unit-tests/1557371394474381312/build-log.txt). Also, the upgrade tests use a version of the test-runner that is 4 months older than the version the rest of our CI uses, and uses go 1.16 instead of go 1.18. I wonder if this could be related, but I don't have a way to know what was in those images. @afrittoli @abayer can you comment here?

**Comment by lbernick** [comment]
@abayer are you still able to update the prow config to use the new image? Hoping that upgrade tests can run successfully after this change, but even if they do I think it's worth making their failures more discoverable (e.g. post on tekton slack).

**Comment by abayer** [comment]
I'm pretty sure I already did, lemme check.

**Comment by lbernick** [comment]
It looks like upgrade tests are still failing on the [prow dashboard](https://prow.tekton.dev/?job=ci-tekton-pipeline-upgrade-tests) with 
```
Cloning into '/home/prow/go/src/github.com/google/licenseclassifier'...
Activated service account credentials for: [prow-account@tekton-releases.iam.gserviceaccount.com]
fatal: not a git repository (or any of the parent directories): .git
```
which now that I look at it is a different error than before-- so might need some more updates to the image

**Comment by JeromeJu** [comment]
Current progress:

- kubetest
  - when run locally `kubetest` would need to be installed 
![unnamed](https://user-images.githubusercontent.com/46675578/194339354-4fb5295a-f062-4215-b6b2-c9053608bce4.png)

  - kubetest is deprecated as in https://github.com/kubernetes/test-infra/blob/master/kubetest/README.md
Trying to figure out why

**Comment by JeromeJu** [comment]
- When disabling [initialize](https://github.com/tektoncd/pipeline/blob/main/test/e2e-tests-upgrade.sh#L32), the test could run locally.

- When set Previous version at v0.40.2 and deploy on the current devel, the following error occurred when upgrading to the current release:
```
Warning: autoscaling/v2beta1 HorizontalPodAutoscaler is deprecated in v1.22+, unavailable in v1.25+; use autoscaling/v2 HorizontalPodAutoscaler
horizontalpodautoscaler.autoscaling/tekton-pipelines-webhook configured
deployment.apps/tekton-pipelines-webhook configured
service/tekton-pipelines-webhook configured
error when retrieving current configuration of:
Resource: "/v1, Resource=serviceaccounts", GroupVersionKind: "/v1, Kind=ServiceAccount"
Name: "tekton-pipelines-resolvers", Namespace: "tekton-pipelines-resolvers"
from server for: "STDIN": Get "https://35.202.119.160/api/v1/namespaces/tekton-pipelines-resolvers/serviceaccounts/tekton-pipelines-resolvers": dial tcp 35.202.119.160:443: connect: connection timed out
error when retrieving current configuration of:
Resource: "rbac.authorization.k8s.io/v1, Resource=clusterrolebindings", GroupVersionKind: "rbac.authorization.k8s.io/v1, Kind=ClusterRoleBinding"
Name: "tekton-pipelines-resolvers", Namespace: ""
from server for: "STDIN": Get "https://35.202.119.160/apis/rbac.authorization.k8s.io/v1/clusterrolebindings/tekton-pipelines-resolvers": dial tcp 35.202.119.160:443: connect: connection timed out
error when retrieving current configuration of:
Resource: "rbac.authorization.k8s.io/v1, Resource=rolebindings", GroupVersionKind: "rbac.authorization.k8s.io/v1, Kind=RoleBinding"
Name: "tekton-pipelines-resolvers-namespace-rbac", Namespace: "tekton-pipelines-resolvers"
from server for: "STDIN": Get "https://35.202.119.160/apis/rbac.authorization.k8s.io/v1/namespaces/tekton-pipelines-resolvers/rolebindings/tekton-pipelines-resolvers-namespace-rbac": dial tcp 35.202.119.160:443: connect: connection timed out
error when retrieving current configuration of:
Resource: "/v1, Resource=configmaps", GroupVersionKind: "/v1, Kind=ConfigMap"
Name: "bundleresolver-config", Namespace: "tekton-pipelines-resolvers"
from server for: "STDIN": Get "https://35.202.119.160/api/v1/namespaces/tekton-pipelines-resolvers/configmaps/bundleresolver-config": dial tcp 35.202.119.160:443: connect: connection timed out
error when retrieving current configuration of:
Resource: "/v1, Resource=configmaps", GroupVersionKind: "/v1, Kind=ConfigMap"
Name: "config-logging", Namespace: "tekton-pipelines-resolvers"
from server for: "STDIN": Get "https://35.202.119.160/api/v1/namespaces/tekton-pipelines-resolvers/configmaps/config-logging": dial tcp 35.202.119.160:443: connect: connection timed out
error when retrieving current configuration of:
Resource: "/v1, Resource=configmaps", GroupVersionKind: "/v1, Kind=ConfigMap"
Name: "config-observability", Namespace: "tekton-pipelines-resolvers"
from server for: "STDIN": Get "https://35.202.119.160/api/v1/namespaces/tekton-pipelines-resolvers/configmaps/config-observability": dial tcp 35.202.119.160:443: connect: connection timed out
ERROR: Build pipeline installation failed
```

**Comment by JeromeJu** [comment]
Current update:
- Trying to debug
```
/usr/local/bin/runner.sh: line 120: ./test/e2e-tests-upgrade.sh: No such file or directory
```

Previous assumptions:
- might disappear with the kind cluster change

I think there're 2 things here: 
- not sure if the --repo arg worked for catalog test or if it's path_alias
- why it didn't work for the upgrade test

And my questions are about:
- where does it clone the --repo if it's what worked for the catalog test (didn't seem to find it in the runner.sh https://github.com/tektoncd/plumbing/blob/main/tekton/images/test-runner/runner.sh#L100)
- Looking at how prow handles the clone (or say how that clone-log.txt got generated)

**Comment by JeromeJu** [comment]
/close
Closing as currently the upgrade test is running in prow at https://prow.tekton.dev/view/gs/tekton-prow/logs/ci-tekton-pipeline-upgrade-tests/1594874572958601216. While https://github.com/tektoncd/pipeline/issues/5782 is created to track down the following improvement for regression.

**Comment by lbernick** [comment]
commenting for the record, looks like https://github.com/tektoncd/plumbing/pull/1279 is the PR that got upgrade tests working.
