### ISSUE TITLE
I deleted a secret associated with a pipeline and now the pipeline fails everytime in openshift. 

### ISSUE THREAD

**Issue by chabeezy** [tektoncd/pipeline#5214]
# Expected Behavior

Pipeline should run. 

# Actual Behavior

# Steps to Reproduce the Problem

1. Pipelines -> Select Pipeline -> Actions Start Pipeline
2. Expand Advanced Options -> Show Credentials -> add a new credential -> run pipeline
3. Go to secrets within openshift, delete the new credential
4. Run the pipeline again
5. Pipeline fails as credential has been deleted. 

I see no way to remove the association?

**Comment by vdemeester** [comment]
@chabeezy 👋🏼 This is not really a tektoncd/pipeline issue but probably an openshift pipelines and/or ui one. 
That said, the situation your are in is the following : you have a `ServiceAccount` (here `pipeline` SA) that list a secrets that doesn't exists. The way to "fix" that, is to edit the `pipeline` SA to remove the secret from the list — using `kubectl edit`, or through the OpenShift console.

**Comment by chabeezy** [comment]
Thanks for the help @vdemeester
