### ISSUE TITLE
fix agent and dynamic taskname in pipeline 

### ISSUE THREAD

**Issue by r67yfyt** [tektoncd/pipeline#5240]
previously i've thougt that tekton is faster than jenkins, and i've learned more about tekton, finnally i found that tekton sometimes needs more time to dealer with pod start and cannot dynamicly define my task name in pipeline, this can be a problem. in Jenkinsfile the groovy script can do that. i think tekton can do that too.

**Comment by r67yfyt** [comment]
now i often take more that 15 seconds to start my pod, i think this is produced by the changing entrypoint process

**Comment by dibyom** [comment]
@r67yfyt could you explain a bit more about the changing entrypoint process?
