### ISSUE TITLE
PipelineRun 's PodTemplate support affinity

### ISSUE THREAD

**Issue by lookis** [tektoncd/pipeline#5241]
### Feature request

currently, PipelineRun support PodTemplate only three feature: tolerations, nodeSelector, and imagePullSecrets. and I would like to see affinity be supported.

### Use case

In my case, I prefer all the task running on the high performance node which I will label it. but PipelineRun scheduler doesn't support affinity.nodeAffinity. 

and I cannot guarantee the high performance node will avalible all the time, so nodeSelector makes assumption too strong.

**Comment by lookis** [comment]
any update? @yuzp1996

**Comment by yuzp1996** [comment]
> any update? @yuzp1996

Hi! I will start working on this issue today.

**Comment by yuzp1996** [comment]
Hi @lookis,  Podtemplate supports affinity now. This document [podtemplates](https://tekton.dev/docs/pipelines/podtemplates/) could help you.

But if your PipelineRun contains PVC then affinity will be overwritten by affinity-assistant. 

I tried and find two solutions to avoid being overwritten by affinity-assistant.
1.  delete PVC in your pipelinerun
2. disable affinity-assistant by setting feature-flag disable-affinity-assistant to be true 
<img width="1380" alt="image" src="https://user-images.githubusercontent.com/23007448/183874665-cda14793-4225-42cc-9367-e3e7c8e31b95.png">

**Comment by yuzp1996** [comment]
@lookis  For more information about Affinity Assistant, you can refer to this document https://tekton.dev/vault/pipelines-v0.16.3/workspaces/#specifying-workspace-order-in-a-pipeline-and-affinity-assistants.

**Comment by lookis** [comment]
@yuzp1996 I think it would be better to merge two configurations, that's what nodeAffinity.weight for.

It's no reason for pvc case not to prefer a better node, thought it may failed, that's why it's nodeAffinity rather than nodeSelector

**Comment by yuzp1996** [comment]
@lookis  Yes, I agree with you that merging the two configurations is the better approach. I made changes in my dev environment and tested some simple cases and everything seems to be working fine. Maybe tomorrow I will create the PullRequest because I need to add some unit tests and test some more complex cases.

**Comment by yuzp1996** [comment]
PR https://github.com/tektoncd/pipeline/pull/5306 has merged 
/close

**Comment by lookis** [comment]
Thx for the merge.
