### ISSUE TITLE
git-init task could not fetch ssh link with ssh-directory setup properly

### ISSUE THREAD

**Issue by lookis** [tektoncd/pipeline#5242]
# Expected Behavior
git-init task with .ssh setup properly will fetch repository

# Actual Behavior
report a warning and error

{"level":"warn","ts":1659233796.5188842,"caller":"git/git.go:277","msg":"URL(\"ssh://git@github.com:xxxxx.git\") appears to need SSH authentication but no SSH credentials have been provided"}
{"level":"error","ts":1659233801.5396273,"caller":"git/git.go:54","msg":"Error running git [fetch --recurse-submodules=yes --depth=1 origin --update-head-ok --force HEAD]: exit status 128\nssh: Could not resolve hostname github.com:xxxx: Try again\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n","stacktrace":"github.com/tektoncd/pipeline/pkg/git.run\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:54\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:149\nmain.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:53\nruntime.main\n\truntime/proc.go:204"}

# Steps to Reproduce the Problem

1. setup with this task https://hub.tekton.dev/tekton/task/git-clone
2. provided ssh-directory workspace
3. run it

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:14:10Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6+k3s1", GitCommit:"418c3fa858b69b12b9cefbcff0526f666a6236b9", GitTreeState:"clean", BuildDate:"2022-04-28T22:16:18Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

v0.37.0

.ssh folder was created in home folder, but validate in CredsDir
https://github.com/tektoncd/pipeline/blob/v0.38.1/pkg/git/git.go#L77-L88

**Comment by sparkstar** [comment]
I also have the same ploblem. `/tekton/home/.ssh/*` exists and valid in kubernetes container. and I tested tekton `git-init` container run in my desktop and wrote private/known_hosts for ssh auth, then git clone is successfully.

**Comment by NewmanJ1987** [comment]
@lookis Did you ever find a solution to this problem ? I'm facing the same thing now.

**Comment by lookis** [comment]
> @lookis Did you ever find a solution to this problem ? I'm facing the same thing now.

I have to replace ssh with https link and use basic authentication to fetch the code to work around

**Comment by jimmyjones2** [comment]
@lookis Think you've mixed URL formats with `ssh://git@github.com:xxxxx.git`

Should either be `git@github.com:xxxxx.git` or `ssh://git@github.com/xxxxx.git`

**Comment by lookis** [comment]
@chengjoey never mind, I've give up tekton for now, thanks

**Comment by lbernick** [comment]
Duplicate of https://github.com/tektoncd/pipeline/issues/5611
