### ISSUE TITLE
broken installation customizations link

### ISSUE THREAD

**Issue by Arhell** [tektoncd/pipeline#5243]
# Steps to Reproduce the Problem

1. https://tekton.dev/docs/pipelines/matrix/#concurrency-control
2. For more information, see [installation customizations](https://github.com/docs/install.md#customizing-basic-execution-parameters).

**Comment by abayer** [comment]
The issue is with this line: https://github.com/tektoncd/pipeline/blob/main/docs/matrix.md?plain=1#L64

I believe that should be just `(install.md#…)`
