### ISSUE TITLE
flake: TestRealRunnerStdoutAndStderrPaths

### ISSUE THREAD

**Issue by dibyom** [tektoncd/pipeline#5250]
TestRealRunnerStdoutAndStderrPaths is testing out the expected stdout and stderr strings are written out to files. However, the writes happen [asynchronously](https://github.com/tektoncd/pipeline/blob/94055d92c120a6010f3d61a821e45dea4f893a74/cmd/entrypoint/runner.go#L139) which means that sometimes the output that we get is empty leading to the test being flaky. 

Noticed here: https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/5202/pull-tekton-pipeline-unit-tests/1554201931411361792

**Comment by lbernick** [comment]
thanks for filing but this is actually a duplicate of #5152  :)
