### ISSUE TITLE
Matrix Beta

### ISSUE THREAD

**Issue by jerop** [tektoncd/pipeline#5265]
In [TEP-0090: Matrix](https://github.com/tektoncd/community/blob/main/teps/0090-matrix.md), we introduced `Matrix` to support fanning out a `PipelineTask` with different combinations of `Parameters`.

This is an overarching issue to track feature requests and work we need to do before promoting `Matrix` to beta. 

- [x] #5925
- [x] #6602
- [ ] #5266
- [x] #5267
- [x] https://github.com/tektoncd/pipeline/issues/7056
- [x] #7070 

Optional, can be explored in the future if there are use cases:
- [ ] #5268

**Comment by EmmaMunley** [comment]
We do not have any use case right now for Excluding combinations in a matrix so this will be excluded  https://github.com/tektoncd/pipeline/issues/5268

We are waiting to see if there are any use cases right now for consuming results from a matrix. See https://github.com/tektoncd/pipeline/issues/5266

cc: @jerop @pritidesai

**Comment by pritidesai** [comment]
@lbernick a humble request to not add something which is not proven as a blocker for this promotion.

**Comment by pritidesai** [comment]
Adding a recently discovered bug which has to be fixed before the promotion. A `pipeline` with `matrix` randomly fails with an error documented in https://github.com/tektoncd/pipeline/issues/7070.
