### ISSUE TITLE
Create a Tekton GCS release bucket & GCR repo

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#527]
## Expected Behavior
Since we want to clearly distinguish Tekton Pipelines from the rest of Knative, and we are decoupling the release schedule, we should be releasing to a Tekton specific gcr repo and gcs bucket.

It should be clear:
- What permissions are required to make releases to these locations
- Who will have these permissions
- How to obtain the permissions if you need them.

## Actual Behavior

We currently release to gcr at `gcr.io/knative-releases` and the gcs bucket at `knative-releases/build-pipeline`. (see [install.md](https://github.com/knative/build-pipeline/blob/master/docs/install.md))

## Additional Info
Actually making the release automation use these endpoints is out of the scope of this issue, this is just about setting up the repo, bucket and permissions.

**Comment by dlorenc** [comment]
We have this at gcr.io/tekton-releases and gs://tekton-releases.
