### ISSUE TITLE
seperate affinity assistant setting on workspace 

### ISSUE THREAD

**Issue by lookis** [tektoncd/pipeline#5275]
### Feature request

Config affinity assistant on each workspace override default setting in feature-flags

### Use case

I've got same problem with this issue: https://github.com/tektoncd/pipeline/issues/3480

In my case, I have a PVC for code, and another PVC for build cache, and I will use a NAS StorageClass for **cache PVC** which will share data across AZs.

the **code PVC** will share between different task, such as git-clone-task and build-task, so this PVC needs affinity assistant

for now, if I set disable-affinity-assistant to true globally:

1. **code PVC** with normal PV may failed if tasks schedule to different node, 
2. **code PVC** with nas PV need to clean up every time build-task done.

if I set disable-affinity-assistant to false globally:

* **cache PVC** will not work (for ```more than one PersistentVolumeClaim is bound```)

and If i can set **code PVC** to use affinity assistant, and disable **cache PVC**'s affinity assistant, every thing works! and we just need to raise error if more than one affinity assistant exists.

**Comment by icereed** [comment]
/remove-lifecycle stale
We have the same issue. We want to use AWS EFS as a build cache, but also use another ephemeral PVC for the usual workspace.

**Comment by lbernick** [comment]
@lookis @icereed your use case should now be addressed by the new "coscheduling" feature, which allows all of a pipelinerun's pods to be scheduled to one node, and multiple PVCs to be bound to a single taskrun in a pipelinerun. We'd appreciate if you can share any feedback on https://github.com/tektoncd/pipeline/issues/6990!
