### ISSUE TITLE
LimitRange transformer behavior inconsistent with our documentation

### ISSUE THREAD

**Issue by lbernick** [tektoncd/pipeline#5278]
# Behavior described in [docs](https://github.com/tektoncd/pipeline/blob/main/docs/compute-resources.md#limits)

If a taskrun is created with resource requirements inconsistent with a limitrange (e.g. requests < min or limits > max),
the resource requirements will be adjusted to fit within the limitrange constraints.

# Actual Behavior

If a taskrun is created with resource requirements inconsistent with a limitrange, the resulting pod will fail to schedule.
The pod may also have requests > limits and be invalid.

**Comment by lbernick** [comment]
@skaegi curious about your opinion on whether we should change the docs or the behavior

**Comment by lbernick** [comment]
Even if we decide to allow TaskRuns to fail when they don't meet limitrange requirements, we should definitely stop creating invalid pods. (This happens when e.g. a taskrun's requests are larger than the limitrange max or its limits are smaller than the limitrange min.)

**Comment by skaegi** [comment]
My feeling is that other than the resource spreading algorithm for step "requests" we should not interfere. We should not change the "requests" for init containers or side-car containers, and we should not change "limits" in any containers.

We should create a valid schema-wise pod but don't try to second guess the admin's intent for limitranges and what other policy they might have in place. Let the pod or limitrange errors happen as they would for a Job, Deployment, etc.
