### ISSUE TITLE
Inconsistency/race conditions in handling of Pipeline Task timeouts for Runs

### ISSUE THREAD

**Issue by lbernick** [tektoncd/pipeline#5286]
Today, [Pipeline Task timeouts](https://tekton.dev/docs/pipelines/pipelines/#configuring-the-failure-timeout) work in a way that I find confusing for Custom Tasks.

The PipelineRun reconciler [passes the pipeline task timeout down to a newly created run](https://github.com/tektoncd/pipeline/blob/deb0fec6e861ed9c74c7f43791b6e52823a62e0d/pkg/reconciler/pipelinerun/pipelinerun.go#L892), [and expects the run to implement timeout](https://github.com/tektoncd/pipeline/blob/deb0fec6e861ed9c74c7f43791b6e52823a62e0d/docs/runs.md#specifying-timeout).
However, the reconciler also [cancels the run when it has timed out](https://github.com/tektoncd/pipeline/blob/deb0fec6e861ed9c74c7f43791b6e52823a62e0d/pkg/reconciler/pipelinerun/pipelinerun.go#L627-L652), and expects the run controller to support cancellation.

This means that a run controller has to handle timing itself out at the same time as it handles being canceled by the PipelineRun. I think this is confusing, and could result in race conditions (the run might be marked as cancelled, or it might be marked as timed out).

There are a few things we could do about this:
1. Leave as is
2. Continue to pass the Pipeline Task timeout to the Run, and expect all Runs to implement timeout. Do not cancel the Run when the Pipeline Task timeout has been reached.
3. Remove timeout from the Run spec, and continue to cancel Runs that have reached their Pipeline Task timeout. If a Run would like to support some type of timeout on its own, timeout can be added to the [custom run spec](https://github.com/tektoncd/pipeline/blob/369665cb683e1b09cc4bbf773c39ec78a005431d/pkg/apis/pipeline/v1alpha1/run_types.go#L44).

**Option 2**

Pros:
- Run spec retains the concept of a timeout (defined as the amount of time after starting that the run controller should set the run status to "failed"), which is critical to the functioning of most custom tasks.
- Run timeouts use the same spec and implementation when they time out as part of a PipelineRun vs on their own.
- Consistent with how we handle Pipeline Task timeouts for TaskRuns.

Cons:
- If a run controller doesn't implement support for timeout, this will likely lead to a confusing user experience (the PipelineRun controller will probably assume the run has timed out, and might mark itself as failed even if the run is still going. I'm actually not sure what would happen here.)

**Option 3**

Pros:
- A Run user knows whether a run supports timeout based on whether or not timeout is in the run custom spec.
- A timeout field doesn't make sense for all runs, like the wait task or colocatedPipelineRun (which has the same `timeouts` field as PipelineRun).

Cons:
- Consider a Run that defines a timeout, and is also referenced from a Pipeline Task with a timeout-- this is pretty confusing. (I think the reason for this confusion is that the run embedded spec is the analog of an embedded Task spec, which is an authoring time type, and timeouts are a runtime-related concern.)

**Related**:
A related issue is #5218. `Retries` are another field specified on Pipeline Tasks, but that require some implementation from the run controller to work as intended. It's probably desirable for our decision on timeouts to be consistent with how we would like to handle retries for custom tasks. (However, we do not have this consistency between retries and timeouts for TaskRuns. TaskRuns implement timeout themselves, while TaskRun retries are mostly implemented by the PipelineRun reconciler.)

We discussed this in API WG today, where a few people favored option 2. I favored option 3 but after writing this issue up I think option 2 may make more sense.

**Comment by lbernick** [comment]
FYI @pritidesai @jerop @abayer

**Comment by abayer** [comment]
`Run` controllers will need to implement cancellation regardless, so there's a certain logic to just requiring cancellation support and having the `PipelineRun` reconciler handle `PipelineTask`-driven timeouts. But both because that's inconsistent with how we handle timeouts with `TaskRun`s (currently, and once #5134 lands) and because the ability to launch a custom task `Run` directly with a timeout seems like a desirable thing, I'd lean hard towards 2. 

If a `Run` controller doesn't implement timeouts in option 2, a `PipelineTask.Timeout` for a custom task will be ignored, which isn't ideal, but I think the consistency in syntax and behavior for both `TaskRun`s and `Run`s, whether run as part of a `PipelineRun` or standalone, is more valuable than the hit from `Run` controllers not implementing timeouts. I'd actually suggest we make supporting timeouts part of the contract for `Run` controllers before we move custom tasks to beta, in fact.
