### ISSUE TITLE
get step name within container

### ISSUE THREAD

**Issue by LilyHolms** [tektoncd/pipeline#5290]
### Feature request

I noticed we can get info like taskrun name (pod name) by `$(context.task.name)`, but is there a way to get step name (container name) within the container? 

https://tekton.dev/vault/pipelines-v0.17.3/variables/

### Use case

```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-get-context
spec:
  steps:
    - name: step-get-context
      image: ubuntu
      script: |
        #!/bin/bash
        echo "TaskRunUID: $(context.taskRun.uid)"
        echo "Task name: $(context.task.name)"
        echo "TaskRun name: $(context.taskRun.name)"
        echo "Step name: $(spec.steps[0].name)"                  # does not work
        cat /etc/hostname
```

**Comment by afrittoli** [comment]
@LilyHolms this is not supported today. Do you have a specific use case for this feature?
