### ISSUE TITLE
Create `Task` for creating GitHub release

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#530]
## Expected behaviour

We should be testing and releasing Pipelines with Pipelines.

We should have a `Task` (and related Resources) defined that we can use to:
- Create a new release in GitHub
- Generate release notes from ["release notes" in merged PRs](https://github.com/knative/build-pipeline/blob/master/.github/pull_request_template.md)

### The Task

* Inputs:
  - git repo
  - gcr images (for all Tekton images - we can assume these have been built by something upstream, specifically this is going to be #528)
  - gcs bucket (where the release.yaml was written - we can assume we have this has been built by something upstream, specifically this is going to be #529)
* Outputs:
  - n/a - we don't yet have a type for this (+ @dlorenc related to some of your investigations about creating an scm type)
* Parameters:
- range of commits to scrape for changelog
- ?

## Actual Behavior

We currently use [prow](https://github.com/knative/test-infra/tree/master/ci/prow) and [knative release scripts](https://github.com/knative/build-pipeline/blob/master/hack/release.md) for releasing.

## Additional Info

* We're going to need a service account that has access to write to GitHub - whoever works on this issue can assume this exists
* See [0.1 release.yaml](https://github.com/knative/build-pipeline/releases/download/v0.1.0/release.yaml) to see all images required
* Actually triggering this is not in scope for this issue, it's fine to test manually (we'll be linking these together in a later issue)
* PR should include docs that explain how the Task works

**Comment by bobcatfish** [comment]
This is what I did manually for the 0.2.0 release:

```bash
git checkout 7c43fbae2816c7271bed51098d0595cd6174c7a3

git tag -a 0.2.0 -m "Tekton Pipeline release v0.2.0"
git push upstream 0.2.0

# Using https://github.com/github/hub
hub release create --prerelease --attach=release.yaml -m "Tekton Pipelines release v0.2.0" 0.2.0
```

Note that hub asked me for my github username + pass - not sure how we'll pass this info to hub in automation, looks like it stores some token info in `~/.config/hub`

To find the committers, I ran `git log --format=short c1500fa...7c43fba | grep Author | sort | uniq` (where the commits are the v0.1.0 and 0.2.0 tags) then manually looked up the usernames for each person :sweat_smile: 

To find the changes I manually opened all commits at https://github.com/tektoncd/pipeline/compare/v0.1.0...0.2.0 and followed them to their PRs :sweat_smile:

**Comment by bobcatfish** [comment]
Maybe use goreleaser: https://github.com/tektoncd/cli/blob/master/tekton/goreleaser.yml

**Comment by afrittoli** [comment]
I think this task in plumbing addresses this: https://github.com/tektoncd/plumbing/pull/134
@bobcatfish

**Comment by vdemeester** [comment]
I think so too :angel: 
/close
