### ISSUE TITLE
Form a Standard Process of Dealing with Kubernetes Deprecations

### ISSUE THREAD

**Issue by XinruZhang** [tektoncd/pipeline#5300]
Currently, the most major implementation of Tekton APIs is on Kubernetes.
Kubernetes deprecates APIS [^1] now and then, we need to form a standard process
to deal with those deprecation announcements.

The benefit is obvious: **we can avoid any incompatibility between Tekton and K8s
of a new version with deprecated APIs/Flags/Features removed.** (#4158 wouldn't be
an issue any more).

One thing we may want to take into account is: the minimum supported k8s version
might change more often, see [the reason](#how-the-minimum-supported-k8s-version-get-changed) detailed below.

[^1]: https://kubernetes.io/docs/reference/using-api/deprecation-guide/

---
#### How the minimum supported k8s version gets changed

Let's take the table below as an example, say Tekton
uses a to-be-deprecated `v1beta1` K8s resource, to migrate the deprecation,
Tekton needs to at least depend on K8s X+3 release (meaning updating related
dependencies like `client-go`), and uses `v1beta2` instead of `v1beta1`, and
there might be kubernetes minor version upgrade between release X and X+3.

<table>
  <thead>
    <tr>
      <th>Release</th>
      <th>API Versions</th>
      <th>Preferred/Storage Version</th>
      <th>Notes</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>X</td>
      <td>v1beta1</td>
      <td>v1beta1</td>
      <td></td>
    </tr>
    <tr>
      <td>X+1</td>
      <td>v1beta1</td>
      <td>v1beta1</td>
      <td></td>
    </tr>
    <tr>
      <td>X+2</td>
      <td>v1beta1</td>
      <td>v1beta1</td>
      <td></td>
    </tr>
    <tr>
      <td>X+3</td>
      <td>v1beta2, v1beta1 (deprecated)</td>
      <td>v1beta1</td>
      <td>
        <ul>
          <li>v1beta1 is deprecated, "action required" relnote</li>
        </ul>
      </td>
    </tr>
    <tr>
      <td>X+4</td>
      <td>v1beta2, v1beta1 (deprecated)</td>
      <td>v1beta2</td>
      <td></td>
    </tr>
    <tr>
      <td>X+5</td>
      <td>v1, v1beta1 (deprecated), v1beta2 (deprecated)</td>
      <td>v1beta2</td>
      <td>
        <ul>
          <li>v1beta2 is deprecated, "action required" relnote</li>
        </ul>
      </td>
    </tr>
    <tr>
      <td>X+6</td>
      <td>v1, v1beta2 (deprecated)</td>
      <td>v1</td>
      <td>
        <ul>
          <li>v1beta1 is removed, "action required" relnote</li>
        </ul>
      </td>
    </tr>
  </tbody>
</table>

**Comment by vdemeester** [comment]
Note: we also depend on `knative.dev/pkg` minimun Kubernetes version. So far, the only "time" we bump our "minimun" Kubernetes verison is when we bump `knative.dev/pkg` and it does bump that version.

/cc @imjasonh
