### ISSUE TITLE
FR: pipelineRun.spec.taskRunTemplate

### ISSUE THREAD

**Issue by lbernick** [tektoncd/pipeline#5302]
### Feature request

We already have [pipelineRun.spec.taskRunSpecs](https://github.com/tektoncd/pipeline/blob/bf8be59f43dd81ef2f26102ae5b3c91e22e30bdb/pkg/apis/pipeline/v1beta1/pipelinerun_types.go#L229), but it might be nice to be able to specify a TaskRun configuration that applies to every TaskRun in the PipelineRun  by default. An analogous feature is [task.spec.stepTemplate](https://github.com/tektoncd/pipeline/blob/bf8be59f43dd81ef2f26102ae5b3c91e22e30bdb/pkg/apis/pipeline/v1beta1/task_types.go#L113).

### Example use cases

- I would like to use the same service account for all of my pipeline tasks except one.
- I want to specify compute resources that each TaskRun in my PipelineRun should run with, and don't want to have to specify them individually for each TaskRun.

**Comment by yuzp1996** [comment]
taskRunTemplate should be a field of pipelineRun.spec or a field of pipeline.spec ?

**Comment by lbernick** [comment]
I think we'd want this to be on PipelineRun, since the use cases I mentioned (service account and compute resources) are probably things you'd want to specify for a pipelinerun rather than a Pipeline. However (I should have mentioned this in the initial issue) I think we should have a small TEP (design proposal) for this before implementing it just to make sure there are no concerns from maintainers. Is that something you'd be willing to do, with help from me?

**Comment by yuzp1996** [comment]
> I think we'd want this to be on PipelineRun, since the use cases I mentioned (service account and compute resources) are probably things you'd want to specify for a pipelinerun rather than a Pipeline. However (I should have mentioned this in the initial issue) I think we should have a small TEP (design proposal) for this before implementing it just to make sure there are no concerns from maintainers. Is that something you'd be willing to do, with help from me?

Of course! I would like to do it!  Thanks for your help！@lbernick     

Maybe I should create a TEP PR in [Tekton/community](https://github.com/tektoncd/community/tree/main/teps) first?

**Comment by lbernick** [comment]
Thank you, that would be amazing! The instructions for creating a new TEP are [here](https://github.com/tektoncd/community/tree/main/teps#creating-and-merging-teps). Please let me know if you need any help with this.

**Comment by yuzp1996** [comment]
> Thank you, that would be amazing! The instructions for creating a new TEP are [here](https://github.com/tektoncd/community/tree/main/teps#creating-and-merging-teps). Please let me know if you need any help with this.

Yes! I will 😁 !

Since I'm not good at English and I need to do some in-depth research, it will take some time to create the TEP, but I'll sync the progress here.

**Comment by lbernick** [comment]
Thanks so much for adding the TEP @yuzp1996! are you still interested in implementing this, or should we assign someone else? Either way works!

**Comment by yuzp1996** [comment]
Yes I am，  I will assign it to me Thanks！



发自我的小米
在 Lee Bernick ***@***.***>，2022年9月7日 上午3:36写道：

Thanks so much for adding the TEP @yuzp1996<https://github.com/yuzp1996>! are you still interested in implementing this, or should we assign someone else? Either way works!

**Comment by yuzp1996** [comment]
@JeromeJu  welcome! 😀

**Comment by yuzp1996** [comment]
When should we start to implement this TEP? I remember we need to implement it in V1. When will V1 be released?

**Comment by lbernick** [comment]
We already have v1 Go structs [here](https://github.com/tektoncd/pipeline/tree/main/pkg/apis/pipeline/v1). Before we release v1, we need to move serviceAccountName and podTemplate to pipelineRun.spec.TaskRunTemplate in this folder. After releasing v1, we can implement the rest of the TaskRunTemplate fields.

**Comment by yuzp1996** [comment]
> 

Ok! I am worried I would not be able to start work on this implement immediatly because I will be a little busy for my work in the next few weeks.

Look like @JeromeJu is fine to do it. Maybe you can start to implement it now. I can just help review the PR if possiable! Thanks!

**Comment by JeromeJu** [comment]
> > 
> 
> Ok! I am worried I will not be able to start to implement it immediatly because I will be a little busy for my work in the next few weeks.
> 
> Look like @JeromeJu is fine to do it. Maybe you can start to implement it now. I can just help review the PR if possiable! Thanks!

Sounds good. Thank you for the excellent collaboration on the TEP work.

**Comment by JeromeJu** [comment]
TODO: implement the rest of the fields after v1 release

**Comment by wuhuizuo** [comment]
How about support `taskTemplate` in `Pipeline.Tasks`. I found it's impossible to build multi arch image with `kaniko` with multi tasks planed to run on different arch nodes.

**Comment by lbernick** [comment]
Thanks @wuhuizuo, could you give an example of what you'd like to exist? I'm curious why `pipelinerun.spec.taskrunspecs` does not work for your use case.

**Comment by wuhuizuo** [comment]
> Thanks @wuhuizuo, could you give an example of what you'd like to exist? I'm curious why `pipelinerun.spec.taskrunspecs` does not work for your use case.

Sorry for late reply. I discussed it in slack [channel](https://tektoncd.slack.com/archives/CJ62C1555/p1679993588687849), also I created a issue in [community](https://github.com/tektoncd/community/issues/1011)
