### ISSUE TITLE
Add a new annotation field `pipeline.tekton.dev/builderVersion`

### ISSUE THREAD

**Issue by chuangw6** [tektoncd/pipeline#5303]
### Feature request

Add a new annotation field `pipeline.tekton.dev/builderVersion` to capture the builder version that can be customized when installing tekton.

### Use case

Use the annotation field to attach customized version string to run objects i.e. pipelinerun/taskrun, which can be used by the Chains to capture the builderVersion in attestation.

note:
- The motivation behind having a customizable field is that this allows users of Tekton Chains to generate an intoto attestation which can capture more customized information other than tekton version itself from the run object i.e. `<customized-prefix>/tekton@<version-number>`
- The reason why not customize `[pipeline.tekton.dev/release](http://pipeline.tekton.dev/release)` is because that the code uses [changeset.Get()](https://github.com/tektoncd/pipeline/blob/bf8be59f43dd81ef2f26102ae5b3c91e22e30bdb/pkg/pod/pod.go#L293-L297) which relies on the vcs.revision property auto set by the go build process (since go 1.18).

**Comment by chuangw6** [comment]
cc @dibyom @wlynch

**Comment by vdemeester** [comment]
@chuangw6 what does that "builderVersion" would/can convey as information ? I am not yet sure to understand the use case there.

**Comment by chuangw6** [comment]
> @chuangw6 what does that "builderVersion" would/can convey as information ? I am not yet sure to understand the use case there.

Hi @vdemeester,
The motivation here is to convey the accurate Tekton Pipeline version in a way that customers can customize the format through `builderVersion`.
In the SLSA community, there is a strong interest that people want to record the builder version information in the SLSA provenance. So next SLSA release is very likely to have a field for the builder version. See more details here https://github.com/slsa-framework/slsa/issues/319.

Today's slsa 0.2 spec doesn't have a field for this. However, we can use this information as the value of [`builder_version`](https://github.com/grafeas/grafeas/blob/cd23d4dc1bef740d6d6d90d5007db5c9a2431c41/proto/v1/build.proto#L32) field in Grafeas BUILD note, and could also embed the version information in the `predicate.builder.id` field of SLSA 0.2 spec. Getting this information from run object rather than through Chains's configmap helps version drift problem i.e. outdated Chains configmap says the version is x, but actual builder version is x + 1.


Feel free to chime in if you have more comments/thoughts @wlynch @dibyom.

Thanks.

**Comment by vdemeester** [comment]
@chuangw6 understand, but then what differs from the `pipeline.tekton.dev/release` ? Do we need 2 labels/annotations or can we just make the existing one have the right set of informations ?

**Comment by wlynch** [comment]
> what differs from the `pipeline.tekton.dev/release` ? Do we need 2 labels/annotations or can we just make the existing one have the right set of informations ?

There's also `app.kubernetes.io/version` and `version` that also look like they serve a similar purpose. 😂

It would be great to consolidate these, or at the very least take inventory of what each label is used for.
