### ISSUE TITLE
How to config timeout or disable in  pipeline v0.32.4

### ISSUE THREAD

**Issue by hillbun** [tektoncd/pipeline#5316]
I install tekton pipeline v0.32.4, PipelineRun aborted when timeout of 1 hour.

PipelineRun "gitlab-pipelinerun-98xsx" failed to finish within "1h0m0s"

How to config timeout or disable it?

**Comment by AlanGreene** [comment]
There are a number of ways to configure the timeout, including on the PipelineRun, the tasks, or by changing the default timeout value.

Docs for Pipelines v0.32: https://tekton.dev/vault/pipelines-v0.32.x/pipelineruns/#configuring-a-failure-timeout
Docs for latest Pipelines release: https://tekton.dev/docs/pipelines/pipelineruns/#configuring-a-failure-timeout

The docs includes information on each of these options, including the global `default-timeout-minutes`.

**Comment by afrittoli** [comment]
Feel free to reopen if there still open questions on this.
