### ISSUE TITLE
YAML Parser tests accept arbitrary fields

### ISSUE THREAD

**Issue by lbernick** [tektoncd/pipeline#5318]
# Expected Behavior
Test inputs representing TaskRuns, PipelineRuns, etc, should not contain fields that aren't part of the spec of those objects.

# Actual Behavior
The following test passes:

```
func TestParseTaskRun(t *testing.T) {
	MustParseTaskRun(t,
		`
spec:
  taskRef:
    name: mytask
  foo: bar
`)
}
```

We use the yaml parser extensively in [pipelinerun_test.go](https://github.com/tektoncd/pipeline/blob/main/pkg/reconciler/pipelinerun/pipelinerun_test.go) and [taskrun_test.go](https://github.com/tektoncd/pipeline/blob/main/pkg/reconciler/taskrun/taskrun_test.go)

**Comment by jerop** [comment]
related discussion in https://github.com/tektoncd/pipeline/issues/297

there's a downside that @jonjohnsonjr pointed out:

> If you don't allow unknown fields and you ever plan to add a new field, your users won't be able to downgrade build-pipeline, because the new field will be unrecognized by the old build-pipeline.

this was before I joined tekton, but I believe `build-pipeline` that's mentioned there was the old name for tekton

**Comment by dibyom** [comment]
> If you make a task with random nonsense it'd successfully be created but then every time you make a pod it will be rejected for the invalid nonsense field

I don't know if this is true - we have a validation webhook that should fail this validation

**Comment by 06kellyjac** [comment]
Tekton already has upgrade schema migrations, is it not possible to have downgrade schema migrations?

Also if there is a breaking difference across schemas I dont think it should be as easy as change the version and apply it because they're different.
You could apply something that doesnt work at all and then youve gone and broken all the pods it churns out.

And if its at the cost of not getting any validation feedback for mistakes thats pretty painful

**Comment by afrittoli** [comment]
@lbernick is it ok to close this issue now?

**Comment by lbernick** [comment]
Thanks for checking @afrittoli, I think my main concern is that it's possible to define invalid yaml in reconciler tests without being alerted by a test failure. We don't have to change the `allow-unknown-fields` in our CRD schemas since we have the validation webhook (that's probably a separate discussion, and better tracked by #1461) but I think this issue has value in ensuring our tests aren't providing false positive signals.

/remove-lifecycle rotten
