### ISSUE TITLE
Support Multiple Windows Entrypoint Images

### ISSUE THREAD

**Issue by doombubbles** [tektoncd/pipeline#5327]
### Feature request

Backwards compatibility for those who still require specifically ltsc2019 entrypoint images by including multiple windows definitions in the manifests such as [this one](https://console.cloud.google.com/gcr/images/tekton-releases/global/github.com%2Ftektoncd%2Fpipeline%2Fcmd%2Fentrypoint@sha256:db48b1a4c903acd0d87ebbe5627a73a4625c253ce1851d42ba28323bee285159/details?tab=pull). I've put together image manifests myself that include separate images for windows `os.version` "10.0.19042.XXX" vs "10.0.20348.XXX" so it hopefully ought be able to work here as well.

### Use case

We'd like to be able to upgrade our Tekton version to be able to build on windows ltsc2022 nodes, but we cannot afford to break our existing ltsc2019 builders.

If I'm missing or misunderstanding anything about the situation that makes this not necessary, please let me know. (I haven't yet had the time to go actually try upgrading on a test cluster yet, but I'm extrapolating based on my previous experience with needing to match the windows image version exactly)

**Comment by imjasonh** [comment]
This should be pretty straightforward to accomplish. The combined base image is stitched together by a script in plumbing (https://github.com/tektoncd/plumbing/tree/main/cmd/combine) which takes two source images, but could fairly easily take 2+ so long as they don't have any overlaps in provided platforms.

I'll send a PR, and if things go well we should see this in an upcoming Tekton release.

**Comment by imjasonh** [comment]
With the change in https://github.com/tektoncd/plumbing/pull/1180 I'm able to produce a combined base image that has support for multiple Windowseses:

```
$ go run ./cmd/combine \
    gcr.io/distroless/static:nonroot \
    mcr.microsoft.com/windows/nanoserver:ltsc2022 \
    mcr.microsoft.com/windows/nanoserver:ltsc2019 \
    $OUT
$ crane manifest $OUT | jq '.manifests[].platform'
...
{
  "architecture": "s390x",
  "os": "linux"
}
{
  "architecture": "amd64",
  "os": "windows",
  "os.version": "10.0.20348.887"
}
{
  "architecture": "amd64",
  "os": "windows",
  "os.version": "10.0.17763.3287"
}
```

**Comment by doctorpangloss** [comment]
Looks great, really relieved about s390x support

**Comment by imjasonh** [comment]
Hey I managed to get this in before today's release!😎

https://github.com/tektoncd/pipeline/releases/tag/v0.39.0
