### ISSUE TITLE
How can I pause the running task and later resume  it or retry the failed task even if it exceed the Retry times？

### ISSUE THREAD

**Issue by NEUerYZY** [tektoncd/pipeline#5348]
When I use Tekton v0.25.0 , I met some scenes in actual use.
scene 1 :  I make up  a Pipeline with several Task , one of the Pipeline's Task runs failed .  I do not want to replay  the succeed Task , only want to restart the failed Task. 
I know  Tekton has a feature with keyboard **retry** which  can retry the failed Task.  But we still met a problem that if the Task's failure time exceed the retry time I set , how can I restart the Task  without replay the former succeed Task？

scene 2 ：I make up  a Pipeline  with several Task , when the Pipeline runs to a Task，out of some reason ,  I want's to pause the Task to do some manual intervention operation  after that  I want to continue the Pipeline to go on the following Task . 
For example ,   Before I execute automated testing  , I must deploy my service and the service  must be available .  I want to pause the Pipeline  until the Deployed service is available  ，and then I send a signal to resume  the Pipeline's running ， so that the automated testing Task can get  correct results.

Is there any solution to resolve the scene I mentioned above?
Hope for help,  Thanks a lot

**Comment by pritidesai** [comment]
[TEP-0123 - Specifying on-demand-retry in a pipelineTask](https://github.com/tektoncd/community/pull/823) addresses the first scene (use case) mentioned here.
