### ISSUE TITLE
Emit warning or error for creation of v1 PipelineRun with "full" or "both" embedded status

### ISSUE THREAD

**Issue by JeromeJu** [tektoncd/pipeline#5355]
This issue tracks down the requirement of a similar validation function for the `minimal` Embedded Status for PipelineRun. Thanks to the discussion with @abayer and @lbernick , a warning should be emitted to users if they are creating a v1 PipelineRun while the feature flag is not set to "minimal".

However, right now in pipeline we don't have a great way of returning a warning to the user. Ideally we would want the webhook to accept the pipelinerun, but return a warning via its rest api.

_Originally posted by and thanks to @lbernick in https://github.com/tektoncd/pipeline/pull/5219#discussion_r932170481_

**Comment by abayer** [comment]
So this wouldn't really be warning on a deprecated field, exactly - the `Status.TaskRuns` and `Status.Runs` fields are created/populated by the reconciler, not the CRD author. What could make sense would be checking if `embedded-status` isn't `minimal` during `v1` `PipelineRun` creation and warning there...or maybe appending something to the `PipelineRun.Status`'s `Condition.Message` saying "yeah, we don't support that?" in addition to whatever's already going there.

Actually, maybe the _right_ answer is for `v1` `PipelineRun` reconciliation to treat `embedded-status` being set to `full` as if it were set to `both` instead - populating both the deprecated `Status.TaskRuns`/`Status.Runs` and the new `Status.ChildReferences`.

**Comment by vdemeester** [comment]
/remove-lifecycle stale
I think we still need to discuss / handle this.

**Comment by lbernick** [comment]
I think this issue is handled by #5813 so I'm going to close, feel free to reopen if needed
