### ISSUE TITLE
Make Tekton Prow jobs invoke Tekton Pipelines

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#538]
## Expected Behavior

The CI/CD used by Tekton Pipelines ([triggered via prow jobs](https://github.com/knative/test-infra/blob/master/ci/prow/config.yaml#L466)) should be able to invoke Pipelines.

In the long run we want Pipeline support in Prow (#537), but in the meantime, we can make the existing Prow jobs:

- Deploy Tekton Pipelines (to the Prow cluster itself? not sure, will need input)
- Create a PipelineRun from a template

For this issue, we can create just a "Hello world" type PipelineRun, to prove it works.

## Actual Behavior

The CI/CD used by Tekton Pipelines ([triggered via prow jobs](https://github.com/knative/test-infra/blob/master/ci/prow/config.yaml#L466)) invokes scripts only.

## Additional Info

This is the short term solution, the long term solution is #537. If we can go straight to that, even better!

**Comment by abayer** [comment]
Is @rawlingsj's Prow work close enough to ready to be feasible here in the near term?

**Comment by rawlingsj** [comment]
We have a pipeline controller that seems to be working great https://github.com/jenkins-x/test-infra/blob/238d673/prow/cmd/pipeline/controller.go - main issue ATM it's slightly tied to Jenkins X as we have it optionally calling out to the 'pipelinerunner' service.  I did want to take what I've done and apply a non Jenkins X related PR to the test-infra repo but not been able to yet unfortunately.

**Comment by dlorenc** [comment]
I don't think this is still relevant. Prow can call Tekton tasks already. Closing for now.

**Comment by bobcatfish** [comment]
I'm gonna assign this to @rawlingsj for posterity :D thanks for this @rawlingsj !!! 🎉 ❤️

**Comment by bobcatfish** [comment]
https://github.com/tektoncd/pipeline/issues/537
