### ISSUE TITLE
Add kube-state-metrics like metrics for TaskRuns and PipelineRuns

### ISSUE THREAD

**Issue by RafaeLeal** [tektoncd/pipeline#5416]
### Feature request

`kube-state-metrics` has some metrics like `kube_pod_labels` and `kube_pod_info` which allow us much more flexibility while aggregating metrics for tasks. But, as far as I know, it doesn't support CRDs out of the box. This [blog post](https://blog.freshtracks.io/a-deep-dive-into-kubernetes-metrics-part-6-kube-state-metrics-14f4e7c8710b) explains well how that works for pods.

This would help us aggregate metrics using arbitrary labels. 

### Use case

If we had something like `kube_taskrun_labels`, we could use it to build metrics like this:
```promql
avg by(label_tekton_dev_pipeline_task) (
  tekton_pipelines_controller_pipelinerun_taskrun_duration_seconds
  * on (taskrun) group_left(label_tekton_dev_pipeline_task) kube_taskrun_labels
)
```

This would give us the average duration by `pipelineTask`. So you could have metrics for avg time of deploy by each environment, for example.

**Comment by colinodell** [comment]
This would be extremely helpful!

**Comment by uqix** [comment]
Is this feature implemented? Can't find it in docs.
