### ISSUE TITLE
TEP-0114: Custom Tasks Beta - Conversion from `v1alpha1.Run` to `v1beta1.CustomRun`

### ISSUE THREAD

**Issue by jerop** [tektoncd/pipeline#5443]
In [TEP-0114: Custom Tasks Beta][tep-0114], we proposed migrating `Custom Tasks` and `Runs` to beta. 

This issue tracks adding a conversion from `v1alpha1.Run` to `v1beta1.CustomRun`.

[tep-0114]: https://github.com/tektoncd/community/blob/main/teps/0114-custom-tasks-beta.md

**Comment by lbernick** [comment]
linking https://github.com/tektoncd/pipeline/issues/5532 where some relevant discussion is occurring
