### ISSUE TITLE
how do I set pipelinerun wait for the previous pipelinerun execution to complete

### ISSUE THREAD

**Issue by gsgs-libin** [tektoncd/pipeline#5485]
I want to set pipelinerun in serial, because the task in pipeline use the same pvc

**Comment by Yongxuanzhang** [comment]
Hi, could you elaborate your use cases? Why not put the tasks in the same pipeline if they have dependency?

**Comment by dibyom** [comment]
If I am reading this correctly, you have multiple runs of the same pipeline but they all need to share a single PVC that can only be mounted to one pod at a time. In that case, https://github.com/tektoncd/community/pull/818 might be what you need

**Comment by gsgs-libin** [comment]
@dibyom  yes,I use git-clone and build code task in pipeline, but the git-clone task will clean the pvc workspace, and the build code task will have some error.
![image](https://user-images.githubusercontent.com/22513159/190303662-1ccb760c-965b-4642-b87d-cc8bae9c424d.png)

**Comment by Yongxuanzhang** [comment]
Wonder if pipeline in pipeline is able to address this issue? 
https://github.com/tektoncd/community/blob/fc1dd1065a7325cee6b3df1b36f6bedb316d7d8d/teps/0056-pipelines-in-pipelines.md#tep-0056-pipelines-in-pipelines

**Comment by gsgs-libin** [comment]
In fact, there are two points to this problem：
1.How to control concurrency
2.How to solve multiple pipelineruns using the same pvc problem

Regarding the first point, it has not yet been resolved and needs to be seen in the subsequent update iterations。

Regarding the second point, I have implemented two solutions so far:
1.When creating a pipelinerun, use `volumeClaimTemplate` to create random PVCs
```shell
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: eve-php-pre-volumeclaimtemplate-
  namespace: tekton-run
spec:
  workspaces:
    - name: git-clone-workspace-random
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
```
2.If you use TriggerTemplate, then you can specify in `resourcetemplates` that workspace uses pvc's `subPath` capability,different directories can be created by `$(uid)`
```shell
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: trigger-template-eve-php-pre
  namespace: tekton-run
spec:
  params:
    - name: user-username
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: eve-php-pre-pipelinerun-
        namespace: tekton-run
      spec:
        workspaces:
          - name: git-clone-workspace
            persistentVolumeClaim:
              claimName: pvc-tekton
            subPath: pvc-$(uid)
```
