### ISSUE TITLE
Feedback/beta release for taskRun.spec.stepSpecs and taskRun.spec.sidecarSpecs

### ISSUE THREAD

**Issue by lbernick** [tektoncd/pipeline#5489]
This issue tracks bringing [step and sidecar overrides](https://tekton.dev/docs/pipelines/taskruns/#overriding-task-steps-and-sidecars) to beta, and any feedback on or issues with this feature.

We'll be renaming these fields to `stepSpecs` and `sidecarSpecs` in [v1](https://github.com/tektoncd/community/blob/main/teps/0096-pipelines-v1-api.md#api-changes) and can optionally do so as well if/when we enable this feature in v1beta1 without `enable-api-fields` set to alpha.

**Comment by skaegi** [comment]
If we can change the names here can we just use `steps` and `sidecars`. The `Specs` or `Overrides` word does not add anything and really is not making things less confusing about what you can and can't do.

**Comment by lbernick** [comment]
@skaegi This feature was actually renamed to `stepSpecs` and `sidecarSpecs` in the v1 API (https://github.com/tektoncd/community/blob/main/teps/0096-pipelines-v1.md#api-changes) for consistency with `taskRunSpecs` in PipelineRun

**Comment by skaegi** [comment]
I fully understand... wish that was just `taskRuns` too but admit the ship has sailed there. With that said I definitely think that `Specs` is better than `Overrides` and indeed more consistent.

**Comment by jimmyjones2** [comment]
@lbernick Think this is still an issue, can you remove lifecycle/rotten please?

**Comment by khrm** [comment]
Let's add this to the milestone for v0.61.0 @chitrangpatel @vdemeester

I wrongly pinged you guys in some other issue.

**Comment by chitrangpatel** [comment]
@khrm can we move this to the next milestone?

**Comment by chitrangpatel** [comment]
Removing a milestone from this issue. I think we can assign it as soon as it is picked up again.

**Comment by khrm** [comment]
@chitrangpatel This was already merged. So we can close this. https://github.com/tektoncd/pipeline/pull/8006/
/close
