### ISSUE TITLE
TEP-0111: Propagated Workspaces Migration to Beta

### ISSUE THREAD

**Issue by jerop** [tektoncd/pipeline#5505]
This issue tracks the migration of Propagated Workspaces to Beta, targeting [v0.44.0](https://github.com/tektoncd/pipeline/releases/tag/v0.44.0).

### Feature looking for Promotion

Propagated Workspaces

TEP: https://github.com/tektoncd/community/blob/main/teps/0111-propagating-workspaces.md

Docs: 
- https://github.com/tektoncd/pipeline/blob/main/docs/pipelineruns.md#propagated-workspaces
- https://github.com/tektoncd/pipeline/blob/main/docs/taskruns.md#propagated-workspaces

### Current Feature Version

`enable-api-fields: alpha`

### Raise Feature Version

`enable-api-fields: beta`

### Pipeline Release

[v0.40.0](https://github.com/tektoncd/pipeline/releases/tag/v0.40.0)

### Issues Reported by the Users

None yet (will update if issues are raised)

### Dogfooding

None yet (will update if we dogfood)

### Examples

- [Propagating Workspaces in PipelineRuns](https://github.com/tektoncd/pipeline/blob/main/examples/v1beta1/pipelineruns/alpha/propagating-workspaces.yaml)
- [Propagating Workspaces in TaskRuns](https://github.com/tektoncd/pipeline/blob/main/examples/v1beta1/taskruns/alpha/propagating_workspaces.yaml)
- [Propagating Workspaces in PipelineRuns with referenced resources](https://github.com/tektoncd/pipeline/blob/main/examples/v1beta1/pipelineruns/alpha/propagating_workspaces_with_referenced_resources.yaml)

**Comment by pritidesai** [comment]
@jerop to check with @chitrangpatel and assign it to him!

**Comment by jerop** [comment]
completed in https://github.com/tektoncd/pipeline/pull/6030 - thanks @chitrangpatel! 

tracking promotion to "stable" in https://github.com/tektoncd/pipeline/issues/6107

/close
