### ISSUE TITLE
Deprecate `TaskRef.Bundle` and `PipelineRef.Bundle` in favor of the bundles resolver

### ISSUE THREAD

**Issue by abayer** [tektoncd/pipeline#5514]
Relates to #4710 

With remote resolution coming out of `alpha` in v0.41.0, the legacy `taskRef.bundle` and `pipelineRef.bundle` syntax should be deprecated in favor of using the `bundles` resolver.

**Comment by vdemeester** [comment]
@abayer is it https://github.com/tektoncd/pipeline/pull/5131 ?

**Comment by abayer** [comment]
Basically, but I think it's worth doing it as a new PR, since I'm also going to change the legacy bundle syntax to be handled by the bundles resolver.
