### ISSUE TITLE
ExtractVariablesFromString likely contains a redundant variable

### ISSUE THREAD

**Issue by chitrangpatel** [tektoncd/pipeline#5521]
In the return of the function [ExtractVariablesFromString](https://github.com/chitrangpatel/pipeline/blob/732aed55d75e4b1024b1cedbe8022e868925fd0e/pkg/substitution/substitution.go#L241-L275), the boolean variable is redundant with the string slice that's returned (i.e. the bool is just len(stringslice) > 0).

**Comment by lbernick** [comment]
@chitrangpatel I'm going to close this issue but feel free to reopen if you're still working on it!
