### ISSUE TITLE
Extend the `Run` (`CustomRun`) interface to log retrieval

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/pipeline#5548]
### Feature request

Define a common interface for `CustomRun` controller implementors to expose logs specific to a resource.

### Use case

Enable `CustomRun` log visualisation through standard tools like Tekton CLI, Dashboard or even `kubectl`.

**Comment by afrittoli** [comment]
The first idea that comes to mind is to use a "logs" sub-resource, which would provide an interface consistent with `Pods` which are used for regular `Tasks`. The "logs" sub-resource is not available however for CRDs (see this [k8s feature request](https://github.com/kubernetes/kubernetes/issues/72637), and besides that log aggregation via API server may not be the most scalable solution.

An alternative could be a field in the status that provides a link to the logs for the resource - however how that link serves the logs would be down to the specific custom run controller implementation, as the location where to fetch the logs from may vary significantly depending on the custom controller.

**Comment by afrittoli** [comment]
Possibly related to https://github.com/tektoncd/pipeline/issues/4313 - even though this is something we could add after the beta as well.

**Comment by pritidesai** [comment]
@afrittoli to check if we still require this kind of feature in `CustomRun`. Thanks @afrittoli!
