### ISSUE TITLE
Add provenance-related data field in `Run.Status`

### ISSUE THREAD

**Issue by chuangw6** [tektoncd/pipeline#5550]
### Feature request

Related to https://github.com/tektoncd/pipeline/issues/5529
Add provenance related data into TaskRun/PipelineRun status

[`TaskRunStatusFields`](https://github.com/tektoncd/pipeline/blob/826d8a0317cd293669bce2a6fcce93287a7ed221/pkg/apis/pipeline/v1beta1/taskrun_types.go#L211) will be

```go
type TaskRunStatusFields struct {
  ...
  ProvenanceData *ProvenanceData
  ...
}
```

[`PipelineRunStatusFields`](https://github.com/tektoncd/pipeline/blob/826d8a0317cd293669bce2a6fcce93287a7ed221/pkg/apis/pipeline/v1beta1/pipelinerun_types.go#L419) will be
```go
type PipelineRunStatusFields sruct {
  ...
  ProvenanceData *ProvenanceData
  ...
}
```

with `ProvenanceData` struct:

```go
type ProvenanceData struct {
  ConfigSource *intoto.ConfigSource
  // In future, we can add more provenance-related fields here as needed that can 
  // be piped from pipeline side.
}
```

### Use case
Recently there is a clear requirement that the provenance needs to record the remote source information of the remote data in order to link the config file back to its origin. The commit sha for git resolver used at the moment of resolving the remote resource is the important information to record in the provenance when users only provide the branch/tag name for the resolver. Additionally, the url and the entrypoint (a path to a configuration file) are the source info to be recorded as well. 
- To record these data in a structured way, we use SLSA standard [`ConfigSource`](https://slsa.dev/provenance/v0.2#invocation.configSource) struct. And the data is piped from remote resolver's `ResolutionRequest`'s status as proposed in https://github.com/tektoncd/pipeline/issues/5529. 
- To give us the flexibility to add more provenance-related data into Run.Status, we aim to create the `ProvenanceData` type that is designed to wrap all the data needed including the `ConfigSource`.

Without having the structured type in `Run.Status` and `ResolutionRequest.Status`, the only way to achieve this is to passing the data through annotations, which has a couple of drawbacks.
- unstructured data
- hard to maintain and make changes in future if more provenance-related data is needed to be piped to Run object so that Chains can pick them up and record in the provenance
- implementation challenges: passing/spreading around annotation maps is not elegant as opposed to a structured&standardized data type.

### Data flow 
<img width="1220" alt="Screen Shot 2022-09-23 at 14 56 28" src="https://user-images.githubusercontent.com/30398455/192037995-d240e46c-e467-4d4e-997c-d35a39aa3159.png">

**Comment by chuangw6** [comment]
Inspired from the PR comments and the conversations with @wlynch and @dibyom. Thanks!

cc @abayer @vdemeester @jerop @lbernick.

Please comment in this issue if anyone has any thoughts/concerns/comments on this. Thank you!!!

**Comment by wlynch** [comment]
lgtm! You should sync with @ywluogg - there was a desire to record other types of provenance data for inputs/outputs of a Run that we probably want to sort out (maybe it also goes in this `Provenance` struct?)

Otherwise, slight bikeshed - `ProvenanceData` -> `Provenance`? I don't think the Data suffix adds much.

**Comment by ywluogg** [comment]
Seems like the configSource records the build provenance data. For recording the provenance of the artifacts, we are looking for `subjects` and `materials` in [`Statement`](https://github.com/in-toto/attestation/blob/main/spec/README.md#statement).

These provenance don't come from resolver, but instead coming from the artifacts' SHAs and URIs. I wonder if this provenance field is also considering including those provenances?

**Comment by chuangw6** [comment]
Synced with @ywluogg @wlynch @jagathprakash in the Chains WG meeting on Sep 29, 2022. We landed the idea that for now just start with having the `ConfigSource` field in the `Provenance`, but we're onboard with adding inputs (a.k.a materials) / outputs (a.k.a materials) mentioned in [Tep-109](https://github.com/tektoncd/community/blob/main/teps/0109-better-structured-provenance-retrieval-in-tekton-chains.md#using-run-status-to-generate-provenance-metadata) when we're ready. 

Thanks you all for sharing your thoughts in the meeting.
