### ISSUE TITLE
Replacements not applied to finally task workspaces

### ISSUE THREAD

**Issue by gigatesseract** [tektoncd/pipeline#5571]
For a finally task, the workspace subpath has a $(context.pipelineRun.name) field. This is used to create a unique folder for each pipelinerun.

# Expected Behavior
The name of the pipelinerun should be substituted for the workspace value

# Actual Behavior
The string `$(context.pipelineRun.name)` is taken literally and a folder with the name `$(context.pipelineRun.name)` is created / overwritten when the pipeline is run multiple times.

# Steps to Reproduce the Problem

1. Create a workspace
2. Create a hello world pipeline with a workspace. Pass the workspace with a subPath in a finally task.  Make sure the workspace subpath has context variable
3. Run the pipeline

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.11", GitCommit:"c6a2f08fc4378c5381dd948d9ad9d1080e3e6b33", GitTreeState:"clean", BuildDate:"2021-05-12T12:19:22Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.19) exceeds the supported minor version skew of +/-1
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
v0.35.1
```

Output of kubectl describe pod for a task in finally:
```
 /workspace/output from ws-wlxmx (rw,path="builds/polaris/$(context.pipelineRun.name)")
```

Output of kubectl describe pod for a task not in finally, in the same pipeline:
```
 /workspace/output from ws-jg4dr (rw,path="builds/polaris/managed-volume-pipeline-runjwjkn")
```

**Comment by abayer** [comment]
We explicitly do workspace replacement on non-`finally` tasks - https://github.com/tektoncd/pipeline/blob/99226de6ef1c3f14e38e9b8cbc1fe0e60753a079/pkg/reconciler/pipelinerun/resources/apply.go#L233-L235

But we don't do so for `finally` tasks. I'm not sure if this is an oversight or a deliberate decision.
