### ISSUE TITLE
Propagated Parameters for Finally Tasks

### ISSUE THREAD

**Issue by chitrangpatel** [tektoncd/pipeline#5588]
### Feature request

Implement propagated parameters for `Finally` tasks.

### Use case

Propagated parameters was implemented for `TaskRuns` and `PipelineRuns`. However, propagating for `finally tasks` was overlooked. This feature needs to run for `finally` tasks as wells since they are exactly like normal tasks, just run at the end of the pipeline.

**Comment by jerop** [comment]
Fixed in https://github.com/tektoncd/pipeline/pull/5593
