### ISSUE TITLE
CustomRun equivalents of FilterRunRef and FilterOwnerRunRef are needed

### ISSUE THREAD

**Issue by abayer** [tektoncd/pipeline#5659]
Stumbled across this today - `pkg/controller/filter.go` has functions that are used in custom task controllers to filter `Run`s for the desired `apiVersion` and `kind`, and we need equivalents of those for `CustomRun`.

cc @jerop

**Comment by XinruZhang** [comment]
/close
https://github.com/tektoncd/pipeline/pull/5822
