### ISSUE TITLE
Keep track of 'beta' features promotion after v1 release

### ISSUE THREAD

**Issue by JeromeJu** [tektoncd/pipeline#5663]
### Feature request

This issue tracks down the necessary updates to be made to the beta features for the promoted features before the v1 release. This issue occurred because there were time that v1 was not released but features had been promoted to beta.

- https://github.com/tektoncd/pipeline/pull/5540#discussion_r998301542
- https://github.com/tektoncd/pipeline/pull/5628
- https://github.com/tektoncd/pipeline/pull/5640

**Comment by JeromeJu** [comment]
TODO:
- add the following at workspaces.md 536
This is a beta feature in v1. The `enable-api-fields` feature flag [must be set to `"beta"`](./install.md)
for csi volume source to function in v1.

**Comment by lbernick** [comment]
@JeromeJu I'm a bit confused-- what action needs to be taken for these features? I think these features are in beta regardless of whether they are used in v1 or v1beta1 crds

**Comment by dibyom** [comment]
I think we should add all beta features to a table like we have for alpha features. It wasn't as important when we only had v1beta1 since beta features were just enabled by default. It is a bit more important now given that with v1 beta features are opt-in

**Comment by dibyom** [comment]
Remote resolution is another beta feature we should add

**Comment by jerop** [comment]
Opened https://github.com/tektoncd/pipeline/pull/6050 updating the docs for Propagated Parameters - no docs changes are needed for CSI Volumes and Projected Volumes.

Opened https://github.com/tektoncd/community/pull/944 to document the decision from the API working group.

**Comment by lbernick** [comment]
Closing since we now have a table tracking beta features.
