### ISSUE TITLE
`Contributor's Guide` link is not found

### ISSUE THREAD

**Issue by chengjoey** [tektoncd/pipeline#5667]
https://github.com/tektoncd/pipeline/blob/2ed31e90628c973b08c6faac1f6afa5361c9bd0d/CONTRIBUTING.md?plain=1#L36-L40

`doc-con-main.md` is not existed in website repository

**Comment by AlanGreene** [comment]
Thanks for raising this @chengjoey. The link should probably point to https://github.com/tektoncd/website/blob/main/content/en/docs/Contribute/_index.md since the old file was removed and this content has been reorganised.

This is published on the website at https://tekton.dev/docs/contribute/
