### ISSUE TITLE
Add example of build + deploy via helm pipeline

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/pipeline#567]
# Expected Behavior
Have an example of how to deploy to a target cluster via helm, based on https://andreafrittoli.me/2019/02/06/define-a-simple-cd-pipeline-with-knative/

# Actual Behavior
n/a

# Steps to Reproduce the Problem
n/a

# Additional Info

**Comment by afrittoli** [comment]
Assigned to @afrittoli

**Comment by dlorenc** [comment]
At some point we may want to split examples to a new repo. I'll write up a quick proposal here for it.

**Comment by yuxintong-github** [comment]
great!

**Comment by vdemeester** [comment]
@afrittoli what is the status of this one ? (we do have a build+deploy with helm on the go integration test, and something a tiny bit similar on the example I think)

**Comment by vdemeester** [comment]
I think we can close this one @afrittoli ?

**Comment by afrittoli** [comment]
Yes, it's fine to close. We might want to add a catalog one in future, but that's a different thing.
