### ISSUE TITLE
Tekton pipeline as knative serving build example

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/pipeline#568]
# Expected Behavior
As part of the hackathon I worked on developing a working example of a taskrun and a pipelinerun  that are defined as part of a configuration/build of a knative service.
The code is available at https://github.com/afrittoli/openstack-health/tree/knative.

This issue is about taking that code and bringing it into the build-pipeline repo as an example, as long as folks are interested into it.

# Actual Behavior

# Steps to Reproduce the Problem

1.  Deploy knative serving and tekton pipelines in the same k8s cluster
2.  Apply the cluster role from https://github.com/knative/serving/blob/master/third_party/config/pipeline/clusterrole.yaml modified for tekton
3.  Create namespace "dev", tasks, pipelines, secrets, ingress rules in the dev namespace
4. Make a change to the code and use the run_from_git.sh script to create/update the service and trigger a task/pipeline

# Additional Info

**Comment by afrittoli** [comment]
Assigned to @afrittoli

**Comment by bobcatfish** [comment]
btw @afrittoli you might find this end to end test in the serving repo relevant: https://github.com/knative/serving/blob/master/test/e2e/build_pipeline_test.go (which uses knative serving with a pipeline)

Having an example in this repo too would be useful - but i hope we can find a way to have it without bringing in knative/serving as a dependency here :thinking:

**Comment by vdemeester** [comment]
I am going to close this as knative/build is deprecated as well as the build part of the configuration spec of knative serving.

/close
