### ISSUE TITLE
Repeated error messages when a Cloud Events sink is configured

### ISSUE THREAD

**Issue by aruiz14** [tektoncd/pipeline#5683]
# Expected Behavior

Absence of error logs.

# Actual Behavior

The following error message is produced every time an event is produced:
```
{
  "severity": "error",
  "timestamp": "2022-10-25T09:07:48.433Z",
  "logger": "tekton-pipelines-controller",
  "caller": "cache/cacheclient.go:58",
  "message": "Unable to fetch client from context.",
  "commit": "40a438a",
  "knative.dev/controller": "github.com.tektoncd.pipeline.pkg.reconciler.taskrun.Reconciler",
  "knative.dev/kind": "tekton.dev.TaskRun",
  "knative.dev/traceid": "073c5d18-258f-44b6-8633-9f922f9ebe53",
  "knative.dev/key": "tekton-pipelines/ginkgo-action-phc96",
  "stacktrace": "github.com/tektoncd/pipeline/pkg/reconciler/events/cache.Get\n\tgithub.com/tektoncd/pipeline/pkg/reconciler/events/cache/cacheclient.go:58\ngithub.com/tektoncd/pipeline/pkg/reconciler/events/cloudevent.SendCloudEventWithRetries\n\tgithub.com/tektoncd/pipeline/pkg/reconciler/events/cloudevent/cloud_event_controller.go:143\ngithub.com/tektoncd/pipeline/pkg/reconciler/events.Emit\n\tgithub.com/tektoncd/pipeline/pkg/reconciler/events/event.go:64\ngithub.com/tektoncd/pipeline/pkg/reconciler/taskrun.(*Reconciler).finishReconcileUpdateEmitEvents\n\tgithub.com/tektoncd/pipeline/pkg/reconciler/taskrun/taskrun.go:295\ngithub.com/tektoncd/pipeline/pkg/reconciler/taskrun.(*Reconciler).ReconcileKind\n\tgithub.com/tektoncd/pipeline/pkg/reconciler/taskrun/taskrun.go:189\ngithub.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1beta1/taskrun.(*reconcilerImpl).Reconcile\n\tgithub.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1beta1/taskrun/reconciler.go:235\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20220818004048-4a03844c0b15/controller/controller.go:542\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20220818004048-4a03844c0b15/controller/controller.go:491"
}
```

# Steps to Reproduce the Problem

1. [Install Tekton](https://github.com/tektoncd/pipeline/releases). 
2. [Configure a Cloud Events sink](https://tekton.dev/docs/pipelines/install/#configuring-cloudevents-notifications).
3. Add some dummy `TaskRun` and observe the controller logs.

# Additional Info

- Kubernetes version: 1.23

  **Output of `kubectl version`:**

```
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.9", GitCommit:"c1de2d70269039fe55efb98e737d9a29f9155246", GitTreeState:"clean", BuildDate:"2022-07-13T14:19:57Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
v0.40.2
```

I suspect this happens due to #3862, when a Cloud Events Sink is configured but the experimental cloud events for `Run` objects are disabled (default).
From what I could see, the `cache.ToContext` function is only called [from `ReconcileKind` for `Run` objects](https://github.com/tektoncd/pipeline/blob/main/pkg/reconciler/run/run.go#L53). However, `SendCloudEventWithRetries` is trying to [retrieve this cache client](https://github.com/tektoncd/pipeline/blob/main/pkg/reconciler/events/cloudevent/cloud_event_controller.go#L142), which fails if the object being processed is not a `Run`.

I assume one of the fixes would be to store the cache client in the context of every kind reconciler, retrieving it conditionally to the kind being checked or maybe just removing the log error, but I'm afraid I'm not familiar with the code to decide which one should make it.

Thanks in advance!

**Comment by mike-serchenia** [comment]
the same issue

but with `send-cloudevents-for-runs: 'true'`
