### ISSUE TITLE
Cluster setup for upgrade test

### ISSUE THREAD

**Issue by JeromeJu** [tektoncd/pipeline#5689]
### Feature request

Kind cluster setup for the upgrade test would be preferred compared with the current setup which relies on GKE at https://github.com/tektoncd/pipeline/blob/d4c2f75e32a8657f486790da8d665019f5e0550b/test/e2e-tests-upgrade.sh#L32

Related: #5649
### Use case

The upgrade test could be run with local kind cluster setup.

**Comment by dibyom** [comment]
I think you should be able to follow a lot from @abayer 's excellent guide here: https://github.com/tektoncd/plumbing/blob/main/docs/kind-e2e.md

**Comment by dibyom** [comment]
(basically we need to put the initialize call within an if block)
