### ISSUE TITLE
Non-root Task Containers trying to run as root (uid=0)

### ISSUE THREAD

**Issue by mtcolman** [tektoncd/pipeline#5692]
# Expected Behavior
Having run this pipeline without issue on OpenShift-Pipelines 1.7.3, which uses:
 -  Tekton Pipelines: v0.33.2
 -  Tekton Triggers: v0.19.0
 -  Tekton Chains (tech-preview): v0.8.0
 -  Tekton Hub (tech-preview): v1.7.3
 -  Pipelines as Code (tech-preview): v0.5.10

I have then tried upgrading to OpenShift-Pipelines 1.8.0, which uses:
 -  Tekton Pipelines: v0.37.4
 -  Tekton Triggers: v0.20.2
 -  Tekton Chains (tech-preview): v0.9.0
 -  Tekton Hub (tech-preview): v1.8.0
 -  Pipelines as Code (tech-preview): 0.10.2

My pipeline no longer runs (and I'm using the same pipeline-run).

# Actual Behavior
It appears the pipeline is trying to run the first four task containers as `runAsUser: 0` despite the fact I've not requested this. I then see this error, and this is the bit that makes me believe they are trying to be run as root `spec.containers[0].securityContext.runAsUser: Invalid value: 0: running with the root UID is forbidden`.

This is the task log:
```
failed to create task run pod "simple-page-pipeline-74cetx-depcheck-scan": pods "simple-page-pipeline-74cetx-depcheck-scan-pod" is forbidden: 

unable to validate against any security context constraint: [

provider "anyuid": Forbidden: not usable by user or serviceaccount, 
provider "pipelines-scc": Forbidden: not usable by user or serviceaccount, 
provider "ibm-restricted-scc": Forbidden: not usable by user or serviceaccount, spec.containers[0].securityContext.runAsUser: Invalid value: 0: running with the root UID is forbidden, 
provider "ibm-anyuid-scc": Forbidden: not usable by user or serviceaccount, 
provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount, 
provider "ibm-anyuid-hostpath-scc": Forbidden: not usable by user or serviceaccount, 
provider "hostnetwork": Forbidden: not usable by user or serviceaccount, 
provider "hostaccess": Forbidden: not usable by user or serviceaccount, 
provider "ibm-anyuid-hostaccess-scc": Forbidden: not usable by user or serviceaccount, 
provider "node-exporter": Forbidden: not usable by user or serviceaccount, 
provider "ibm-privileged-scc": Forbidden: not usable by user or serviceaccount, 
provider "privileged": Forbidden: not usable by user or serviceaccount

]. Maybe missing or invalid Task tekton-pipelines/depcheck-scan
```

I use this in my pipeline-run:
```
  serviceAccountName: pipelinerunner
  taskRunSpecs:
    - pipelineTaskName: source-to-image-test
      taskServiceAccountName: pipelinesource
```

My first four tasks should all be using `pipelinerunner` (which is aligned to run via restricted SCC, whereas `pipelinesource` is aligned to run via anyuid SCC - and used an a latter task that needs to run as root)). Instead they all failed with the error shown above.

The error message appears to show the task didn't try and use restricted SCC, but instead tried the others, all of which aren't permitted to be used by user. The `ibm-restricted-scc` whilst not permitted, also wasn't a match, given that it thinks the task wants to run as root, and this SCC doesn't permit that.

# Steps to Reproduce the Problem

1. Create a pipeline where first task should run via restricted SCC and second task should run via anyuid SCC
2. Include serviceAccountName and taskRunSpecs in pipeline run to ensure correct serviceAccounts are aligned to tasks
3. Run pipeline

# Additional Info

- Kubernetes version:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"e29d58e5a549866f51d928fd49ae8b9ad457a71c", GitTreeState:"clean", BuildDate:"2022-08-15T06:34:42Z", GoVersion:"go1.17.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5+012e945", GitCommit:"3c28e7a79b58e78b4c1dc1ab7e5f6c6c2d3aedd3", GitTreeState:"clean", BuildDate:"2022-07-13T08:38:41Z", GoVersion:"go1.17.12", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

```
$ tkn version
Client version: 2020-04-01T10:57:38Z
Pipeline version: unknown
```

I don't specify any `securityContext` for my tasks, as I don't have need to specify anything for the tasks to work with restricted SCC.

I appreciate this is OpenShift-pipelines, but I wondered if the underlying issue is with tekton version. 

When I revert openshift-pipelines to 1.7.3, my pipeline works again.

**Comment by mtcolman** [comment]
Further testing has shown that the error in 1.8.0 only occurs when I include a git pipelineResource in the pipelineRun, pipeline and task. Without it (I can even have an image pipelineResource included and it uses the correct SA and SCC), it works fine.

**Comment by cp-samantha** [comment]
I can confirm this behavior and have noted that git pull container inside the task run is indeed being run with a securityContext with a runAs of UID 0. Does a git pull really require root? Following an upgrade, I've had to adjust the SCC of several SA's just to accommodate this change. As noted, these pipelines worked flawlessly without extra permissions until a recent upgrade.

**Comment by mtcolman** [comment]
@cp-samantha it's related to [this code](https://github.com/tektoncd/pipeline/blob/7de70f1c095a12c10e81932ab3b0e2268dd80ec5/pkg/apis/resource/v1alpha1/git/git_resource.go#L198). The pipelineResources are, for most of them, setting the `runAsUser: 0` which causes this problem. 

However, PipelineResource are deprecated and not really supported on OpenShift Pipelines, as stated [here](https://docs.openshift.com/container-platform/4.11/cicd/pipelines/op-release-notes.html#deprecated-features-1-8_op-release-notes).

I have therefore removed pipelineResources from my configuration and thus solved my issue.

**Comment by cp-samantha** [comment]
Thanks for the nudge in the right direction.

Some searching led me to this documentation which should help aid other folks in making similar transitions themselves:

https://github.com/tektoncd/pipeline/blob/main/docs/pipelineresources.md
