### ISSUE TITLE
Testcase TestGitResolver_API using non multi-arched images

### ISSUE THREAD

**Issue by kabhiibm** [tektoncd/pipeline#5703]
The Tekton Pipeline nightly job fails on dogfooding for **Power** due to a testcase :- `TestGitResolver_API`.

![image](https://user-images.githubusercontent.com/97608374/199189088-2d81df81-a47e-47e9-a0f0-c5b8eee70fb1.png)

On initial investigation we found that the testcase use images which are not multi-arched - [bitnami/memcached](https://github.com/tektoncd/pipeline/blob/99226de6ef1c3f14e38e9b8cbc1fe0e60753a079/test/git-resolver/gitea.yaml#L489) and [bitnami/postgresql](https://github.com/tektoncd/pipeline/blob/99226de6ef1c3f14e38e9b8cbc1fe0e60753a079/test/git-resolver/gitea.yaml#L575)

In addition, the base image `docker.io/bitnami/minideb:bullseye` , used to build above images itself is not a multi-arched images.

This will impact testrun in P & Z both.

We need find/build equivalent multi-arched images of `bitnami/memcached` and `bitnami/postgresql` that should be used in the testsuite.

cc @afrittoli , @basavaraju-g

**Comment by abayer** [comment]
Wonder if there's a way we can skip this test if we're on multiarch as a workaround?

**Comment by kabhiibm** [comment]
@abayer , the test can be skipped with https://github.com/tektoncd/pipeline/blob/main/test/multiarch_utils.go#L135-L153. 
But in place of skipping it, what is the test doing and if including opensource memcached and postgresql (which is multi-arched) in the testcase would work for the test case ?

**Comment by abayer** [comment]
This test is verifying that the git resolver's API approach works, using a Gitea instance that we spin up and configure locally to test against. I'd say we can skip it, since there's nothing arch-specific about the actual functionality we're testing, just the Gitea instance we spin up for the test. I'll open a PR.
