### ISSUE TITLE
0.41.0 new configmap: config-observability contains helm specific syntax

### ISSUE THREAD

**Issue by rphua** [tektoncd/pipeline#5707]
We are using our own custom helm chart to deploy new versions of tekton and in version 0.41.0 there is a new configmap named "config-observability" and in the example the following syntax is used: 

{{.Request.Method}}

and more of this in the same example.

By doing so helm will try to resolve this eventhough it is just an example. It would be nice if the entire example could be commented out

**Comment by abayer** [comment]
Whoops - I'll open a PR to get `config/resolvers/config-observability.yaml` more like the previously-existing `config/config-observability.yaml`, which doesn't contain the relevant lines that are causing this problem.
