### ISSUE TITLE
Array indexing  for v1beta1

### ISSUE THREAD

**Issue by Ganiredi** [tektoncd/pipeline#5769]
### Feature request

Hi Team ,I come up with a problem where we are using v1beta1 and we are trying to use array indexing for default values to pass those in steps.As i am aware this feature in alpha,But my team was not a in place to upgrade it to newer version just because of one task that it requires.So as this feature is not available in v1beta1 ,is there any chance that could added in next resales ?

To get more insights into this i am leaving a slack thread that i discussed  https://tektoncd.slack.com/archives/CJ62C1555/p1668629030223269 

### Use case
The above slack thread will provide the use case details and it will benefit the users who are still depending the v1beta1.

**Comment by lbernick** [comment]
Also, https://github.com/tektoncd/pipeline/issues/5632 tracks allowing alpha features to be enabled individually instead of all or nothing
