### ISSUE TITLE
Indent missmatches after running `.hack/update-codegen.sh`

### ISSUE THREAD

**Issue by XinruZhang** [tektoncd/pipeline#5771]
### Feature request

`./hack/update-codegen.sh` should avoid using `tab` to indent.

### Use case

In https://github.com/tektoncd/pipeline/pull/5765, I updated Custom Task API Spec by adding new fields. Per https://github.com/tektoncd/pipeline/blob/main/hack/README.md, I ran `./hack/update-codegen.sh` to generate corresponding client code and pushed the PR.

However, our CI failed to build (`pull-tekton-pipeline-build-tests` failed) because of indent mismatches, see [the result](https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/5765/pull-tekton-pipeline-build-tests/1593237611424518144).

**Comment by abayer** [comment]
Yeah, I've seen this pop up but haven't reproduced it myself (though I'm running `update-codegen.sh` on my new M1 for the first time as we speak, so maybe I'll see it now?) and have never been able to figure out what's causing it.

**Comment by lbernick** [comment]
@XinruZhang did you find a workaround here? Running into the same issue on https://github.com/tektoncd/pipeline/pull/5945

**Comment by XinruZhang** [comment]
@lbernick  Unfortunately no, I tried to trace back to https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/staging/src/k8s.io/code-generator/cmd/client-gen/generators/scheme/generator_for_scheme.go#L157, but nothing wrong with it (it uses spaces instead of tabs)

Since we have a workaround  -- manually replace `tabs` with `spaces`, I decided not to invest more time on this issue.

**Comment by wlynch** [comment]
Pretty sure this is caused by the gofmt changes in Go 1.19. We're still using 1.18 https://github.com/tektoncd/plumbing/blob/244a3ab6ae4b64f05d3dfb2fd152fcd98232e543/prow/config.yaml#L1183
which is EOL - we should bump

**Comment by vdemeester** [comment]
@wlynch ah.. I updated the image but not the jobs 🤦🏼
