### ISSUE TITLE
Error handling on api-server unstable

### ISSUE THREAD

**Issue by huangjingfang** [tektoncd/pipeline#5778]
Hi, tekton team.
Recently I find a case in my cluser: some TaskRun occasionally stopped with status TaskRunResolutionFailed. and the reason is the api servers is unavaiable, such as 'connection refused' or 'the server is currently unable to handle the request'. in tekton, this TaskRun's status will be set to TaskRunResolutionFailed.

This produce a very strange behaver,  for example, one of my pipeline has completed, and the status was Succeed, and later on a new Reconcile occuried, and the staus of this task became to TaskRunResolutionFailed.  and no matter how many Reconcile event occures, the status will nerver be Succeed again.  

![image](https://user-images.githubusercontent.com/14036067/202977653-3d0c6769-f02f-4d72-a6bc-78eca10642d9.png)

# Expected Behavior
A task run would never change it's status once it has reached a final status

# Actual Behavior
A task run changed form success status to failed status

# Steps to Reproduce the Problem

this problem only happens when the cluster is not stable.

1. run an tekton pipeline
2. apiserver unavilable

# Additional Info

- Kubernetes version:  v1.19.11+k3s1

  **Output of `kubectl version`:**

  ```
  Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/amd64"}
  Kustomize Version: v4.5.7
  Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9+k3s1", GitCommit:"bead080d5e564206c23dcfbea3e6cf6f316e7f6c", GitTreeState:"clean", BuildDate:"2021-03-31T05:51:05Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
  WARNING: version difference between client (1.25) and server (1.19) exceeds the supported minor version skew of +/-1
  ```

- Tekton Pipeline version:

  **v0.17.3**

I wonder should we add a status check when we change the staus of Taskrun, maybe this could provent this problem

**Comment by AlanGreene** [comment]
v0.17.3 is a very old release, over 2 years old now. There have been many changes and improvements to Tekton Pipelines since. Do you see the same behaviour with a recent release?

**Comment by huangjingfang** [comment]
after updated to 0.43.0 version, the TaskRunResolutionFailed status has never appeared again. thx

/close
