### ISSUE TITLE
ClusterRoleBinding tekton-pipelines-resolvers has namespace set

### ISSUE THREAD

**Issue by pst** [tektoncd/pipeline#5795]
ClusterRoleBindings are not namesapce scoped, but the [`tekton-pipelines-resolvers` ClusterRoleBinding has a namespace set](https://github.com/tektoncd/pipeline/blob/c6ba630e38ed9766ee148b11c18fdc01a20dab5e/config/resolvers/201-clusterrolebinding.yaml#L19).

- Tekton Pipeline version:

This "namespaced" ClusterRoleBinding made it into the release.yaml of the v0.42.0 release.

**Comment by abayer** [comment]
Oops! Good catch.
