### ISSUE TITLE
Pipelinerun should not be failed if some of the results do not exist.

### ISSUE THREAD

**Issue by yuzp1996** [tektoncd/pipeline#5802]
# Expected Behavior
Pipelinerun should not be failed if some of the results do not exist. It is more like a warning but not an error. 

# Actual Behavior
If any of results in pipelineRun do not exist, pipelineRun will be fail.

# Steps to Reproduce the Problem

1.  Deploy pipeline with latest commit
2. Apply task pipeline and pipelinerun  to cluster
```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: unset-result-pipeline
spec:
  tasks:
    - name: unset
      taskRef:
        name: unset-result-task
  results:
    - name: sum
      description: the sum of all three operands
      value: $(tasks.unset.results.sum)
    - name: unset
      description: the sum of everything
      value: $(tasks.unset.results.unset)
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: unset-result-task
spec:
  results:
    - name: sum
      description: the sum of the first and second operand
    - name: unset
      description: the unset of the first and second operand
  steps:
    - name: add
      image: alpine:latest
      script: |
        #!/bin/sh
        echo -n "sum" | tee $(results.sum.path) ;

---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: unset-pipeline-run-
spec:
  pipelineRef:
    name: unset-result-pipeline
```
3. Check pipelineRun status

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/23007448/204091977-59abaa6c-ffd6-49d6-a25e-ad4c0ecf085f.png">
<img width="894" alt="image" src="https://user-images.githubusercontent.com/23007448/204092024-4ce63e47-f98d-418f-bc72-4dabffcd4fcc.png">

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:38:19Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:
```devel```
I deploy pipeline with commit b3e4f35712fca02, which is the latest commit.

**Comment by Yongxuanzhang** [comment]
Hi @yuzp1996 again thanks for raising this issue and I'm happy to discuss. I think this behaviour is expected. Since you want to refer a result in pipeline but it doesn't exist (the result is not emitted). This seems like an error that needs to fixed by how we define the pipeline, task or how the results are emitted?

I may be wrong. Feel free to leave any suggestions! 
Thanks!

**Comment by vdemeester** [comment]
Hey @yuzp1996, agreeing with @Yongxuanzhang, this is an expected behavior. There is a [TEP](https://github.com/tektoncd/community/blob/main/teps/0048-task-results-without-results.md) discussing this a bit I think.

**Comment by Yongxuanzhang** [comment]
> Hey @yuzp1996, agreeing with @Yongxuanzhang, this is an expected behavior. There is a [TEP](https://github.com/tektoncd/community/blob/main/teps/0048-task-results-without-results.md) discussing this a bit I think.

Oh thanks! I remembered I saw it somewhere. TEP-48 is in progress and once it is implemented it should "fix" this issue as well. Since it will allow you to add default results to avoid the failure.

Again feel free to provide any suggestions. @yuzp1996

**Comment by yuzp1996** [comment]
Thanks for your reply! @Yongxuanzhang @vdemeester 

Since this is expected behaviour and TEP-48 will allow adding default results I will close this issue.
