### ISSUE TITLE
Handle PipelineRun conversion when `embedded-status` flag is set to "full" or "both"

### ISSUE THREAD

**Issue by JeromeJu** [tektoncd/pipeline#5813]
This issue aims point out the needs to handle PipelineRunStatus conversion when embedded-status flag is set to "full" or "both". It tracks the information loss depending on `embedded-status` flag when converting ChildReferences to `TaskRuns` and `Runs` status. Specifically in the case where:
- Users creates a v1 PipelineRun CRD without `TaskRuns`/ `Runs` but with `ChildReferences`, converted to v1beta1
- Since there is no way converting `ChildStatusReference` to `TaskRuns` / `Runs`, the information would get lost

Local tests results following the above procedures are provided to determine the behaviours of the conversion

- [ ] This is to be done by the time we **swap the storage version from `v1beta1` to `v1`** according to the findings at https://github.com/tektoncd/pipeline/issues/5813#issuecomment-1332503027

- [ ] Come up with a decision to move forward
   - return an error if embedded status is set to "full" or "both" instead of attempting to convert, https://github.com/tektoncd/pipeline/issues/5355 is relatable
   - Serializing `TaskRuns` and `Runs` to the annotations when converting up to v1 and deserializing it when converting down.

- [ ] https://github.com/tektoncd/pipeline/pull/5797#discussion_r1034916796 needs to be resolved once the decision is made

Thanks to @lbernick spotting this at https://github.com/tektoncd/pipeline/pull/5797#discussion_r1034913730, pointing out that without the reconciler logics processing the `embedded-status` flag.

Thanks for the discussion cc @abayer @lbernick And also many thanks to @XinruZhang for the pointers at the storage version concerns and the reconciler logics on the findings!

**Comment by JeromeJu** [comment]
Findings:

- Embedded status: full:
  - 
  
 ```
 ± |fix-pr-status-conversion → origin {6} U:2 ?:2 ✗| → k get pipelineruns.v1beta1.tekton.dev/pipelinerun-test-embedded -o yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: "2022-11-30T17:19:41Z"
  generation: 1
  labels:
    tekton.dev/pipeline: pipelinerun-test-embedded
  name: pipelinerun-test-embedded
  namespace: default
  resourceVersion: "33376173"
  uid: 0bf519dd-1ede-4304-8938-8716c8a1da36
spec:
  pipelineSpec:
    tasks:
    - name: echo-good-morning
      taskSpec:
        metadata:
          labels:
            app: example
        spec: null
        steps:
        - image: ubuntu
          name: echo
          resources: {}
          script: |
            #!/usr/bin/env bash
            echo "Good Morning!"
  serviceAccountName: default
  timeout: 1h0m0s
status:
  childReferences:
  - apiVersion: tekton.dev/v1beta1
    kind: TaskRun
    name: pipelinerun-test-embedded-echo-good-morning
    pipelineTaskName: echo-good-morning
  completionTime: "2022-11-30T17:19:46Z"
  conditions:
  - lastTransitionTime: "2022-11-30T17:19:46Z"
    message: 'Tasks Completed: 1 (Failed: 0, Cancelled 0), Skipped: 0'
    reason: Succeeded
    status: "True"
    type: Succeeded
  pipelineSpec:
    tasks:
    - name: echo-good-morning
      taskSpec:
        metadata:
          labels:
            app: example
        spec: null
        steps:
        - image: ubuntu
          name: echo
          resources: {}
          script: |
            #!/usr/bin/env bash
            echo "Good Morning!"
  startTime: "2022-11-30T17:19:41Z"
  ```

**Comment by JeromeJu** [comment]
- `minimal` - Just populate `status.childReferences`, not `status.taskRuns` or `status.runs`.
- `both` - Populate `status.childReferences` as well as `status.taskRuns` and `status.runs`.

**Comment by JeromeJu** [comment]
Embedded status:
- `full` - The current default behavior of populating `status.taskRuns` and `status.runs`, without populating `status.childReferences`.
```
± |fix-pr-status-conversion → origin {6} U:2 ?:2 ✗| → k get pipelineruns.v1beta1.tekton.dev/pipelinerun-test-embedded -o yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: "2022-11-30T17:24:26Z"
  generation: 1
  labels:
    tekton.dev/pipeline: pipelinerun-test-embedded
  name: pipelinerun-test-embedded
  namespace: default
  resourceVersion: "33378985"
  uid: 9f984f5e-a9e5-453d-b267-81acb1b15a91
spec:
  pipelineSpec:
    tasks:
    - name: echo-good-morning
      taskSpec:
        metadata:
          labels:
            app: example
        spec: null
        steps:
        - image: ubuntu
          name: echo
          resources: {}
          script: |
            #!/usr/bin/env bash
            echo "Good Morning!"
  serviceAccountName: default
  timeout: 1h0m0s
status:
  completionTime: "2022-11-30T17:24:32Z"
  conditions:
  - lastTransitionTime: "2022-11-30T17:24:32Z"
    message: 'Tasks Completed: 1 (Failed: 0, Cancelled 0), Skipped: 0'
    reason: Succeeded
    status: "True"
    type: Succeeded
  pipelineSpec:
    tasks:
    - name: echo-good-morning
      taskSpec:
        metadata:
          labels:
            app: example
        spec: null
        steps:
        - image: ubuntu
          name: echo
          resources: {}
          script: |
            #!/usr/bin/env bash
            echo "Good Morning!"
  startTime: "2022-11-30T17:24:26Z"
  taskRuns:
    pipelinerun-test-embedded-echo-good-morning:
      pipelineTaskName: echo-good-morning
      status:
        completionTime: "2022-11-30T17:24:32Z"
        conditions:
        - lastTransitionTime: "2022-11-30T17:24:32Z"
          message: All Steps have completed executing
          reason: Succeeded
          status: "True"
          type: Succeeded
        podName: pipelinerun-test-embedded-echo-good-morning-pod
        startTime: "2022-11-30T17:24:26Z"
        steps:
        - container: step-echo
          imageID: docker.io/library/ubuntu@sha256:4b1d0c4a2d2aaf63b37111f34eb9fa89fa1bf53dd6e4ca954d47caebca4005c2
          name: echo
          terminated:
            containerID: containerd://ac17e55a5054deffc0fc3e12e4a5019ba9ab104718d1b790e595e02f8c60b05a
            exitCode: 0
            finishedAt: "2022-11-30T17:24:32Z"
            reason: Completed
            startedAt: "2022-11-30T17:24:32Z"
        taskSpec:
          steps:
          - image: ubuntu
            name: echo
            resources: {}
            script: |
              #!/usr/bin/env bash
              echo "Good Morning!"
```

**Comment by JeromeJu** [comment]
Looking at https://github.com/tektoncd/pipeline/blob/main/pkg/reconciler/pipelinerun/pipelinerun.go#L1299-L1302

**Comment by JeromeJu** [comment]
V1 PR yaml:
```
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: pipelinerun-test-embedded
spec:
  pipelineSpec:
    tasks:
      - name: echo-good-morning
        taskSpec:
          metadata:
            labels:
              app: "example"
          steps:
            - name: echo
              image: ubuntu
              script: |
                #!/usr/bin/env bash
                echo "Good Morning!"
                ```

**Comment by afrittoli** [comment]
Even after we flip the default for the flag or remove the flag, there may still be `v1beta1.PipelineRuns` in clusters with full status. Given that usually users need to garbage collect `PipelineRuns`, this is probably not very likely, so what we could do is add to the release notes that upgrading to a version with `v1` storage would lose the full status there.

Alternatively, we could do the same that we do for other removed fields, i.e. store them as annotations on `v1` resources, so that someone uses a `v1beta1` client to fetch the resource from a Tekton instance with `v1` storage, the full status can still be restored.

**Comment by JeromeJu** [comment]
The reconciler logics need to be updated once swapping the storage version to v1 to make sure:
- the resources being correctly converted from v1beta1 to v1 regardless of feature flags of `embeddedStatus`
- the controller behaviour of accepting `pipelineRunStatus` with `embeddedStatus`that are changed back and forth from `full` and `minimal`

:pray: Thanks again for the guidance here from Andrea and Lee https://github.com/tektoncd/pipeline/pull/5797#discussion_r1038176920
https://github.com/tektoncd/pipeline/pull/5797#discussion_r1038208069

**Comment by JeromeJu** [comment]
Discussed offline and in the WG as well. And many thanks to Andrew, Andrea, Dibyo and Xinru 🙏 .

Currently the approach moving forward is to serialize the `status.taskRuns` and `status.runs` into annotations when converting up from v1beta1 to v1.
