### ISSUE TITLE
TEP-0114: Remove the feature flag `custom-task-version` in release v0.47.0

### ISSUE THREAD

**Issue by XinruZhang** [tektoncd/pipeline#5837]
Remove the feature flag `custom-task-version` in release `v0.47.0`, which means we stop supporting `v1alpha1.Run` anymore.

**Background**

As proposed in [TEP-0114](https://github.com/tektoncd/community/blob/main/teps/0114-custom-tasks-beta.md#new-feature-flag-custom-task-version), the default value of `custom-task-version` is set to `v1alpha1` in the first release, approximately v0.43.0, then we switch it to `v1beta1` in v0.44.0 (which is tracked by https://github.com/tektoncd/pipeline/issues/5836), then eventually remove it in release v0.47.0.

cc @jerop @abayer

**Comment by pritidesai** [comment]
@XinruZhang any updates on this one?

**Comment by XinruZhang** [comment]
Thank you @pritidesai, yes this is on my plate for this release :)
