### ISSUE TITLE
TEP-0114: Custom Tasks Beta - Future Work

### ISSUE THREAD

**Issue by jerop** [tektoncd/pipeline#5863]
In [TEP-0114: Custom Tasks Beta][tep-0114], we proposed migrating `Custom Tasks` to beta.  

This is an overarching issue to track the work after the promotion of `Custom Tasks` to beta.

- [x] https://github.com/tektoncd/pipeline/issues/5861
- [x] https://github.com/tektoncd/pipeline/issues/5836
- [x] https://github.com/tektoncd/pipeline/pull/6040
- [x] https://github.com/tektoncd/pipeline/issues/5837
- [x] https://github.com/tektoncd/pipeline/issues/6498

[tep-0114]: https://github.com/tektoncd/community/blob/main/teps/0114-custom-tasks-beta.md

**Comment by afrittoli** [comment]
The only part left for v0.44 seems to be " Wait Custom Task updates in v0.44" - is that addressed in v0.44 or do we need to move that to v0.45?

**Comment by pritidesai** [comment]
@lbernick to check if this can be assigned to @XinruZhang, We have started releasing 0.44, moving this to next milestone!

**Comment by XinruZhang** [comment]
Ah ok, somehow I missed this thread 🤦‍♀️ and was OOO yesterday.  Thanks for the comment @afrittoli and @pritidesai.

PR is ready! https://github.com/tektoncd/pipeline/pull/6040

**Comment by XinruZhang** [comment]
@jerop  would you mind crossing the last item as https://github.com/tektoncd/pipeline/pull/6040 is merged, thanks~

**Comment by pritidesai** [comment]
@jerop to confirm if we can close this. thanks!
