### ISSUE TITLE
Consider removing dockercfg from examples/v1/taskruns/no-ci/pull-private-image.yaml

### ISSUE THREAD

**Issue by JeromeJu** [tektoncd/pipeline#5867]
This issue tracks the test examples in `examples/v1/taskruns/no-ci/pull-private-image.yaml`. We need to decide if we really need to commit the dockercfg given that this test/example is not even being run on CI. More comments might be necessary for this. And if not, to remove it from the examples.

This shall also apply to the example in v1beta1.

_Originally posted by @dibyom in https://github.com/tektoncd/pipeline/pull/5579#discussion_r1044885640_

**Comment by jerop** [comment]
@JeromeJu please add more details/context

/kind misc

**Comment by pritidesai** [comment]
@JeromeJu please add more details as requested. @dibyom to check with @JeromeJu

**Comment by lbernick** [comment]
I think the TODO is just to remove this line: 
https://github.com/tektoncd/pipeline/blob/add97eae68d2f1ca131163645f0ca37913090494/examples/v1/taskruns/no-ci/pull-private-image.yaml#L27

/help wanted
