### ISSUE TITLE
Cancelling a PipelineRun that is already running when new one is triggered

### ISSUE THREAD

**Issue by daniyalsuri6** [tektoncd/pipeline#5868]
The question is for pipeline cancelation: a PipelineRun triggered by EventListener (let's say it's testing a github PR). To cancel the previous PipelineRun (still running) when another PipelineRun of the same type was triggered, is there some native way using special parameters?

Use Case/ Expected Behaviour:

- Developer pushes to PR (PipelineRun triggered through event Listener)
- Developer again pushes to the same PR (previous PR PipelineRun should cancel in favour of the new one that is triggered through the new push)

/kind question
/kind feature

**Comment by AlanGreene** [comment]
See https://github.com/tektoncd/community/blob/main/teps/0120-canceling-concurrent-pipelineruns.md and related issues for current work in progress on concurrency controls.

**Comment by daniyalsuri6** [comment]
Thank you @AlanGreene for the information. As per the threads is it possible to use to experimental feature of concurrency for now? do I need to update my tekton-pipelines to the latest version for it?

**Comment by AlanGreene** [comment]
You can check out the experimental [concurrency](https://github.com/tektoncd/experimental/tree/main/concurrency) and [workflows](https://github.com/tektoncd/experimental/tree/main/workflows) projects. Bear in mind that they are currently experimental and may change in breaking ways.

Feedback is always welcome and can be added via issues / discussions, joining us on Slack, or at the Workflows working group meetings: https://github.com/tektoncd/community/blob/main/working-groups.md#workflows
