### ISSUE TITLE
Cleanup `isRunRetriable` in the release `v0.47.0`

### ISSUE THREAD

**Issue by XinruZhang** [tektoncd/pipeline#5870]
In the release `v0.47.0`, we plan to fully remove the support for `v1alpha1.Run` as proposed in [TEP-0114](https://github.com/tektoncd/community/blob/main/teps/0114-custom-tasks-beta.md#new-feature-flag-custom-task-version).

[`isRunRetriable`](https://github.com/tektoncd/pipeline/pull/5844/files#diff-39d9baa708e379638f742c8b9fd36d9d15c64c3386de958b5a3f309ca8fa037aR206) exists only to support the retries function in `v1alpha1.Run`. Therefore we need to clean that function up  after fully deprecating `v1alpha1.Run` in the release `v0.47.0`.

Related issue: https://github.com/tektoncd/pipeline/issues/5837, https://github.com/tektoncd/pipeline/issues/5810

**Comment by pritidesai** [comment]
@XinruZhang are we good with the current milestone on this one? thanks!

**Comment by XinruZhang** [comment]
Thank you @pritidesai, yes we need this one in the current milestone, will do
