### ISSUE TITLE
cleanup: remove `io/ioutil`

### ISSUE THREAD

**Issue by my-git9** [tektoncd/pipeline#5874]
The package about `io/ioutil` has been deprecated from go 1.16: https://go.dev/doc/go1.16#ioutil
We should remove it for go version 1.18 which used by tekton/pipeline.
We can clean up by directory in batches, like:https://github.com/tektoncd/pipeline/pull/5864

**Comment by lbernick** [comment]
I don't see any more usage of "io/ioutil" outside of our vendor directory so I'm going to go ahead and close-- thanks @my-git9 for your contributions! Feel free to reopen if there's something I missed.
