### ISSUE TITLE
Go Readability Improvement: Avoid Comparing Error Strings in Unit Tests

### ISSUE THREAD

**Issue by XinruZhang** [tektoncd/pipeline#5882]
We should avoid using string comparison in Unit Tests, instead, consider using [`errors.Is()`](https://pkg.go.dev/errors#Is), which requires us to have predefined error types. 

Ref: this comment thread: https://github.com/tektoncd/pipeline/pull/5844#discussion_r1049795352

**Comment by bendory** [comment]
See, for example:
- https://testing.googleblog.com/2015/01/testing-on-toilet-change-detector-tests.html (comparing error strings is a change-detector test for errors)
- https://testing.googleblog.com/2014/05/testing-on-toilet-effective-testing.html
- https://go.dev/blog/go1.13-errors
