### ISSUE TITLE
Helm Chart to install Tekton Pipelines

### ISSUE THREAD

**Issue by bngsudheer** [tektoncd/pipeline#5886]
Is there an official Helm Chart to install Tekton Pipelines?

If not, will you consider accepting a contribution to create a Helm chart?

**Comment by jerop** [comment]
There's no official helm chart - but there were extensive discussions to create one in this issue: https://github.com/tektoncd/pipeline/issues/1542 (other requests for helm chart in https://github.com/tektoncd/pipeline/issues/5136, https://github.com/tektoncd/plumbing/issues/278)

There's an experimental helm chart that's not maintained: https://github.com/tektoncd/experimental/tree/main/helm

But there's another Tekton helm chart from the CDF that's better maintained: https://github.com/cdfoundation/tekton-helm-chart

**Comment by pritidesai** [comment]
@bngsudheer are you still available to help and maintain the helm charts in tektoncd repo?

/help wanted

**Comment by kahirokunn** [comment]
@pritidesai 
Will they currently accept a Helm chart if I create one?
