### ISSUE TITLE
Use a different serviceaccount for a task in a Pipeline

### ISSUE THREAD

**Issue by BlueCog** [tektoncd/pipeline#5892]
### Feature request

We are using `EventListener` (to catch Git webhooks) with an `TriggerTemplate` and a `Pipeline`

We'd like to be able to configure a different serviceaccount (or serviceaccountname) for specific tasks. It seems this is only possible with PipeleRuns and TaskRuns at the moment (if i'm reading the docs and issues correctly)

### Use case

We are not using PipeleRuns and TaskRuns in our environment (we rely on the EventListener and TriggerTemplate) and we would like to give for example the Task which pushes docker image's a different ServiceAccount.

**Comment by vdemeester** [comment]
Hey @BlueCog, using `TriggerTemplate` means you are still using `PipelineRun` or `TaskRun` (in you template, you define one of these). So anything that applies to `PipelineRun` or `TaskRun` still applies (especially [this](https://tekton.dev/docs/pipelines/pipelineruns/#mapping-serviceaccount-credentials-to-tasks) to be able to specify a serviceaccount for a specific task).

**Comment by BlueCog** [comment]
Thanks for the pointer vdemeester, this works!
