### ISSUE TITLE
Unified Error Package for Error Type across Implementation and Testing

### ISSUE THREAD

**Issue by JeromeJu** [tektoncd/pipeline#5897]
### Feature request
[Drafted]
Currently in the repo,  the testing and implementations are coupled and it would be better to decouple the implementation and testing when comparing the errors. 

### Use case

Unified error types/ messages could be referenced across both implementations and testing.

cc @XinruZhang @bendory  thanks for bringing this up for go readability.

_Please feel free to add any examples or details for the request._

**Comment by XinruZhang** [comment]
Ahh this is kind of duplicated with https://github.com/tektoncd/pipeline/issues/5882

**Comment by lbernick** [comment]
@JeromeJu do you have any examples here of where the codebase could use readability improvements? It sounds like this issue is for creating a package for error handling; are there frequently repeated functions that would benefit from refactoring?
