### ISSUE TITLE
Release pipeline fails koparse for branch release-v0.41.x

### ISSUE THREAD

**Issue by lbernick** [tektoncd/pipeline#5969]
# Expected Behavior

I can release a patch version of Pipelines

# Actual Behavior

Kick off release pipeline for release-v0.41.x; accept all defaults except release-as-latest

koparse fails with

```
Expected images did not match: Images ['gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/sidecarlogresults:0.41.1'] were expected but missing.
```

https://dashboard.dogfooding.tekton.dev/#/namespaces/default/pipelineruns/pipeline-release-run-tss4d?pipelineTask=publish-images&step=koparse

**Comment by afrittoli** [comment]
Hi @lbernick - backports today require applying to the cluster the version of the release pipeline that matches the version you're releasing. That's an issue that I hope to solve by switching to remote resources - which should allow us to point to the version of the release in pipeline in git that we need.

**Comment by lbernick** [comment]
@afrittoli would you mind elaborating a bit? Should we add a section to the release guide explaining how to apply the correct version of the release pipeline to the dogfood cluster? (Assuming there's some use of kustomize/other tools and it's not just a kubectl apply?)

We cherry-picked https://github.com/tektoncd/pipeline/pull/5942 to a few release branches; does this not do anything? Does this mean that our v0.43.1 release doesn't actually publish all the intended manifests?
