### ISSUE TITLE
Typo in error message

### ISSUE THREAD

**Issue by data-henrik** [tektoncd/pipeline#5983]
https://github.com/tektoncd/pipeline/blob/1f5980f8c8a05b106687cfa3e5b3193c213cb66e/pkg/reconciler/taskrun/resources/taskresourceresolution.go#L81-L94

I ran into this error message:
> Neither ResourseRef nor ResourceSpec is defined

It should be "ResourceRef"

**Comment by codeleongy** [comment]
Hi there, I am interested in fixing this bug, could you assign to me: )

**Comment by vdemeester** [comment]
@codeleongy if you comment `/assign` it should assign it to you automatically 😉 

/assign @codeleongy

**Comment by data-henrik** [comment]
/lifecycle frozen "it should be fixed for quality reasons"

**Comment by AlanGreene** [comment]
Looks like this was fixed in https://github.com/tektoncd/pipeline/pull/6184 which was first release in v0.46.0
/close

**Comment by aaron-prindle** [comment]
+1 @AlanGreene, this was fixed with https://github.com/tektoncd/pipeline/pull/6184
/close
