### ISSUE TITLE
Integration tests for changing feature flags

### ISSUE THREAD

**Issue by lbernick** [tektoncd/pipeline#5999]
When a cluster operator changes the value of a feature flag, or when they upgrade to a new Pipeline version that modifies the default value for a feature flag, this has the potential to affect running PipelineRuns. We don't have any tests for this as far I know.

One example of how this can cause problems is #5991, where a running PipelineRun fails to complete if `embedded-status` is modified during its execution (thanks @JeromeJu for spotting this problem!). There are other feature flags (disable-affinity-assistant, enable-api-fields, etc) that have the potential to interfere with running PipelineRuns, but we haven't tested out these interactions.

I'm not sure how problematic this is. I expect these changes happen infrequently, but operators should be able to smoothly upgrade tekton versions, and clusters that run a large volume of PipelineRuns will likely run into this problem. We are also planning to change the value of "disable-affinity-assistant" in the v1 release.

I'm also not sure of the best way to test for this. Modifying feature flags during unit tests is challenging, because our unit tests test one reconcile loop at a time. Inserting a flag change into unit tests means baking in assumptions about when during execution a flag flip would happen, and makes tests much more complicated. However, doing the same during integration tests also has challenges, because we run all integration tests at the same time on the same cluster. Maybe we could write some new integration tests that run on their own cluster?

**Comment by dibyom** [comment]
> I'm not sure how problematic this is. I expect these changes happen infrequently, but operators should be able to smoothly upgrade tekton versions, and clusters that run a large volume of PipelineRuns will likely run into this problem. We are also planning to change the value of "disable-affinity-assistant" in the v1 release.

I agree that these changes will be infrequent. So one option might be to declaring that changing values mid-flight will result in undefined behavior.
If we do decide to provide defined behavior here, we could "freeze" the config used for a particular run in the beginning of the run.

**Comment by afrittoli** [comment]
> > I'm not sure how problematic this is. I expect these changes happen infrequently, but operators should be able to smoothly upgrade tekton versions, and clusters that run a large volume of PipelineRuns will likely run into this problem. We are also planning to change the value of "disable-affinity-assistant" in the v1 release.
> 
> I agree that these changes will be infrequent. So one option might be to declaring that changing values mid-flight will result in undefined behavior. If we do decide to provide defined behavior here, we could "freeze" the config used for a particular run in the beginning of the run.

The only way I can imagine we could freeze the config, would be store in the status of the particular run, but I'm not sure we should go down this path. Perhaps declaring "undefined behaviour" like @dibyom suggested is a good way to handle this.

**Comment by lbernick** [comment]
SGTM, I'll open a PR.

**Comment by lbernick** [comment]
@afrittoli @dibyom I realized we now do actually store feature flags in taskrun/pipelinerun status via the provenance field. Is it worth updating the codebase to use the value of feature flags stored in the provenance field, if they are present, rather than always using the value from the configmap? @chuangw6 curious to hear your thoughts as well.

**Comment by chuangw6** [comment]
> This seems like a reason in favor of using the feature flags from provenance, not a reason against. 

+1

> Shouldn't we make sure the provenance reflects the flags that were actually used to execute the pipelinerun?

yes, we definitely need to make sure the data there reflects the actually flags being used. I will revise this with @chitrangpatel and get back here with updates.

**Comment by chitrangpatel** [comment]
I've been giving this a lot of thought and tried to prototype things a bit. The challenge with feature flags is as follows:

- Validation happens in two places: `webhook` and `reconciler`.
- If the feature flags are saved in the `status` of the taskrun/pipelinerun then when we validate a stand-alone pipelineSpec/taskSpec (particularly at the webhook stage), this status field is not accessible and so we cannot rely on the `status`.  The `status` idea would work if we were only validating at the reconciler level.
- This means that we need to rely on the `context`. Now, the challenge here is that the `webhook` and `controller` watches for updates to the `config map` and the `context` is updated when changes are detected (I think. Please correct me if I'm wrong). This means that we cannot rely on the context directly as well.

**Comment by lbernick** [comment]
@chitrangpatel thanks for the update, that's a great point. Just one clarification: Are the feature flags in provenance meant to reflect only the values used for the taskrun/pipelinerun, and not for the task/pipeline? And would it be worth creating a separate issue to figure out how feature flags in provenance can better reflect the execution of the pipelinerun, or do you think this issue is sufficient?

**Comment by chitrangpatel** [comment]
https://github.com/tektoncd/pipeline/issues/6797 continues this discussion from the provenance perspective.
