### ISSUE TITLE
Consider excluding third_party from ci jobs

### ISSUE THREAD

**Issue by Yongxuanzhang** [tektoncd/pipeline#6015]
In commit https://github.com/tektoncd/pipeline/tree/b27ec733a7debf40a31f9628bc749603963b8fbb we pull in the hashicorp libraries, and after running `hack/update-codegen.sh`, it will copy code into [third_party](https://github.com/tektoncd/pipeline/tree/main/third_party) folder and cause errors in our ci jobs.

Short term solution: remove hasicorp KMS support for trusted resources.
Long term solution: Exclude `third_party` from Pipeline's ci jobs (e.g. https://github.com/tektoncd/pipeline/pull/6012)

**Comment by pritidesai** [comment]
> IIRC, this was originally set up for license compliance as a safety net for source distribution in case the underlying dependency repos were deleted. [We also tar up the vendor folder as part of releases](https://github.com/tektoncd/pipeline/blob/bf26bfb35745b403ac8ca760068f4d102e441940/tekton/publish.yaml#L139-L152) which serves a similar purpose, and is more likely to stay up to date and be recognized by other Go tools.

Wouldn't that cause a bigger issue instead if we rely on a dependency repo which is deleted so carry it around in the vendor directory? I would instead think of changing the code base to not rely on that dependency. What is the best practice with GO 1.19 now? How about we just standardize on go.mod to lock the dependencies upto the commit level?

https://stackoverflow.com/questions/61547433/what-are-the-benefits-of-having-a-vendor-folder illustrates the benefits of vendor directory:

> Vendoring on the other hand, with or without Go modules, brings stronger guarantees as it enables to commit the dependencies next to the code. Thus even if the remote repository is no longer accessible (deleted, renamed, etc), you will still be able to build your project.

But the latest documentation on how to manage dependencies has not specifications of third_party or vendor directories.

**Comment by pritidesai** [comment]
Couple of more references:

https://github.com/golang/go/wiki/Modules#how-do-i-use-vendoring-with-modules-is-vendoring-going-away

> Older versions of Go such as 1.10 understand how to consume a vendor directory created by go mod vendor, as do Go 1.11 and 1.12+ when [module mode](https://github.com/golang/go/wiki/Modules#when-do-i-get-old-behavior-vs-new-module-based-behavior) is disabled. Therefore, vendoring is one way for a module to provide dependencies to older versions of Go that do not fully understand modules, as well as to consumers that have not enabled modules themselves.

**Comment by wlynch** [comment]
@pritidesai Not quite following, can you explain a bit more?

> Wouldn't that cause a bigger issue instead if we rely on a dependency repo which is deleted so carry it around in the vendor directory? I would instead think of changing the code base to not rely on that dependency. I would instead think of changing the code base to not rely on that dependency.

The kodata trick is less to do with dependencies at head and more to do with making sure we maintain compliance for already released artifacts. Some licenses like MPL-2.0 say you have to give users of binaries you distribute a way to get the source - bundling the source with the artifact ensures they always stick together (same for license redistribution) even if the repo they originally came from disappears.

> How about we just standardize on go.mod to lock the dependencies upto the commit level?

We're already doing this. IIUC the primary purpose of `third_party` is as a location to include licenses and code that need to be redistributed through kodata for license compliance.

`third_party` was not meant to be used for dependency management, and AFAIK it hasn't been - but I wasn't 100% confident if other usages of the directory snuck in over time. 🙃 (my sense based on code search is the answer is no)

**Comment by wlynch** [comment]
@afrittoli - Yes, most projects that use the default plumbing template will run [`go-licenses check`](https://github.com/tektoncd/plumbing/blob/c6cc7570d1254ac6796b08f20adcaf10a80d38a4/scripts/library.sh#L307) as part of presubmit.

**Comment by pritidesai** [comment]
Didn't intend to cause any panic but we might have to investigate this further.

MPL-2.0 license text has a list of secondary licenses:

```
1.12. "Secondary License"
    means either the GNU General Public License, Version 2.0, the GNU
    Lesser General Public License, Version 2.1, the GNU Affero General
    Public License, Version 3.0, or any later versions of those
    licenses.
```

@wlynch I am getting a little different output with `go-licenses`:

```
go-licenses report github.com/hashicorp/go-multierror
...
github.com/hashicorp/errwrap,Unknown,MPL-2.0
github.com/hashicorp/go-multierror,Unknown,MPL-2.0
```

Notice an `Unknown` along with `MPL-2.0`.

https://github.com/google/go-licenses#check

are we considering `Unknown` a normal scenario?

**Comment by lbernick** [comment]
I noticed we're using a version of go-licenses in plumbing that's a [few years old](https://github.com/tektoncd/plumbing/blob/c6cc7570d1254ac6796b08f20adcaf10a80d38a4/go.mod#L7), should we update?

**Comment by wlynch** [comment]
> MPL-2.0 license text has a list of secondary licenses:
> 
> ```
> 1.12. "Secondary License"
>     means either the GNU General Public License, Version 2.0, the GNU
>     Lesser General Public License, Version 2.1, the GNU Affero General
>     Public License, Version 3.0, or any later versions of those
>     licenses.
> ```
> 

That's a definition of what the MPL means when it refers to a secondary license.
My understanding is that is not saying the MPL is also bound by those secondary licenses. The MPL has additional obligations if you wish to distribute MPL code with one of those secondary licenses, but since Tekton uses Apache-2.0 (i.e. not in the set of secondary licenses) that shouldn't be in scope for us.

(if you want, there's always the option to reach out to CDF legal if you want a more authoritative opinion. DM me if you're interested - I can get you in touch).

---

> @wlynch I am getting a little different output with `go-licenses`:
> 
> ```
> go-licenses report github.com/hashicorp/go-multierror
> ...
> github.com/hashicorp/errwrap,Unknown,MPL-2.0
> github.com/hashicorp/go-multierror,Unknown,MPL-2.0
> ```
> 
> Notice an `Unknown` along with `MPL-2.0`.
> 
> https://github.com/google/go-licenses#check
> 
> are we considering `Unknown` a normal scenario?

Shouldn't be an issue - `Unknown` in this case isn't referring to a license type - that field is for the location URL of the license. It just means go-licenses can't find a reliable location for the license.

Digging a bit more, it also like that's a bug with go-licenses when used with a vendor folder. I created a new module without vendor and it worked fine:

```
$ go-licenses report  github.com/hashicorp/go-multierror
github.com/hashicorp/errwrap,https://github.com/hashicorp/errwrap/blob/v1.0.0/LICENSE,MPL-2.0
github.com/hashicorp/go-multierror,https://github.com/hashicorp/go-multierror/blob/v1.1.1/LICENSE,MPL-2.0
```
