### ISSUE TITLE
PipelineRun reconciler panics for a matrix parameter with an empty array value

### ISSUE THREAD

**Issue by abayer** [tektoncd/pipeline#6071]
# Expected Behavior

`Pipeline` validation should fail at creation time when a matrix parameter is set to an empty array.

# Actual Behavior

The `PipelineRun` reconciler will panic when attempting to create the planned tasks for a matrix with an empty array parameter, because the count of matrix combinations becomes 0 (the combination count is generated by multiplying the length of each of the matrix parameters together, and 0...well, yeah). The controller then crashes. The panic itself looks like this (line numbers may be slightly different, 'cos this crash was on a branch of mine):
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1dbebe6]

goroutine 264 [running]:
github.com/tektoncd/pipeline/pkg/reconciler/taskrun.ValidateResolvedTaskResources({0x2899fd0?, 0xc000ccf800?}, {0x0?, 0xc0005581f0?, 0x3?}, 0x3a37e40?, 0x0)
	github.com/tektoncd/pipeline/pkg/reconciler/taskrun/validate_resources.go:212 +0x46
github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun.(*Reconciler).reconcile(0xc0003b5680, {0x2899fd0, 0xc000bcdb60}, 0xc00057e000, 0xc000bcdb60?, 0xc000354af0)
	github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun/pipelinerun.go:599 +0x2c45
github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun.(*Reconciler).ReconcileKind(0xc0003b5680, {0x2899fd0, 0xc000bcda40}, 0xc00057e000)
	github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun/pipelinerun.go:249 +0x161e
github.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1beta1/pipelinerun.(*reconcilerImpl).Reconcile(0xc0001e4a00, {0x2899fd0, 0xc000bcd980}, {0xc00012d540, 0x19})
	github.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1beta1/pipelinerun/reconciler.go:235 +0x582
```

# Steps to Reproduce the Problem

1. Create a `PipelineRun` with a `Pipeline` (or `.spec.pipelineSpec`) containing a matrixed `PipelineTask` with an empty array value for one of its parameters.
2. Watch the `tekton-pipelines-controller` pod crash.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
n/a
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
v0.44.0
```

**Comment by pritidesai** [comment]
> Pipeline validation should fail at creation time when a matrix parameter is set to an empty array.

One can argue that an empty array is used by design to designate zero iteration of a `pipelineTask`. It really depends on the use case. Also, it is possible to have one of the matrix params empty.

Instead of throwing a validation error which will cause the entire pipeline to fail, I suggest to mark that `pipelineTask` as part of skipped tasks. This design will work in future when a matrix param is referencing an array result. An array result could be an empty array.
