### ISSUE TITLE
Skipped Integration Tests

### ISSUE THREAD

**Issue by chitrangpatel** [tektoncd/pipeline#6079]
While working on PR https://github.com/tektoncd/pipeline/pull/6072, I noticed that 5 `alpha` [integration tests](https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/6072/pull-tekton-pipeline-alpha-integration-tests/1620184025870110720) were skipped.

Of the five, two were because they require `embedded-status: full` and `enable-provenance-in-status: true`. However, the kind-e2e tests set the feature flags to specific values for all integration tests. Therefore, these tests are skipped as a result and could potentially lead us to merge broken code. 

I think this is surfacing now because we have many independent feature flags like `results-from, embedded-status, enable-provenance-in-status` etc. and some alpha features require one set of values while other alpha features could require a different value.

I think we require some restructuring of our integration tests. 

WDYT?

/kind bug

**Comment by Yongxuanzhang** [comment]
I think those tests need feature flags not set by the script could set them in the test itself like:
https://github.com/tektoncd/pipeline/blob/ea358a6e18fdbbbc540053a04dbbfc56f9ceebb3/test/trusted_resources_test.go#L435-L437
And reset the config after the test is done.

This is based on the tests are not running in parallel

**Comment by chitrangpatel** [comment]
Yes, I agree. That's what needs to happen. I needed to do that for larger results.

But as you can see, it is easy to miss and prone to errors. I was wondering if we should rethink the strategy where instead of having `requireAllGates or requireAnyGate` which can lead to skipping of tests, we explicitly set the feature flag that the test needs.

Again, just a thought. It might cause more issues than what I foresee at the surface level.

**Comment by Yongxuanzhang** [comment]
> Yes, I agree. That's what needs to happen. I needed to do that for larger results.
> 
> However, after the test is complete, we also need to unset those feature flags and set them back to what they were. Otherwise, tests that follow will get the feature flags that you set in the tests and[ it can break them](https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/6072/pull-tekton-pipeline-alpha-integration-tests/1620439049745469440). This is because the feature flags are applied to the namespace `tekton-pipelines` instead of `arendelle....`
> 
> But as you can see, it is easy to miss and prone to errors. I was wondering if we should rethink the strategy where instead of having `requireAllGates or requireAnyGate` which can lead to skipping of tests, we explicitly set the feature flag that the test needs and then set it back to default when that test is complete.
> 
> Again, just a thought. It might cause more issues than what I foresee at the surface level.

I think we are talking about the same solution. 😅 Set the flag and reset when that test is done.

**Comment by chitrangpatel** [comment]
One other thing I found is that in order to fix [the broken tests](https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/6072/pull-tekton-pipeline-alpha-integration-tests/1620439049745469440), I had to remove `t.Parallel()` so that it does not run in parallel with the other tests. This is because when my test updated the feature flags, it affected other tests running in parallel that would error when running along side mine.

**Comment by Yongxuanzhang** [comment]
> One other thing I found is that in order to fix [the broken tests](https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/6072/pull-tekton-pipeline-alpha-integration-tests/1620439049745469440), I had to remove `t.Parallel()` so that it does not run in parallel with the other tests. This is because when my test updated the feature flags, it affected other tests running in parallel that would error when running along side mine.

yeah, I also mentioned that in my previous comment. I think this is important.
>This is based on the tests are not running in parallel

**Comment by chitrangpatel** [comment]
I wanted to add that while this is doable for e2e tests, we cannot do this for example tests since all example tests will have the same feature flags for all.

I guess, my main point is if we think it's ok for this process to be as is or if we think it should be improved.
