### ISSUE TITLE
Cleanup for `PipelineRunStatus` Migration after `EmbeddedStatus` Feature Flag is removed

### ISSUE THREAD

**Issue by JeromeJu** [tektoncd/pipeline#6090]
This issue tracks the cleanup after v0.45 post the `EmbeddedStatus` feature flag is removed.

- [ ] Cleanup previous guards for `status.taskruns` or `status.runs` for `full` or `both` `embedded-status`
       - for example: https://github.com/tektoncd/pipeline/blob/ea358a6e18fdbbbc540053a04dbbfc56f9ceebb3/pkg/reconciler/pipelinerun/pipelinerun.go#L1404
- [ ] Remove `status.taskruns` and `status.runs` from the codebase
- [ ] Refactor the helper functions that has been cut after the removal of the feature flag as they might be combined
- [ ] Clean up the `pkg/status` package or not?

This was not cleaned up in v0.45 as now users might be in the progress of migrating off the `embedded-status` feature flag.

**Comment by JeromeJu** [comment]
I also noticed https://github.com/tektoncd/pipeline/pull/4850 for changes in `pkg/status`, I think these should be kept specifically for those who wants to populate `full`/ `both` like PipelineRunStatus? So probably I should not even rename the functions nor the test cases in `pkg/status`?

cc @abayer  could you help confirm my understanding on this, TY🙇‍♂️

**Comment by lbernick** [comment]
When we remove the feature flag, we're no longer populating those fields, so it doesn't make sense to have the helpers continue to read from them

**Comment by JeromeJu** [comment]
That makes sense, so shall we go ahead and delete the package `pkg/status`?

**Comment by lbernick** [comment]
Let's leave the helpers there, but they should only read from childreferences
