### ISSUE TITLE
TEP-0111: Propagated Workspaces Migration to Stable

### ISSUE THREAD

**Issue by jerop** [tektoncd/pipeline#6107]
This issue tracks the migration of Propagated Workspaces to Beta, targeting [v0.47.0](https://github.com/tektoncd/pipeline/releases/tag/v0.47.0).

### Feature looking for Promotion

Propagated Workspaces

TEP: https://github.com/tektoncd/community/blob/main/teps/0111-propagating-workspaces.md

Docs: 
- https://github.com/tektoncd/pipeline/blob/main/docs/pipelineruns.md#propagated-workspaces
- https://github.com/tektoncd/pipeline/blob/main/docs/taskruns.md#propagated-workspaces

### Current Feature Version

`enable-api-fields: beta`

### Raise Feature Version

`enable-api-fields: stable`

### Pipeline Release

[v0.40.0](https://github.com/tektoncd/pipeline/releases/tag/v0.40.0)

### Issues Reported by the Users

None yet (will update if issues are raised)

### Dogfooding

None yet (will update if we dogfood)

### Examples

- [Propagating Workspaces in PipelineRuns](https://github.com/tektoncd/pipeline/blob/main/examples/v1beta1/pipelineruns/alpha/propagating-workspaces.yaml)
- [Propagating Workspaces in TaskRuns](https://github.com/tektoncd/pipeline/blob/main/examples/v1beta1/taskruns/alpha/propagating_workspaces.yaml)
- [Propagating Workspaces in PipelineRuns with referenced resources](https://github.com/tektoncd/pipeline/blob/main/examples/v1beta1/pipelineruns/alpha/propagating_workspaces_with_referenced_resources.yaml)

**Comment by pritidesai** [comment]
@chitrangpatel are you available to work on this? This is targeted for 0.47, thanks!

**Comment by chitrangpatel** [comment]
Yes, I will be able to.

**Comment by jerop** [comment]
Done in https://github.com/tektoncd/pipeline/pull/6432, thanks @chitrangpatel!

/meow
/close
