### ISSUE TITLE
Refactor `getTaskRunCreations` to be explicit on getting TaskRuns

### ISSUE THREAD

**Issue by JeromeJu** [tektoncd/pipeline#6143]
The usage of [`getTaskRunCreations`](https://github.com/tektoncd/pipeline/blob/2da10fc5ff9d99571b6055bcb86aca12805cb9e0/pkg/reconciler/pipelinerun/pipelinerun_test.go#L161) in the pipelineRun reconciler test suite verifies implementation details (API calls) rather than the outputs we care about (TaskRuns themselves), making the tests harder to understand. This should be refactored to not rely on this.

_Originally posted by @lbernick in https://github.com/tektoncd/pipeline/pull/6135#discussion_r1101937678_
            

/kind cleanup

**Comment by Hussain0520** [comment]
Hey @JeromeJu is someone working on this?

**Comment by JeromeJu** [comment]
> Hey @JeromeJu is someone working on this?

@Hussain0520 there is not. Please feel free to self-assign:)
