### ISSUE TITLE
Feature to rerun task

### ISSUE THREAD

**Issue by Faraaaaaaaaaaaa** [tektoncd/pipeline#6152]
### Feature request
Why in tekton, we have not opportunity to rerun task in pipeline or just a task.  

### Use case
Many time's I need to rerun just last task in pipeline, and in tekton i need to rerun huge pipeline.
For example sometime's need some time for helm to be pushed after we pushed it or situation like this with docker images, we pushed it, but in next step we can't find in, couse some trable with registry and we need some second's to be relly be pushed

btw, thanks for tekton, it's really usefull and powerfull tool)

**Comment by chengjoey** [comment]
hi @Faraaaaaaaaaaaa ,here is a [retry]()https://github.com/tektoncd/pipeline/blob/main/docs/taskruns.md#specifying-retries that should be able to meet your needs

**Comment by jerop** [comment]
@Faraaaaaaaaaaaa are you looking for retry that @chengjoey shared? or is it on-demand retry upon failure? 

if the latter, there's some previous work by @ScrapCodes in https://github.com/tektoncd/community/pull/422 and https://github.com/tektoncd/community/pull/484 if you're interested in picking it up - can start by commenting on those PRs with your use cases

**Comment by Faraaaaaaaaaaaa** [comment]
Hi @jerop and @chengjoey, I think retry option is really good for my situtation. Thank's guy's. You are amazing :)
