### ISSUE TITLE
Migrate examples in documentation to use v1

### ISSUE THREAD

**Issue by lbernick** [tektoncd/pipeline#6154]
Most of our documentation uses v1beta1 versions of Task, TaskRun, Pipeline, and PipelineRun.
We should update our examples to use v1 versions, using our [existing migration guide](https://github.com/tektoncd/pipeline/blob/main/docs/migrating-v1beta1-to-v1.md).

**Comment by pritidesai** [comment]
Can we somehow `embed` examples from the `yaml` files instead of re-writing the entire `yaml` in a markdown? This can be done whenever it directly applies and might not work for all features.

What are we doing with the `v1beta1` resources? I would not recommend deleting them as most of the users are still using `v1beta1` and will continue to use for many more releases since `v1beta1` was our longest supported version. Is there anyway we can host both `v1` and `v1beta1` CRDs in our documentation?

**Comment by lbernick** [comment]
> Can we somehow `embed` examples from the `yaml` files instead of re-writing the entire `yaml` in a markdown? This can be done whenever it directly applies and might not work for all features.

Not sure-- could this be tackled separately?

> What are we doing with the `v1beta1` resources? I would not recommend deleting them as most of the users are still using `v1beta1` and will continue to use for many more releases since `v1beta1` was our longest supported version. Is there anyway we can host both `v1` and `v1beta1` CRDs in our documentation?

Great point! @geriom I wonder if we could do something similar to what you did showing multiple installation methods?

**Comment by geriom** [comment]
- We can embed code from the yaml files in the markdown files. I just opened a [PR](https://github.com/tektoncd/website/pull/523) to add a section explaining how. Instructions [preview here](https://deploy-preview-523--tekton.netlify.app/docs/contribute/doc-con-formatting/#embed-code-samples). Only samples below the markdown's directory are supported though.

- We can indeed use tabs to have ` v1beta1` and `v1` samples side by side. The link above also shows how to use tabs with code samples.

**Comment by chitrangpatel** [comment]
This is fantastic @geriom!! Once the above PR is merged, I can work on this.

**Comment by vdemeester** [comment]
I think this might get a bit tricky on some part of the doc. For example, on [`PipelineRun`](https://github.com/tektoncd/pipeline/blob/main/docs/pipelineruns.md), we list the fields ([here](https://github.com/tektoncd/pipeline/blob/main/docs/pipelineruns.md#configuring-a-pipelinerun)) — which can be a bit different from v1beta1 to v1.

That said, I think we need to up the "urgency" of this a bit. We have already 3/4 releases where `v1` is out and there is very little `v1` material in the documentation.

**Comment by chitrangpatel** [comment]
I will prioritize this for this week and try to open up a PR at the least.

**Comment by chitrangpatel** [comment]
Drafting a PR. https://github.com/tektoncd/pipeline/pull/6414

I've only done one file but wanted to gather thoughts before I take a similar approach to all other places.

1. For all of the examples in tasks.md, there was no difference between the v1 and v1beta1 api (I think). In this case:
  - should I just update `v1beta1 --> v1` ?
  - leave a comment in the yaml like `apiVersion: tekton.dev/v1 # or tekton.dev/v1beta1`?
  - or have two tabs with the same content except for the `apiVersion` field? This involves a lot of duplication.

**Comment by lbernick** [comment]
Closed in https://github.com/tektoncd/pipeline/pull/6414
