### ISSUE TITLE
Link inputs and outputs without using volumes

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#617]
# Expected Behavior

When a user wants to [link Pipeline Task outputs and inputs](https://github.com/tektoncd/pipeline/blob/master/docs/pipelines.md#from), this should:

* Not be significantly slower than executing a Pipeline where no outputs are linked.
* Not require external resources such as PVCs or GCS/S3 buckets

# Actual Behavior

There are currently two options for how outputs and inputs are linked:

* By default, when this happens, a PVC is created so that the content of the PVC serves as the output of a Task, which can then be provided as an input to the next Task via the volume
* Or [you can configure pipelines](https://github.com/tektoncd/pipeline/blob/master/docs/install.md#how-are-resources-shared-between-tasks) to use GCS to store outputs - this means they output data would be uploaded at the end of Task's execution, and downloaded to serve as input for the next

# Additional Info

* More details on the implementation [in the developer docs](https://github.com/tektoncd/pipeline/blob/master/docs/developers/README.md#how-are-resources-shared-between-tasks)
* Related but different issue: https://github.com/tektoncd/pipeline/issues/398

**Comment by bobcatfish** [comment]
One possible solution is to detect when this is happening, and schedule pods for Tasks with linked inputs/outputs onto the same nodes so they can share data directly on disk.

This would be a bit of a scheduling challenge; we may need to look into using a custom scheduler.

**Comment by dlorenc** [comment]
Hmm, I was sort of hoping that the k8s scheduler would be smart enough to allow us to schedule subsequent tasks on the same node as the previous one when there's a shared volume (in cases where this is possible). Maybe this is true and we just need to use the scheduler differently? If not a custom scheduler should do the trick.

**Comment by al3xisb** [comment]
Not sure about this one, probably because caching (read persistance) is a core concept of ci/cd architectures. But did you looked at [emptydir](https://kubernetes.io/docs/concepts/storage/volumes/#emptydir) ?

**Comment by bobcatfish** [comment]
These days the [affinity assistant](https://github.com/tektoncd/pipeline/blob/116fadd01482919acfb4fe9c17bca287dd6b4d36/docs/workspaces.md#specifying-workspace-order-in-a-pipeline-and-affinity-assistants) helps us a lot with this; also we are still trying to determine the fate of pipelineresources #1673
