### ISSUE TITLE
Issues running openapigen.sh with a different directory path 

### ISSUE THREAD

**Issue by EmmaMunley** [tektoncd/pipeline#6192]
# Expected Behavior

Running from different directory naming should not modify output.

If directory naming is different than  

~/go/src/github.com/tektoncd/pipeline 

Such as:
 ~/go/src/github.com/tekton/pipeline

Running `hack/update-openapigen.sh` should work without errors.

# Actual Behavior

Errors: 

End up replacing tektoncd with tekton file pkg/apis/pipeline/v1/openapi_generated.go:

For example:
/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1.CloudEventDeliveryState"

# Steps to Reproduce the Problem

1. Directory naming cd into: ~/go/src/github.com/tekton/pipeline 
2. Run `hack/update-openapigen.sh`
3. See changes in `openapi_generated.go`

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-25T19:35:11Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
Client version: 0.29.0
Pipeline version: devel
```

This was resolved when I changed my directory naming to  ~/go/src/github.com/tektoncd/pipeline

**Comment by vdemeester** [comment]
I think this is mainly due to some GOPATH assumption either in the script or in the openapi tooling 😓

**Comment by JeromeJu** [comment]
Thanks both @EmmaMunley and @lbernick for the time for this, setting `$GOPATH/src/github.com/tektoncd/pipeline/` will solve this issue.

related: https://github.com/tektoncd/pipeline/issues/6485
