### ISSUE TITLE
Tekton controller performance impacted by redundant existing and desired resource state difference calculation

### ISSUE THREAD

**Issue by rafalbigaj** [tektoncd/pipeline#6193]
## Expected Behavior

The existing and desired resource state difference should be calculated in the reconciler implementation only when debug logging is enabled.

The state comparison using `kmp.SafeDiff(existing.Status, desired.Status)` in the `reconcilerImpl.updateStatus` method is performed for debug logging purposes only and should not affect the reconciler performance in the production mode. The state difference should be calculated only when debug log level is enabled.

## Actual Behavior

The `reconcilerImpl.updateStatus` method contribution to overall reconciler CPU consumption happens to be extremely high for resources of significant size (> 30kB). Attached logs show the example of 66.5% CPU time spend on calculating state diff using `kmp.SafeDiff`, which is used only for debug logging.

| CPU Time | Code |
| --- | --- |
| 66.5%  | github.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1alpha1/run.(*reconcilerImpl).updateStatus.func1 at github.com/tektoncd/pipeline@v0.41.0/pkg/client/injection/reconciler/pipeline/v1alpha1/run/reconciler.go:330 |
| 66.5% | knative.dev/pkg/kmp.SafeDiff at knative.dev/pkg@v0.0.0-20221011175852-714b7630a836/kmp/diff.go:50 |

![image](https://user-images.githubusercontent.com/824894/218104206-a369f74c-30e8-45d1-8d51-aeabc5d663f3.png)

Related knative.dev/pkg issue: https://github.com/knative/pkg/issues/2677

## Steps to Reproduce the Problem

1. Create hundreds of Tekton PipelineRuns of significant size (> 30kB).
2. Observer `reconcilerImpl.updateStatus` method CPU consumption in Tekton controller.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:51:43Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.6+5658434", GitCommit:"eddac29feb4bb46b99fb570999324e582d761a66", GitTreeState:"clean", BuildDate:"2022-11-09T10:31:39Z", GoVersion:"go1.18.7", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.26) and server (1.24) exceeds the supported minor version skew of +/-1
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
0.45.0
```

**Comment by vdemeester** [comment]
Agreed 👍🏼

**Comment by vdemeester** [comment]
cc @tektoncd/triggers-maintainers @tektoncd/chains-maintainers @tektoncd/results-maintainers @tektoncd/operator-maintainers 
To check if you also want these perf. improvements in your projects 👼🏼
