### ISSUE TITLE
CI not catching updates to LICENSE files and api docs

### ISSUE THREAD

**Issue by dibyom** [tektoncd/pipeline#6210]
I wonder how is it possible that this delta is not caught by CI, it sounds like something is broken? @vdemeester wdyt?

_Originally posted by @afrittoli in https://github.com/tektoncd/pipeline/issues/6189#issuecomment-1435244240_
            
/kind bug

**Comment by lbernick** [comment]
Curious if there's a good way to check license files? It would involve diffing the entire third_party directory which I'm not sure whether or not is worth it. (Then again we diff the whole vendor directory so maybe it wouldn't take that long; or maybe someone who's better at shell scripting than I am knows a magic way of doing this :) )

**Comment by pritidesai** [comment]
> Curious if there's a good way to check license files?

What is involved in this kind of check? diffing third_party directory? Please elaborate

**Comment by vdemeester** [comment]
We do diff any "generated" files (from `go generate`, from `go mod vendor` , …), so we could definitely also check the `third_party` content. But, from my memory, I really thought we did already 🤔

**Comment by lbernick** [comment]
We don't diff third_party but on second thought adding it in is totally reasonable-- working on this in https://github.com/tektoncd/pipeline/pull/6342
