### ISSUE TITLE
update knative 1.8 and 1.9

### ISSUE THREAD

**Issue by pritidesai** [tektoncd/pipeline#6224]
`knative.dev/pkg` 1.8 and 1.9 were recently updated to include a performance fix which helped reduced the CPU usage by 61% and memory usage by 44% for huge pipelines. Pipelines 0.41 through 0.45 depends on knative 1.8 and main depends on knative 1.9. Update tekton controllers to reflect a change in knative pkg.

| Release | Knative Version | PR |  Status |
|---|---|---|----|
| release-v0.41.x | 1.8 |  https://github.com/tektoncd/pipeline/pull/6201 |  Done |
| release-v0.42.x | 1.8 | https://github.com/tektoncd/pipeline/pull/6202 |  Done |
| release-v0.43.x | 1.8 | https://github.com/tektoncd/pipeline/pull/6203 |  Done |
| release-v0.44.x | 1.8 | https://github.com/tektoncd/pipeline/pull/6226 |  Done |
| release-v0.45.x | 1.8 | https://github.com/tektoncd/pipeline/pull/6204 |  Done |
| main | 1.9 | https://github.com/tektoncd/pipeline/pull/6256 | Done |

**Comment by Yongxuanzhang** [comment]
pr for 0.44 https://github.com/tektoncd/pipeline/pull/6226

**Comment by liangyuanpeng** [comment]
Seems like this issue can be closed.

**Comment by vdemeester** [comment]
There is still 2 cherry-pick in progress

**Comment by vdemeester** [comment]
All is done now.
