### ISSUE TITLE
Azure repository support

### ISSUE THREAD

**Issue by ChrisDoddGit** [tektoncd/pipeline#6227]
### Feature request

Support Azure Devops repository authentication with Tekton Pipelines. Currently I only see support for github / gitlab / bitbucket:

  annotations:
    tekton.dev/git-0: https://github.com # No support for azure

### Use case

Currently my organizations code is stored in Azure repositories. I need to set up a Tekton pipeline in openshift, however I can't find support for Azure repos.

**Comment by khrm** [comment]
Did you try setting up ssh for Azure repos? 
Examples only have Gitlab or Github but it should work with any Git SSH.

Refer here: https://github.com/tektoncd/pipeline/blob/main/docs/auth.md
