### ISSUE TITLE
Potential flakes in our CI 🤔 

### ISSUE THREAD

**Issue by pritidesai** [tektoncd/pipeline#6228]
Started noticing a few common test failures across many PRs this afternoon:

https://github.com/tektoncd/pipeline/pull/6225#issuecomment-1442556430

Test name | Commit | Details | Required | Rerun command
-- | -- | -- | -- | --
pull-tekton-pipeline-beta-integration-tests | 9a90496 | link | true | /test pull-tekton-pipeline-beta-integration-tests
pull-tekton-pipeline-alpha-integration-tests | 9a90496 | link | true | /test pull-tekton-pipeline-alpha-integration-tests
pull-tekton-pipeline-integration-tests | 9a90496 | link | true | /test pull-tekton-pipeline-integration-tests

Test name	Commit	Details	Required	Rerun command
pull-tekton-pipeline-beta-integration-tests	https://github.com/tektoncd/pipeline/commit/9a9049694e55d8f8d0690c9944667776f59f5a5c	[link](https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/6225/pull-tekton-pipeline-beta-integration-tests/1628886920597606400)	true	/test pull-tekton-pipeline-beta-integration-tests
pull-tekton-pipeline-alpha-integration-tests	https://github.com/tektoncd/pipeline/commit/9a9049694e55d8f8d0690c9944667776f59f5a5c	[link](https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/6225/pull-tekton-pipeline-alpha-integration-tests/1628886920526303232)	true	/test pull-tekton-pipeline-alpha-integration-tests
pull-tekton-pipeline-integration-tests	https://github.com/tektoncd/pipeline/commit/9a9049694e55d8f8d0690c9944667776f59f5a5c	[link](https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/6225/pull-tekton-pipeline-integration-tests/1628886920488554496)	true	/test pull-tekton-pipeline-integration-tests

```
test: TestExamples expand_more	0s
test: TestExamples/v1beta1/taskruns/git-ssh-creds-without-known_hosts expand_more	9s
test: TestExamples/v1beta1/taskruns/git-ssh-creds expand_more
```

/kind flake

**Comment by JeromeJu** [comment]
Thanks @pritidesai   https://prow.tekton.dev/job-history/gs/tekton-prow/pr-logs/directory/pull-tekton-pipeline-alpha-integration-tests have been failing since Feb 24.
