### ISSUE TITLE
release job in knative/build-pipeline is consistently failing

### ISSUE THREAD

**Issue by chaodaiG** [tektoncd/pipeline#624]
# Expected Behavior
Release job succeeds 
# Actual Behavior
Release job is failing consistently in past 7 days
# Steps to Reproduce the Problem
https://testgrid.knative.dev/knative-build-pipeline#release

# Additional Info
This might be expected as build-pipeline is now moved out of knative

**Comment by adrcunha** [comment]
@bobcatfish can we simply remove them from our Prow and Testgrid instances, now that you guys have your own?

**Comment by dlorenc** [comment]
> @bobcatfish can we simply remove them from our Prow and Testgrid instances, now that you folks have your own?

Yes we should remove.

**Comment by adrcunha** [comment]
/assign @chaodaig

Chao, please deploy the new configs once 563 merges and close this issue, thanks.

**Comment by chaodaiG** [comment]
Both Prow and Testgrid configs deployed
