### ISSUE TITLE
Highlight LTS releases 

### ISSUE THREAD

**Issue by drriguz** [tektoncd/pipeline#6275]
Hi,
As described in tekton dashboard release notes

> Tekton Dashboard release v0.33.0
> This Dashboard release supports Pipelines v0.41.x LTS - v0.45.x LTS and Triggers v0.22.x, bringing a number of features and enhancements.

So is v0.41 and v0.45 a LTS release? I cannot find message about LTS in pipeline releases.
I suggest that we can highlight the LTS release by add `LTS` suffix in the release title, here's what dashboard release does:

> [Tekton Dashboard release v0.32.0 LTS](https://github.com/tektoncd/dashboard/releases/tag/v0.32.0)

Thanks!

**Comment by pritidesai** [comment]
that sounds like a good idea, we have it documented in the [release.md](https://github.com/tektoncd/pipeline/blob/main/releases.md#release). We will have to update the release process. How about we add such suffix as part of the release name itself?

Change:

```
TEKTON_RELEASE_NAME=# The release name you just chose, e.g.: "Ragdoll Norby"
```

to:

```
TEKTON_RELEASE_NAME=# The release name you just chose, e.g.: "Ragdoll Norby LTS"
```
OR

Ask the release managers to update the release title before publishing the release?

@tektoncd/core-maintainers?

**Comment by lbernick** [comment]
I think adding "LTS" to the release name in the release process sounds like a good idea!
