### ISSUE TITLE
 consider installing goodfirstissue app on project/org

### ISSUE THREAD

**Issue by rajatjindal** [tektoncd/pipeline#629]
Hi,

Thanks for the opensource project for k8s native CI/CD. I stumbled upon the repo while searching for projects promoting/using "goodfirstissue" label to encourage first time contributors.

I've developed a github app [goodfirstissue](https://github.com/rajatjindal/goodfirstissue) which tweets 'good first issues' via twitter handle [@goodfirstissue](https://twitter.com/goodfirstissue). 

the targeted audience for twitter account are first time contributors, and to encourage open source contributions.

## Some details:

**Permissions this app need:** read permission on issues and metadata.
**Twitter Handle used to tweet:** [@goodfirstissue](https://twitter.com/goodfirstissue)
**Source code of the app/webhook:** https://github.com/rajatjindal/goodfirstissue
**Instructions to install github app**: https://github.com/rajatjindal/goodfirstissue#how-to-install

Thank you for considering this app.

Disclaimer: i am the author of goodfirstissue app. I am relatively new to opensource community and looking to engage more in open source contributions myself too.

**Comment by bobcatfish** [comment]
Thanks @rajatjindal ! We've set it up, seems pretty cool. Thanks for taking this on :)

Question, is it possible to configure the twitter handle used for tweeting, or at least the message? Would be cool to add twitter.com/tektoncd to the tweet as well :)

(btw great docs :D)

**Comment by rajatjindal** [comment]
Hi @bobcatfish 

many thanks for installing it. 

Currently its not possible to tweet using a specific twitter handle as it would require the auth token for that handle.

but its possible to cc a twitter handle whenever a goodfirstissue is reported for the project. I've [updated](https://github.com/rajatjindal/goodfirstissue/pull/24/commits/08e13e89cc1731dc177b13877b6b2c537207e504) our twitter handle map to include the same. so when next goodfirstissue is reported, the app should tweet the link to issue as well as cc the tweeter handle.

once again, many thanks for installing it.

Cheers,
Rajat Jindal
