### ISSUE TITLE
Add pipeline stages as a way of categorizing/grouping tasks

### ISSUE THREAD

**Issue by andrejusc** [tektoncd/pipeline#6299]
### Feature request

Have capability to specify within Task definition to which stage it belongs.

### Use case

Within GitLab pipelines it's possible to group jobs to stages, i.e. build, test, etc. See here: https://docs.gitlab.com/ee/ci/pipelines/pipeline_architectures.html#basic-pipelines

and notation like such:
````
stages:
  - build
  - test
  - deploy
````

Could we have similar concept for Tekton pipelines in regards to involved Tasks?

**Comment by andrejusc** [comment]
Besides order/sequence of possible stages - I'd like to have some reserved field/attribute for a Task, so then some UI could reflect visually defined grouping.

**Comment by ileixe** [comment]
I'm looking for the way to group a set of tasks as well.

For my case,

```
- Lint (I want it as Task not Pipeline)
  - isort task
  - black task
  - etc
- Test (Task)
  - pytest task 
  - pytest notebook test
  - etc
```

You can see `Lint` task have several sub tasks which already defined. I could not find a way to express it as native tekton. I saw several other approaches like 'Pipeline in Pipeline' but looks way verbose that I want (I just want to have a Pipeline instead Pipeline(s) just to group my Tasks)
