### ISSUE TITLE
Clean up interface for building + releasing

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#631]
# Expected Behavior

If automation (or a user) wants to create a `TaskRun` or `PipelineRun` to release the tekton pipelines project:

1. The Task should be able to use images for each step that have all the dependencies they need
2. It should be possible to auth for pushing images to registries to fall back in the following order:
  a. If the user [provided a service account to the run](https://github.com/tektoncd/pipeline/blob/master/docs/taskruns.md#service-account), use that
  b. Otherwise use the default account in the namespace (creds automatically provided to the executing container)

# Actual Behavior

In #528 and #529 we had to add some significant hacks to make `ko` work in a `Task`:

1. We had to have a step to install `ko` and copy the binary around so we could use it in later steps
2. We had to have a step to copy the `go` binary + supporting libs out of a `golang` image so we could use `go` in the `gcloud` image
3. We call `gcloud auth configure-docker` to setup docker auth which 1) only works in GCP based projects and 2) only works with default service credentials (not user supplied service accounts)

# Additional Info

* The solution here doesn't need to use `ko` - if we decide we want to use something else instead, and/or if we decided we want to split up publishing the images from generating the k8s config
* https://github.com/google/go-containerregistry/issues/383 is the issue for creating an image for `ko` upstream, if that issue is solved it could close this one :) (one potential solution)
* https://github.com/tektoncd/pipeline/blob/master/docs/auth.md#basic-authentication-docker might work for us however it looks like it requires a user to provide their username and password :(
* Maybe we can add some kind of credential helper to the `ko` image (https://github.com/google/go-containerregistry/issues/383) which knows how to handle credentials via some well defined interface
  * https://github.com/google/go-containerregistry/blob/871d0d9dba6c1a9aa6aed154d5a936ebf7607a1d/pkg/authn/k8schain/k8schain.go#L108
  * https://github.com/docker/docker-credential-helpers

**Comment by vdemeester** [comment]
@bobcatfish what is the status of this issue ? :angel:

**Comment by vdemeester** [comment]
@afrittoli @bobcatfish are you ok closing this issue ? (and if there is anything that is still needed from it, creating issues on [`tektoncd/plumbing`](https://github.com/tektoncd/plumbing) instead ?

**Comment by bobcatfish** [comment]
> @bobcatfish what is the status of this issue ? 👼

i think we're still in the same state but it also seems like it hasnt been important enough for anyone to get to
