### ISSUE TITLE
Deprecate `ResourcesResult` with the removal of `PipelineResources`

### ISSUE THREAD

**Issue by JeromeJu** [tektoncd/pipeline#6325]
`taskrun.status.resourcesresult` was introduced for writing PipelineResourcesResults from images digest since created. Now that `PipelineResources` are removed, we should deprecate the field.

Also reasons why it should be removed in details:
- `ResourceResult`, according its description, was 'Results from Resources built during the TaskRun. currently includes the digest of build container images', now since image resources are removed, it was left meaningless.
- `ResourceResult` highly relies on PipelineResourcesResult type, where previously PipelineResourceResult is being written to it, now that PipelineResources is being removed, there is no usage for resourcesResult
- `ResourceResult` has not been moved to v1, when we swap the storage versions, there will not be a suitable place to write to `PipelineResourceResult` any more

/kind cleanup

**Comment by lbernick** [comment]
Closed by #6301
