### ISSUE TITLE
hack/update-deps.sh script removes third_party directory 

### ISSUE THREAD

**Issue by EmmaMunley** [tektoncd/pipeline#6352]
# Expected Behavior

Run `hack/update-codegen.sh` to update `pipeline-api.md`.

# Actual Behavior

Deletes over 200 license files. 

https://github.com/tektoncd/pipeline/compare/54d617d4273807a33c029b9121bc181a736413f3..5c3944dea8f4029af6e28aeb3542451df52f0006

Workaround run `hack/update-reference-docs.sh` directly. 

# Steps to Reproduce the Problem

1. Run `hack/update-codegen.sh

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
Client version: 0.29.0
```

**Comment by lbernick** [comment]
Thanks for filing! I'm running into this as well in https://github.com/tektoncd/pipeline/pull/6342, and I believe the problem is with `hack/update-deps.sh` specifically. (I hope you don't mind me retitling the issue!) I suspect this has to do with whether the repo is in your gopath or not.
