### ISSUE TITLE
Pipelines CI - block merging PRs with a drop in code coverage

### ISSUE THREAD

**Issue by pritidesai** [tektoncd/pipeline#6367]
Pipelines contribution [standards](https://github.com/tektoncd/community/blob/main/standards.md#tests) describes/requests PR authors to maintain the code coverage:

```
Unit tests:
Coverage should remain the same or increase
```

As a reviewer, I expect the PR authors to follow this guideline. But there are times where this rule is not practiced. I would like to propose a new check in our CI to mandate this rule rather than relying on the PR reviewer to manually validate it.

**Comment by afrittoli** [comment]
Hi @pritidesai - thanks for bringing this up. 
I 100% agree we should avoid a drop in code coverage, and I always check for the coverage numbers. It can be hard however to enforce an automated check that allows for a 0% coverage drop without disrupting the user experience. If we were able to specify a threshold I think it would provide a better user experience.
On top of that, I think reviewers should get used to checking the coverage report anyways :)

**Comment by khrm** [comment]
We need to reopen this. We can probably move this to the plumbing repo because this is needed for other projects also.
/reopen
