### ISSUE TITLE
Re-add coverge automation

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#637]
# Expected Behavior

* For each PR, the author should get a report about:
  * Whether coverage has gone up and down
  * Which lines are covered and which arent 
* We should be able to track coverage over time in testgrid (e.g. see the coverage for knative/serving at https://testgrid.knative.dev/knative-serving#coverage - we'll need our own testgrid instance too :O)
* The coverage check will also fail if the coverage goes down below a threshold

Example of the covbot feedback:

![image](https://user-images.githubusercontent.com/432502/54629334-99c39f80-4a34-11e9-841a-5b0955d05df5.png)

The file link above will link to a line by line coverage analysis.

# Actual Behavior

Since creating [our own test infrastructure](https://github.com/tektoncd/pipeline/tree/master/infra) we lost the coverage reporting.

**Comment by dlorenc** [comment]
This looks pretty easy to add back. Do we care if it uses "covbot" or the same  account the rest of prow uses?

**Comment by bobcatfish** [comment]
same bot should be fine!

**Comment by shashwathi** [comment]
Yes this would be great

**Comment by vdemeester** [comment]
@dlorenc I think this can be closed now right ?

**Comment by dlorenc** [comment]
Yup!
