### ISSUE TITLE
[resolvers: bundle] Errors when pulling bundles from registries should be wrapped

### ISSUE THREAD

**Issue by arewm** [tektoncd/pipeline#6386]
# Expected Behavior

When the bundle resolver is pulling bundles from a registry, it should be able to detect when there is an issue with the registry and wrap that error to present a more user-friendly error

# Actual Behavior

```
Pipeline tekton-ci/tekton-bundle-builder can't be Run; it contains Tasks that don't exist: Couldn't retrieve Task "summary": yaml: control characters are not allowed
```

# Steps to Reproduce the Problem

This is not an issue that I have encountered directly but one that I have seen others encounter. I have seen this arise when the registry service blips out so multiple images might not be able to be pulled. Potential reproduction steps

1. Reference an invalid bundle image (i.e. one that will return a 404 or 5xx)
2. Run the pipeline

# Additional Info

- Kubernetes version: 

```
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4+a34b9e9", GitCommit:"b6d1f054747e9886f61dd85316deac3415e2726f", GitTreeState:"clean", BuildDate:"2023-01-10T15:55:28Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version: `0.41`

**Comment by arewm** [comment]
The bundle resolving was actually performed via `.taskRef.bundle` and not `.taskRef.resolver`. While I will need to move to the new bundle resolver, we should still make sure that the resolver properly handles the errors seen from the previous bundle resolution method.

**Comment by vdemeester** [comment]
Looking a little bit into it, it does seem it happens when quay.io doesn't return a 500 but an actual 200 with an html content.

**Comment by vdemeester** [comment]
@arewm so this is actually a bit of a problem to fix, and I am going to close this. 
- The resolvers (and the legacy bundle code as well) act correctly given the registry is acting like a normal service.
- Quay sometimes returns an HTTP 200 with some html content when it is unstable or errors out on a pull.. This is a Quay issue. Tt should return a HTTP 500 which would be properly handled by tekton
- The error contains `Couldn't retrieve Task "summary"`, which, even though the later is a bit criptic, convey the information that something went wrong and tekton couldn't find the task
