### ISSUE TITLE
How can I build the code in my local environment

### ISSUE THREAD

**Issue by skeeey** [tektoncd/pipeline#641]
# Expected Behavior

I can build the code in my local environment

# Actual Behavior

When I run

```
./hack/release.sh --skip-tests --nopublish --notag-release
```

It failed with 

```
./hack/release.sh: line 34: ko: command not found
```

What is the `ko` command?

**Comment by skeeey** [comment]
Oh, I should install `ko` command by

```
go get github.com/google/go-containerregistry/cmd/ko
```

**Comment by vdemeester** [comment]
@skeeey yes :angel: We're working towards having actual releases for `ko` so it can be installed more easily (and maybe automated in the scripts :man_dancing:). I think we can go ahead and close this issue :wink: 

/close
