### ISSUE TITLE
branches in the repo

### ISSUE THREAD

**Issue by pritidesai** [tektoncd/pipeline#6411]
We have about **55** branches in the repo:

```
 git ls-remote origin | grep refs/head
76a30522421f06ea509104c2bc9b50c26032c29e        refs/heads/api-compat-link
f91430e7aec6988c522da026b860b526f27c2166        refs/heads/bobcatfish-patch-1
f74bdaead119181e93cfeefab6337b0baef63f71        refs/heads/codeql
a7babbf4c0997708085f2b717f98998f121d142c        refs/heads/dependabot/go_modules/github.com/jenkins-x/go-scm-1.13.12
d32320a0dcf078a7f64f95f7fd2f3703e616c633        refs/heads/dependabot/go_modules/k8s.io/apimachinery-0.25.8
bfd676c025c679a1152607d2307384fbcffb3252        refs/heads/imjasonh-patch-1
9f971c41f669dfe3559518206a5e78766e76778f        refs/heads/imjasonh-patch-2
34fa1c0128f7d0df7c755e1c975d23b1f5e1833b        refs/heads/main
c1500fab83b09edadefb38bb8920a0c837d8f32b        refs/heads/release-0.1
b3c2b788a87a3983e44bd127f376795907c58075        refs/heads/release-21-0
0de7e2179090e0e2852ed5f12635137f36b4ee58        refs/heads/release-v0.10.x
821ac4d41f7ac8852cc51a3942b0fa171315a67e        refs/heads/release-v0.11.x
a54dd3984affab47f3018852e61a1a6f9946ecfa        refs/heads/release-v0.12.x
3a0cdba56ecb64069b12cbf12936223ab0f67e38        refs/heads/release-v0.13.0x
a4836a97f344c275cdf539288c75b7353a2e89f2        refs/heads/release-v0.14.x
92cf75ff742913f2ccecc27f6bb76ab0085833ee        refs/heads/release-v0.15.x
c1e10c767aa871fbec31551adb07d182beec6bcf        refs/heads/release-v0.16.x
a164ba3ef1f1cdbf4f8aa2bf8b5ecc89d3268dba        refs/heads/release-v0.17.x
f05ae9ebe08f0cc24815cb73f986856aa8633610        refs/heads/release-v0.18.x
e7425154434fe2a3c240216034f0832fdc51b0bf        refs/heads/release-v0.19.x
3d178f0fb90a64c0af995da1839f80dea3381c97        refs/heads/release-v0.20.x
787ad0ecdbebd8b503b7780ffe2a44e706146b39        refs/heads/release-v0.21.x
52f10075658f719492d63f404e5d05516ec1fe92        refs/heads/release-v0.22.x
bd1abcbeada651f28c6f3558332e9177d07d8fac        refs/heads/release-v0.23.x
36026c1bcdd2a53a037b12c659e5e105fd0fd4d9        refs/heads/release-v0.24.x
17c1c848c36cc633143f3821512ddd94df9eae90        refs/heads/release-v0.25.x
18c9bfae3a0e457441fcf17dedfdef49ea821f87        refs/heads/release-v0.27.x
e5c33d95d5bc1f27b0e94c9797cca231fcf3fcf6        refs/heads/release-v0.28.x
e68808a503237f28d70b15375c06219bab7e6a2c        refs/heads/release-v0.29.x
e0fed7f44ead371308a269b93c0cd0ef6cb8b221        refs/heads/release-v0.3.0
2f41321717beb9126e7ab2b1ae9f0fa51a1a9751        refs/heads/release-v0.30.x
b76cb0a2402492f6a116fc6103277026a8155b51        refs/heads/release-v0.31.x
2057c9dc65866118c45354c6b79a2b0bc7563f3b        refs/heads/release-v0.32.x
6b5710c3242ce7c3e1e8b876b7d35316449f617a        refs/heads/release-v0.33.x
fea15d7282b9fd571b97749442781753e2f82d29        refs/heads/release-v0.34.x
2bbc458c232820ae865e6a8254cdc1f4027f974b        refs/heads/release-v0.35.x
2da9a58c7e773c2068d3fccec84719f83488e1d8        refs/heads/release-v0.36.x
1759eabb937cb3b4c3f9d8327efb796d2fdd1f07        refs/heads/release-v0.37.x
b109054304f5a1db12910c71874eb9c7d896fb05        refs/heads/release-v0.38.x
6a789d4d48c0ed23e2c4607cb5d1519f2f64e569        refs/heads/release-v0.39.x
4003f7211e03122cd314816be8554bf27beb1898        refs/heads/release-v0.40.x
987d00a7a57a4051a2d615f0f1ac9ae7e92e5f72        refs/heads/release-v0.41.x
c12d43d5fe9c455b06b64eb3fc69aac711c78ade        refs/heads/release-v0.42.x
466db395ede35f9fad39c6b54da3ded31cf86571        refs/heads/release-v0.43.x
0e9e4b9daf9f54dc131533edf41c569c31e49926        refs/heads/release-v0.44.x
268b94bd749d2371634656f472e031ca1700a463        refs/heads/release-v0.45.x
086e76abb81d2d35e341553e501410790b0797d8        refs/heads/release-v0.46.x
f8232b8b73d6996515f7672c7acd2decf5046c93        refs/heads/release-v0.5.x
5fa70add12ede0ac3b14f90563eb2d6626adecc5        refs/heads/release-v0.6.x
1db2b54a1684a34232e8505c4af15824b7c4668f        refs/heads/release-v0.9.x
fad2bef872c3699448b0dbfb46cea85499855bba        refs/heads/release-v0.9.x-jasonhall
486be668f009d79c0f663eedf3cbd0a9a72cdc76        refs/heads/revert-5361-main
dcc7e55a5f077b1b3f4a403504da6b053feb44e3        refs/heads/v0-21-0
9a7a331134857da05889cde94e35b56f5be3f65f        refs/heads/v0.31.x
131a0ffa75e941493f2073354ae346762e1ad27d        refs/heads/v0.9.2-release
```

Currently, we do not have any formal process of how many branches should we maintain at any given time. This is a lower priority cleanup but just wanted to bring awareness of having many stale branches in the repo.

Can we delete branches owned by some of the pipeline maintainers?

```
 git ls-remote origin | grep refs/head | grep jason
bfd676c025c679a1152607d2307384fbcffb3252        refs/heads/imjasonh-patch-1
9f971c41f669dfe3559518206a5e78766e76778f        refs/heads/imjasonh-patch-2
fad2bef872c3699448b0dbfb46cea85499855bba        refs/heads/release-v0.9.x-jasonhall
```

@imjasonh, thoughts?

```
git ls-remote origin | grep refs/head | grep bobcatfish
f91430e7aec6988c522da026b860b526f27c2166        refs/heads/bobcatfish-patch-1
```

@bobcatfish thoughts?

We might be able to propose some guidelines on maintaining branches based on the release process:

https://github.com/tektoncd/pipeline/blob/main/releases.md

How about we only maintain the branches until the oldest EOL which is [0.37](https://github.com/tektoncd/pipeline/blob/release-v0.41.x/releases.md#v037) i.e. maintain branches from `0.37` to the current latest `0.46`?

**Comment by vdemeester** [comment]
@pritidesai what do you mean by "maintaining" the branches ? We shouldn't necessarily thing of "maintaining" branches but maintaining releases — and today, with LTS, we kind-of have those guidelines.

I deleted the "personal" branches (patch & co) from Jason and Christe 😛

**Comment by pritidesai** [comment]
thanks @vdemeester 😄 

> what do you mean by "maintaining" the branches ? We shouldn't necessarily thing of "maintaining" branches but maintaining releases — and today, with LTS, we kind-of have those guidelines.

sorry for the confusion 😄 "maintaining" as in create a branch for each release and update them with the patches (which is what we follow) in addition to **clean** them up when no longer supported based on the release guidelines.

**Comment by vdemeester** [comment]
> thanks @vdemeester smile
> 
> > what do you mean by "maintaining" the branches ? We shouldn't necessarily thing of "maintaining" branches but maintaining releases — and today, with LTS, we kind-of have those guidelines.
> 
> sorry for the confusion smile "maintaining" as in create a branch for each release and update them with the patches (which is what we follow) in addition to **clean** them up when no longer supported based on the release guidelines.

So I would definitely *not* want to clean them up (aka removing them). The main reason for this is, even if we "don't" support those release anymore (aka not cherry-picking to it, …), some people or tools might rely on those being available. As an example, OpenShift Pipelines do track release branches, and our support cycle is larger than the LTS timeframe, which means, we may carry patches, but we will rely on the release branch to still be there. (*Note: technically, we could rely on tags, but in practice, right now, one of the tool we use, doesn't work properly with them for some arcane reason*).

Branches in git are very cheap, removing them from a remote is almost solely cosmetic.

**Comment by afrittoli** [comment]
We could consider removing branches for releases that are not maintained anymore - it is cosmetic, but still would be nice to have.

**Comment by vdemeester** [comment]
> We could consider removing branches for releases that are not maintained anymore - it is cosmetic, but still would be nice to have.

As said above, I would rather not *and* I am not even sure what we would gain to do so. Also, the fact that we do not support a release any more, doesn't mean no one is depending on it, or tracking the release branch. As an example, OpenShift Pipelines, fetch sources from the release branches and, as we have a support time that is longer than LTS (more than a year), we are usually still fetching branches of version not supported any more by upstream. Removing these from the repository (upstream remote) would be a problem for us.

As said, branches in git are very cheap, and I don't really see any reason to remove them.
