### ISSUE TITLE
Ignore certain Tekton annotations when creating resources

### ISSUE THREAD

**Issue by lcarva** [tektoncd/pipeline#6435]
# Expected Behavior

When creating a TaskRun or PipelineRun resource, any annotation that starts with `*.tekton.dev/` should be removed.

# Actual Behavior

Chains completely ignores the resource because 

# Steps to Reproduce the Problem

1. Create a TaskRun or PipelineRun with the following annotation: `chains.tekton.dev/signed: 'true'`
2. Notice that Chains completely ignores the resource.

Furthermore, other annotations, like `chains.tekton.dev/transparency`, can cause confusion to users.

This is, of course, not isolated to Chains. Tekton Results is also affected by this issue.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
🐚 kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.24.2
Kustomize Version: v4.5.4
Server Version: v1.25.4+77bec7a

```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
🐚 tkn version
Client version: 0.29.0
Chains version: v0.13.1
Pipeline version: v0.41.1
Triggers version: v0.22.2
Operator version: v0.63.0

```

**Comment by lbernick** [comment]
@lcarva I'm a bit confused why this is something that should be addressed in Pipelines rather than in chains/results? I'm not familiar with how chains deals with annotations

**Comment by lcarva** [comment]
> @lcarva I'm a bit confused why this is something that should be addressed in Pipelines rather than in chains/results? I'm not familiar with how chains deals with annotations

@lbernick , Chains doesn't have an AdmissionController so it doesn't have a chance to reject/modify such resources. By the time Chains sees the resource, it's too late. I think something in the Tekton ecosystem should probably do this, and Tekton Pipeline seems like the right place. Wdyt?

**Comment by vdemeester** [comment]
That is my reading too. Note that #6441 tries to handle this for the "known cases" (aka anything with `*tekton.dev/*`) but that could as well be the same for any other tool (outside of tekton) that uses annotations to drive some behavior. A follow-up to #6441 could be to have a way to configure those "ignores" 🙃.

**Comment by lbernick** [comment]
I think that sounds reasonable!

**Comment by afrittoli** [comment]
I think this makes sense, but I would not categorise it as bug, it looks more like a new feature to me.

**Comment by pritidesai** [comment]
Pipelines WG - @vdemeester please move this to the next milestone if we cannot merge the fix in time
