### ISSUE TITLE
Default Resolver is not set for Finally Tasks

### ISSUE THREAD

**Issue by jerop** [tektoncd/pipeline#6449]
# Expected Behavior

Default Resolver is set for Finally Tasks

# Actual Behavior

Default Resolver is not set for Finally Tasks

# Additional Info

Was looking into the `SetDefaults` function and realized that support for default Resolver is not implemented for Finally Tasks:
https://github.com/tektoncd/pipeline/blob/9ff4f888e30aa8c11e24fb3fc74f81d95c3c7362/pkg/apis/pipeline/v1/pipeline_defaults.go#L34-L65

Related PR: https://github.com/tektoncd/pipeline/pull/6317

cc @QuanZhang-William

**Comment by QuanZhang-William** [comment]
Ahh... Good catch and thank you @jerop!

/assign
