### ISSUE TITLE
Task can't use ENV variables

### ISSUE THREAD

**Issue by JiriHusak-lab** [tektoncd/pipeline#6475]
# Expected Behavior
Task script execution of this code:
MY_VALUE=“AAA“
export MY_VALUE
echo $MY_VALUE

shows:
AAA

# Actual Behavior
shows nothing, MY_VALUE variable is empty.
See additional information below.

# Steps to Reproduce the Problem
1.
2.
3.

# Additional Info

- Kubernetes version:
OpenShift version: 4.11.7
Podman version: 4.2.0

  **Output of `kubectl version`:**

```
- Tekton Pipeline version:
Red Hat OpenShift Pipelines
1.9.2 provided by Red Hat
Components
• Tekton Pipelines: v0.41.1
• Tekton Triggers: v0.22.1
• Pipelines as Code: 0.15.5
• Tekton Chains (tech-preview): v0.13.1
• Tekton Hub (tech-preview): v1.11.3
  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**```


```
 have a critical issue. Believe me I tried mostly everything.
When Tekton pipeline executes Task, I can’t work with environment variables – I mean to set ENV variable in Task script part and use it.
Parameters work, env variables in Cluster tasks WORKS! Yes, in cluster task it works.
What doesn’t work:

```
MY_VALUE=“AAA“
export MY_VALUE
echo $MY_VALUE
if [ „$MY_VALUE“ == „AAA“ ]
then 
       echo „is AAA“
else
      echo „is NOT AAA“
fi
```

Even echo prints nothing, variable is empty, test shows is NOT AAA.

I’ve put sleep 600 into the script, use Terminal for the same task pod and it works there! So in the same pod, when I eneter POD via Terminal, I can do MY_VALUE=“AAA“; echo $MY_VALUE.
I tried different images, for example:
registry.access.redhat.com/ubi8/ubi-minimal:8.2
registry.access.redhat.com/ubi8/ubi@sha256:e721f98a49e731f0bd64f8e89c229e1dbb38c46265d92849b3e0bedaf5f81139
mcr.microsoft.com/playwright:focal

Behaviour is always the same.

I’m really confused.
Why in cluster tasks it works??? I’ve modified cluster tasks and at the beginning of the script section I’ve put MY_VALUE=“AAA“; echo $MY_VALUE. It works.
For tasks it doesn’t work regardless image.
For the same task POD, when enetered via Terminal, it works.
Sounds crazy.
How Tekton could change behaviour of POD when run in pipeline?

Issue is critical, I can’t use some Tasks.

Thanks.
Jiri

**Comment by afrittoli** [comment]
@JiriHusak-lab thank you for your bug report. Would it be possible to share the task definition?

**Comment by JiriHusak-lab** [comment]
Sure, here is a sample. Environment variables behave as empty after setting value.
I'm using  CRC OpenShift version: 4.11.7 and Red Hat OpenShift Pipelines 1.9.2 provided by Red Hat Operator.

My colleague is using Openshift v4.10.52 and openshift-pipelines-operator-rh.v1.8.2 and it is working for him corretcly.

Here is a Task yaml script, but, ...., on my environment, you can edit any Task (not Cluster Task) and add into script section MY_VARIABLE="WHATEVER" and then echo it, it is not displayed as variable is still empty.
Doing the same in any Cluster task - it works !!!! How is it possible, I supposed that only difference is Task scope?
And !!!!  when going into the Task POD using Terminal - going into running container, value assignment to variable works as well. In the identical Task container where in the pipeline it doesn't work !!!!


  1 apiVersion: tekton.dev/v1beta1
  2 kind: Task
  3 metadata:
  4   name: functional-test
  5 spec:
  6   params:
  7   - name: functional-test-run-image
  8     description: Image to run the test task
  9     type: string
 10   - name: environment-url
 11     description: Environment url that the tests will run against
 12     type: string
 13   - name: test-path
 14     description: Fully qualified path for tests
 15     type: string
 16   steps:
 17   - name: run-test
 18     image: $(params.functional-test-run-image)
 19     script: |
 20       #!/bin/sh
 21       echo " "
 22       M_VALUE="AAA"
 23       M_VALUE2='BBB'
 24       M_VALUE3="16"
 25       M_VALUE4='18'
 26       echo "M_VALUE: ${M_VALUE}" $M_VALUE
 27       echo "M_VALUE2: ${M_VALUE2}" $M_VALUE2
 28       echo "M_VALUE3: ${M_VALUE3}" $M_VALUE3
 29       echo "M_VALUE4: ${M_VALUE4}" $M_VALUE4
 30       echo " "
 31       #EXIT_CODE="$?"
 32       export EXIT_CODE='AAA'
 33       echo "EXIT_CODE: ${EXIT_CODE}"
 34       if [ "${EXIT_CODE}" != "AAA" ] ; then
 35          echo "NOT AAA"
 36          echo "EXIT_CODE: ${EXIT_CODE}"
 37          printf "%s" "EXIT_CODE: ${EXIT_CODE}"
 38          #exit "${EXIT_CODE}"
 39       else
 40          echo "AAA"
 41          echo "EXIT_CODE: ${EXIT_CODE}"
 42          printf "%s" "EXIT_CODE: ${EXIT_CODE}"
 43       fi
 44       M_VALUE="8"
 45       if [ "${MVALUE}" == "8" ] ; then
 46          echo "IT IS 8"
 47          echo "MVALUE: ${MVALUE}" $MVALUE
 48       else
 49          echo "NOT 8"
 50          echo "MVALUE: ${MVALUE}" $MVALUE
 51       fi
 52       echo " "
 53   workspaces:
 54   - name: source
 55     description: contains the cloned git repo
 56   - name: output
 57     description: place for output artifacts

**Comment by JiriHusak-lab** [comment]
For example, also this Task fails because the same reason. It is not possible to set values into env variables in script part.
 
https://raw.githubusercontent.com/tektoncd/catalog/main/task/sonarqube-scanner/0.2/sonarqube-scanner.yaml

Of course, it is hardly reproducable for you, It is specific to my environment. But tell me HOW, how this strange functionality could be achieved? Just theoretically, in case this behaviour would be intentional requirement, how could Tekton influence shell run in Task container in the way, that environment variable can't get value?
And it works in all Cluster Tasks!

**Comment by JiriHusak-lab** [comment]
Ok, I’ve located the rootcause. Am I doing something wrong, when creating pipeline run using „oc create -f filename.yaml“ or using „oc apply -f filename.yaml“ ?

So, issue seems to be that when I create pipeline run using:
oc apply -f ci.PipelineRun.yaml
or
oc create -f ci.PipelineRun.yaml
then created pipeline run yaml have replaced } character with ( character.
This replacement, when looking into create pipeline run yaml code doesn’t happen for cluster tasks. And it explains why cluster tasks are not facing this bug.

Example of wrongly created part of pipeline run code (Task part) using this creation way:
echo "STARTING test-task-script
-------------------------------------------------------"

            echo " "

            M_VALUE="AAA"

            echo "M_VALUE: $(M_VALUE)" $(M_VALUE)

            if [ "${M_VALUE}" != "AAA" ] ; then
               echo "IS NOT AAA"
               echo "M_VALUE: $(M_VALUE)" $(M_VALUE)
            else
               echo "AAA"
               echo "IS AAA"
               echo "M_VALUE: $(M_VALUE)" $(M_VALUE)
            fi
so logs of run looks like this:
STEP-TEST-TASK-SCRIPT
STARTING test-task-script -------------------------------------------------------

/tekton/scripts/script-0-9qz65: line 6: M_VALUE: command not found
M_VALUE:
/tekton/scripts/script-0-9qz65: line 6: M_VALUE: command not found
AAA
IS AAA
/tekton/scripts/script-0-9qz65: line 13: M_VALUE: command not found
/tekton/scripts/script-0-9qz65: line 13: M_VALUE: command not found
M_VALUE:

When Pipeline started from oc console, using GUI for pipeline start,
Then
Code looks like this:
script: >
echo "STARTING test-task-script
-------------------------------------------------------"

      echo " "

      M_VALUE="AAA"

      echo "M_VALUE: ${M_VALUE}"

      if [ "${M_VALUE}" == "AAA" ] ; then
         echo "IS AAA"
         echo "M_VALUE: ${M_VALUE}" ${M_VALUE}
      else
         echo "IS NOT AAA"
         echo "M_VALUE: ${M_VALUE}" ${M_VALUE}
      fi
so , correctly and log looks correctly as well:
STEP-TEST-TASK-SCRIPT
STARTING test-task-script -------------------------------------------------------

M_VALUE: AAA
IS AAA
M_VALUE: AAA AAA

Original scripts (3 scripts):
1st script) ci.PipelineRun.yaml:
1 apiVersion: tekton.dev/v1beta1
2 kind: PipelineRun
3 metadata:
4 name: test-tekton
5 spec:
6 taskRunSpecs:
7 pipelineRef:
8 name: test-tekton

2nd script) ci.Pipeline.yaml
1 apiVersion: tekton.dev/v1beta1
2 kind: Pipeline
3 metadata:
4 name: test-tekton
5 spec:
6 tasks:
7 # =========================================== TEST-TASK-SCRIPT ================================================
8 - name: test-task-script
9 taskRef:
10 name: test-task-script

3rd script) test-tekton.Task.yaml
1 apiVersion: tekton.dev/v1beta1
2 kind: Task
3 metadata:
4 name: test-task-script
5 spec:
6 steps:
7 - name: test-task-script
8 image: registry.access.redhat.com/ubi8/ubi@sha256:e721f98a49e731f0bd64f8e89c229e1dbb38c46265d92849b3e0bedaf5f81139
9 script: |
10 echo "STARTING test-task-script -------------------------------------------------------"
11 echo " "
12 M_VALUE="AAA"
13 echo "M_VALUE: ${M_VALUE}"
14 if [ "${M_VALUE}" == "AAA" ] ; then
15 echo "IS AAA"
16 echo "M_VALUE: ${M_VALUE}" ${M_VALUE}
17 else
18 echo "IS NOT AAA"
19 echo "M_VALUE: ${M_VALUE}" ${M_VALUE}
20 fi

**Comment by JiriHusak-lab** [comment]
So now question. Regarding my previous comment explaining bug rootcause, is it issue of OpenShift, CRC or Tekton? To whom log the bug?

**Comment by JiriHusak-lab** [comment]
I've just noticed that the same happens when creating Task using oc apply -f or oc create -f.
"${M_VALUE}" is replaced with "$(M_VALUE)"
$M_VALUE is replaced to empty string:
if [ "$M_VALUE" != "AAA" ] ; then
is created as
if [ "" != "AAA" ] ; then

So points to oc CLI binary or CRC Openshift?
oc version
Client Version: 4.11.7
Kustomize Version: v4.5.4
Server Version: 4.11.7
Kubernetes Version: v1.24.0+3882f8f

**Comment by JiriHusak-lab** [comment]
resolved in my code
