### ISSUE TITLE
Queue for task(taskun)

### ISSUE THREAD

**Issue by alezander86** [tektoncd/pipeline#6488]
Which option I could use now since "PipelineResources", "conditions" is deprecated. A task cannot be run concurrently with another one running in another pipelinerun. How to organize a queue for this Task? 

![graf](https://raw.githubusercontent.com/alezander86/flask-edp/main/taskrunq.png)

**Comment by chengjoey** [comment]
hi @alezander86 , [TEP-queueing-concurrent](https://github.com/tektoncd/community/blob/main/teps/0132-queueing-concurrent-runs.md) is on the way.

But this TEP seems to be mainly to solve the problem of concurrent number of taskrun, pipelinerun, etc. Can the use case taskrun you provide be put into a pipelinerun to solve the problem of sequence.

It seems that different scenarios should cancel the previous task or wait for the previous task to have different requirements, which should be turned into a queue strategy
