### ISSUE TITLE
How to enable profiling?

### ISSUE THREAD

**Issue by BoyanBlagoev91** [tektoncd/pipeline#6490]
Hello all,

We are trying to enable profiling for tekton-pipeline-webhook pod but setting the `profiling.enable: "true"` in the [observability configmap](https://github.com/tektoncd/pipeline/blob/2ae8b6a54a1bab401dbd3b1cc533a3b087ca54ea/config/config-observability.yaml) is not working. 

We set the parameter  `profiling.enable: "true"`  , restart the webhook pod but the string always says:
`"logger":"tekton-pipelines-webhook","caller":"profiling/server.go:64","message":"Profiling enabled: false"`

Did someone succeeded to enable profiling and get heap dumps from the controller/webhook pod?

Thanks in advance

**Comment by chengjoey** [comment]
hi @BoyanBlagoev91 , you can use this command:
```
kubectl edit cm config-observability -n tekton-pipelines
```

set configmap data like this:
```
data:
  "profiling.enable": "true"
```
<img width="407" alt="image" src="https://user-images.githubusercontent.com/30427474/229775920-a9d29b0f-103b-4dbd-8254-06f35b41eab9.png">

and restart webhook pod

then you could get logs like this:
```
kubectl logs tekton-pipelines-webhook-5d659cfbf7-sspq7 -n tekton-pipelines | grep -i "profiling"
{"severity":"info","timestamp":"2023-04-04T11:07:17.209Z","logger":"tekton-pipelines-webhook","caller":"profiling/server.go:64","message":"Profiling enabled: false","commit":"8cb2529-dirty"}
{"severity":"info","timestamp":"2023-04-04T11:07:17.230Z","logger":"tekton-pipelines-webhook","caller":"profiling/server.go:102","message":"Profiling enabled: true","commit":"8cb2529-dirty"}
```

**Comment by BoyanBlagoev91** [comment]
Thank you very much for the fast feedback. I managed to enable it now.
