### ISSUE TITLE
TEP-0114: Remove the v1alpha1.Run 

### ISSUE THREAD

**Issue by Yongxuanzhang** [tektoncd/pipeline#6498]
We need to remove v1alpha1.Run as planned in [TEP-0114: Custom Tasks Beta](https://github.com/tektoncd/community/blob/main/teps/0114-custom-tasks-beta.md) 
This issue is part of https://github.com/tektoncd/pipeline/issues/5863. 
https://github.com/tektoncd/pipeline/issues/5870 should also be closed once this issue is done.

**Comment by lbernick** [comment]
@Yongxuanzhang sorry to snag this from you, but I know you're out for a few days and want to get this into the v0.47 milestone

**Comment by Yongxuanzhang** [comment]
> TEP-0114: Remove support for v1alpha1.Run #6508

Thank you so much! ❤️
