### ISSUE TITLE
Promote TEP 0104 : Task-level Resource Requirements to beta

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/pipeline#6540]
Creating this issue to track work and requirements on promoting [TEP-0104](https://github.com/tektoncd/community/blob/main/teps/0104-tasklevel-resource-requirements.md#example-with-stepoverrides) to beta so that it is easier to consume for our users.

### Feature looking for Promotion

"Task-level Resource Requirements" was implemented to support adding compute resource per Tasks in 0.39 as an alpha feature. This feature request is created to keep track of work items and any outstanding issues before "Task-level Resource Requirements" can be promoted to beta.

### Current Feature Version

`enable-api-fields: alpha`

### Raise Feature Version

`enable-api-fields: beta`

### Pipeline Release

[Tekton Pipelines v0.38.0](https://github.com/tektoncd/pipeline/releases/tag/v0.38.0)

### Issues Reported by the Users

* 

### Usage in Dogfooding Cluster

None

### Open questions

- Is there anything that would block us from promoting this to beta ?
- If not, what could be the timeline for it ? (I would *love* 0.47.0 😝 )

/cc @jerop @lbernick @skaegi

**Comment by lbernick** [comment]
@vdemeester I think this is a duplicate of https://github.com/tektoncd/pipeline/issues/5490 :) there's some discussion on that issue already

**Comment by vdemeester** [comment]
oh yes it is. I didn't find it because it didn't have the TEP number in. Will close as duplicate of #5490 then.
