### ISSUE TITLE
Update instructions for patch releases

### ISSUE THREAD

**Issue by lbernick** [tektoncd/pipeline#6549]
Thanks @JeromeJu for catching this! Our [patch release docs](https://github.com/tektoncd/pipeline/tree/main/tekton#create-a-patch-release) are out of date.

We should discuss the process in this doc and decide if we want to make changes to it, as we aren't following the process right now. Also, we should add instructions for using the new `cherry-pick` automation, and give some examples of git cherry-pick commands and how to create a cherry-pick PR in case manual rebase is needed.

**Comment by vdemeester** [comment]
> * we used to use milestones for patch releases but started deleting milestones after the release was done. If we want to continue doing so we'd need someone to take on the milestone (possibly the release captain can also handle patch releases, but this is a bit unfair to LTS release captains).

I don't think we delete them though, just mark them as completed.

> * would be nice to have more automation for patch releases (but shouldn't block updates to these docs)

Definitely !
