### ISSUE TITLE
translating TaskSpec to Pod, Maybe missing or invalid Task default/kaniko

### ISSUE THREAD

**Issue by lazywhite** [tektoncd/pipeline#6551]
```
{
  "caller": "taskrun/taskrun.go:518",
  "commit": "086e76a",
  "knative.dev/controller": "github.com.tektoncd.pipeline.pkg.reconciler.taskrun.Reconciler",
  "knative.dev/key": "default/clone-build-push-run-rpnjg-build-push",
  "knative.dev/kind": "tekton.dev.TaskRun",
  "knative.dev/traceid": "ec7d13b3-4b27-45c5-91d8-b7462cdab3df",
  "logger": "tekton-pipelines-controller",
  "message": "Failed to create task run pod for taskrun \"clone-build-push-run-rpnjg-build-push\": failed to create task run pod \"clone-build-push-run-rpnjg-build-push\": translating TaskSpec to Pod: Get \"https://gcr.io/v2/\": dial tcp 64.233.188.82:443: i/o timeout. Maybe missing or invalid Task default/kaniko",
  "severity": "error",
  "stacktrace": "github.com/tektoncd/pipeline/pkg/reconciler/taskrun.(*Reconciler).reconcile\n\tgithub.com/tektoncd/pipeline/pkg/reconciler/taskrun/taskrun.go:518\ngithub.com/tektoncd/pipeline/pkg/reconciler/taskrun.(*Reconciler).ReconcileKind\n\tgithub.com/tektoncd/pipeline/pkg/reconciler/taskrun/taskrun.go:192\ngithub.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1beta1/taskrun.(*reconcilerImpl).Reconcile\n\tgithub.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1beta1/taskrun/reconciler.go:236\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20230221145627-8efb3485adcf/controller/controller.go:542\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20230221145627-8efb3485adcf/controller/controller.go:491",
  "timestamp": "2023-04-18T09:55:55.189Z"
}
```
I'm using kaniko task from  tekton-catalog, installed with `tekton hub install task kaniko`
It seems like tekton-controller will try to access https://gcr.io/v2 then failed with i/o timeout.

Question: why tekton-controller need to access image registry, why not leave this job to CRI like docker?

**Comment by vdemeester** [comment]
This is due to the "entrypoint" hack we have. Basically, if there is no `command` defined in the Task (which, I think it's the case), the pipeline controller fetch the image to get the image configuration, to know which command to use to run.

This is usually cached in memory (if I remember correctly), but if there is a network glitch or issue when doing the fetch, then, it will fail indeed.

One "workaround" here would be to set a `command` on the `kaniko` Task to make sure it doesn't need the controller to fetch the config.

cc @imjasonh

**Comment by lazywhite** [comment]
> 

can you let CRI to pull the image and tekton-controller just check if this image exists? because CRI like docker can set https_proxy but tekton-controller not as default

**Comment by lazywhite** [comment]
> This is due to the "entrypoint" hack we have. Basically, if there is no `command` defined in the Task (which, I think it's the case), the pipeline controller fetch the image to get the image configuration, to know which command to use to run.
> 
> This is usually cached in memory (if I remember correctly), but if there is a network glitch or issue when doing the fetch, then, it will fail indeed.
> 
> One "workaround" here would be to set a `command` on the `kaniko` Task to make sure it doesn't need the controller to fetch the config.
> 
> cc @imjasonh

can you let CRI to pull the image and tekton-controller just check if this image exists? because CRI like docker can set https_proxy but tekton-controller not as default, then failed with network error

**Comment by AlanGreene** [comment]
Tekton Operator provides proxy support for Tekton components, you can find details in the docs: https://github.com/tektoncd/operator/blob/main/docs/Proxy.md
