### ISSUE TITLE
Handle Loss of Deprecated Container Fields in v1 for Step LivenessProbes and etc.

### ISSUE THREAD

**Issue by JeromeJu** [tektoncd/pipeline#6575]
### Feature request

In [pipeline/pkg/apis/pipeline/v1beta1/container_conversion.go](https://github.com/tektoncd/pipeline/blob/a0b5cc55986818bff3c068f85e440e1236f172d1/pkg/apis/pipeline/v1beta1/container_conversion.go#L51) v1beta1 we are converting a v1beta1 sidecar to a v1beta1 step, which doesn't have any information loss while during the v1-storage swap, converting a v1 sidecar to a v1 step would have information loss. 

The script.go needs to be updated to ensure these fields are still supported in sidecars, and add tests for that functionality if they don't already exist.

Related to https://github.com/tektoncd/pipeline/issues/4546

**Comment by santhoshivan23** [comment]
hi @JeromeJu
i would like to work on this.

**Comment by pritidesai** [comment]
Pipelines WG - in progress, expected to close this in 0.48
