### ISSUE TITLE
[TEP-0089] Kubernetes service accounts do contain workload identity

### ISSUE THREAD

**Issue by jimmyjones2** [tektoncd/pipeline#6589]
TEP-0089 states ["The cert is tied to a service account rather than to a specific workload"](https://github.com/tektoncd/community/blob/main/teps/0089-nonfalsifiable-provenance-support.md#kubernertes-service-account-token-volume-projection) however [bound Kubernetes service account tokens](https://kubernetes.io/docs/concepts/storage/projected-volumes/#serviceaccounttoken) (1.21+) contains the pod name and UID, eg.
```
{
 "aud": [
   "foobar.com"
 ],
 "exp": 1636151360,
 "iat": 1636147760,
 "iss": "https://container.googleapis.com/v1/projects/taahm-gke-dev/locations/us-central1-c/clusters/mesh-certs-test2",
 "kubernetes.io": {
   "namespace": "default",
   "pod": {
     "name": "basic-debian-pod-bound-token",
     "uid": "a593ded9-c93d-4ccf-b43f-bf33d2eb7635"
   },
   "serviceaccount": {
     "name": "default",
     "uid": "ab71f2b0-abca-4bc7-905a-cc9b2d6832cf"
   }
 },
 "nbf": 1636147760,
 "sub": "system:serviceaccount:default:default"
}
```
(taken from [here](https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-bound-service-account-tokens))

Is this worth updating TEP-0089 for? Does it change any decisions?

@priyawadhwa
@lumjjb
@pxp928

**Comment by pxp928** [comment]
@jimmyjones2 that snippet you found is from the alternatives section of the TEP. These were other alternatives that were considered and not implemented (pros/cons for each). Spire allows us to do similar checks, utilizing the [k8s workload attestor](https://github.com/spiffe/spire/blob/main/doc/plugin_agent_workloadattestor_k8s.md#k8s-selectors), it can also validate the pod name, uid..etc of the pod.

**Comment by jimmyjones2** [comment]
Thanks!
