### ISSUE TITLE
Flake: TestExamples Git-Resolver

### ISSUE THREAD

**Issue by EmmaMunley** [tektoncd/pipeline#6626]
Logs: https://storage.googleapis.com/tekton-prow/pr-logs/pull/tektoncd_pipeline/6620/pull-tekton-pipeline-integration-tests/1654229828724854784/build-log.txt

Example PR where the test failed: https://github.com/tektoncd/pipeline/pull/6620

Relevant Build Logs: 
```
Error running git [fetch --recurse-submodules=yes --depth=1 origin --update-head-ok --force HEAD]: exit status 128\nerror: RPC failed; curl 56 OpenSSL SSL_read: Connection reset by peer, errno 104\nfatal: the remote end hung up unexpectedly\nfatal: early EOF\nfatal: index-pack 
```

```
Error fetching git repository: failed to fetch [HEAD]: exit status 128","stacktrace":"main.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:54\nruntime.main\n\truntime/proc.go:225
```

**Comment by lbernick** [comment]
Seeing PRs fail with logs like:
```
{"level":"error","ts":1684333449.4095483,"caller":"git/git.go:53","msg":"Error running git [fetch --recurse-submodules=yes --depth=1 origin --update-head-ok --force main]: exit status 128\nfatal: unable to access 'https://github.com/GoogleContainerTools/skaffold/': Could not resolve host: github.com\n","stacktrace":"github.com/tektoncd/pipeline/pkg/git.run\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:53\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:156\nmain.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:53\nruntime.main\n\truntime/proc.go:250"}
        {"level":"fatal","ts":1684333449.4096603,"caller":"git-init/main.go:54","msg":"Error fetching git repository: failed to fetch [main]: exit status 128","stacktrace":"main.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:54\nruntime.main\n\truntime/proc.go:250"}
```

a quick google search gave me https://stackoverflow.com/questions/20370294/git-could-not-resolve-host-github-com-error-while-cloning-remote-repository-in (suggests a networking problem)

The error Emma posted gives this stackoverflow result: https://stackoverflow.com/questions/46232906/git-clone-error-rpc-failed-curl-56-openssl-ssl-read-ssl-error-syscall-errno
This suggests increasing git buffer size for large repos, but this is less likely to explain why our integration tests using git all started failing around the same time, even with different repos.

I think it would be worth rewriting our integration tests to not use git clone where possible, although this probably wouldn't work for git resolver tests.
