### ISSUE TITLE
Some code blocks are not rendered properly in the documentation

### ISSUE THREAD

**Issue by rh-hectormartinezdev** [tektoncd/pipeline#6636]
# Expected Behavior

Code blocks are rendered properly at https://tekton.dev/docs/pipelines/tasks/#task-vs-clustertask

# Actual Behavior

![image](https://github.com/tektoncd/pipeline/assets/87312991/0a1c08ae-9893-408a-b177-b27cdd3884bc)

# Steps to Reproduce the Problem

1. Open https://tekton.dev/docs/pipelines/tasks/#task-vs-clustertask
2. You should se a code block that starts with ``` and it is not rendered visually

**Comment by rh-hectormartinezdev** [comment]
I think the commit https://github.com/tektoncd/website/commit/b0f804ac33987476c65a602642c4518d274d92a3 caused the problems. The code changed to allow the inclusion of code using another shortcode, but that broke the inclusion of code using the normal markdown block. I will submit an MR to fix the blocks so they adhere to the new way of including tabbed code.

**Comment by AlanGreene** [comment]
Looks like #6636 is a partial fix for this, but there are still some issues. The surrounding backticks and language identifier are being displayed:
![image](https://github.com/tektoncd/pipeline/assets/2829095/41c99b97-9469-40fa-a1e5-a17c7895fde1)

**Comment by rh-hectormartinezdev** [comment]
Ops, I will remove those too next week.

**Comment by rh-hectormartinezdev** [comment]
Completely forgot, sorry. I think this is not valid anymore, somehow my changes were reverted.
