### ISSUE TITLE
Task defined as finally is started, even though other tasks never completed

### ISSUE THREAD

**Issue by pratap0007** [tektoncd/pipeline#6637]
# Expected Behavior

Finally Task should only start running when all previous Task are completed (no matter if successful or not successful). Meaning finally should only trigger if all Task have completionTime set.

# Actual Behavior

The PipelineRun completed with problems as finally ran before all other Task had completionTime set and thus finally was failing.

# Steps to Reproduce the Problem

1. Create Pipeline containing few tasks and finally task
2. Start the Pipeline 

# Additional Info

- Tekton Pipeline version: 0.37.3

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
Pipeline version: v0.37.3

```

**Comment by lbernick** [comment]
@pratap0007 bumping [my previous comment](https://github.com/tektoncd/pipeline/issues/6637#issuecomment-1540468045); having this information will help us reproduce this issue. If you're able to try reproducing your issue on a current version of Pipelines, that would also be helpful.

**Comment by vdemeester** [comment]
Closing this, no updates so assuming this was fixed or workaround
