### ISSUE TITLE
Add documentation for determining what CRD versions exist on a cluster

### ISSUE THREAD

**Issue by lbernick** [tektoncd/pipeline#6669]
When we eventually remove v1beta1, users will need to know what v1beta1 objects still exist on their cluster, so they can remove or upgrade them before updating to a version of Pipelines that removes v1beta1. Users may also want to know what v1beta1 objects exist now, so they know what to upgrade to v1. We should add instructions to our documentation for easily listing out any v1beta1 objects.

**Comment by vdemeester** [comment]
> When we eventually remove v1beta1, users will need to know what v1beta1 objects still exist on their cluster, so they can remove or upgrade them before updating to a version of Pipelines that removes v1beta1. Users may also want to know what v1beta1 objects exist now, so they know what to upgrade to v1. We should add instructions to our documentation for easily listing out any v1beta1 objects.

Define "listing" them ? Because if v1beta1 is removed but etcd still has some `v1beta1` object, the only way to list them is going to be through etcd (because the CRDs definition for v1beta1 doesn't exists anymore, so kubectl or other clients won't be able to query them).

**Comment by lbernick** [comment]
I think the "listing" would have to happen before upgrading to a version of Pipelines that drops support for the api version. (Otherwise a user would have to temporarily downgrade, delete v1beta1 objects, and upgrade again.) Just based on [these docs](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#version-removal): "An older API version cannot be dropped from a CustomResourceDefinition manifest until existing stored data has been migrated to the newer API version for all clusters that served the older version of the custom resource". (This makes it sound like the Pipelines upgrade would actually fail)
