### ISSUE TITLE
TestPipelineRunCRDConversion is flake

### ISSUE THREAD

**Issue by Yongxuanzhang** [tektoncd/pipeline#6672]
Logs: https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/6663/pull-tekton-pipeline-alpha-integration-tests/1658558758315364352

Example PR where the test failed: https://github.com/tektoncd/pipeline/pull/6663

Relevant Logs:
```
    conversion_test.go:910: Failed waiting for v1 pipelineRun done: "pipeline-run-c-r-d-conversion-wgsdqpcl" failed
    panic.go:540: ############################################
    panic.go:540: ### Dumping objects from arendelle-fqvtt ###
    panic.go:540: ############################################
```

```
         conditions:
          - lastTransitionTime: "2023-05-16T20:02:20Z"
            message: PipelineRun "pipeline-run-c-r-d-conversion-wgsdqpcl" failed to finish
              within "1m0s"
            reason: PipelineRunTimeout
            status: "False"
            type: Succeeded
```

/kind flake

**Comment by JeromeJu** [comment]
Thanks @Yongxuanzhang , seems the actual flake was `TestPipelineRunCRDConversion `. I previously thought 60s should be enough for the wait time but I guess it is not 🤔 ? :/

**Comment by Yongxuanzhang** [comment]
> Thanks @Yongxuanzhang , seems the actual flake was `TestPipelineRunCRDConversion `. I previously thought 60s should be enough for the wait time but I guess it is not 🤔 ? :/

Oh yes, I'm not sure.. so it was incremented to 60s before?

**Comment by JeromeJu** [comment]
> > Thanks @Yongxuanzhang , seems the actual flake was `TestPipelineRunCRDConversion `. I previously thought 60s should be enough for the wait time but I guess it is not 🤔 ? :/
> 
> Oh yes, I'm not sure.. so it was incremented to 60s before?

Alike https://github.com/tektoncd/pipeline/pull/6026 . going to look into this specifically.
