### ISSUE TITLE
consider replace  git-clone related tests to not clone code

### ISSUE THREAD

**Issue by Yongxuanzhang** [tektoncd/pipeline#6680]
We encountered failing git-clone tests and the ci is fixed by pinning the test-runner tag.  https://github.com/tektoncd/plumbing/pull/1404. It's worth figuring the root cause of the failing tests,

Following is the previous bug report:

# Expected Behavior

The ci should pass. 

# Actual Behavior

We're having failing `pull-tekton-pipeline-alpha-integration-tests`, `pull-tekton-pipeline-beta-integration-tests` and `pull-tekton-pipeline-integration-tests `. This is blocking all of our PRs starting from today.  

Those tests pass in local environment (kind cluster + latest pipeline)

err logs can be viewed here:
https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/6673/pull-tekton-pipeline-alpha-integration-tests/1658899667351506944

```
     + /ko-app/git-init '-url=https://github.com/tektoncd/pipeline' '-revision=' '-refspec=' '-path=/workspace/output/' '-sslVerify=true' '-submodules=true' '-depth=1' '-sparseCheckoutDirectories='
        {"level":"error","ts":1684348699.0978005,"caller":"git/git.go:55","msg":"Error running git [fetch --recurse-submodules=yes --depth=1 origin --update-head-ok --force HEAD]: exit status 128\nfatal: unable to access 'https://github.com/tektoncd/pipeline/': Could not resolve host: github.com\n","stacktrace":"github.com/tektoncd/pipeline/pkg/git.run\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:55\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:150\nmain.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:53\nruntime.main\n\truntime/proc.go:225"}
        {"level":"fatal","ts":1684348699.097931,"caller":"git-init/main.go:54","msg":"Error fetching git repository: failed to fetch [HEAD]: exit status 128","stacktrace":"main.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:54\nruntime.main\n\truntime/proc.go:225"}
```

The error is from the git-clone task:
https://github.com/tektoncd/catalog/blob/835896be3d306356f896c51d1b53fd1130ecfa6a/task/git-clone/0.9/git-clone.yaml#L224-L232 

# Additional Info

I tried to replace the git-clone task with write-file task and those changed tests all passed. https://github.com/tektoncd/pipeline/pull/6679

Maybe one way is to replace them and move the git-clone example to `no-ci`

**Comment by Yongxuanzhang** [comment]
it seems the ci passed since https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/6596/pull-tekton-pipeline-beta-integration-tests/1658998986159165440
It's probably because @lbernick's fix https://github.com/tektoncd/plumbing/pull/1404 works by checking the prow job yaml, after the runner image is updated to not use latest tag, the ci passed

**Comment by lbernick** [comment]
I think it's still worth figuring out the root cause here and potentially rewriting some of our clone tests that don't need to actually clone anything 🤔
