### ISSUE TITLE
Unable to build Docker image using buildah

### ISSUE THREAD

**Issue by vignesh-vicky-tech** [tektoncd/pipeline#6698]
# Expected Behavior
When a commit happens in github repo, the github listener triggers and starts the pipeline, it fetches the repo, build the docker image and pushes to dockerhub repo and deploy it in kubernetes env.
 
# Actual Behavior
When a commit happens in github repo, the github listener triggers and starts the pipeline, it fetches the repo, failed to build the docker image and shows the docker img tag as invalid reference format.
Error: invalid reference format for docker repo link
![tkn-error](https://github.com/tektoncd/pipeline/assets/85112276/a3c4f957-92fe-4f7a-8ea8-8f5f64f2ac71)

# Steps to Reproduce the Problem
Create a event listener to trigger the pipeline whenever there is a commit in github and run this pipeline code.
Ref: https://github.com/vignesh-vicky-tech/pipeline4.git

# Additional Info
This pipeline works fine when we start the pipeline manually without using trigger, it fetches the repo, build the docker image and pushes to dockerhub repo and deploy it in kubernetes env but throws error in build image when using tekton triggers.

- Kubernetes version:
Client Version: v1.26.4+k3s1
Kustomize Version: v4.5.7
Server Version: v1.26.4+k3s1

- Tekton Pipeline version:
Client version: 0.30.1
Pipeline version: v0.43.1
Triggers version: v0.23.1
Dashboard version: v0.35.0

**Comment by alexezio** [comment]
Based on your description and the provided Git repo, I tested it in my own Tekton environment and couldn't reproduce the issue you mentioned. 
If you're using an EventListener to trigger the PipelineRun, then I suspect the issue might be related to the definition of the EventListener. Could you provide the corresponding YAML for the EventListener and the description of the TaskRun when the issue occurs?

**Comment by vignesh-vicky-tech** [comment]
Yaml file for eventlistener: https://github.com/vignesh-vicky-tech/trigger.git
Used ngork for exposing the el-githublistener service and adding the generated url by ngork to github webhook.
The issue oocurs whenever there is a commit in github repo, the pipeline starts running, fetches the repo and fails in the build docker image task.

**Comment by alexezio** [comment]
seems like there is no issue with your trigger define.
could you please paster the taskrun detail(it show the substitutedparams) on tekton dashboard when the pipeline is triggered?
![image](https://github.com/tektoncd/pipeline/assets/35565813/9127ae73-dbfa-462a-a234-ffe4159e465c)

**Comment by vignesh-vicky-tech** [comment]
![image](https://github.com/tektoncd/pipeline/assets/85112276/ff87ba35-da8a-4618-bc78-63fcf57417a9)

**Comment by alexezio** [comment]
I think you misunderstand the IMAGE params of buildah.
The IMAGE params in buildah means oci image tag.  In oci standard, you should not add schema protocol `https`
So in your scenario, you should change your IMAGE params default to "hub.docker.com/repository/docker/vigneshvicky12345/maven"

**Comment by dinushchathurya** [comment]
Remove the default values that have passed in your [pipeline](https://github.com/vignesh-vicky-tech/pipeline4/blob/main/pipeline4.yaml) file or change their values to `docker.io/vigneshvicky12345/maven` or `vigneshvicky12345/maven` to fix your issue.

**Comment by vignesh-vicky-tech** [comment]
@alexezio i tried using "hub.docker.com/repository/docker/vigneshvicky12345/maven" 
![image](https://github.com/tektoncd/pipeline/assets/85112276/52733c5d-aaca-4396-983f-3c3f71ccb490)
![image](https://github.com/tektoncd/pipeline/assets/85112276/8ca3ec52-45c2-4729-b291-5d495a5d98ac)
It throws error as:
Getting image source signatures
error pushing image "[hub.docker.com/repository/docker/vigneshvicky12345/maven:latest](http://hub.docker.com/repository/docker/vigneshvicky12345/maven:latest)" to "docker://[hub.docker.com](http://hub.docker.com/)/repository/docker/vigneshvicky12345/maven:latest": trying to reuse blob sha256:87c8a1d8f54f3aa4e05569e8919397b65056aa71cdf48b7f061432c98475eee9 at destination: pinging container registry hub.docker.com: invalid status code from registry 404 (Not Found)


But it works when we don't use triggers

**Comment by vignesh-vicky-tech** [comment]
@dinushchathurya i have changed their values to docker.io/vigneshvicky12345/maven and vigneshvicky12345/maven
but facing the error as:
writing blob: initiating layer upload to /v2/vigneshvicky12345/maven/blobs/uploads/ in [registry-1.docker.io](http://registry-1.docker.io/): errors:
denied: requested access to the resource is denied
unauthorized: authentication required

![image](https://github.com/tektoncd/pipeline/assets/85112276/0f57b659-d4ee-4c36-a62b-8d8577d158ae)
![image](https://github.com/tektoncd/pipeline/assets/85112276/8e22bf29-88f9-4127-aadc-202032dc88a1)

**Comment by dinushchathurya** [comment]
> @dinushchathurya i have changed their values to docker.io/vigneshvicky12345/maven and vigneshvicky12345/maven but facing the error as: writing blob: initiating layer upload to /v2/vigneshvicky12345/maven/blobs/uploads/ in [registry-1.docker.io](http://registry-1.docker.io/): errors: denied: requested access to the resource is denied unauthorized: authentication required
> 
> ![image](https://user-images.githubusercontent.com/85112276/240515781-0f57b659-d4ee-4c36-a62b-8d8577d158ae.png) ![image](https://user-images.githubusercontent.com/85112276/240515942-8e22bf29-88f9-4127-aadc-202032dc88a1.png)

Did you create a secret file for your docker authentication and attached it in to your service account?

**Comment by vignesh-vicky-tech** [comment]
yes i have created a secret file for docker authentication and attached to the service account. The pipeline works without using trigger, it only throws error when we trigger using the eventlistener.

**Comment by dinushchathurya** [comment]
> yes i have created a secret file for docker authentication and attached to the service account. The pipeline works without using trigger, it only throws error when we trigger using the eventlistener.

Take a look at this [repo](https://github.com/dinushchathurya/tekton-buildah-docker-build/tree/master).

**Comment by vignesh-vicky-tech** [comment]
.

**Comment by vignesh-vicky-tech** [comment]
@dinushchathurya when using the code from the above repo
Facing this error
![image](https://github.com/tektoncd/pipeline/assets/85112276/2d71584a-e955-4a1f-a064-19cdad817600)

**Comment by dinushchathurya** [comment]
> @dinushchathurya when using the code from the above repo Facing this error ![image](https://user-images.githubusercontent.com/85112276/240530158-2d71584a-e955-4a1f-a064-19cdad817600.png)

Please remove that `git-clone` namespace from files and use your preferred namespace, you want to use.

**Comment by dinushchathurya** [comment]
> @dinushchathurya ![image](https://github.com/tektoncd/pipeline/assets/85112276/b57763ae-d8ba-4df3-a41c-ce9c3c863a6c) it works for value: (params.image−reference):(tasks.fetch-repository.results.commit)
> 
> it fails when we use tag name as latest, value: (params.image−reference):(params.image-tag) ![image](https://github.com/tektoncd/pipeline/assets/85112276/1588b454-6372-43d4-a0ee-7b039803db81)
These files are on GIt repo?

**Comment by vignesh-vicky-tech** [comment]
yes the repo u shared, https://github.com/dinushchathurya/tekton-buildah-docker-build.git
In pipeline.yaml file  value: $(params.image-reference):$(tasks.fetch-repository.results.commit)
In pipeline-run.yaml file we are passing value to image tag but we haven't used it in the pipeline.yaml 
- name: image-tag
    value: latest

**Comment by dinushchathurya** [comment]
> yes the repo u shared, https://github.com/dinushchathurya/tekton-buildah-docker-build.git In pipeline.yaml file value: (params.image−reference):(tasks.fetch-repository.results.commit) In pipeline-run.yaml file we are passing value to image tag but we haven't used it in the pipeline.yaml
> 
> * name: image-tag
>   value: latest

Did you run pipeline using trigger? If yes, Can you share your pipeline, pipelineRun, triggerbinding and triggertemplate file.

**Comment by vignesh-vicky-tech** [comment]
yes i have used triggers
https://github.com/vignesh-vicky-tech/trigger.git

**Comment by dinushchathurya** [comment]
> yes i have used triggers https://github.com/vignesh-vicky-tech/trigger.git

Change https://github.com/vignesh-vicky-tech/trigger/blob/main/triggertemplate.yaml's `image-tag` value to `latest`
