### ISSUE TITLE
TEP-0135: Coscheduling PipelineRun pods Implementation

### ISSUE THREAD

**Issue by QuanZhang-William** [tektoncd/pipeline#6740]
In [TEP-0135](https://github.com/tektoncd/community/blob/main/teps/0135-coscheduling-pipelinerun-pods.md#tep-0135-coscheduling-pipelinerun-pods),  we introduced a feature which allows a cluster operator to ensure that all of a PipelineRun's pods will be scheduled to the same node.

This issue tracks the implementation for this TEP.

The implementation PRs:

- https://github.com/tektoncd/pipeline/pull/6741
- https://github.com/tektoncd/pipeline/pull/6790
- https://github.com/tektoncd/pipeline/pull/6818
- https://github.com/tektoncd/pipeline/pull/6819
- https://github.com/tektoncd/pipeline/pull/6892
- https://github.com/tektoncd/pipeline/pull/6893
- https://github.com/tektoncd/pipeline/pull/6921
- https://github.com/tektoncd/pipeline/pull/6927
- https://github.com/tektoncd/pipeline/pull/6929
- https://github.com/tektoncd/pipeline/pull/6940
- https://github.com/tektoncd/pipeline/pull/6984

Related issues:
- https://github.com/tektoncd/pipeline/issues/6915
- https://github.com/tektoncd/pipeline/issues/6985
- Beta promotion: https://github.com/tektoncd/pipeline/issues/6990

Misc:
- https://github.com/tektoncd/pipeline/pull/6925
- https://github.com/tektoncd/pipeline/pull/6930
- https://github.com/tektoncd/pipeline/pull/6991
- https://github.com/tektoncd/pipeline/pull/6994

**Comment by lbernick** [comment]
@QuanZhang-William is this a duplicate of https://github.com/tektoncd/pipeline/issues/6543?

**Comment by QuanZhang-William** [comment]
> @QuanZhang-William is this a duplicate of #6543?

Not really, I saw some discussions in https://github.com/tektoncd/pipeline/issues/6543. I plan to use this issue to track the implementation progress only so that it can be separated from the discussion.

**Comment by QuanZhang-William** [comment]
TEP-0135 is now implemented 😄 

/close
