### ISSUE TITLE
Promote TEP-75 from Beta to Stable

### ISSUE THREAD

**Issue by Yongxuanzhang** [tektoncd/pipeline#6748]
### Feature request

This issue is to collect feedback and track the progress of work to promote both [TEP-75](https://github.com/tektoncd/community/blob/main/teps/0075-object-param-and-result-types.md) from Beta to Stable. 

This feature was promoted from alpha to beta in [v0.46](https://github.com/tektoncd/pipeline/blob/main/docs/additional-configs.md#beta-features) tracked by https://github.com/tektoncd/pipeline/issues/5688. 

### Use case

Examples:

- [object param](https://github.com/tektoncd/pipeline/blob/main/examples/v1beta1/pipelineruns/beta/pipeline-object-param-and-result.yaml)
- [object results](https://github.com/tektoncd/pipeline/blob/main/examples/v1beta1/pipelineruns/beta/pipeline-object-results.yaml)

**Comment by lbernick** [comment]
@Yongxuanzhang would you mind updating this issue to use the [promotion request template](https://github.com/tektoncd/pipeline/blob/main/.github/ISSUE_TEMPLATE/promotion-request.md) rather than the feature request template?
