### ISSUE TITLE
Flake: TestLargerResultsSidecarLogs is flaky

### ISSUE THREAD

**Issue by JeromeJu** [tektoncd/pipeline#6769]
The PipelienRun times out after waiting for 10 minutes.

Prow logs: https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/6766/pull-tekton-pipeline-alpha-integration-tests/1664713403156926464

[logs](https://gist.github.com/JeromeJu/d19845cfac2f69d83d33c3ee385ca0cf)

/kind flake

**Comment by EmmaMunley** [comment]
Also saw this in #6792 and was able to reproduce locally even when on main.  Here are the logs from my cluster: https://gist.github.com/EmmaMunley/5f0a056b410bbb6ef7dc41e08e62c2f7

**Comment by JeromeJu** [comment]
@chitrangpatel Thanks for the clarification! It looks like we could close this for now unless anything other than pull issue or the feature setup, WDYT?

**Comment by chitrangpatel** [comment]
> @chitrangpatel Thanks for the clarification! It looks like we could close this for now unless anything other than pull issue or the feature setup, WDYT?

Agreed. We can close this for now.
