### ISSUE TITLE
Promote TEP-76 from Beta to Stable

### ISSUE THREAD

**Issue by Yongxuanzhang** [tektoncd/pipeline#6816]
### Feature request

This issue is to collect feedback and track the progress of work to promote both [TEP-76](https://github.com/tektoncd/community/blob/main/teps/0076-array-result-types.md) from Beta to Stable. 

This feature was promoted from alpha to beta in [v0.45](https://github.com/tektoncd/pipeline/blob/main/docs/additional-configs.md#beta-features) tracked by https://github.com/tektoncd/pipeline/issues/5688. 

### Use case

Examples:

- [array results in PipelineRun](https://github.com/tektoncd/pipeline/blob/main/examples/v1/pipelineruns/beta/pipelinerun-array-results-substitution.yaml)
- [array indexing](https://github.com/tektoncd/pipeline/blob/main/examples/v1/pipelineruns/beta/pipelinerun-param-array-indexing.yaml)
- [emit array results from matrix](https://github.com/tektoncd/pipeline/blob/main/examples/v1/pipelineruns/beta/pipelinerun-with-matrix-emitting-results.yaml)

### Issues to be fixed:

- https://github.com/tektoncd/pipeline/issues/7392

**Comment by lbernick** [comment]
@Yongxuanzhang would you mind updating this issue to use the [promotion request template](https://github.com/tektoncd/pipeline/blob/main/.github/ISSUE_TEMPLATE/promotion-request.md) rather than the feature request template?
