### ISSUE TITLE
taskruns_pod_latency metric should include units in the name

### ISSUE THREAD

**Issue by ralphbean** [tektoncd/pipeline#6830]
# Expected Behavior

When looking at metrics, it is trivial for a human reader to identify the units associated with a metric.

https://prometheus.io/docs/practices/naming/

# Actual Behavior

The "duration" metrics satisfy this (see `taskrun_duration_seconds`).

The `taskruns_pod_latency` metric does not.

# Steps to Reproduce the Problem

Observe the metric names exposed.

---

Related to #6832.

**Comment by vdemeester** [comment]
We should rename `taskruns_pod_latency` to `taskruns_pod_latency_nanosecends` or change it to seconds and name it `taskruns_pod_latency_seconds`, I agree 👍🏼 

cc @khrm @lbernick
