### ISSUE TITLE
Could you add more info to `tekton_pipelines_controller_taskruns_pod_latency` Prometheus metric?

### ISSUE THREAD

**Issue by jhutar** [tektoncd/pipeline#6832]
### Feature request

Could you add more info to `tekton_pipelines_controller_taskruns_pod_latency` Prometheus metric?

### Use case

When I examine what this metric returns, I see value 0 for most of the data points, but some of them have value 1000000000 and some 1000000000. These numbers looks suspicious to how I interpret the number based on metric name.

If the value would be in milliseconds, 4000000000 ms is 4000000 s and that is 1111 h and that is 46 days. But pod it relates to was both created and started in a same second.

**Comment by vdemeester** [comment]
Seems like its a float64 of the Pod Latency (see `podLatency.M(float64(latency))` — see [here](https://github.com/tektoncd/pipeline/blob/main/pkg/taskrunmetrics/metrics.go#L441)). 
The latency being the *scheduled* time substract by the *creation* time which makes it a [`Duration`](https://pkg.go.dev/time#Duration) (`int64`) casted in `float64` (not sure why 🤔).

But I agree, the values you report are suspicious… so something weird is happening somewhere (or decimals are gone or something …).

**Comment by vdemeester** [comment]
Alright, the duration is in nanoseconds so `4000000000` would be about 4s, which.. makes a little bit more sense.

![2023-06-19-093410](https://github.com/tektoncd/pipeline/assets/6508/64abfac5-96c0-48f2-9825-4975b01300be)
![2023-06-19-093354](https://github.com/tektoncd/pipeline/assets/6508/e0ffcfbe-3b3e-4d32-8a0b-e3e3d167cdd1)

I think this should at least be documented if not "changed" (but.. this would possible break some usage).

cc @khrm @lbernick

**Comment by jhutar** [comment]
> decimals are gone or something

:smile: 

Oh, ns, that makes sense, thank you!
