### ISSUE TITLE
Improve TestYamls and TestExamples

### ISSUE THREAD

**Issue by JeromeJu** [tektoncd/pipeline#6844]
For the current being, there are overlapped tests ie. [pipelinerun.yaml](https://github.com/tektoncd/pipeline/blob/main/test/yamls/v1beta1/beta/pipelineruns/pipelinerun.yaml) in both [examples test ](https://github.com/tektoncd/pipeline/blob/main/test/yamls/v1beta1/beta/pipelineruns/pipelinerun.yaml) and [yaml test](https://github.com/tektoncd/pipeline/blob/main/test/yamls/v1beta1/beta/pipelineruns/pipelinerun.yaml). This is confusing in the case for maintainers to decide whether we should maintain and keep both yamls synced or not. This issue is reported in order to find a way forward for TestYamls and TestExamples, we need to either:

- [ ] rewrite TestYamls and TestExamples to avoid testing on repeated yaml cases 
- [ ] keep the testYamls yaml files and examples synced

cc @lbernick @vdemeester

**Comment by JeromeJu** [comment]
Related: https://github.com/tektoncd/pipeline/issues/6142

**Comment by lbernick** [comment]
From https://github.com/tektoncd/pipeline/pull/3564, it looks like testYamls was introduced to test pipelineruns w/ images built based on the pipelines source, while our examples tests would use the latest versions of the images. Looking at the two yaml tests remaining, they are duplicates of examples tests, and neither of them use `ko` to build images. So I think we can just remove the yamls tests. @vdemeester to confirm.
