### ISSUE TITLE
Sync implementation of propagated parameters and workspaces

### ISSUE THREAD

**Issue by chitrangpatel** [tektoncd/pipeline#6847]
Parameters are propagated from `pipelinerun` to `pipeline tasks` to the created `taskruns`. However workspaces are propagated directly from `pipelinerun` to the `taskruns`. This makes the validation a little tricky. Also, from code readability it makes things a little challenging (even though they are functionally equivalent).

To sync things up, we should make the logic of propagated workspaces equivalent to propagated parameters (i.e. propagate them through the entire chain instead of skipping over pipeline and pipeline tasks).

/kind cleanup
/assign

**Comment by vdemeester** [comment]
/remove-lifecycle rotten
@chitrangpatel what's the status on this ?

**Comment by chitrangpatel** [comment]
Yes, I believe it was fixed in PR https://github.com/tektoncd/pipeline/pull/6660 by Lee!
