### ISSUE TITLE
Injection client uses knative type that has been deleted

### ISSUE THREAD

**Issue by drewbailey** [tektoncd/pipeline#6848]
When creating a new controller/reconciler, I get the following error

```
vendor/github.com/tektoncd/pipeline/pkg/client/injection/client/client.go:53:12: undefined: injection.Dynamic
```

knative.dev/pkg has removed `injection.Dynamic` in https://github.com/knative/pkg/commit/5671699f23d96f7fcfabbd45aa74fbc256dd3fe9. It seems like the tekton injection client will need to be updated.

**Comment by mike-serchenia** [comment]
also related
https://github.com/knative/pkg/issues/2725

**Comment by vdemeester** [comment]
@drewbailey this is handled as part of https://github.com/tektoncd/pipeline/pull/6975 👼🏼

**Comment by drewbailey** [comment]
Awesome, it was causing some versioning and complication issues in a controller we were writing at the time I believe.

**Comment by mike-sirs** [comment]
We have tekton integration project `toolbox` that can't upgrade to 0.50.0 
https://github.com/ElementalCognition/tekton-toolbox/pull/232

**Comment by vdemeester** [comment]
https://github.com/tektoncd/pipeline/pull/6975 has been merged, so closing this.
