### ISSUE TITLE
Results Summary Annotation is being filtered

### ISSUE THREAD

**Issue by khrm** [tektoncd/pipeline#6857]
# Expected Behavior
Results Summary and Record Summary Annotations are used by integrators like Triggers, PAC, etc during creation time.  Integrators don't care after creating the pipelineruns/taskruns. The results don't do any modification.  It just stores them as it is.

# Actual Behavior
At present, every results annotation is being filtered including summary annotations. 

This is also causing failure of CI in Results due to integration test failures.

**Comment by adambkaplan** [comment]
Do we have an accounting of how the summary annotations are being used by Triggers, Pipelines as Code, etc. today? 

If we have a better understanding of the use cases, I'm wondering if this issue can be worked around via other means.

**Comment by khrm** [comment]
PAC will include an annotation for Commits, and PR in the Results Summary Annotation of Pipelineruns. 

At present, filtering out annotations from Pipelines code introduces a coupling between components - pipelines, chains and Results.

**Comment by khrm** [comment]
We should add https://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy/ in chains and results to handle this filter instead of directly filtering from Pipelines code.

What do @tektoncd/core-maintainers @tektoncd/results-maintainers think?
