### ISSUE TITLE
Tekton Deployments failing to work after installation on OKD

### ISSUE THREAD

**Issue by dtrowbri7669** [tektoncd/pipeline#6918]
# Expected Behavior
All deployments in the Tekton Namespace should be working and creating pods.

# Actual Behavior
Receiving errors from the replicasets and all deployments have deployed 0 of 1 pods in the tekon-pipelines namespace

# Steps to Reproduce the Problem

(steps listed on the Tekton install page https://tekton.dev/docs/pipelines/install/)
1.  Oc login
2. oc new-project tekton-pipelines
3. oc adm policy add-scc-to-user anyuid -z tekton-pipelines-controller
4. oc adm policy add-scc-to-user anyuid -z tekton-pipelines-webhook
5. oc apply --filename https://storage.googleapis.com/tekton-releases/pipeline/latest/release.notags.yaml

# Additional Info
Brand new OKD cluster
OKD version: 4.13.0-0.okd-2023-06-24-145750
kubernetes version: v1.26.4-2868+a7ee68b55354d8-dirty
Tekton version: v0.49.0

I have made sure to apply the anyuid SCC to the service accounts. I have also tried applying the hostmount-anyuid and privileged SCCs as well, but the issue remains the same.

Error messages:
Replica set: tekton-pipeline-webhook
message: Error creating: pods "tekton-pipelines-webhook-6959c9dcfb-" is forbidden: unable to validate against any security context constraint: [pod.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/webhook]: Forbidden: seccomp may not be set, provider restricted-v2: .containers[0].runAsUser: Invalid value: 65532: must be in the ranges: [1000670000, 1000679999], provider "restricted": Forbidden: not usable by user or serviceaccount, provider "nonroot-v2": Forbidden: not usable by user or serviceaccount, provider "nonroot": Forbidden: not usable by user or serviceaccount, provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount, provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount, provider "hostnetwork-v2": Forbidden: not usable by user or serviceaccount, provider "hostnetwork": Forbidden: not usable by user or serviceaccount, provider "hostaccess": Forbidden: not usable by user or serviceaccount, provider "node-exporter": Forbidden: not usable by user or serviceaccount, provider "privileged": Forbidden: not usable by user or serviceaccount]

Replica set: tekton-pipeline-controller
message: Error creating: pods "tekton-pipelines-controller-8c7cd975d-" is forbidden: unable to validate against any security context constraint: [pod.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/tekton-pipelines-controller]: Forbidden: seccomp may not be set, provider restricted-v2: .containers[0].runAsUser: Invalid value: 65532: must be in the ranges: [1000670000, 1000679999], provider "restricted": Forbidden: not usable by user or serviceaccount, provider "nonroot-v2": Forbidden: not usable by user or serviceaccount, provider "nonroot": Forbidden: not usable by user or serviceaccount, provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount, provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount, provider "hostnetwork-v2": Forbidden: not usable by user or serviceaccount, provider "hostnetwork": Forbidden: not usable by user or serviceaccount, provider "hostaccess": Forbidden: not usable by user or serviceaccount, provider "node-exporter": Forbidden: not usable by user or serviceaccount, provider "privileged": Forbidden: not usable by user or serviceaccount]

Replica set: tekton-pipeline-events
message: Error creating: pods "tekton-events-controller-7998d9c-" is forbidden: unable to validate against any security context constraint: [provider "anyuid": Forbidden: not usable by user or serviceaccount, provider restricted-v2: .containers[0].runAsUser: Invalid value: 65532: must be in the ranges: [1000670000, 1000679999], provider "restricted": Forbidden: not usable by user or serviceaccount, provider "nonroot-v2": Forbidden: not usable by user or serviceaccount, provider "nonroot": Forbidden: not usable by user or serviceaccount, provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount, provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount, provider "hostnetwork-v2": Forbidden: not usable by user or serviceaccount, provider "hostnetwork": Forbidden: not usable by user or serviceaccount, provider "hostaccess": Forbidden: not usable by user or serviceaccount, provider "node-exporter": Forbidden: not usable by user or serviceaccount, provider "privileged": Forbidden: not usable by user or serviceaccount]

**Comment by vdemeester** [comment]
This is "expected", the yamls cannot apply as is on OKD (or OCP). This is documented in the [install](https://tekton.dev/docs/pipelines/install/) documentation (the `OpenShift` tab). I'll go ahead and close this.

**Comment by Adoptsomekids** [comment]
@vdemeester Excuse me, I'am getting the same issue on an Openshift Cluster while trying to [import some Tekton resources using the Tekton Dashboard](https://tekton.dev/docs/dashboard/tutorial/#import-some-tekton-resources-using-the-tekton-dashboard)
I've already tried to apply the anyuid security context constraint to the tekton-pipelines-controller service account and set the "set-security-context" feature flag to "true" in the [feature-flags configMap](https://github.com/tektoncd/pipeline/blob/main/docs/additional-configs.md#customizing-the-pipelines-controller-behavior) but it doesn't work. I've searched for a solution across different channels of the Tekton workspace on Slack, but nothing seems to work. Do you have any idea what could be the problem here?
![image](https://github.com/tektoncd/pipeline/assets/83385717/98219296-7a92-4bd2-ae57-717f7e7e3b16)
![image](https://github.com/tektoncd/pipeline/assets/83385717/132c2ede-ae89-4171-8cff-062496e5574f)

**Versions:**
![image](https://github.com/tektoncd/pipeline/assets/83385717/527baddb-9934-4b27-9246-e8e4b981b766)
