### ISSUE TITLE
Add URL Resolver

### ISSUE THREAD

**Issue by zroubalik** [tektoncd/pipeline#6920]
### Feature request

Would be nice to add URL Resolver, that fetches Task/Pipeline directly from the URL. Pipelines as Code support [this kind of resolver](https://pipelinesascode.com/docs/guide/resolver/#remote-http-url).

### Use case

It useful to reference a task that is hosted on some remote URL or even in a git repo. Using Git Resolver on a large repository is not convenient, becase it takes a lot of time to fetch the whole repo and the use the file. If we can just reference the file by URL, the resolving will be much faster.

**Comment by AlanGreene** [comment]
When using the authenticated API the git resolver only fetches the specified file: https://tekton.dev/docs/pipelines/git-resolver/#authenticated-api

Does this work for your use case? If not can you elaborate on the issue(s) you're facing?

**Comment by zroubalik** [comment]
Authenticated API doesn't work for our usecase, as it would require another configuration that we don't want to deal with. At least that's my understanding that we would need to configure additional secrets and what not, right?

Also the documentation on https://tekton.dev/docs/pipelines/git-resolver/#authenticated-api is not very clear TBH, the Task & Pipelines Resolution examples are complete? It would be nice if it really show everything that needs to be configured.

**Comment by chmouel** [comment]
since I'd like to have Pipelines-as-Code using the resolvers I can take this on!
