### ISSUE TITLE
Default `enable-api-fields` value for opt-in features once feature and API versioning are decoupled

### ISSUE THREAD

**Issue by JeromeJu** [tektoncd/pipeline#6948]
This issue tracks the decision to be made for the default `enable-api-fields` after [decoupling the feature and api version](https://github.com/tektoncd/pipeline/issues/6592). It has been [discussed in the process of TEP0138](https://github.com/tektoncd/community/pull/1034#discussion_r1268519228) and is worth noted after the TEP being implemented. For context, we have [changed the default `enable-api-fields` to beta ](https://github.com/tektoncd/pipeline/pull/6732) for the [v1 storage swap ](https://github.com/tektoncd/pipeline/pull/6444), and with [decoupling the feature and api version](https://github.com/tektoncd/pipeline/issues/6592), we would be able to switch back to `stable` `enable-api-fields` for any version upgrades.

Thanks to @lbernick and @afrittoli , there are couple of points to be discussed that are related:
- It is going to a backwards incompatible change to switch the default `enable-api-fields` to `stable`
   - Would it be worth it to make the breaking change?
   - What are we going to convey to users when we are making the change?
-  What value are we going to have as the `enable-api-fields` in the long run?

/kind feature

**Comment by JeromeJu** [comment]
related:
- https://github.com/tektoncd/pipeline/issues/6592
- https://github.com/tektoncd/community/pull/1034

**Comment by afrittoli** [comment]
Thanks @JeromeJu

I think we should try and switch to `stable` as default as soon as possible. 
We have "alpha, beta and stable" path for our features to that as Tekton developers we can communicate to the users that we are working on certain features, users may try them, but we don't guarantee they won't change or even be descoped.
Enabling an alpha or beta feature should be a conscious choice, i.e. A user is keen on using a feature and is willing to take the risk that comes with it.

These are 5 features currently in beta, which are enabled by default in the `v1beta1` API.

| Feature   | Proposal | Beta Release | 
|:----|:--------------|:----------|
| [Array Results and Array Indexing](pipelineruns.md#specifying-parameters)             | [TEP-0076](https://github.com/tektoncd/community/blob/main/teps/0076-array-result-types.md)   | [v0.45.0](https://github.com/tektoncd/pipeline/releases/tag/v0.45.0) |         
| [Object Parameters and Results](pipelineruns.md#specifying-parameters) | [TEP-0075](https://github.com/tektoncd/community/blob/main/teps/0075-object-param-and-result-types.md) | [v0.46.0](https://github.com/tektoncd/pipeline/releases/tag/v0.46.0) |
| [Remote Tasks](./taskruns.md#remote-tasks) and [Remote Pipelines](./pipelineruns.md#remote-pipelines) | [TEP-0060](https://github.com/tektoncd/community/blob/main/teps/0060-remote-resolution.md) | [v0.41.0](https://github.com/tektoncd/pipeline/releases/tag/v0.41.0) |
| [CSI workspaces](workspaces.md#csi)| [issue#4446](https://github.com/tektoncd/pipeline/issues/4446)|  [v0.41.0](https://github.com/tektoncd/pipeline/releases/tag/v0.41.0) | 
| [Projected volume workspaces](workspaces.md#projected)| [issue#5075](https://github.com/tektoncd/pipeline/issues/5075)| [v0.41.0](https://github.com/tektoncd/pipeline/releases/tag/v0.41.0) | 

If we turned the `api-feature-flag` to `stable` by default, we would risk breaking users of these features who have not migrated to `v1` yet. 

I think the next steps could be:
- deprecate the current default value of the flag
- every alpha feature promoted to beta will be decoupled from the API version starting now
- wait until these 5 features are stable
- switch the default value back to stable

**Comment by JeromeJu** [comment]
Thank you Andrea for the investigations on the currently impacted beta features. I found csi and projected volume workspaces are documented to become stable at https://github.com/tektoncd/community/commit/d83771533b9e258bf17fc1f4a693253e0148d40c. I have been wondering if this would make sense as an example for other features that are currently at beta stability level now?

Also I opened https://github.com/tektoncd/pipeline/pull/6954 to keep sync of the TEP096 and our codebase.

**Comment by lbernick** [comment]
chatted offline with @afrittoli and I think we came to the following plan (mostly the same as what he put in his comment, but noting that we want to change validation for existing beta features, and that we will wait at most 9 months to swap enable-api-fields):

1. Change all existing beta features to require enable-api-fields=beta regardless of api version, and use this pattern for any new beta features
2. announce that we will change the default value of enable-api-fields to stable, for the reasons Andrea has listed
3. wait until all existing beta features have been promoted to stable, or 9 months from now, whichever happens first
4. swap enable-api-fields to stable by default

**Comment by lbernick** [comment]
chatted offline with [@afrittoli](https://github.com/afrittoli) and we came to the following conclusions:

- We should change all existing beta features to require enable-api-fields=beta regardless of api version now, and use this pattern for any new beta features. 
- enable-api-fields should default to stable, for the reasons Andrea listed.

However, we are unsure of the best migration plan for getting enable-api-fields back to stable. Whenever we change enable-api-fields to stable, all beta features will go from enabled by default to disabled by default. Announcing it 9 months in advance gives cluster operators more time to adapt, but we don't know how many features will be in beta 9 months from now, so we don't know whether making this change in 9 months will result in more backwards incompatibility than making it at any other time. (We also don't want to stop new features from going to beta.)

To work around this, @afrittoli suggested a new flag, something like legacy-enable-beta-features-by-default, that we'd phase out after 9 months. We'd default enable-api-fields to stable and introduce this flag at the same time, with a default value of "true", preserving existing behavior. The main concern we have about this is that it could be confusing.

We'd love to know what others think about how to address this problem!

**Comment by lbernick** [comment]
I've chatted with @jerop and @dibyom and will summarize our conversation here:

After writing up the table above, the three of us agree that another feature flag will add more complexity than necessary. We also all agree that the appropriate value for enable-api-fields is "stable".

Dibyo has suggested that instead of changing validation for v1beta1, we simply document that the updated validation will apply to future beta APIs, and swap "enable-api-fields" back to stable. The reason for this suggestion is that the user impact from the existing bug (v1beta1 pipelineruns being unable to create taskruns when "enable-api-fields" is set to "stable") is likely smaller than the user impact of turning off beta features by default for v1beta1, and the bug can be avoided by migrating to v1.

**Comment by vdemeester** [comment]
/remove-lifecycle stale
@JeromeJu what is the status for this ?

**Comment by JeromeJu** [comment]
Thanks for the reminder Vincent!

During WG we have reached consensus that the default `enable-api-fields` value will remain `beta`. This was made due to the following reasons: 
- As of existing API-driven features under `enable-api-fields`, we are not switching back to `stable` for backwards-compatibility reason since changing back to `stable` might break users on those beta features.
- For new features, since we are having [Per-feature flags](https://github.com/tektoncd/pipeline/pull/7090), this would not be an issue since new features would only be enabled or disabled.

**Comment by JeromeJu** [comment]
Closing this as consensus has been reached.
