### ISSUE TITLE
Support resources configuration for container created by controller

### ISSUE THREAD

**Issue by vicoooo26** [tektoncd/pipeline#6974]
### Feature request
Support resource configuration for container created by tekton controller, such as entrypoint and shell initContainers.
Currently, tekton controller accepts cmd options like `entrypoint-image`, and then controller will use it as initContainer image but left resources empty.
To make container more configurable, maybe we could add some new cmd options like `entrypoint-cpu-request` or `entrypoint-cpu-limit` that can be overridden by taskRun annotations like `tekton.dev/entrypoint-cpu-request` during reconciliation.

### Use case
Achieve pod QoS by specifying container resources explicitly.

**Comment by vdemeester** [comment]
/remove-lifecycle stale
Hey @vicoooo26. I think this is linked to https://github.com/tektoncd/pipeline/pull/7003 and https://github.com/tektoncd/pipeline/issues/2933, and https://github.com/tektoncd/pipeline/issues/7058.
