### ISSUE TITLE
deduplicate and update the taskRun status to provide meaningful info 

### ISSUE THREAD

**Issue by pritidesai** [tektoncd/pipeline#7013]
When a `task` in a `pipeline` fails with reason `Failed`, the `status.conditions[].mesasge` of the `taskRun` reports the step which caused the failure along with the `imageID` and a `kubectl logs` command:

```
"message": "\"step-step1\" exited with code 2 (image: \"alpine@sha256:82d1e9d7ed48a7523bdebc18cf6290bdb97b82302a8a9c27d4fe885949ea94d1\"); for logs run: kubectl -n default logs large-result-pipeline-run-large-task-pod -c step-step1\n",
```

There are two issues with this:

1. Generally, the users of a CI/CD service are not given access to the cluster and running `kubectl logs` is prohibited. In most of these cases, access to the Tekton Controller is often prohibited as well. So there is no meaningful information available to the user based on this `message`.

2. The `imageID` is already part of the `status.steps[].imageID` which is duplicated in the `status.conditions[].message`, unnecessary taking up the space.

In case of such failure, please try to surface more detailed errors rather than or in addition to `kubectl logs` command.

/kind feature

**Comment by dibyom** [comment]
+1 I definitely think we should change the kubectl logs message

**Comment by santhoshivan23** [comment]
@dibyom @pritidesai I can take this up and remove imageID from the message. I’d need some help in figuring out how to get more detailed errors.

**Comment by JeromeJu** [comment]
https://github.com/tektoncd/pipeline/pull/7405 is raised to fix this.
From my understanding, there might not be much other related info we could provide with the internal runResult. Plus https://github.com/tektoncd/pipeline/issues/7223 will help provide more information with the termination status.
