### ISSUE TITLE
Review usage of `cmp.Diff` to follow the `(want, got)` pattern

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/pipeline#7027]
We heavily use `cmp.Diff` in our tests. Those should follow the `(want, got)` pattern (or `(expected, actual)`) when used.
However, if we go through the tests, sometimes it is used in the opposite way (aka `(got, want)`). 

This can become a problem when reviewing the failures of tests as, we are assuming the *correct* usage when printing out the error (`diff.PrintWantGot(d)`). This means, in some tests, the error is inverted, it displays "got" as wanted, and "wanted" as got… Which tends to be relatively painful when figuring things out.

> // PrintWantGot takes a diff string generated by cmp.Diff and returns it
> // in a consistent format for reuse across all of our tests. **This
> // func assumes that the order of arguments passed to cmp.Diff was
> // (want, got) or, in other words, the expectedResult then the actualResult.**

We would need to go from the former to the latter.

```go
        // Invalid usage
	if d := cmp.Diff(updatedTR.Status.TaskSpec, expectedStatusSpec); d != "" {
		t.Errorf("expected Status.TaskSpec to match, but differed: %s", diff.PrintWantGot(d))
	}
        // Valid usage
	if d := cmp.Diff(expectedStatusSpec, updatedTR.Status.TaskSpec); d != "" {
		t.Errorf("expected Status.TaskSpec to match, but differed: %s", diff.PrintWantGot(d))
	}
```

/cc @tektoncd/core-collaborators @tektoncd/core-maintainers

**Comment by minhoryang** [comment]
Is there any progress on this?
