### ISSUE TITLE
PipelineValidationFailed for external reference after update from 0.49 to 0.50

### ISSUE THREAD

**Issue by isniukArte** [tektoncd/pipeline#7042]
# Expected Behavior
We use TriggerTemplate with reference to Pipeline in another namespace.
`
spec:
  resourcetemplates:
    spec:    
      pipelineRef:
        params:
        - name: kind
          value: pipeline
        - name: name
          value: my-pipeline
        - name: namespace
          value: my-tekton-catalog
        resolver: cluster`
Everything worked as expected till version 0.50. Cluster-resolver uses default configuration from release.yaml
# Actual Behavior
PipelineRun in the app namespace throws an error PipelineValidationFailed with the message:
`message: 'validation failed for referenced Pipeline k8s-deploy-app: the namespace
      of the provided object does not match the namespace sent on the request'`
I observed no errors in Resolution requests or in the logs of tekton-pipelines-resolver.

Everything works as expected when I copy Pipeline from the catalog namespace to the app workspace and change 'pipelineRef:' block to simple 'name:'.

A simple change of resolver image to v0.49 version does not fix the problem. Complete rollback of release.yaml to v0.49 does.

# Additional Info

- Kubernetes version: 1.26.6

  **Output of `kubectl version`:**

```
Client Version: v1.27.4
Kustomize Version: v5.0.1
Server Version: v1.26.6
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
v0.50.0
```

**Comment by vdemeester** [comment]
Hey @isniukArte, this is a similar issue as https://github.com/tektoncd/pipeline/issues/7015 and has been fixed by https://github.com/tektoncd/pipeline/pull/7017 👼🏼 
It's gonna be in the upcoming 0.50.1 release, which I am trying to get released today 😉
