### ISSUE TITLE
Allow Alternative Shell Image for the Pipeline Controller

### ISSUE THREAD

**Issue by chriscannon** [tektoncd/pipeline#7081]
### Feature request

As it works now the shell images for the Tekton pipeline controller is hard coded (https://github.com/tektoncd/pipeline/blob/main/config/controller.yaml#L76C29-L76C54) and cannot be changed when using the `script` action. Ideally this image location could be overwritten to point to any image desired. This would be especially valuable in egress restricted environments where the type of external requests are restricted. 

### Use case

Instead of using the hard coded shell image (cgr.dev/chainguard/busybox@sha256:19f02276bf8dbdd62f069b922f10c65262cc34b710eea26ff928129a736be791) I would like to point to a different shell image that I am in control of on my local network.

**Comment by khrm** [comment]
If you use tekton operator to install, you can use a different image.

**Comment by vdemeester** [comment]
@chriscannon I am not sure I entirely follow. You can update the deployment (or the `release.yaml`) to use a different shell image. But no matter what, it doesn't have anything to do with the `script` feature. The `script` feature depend on a shell being available in the image used by the step where it is defined, it doesn't use the shell image.

**Comment by chriscannon** [comment]
@vdemeester I guess what's confusing to me then is that whewn I use the `script` feature I see it pull this image cgr.dev/chainguard/busybox@sha256:19f02276bf8dbdd62f069b922f10c65262cc34b710eea26ff928129a736be791. When I stop using the `script` feature it does not try to pull that image. Why does this happen if it's using the shell on the image I specify in the step?

**Comment by vdemeester** [comment]
@chriscannon yes, it uses the shell image to actually "write" the script (from the spec to the container "filesystem") in a place (`/tekton/scripts`) that is mounted in a given step. It is used as an init container to "prepare" things for the execution, but not for the step itself. Is that a bit clearer ?

**Comment by chriscannon** [comment]
I'm just going to update the image in the `release.yaml`.

**Comment by jsteenb2** [comment]
@vdemeester, I'm having a similar issue. What's the best way to update the shell-image's to point at a different registry (works as a proxy, no access to public registry directly)?
