### ISSUE TITLE
Add documentation for object `Results`

### ISSUE THREAD

**Issue by jerop** [tektoncd/pipeline#7106]
Existing documentation covers `Results` of types [string](https://github.com/tektoncd/pipeline/blob/main/docs/tasks.md#emitting-results) and [array](https://github.com/tektoncd/pipeline/blob/main/docs/tasks.md#emitting-array-results). The docs for array `Results` was added in https://github.com/tektoncd/pipeline/pull/6039. We need to add similar documentation for object `Results`. 

Note that the documentation for `Parameters` covers all the types -- [string](https://github.com/tektoncd/pipeline/blob/main/docs/tasks.md#string-type), [array](https://github.com/tektoncd/pipeline/blob/main/docs/tasks.md#array-type) and [object](https://github.com/tektoncd/pipeline/blob/main/docs/tasks.md#object-type).

cc @Yongxuanzhang

**Comment by Yongxuanzhang** [comment]
/assign
Thanks!
