### ISSUE TITLE
Support Slack

### ISSUE THREAD

**Issue by abergmeier** [tektoncd/pipeline#712]
Maybe create a Tekton channel in Kubernetes Slack?

**Comment by pivotal-nader-ziada** [comment]
There is a slack channel currently in the knative slack https://knative.slack.com/messages/CDCQ72D0R

**Comment by bobcatfish** [comment]
You can see all of our docs about getting in contact at https://github.com/tektoncd/community/blob/master/contact.md

(And we'll update there once we have our own slack!)
