### ISSUE TITLE
TEP0138 Per-feature Flags Improvement to Decouple API and Feature Versioning

### ISSUE THREAD

**Issue by JeromeJu** [tektoncd/pipeline#7177]
[[TEP-0138]: Decouple API and Feature Versioning](https://github.com/tektoncd/community/pull/1034) proposed to change to per-feature flags for **new** features in Tekton and so as to decouple API and feature versioning.

This issue tracks the per-feature flags improvement and the documentation changes to decouple API and feature versioning:
- Change existing validation to decouple feature and API versioning
- API compatibility policies update and broadcast in the community that we are shifting to per-feature flags
  - [x] [Add feature graduation process](https://github.com/tektoncd/pipeline/pull/7076)
  - [x] Updates API-compatibility policies regarding **new** feature validations
 -  [Plumbing setup for additional CI tests](https://github.com/tektoncd/plumbing/issues/1629)
 -  User facing impact clarifications to tekton-users.

**Comment by JeromeJu** [comment]
area/api

**Comment by JeromeJu** [comment]
Can we please add this to the current milestone? cc @tektoncd/core-maintainers

**Comment by afrittoli** [comment]
@JeromeJu can we close this?

**Comment by JeromeJu** [comment]
> @JeromeJu can we close this?

We would still need https://github.com/tektoncd/pipeline/pull/7090 to close this one. But I think it shall be fine for the cutoff.

**Comment by JeromeJu** [comment]
Closing as https://github.com/tektoncd/pipeline/pull/7090 is merged. Thanks again for the time and review on this!
