### ISSUE TITLE
The container runtime is docker tekton-pipelines version 1.24

### ISSUE THREAD

**Issue by 1569099266** [tektoncd/pipeline#7183]
# Expected Behavior

# Actual Behavior

# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**
![image](https://github.com/tektoncd/pipeline/assets/46311200/08c7a1b3-d581-4e03-bdad-1f4b18e8a9a8)

```
(paste your output here)
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**
![image](https://github.com/tektoncd/pipeline/assets/46311200/d4fe4240-45a2-4aa0-bc68-658898738696)

```
(paste your output here)
```
![image](https://github.com/tektoncd/pipeline/assets/46311200/4ffd28ab-624c-4035-adcd-8d96e2403ee4)
![image](https://github.com/tektoncd/pipeline/assets/46311200/db262419-5b98-4687-a0f1-25f14cbfa211)

**Comment by AlanGreene** [comment]
Starting with Pipelines v0.51 the minimum required Kubernetes version is 1.25 as mentioned in the error message you provided.

You can find the minimum required Kubernetes version in the readme: https://github.com/tektoncd/pipeline#required-kubernetes-version

This is also mentioned in the release notes when the minimum version is increased.
