### ISSUE TITLE
fix a link - display name

### ISSUE THREAD

**Issue by pritidesai** [tektoncd/pipeline#7190]
`pipelines.md` has a incorrect link in a section where with optional configruation.

`displayName` in multiple places should point to https://github.com/tektoncd/pipeline/blob/main/docs/pipelines.md#specifying-a-display-name instead it is pointing to https://github.com/tektoncd/pipeline/blob/main/docs/pipelines.md#adding-tasks-to-the-pipeline and https://github.com/tektoncd/pipeline/blob/main/docs/pipelines.md#adding-finally-to-the-pipeline.

```
optional:
  tasks:
    displayName
```

```
optional:
  finally:
    displayName:
```

/kind bug

**Comment by pranav-jadhav** [comment]
Please assign me this issue

**Comment by chengjoey** [comment]
> Please assign me this issue

hi @pranav-jadhav , you can comment /assign it should assign yourself to the issue (it just needs you to have a comment on the issue)

/assign @pranav-jadhav

**Comment by vavrajosef** [comment]
Hi, I think I  can fix this
