### ISSUE TITLE
introduce an option to parameterize `displayName`

### ISSUE THREAD

**Issue by pritidesai** [tektoncd/pipeline#7200]
`displayName` was introduced as part of https://github.com/tektoncd/community/blob/main/teps/0047-pipeline-task-display-name.md. 

`displayName` helps describing and identifying `pipelineTasks` using human readable names in addition to machine friendly. `displayName` is limited to static values. It will help to specify these values dynamically through `params` in such way that the users can specify their own desired names through `pipelineRun` in a shared env.

For example:

```
displayName: "comments=$(params.comments)"
```

/kind feature

**Comment by AverageMarcus** [comment]
Related - https://github.com/tektoncd/pipeline/issues/7082 (this is the same request but specifically for Matrixs)
