### ISSUE TITLE
Surfacing of actual Termination Reason in Step Status

### ISSUE THREAD

**Issue by chitrangpatel** [tektoncd/pipeline#7223]
## Current behaviour
Currently, Tekton only reports `Completed` and `Error` as `Terminated Reasons` in `Step` status after the `Step` terminates. 

The status `Error` is also applied to the `Steps` if it "times out" or if the previous `Step` failed and caused this to be "skipped".
Likewise, the status `Completed` is applied to the `Step` if it actually "completed with exit code 0" or if the `Step` actually errored but the `Task` set `onError: continue` for that `Step`.

The table below summarizes it.

| Termination Reason | Meaning |
|--------------|----------|
|Completed | Finished successfully with exit code 0|
|Completed | `Errored` but ignored since `onError` was set to `continue`.|
|Error | Actually failed with a non-zero exit code.|
|Error | timed out (but only the logs indicate that it timed out)|
|Error | skipped because the previous Step failed.|

This makes getting true visibility into the Steps challenging since the Termination reasons `Completed` and `Error` could mean different things.

## Proposed behaviour
In order to get better visibility into what's happening in the underlying `Steps`, here is the proposed changes to the Termination Reason in the `Step` status.

| Termination Reason | Meaning |
|--------------|----------|
|Completed | Finished successfully with exit code 0|
|Continued | `Errored` but ignored since `onError` was set to `continue`.|
|Error | Actually failed with a non-zero exit code.|
|TimeoutExceeded | timed out (but only the logs indicate that it timed out)|
|Skipped | skipped because the previous Step failed.|
|TaskRunCancelled| The task run was cancelled. |

/kind bug

**Comment by chengjoey** [comment]
Hi @chitrangpatel , Recently a Termination Reason `Canceled` has been added
https://github.com/tektoncd/pipeline/blob/a7d15ce59876405750154748e31312f3c63b17ab/pkg/entrypoint/entrypointer.go#L195-L201

Termination Reason: Canceled
Meaning: The step was stopped by user

Should this reason also be added to the table?

**Comment by chitrangpatel** [comment]
Yes, it should @chengjoey!

**Comment by pritidesai** [comment]
@shankarpentyala07 PTAL at the proposed changes to surface actual termination reason, thanks!

**Comment by renzodavid9** [comment]
Hey @shankarpentyala07! I just wanted to check if you are actively working in this issue. If not I would be happy to help with this. Thanks a lot! 😄

**Comment by shankarpentyala07** [comment]
Hi @renzodavid9 ,Thanks for checking.
 I am yet to start working , I would be happy to work together. Shall we have one meeting and discuss the changes. My email is shankarpentyala@gmail.com , available any time apart from 9am-11am PST.

**Comment by shankarpentyala07** [comment]
Hi @renzodavid9 - I have unassigned , please proceed.

**Comment by renzodavid9** [comment]
Got it! Thanks @shankarpentyala07! I just assigned this
