### ISSUE TITLE
Flake: waiter_test is flaky

### ISSUE THREAD

**Issue by Yongxuanzhang** [tektoncd/pipeline#7226]
It seems that after the merging of: https://github.com/tektoncd/pipeline/pull/6511
There are lots of failing flaky unit tests:
https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/7167/pull-tekton-pipeline-unit-tests/1714307892095488000
https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/7204/pull-tekton-pipeline-unit-tests/1714305917400387584
https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/7167/pull-tekton-pipeline-unit-tests/1714304663337046016
https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/7193/pull-tekton-pipeline-unit-tests/1714303905107546112

The PR itself also has several times of failures. We shouldn't ignore this by just re-running the tests when it is a new flaky test
https://prow.tekton.dev/pr-history/?org=tektoncd&repo=pipeline&pr=6511

/kind flake

**Comment by Yongxuanzhang** [comment]
@chengjoey do you want to take a look since you have more contexts?

**Comment by chengjoey** [comment]
because goroutine was added to entrypointer in #6511, the fakeWaiter append cancel file in the `TestEntrypointer` test is uncertain.https://github.com/tektoncd/pipeline/blob/6bb051379880d17931a50bd844dfcac03f7106e5/pkg/entrypoint/entrypointer.go#L175-L181

**Comment by chengjoey** [comment]
Version 0.52x and before
in the for loop, the file will be detected directly without waiting for the first time.
https://github.com/tektoncd/pipeline/blob/e7b5e5821a100d38a97eee50be60ce6580ec863e/cmd/entrypoint/waiter.go#L50-L75

in latest version:
for the first time, need to wait for `waitPollingInterval` before file detection is performed. The select statement block should be moved to the bottom
https://github.com/tektoncd/pipeline/blob/6bb051379880d17931a50bd844dfcac03f7106e5/cmd/entrypoint/waiter.go#L52-L88
