### ISSUE TITLE
Steps with workingDir refuse to start because the directory does not exist on pod startup

### ISSUE THREAD

**Issue by dicarlo2** [tektoncd/pipeline#725]
# Expected Behavior

We can set the workingDir to a subdirectory of the workspace directory (e.g. the one we plan to populate with a git repository).

# Actual Behavior

Pods fail because the containers can't `chdir` into a directory that does not exist. This is likely a bug due to the move from init containers (where the directory would have existed since they start in order).

# Steps to Reproduce the Problem

Create a task/taskrun with

1. a git input with targetPath "foo"
2. a step with workingDir "workspace/foo"

# Additional Info

**Comment by bobcatfish** [comment]
Ah nice one @dicarlo2  - I ran into this while dogfooding as well but wrote it off as https://github.com/moby/moby/issues/32708 and gave up on it (i think that's the same problem!)

Thanks for being proactive and pushing us to actually fix this XD
