### ISSUE TITLE
move getFeatureFlagsBaseOnAPIFlag from custom_task_test to another file

### ISSUE THREAD

**Issue by Yongxuanzhang** [tektoncd/pipeline#7269]
The [getFeatureFlagsBaseOnAPIFlag](https://github.com/tektoncd/pipeline/blob/8123d6332245008983aabe1dc910a63bd2c6f261/test/custom_task_test.go#L729) is used in multiple tests, and when developers want to introduce a new feature flag, they need to change this functions as well. 

It's not clear since the helper function is in `custom_task_test` and also cause confusions to reviewers. We should move it to another file

**Comment by Dhruval7878** [comment]
If this issue is still open then please assign me

**Comment by Yongxuanzhang** [comment]
> If this issue is still open then please assign me

Thanks!
