### ISSUE TITLE
unknown field `EnableCELInWhenExpression`

### ISSUE THREAD

**Issue by pritidesai** [tektoncd/pipeline#7278]
I am not sure why this only happening in my local setup or the CI is not able to catch such errors:

After installing the latest using `ko apply -f config/` and running a sample pipelineRun, I am experiencing a prolonged execution with this log message:

```
 kubectl apply -f examples/v1/pipelineruns/pipeline-with-displayname.yaml
```

Tekton Controller logs:

```
{"severity":"info","timestamp":"2023-10-25T17:18:04.601Z","logger":"tekton-pipelines-controller.event-broadcaster","caller":"record/event.go:285","message":"Event(v1.ObjectReference{Kind:\"TaskRun\", Namespace:\"default\", Name:\"sum-wct7l-sum-two-numbers\", UID:\"ae4f1f5d-3008-4414-8096-e2fff3a5d932\", APIVersion:\"tekton.dev/v1\", ResourceVersion:\"14004\", FieldPath:\"\"}): type: 'Warning' reason: 'UpdateFailed' Failed to update status for \"sum-wct7l-sum-two-numbers\": admission webhook \"webhook.pipeline.tekton.dev\" denied the request: mutation failed: cannot decode incoming new object: json: unknown field \"EnableCELInWhenExpression\"","commit":"44d77de-dirty"}
```

Is someone available to verify this? Appreciate if anyone can reproduce this 🙏

**Comment by chitrangpatel** [comment]
I was able to run it on my cluster locally after checking out main and then applying `ko apply -f config/`:

```
 chitrang@chitrang-macbookpro  ~/go/src/github.com/tektoncd/pipeline  ⇅ main   kubectl apply -f examples/v1/pipelineruns/pipeline-with-displayname.yaml
task.tekton.dev/sum created
pipeline.tekton.dev/sum-pipeline created
pipelinerun.tekton.dev/sum created
 chitrang@chitrang-macbookpro  ~/go/src/github.com/tektoncd/pipeline  ⇅ main  kubectl get pr sum
NAME   SUCCEEDED   REASON      STARTTIME   COMPLETIONTIME
sum    True        Succeeded   56s         32s
```

**Comment by QuanZhang-William** [comment]
I was not able to reproduce the issue:

``` bash
kubectl apply -f examples/v1/pipelineruns/pipeline-with-displayname.yaml
k get pr
NAME   SUCCEEDED   REASON      STARTTIME   COMPLETIONTIME
sum    True        Succeeded   4m1s        3m27s
```

And not able to find the related log:
```
k logs tekton-pipelines-controller-b8d94569f-tfm4g  -n tekton-pipelines | grep 'EnableCELInWhenExpression'
```

I guess maybe there are some older service are not deleted properly. Maybe try `ko delete -R -f config` first before installing?

**Comment by pritidesai** [comment]
yup looks like it, thank you @Yongxuanzhang, @chitrangpatel, and @QuanZhang-William for helping troubleshoot this. I was running webhook from the `latest` release with the controller from `main`. Running a clean delete and reapplying from `main`.

**Comment by pritidesai** [comment]
I was able to resolve this by deleting and recreating using `ko`. Thanks!

/close
