### ISSUE TITLE
[TaskResults] WHY are the Results of TaskRun appended to the terminated message?

### ISSUE THREAD

**Issue by Pangjiping** [tektoncd/pipeline#7293]
As shown below, our TaskRun generates multiple results, but I have noticed that they are present on each step's terminated message. 

```json
"status":{
        "completionTime":"2023-10-27T02:18:19Z",
        "conditions":[
            {
                "lastTransitionTime":"2023-10-27T02:18:19Z",
                "message":"All Steps have completed executing",
                "reason":"Succeeded",
                "status":"True",
                "type":"Succeeded"
            }
        ],
        "podName":"task-run-optionsbuild-16179526-pod",
        "startTime":"2023-10-27T02:17:55Z",
        "steps":[
            {
                "container":"step-diskprepare",
                "imageID":"******",
                "name":"diskprepare",
                "terminated":{
                    "containerID":"******",
                    "exitCode":0,
                    "finishedAt":"2023-10-27T02:18:02Z",
                    "message":"[{\"key\":\"diskprepare-cache-ratio\",\"value\":\"l0,1\",\"type\":1},{\"key\":\"diskprepare-perf-data\",\"value\":\"aone-build:shanggongtest[l0:431860656,418\",\"type\":1}]",
                    "reason":"Completed",
                    "startedAt":"2023-10-27T02:18:01Z"
                }
            },
            {
                "container":"step-setup-env",
                "imageID":"******",
                "name":"setup-env",
                "terminated":{
                    "containerID":"******",
                    "exitCode":0,
                    "finishedAt":"2023-10-27T02:18:04Z",
                    "message":"[{\"key\":\"diskprepare-cache-ratio\",\"value\":\"l0,1\",\"type\":1},{\"key\":\"diskprepare-perf-data\",\"value\":\"aone-build:shanggongtest[l0:431860656,418\",\"type\":1}]",
                    "reason":"Completed",
                    "startedAt":"2023-10-27T02:18:02Z"
                }
            },
            {
                "container":"step-build-package",
                "imageID":"******",
                "name":"build-package",
                "terminated":{
                    "containerID":"******",
                    "exitCode":0,
                    "finishedAt":"2023-10-27T02:18:11Z",
                    "message":"[{\"key\":\"diskprepare-cache-ratio\",\"value\":\"l0,1\",\"type\":1},{\"key\":\"diskprepare-perf-data\",\"value\":\"aone-build:shanggongtest[l0:431860656,418\",\"type\":1}]",
                    "reason":"Completed",
                    "startedAt":"2023-10-27T02:18:04Z"
                }
            },
            {
                "container":"step-build-image",
                "imageID":"******",
                "name":"build-image",
                "terminated":{
                    "containerID":"******",
                    "exitCode":0,
                    "finishedAt":"2023-10-27T02:18:17Z",
                    "message":"[{\"key\":\"diskprepare-cache-ratio\",\"value\":\"l0,1\",\"type\":1},{\"key\":\"diskprepare-perf-data\",\"value\":\"aone-build:shanggongtest[l0:431860656,418\",\"type\":1},{\"key\":\"results-docker-image-url\",\"value\":\"******\",\"type\":1}]",
                    "reason":"Completed",
                    "startedAt":"2023-10-27T02:18:12Z"
                }
            },
            {
                "container":"step-taskline-last",
                "imageID":"******",
                "name":"taskline-last",
                "terminated":{
                    "containerID":"******",
                    "exitCode":0,
                    "finishedAt":"2023-10-27T02:18:18Z",
                    "message":"[{\"key\":\"diskprepare-cache-ratio\",\"value\":\"l0,1\",\"type\":1},{\"key\":\"diskprepare-perf-data\",\"value\":\"aone-build:shanggongtest[l0:431860656,418\",\"type\":1},{\"key\":\"last-perf-data\",\"value\":\"aone-build:shanggongtest[ossa:16773005,982|pvc:415117746,638\",\"type\":1},{\"key\":\"results-docker-image-url\",\"value\":\"******\",\"type\":1}]",
                    "reason":"Completed",
                    "startedAt":"2023-10-27T02:18:17Z"
                }
            }
        ],
        "taskResults":[
            {
                "name":"diskprepare-cache-ratio",
                "type":"string",
                "value":"l0,1"
            },
            {
                "name":"diskprepare-perf-data",
                "type":"string",
                "value":"aone-build:shanggongtest[l0:431860656,418"
            },
            {
                "name":"results-docker-image-url",
                "type":"string",
                "value":"******"
            },
            {
                "name":"last-perf-data",
                "type":"string",
                "value":"aone-build:shanggongtest[ossa:16773005,982|pvc:415117746,638"
            }
        ]
    }
```

Is there any specific significance to this? 
I have looked into the source code of the pipeline and found that this is an unavoidable behavior, but I have not found any actions that depend on these messages. 
When there are a large number of results, this is a significant waste of resource storage in ETCD.

**Comment by vdemeester** [comment]
Hey @Pangjiping.

So the way `tektoncd/pipeline` *gets* the results is through the "termination message". And I think we do not control what Kubernetes does with it, as the fact that the "termination message" is attach to each containers of a Pod is a Kubernetes behavior that we cannot change (I think 😅). 

I do agree this is a relatively significant wase of resource storage in `etcd`, but I am not sure what alternative there is to this (except not relying on termination message anymore).

**Comment by jerop** [comment]
@Pangjiping you can try out an alpha feature that we have for larger Results through Sidecar logs instead of termination message -- [documentation](https://github.com/tektoncd/pipeline/blob/53f3516f51c7a9d4b299be81fe368f8102b48aff/docs/tasks.md#larger-results-using-sidecar-logs)

If you do, please share feedback in https://github.com/tektoncd/pipeline/issues/6133 as we work towards promoting it to beta -- cc @pritidesai

**Comment by Pangjiping** [comment]
> Hey @Pangjiping.
> 
> So the way `tektoncd/pipeline` _gets_ the results is through the "termination message". And I think we do not control what Kubernetes does with it, as the fact that the "termination message" is attach to each containers of a Pod is a Kubernetes behavior that we cannot change (I think 😅).
> 
> I do agree this is a relatively significant wase of resource storage in `etcd`, but I am not sure what alternative there is to this (except not relying on termination message anymore).

Thank you for your explanation. I seem to understand the design of using `termination message` in taskruns to convey results. Even though taskruns avoid using message, it is inevitable at the pod resource.

**Comment by Pangjiping** [comment]
> @Pangjiping you can try out an alpha feature that we have for larger Results through Sidecar logs instead of termination message -- [documentation](https://github.com/tektoncd/pipeline/blob/53f3516f51c7a9d4b299be81fe368f8102b48aff/docs/tasks.md#larger-results-using-sidecar-logs)
> 
> If you do, please share feedback in #6133 as we work towards promoting it to beta -- cc @pritidesai

Thanks, I have enabled this featuregate in our dev environment for a few weeks, and it did NOT produce any extra messages, which aligns with our expectations. Additionally, it seems that sidecarlog is functioning well, and we plan to enable this featuregate in our prod environment in the future.

Additionally, we are also exploring ways to extend the implementation of sidecarlog by abstracting it as a result PROXY. This would enable us to upload some extremely large results to remote storage (like OSS, Redis), which could expand the current result size limit (maximum of 1.5MB) by 1-2 orders of magnitude. Our custom scheduler will parse these specific results, similar to init container, and inject them into taskruns that depend on these results as a workspace. This feature is currently in the alpha phase, and if there is any progress or suggestions that can be incorporated into the community, I will provide timely updates in this issue.

- [ ]

**Comment by jerop** [comment]
@Pangjiping happy to hear that Results via Sidecar logs is working well. This is valuable feedback as we work towards promoting it to beta stability (note that it's alpha now).

I'm curious to learn more about the extension you're working on, and explore making it available to the community. You may also be interested in the Artifacts work we're doing, see https://github.com/tektoncd/community/pull/1044. Maybe you can join us in the weekly [data interface working group](https://github.com/tektoncd/community/blob/main/working-groups.md#data-interface) soon? I won't make it on 11/1 but planning to attend the other meetings in November
