### ISSUE TITLE
https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml does not seems updated to latest version

### ISSUE THREAD

**Issue by chmouel** [tektoncd/pipeline#7298]
latest at the time of writing this issue is [v0.53.0 ](https://github.com/tektoncd/pipeline/releases/tag/v0.53.0)and we are getting 0.52.1

```
% curl -s https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml|grep /release|head -1
    pipeline.tekton.dev/release: "v0.52.1"
```

/area plumbing
/kind misc

**Comment by vdemeester** [comment]
cc @afrittoli

**Comment by dibyom** [comment]
I think @afrittoli fixed this manually for now

**Comment by chmouel** [comment]
keeping this open in case there is some further task to do but feel free to close it if needed!
