### ISSUE TITLE
Display last updated time for Tasks, Pipelines, Resources

### ISSUE THREAD

**Issue by imjasonh** [tektoncd/pipeline#733]
# Expected Behavior

After updating a Task, Pipeline or Resource definition, `kubectl get pipeline my-pipeline` should give some indication of when it was last updated.

# Actual Behavior

Instead, it only displays the resource's age (time since creation), which is somewhat less helpful.

```
$ kubectl get pipeline my-pipeline
NAME            AGE
my-pipeline     14h
```

# Steps to Reproduce the Problem

1. Define a Task, Pipeline, Resource
2. Update it
3. `kubectl get` it

# Additional Info

TaskRuns and PipelineRuns have a `lastTransitionTime` in its `.Status.Conditions`, which is [configured to be displayed in `kubectl` output](https://github.com/tektoncd/pipeline/blob/master/config/300-taskrun.yaml#L41).

It probably makes sense for Pipelines, etc., to define Conditions too, which will give it a `lastTransitionTime` which I believe will be automatically updated by knative/pkg internals, and which might be useful in the future.

This also enables users to list resources sorted by last update time, or to only show recently-updated resources, etc.

cc @skim1420

**Comment by girishramnani** [comment]
I can work on this, the way to resolve this is same as https://github.com/tektoncd/pipeline/issues/615. I would have to add `additional-printer-columns` https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#additional-printer-columns

**Comment by bobcatfish** [comment]
@nikhil-thomas let me know if you want to be added to the `tektoncd` org and you can be assigned for real! (but either way we'll consider it assigned to you :) )

**Comment by nikhil-thomas** [comment]
@bobcatfish Thank you for adding me :+1:

**Comment by bobcatfish** [comment]
@piyush-garg are you still working on this?

**Comment by piyush-garg** [comment]
@bobcatfish Yaa, I am working on this. Sorry for the delay.

@ImJasonH The solution you suggested is to use Conditions. But I see the status for Pipeline or Task is deprecated. Should I use Conditions in Spec? or I remove the deprecation? or any other suggestions?

There is this issue https://github.com/kubernetes/kubernetes/issues/12430 for adding the field in ObjectMeta

cc @vdemeester @hrishin

**Comment by vdemeester** [comment]
ah good point, we remove those Status field because they weren't used at all :thinking: 
We may need to un-deprecated those… I'm interested in "which I believe will be automatically updated by knative/pkg internals, and which might be useful in the future" part :angel:

**Comment by AhmaudArbery** [comment]
Can this be worked on? I'm looking for a first issue to take on.

**Comment by vdemeester** [comment]
Of course :wink: You can do `/assign` to assign yourself to issue you are working on.

/assign @AhmaudArbery

**Comment by bobcatfish** [comment]
@AhmaudArbery and @JoaoVitoGomesa are you still working on this one?

**Comment by JoaoVitoGomes** [comment]
No feel free to remove me

**Comment by piyush-garg** [comment]
@bobcatfish I would love to work on this. I may need some time to look at the possible solutions now. Or do you have something in mind that can done for this? Outcomes from my previous try https://github.com/tektoncd/pipeline/issues/733#issuecomment-572013166

**Comment by piyush-garg** [comment]
@bobcatfish @vdemeester @ImJasonH 

The last updation time can be retrieved from `metadata.managedFields` also. But this is an array and for every different method, it does add an element to array like `kubectl, oc, controller` and each have their own last time.
