### ISSUE TITLE
Cannot find referenced task

### ISSUE THREAD

**Issue by MrMrAnderson** [tektoncd/pipeline#7402]
# Expected Behavior
The pipeline should be calling a remote task

# Actual Behavior
Error message:
There was an error while processing the payload: cannot find referenced task [TASKNAME]. if it's a remote task make sure to add it in the annotations

# Steps to Reproduce the Problem

1. create pipeline run where in annotations you reference the files you will use
2. create a pipeline to specify the tasks to be executed in which order that you want
3. create the task that will do the work

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
/
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
/
```

**Comment by vdemeester** [comment]
Hey @MrMrAnderson, are you using [`pipelines-as-code`](https://github.com/openshift-pipelines/pipelines-as-code/) ? There is no concept of "annotations" to fetch a remote task *except* in pipelines-as-code ([documentation](https://pipelinesascode.com/docs/guide/resolver/#remote-task-annotations)).

**Comment by MrMrAnderson** [comment]
Hey @vdemeester, yes I am using pipelines-as-code, sorry i'm still a junior in this domain so I barely even know what a pipeline is :,)

**Comment by vdemeester** [comment]
@MrMrAnderson alright, can you re-create this issue on the [`pipelines-as-code`](https://github.com/openshift-pipelines/pipelines-as-code/) repository then ? Can you also add a bit more detailed, like the `PipelineRun` yaml used, etc..

I'll close this issue as it's an issue that should be reported on [`pipelines-as-code`](https://github.com/openshift-pipelines/pipelines-as-code/) and not on `tektoncd/pipeline` upstream project.
