### ISSUE TITLE
TEP-0142: Improve e2e tests, examples and documentation

### ISSUE THREAD

**Issue by jerop** [tektoncd/pipeline#7421]
StepActions is introduced in v0.54, this issue tracks improvements to e2e tests, examples and documentation

**Comment by Yongxuanzhang** [comment]
Thanks! I will add e2e tests for params

**Comment by vdemeester** [comment]
Closing this umbrella tracking issue for TEP-0142. The documentation, examples and testing improvements it tracked have been addressed through multiple PRs (#7441 and others). Ongoing test and docs improvements are tracked in their own individual issues (e.g. #9201, #9191, #9499, #9559, #9670).
