### ISSUE TITLE
AffinityAssistantPerPipelineRunWithIsolation is not implemented

### ISSUE THREAD

**Issue by lwabish** [tektoncd/pipeline#7440]
According to https://tekton.dev/vault/pipelines-main/affinityassistants/, I want to enable **isolate pipelinerun** mode.

I have changed these values in feature-flags configmap,but pipelinerun throws `AffinityAssistantPerPipelineRunWithIsolation is not implemented` error message.
```
enable-api-fields=alpha
disable-affinity-assistant=true
coschedule=isolate-pipelinerun 
```

version: v0.50.3
task/taskrun/pipeline/pipelinerun apiversion: v1beta1

Is there anything more I could do to enable **isolate pipelinerun** feature?

**Comment by QuanZhang-William** [comment]
Hi @lwabish. The `coschedule: isolate-pipelinerun` feature is in release `v0.51.0`.  Could you please try the newer release?

(The feature was WIP in `v0.50` release, so you may see part of the feature working...)

I have also updated doc to make it explicit: https://github.com/tektoncd/pipeline/pull/7444

**Comment by QuanZhang-William** [comment]
@lwabish, can we close the issue if it is resolved?

**Comment by lwabish** [comment]
> @lwabish, can we close the issue if it is resolved?

Ok, I'll try it later.
