### ISSUE TITLE
Fail to parse .gitconfig

### ISSUE THREAD

**Issue by tetra12** [tektoncd/pipeline#7456]
I wanna use `ssh` instead of `https` to check out submodules in a git repo.

I have `private submodules` in a `private` git repo. I'm **able** to clone the parent dir without submodules. It is failing to clone `submodules`  with the error: `fatal: could not read Username for 'https://gitlab.com': No such device or address`

My solution is to update `.gitconfig` with `[url "git@github.com:"] insteadOf = https://github.com/` which works on my lap.
However, `tekton hub` module `git-clone` fails to parse the base64 encoded `.gitconfig` with the following:
```
[git-clone : clone] + git config --global --add safe.directory /workspace/output
[git-clone : clone] + /ko-app/git-init '-url=git@<hidded>.git' '-revision=main' '-refspec=' '-path=/workspace/output/' '-sslVerify=true' '-submodules=true' '-depth=1' '-sparseCheckoutDirectories='
[git-clone : clone] {"level":"warn","ts":1701644349.0057952,"caller":"git/git.go:271","msg":"URL(\"git@github.com:<hidden>.git\") appears to need SSH authentication but no SSH credentials have been provided"}
[git-clone : clone] {"level":"error","ts":1701644349.0627475,"caller":"git/git.go:53","msg":"Error running git [fetch --recurse-submodules=yes --depth=1 origin --update-head-ok --force main]: exit status 128\n/home/git/.ssh/config line 1: no argument after keyword \"[user]\"\r\n/home/git/.ssh/config: line 2: Bad configuration option: name\r\n/home/git/.ssh/config: line 3: Bad configuration option: email\r\n/home/git/.ssh/config line 4: no argument after keyword \"[pull]\"\r\n/home/git/.ssh/config: line 5: Bad configuration option: rebase\r\n/home/git/.ssh/config: line 6
```

# Expected Behavior
Parse `.gitconfig` with the following data:
```
[user]
        name = dummy
        email = dummy@mail.me
[pull]
        rebase = false
[url "git@github.com:"]
        insteadOf = https://github.com/
[url "git@gitlab.com:"]
        insteadOf = https://gitlab.com/
[init]
        defaultBranch = main

```

# Actual Behavior
```
no argument after keyword \"[user]\"\r\n/home/git/.ssh/config: line 2: Bad configuration option: name\r\n/home/git/.ssh/config: line 3: Bad configuration option: email\r\n/home/git/.ssh/config line 4: no argument after keyword \"[pull]
```

# Steps to Reproduce the Problem
```
cat .gitconfig
[user]
        name = dummy
        email = dummy@mail.me
[pull]
        rebase = false
[url "git@github.com:"]
        insteadOf = https://github.com/
[url "git@gitlab.com:"]
        insteadOf = https://gitlab.com/
[init]
        defaultBranch = main
```
```
cat .gitconfig | base64 -w0 > gitconfigb64
```
```
cat git-secret.yml
---
apiVersion: v1
kind: Secret
metadata:
  name: git-bku-ssh
type: Opaque
data:
  config: <base64-from-gitconfigb64>
  id_rsa: <base64-redacted>
  known_hosts: <base64-redacted>
```

# Additional Info
- Git version
```
2.34.1
```

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: v1.28.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
Client version: 0.33.0
Pipeline version: v0.54.0
Dashboard version: v0.42.0
```

- Kind version:
```
kind v0.20.0 go1.21.4 linux/amd64
```

**Comment by vdemeester** [comment]
👋🏼 @tetra12. I am wondering if the "CR/LF" is not an issue there ; from the logs, it appears the encoded `gitconfig` contains `\r\n` and the error also inclue it in the log `Bad configuration option: name\r\n`.

- What version of the `git-clone` task are you using ?
- This could be either a `git-init` image shipping with a too old git version (it would be weird but.. maybe ?) or the CRLF handling in git.
- This can be "worked-around" but changing the CRLF to normal to LF (`\n`) — it's usually done in the settings of the editor (like vscode, …)

**Comment by tetra12** [comment]
@vdemeester Hi Vincent
1. I'm using `0.9-latest` for `git-clone`
2. As I wrote, I use the following to `base64` encode: `cat .gitconfig | base64 -w0 > gitconfigb64`
This works well and I double checked it with: `cat gitconfigb64 | base64 -w0 -d`
3. I use VSCode to open the `gitconfigb64` file and paste it to my `ssh-secret.yml` as a single line

:eyes:  [sshconfig.txt](https://github.com/tektoncd/pipeline/files/13543768/sshconfig.txt)

4. You can suggest your own option on how to encode the `.gitconfig` . And update docs with that :100:

**Comment by tetra12** [comment]
@vdemeester The **actual** issue here is how to clone a `private repo` with `private submodules`. Any suggestions? :roll_eyes:

**Comment by tetra12** [comment]
@vdemeester Nein, that doesn't work either :roll_eyes: 
```sh
> cat .gitconfig | tr -d '[:blank:]' | tr -d '[:space:]' | base64 -w0            
W3VzZXJdbmFtZT10YW1wbGVyZW1haWw9c29jbmV0ZnBnYUBnbWFpbC5jb21bcHVsbF1yZWJhc2U9ZmFsc2VbdXJsImdpdEBnaXRodWIuY29tOiJdaW5zdGVhZE9mPWh0dHBzOi8vZ2l0aHViLmNvbS9bdXJsImdpdEBnaXRsYWIuY29tOiJdaW5zdGVhZE9mPWh0dHBzOi8vZ2l0bGFiLmNvbS9baW5pdF1kZWZhdWx0QnJhbmNoPW1haW4=
```
The problem still persists without any idents at  all!

PS: My problem was actually solved when I updated links in my `submodules`. It turned out that there were `some` modules with the `git` link, and others were with `https`. I moved all `submodules` deps into `git` links and **removed** `config` field from my `yaml` at all. That solved my issue with submodules.

1. Do you have a test for parsing `.gitconfig`? 
2. If you still think that there's no issue with parsing `.gitconfig`, I'm ok to close this issue since **my problem** was solved

**Comment by vdemeester** [comment]
> * Do you have a test for parsing `.gitconfig`?

We do not as we never, in `tektoncd/pipeline` parse the `.gitconfig`. Even in the `Task` itself (from `tektoncd/catalog`) we are not parsing `.gitconfig`, it's the `git` binary that does the parsing, never any go code we produce.

> * If you still think that there's no issue with parsing `.gitconfig`, I'm ok to close this issue since **my problem** was solved

👌🏼
