### ISSUE TITLE
Upstream error messages reference shall be used from imports

### ISSUE THREAD

**Issue by JeromeJu** [tektoncd/pipeline#7466]
# Context:
[OptimisticLockErrorMsg](https://github.com/kubernetes/kubernetes/blob/55f2bc10435160619d1ece8de49a1c0f8fcdf276/staging/src/k8s.io/apiserver/pkg/registry/generic/registry/store.go#L240) is an error message exported from [k8s.io/apiserver/pkg/registry/generic/registry](https://pkg.go.dev/k8s.io/apiserver/pkg/registry/generic/registry#pkg-constants). But the import of the package is blocked as noted at https://github.com/tektoncd/pipeline/issues/7464. 

This issue tracks that once we have the dependencies bumped successfully with the fix of #7464, we shall reference the const created in pipeline to the upstream constants for consistency and maintainability.

/kind cleanup

**Comment by pritidesai** [comment]
Hey @JeromeJu, we have the dependencies fixed for this issue, is this issue unblocked?

**Comment by JeromeJu** [comment]
@pritidesai yes this is unblocked by https://github.com/tektoncd/pipeline/issues/7464.
Thanks for adding the label 🙏

**Comment by lunarwhite** [comment]
I'd like to help with it.

/assign
