### ISSUE TITLE
TEP-0142: Dogfood StepActions

### ISSUE THREAD

**Issue by jerop** [tektoncd/pipeline#7478]
Convert some of our sequential Pipelines into Tasks using StepActions on the dogfooding cluster (assuming it has >v0.54 installed) ~ @chitrangpatel

**Comment by chitrangpatel** [comment]
We are now dogfooding StepActions for the CI test:
https://dashboard.dogfooding.tekton.dev/#/namespaces/tekton-ci/pipelineruns/run-go-coverage-88vft?pipelineTask=clone-coverage-upload&step=coverage
