### ISSUE TITLE
allow controller to be configured to watch a single namespace

### ISSUE THREAD

**Issue by jstrachan** [tektoncd/pipeline#751]
some clusters get locked down so getting clusterroles applied can be challenging; so it'd be nice to have a namespace CLI argument / environment variable so that the tekton controller can be configured to watch a specific namespace only for CRDs rather than always `v1.NamespaceAll`

then if a namespace is specified it'd call `.WithNamespace(ns)` on the informer factory stuff: https://github.com/tektoncd/pipeline/blob/c3910c31a73db8357eecf15b02c060b97ec0ea64/cmd/controller/main.go#L104

**Comment by jstrachan** [comment]
this will also make it easier for us to test tekton in preview environments (in temporary namespaces for each PR etc)

**Comment by abayer** [comment]
My gut instinct is to add this as a flag to the controller - defaulting to all namespaces, optionally scoping to a single namespace. @vdemeester, @bobcatfish, @dlorenc, @ImJasonH - does that sound like the right approach to y'all?

**Comment by jstrachan** [comment]
I don't mind whether its an environment variable or CLI flag; I find environment variables are easier to conditionally add in YAML but its not a biggie

**Comment by dlorenc** [comment]
> My gut instinct is to add this as a flag to the controller - defaulting to all namespaces, optionally scoping to a single namespace. @vdemeester, @bobcatfish, @dlorenc, @ImJasonH - does that sound like the right approach to y'all?

This makes sense to me.
