### ISSUE TITLE
Cluster PipelineResources should be able to reference cluster-registry

### ISSUE THREAD

**Issue by gorkem** [tektoncd/pipeline#752]
`PipelineResources` of type `cluster` defines the similar kind of data as [Cluster-registry ](https://github.com/kubernetes/cluster-registry) APIs that comes from kubernetes multicluster-sig. It should be possible for the `cluster` `PipelineResource` to reuse or reference clusters that are defined as part of the cluster registry.

**Comment by bobcatfish** [comment]
Hey @gorkem !

Apologies for the delayed reply - I'm not familiar with the cluster registry API, could you give us an example of what it might look like to define a `cluster` `PipelineResource` that references the cluster registry?

**Comment by bobcatfish** [comment]
Closing this for now, please re-open if needed.
