### ISSUE TITLE
Complete CII Best Practices Badge

### ISSUE THREAD

**Issue by caniszczyk** [tektoncd/pipeline#753]
Generally a good thing to do recommended for all LF related sub foundation projects:
https://bestpractices.coreinfrastructure.org/en

**Comment by bobcatfish** [comment]
Notes to self:

- [ ] Do this for all repos
- [ ] Once this is done, I should add this to our docs on the process for adding new repos

**Comment by bobcatfish** [comment]
I started turning this on for tektoncd/pipeline, looks like the next thing to do is fill in a bunch of questions at https://bestpractices.coreinfrastructure.org/en/projects/4020/edit

**Comment by afrittoli** [comment]
/lifecycle frozen This should be open until it's fixed

**Comment by afrittoli** [comment]
Implemented - see https://github.com/tektoncd/community/issues/805
