### ISSUE TITLE
Move to CDF/LF CLA

### ISSUE THREAD

**Issue by caniszczyk** [tektoncd/pipeline#754]
We need to move to the LF/CDF CLA.

**Comment by caniszczyk** [comment]
I will connect @dlorenc with the LF IT folks to make this happen

**Comment by dlorenc** [comment]
Just chatted with Vasu from the LF on this. There's a backlog of a few weeks to get new projects onboarded to the LF CLA, but we're on the list now. I'll share some more info on the exact timeline and process shortly.

**Comment by afrittoli** [comment]
Thanks for this. For corporate contributors, does the CDF require companies to sign a dedicated CCLA?

**Comment by dlorenc** [comment]
@afrittoli  The CLA will be the standard LF one.

**Comment by dlorenc** [comment]
Update here: still waiting on the LF to setup the right automation for this.

**Comment by vdemeester** [comment]
@dlorenc should we retry the LF CLA on `experimental` or some other repository ?

**Comment by danlopez00** [comment]
@dlorenc LF EasyCLA team is also working on some of the issues and coordinating. For reference

https://github.com/communitybridge/easycla/issues/400
https://github.com/communitybridge/easycla/issues/401

**Comment by bobcatfish** [comment]
I think this is the CLA we're talking about https://github.com/cdfoundation/cla ? p.s. any update here @danlopez00 ?

**Comment by bobcatfish** [comment]
ITS FINALLY HAPPENED!!! 🎉 🎉🎉

**Comment by bobcatfish** [comment]
Shout out in particular to Heather Willson from EasyCLA for helping us out!! 🙏
