### ISSUE TITLE
Tekton buildid task not able to apply

### ISSUE THREAD

**Issue by tppalani** [tektoncd/pipeline#7636]
# Expected Behavior

generate-build-id Task should applied 

# Actual Behavior

I'm trying to configure the generate-build-id inside my tekton, i followed the steps according catalog page when i'm trying to install build-service-api task yaml i'm getting below error.
kubectl apply -f https://api.hub.tekton.dev/v1/resource/tekton/task/generate-build-id/0.1/raw ( Already Installed)
k apply -f build-service-api.yaml
error: resource mapping not found for name: "build" namespace: "dev-pipeline" from "build-service-api.yaml": no matches for kind "Task" in
version "[tekton.dev/v1betal](http://tekton.dev/v1betal)"
ensure CRDs are installed first

# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:*1.26*

```
(1.26)
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
(0.48.0)
```

**Comment by vdemeester** [comment]
Hey @tppalani, `version "tekton.dev/v1betal"` seems weird, it should be `tekton.dev/v1beta1` (or `tekton.dev/v1`).

**Comment by vdemeester** [comment]
I am going to go ahead and close. @tppalani feel free to ask me to re-open if it's not fixed.

**Comment by tppalani** [comment]
@vdemeester  Thanks for your help
