### ISSUE TITLE
Tekton Migrating From paketobuildpacks/builder:base To paketobuildpacks/builder-jammy-base

### ISSUE THREAD

**Issue by lhmoraes** [tektoncd/pipeline#7647]
The Tekton pipeline was working fine until the migration to Jammy.  The only pipeline change was in the image builder name

1. On the "**task-build-packs**" the "**prepare**" step works fine and I can see the permissions being applied:

```
> Setting permissions on '/workspace/cache'...
> Setting permissions on '/tekton/home'...
> Setting permissions on '/layers'...
> Setting permissions on '/workspace/source'...
> Parsing additional configuration...
-> Parsing env variables...
> Processing any environment variables...
--> Creating 'env' directory: /platform/env
--> Writing /platform/env/BP_NATIVE_IMAGE...
--> Writing /platform/env/BP_JVM_VERSION...
--> Writing /platform/env/BP_GRADLE_BUILD_ARGUMENTS...
--> Writing /platform/env/BP_GRADLE_BUILT_ARTIFACT...
--> Writing /platform/env/REPOSITORY_NAME...
--> Writing /platform/env/REPOSITORY_URL...
--> Writing /platform/env/REPOSITORY_USERNAME...
--> Writing /platform/env/REPOSITORY_PASSWORD...
```

2. Then the second task "**create**" fails with the error below:

```
ERROR: failed to exec as user 1001:1000: operation not permitted
```

**Comment by AlanGreene** [comment]
Hi @lhmoraes, can you provide more information about the issue you're seeing and why you think it might be a bug in Tekton Pipelines?

I see you've also opened an issue on the paketo-buildpacks repo: https://github.com/paketo-buildpacks/builder-jammy-base/issues/430, and at first glance it seems that might be the more appropriate location for your issue.

If you do think this is a bug with Tekton Pipelines please provide more information to help reproduce and debug it, for example:
- the Pipelines version affected
- Kubernetes version
- resources being used (e.g. any Task, Pipeline, and PipelineRun definitions used to reproduce the issue)
- any other relevant information to help reproduce the issue. You say this was working before, what has changed?
- etc.
