### ISSUE TITLE
`StepAction` hub/catalog resolver support 

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/pipeline#7668]
### Feature request

Make sure we can pull `StepAction` from the hub/catalog resolver, and also that we can configure the default "catalog" for them (similar to `Task` and `Pipeline`)

### Use case

This is kind-of a follow-up of https://github.com/tektoncd/catalog/issues/1218 (and part of https://github.com/tektoncd/pipeline/issues/7424)

**Comment by chitrangpatel** [comment]
This is now implemented: https://github.com/artifacthub/hub/issues/3677#issuecomment-2034005179 

@vdemeester can we close this issue now? 

We have support for StepActions on our GitHub catalog, Tekton Bundles and ArtifactHub.

**Comment by vdemeester** [comment]
@chitrangpatel if we have tests already that get some `stepaciton` using the `hub` resolvers, yes we can 😉
