### ISSUE TITLE
TEP-0147 Phase 1 implementation Plan 

### ISSUE THREAD

**Issue by ericzzzzzzz** [tektoncd/pipeline#7693]
- Implementation plan for [TEP-0147](https://github.com/tektoncd/community/blob/main/teps/0147-tekton-artifacts-phase1.md)
 - #7700
  - #7699 
  - #7708 .
  - #7713
  -  #7717
  -  #7870
  - #7869
    - create container image
    - produce artifacts with the image 

## Improvements
 - #7871

**Comment by chitrangpatel** [comment]
Closing this Thanks @ericzzzzzzz !!
