### ISSUE TITLE
During configuration : executing 'ko apply -R -f config/'

### ISSUE THREAD

**Issue by rgahockey** [tektoncd/pipeline#7738]
# Expected Behavior
expected the ko command to succeed without error - this is within the context of configuring a development enviroment on Ubuntu 22.04

# Actual Behavior
Error: error processing import paths in "config/controller.yaml": error resolving image references: build: go build: exit status 1: cmd/workingdirinit/main.go:20:2: package log is not in std (/usr/local/src/log)
cmd/workingdirinit/main.go:21:2: package os is not in std (/usr/local/src/os)
cmd/workingdirinit/main.go:22:2: package path/filepath is not in std (/usr/local/src/path/filepath)
cmd/workingdirinit/main.go:23:2: package runtime is not in std (/usr/local/src/runtime)
cmd/workingdirinit/main.go:24:2: package strings is not in std (/usr/local/src/strings)

# Steps to Reproduce the Problem

1. Follow all steps to configuring a development environment

# Additional Info

I observed that /usr/local/src is completely empty

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.3
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
 kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'
error: error executing jsonpath "{.items[0].metadata.labels.version}": Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the template:
	template was:
		{.items[0].metadata.labels.version}
	object given to jsonpath engine was:
		map[string]interface {}{"apiVersion":"v1", "items":[]interface {}{}, "kind":"List", "metadata":map[string]interface {}{"resourceVersion":""}}
```

**Comment by vdemeester** [comment]
Hey @rgahockey, thanks for the issue. Not sure about the `/usr/local/src` (might come from the way `go` was compiled). Anyway, the error in there is `package log is not in std (/usr/local/src/log)`, which more or less means it can't find the go standard library code (`std`). Essentially, this means something is wrong with your `go` setup – if you look at `go env`, there is a `GOROOT` that should point to the standard library code, if it is empty or doesn't exists, you can't compile too much go code 😅

**Comment by rgahockey** [comment]
Hi Vincent,

My co-worker and I spent over 5 hours starting at 8:00 am EST today to try and get my tekton development environment set up. This involved an incredible amount of trial and error. Apparently, many changes have occurred over the past two weeks. I created another issue as we got past this original problem.

Look at this newest issue because I am curious if anyone has encountered this same problem.

You can close this first issue as I have gotten past this problem.


Regards,

Russ Anderson
CP4D/RedHat/AWS Certifications
IBM Expert Labs
Mobile: +1 603-213-1974
Email: ***@***.******@***.***>
https://www.linkedin.com/in/russell-anderson-ba357116/


Vacation ALERT : April 22-26

From: Vincent Demeester ***@***.***>
Date: Tuesday, March 5, 2024 at 9:52 AM
To: tektoncd/pipeline ***@***.***>
Cc: RUSSELL Anderson ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [tektoncd/pipeline] During configuration : executing 'ko apply -R -f config/' (Issue #7738)
Hey @rgahockey, thanks for the issue. Not sure about the /usr/local/src (might come from the way go was compiled). Anyway, the error in there is package log is not in std (/usr/local/src/log), which more or less means it can't find the go standard
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
<https://us-phishalarm-ewt.proofpoint.com/EWT/v1/PjiDSg!2U-pSBUXwVJQ0KZT06lPJVxE_H4YxWR-UXdVVYKy-sa5ZWxNxTQApTJa87Lq1_aMoeWSoHGypclehd3oROuPeKstJgq5TOjCfl0$>
Report Suspicious <https://us-phishalarm-ewt.proofpoint.com/EWT/v1/PjiDSg!2U-pSBUXwVJQ0KZT06lPJVxE_H4YxWR-UXdVVYKy-sa5ZWxNxTQApTJa87Lq1_aMoeWSoHGypclehd3oROuPeKstJgq5TOjCfl0$>


ZjQcmQRYFpfptBannerEnd

Hey @rgahockey<https://github.com/rgahockey>, thanks for the issue. Not sure about the /usr/local/src (might come from the way go was compiled). Anyway, the error in there is package log is not in std (/usr/local/src/log), which more or less means it can't find the go standard library code (std). Essentially, this means something is wrong with your go setup – if you look at go env, there is a GOROOT that should point to the standard library code, if it is empty or doesn't exists, you can't compile too much go code 😅
