### ISSUE TITLE
horizontalpodautoscaler.autoscaling/tekton-pipelines-webhook unchanged Error: error processing import paths in "config/events.yaml": error resolving image references: HEAD https://osstektonpipleine.cp4d-de-1.aws-cpd-daell.com:5000/v2/events-a9042f7efb0cbade2a868a1ee5ddd52c/manifests/latest: unexpected status code 401 Unauthorized (HEAD responses have no body, use GET for details)

### ISSUE THREAD

**Issue by rgahockey** [tektoncd/pipeline#7739]
# Expected Behavior

Development environment with a private docker-registry should succeed 

# Actual Behavior
The error in the title appears to be something new and need suggestions on how to resolve it.

# Steps to Reproduce the Problem

1. Go through the many steps of getting the private registry and cert created.
2. The error occurs on the 'ko apply -R -f config/'

# Additional Info

- Kubernetes version:

Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.3

```
(paste your output here)
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
(paste your output here)
```

**Comment by vdemeester** [comment]
Hey @rgahockey, the error state that there is a 401 (unauthorized) response, when building and pushing the `cmd/events` image. This means, the *process*/*system* that runs the `ko apply …` most likely doesn't have the proper registry credential set up, *or* it cannot push to a repository call `osstektonpipleine.cp4d-de-1.aws-cpd-daell.com:5000/v2/events-a9042f7efb0cbade2a868a1ee5ddd52c` for some reason.

- Where do you run `ko apply …` ?
- Can you check the registry logs ?

**Comment by rgahockey** [comment]
I have resolved my configuration issues
