### ISSUE TITLE
Tekton upgrade to v0.56.2 is broken 

### ISSUE THREAD

**Issue by rashedkvm** [tektoncd/pipeline#7759]
# Expected Behavior

Expected to upgrade tekton from `v0.50.3` to `v0.56.2` to be installed on the cluster

# Actual Behavior

Error while upgrading to `v0.56.2`

```sh
Error from server (BadRequest): error when applying patch:
{"data":{"enable-cel-in-whenexpression":"false","enable-param-enum":"false","enable-step-actions":"false","enforce-nonfalsifiability":"none","enforce-nonfalsifiablity":null,"keep-pod-on-cancel":"false"},"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"v1\",\"data\":{\"await-sidecar-readiness\":\"true\",\"coschedule\":\"workspaces\",\"disable-affinity-assistant\":\"false\",\"disable-creds-init\":\"false\",\"enable-api-fields\":\"beta\",\"enable-cel-in-whenexpression\":\"false\",\"enable-param-enum\":\"false\",\"enable-provenance-in-status\":\"true\",\"enable-step-actions\":\"false\",\"enable-tekton-oci-bundles\":\"false\",\"enforce-nonfalsifiability\":\"none\",\"keep-pod-on-cancel\":\"false\",\"require-git-ssh-secret-known-hosts\":\"false\",\"results-from\":\"termination-message\",\"running-in-environment-with-injected-sidecars\":\"true\",\"send-cloudevents-for-runs\":\"false\",\"set-security-context\":\"false\",\"trusted-resources-verification-no-match-policy\":\"ignore\"},\"kind\":\"ConfigMap\",\"metadata\":{\"annotations\":{},\"labels\":{\"app.kubernetes.io/instance\":\"default\",\"app.kubernetes.io/part-of\":\"tekton-pipelines\"},\"name\":\"feature-flags\",\"namespace\":\"tekton-pipelines\"}}\n"}}}
to:
Resource: "/v1, Resource=configmaps", GroupVersionKind: "/v1, Kind=ConfigMap"
Name: "feature-flags", Namespace: "tekton-pipelines"
for: "https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.56.2/release.yaml": error when patching "https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.56.2/release.yaml": admission webhook "config.webhook.pipeline.tekton.dev" denied the request: validation failed: invalid value for feature flag "enforce-nonfalsifiability": "none"
```

# Steps to Reproduce the Problem

1. Install tekton `v0.50.3`
```sh
kubectl apply -f https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.50.3/release.yaml 
```
2. Upgrade tekton to `v0.56.2`
```sh
kubectl apply -f https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.56.2/release.yaml 
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.0
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
Client version: 0.35.1
Pipeline version: v0.56.2
```

**Comment by rashedkvm** [comment]
Perhaps related to the change introduced #6937

**Comment by vdemeester** [comment]
@rashedkvm most likely that's the case. 
This is a tricky problem to solve. I do not exactly remember on which issue we discussed it, but using `kubectl apply` to upgrade from one release to the other is not really guaranteed to work. The main reason is that `kubectl apply` does merge the existing object and the "new" ones (the new release yaml). This can lead to errors such as what you got, *or* things where the CRD(s) still have the `v1alpha1` "element" on the cluster, even though it's gone from the `release.yaml`.

This is where things like the [operaton](https://github.com/tektoncd/operator) or an helm chart are useful.

There is *very* little we can do from `tektoncd/pipeline`, at least from how we do our release, today…

**Comment by rszumlakowski** [comment]
Hi @vdemeester.  What's your recommendation however for us to go forward?

**Comment by vdemeester** [comment]
Indeed, using operator, or having some "manual" maintenance planning. Here, it is a simple fix, you just need to update the configmap (commenting that field), and re-applying.

**Comment by rashedkvm** [comment]
@vdemeester you can mark this issue resolved. In our case,  we are using the [carvel tools](https://carvel.dev/) to manage the upgrade of Tekton between LTS versions. Thanks!

**Comment by vdemeester** [comment]
Sounds good @rashedkvm 👍🏼
