### ISSUE TITLE
Design: Support for Manipulating PullRequests

### ISSUE THREAD

**Issue by dlorenc** [tektoncd/pipeline#778]
# Expected Behavior

Task/Runs should be able to declaratively manipulate PullRequests (across SCM providers), similarly to how they can manipulate Images, k8s Clusters, and the other PipelineResources.

# Actual Behavior

This is not possible today.

# Additional Info

Potential Design Document/PRD: https://docs.google.com/document/d/1MXy-AOZmrgNusX710MgeERin_RkjNhnl0P5e5-ROhuc/edit (shared with tekton-dev@googlegroups.com)

**Comment by bobcatfish** [comment]
Especially since this issue is just about design, I think we can close the issue, unless you think otherwise @wlynch !

**Comment by wlynch** [comment]
SGTM

**Comment by bobcatfish** [comment]
This has been implemented! (Thanks @wlynch !! 🎉 )
