### ISSUE TITLE
Bundle resolver from private ECR registries

### ISSUE THREAD

**Issue by wilstdu** [tektoncd/pipeline#7854]
I'm looking for a workflow to use bundle resolver with bundled images (tkn bundle) from Amazon ECR private repositories.

With the previous bundle resolver implementation (when it still used ServiceAccounts for auth) my use-case worked, but with Secrets approach (https://github.com/tektoncd/pipeline/commit/0fa076e983593e564b10ca5bba1d78336ce7e91d) it no longer works, because ECR uses short-lived tokens (up to 12 hours if not mistaken) for auth and I cannot just add something once to the secret and use it for long. I would then need to build some kind of mechanism (maybe simply CronJob) in front that generates the token every X hours and replaces it in the secret - and this doesn't sound like a good approach to me.

Also another question - where do secrets have to be deployed? In all namespaces where pipelines reference the bundle or in just a single namespace that Tekton looks for?

Related topics: 
- https://github.com/tektoncd/pipeline/issues/7159 (initiative for Service Accounts replacement to Secrets approach)

**Comment by wilstdu** [comment]
@shruthipuranik @Yongxuanzhang @vdemeester - maybe you have some ideas on this topic?
I'd really appreciate some feedback and if there is really a gap, we'd be more than happy to fill it and restore ServiceAccount approach to work side-by-side with the secret approach.

Related to this issue: https://github.com/tektoncd/pipeline/pull/7331

**Comment by vdemeester** [comment]
> Also another question - where do secrets have to be deployed? In all namespaces where pipelines reference the bundle or in just a single namespace that Tekton looks for?

They need to be deployed in the namespace the `TaskRun` or `PipelineRun` that reference the tekton bundle is.

Reading this issue, it does indeed sounds like a gap, or at least something we need to provide a better ux than having to "manually" rotate secrets.
