### ISSUE TITLE
Liniting errors

### ISSUE THREAD

**Issue by chmouel** [tektoncd/pipeline#794]
I have launched [golangci](https://github.com/golangci/golangci-lint) on the codebase and there is quite a lot of errors reported in there that may be useful to address/cleanup : 

<details>
<summary>
golangci errors list
</summary>

test/builder/doc.go:63:2: `defaultAPIVersion` is unused (varcheck)
	defaultAPIVersion = "a1"
	^
pkg/apis/pipeline/v1alpha1/build_gcs_resource.go:51:5: `validArtifactTypes` is unused (varcheck)
var validArtifactTypes = []string{string(GCSArchive), string(GCSManifest)}
    ^
pkg/reconciler/v1alpha1/pipelinerun/pipelinerun.go:73:2: `eventReasonSucceeded` is unused (varcheck)
	eventReasonSucceeded = "PipelineRunSucceeded"
	^
pkg/client/clientset/versioned/fake/register.go:29:5: `parameterCodec` is unused (varcheck)
var parameterCodec = runtime.NewParameterCodec(scheme)
    ^
pkg/reconciler/v1alpha1/taskrun/entrypoint/entrypoint.go:44:2: `digestSeparator` is unused (varcheck)
	digestSeparator   = "@"
	^
test/clients.go:60:6: `newClients` is unused (deadcode)
func newClients(t *testing.T, configPath, clusterName, namespace string) *clients {
     ^
pkg/reconciler/v1alpha1/pipelinerun/pipelinerun_test.go:554:6: `validateEvents` is unused (deadcode)
func validateEvents(t *testing.T, r *record.FakeRecorder) {
     ^
cmd/bash/main.go:58:19: Error return value of `logger.Sync` is not checked (errcheck)
	defer logger.Sync()
	                 ^
cmd/controller/main.go:67:19: Error return value of `logger.Sync` is not checked (errcheck)
	defer logger.Sync()
	                 ^
cmd/creds-init/main.go:32:19: Error return value of `logger.Sync` is not checked (errcheck)
	defer logger.Sync()
	                 ^
pkg/reconciler/reconciler.go:126:28: Error return value of `pipelineScheme.AddToScheme` is not checked (errcheck)
	pipelineScheme.AddToScheme(scheme.Scheme)
	                          ^
pkg/reconciler/v1alpha1/pipelinerun/pipelinerun_test.go:189:24: Error return value of `c.Reconciler.Reconcile` is not checked (errcheck)
	c.Reconciler.Reconcile(context.Background(), "foo/test-pipeline-run-success")
	                      ^
pkg/reconciler/v1alpha1/pipelinerun/pipelinerun_test.go:336:26: Error return value of `c.Reconciler.Reconcile` is not checked (errcheck)
			c.Reconciler.Reconcile(context.Background(), getRunName(tc.pipelineRun))
			                      ^
pkg/reconciler/v1alpha1/pipelinerun/pipelinerun_test.go:502:24: Error return value of `c.Reconciler.Reconcile` is not checked (errcheck)
	c.Reconciler.Reconcile(context.Background(), "foo/test-pipeline-run-completed")
	                      ^
pkg/reconciler/v1alpha1/taskrun/entrypoint/entrypoint_test.go:218:11: Error return value of `w.Write` is not checked (errcheck)
			w.Write(mustRawConfigFile(t, img))
			       ^
pkg/reconciler/v1alpha1/taskrun/entrypoint/entrypoint_test.go:223:11: Error return value of `w.Write` is not checked (errcheck)
			w.Write(mustRawManifest(t, img))
			       ^
pkg/reconciler/v1alpha1/taskrun/entrypoint/entrypoint_test.go:287:11: Error return value of `w.Write` is not checked (errcheck)
			w.Write(mustRawConfigFile(t, img))
			       ^
pkg/reconciler/v1alpha1/taskrun/resources/input_resource_test.go:198:55: Error return value of `(github.com/tektoncd/pipeline/vendor/k8s.io/client-go/tools/cache.Queue).Add` is not checked (errcheck)
		pipelineResourceInformer.Informer().GetIndexer().Add(r)
		                                                    ^
pkg/reconciler/v1alpha1/taskrun/resources/output_resource_test.go:102:55: Error return value of `(github.com/tektoncd/pipeline/vendor/k8s.io/client-go/tools/cache.Queue).Add` is not checked (errcheck)
		pipelineResourceInformer.Informer().GetIndexer().Add(r)
		                                                    ^
pkg/reconciler/v1alpha1/taskrun/resources/pod.go:251:25: Error return value of `entrypoint.RedirectStep` is not checked (errcheck)
	entrypoint.RedirectStep(cache, len(podContainers), nopContainer, kubeclient, taskRun, logger)
	                       ^
pkg/reconciler/v1alpha1/taskrun/taskrun_test.go:964:70: Error return value of `(github.com/tektoncd/pipeline/vendor/k8s.io/client-go/kubernetes/typed/core/v1.ServiceAccountInterface).Create` is not checked (errcheck)
			clients.Kube.CoreV1().ServiceAccounts(tc.taskRun.Namespace).Create(&corev1.ServiceAccount{
			                                                                  ^
test/controller.go:125:44: Error return value of `(github.com/tektoncd/pipeline/vendor/k8s.io/client-go/tools/cache.Queue).Add` is not checked (errcheck)
		i.PipelineRun.Informer().GetIndexer().Add(pr)
		                                         ^
test/gohelloworld/main.go:18:21: Error return value of `http.ListenAndServe` is not checked (errcheck)
	http.ListenAndServe(":8080", nil)
	                   ^
cmd/entrypoint/main.go:74:25: `waitFile` is unused (structcheck)
type RealWaiter struct{ waitFile string }
                        ^
pkg/reconciler/v1alpha1/pipelinerun/pipelinerun.go:425:5: ineffectual assignment to `taskRunTimeout` (ineffassign)
				taskRunTimeout = 0
				^
pkg/reconciler/v1alpha1/taskrun/resources/input_resources.go:162:20: this result of append is never used, except maybe in other appends (megacheck)
		buildVol = append(buildVol, volume)
		                 ^
pkg/reconciler/v1alpha1/taskrun/resources/input_resources.go:178:21: this result of append is never used, except maybe in other appends (megacheck)
			buildVol = append(buildVol, gcsSecretVolume)
			                 ^
pkg/reconciler/v1alpha1/taskrun/resources/output_resource.go:177:25: this result of append is never used, except maybe in other appends (megacheck)
		totalBuildVol = append(totalBuildVol, volume)
		                      ^
test/logs/pod/watcher.go:58:5: empty branch (megacheck)
				if !ok {
				^
pkg/apis/pipeline/v1alpha1/dag.go:100:2: should write next := nodes[pt.Name] instead of next, _ := nodes[pt.Name] (megacheck)
	next, _ := nodes[pt.Name]
	^
pkg/apis/pipeline/v1alpha1/pipeline_validation.go:79:4: should use copy() instead of a loop (megacheck)
			for i, o := range task.Resources.Outputs {
			^
pkg/apis/pipeline/v1alpha1/resource_defaults.go:26:2: redundant return statement (megacheck)
	return
	^
pkg/apis/pipeline/v1alpha1/task_defaults.go:26:2: redundant return statement (megacheck)
	return
	^
pkg/artifacts/artifacts_storage.go:140:2: should merge variable declaration with assignment on next line (megacheck)
	var pvcSizeBytes int64
	^
pkg/reconciler/v1alpha1/pipelinerun/pipelinerun.go:423:22: should use time.Until instead of t.Sub(time.Now()) (megacheck)
			taskRunTimeout := pTimeoutTime.Sub(time.Now())
			                  ^
pkg/reconciler/v1alpha1/pipelinerun/pipelinerun_test.go:254:96: should omit comparison to bool constant, can be simplified to !exists (megacheck)
	if _, exists := reconciledRun.Status.TaskRuns["test-pipeline-run-success-unit-test-1-mz4c7"]; exists == false {
	                                                                                              ^
pkg/reconciler/v1alpha1/pipelinerun/pipelinerun_test.go:257:107: should omit comparison to bool constant, can be simplified to !exists (megacheck)
	if _, exists := reconciledRun.Status.TaskRuns["test-pipeline-run-success-unit-test-cluster-task-78c5n"]; exists == false {
	                                                                                                         ^
pkg/reconciler/v1alpha1/taskrun/entrypoint/entrypoint.go:181:2: should merge variable declaration with assignment on next line (megacheck)
	var command []string
	^
test/logs/main.go:43:2: should merge variable declaration with assignment on next line (megacheck)
	var out io.Writer
	^
pkg/reconciler/v1alpha1/taskrun/resources/apply_test.go:185:6: type `rg` is unused (megacheck)
type rg struct {
     ^
pkg/reconciler/v1alpha1/taskrun/resources/output_resource_test.go:682:3: field `wantVolumes` is unused (megacheck)
		wantVolumes []corev1.Volume
		^
pkg/reconciler/v1alpha1/taskrun/resources/output_resource_test.go:850:3: field `wantSteps` is unused (megacheck)
		wantSteps []corev1.Container
		^

</details>

**Comment by dlorenc** [comment]
Once these are all fixed we should add a presubmit to verify they stay fixed.

**Comment by bobcatfish** [comment]
I think we've got the presubmit now - thanks @dlorenc ! Safe to close this?

**Comment by vdemeester** [comment]
I think so yes !
/close
