### ISSUE TITLE
Update Github release task to scrape initial release notes

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#799]
# Expected Behavior

When making a release, we should be able to scrape the release notes from all the PRs since the last release to create a draft release description.

# Actual Behavior

When making a release, you currently have to manually look through all the pull requests and create the release notes, e.g. https://github.com/tektoncd/pipeline/releases/tag/untagged-ae24b5214648d4ec25dc

# Additional Info

* Promising tool used by [traefik](https://github.com/containous/traefik) https://github.com/ldez/gcg
* Blocked by #530

**Comment by dibyom** [comment]
There is now a create-draft-release task that we've been using to do this: https://github.com/tektoncd/triggers/blob/master/tekton/create-draft-triggers-release.yaml

/close
