### ISSUE TITLE
Incorrect param type passed to stepaction makes it use default value

### ISSUE THREAD

**Issue by arifash01** [tektoncd/pipeline#8079]
Github Repo Link to reproduce bug: https://github.com/arifash01/tekton-param-issue

# Expected Behavior
Fail the run because the commands param expects a list but a string is passed instead

# Actual Behavior
Run succeeds and the logs show the default value instead

- Kubernetes version: 

  **Output of `kubectl version`:**

```
Client Version: v1.29.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.5-gke.1060000
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
Client version: 0.32.0
Pipeline version: v0.58.0
```

**Comment by chitrangpatel** [comment]
Thanks @arifash01! This is indeed a bug.
