### ISSUE TITLE
FR: Allow Resources to be declared as "optional"

### ISSUE THREAD

**Issue by dlorenc** [tektoncd/pipeline#812]
# Expected Behavior

`Task` authors should be able to declare some Inputs as "optional". 

# Actual Behavior

Today all declared input resources must be supplied.

**Comment by dlorenc** [comment]
Example use-cases:

- A "deployment" task that can deploy to a specified cluster, but defaults to the cluster it is running in.
- A task that can optionally upload artifacts to an artifact store, but does not need to.

**Comment by sbwsg** [comment]
gke-deploy Task in the catalog could use this functionality: https://github.com/tektoncd/catalog/pull/126

That task would ideally be able to accept either a cluster resource OR the necessary args to configure access to that cluster.  Very similar to the first example use case mentioned by @dlorenc

**Comment by pritidesai** [comment]
Design Doc: https://docs.google.com/document/d/1oe936Zspc8jL9Tb7kWd26bS6sf2emxUxTjt-aKv01Mc/edit#heading=h.duu98lpb6lg4
