### ISSUE TITLE
Remove references to "build"

### ISSUE THREAD

**Issue by ImJasonH** [tektoncd/pipeline#815]
# Expected Behavior

TaskRuns are not assumed to be "building" something; they can do anything, including tests, deployments, busy-waits, making sandwiches

# Actual Behavior

TaskRuns describe things in terms of "build" all over the place, including (but not limited to):

* A running TaskRun's status is `Building` ([here](https://github.com/tektoncd/pipeline/blob/11e03b73e549ab1508827182f6cc05ccf1a3080c/pkg/reconciler/v1alpha1/taskrun/taskrun.go#L353)) -- this could be changed to `Running`
* A TaskRun's Pod has containers named like `build-step-${step-name}` ([here](https://github.com/tektoncd/pipeline/blob/11e03b73e549ab1508827182f6cc05ccf1a3080c/pkg/reconciler/v1alpha1/taskrun/resources/pod.go#L92)) -- this could be changed to `step-`
* TaskRun logs end with a line saying `Build successful` ([here](https://github.com/tektoncd/pipeline/blob/5ee5ace505e8ca37a0398c47f98c829fd2a29a9e/cmd/nop/main.go#L22)) -- this could be changed to `TaskRun successful`, or just not log anything.

(There are probably more)

**Comment by aristosvo** [comment]
It looks like the order of steps is changed. In the failing [test](https://github.com/aristosvo/pipeline/blob/master/test/taskrun_test.go) the order is:
- exit
- hello
- world
- nop

In the output yaml the order is:

- nop
- exit
- hello
- world

**Comment by ImJasonH** [comment]
Looks like there's still at least one lingering reference:

- TaskRuns in progress have `Reason: Building` (from [here](https://github.com/tektoncd/pipeline/blob/53c936baecfe40a04800c0d3f1502b3f1687a7f0/pkg/status/taskrunreasons.go#L38)) -- I'm not sure what the difference is between `ReasonBuilding` and `ReasonRunning`, but any place we use `Building` we should use `Running` instead.
