### ISSUE TITLE
Investigate why the trigger field exists

### ISSUE THREAD

**Issue by dlorenc** [tektoncd/pipeline#816]
This came up as a question in today's WG meeting. Proposal is to delete it if we can't figure out what it's for to prevent confusion.

**Comment by vdemeester** [comment]
@dlorenc on `TaskRun` it's to know if the run has been created by a PipelineRun or on its own. For `PipelineRun`, I feel it's there for the "near future" :angel:

**Comment by bobcatfish** [comment]
This is one of the fields hanging around from our first implementation that we should probably revisit.

The goal of this field isn't to _cause_ triggering to occur, the goal was to record for posterity why the Run was created, this is probably clearest when looking at `TaskRun`:

https://github.com/tektoncd/pipeline/blob/19bf18abe2f7e71c5eb3ee6ff10351643db5510b/pkg/apis/pipeline/v1alpha1/taskrun_types.go#L95-L115

I've added a requirement [to the pipeline listener proposal](https://docs.google.com/document/d/1tfG6dkARP2xko-5trDV3D62DJZiXQBZgLtLH7GyUopM/edit#heading=h.r917fv3d9wg8) about history / traceability - we should feel free to completely change these fields to something that makes sense :)

**Comment by bobcatfish** [comment]
+ @dlorenc anything else you'd like to see added here?

**Comment by dlorenc** [comment]
Should retitle this to be "decide if it should continue to exist"? It seems like we're still not clear.

I also wonder if some of this "provenance"-style info should be tracked as annotations rather than fields.

**Comment by vincent-pli** [comment]
Could we reuse the field to introduce new function: execute immediately or hold on
if "hold on" (TaskTriggerType: "hold-on"), then the CRD is created, but Controller will leave it alone.
A later event or operation will trigger it (A couldevent or `kubectl apply`)

**Comment by bobcatfish** [comment]
> Should retitle this to be "decide if it should continue to exist"? It seems like we're still not clear.
> I also wonder if some of this "provenance"-style info should be tracked as annotations rather than fields.

I created a new issue instead #833 feel free to edit it @dlorenc :D

> Could we reuse the field to introduce new function: execute immediately or hold on
if "hold on" (TaskTriggerType: "hold-on"), then the CRD is created, but Controller will leave it alone.
A later event or operation will trigger it (A couldevent or kubectl apply)

@vincent-pli that's an interesting idea - do you feel like opening a new issue to discuss this further? If we want to support the use cases you're describing, we can happily add new field(s) even :D

**Comment by vincent-pli** [comment]
@bobcatfish 
I am glad to hear that, I will open a new issue for it for the further discussion, thanks.
