### ISSUE TITLE
Cancelling an active PipelineRun with TaskRuns that are already complete hits "PipelineRunCouldntCancel" condition on v0.62.0

### ISSUE THREAD

**Issue by hrivera-ntap** [tektoncd/pipeline#8172]
# Expected Behavior
Cancelling a PipelineRun via `kubectl patch` that has TaskRuns that have completed (pass or fail) should properly cancel the pipelinerun and reflect that the pipeline is cancelled.

This is how i am currently cancelling the pipeline.

```
kubectl patch pipelinerun <pipeline> --type='merge' -p '{"spec":{"status":"Cancelled"}}'
```

# Actual Behavior

Cancelling a PipelineRun that has taskruns that have already completed results in the pipeline encountering the `PipelineRunCouldntCancel` condition .

# Steps to Reproduce the Problem

See the following gist for a script to reproduce: https://gist.github.com/hrivera-ntap/4376d79825c2b720e76fd109b26bd013

I suspect that this started happening after this was introduced: https://github.com/tektoncd/pipeline/pull/8147 , if possible @l-qing , can you confirm?

# Additional Info

- Kubernetes version:

```
Client Version: v1.28.6
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.6
```

- Tekton Pipeline version:

```
v0.62.0
```

**Comment by l-qing** [comment]
Your description is very detailed. 

It seems that the cancellation request was sent to all TaskRuns here, including those that were already completed.

https://github.com/tektoncd/pipeline/blob/95fbf318460a2f73ac505bbdb13786a788d1c092/pkg/reconciler/pipelinerun/cancel.go#L138-L145

I will address this issue today. I'm very sorry for the inconvenience caused.

/assign l-qing
