### ISSUE TITLE
Artifact storage PVCs aren't cleaned up until the PipelineRun is deleted

### ISSUE THREAD

**Issue by abayer** [tektoncd/pipeline#823]
# Expected Behavior

Artifact storage PVCs get deleted after the completion of the `PipelineRun`.

# Actual Behavior

Artifact storage PVCs don't get deleted automatically until/unless the owning `PipelineRun` itself is deleted.

# Steps to Reproduce the Problem

1. Run a `Pipeline` with multiple `Task`s, with one having its workspace as output and another having that workspace as input.
2. Notice that the PVC created for that input/output isn't deleted after completion of the `PipelineRun`.

# Additional Info

**Comment by nader-ziada** [comment]
The pods using the pvc have to be deleted first before the pvc is deleted

**Comment by waveywaves** [comment]
I would like to work on this. Anything specific I should keep in mind before I start ? This would be my first time contributing.
