### ISSUE TITLE
PipelineRun fails to timeout properly in v0.63.0 (hits PipelineRunCouldntTimeOut state)

### ISSUE THREAD

**Issue by hrivera-ntap** [tektoncd/pipeline#8230]
# Expected Behavior
Creating a pipelinerun with a timeout set that has multiple tasks, where some complete before the timeout expires should properly timeout.

# Actual Behavior
The pipelinerun resource hits a "PipelineRunCouldntTimeout" state with the following error:

```
  Normal   PipelineRunCouldntTimeOut  10s                PipelineRun  PipelineRun "timeout-pipelinerun" was timed out but had errors trying to time out TaskRuns and/or Runs: failed to patch TaskRun `timeout-pipelinerun-fast-task` with timeout: admission webhook "validation.webhook.pipeline.tekton.dev" denied the request: validation failed: invalid value: Once the TaskRun is complete, no updates are allowed: spec
```

# Steps to Reproduce the Problem

See the following gist for an easy way to reproduce: https://gist.github.com/hrivera-ntap/a9dc47e7924feb6dc3ad32ac13751ffb 

1. Create a pipelinerun with multiple tasks and provide a timeout to the pipelinerun
2. PipelineRun will hit PipelineRunCouldntTimeout state

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
(paste your output here)
```

- Tekton Pipeline version:

v0.63.0
v0.62.x

(appears to be a regression introduced after v0.61.1)

@l-qing : This appears to be closely related to the issue reported in #8172 that you recently fixed by #8173. Mind taking a look?

**Comment by l-qing** [comment]
Thank you for your feedback. I looked at it today.
