### ISSUE TITLE
referencing and calling remote github pipeline in pipelinerun

### ISSUE THREAD

**Issue by martinmlouis** [tektoncd/pipeline#8258]
I want to use a reference to a remote github pipeline in a pipelinerun
    spec:
      serviceAccountName: serviceaccount-basic-auth-remote
      pipelineRef:
        resolver: git
        params:
        - name: url
          value: https://github.com/martinmlouis/leido.git
        - name: pathInRepo
          value: demo/pipeline.yaml
I am getting error "clone error: authetication required"
It works for tasks but not able to get it working for pipelines,
Thanks

**Comment by vdemeester** [comment]
@martinmlouis isn't this just a typo ? (it's leidos.git and not leido.git it seems)

**Comment by martinmlouis** [comment]
Sorry, my mistake, it works as specified in the document
