### ISSUE TITLE
making ci images fails with 

### ISSUE THREAD

**Issue by objectiveous** [tektoncd/pipeline#827]
# Expected Behavior

I'm trying to build and publish CI images as I intend to make enhancements to the "creds-image" to work better with our corporate github and container registries. 

# Actual Behavior

It fails to publish but more importantly the error message doesn't help me. 

# Steps to Reproduce the Problem

Not sure yet. 

```
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: publish-ci-images-run
spec:
  taskRef:
    name: publish-ci-images
  trigger:
    type: manual
  inputs:
    resources:
    - name: source
      resourceRef:
        name: tekton-pipelines
    params:
    - name: imageRegistry
      #value: gcr.io/tekton-releases # REPLACE with your own registry
      value: docker.corp.com/XXX # REPLACE with your own registry
  outputs:
    resources:
    - name: builtKoImage
      resourceRef:
        name: ko-image
```

# Additional Info

## Using 
[36mINFO[0m[0000] Downloading base image google/cloud-sdk:latest 
2019/05/03 15:24:43 No matching credentials were found, falling back on anonymous
[36mINFO[0m[0001] Unpacking rootfs as cmd RUN curl https://dl.google.com/go/go1.12.1.linux-amd64.tar.gz > go1.12.1.tar.gz requires it. 
[36mINFO[0m[0746] Taking snapshot of full filesystem...        
[36mINFO[0m[0747] Skipping paths under /kaniko, as it is a whitelisted directory 
[36mINFO[0m[0747] Skipping paths under /var/run, as it is a whitelisted directory 
[36mINFO[0m[0747] Skipping paths under /builder/tools, as it is a whitelisted directory 
[36mINFO[0m[0747] Skipping paths under /builder/home, as it is a whitelisted directory 
[36mINFO[0m[0747] Skipping paths under /proc, as it is a whitelisted directory 
[36mINFO[0m[0747] Skipping paths under /dev, as it is a whitelisted directory 
[36mINFO[0m[0747] Skipping paths under /sys, as it is a whitelisted directory 
[36mINFO[0m[0747] Skipping paths under /workspace, as it is a whitelisted directory 
[36mINFO[0m[0764] RUN curl https://dl.google.com/go/go1.12.1.linux-amd64.tar.gz > go1.12.1.tar.gz 
[36mINFO[0m[0764] cmd: /bin/sh                                 
[36mINFO[0m[0764] args: [-c curl https://dl.google.com/go/go1.12.1.linux-amd64.tar.gz > go1.12.1.tar.gz] 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  121M    0  677k    0     0  1850k      0  0:01:07 --:--:--  0:01:07 1846k
  1  121M    1 1759k    0     0  1273k      0  0:01:38  0:00:01  0:01:37 1272k
  2  121M    2 2783k    0     0  1178k      0  0:01:46  0:00:02  0:01:44 1177k
  3  121M    3 3775k    0     0  1121k      0  0:01:51  0:00:03  0:01:48 1121k
  3  121M    3 4847k    0     0  1110k      0  0:01:52  0:00:04  0:01:48 1110k
  4  121M    4 5845k    0     0  1088k      0  0:01:54  0:00:05  0:01:49 1033k
  5  121M    5 6902k    0     0  1074k      0  0:01:56  0:00:06  0:01:50 1019k
  6  121M    6 7871k    0     0  1068k      0  0:01:56  0:00:07  0:01:49 1017k
  7  121M    7 8866k    0     0  1059k      0  0:01:57  0:00:08  0:01:49 1018k
  7  121M    7 9871k    0     0  1054k      0  0:01:58  0:00:09  0:01:49 1005k
  8  121M    8 10.6M    0     0  1047k      0  0:01:59  0:00:10  0:01:49 1002k
  9  121M    9 11.6M    0     0  1043k      0  0:01:59  0:00:11  0:01:48 1004k
 10  121M   10 12.5M    0     0  1034k      0  0:02:00  0:00:12  0:01:48  984k
 11  121M   11 13.5M    0     0  1037k      0  0:02:00  0:00:13  0:01:47  999k
 11  121M   11 14.5M    0     0  1032k      0  0:02:01  0:00:14  0:01:47  991k
 12  121M   12 15.4M    0     0  1028k      0  0:02:01  0:00:15  0:01:46  988k
 13  121M   13 16.3M    0     0  1023k      0  0:02:01  0:00:16  0:01:45  978k
 14  121M   14 17.2M    0     0  1019k      0  0:02:02  0:00:17  0:01:45  982k
 14  121M   14 18.2M    0     0  1018k      0  0:02:02  0:00:18  0:01:44  967k
 15  121M   15 19.2M    0     0  1018k      0  0:02:02  0:00:19  0:01:43  976k
 16  121M   16 20.2M    0     0  1017k      0  0:02:02  0:00:20  0:01:42  983k
 17  121M   17 21.2M    0     0  1016k      0  0:02:02  0:00:21  0:01:41  991k
 18  121M   18 22.1M    0     0  1015k      0  0:02:02  0:00:22  0:01:40 1002k
 18  121M   18 23.1M    0     0  1014k      0  0:02:03  0:00:23  0:01:40 1000k
 19  121M   19 24.0M    0     0  1007k      0  0:02:03  0:00:24  0:01:39  968k
 20  121M   20 24.8M    0     0  1001k      0  0:02:04  0:00:25  0:01:39  938k
 20  121M   20 25.4M    0     0   987k      0  0:02:06  0:00:26  0:01:40  865k
 21  121M   21 26.1M    0     0   978k      0  0:02:07  0:00:27  0:01:40  811k
 22  121M   22 27.6M    0     0   998k      0  0:02:05  0:00:28  0:01:37  926k
 23  121M   23 28.6M    0     0  1000k      0  0:02:04  0:00:29  0:01:35  962k
 24  121M   24 29.6M    0     0  1000k      0  0:02:04  0:00:30  0:01:34  993k
 25  121M   25 30.6M    0     0   998k      0  0:02:05  0:00:31  0:01:34 1052k
 25  121M   25 31.6M    0     0   999k      0  0:02:04  0:00:32  0:01:32 1116k
 26  121M   26 32.5M    0     0   999k      0  0:02:04  0:00:33  0:01:31 1006k
 27  121M   27 33.5M    0     0   999k      0  0:02:04  0:00:34  0:01:30  998k
 28  121M   28 34.5M    0     0   999k      0  0:02:05  0:00:35  0:01:30  991k
 29  121M   29 35.4M    0     0   999k      0  0:02:05  0:00:36  0:01:29 1006k
 29  121M   29 36.4M    0     0   998k      0  0:02:05  0:00:37  0:01:28  988k
 30  121M   30 37.4M    0     0   998k      0  0:02:05  0:00:38  0:01:27  991k
 31  121M   31 38.4M    0     0   999k      0  0:02:05  0:00:39  0:01:26  994k
 32  121M   32 39.3M    0     0   999k      0  0:02:05  0:00:40  0:01:25  999k
 33  121M   33 40.3M    0     0   999k      0  0:02:05  0:00:41  0:01:24  999k
 33  121M   33 41.3M    0     0   999k      0  0:02:04  0:00:42  0:01:22 1008k
 34  121M   34 42.3M    0     0   998k      0  0:02:05  0:00:43  0:01:22  999k
 35  121M   35 43.2M    0     0   998k      0  0:02:05  0:00:44  0:01:21  997k
 36  121M   36 44.2M    0     0   997k      0  0:02:05  0:00:45  0:01:20  986k
 36  121M   36 45.0M    0     0   994k      0  0:02:05  0:00:46  0:01:19  954k
 37  121M   37 45.8M    0     0   990k      0  0:02:06  0:00:47  0:01:19  917k
 38  121M   38 46.6M    0     0   988k      0  0:02:06  0:00:48  0:01:18  892k
 38  121M   38 47.4M    0     0   982k      0  0:02:07  0:00:49  0:01:18  841k
 39  121M   39 48.1M    0     0   979k      0  0:02:07  0:00
:50  0:01:17  813k
 40  121M   40 49.0M    0     0   977k      0  0:02:07  0:00:51  0:01:16  820k
 41  121M   41 50.1M    0     0   980k      0  0:02:07  0:00:52  0:01:15  877k
 41  121M   41 51.0M    0     0   980k      0  0:02:07  0:00:53  0:01:14  904k
 42  121M   42 52.0M    0     0   979k      0  0:02:07  0:00:54  0:01:13  949k
 43  121M   43 53.0M    0     0   980k      0  0:02:07  0:00:55  0:01:12  991k
 44  121M   44 53.9M    0     0   980k      0  0:02:07  0:00:56  0:01:11 1014k
 45  121M   45 54.9M    0     0   981k      0  0:02:07  0:00:57  0:01:10  999k
 45  121M   45 55.9M    0     0   981k      0  0:02:07  0:00:58  0:01:09  991k
 46  121M   46 56.9M    0     0   981k      0  0:02:07  0:00:59  0:01:08 1003k
 47  121M   47 57.9M    0     0   982k      0  0:02:07  0:01:00  0:01:07 1000k
 48  121M   48 58.8M    0     0   982k      0  0:02:07  0:01:01  0:01:06 1001k
 49  121M   49 59.8M    0     0   982k      0  0:02:07  0:01:02  0:01:05  988k
 49  121M   49 60.7M    0     0   982k      0  0:02:07  0:01:03  0:01:04  992k
 50  121M   50 61.7M    0     0   981k      0  0:02:07  0:01:04  0:01:03  980k
 51  121M   51 62.6M    0     0   982k      0  0:02:07  0:01:05  0:01:02  979k
 52  121M   52 63.6M    0     0   981k      0  0:02:07  0:01:06  0:01:01  968k
 52  121M   52 64.6M    0     0   982k      0  0:02:07  0:01:07  0:01:00  980k
 53  121M   53 65.5M    0     0   982k      0  0:02:07  0:01:08  0:00:59  985k
 54  121M   54 66.5M    0     0   982k      0  0:02:07  0:01:09  0:00:58  989k
 55  121M   55 67.5M    0     0   982k      0  0:02:07  0:01:10  0:00:57  994k
 56  121M   56 68.5M    0     0   982k      0  0:02:07  0:01:11  0:00:56 1004k
 56  121M   56 69.4M    0     0   982k      0  0:02:07  0:01:12  0:00:55  986k
 57  121M   57 70.4M    0     0   983k      0  0:02:07  0:01:13  0:00:54  994k
 58  121M   58 71.4M    0     0   983k      0  0:02:07  0:01:14  0:00:53  994k
 59  121M   59 72.3M    0     0   983k      0  0:02:07  0:01:15  0:00:52  984k
 60  121M   60 73.3M    0     0   983k      0  0:02:06  0:01:16  0:00:50  994k
 60  121M   60 74.3M    0     0   983k      0  0:02:06  0:01:17  0:00:49 1002k
 61  121M   61 75.2M    0     0   983k      0  0:02:06  0:01:18  0:00:48  994k
 62  121M   62 76.2M    0     0   983k      0  0:02:06  0:01:19  0:00:47  993k
 63  121M   63 77.2M    0     0   983k      0  0:02:06  0:01:20  0:00:46  994k
 64  121M   64 78.1M    0     0   983k      0  0:02:06  0:01:21  0:00:45  987k
 64  121M   64 79.1M    0     0   984k      0  0:02:06  0:01:22  0:00:44  990k
 65  121M   65 80.2M    0     0   984k      0  0:02:06  0:01:23  0:00:43  997k
 66  121M   66 81.1M    0     0   984k      0  0:02:06  0:01:24  0:00:42  992k
 67  121M   67 82.1M    0     0   984k      0  0:02:06  0:01:25  0:00:41 1004k
 68  121M   68 83.0M    0     0   985k      0  0:02:06  0:01:26  0:00:40 1007k
 68  121M   68 84.0M    0     0   985k      0  0:02:06  0:01:27  0:00:39 1005k
 69  121M   69 85.0M    0     0   985k      0  0:02:06  0:01:28  0:00:38 1003k
 70  121M   70 86.0M    0     0   985k      0  0:02:06  0:01:29  0:00:37 1014k
 71  121M   71 86.9M    0     0   985k      0  0:02:06  0:01:30  0:00:36 1000k
 72  121M   72 87.9M    0     0   986k      0  0:02:06  0:01:31  0:00:35 1000k
 72  121M   72 88.9M    0     0   986k      0  0:02:06  0:01:32  0:00:34  997k
 73  121M   73 89.9M    0     0   986k      0  0:02:06  0:01:33  0:00:33  997k
 74  121M   74 90.9M    0     0   986k      0  0:02:06  0:01:34  0:00:32  997k
 75  121M   75 91.9M    0     0   986k      0  0:02:06  0:01:35  0:00:31 1005k
 76  121M   76 92.8M    0     0   986k      0  0:02:06  0:01:36  0:00:30  999k
 76  121M   76 93.8M    0     0   986k      0  0:02:06  0:01:37  0:00:29 1004k
 77  121M   77 94.8M    0     0   987k      0  0:02:06  0:01:38  0:00:28 1004k
 78  121M   78 95.8M    0     0   987k      0  0:02:06  0:01:39  0:00:27 1005k
 79  121M   79 96.8M    0     0   987k      0  0:02:06  0:01:40  0:00:26 1007k
 80  121M   80 97.8M    0     0   987k      0  0:02:06  0:01:41  0:00:25 1008k
 80  121M   80 98.7M    0     0   987k      0  0:02:06  0:01:42  0:00:24 1002k
 81  121M   81 99.7M    0     0   988k      0  0:02:06  0:01:43  0:00:23 1007k
 82  121M   82  100M    0     0   987k      0  0:02:06  0:01:44  0:00:22  996k
 83  121M   83  101M    0     0   986k      0  0:02:06  0:01:45  0:00:21  959k
 84  121M   84  102M    0     0   988k      0  0:02:06  0:01:46  0:00:20  999k
 84  121M   84  103M    0     0   988k      0  0:02:06  0:01:47  0:00:19 1004k
 85  121M   85  104M    0     0   988k      0  0:02:06  0:01:48  0:00:18  996k
 86  121M   86  105M    0     0   988k      0  0:02:06  0:01:49  0:00:17 1004k
 87  121M   87  106M    0     0   988k      0  0:02:06  0:01:50  0:00:16 1034k
 88  121M   88  107M    0     0   988k      0  0:02:06  0:01:51  0:00:15  998k
 88  121M   88  108M    0     0   988k      0  0:02:06  0:01:52  0:00:14  994k
 89  121M   89  109M    0     0   989k      0  0:02:06  0:01:53  0:00:13  998k
 90  121M   90  110M    0     0   989k      0  0:02:06  0:01:54  0:00:12 1000k
 91  121M   91  111M    0     0   989k      0  0:02:06  0:01:55  0:00:11 1008k
 92  121M   92  112M    0     0   989k      0  0:02:06  0:01:56  0:00:10 1006k
 92  121M   92  113M    0     0   989k      0  0:02:06  0:01:57  0:00:09 1007k
 93  121M   93  114M    0     0   990k      0  0:02:06  0:01:58  0:00:08 1012k
 94  121M   94  115M    0     0   990k      0  0:02:06  0:01:59  0:00:07 1011k
 95  121M   95  116M    0     0   990k      0  0:02:06  0:02:00  0:00:06 1013k
 96  121M   96  117M    0     0   990k      0  0:02:06  0:02:01  0:00:05 1012k
 97  121M   97  118M    0     0   990k      0  0:02:06  0:02:02  0:00:04 1018k
 97  121M   97  119M    0     0   990k      0  0:02:06  0:02:03  0:00:03 1009k
 98  121M   98  120M    0     0   991k      0  0:02:06  0:02:04  0:00:02 1014k
 99  121M   99  121M    0     0   990k      0  0:02:06  0:02:05  0:00:01 1001k
100  121M  100  121M    0     0   991k      0  0:02:06  0:02:06 --:--:-- 1007k
[36mINFO[0m[0891] Taking snapshot of full filesystem...        
[36mINFO[0m[0891] Skipping paths under /kaniko, as it is a whitelisted directory 
[36mINFO[0m[0891] Skipping paths under /var/run, as it is a whitelisted directory 
[36mINFO[0m[0891] Skipping paths under /builder/tools, as it is a whitelisted directory 
[36mINFO[0m[0891] Skipping paths under /builder/home, as it is a whitelisted directory 
[36mINFO[0m[0891] Skipping paths under /proc, as it is a whitelisted directory 
[36mINFO[0m[0891] Skipping paths under /dev, as it is a whitelisted directory 
[36mINFO[0m[0891] Skipping paths under /sys, as it is a whitelisted directory 
[36mINFO[0m[0891] Skipping paths under /workspace, as it is a whitelisted directory 
[36mINFO[0m[0902] RUN tar -C /usr/local -xzf go1.12.1.tar.gz   
[36mINFO[0m[0902] cmd: /bin/sh                                 
[36mINFO[0m[0902] args: [-c tar -C /usr/local -xzf go1.12.1.tar.gz] 
[36mINFO[0m[0905] Taking snapshot of full filesystem...        
[36mINFO[0m[0907] Skipping paths under /kaniko, as it is a whitelisted directory 
[36mINFO[0m[0907] Skipping paths under /var/run, as it is a whitelisted directory 
[36mINFO[0m[0907] Skipping paths under /builder/tools, as it is a whitelisted directory 
[36mINFO[0m[0907] Skipping paths under /builder/home, as it is a whitelisted directory 
[36mINFO[0m[0907] Skipping paths under /proc, as it is a whitelisted directory 
[36mINFO[0m[0907] Skipping paths under /dev, as it is a whitelisted directory 
[36mINFO[0m[0907] Skipping paths under /sys, as it is a whitelisted directory 
[36mINFO[0m[0907] Skipping paths under /workspace, as it is a whitelisted directory 
[36mINFO[0m[0925] ENV PATH="${PATH}:/usr/local/go/bin"         
[36mINFO[0m[0925] ENV GOBIN=/usr/local/go/bin                  
[36mINFO[0m[0925] RUN go get github.com/google/go-containerregistry/cmd/ko 
[36mINFO[0m[0925] cmd: /bin/sh                                 
[36mINFO[0m[0925] args: [-c go get github.com/google/go-containerregistry/cmd/ko] 
package github.com/google/go-containerregistry/cmd/ko: no Go files in /root/go/src/github.com/google/go-containerregistry/cmd/ko
error building image: error building stage: waiting for process to exit: exit status 1

## LOGS 
Podspublish-ci-images-run-pod-0b9a1c
Edit
Status
Specifications
View
Labels
Logs
build-step-git-source-tekton-pipelines-lm5pq
build-step-build-push-ko-image
nop
Show last 500 lines
[36mINFO[0m[0000] Downloading base image google/cloud-sdk:latest 
2019/05/03 14:58:29 No matching credentials were found, falling back on anonymous
[36mINFO[0m[0002] Unpacking rootfs as cmd RUN curl https://dl.google.com/go/go1.12.1.linux-amd64.tar.gz > go1.12.1.tar.gz requires it. 
[36mINFO[0m[0764] Taking snapshot of full filesystem...        
[36mINFO[0m[0765] Skipping paths under /kaniko, as it is a whitelisted directory 
[36mINFO[0m[0765] Skipping paths under /var/run, as it is a whitelisted directory 
[36mINFO[0m[0765] Skipping paths under /builder/tools, as it is a whitelisted directory 
[36mINFO[0m[0765] Skipping paths under /builder/home, as it is a whitelisted directory 
[36mINFO[0m[0765] Skipping paths under /proc, as it is a whitelisted directory 
[36mINFO[0m[0765] Skipping paths under /dev, as it is a whitelisted directory 
[36mINFO[0m[0765] Skipping paths under /sys, as it is a whitelisted directory 
[36mINFO[0m[0765] Skipping paths under /workspace, as it is a whitelisted directory 
[36mINFO[0m[0819] RUN curl https://dl.google.com/go/go1.12.1.linux-amd64.tar.gz > go1.12.1.tar.gz 
[36mINFO[0m[0819] cmd: /bin/sh                                 
[36mINFO[0m[0819] args: [-c curl https://dl.google.com/go/go1.12.1.linux-amd64.tar.gz > go1.12.1.tar.gz] 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  1  121M    1 1519k    0     0   922k      0  0:02:15  0:00:01  0:02:14  922k
...
[36mINFO[0m[0960] Taking snapshot of full filesystem...        
[36mINFO[0m[0960] Skipping paths under /kaniko, as it is a whitelisted directory 
[36mINFO[0m[0960] Skipping paths under /var/run, as it is a whitelisted directory 
[36mINFO[0m[0961] Skipping paths under /builder/tools, as it is a whitelisted directory 
[36mINFO[0m[0961] Skipping paths under /builder/home, as it is a whitelisted directory 
[36mINFO[0m[0961] Skipping paths under /proc, as it is a whitelisted directory 
[36mINFO[0m[0961] Skipping paths under /dev, as it is a whitelisted directory 
[36mINFO[0m[0961] Skipping paths under /sys, as it is a whitelisted directory 
[36mINFO[0m[0961] Skipping paths under /workspace, as it is a whitelisted directory 
[36mINFO[0m[0975] RUN tar -C /usr/local -xzf go1.12.1.tar.gz   
[36mINFO[0m[0975] cmd: /bin/sh                                 
[36mINFO[0m[0975] args: [-c tar -C /usr/local -xzf go1.12.1.tar.gz] 
[36mINFO[0m[0980] Taking snapshot of full filesystem...        
[36mINFO[0m[0983] Skipping paths under /kaniko, as it is a whitelisted directory 
[36mINFO[0m[0983] Skipping paths under /var/run, as it is a whitelisted directory 
[36mINFO[0m[0983] Skipping paths under /builder/tools, as it is a whitelisted directory 
[36mINFO[0m[0983] Skipping paths under /builder/home, as it is a whitelisted directory 
[36mINFO[0m[0983] Skipping paths under /proc, as it is a whitelisted directory 
[36mINFO[0m[0983] Skipping paths under /dev, as it is a whitelisted directory 
[36mINFO[0m[0983] Skipping paths under /sys, as it is a whitelisted directory 
[36mINFO[0m[0983] Skipping paths under /workspace, as it is a whitelisted directory 
[36mINFO[0m[1016] ENV PATH="${PATH}:/usr/local/go/bin"         
[36mINFO[0m[1016] ENV GOBIN=/usr/local/go/bin                  
[36mINFO[0m[1016] RUN go get github.com/google/go-containerregistry/cmd/ko 
[36mINFO[0m[1016] cmd: /bin/sh                                 
[36mINFO[0m[1016] args: [-c go get github.com/google/go-containerregistry/cmd/ko] 
package github.com/google/go-containerregistry/cmd/ko: no Go files in /root/go/src/github.com/google/go-containerregistry/cmd/ko
error building image: error building stage: waiting for process to exit: exit status 1

**Comment by vdemeester** [comment]
> package github.com/google/go-containerregistry/cmd/ko: no Go files in /root/go/src/github.com/google/go-containerregistry/cmd/ko
error building image: error building stage: waiting for process to exit: exit status 1

Looking at this message, the task you are using refers to a non-existing go package. `ko` move away from `go-containerregistry` and now leaves here : https://github.com/google/ko.

**Comment by objectiveous** [comment]
@vdemeester, thank you. Sorry for the trouble. ;-)

**Comment by ImJasonH** [comment]
This is an actual issue, this line needs to be updated: https://github.com/tektoncd/pipeline/blob/master/tekton/ko/Dockerfile#L10
