### ISSUE TITLE
Unable to remove finally tasks in pipeline builder mode

### ISSUE THREAD

**Issue by RoboMWM** [tektoncd/pipeline#8358]
# Expected Behavior

Finally task gets removed from pipeline when removing the finally tasks and saving the pipeline in the "pipeline builder" mode.

# Actual Behavior

The finally tasks do not get removed and remain in the pipeline.

# Steps to Reproduce the Problem

1. Create a finally task in a pipeline in pipeline builder
2. Save pipeline
3. Edit pipeline and remove finally task in pipeline builder
4. Save pipeline
5. Observe that the finally task has not been removed

# Additional Info

- OpenShift version: 4.16.7 (also present in 4.12)
- Red Hat OpenShift Pipelines Operator 1.16.0

I'm not sure if this is the correct place to report this issue, as it appears to be an issue with the Pipeline Builder view in OpenShift's UI and not Tekton itself, as I'm able to delete finally tasks if I remove the entire `finally` section under `spec` in the YAML view.

**Comment by AlanGreene** [comment]
> I'm not sure if this is the correct place to report this issue, as it appears to be an issue with the Pipeline Builder view in OpenShift's UI

https://github.com/openshift-pipelines/console-plugin looks like it might be the correct place. @vdemeester may be able to confirm.

**Comment by vdemeester** [comment]
Yes, this should be reported on `console-plugin` indeed (or `openshift/console`, but `console-plugin` should be fine).
@RoboMWM I'll let you create an issue on https://github.com/openshift-pipelines/console-plugin and I'll be closing this one.
