### ISSUE TITLE
Design: Suspend PipelineRun and TaskRuns after creation

### ISSUE THREAD

**Issue by vincent-pli** [tektoncd/pipeline#836]
# Expected Behavior
In some scenario, we expect `Pipelinerun/Taskrun` suspend after creation until triggered by some event (whatever, `kubectl patch` or `cloudevent` )
# Actual Behavior
`Pipelinerun/Taskrun` will execute immediately once created.

# Additional Info
The idea is come from an internal demo several weeks ago.
We plan to use `gitlab `+ `knative` + `tekton` to implement a simple CI/CD case.
See the diagram :
![image](https://user-images.githubusercontent.com/8669744/57265117-9ea5e680-70a8-11e9-99a0-d346e83018d8.png)
Use `Gitlab source` from `Knative eventing-sources` to receive event from `web hook gitlab`, then deliver the event to `Pipeline invoker` (a Knative service, we write it) then run a `Pipeline`.
A obvious problem is `Pipeline` could be too complex to create just based on payload of the event, so if `Pipelinerun` could be prepare in advance that’s will be great.

Our solution is reuse the `TaskTriggerType` (confuse us at the beginning), let controller leave the `Pipelinerun` alone if the value of `TaskTriggerType` is something.
In `Pipeline invoker` we use `kubectl patch` to modify that `Pipelinerun`, so the `Pipelinerun` started.

That’s a very draft solution, but the suspend mechanism is useful, I think we can consider to add new field for it.

A further though is to create additional Pipeline-invoker when create `Pipelinerun` if it’s a suspend one.

**Comment by sbwsg** [comment]
Could you describe a bit more about the specific scenarios that you'd like to serve with this feature?  We have some discussion of features that provide related functionality. [Wait until condition is met](https://github.com/tektoncd/pipeline/issues/233) seems particularly relevant.

**Comment by vincent-pli** [comment]
@sbwsg  Sure,
basically in my case, I expect everything (resource, tasks, pipelines, pipelinerun . etc) is ready, but not start. The “start” should be triggered by something (couldevent or kubectl patch or whatever).

That’s require feature that the **Pipelinerun could suspend rather than execute immediately after creation.**

I saw the link you mentioned, that’s reasonable. we can leverage Knative-eventing for different event resource and Broker, Trigger to subscribe certain event to trigger pipelinerun, but firstly, we need the ability to suspend after creation.

Hmm, in my draft solution, just add these code to `/pkg/reconciler/v1alpha1/pipelinerun/pipelinerun.go`
```
        pr := original.DeepCopy()
+
+       if pr.Spec.Trigger.Name != "run" {
+               c.Logger.Errorf("%s will not start, wait for trigger...", name)
+               return nil
+       }
```
:D :D :D

**Comment by dibyom** [comment]
Could this be a special case of #233 where the initial task(s) are paused waiting on a condition?

**Comment by vincent-pli** [comment]
@dibyom I guess so, but the `condition met` is a big picture, such as `event trigger`, `kubectl apply` .etc

**Comment by bobcatfish** [comment]
> That’s require feature that the Pipelinerun could suspend rather than execute immediately after creation.

@vincent-pli what kind of action would cause the PipelineRun to un-suspend?

**Comment by bobcatfish** [comment]
Closing this for now, please re-open if needed @vincent-pli 

(Note this proposal could also be relevant to #233)
