### ISSUE TITLE
Allow to define the source path of output resources when use pvc for sharing

### ISSUE THREAD

**Issue by vincent-pli** [tektoncd/pipeline#841]
# Expected Behavior
User could define a path for output resource, then controller will copy it to PV when the task complete.
# Actual Behavior
Currently, there are two ways to decide the path of the output resource:
**1. Define an input resource which has the same name with this output resource**
Controller will copy the path of input resource to PV when complete.
I can understand the design. just like a workspace, the workspace input --> do some work in the workspace --> the workspace output.

That's make sense, but I think there is another case: user just want to release certain stuff, like a war, jar or binary. so he want to define a specific path. 

**2. Copy from /workspace/output/resource_name**
# Additional Info
I think we can use the `TargetPath` in resource definition.

**Comment by vincent-pli** [comment]
#842

**Comment by vdemeester** [comment]
As #842 got merge, I think this issue can be closed

/kind feature
/close
