### ISSUE TITLE
Add subfolder to the target path when input source has more than one from condition

### ISSUE THREAD

**Issue by vincent-pli** [tektoncd/pipeline#851]
# Expected Behavior
If input resource has more than one `from` condition, controller should copy output of previous to `/workspace/task_resource_name/previous_task_1/` and `/workspace/task_resource_name/previous_task_n/`
# Actual Behavior
The controller will add copy container to copy from PV to `/workspace/task_resource_name`,
If there are more than one output need to copy, the stuff from outputs will mix together, that's not good behavior

**Comment by vdemeester** [comment]
@vincent-pli As #853, I am guessing this issue should be closed too ?

**Comment by vincent-pli** [comment]
Sure
