### ISSUE TITLE
Feature request: allow populating creds with non-root UID

### ISSUE THREAD

**Issue by AkihiroSuda** [tektoncd/pipeline#852]
# Expected Behavior

Credentials under `/builder/home` should be accessible by non-root builders

# Actual Behavior

Credentials are not accessible by non-root builders

# Steps to Reproduce the Problem

`1-task.yaml` in https://github.com/tektoncd/catalog/pull/20  fails if `moby/buildkit:v0.5.1-rootless` is used instead of `moby/buildkit:v0.5.1` because `buildctl` (runs as  UID 1000) cannot access `/builder/home/.docker/config.json` which is owned by root:root with permission 0600.

# Additional Info

**Comment by vdemeester** [comment]
@sbwsg I think this might be fixed by #2671 ins't it ?

**Comment by sbwsg** [comment]
Yeah, the UID issue should be resolved.  `/tekton/home` is also going away at some point (or at least that's the current plan).  I'll close this but feel free to reopen if there is more to do here.

**Comment by shibumi** [comment]
Hey everybody, I stumbled upon this while reading the buildkit-daemonless README:
https://github.com/tektoncd/catalog/tree/master/task/buildkit-daemonless/0.1

Am I correct with the thought that we can remove the `privileged: true` from that task now?

**Comment by sbwsg** [comment]
@shibumi I'm not entirely sure why buildkit-daemonless uses `privileged: true` tbh.  Does that have any bearing on the user which the container runs with?  I would've thought that's decided by the image.

**Comment by shibumi** [comment]
@sbwsg  privileged: true means it runs with root in the cluster/on the node. This is a possible security vulnerability, especially if want to include/run a shell script in the container from the git repository you have checked out.

**Comment by sbwsg** [comment]
Right, I'm just not sure that buildkit-daemonless uses `priviliged: true` due to the credential issue we fixed in https://github.com/tektoncd/pipeline/pull/2671 though.  I'm unclear why buildkit-daemonless needs `privileged: true` in the first place.

**Comment by shibumi** [comment]
@sbwsg ah okay, my assumption was that it needed to run as root (because of certain reasons). The task's README mentioned this:

|                  | `buildkit`     | `buildkit-daemonless`|
|------------------|----------------|----------------------|
|Difficulty        | Hard           | Easy                 |
|Supports Rootless | Yes            | No (BuildKit per se supports, but [Tekton doesn't support](https://github.com/tektoncd/pipeline/issues/852))|
|Cache             | Registry+Local | Registry             |

and that's how I found this issue here.

**Comment by AkihiroSuda** [comment]
We should be now able to switch to rootless and remove privileged: true, but I haven't confirmed yet

**Comment by shibumi** [comment]
btw the image says this:

```
    # The image needs to be rootful because Tekton creates /builder/home/.docker/config.json owned by root:root with 0600
    # https://github.com/tektoncd/pipeline/issues/852
    default: "docker.io/moby/buildkit:v0.6.2@sha256:db234cf7362aef489e4273a6937794cb19c09ba15c7ee0ec6f85044086ea4f6a"
```

and when I try to run this task I get a bigge error (but I am not sure if I am just calling it incorrectly)

**Comment by shibumi** [comment]
@sbwsg  @akihikokuroda  We seem to need root for the daemonless version, because buildkit wants to mount things:

```
error: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: failed to mount /tmp/buildkit-mount266242261: [{Type:bind Source:/var/lib/buildkit/runc-native/snapshots/snapshots/2 Options:[rbind ro]}]: operation not permitted
```

**Comment by shibumi** [comment]
@sbwsg  @akihikokuroda ok.. one addition: The daemonless task uses `moby/buildkit:6.2` if you change the image to `moby/buildkit:6.2-rootless` it works.

**Comment by AkihiroSuda** [comment]
> 
> ```
> 
> error: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: 
> 
> failed to read dockerfile: failed to mount  
> 
> /tmp/buildkit-mount266242261: 
> 
> [{Type:bind Source:/var/lib/buildkit/runc-native/snapshots/snapshots/2 Options:[rbind ro]}]:
> 
> operation not permitted
> 
> ```

Seccomp and AppArmor needs to be unconfined like this https://github.com/moby/buildkit/blob/v0.8.2/examples/kubernetes/job.rootless.yaml

Also might be related to https://github.com/moby/buildkit/issues/879

**Comment by qu1queee** [comment]
Jumping into this thread. I opened a [PR](https://github.com/shipwright-io/build/pull/675) in Shipwright to support Buildkit, there, we do a small trick so that the `/tekton/home` is nonroot. Thanks for the discussions in here, they helped me a lot.
