### ISSUE TITLE
Observability aspects of CD pipelines

### ISSUE THREAD

**Issue by pavlobaron** [tektoncd/pipeline#855]
hi guys,

I opened this communication thread offline with Christie, Chris and Dan, they recommended to move it here.

In my role as founder and CTO of Instana, and for the reasons of personal interest I would like to open a discussion about observability aspects, and eventually see if this needs to be worked on in a dedicated group. Observability of CD pipelines IMO goes way beyond just metrics collection and local health checks inside of the pipeline.

I would be happy if people could first point me at where observability's homebase is right now inside of Tekton, from where I could move forward and ask questions / make suggestions. We as APM vendor built our product specifically for modern tech stacks and architectural approaches, and CD pipelines always play an important role in the overall work of our very customers.

I am sure we can make a great contribution here together. Looking forward to working on this!

regards - Pavlo Baron, CTO Instana

**Comment by sbwsg** [comment]
We had our first meeting regarding observability, specifically metrics, today and work is now underway. There are a couple of other issues that overlap in theme with this one. I am linking them together here for us to review later and figure out which to keep and which to close.

Related issues:
https://github.com/tektoncd/pipeline/issues/164
https://github.com/tektoncd/pipeline/issues/540
https://github.com/tektoncd/pipeline/issues/855

[Metrics Design Doc](https://docs.google.com/document/d/1NbY3spcNVXqrZHbEp5pfFQbCyGtN8Aj7Y5d4elwM5cI/edit)

[Notes from the initial metrics meeting](https://docs.google.com/document/d/1n-ZJzKMEH31mDSooaCjVV5b3d19zwJkuDm4fmrevoLs/edit)

**Comment by bobcatfish** [comment]
what are the next steps here @sbwsg @pavlobaron ?

**Comment by sbwsg** [comment]
Some work has been done on this: https://github.com/tektoncd/pipeline/pull/1387

I'm tempted to say we should close this.

**Comment by bobcatfish** [comment]
Closing for now! Thanks all :)
