### ISSUE TITLE
Create Pipeline for nightly releases

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#860]
# Expected Behavior

Folks who are integrating with Tekton would like to be able to integrate with regular builds (e.g. nightly) so that they can test out new functionality and catch integration pain points and bugs between releases.

# Actual Behavior

Currently we release manually approximately every 4 weeks.  In #531 we will add a Pipeline which can do this via Prow.

# Additional Info

* #531 adds release Pipeline triggering via Prow
* knative uses a completely different bucket for nightly releases ([knative-nightly vs knative-releases](https://github.com/knative/test-infra/blob/e645a487ca4e1c867d87685f215e9746bea18475/scripts/release.sh#L26)), we could do the same

Solving this issue should include:
* Docs on what is released when and how to find it (probably at https://github.com/tektoncd/pipeline/blob/master/docs/install.md)
* Nightly releases should _not_ show up in https://github.com/knative/serving/releases (or should they? i'm not sure)

**Comment by bobcatfish** [comment]
@vdemeester does this mean you'll be doing https://github.com/tektoncd/pipeline/issues/531 as well? :D :D  :D

**Comment by bobcatfish** [comment]
I guess you do them independently - #531 is blocked on https://github.com/tektoncd/pipeline/issues/530 also :sweat_smile:

**Comment by Gl4di4torRr** [comment]
@bobcatfish are you saying this is currently blocked by #530 and #531?

**Comment by vdemeester** [comment]
@Gl4di4torRr it's not entirely blocked but it's kinda related :angel: Now that Kubecon and Red Hat Summit are behind, I'll have more time to make this happen :man_dancing:

**Comment by Gl4di4torRr** [comment]
@vdemeester great! i am looking for a good "first time contributor" issue to tackle. if this would be a good one, i can try implementing this.

**Comment by Gl4di4torRr** [comment]
@vdemeester nvm looks like y'all have a `good first issue` tag :)

**Comment by bobcatfish** [comment]
Gonna base this on @vdemeester 's proposal for [automated releases](https://docs.google.com/document/d/1BE9E2NkkvnZHdpX4F8ofBG-Uwd07bzx5cPoHSP67qmo/edit#heading=h.2gby4qql9dya)

**Comment by bobcatfish** [comment]
Nightly releases are now releasing to the gs bucket `tekton-releases-nightly` !! 🎉
