### ISSUE TITLE
PipelineRun definition expects pipelinerun.spec.trigger.type

### ISSUE THREAD

**Issue by jotacamou** [tektoncd/pipeline#884]
# Expected Behavior
Following the examples and documentation, was not able to create a `PipelineRun` if `pipelinerun.spec.trigger.type` is not specified.

# Actual Behavior

```Error from server (InternalError): error when creating "pipelinerun.yaml": Internal error occurred: admission webhook "webhook.tekton.dev" denied the request: mutation failed: invalid value: : pipelinerun.spec.trigger.type```

# Steps to Reproduce the Problem

1. Create a `PipelineRun` without
```
spec:
  trigger:
    type: manual
```

# Additional Info
Using lastest release.

**Comment by vincent-pli** [comment]
@jotacamou 
Please check the age of  pods in name space: `tekton-pipelines`, they just removed `trigger` several days ago.
Use the `master` cannot reproduce this issue.

**Comment by jotacamou** [comment]
Confirmed.  Not an issue on `master` branch however present on `v0.3.1`.  Please close, thank you!

**Comment by bobcatfish** [comment]
Glad you got it working! Thanks for opening the issue @jotacamou :D

**Comment by cmoulliard** [comment]
This error still exists with the tutorial doc as I get this error when I deploy the pipelineRun

```
kubectl  apply -f pipelineRun.yml -n tutorial
Error from server (InternalError): error when creating "pipelineRun.yml": Internal error occurred: admission webhook "webhook.tekton.dev" denied the request: mutation failed: invalid value: : pipelinerun.spec.trigger.type
```

**Comment by vdemeester** [comment]
@cmoulliard which version of tekton pipeline did you deploy ?

**Comment by sarnaudova** [comment]
Getting the same error with the latest tekton release v0.3.1
If this change is only in master, how can I install tekton from a master branch ?
I am using the installation instruction from the doc :
kubectl apply --filename https://storage.googleapis.com/tekton-releases/latest/release.yaml

Error when running pipeline (without triggers):
Error from server (InternalError): error when creating "pipelinerun.yaml": Internal error occurred: admission webhook "webhook.tekton.dev" denied the request: mutation failed: invalid value: : pipelinerun.spec.trigger.type

**Comment by vincent-pli** [comment]
@sarnaudova 
Please take a look this: https://github.com/tektoncd/pipeline/blob/master/DEVELOPMENT.md
Use `ko` to apply the `master` to the cluster.

**Comment by bobcatfish** [comment]
We should have a 0.4 release coming out this week @sarnaudova ! Sorry for the difficulty :(
