### ISSUE TITLE
Doc: Improve task introduction

### ISSUE THREAD

**Issue by cmoulliard** [tektoncd/pipeline#896]
## Request

The[ Task's doc](https://github.com/tektoncd/pipeline/blob/master/docs/tasks.md#tasks) part don't really introduce from a technical perspective what it does and how it works (pod + containers for each step). Nevertheless, this is covered by the first part of the [tutorial](
https://github.com/tektoncd/pipeline/blob/master/docs/tutorial.md#task)

So I propose to review the Task intro part and merge the content from the tutorial such as

"The main objective of Tekton Pipelines is to run your Task individually or as a part of a Pipeline. Every task runs as a Pod on your Kubernetes cluster with each step as its own container."

Remark: All these concepts (task, pipelines) should be covered [here](https://github.com/tektoncd/pipeline/tree/master/docs) and documented to explain how a TaskRun or PipelineRun will be converted by the operator/controller into pod(s) and container(s) created.

**Comment by bobcatfish** [comment]
Sounds good to me!

**Comment by dibyom** [comment]
Task intro now mentions that it creates Pods.

/close
