### ISSUE TITLE
Merge "Graceful Sidecar Support" implementation

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/pipeline#926]
@dicarlo2 has [proposed](https://github.com/tektoncd/pipeline/issues/727) and [implemented](https://github.com/tektoncd/pipeline/pull/728) graceful sidecar support. The remaining work is to:

- [x] Perform any needed code organization
- [x] Get all existing tests passing
- [x] Satisfy lint and any other presubmit tools
- [x] Add test coverage where needed
- [x] Document usage
- [ ] \~\~Demo the results\~\~

**Comment by bobcatfish** [comment]
It is done!! Thanks @sbwsg @joseblas @dicarlo2 !!! 🎉
