### ISSUE TITLE
v0.4.0 release.yaml missing from GitHub assets

### ISSUE THREAD

**Issue by khrisrichardson** [tektoncd/pipeline#932]
# Expected Behavior

Download `release.yaml` from GitHub release [v0.4.0](https://github.com/tektoncd/pipeline/releases/tag/v0.4.0) :+1: 

# Actual Behavior

Download `release.yaml` ala `gsutil cp gs://tekton-releases/latest/release.yaml .` :-1: 

# Steps to Reproduce the Problem

1. Get excited to install new release
2. Look for release.yaml
3. :crying_cat_face: 

# Additional Info

**Comment by bobcatfish** [comment]
Whoops! One sec :D (#530 can't come quickly enough... :sweat_smile: )

**Comment by bobcatfish** [comment]
Okay [should be up now with the v0.4.0 release!](https://github.com/tektoncd/pipeline/releases/tag/v0.4.0) Sorry about that and thanks for the quick report @khrisrichardson :D :heart::heart::heart:

**Comment by khrisrichardson** [comment]
Sweet. Thanks @bobcatfish for all the awesomeness

**Comment by bobcatfish** [comment]
p.s. I am a big fan of your emoji use in the report, especially the skillful deployment of the sad cat emoji :crying_cat_face:
