### ISSUE TITLE
Tekton Creates PVC unnecessarily if volumes are defined

### ISSUE THREAD

**Issue by mustafaakin** [tektoncd/pipeline#937]
# Expected Behavior

I have task with no inputs or outputs. It should not have any PVCs.

# Actual Behavior

But a PVC is created if the Task spec has volumes in it. 

# Steps to Reproduce the Problem

```yml
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: msg
spec:
  steps:
  - name: msg
    image: alpine
    command:
    - echo
    args:
    - slm
  volumes: []
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: demo-pipeline
spec:
  tasks:
  - name: test-1
    taskRef:
      name: msg
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: tst-run
spec:
  pipelineRef:
    name: demo-pipeline
```

```sh
$  kubectl apply -f test-1.yaml
task.tekton.dev/msg created
pipeline.tekton.dev/demo-pipeline created
pipelinerun.tekton.dev/tst-run created
$ kubectl get pvc
NAME          STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
tst-run-pvc   Pending                                      standard       2s
```

# Additional Info

tekton 0.4

**Comment by bobcatfish** [comment]
I see the same thing:

```
➜  pipeline git:(stepTemplate) ✗ k get pvc          
NAME          STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
tst-run-pvc   Bound    pvc-ab83fef7-83f9-11e9-8c6b-42010a800ff4   5Gi        RWO            standard       6s
```

**Comment by bobcatfish** [comment]
Re-opening this b/c we had a massive bug (#1068) in our first attempt to fix this! 😅 🙏

**Comment by bobcatfish** [comment]
Quick update: @dlorenc and I have been looking into this, and instead of tackling it directly, want to propose some updates to the way we've designed input + output linking. Stay tuned!

**Comment by bobcatfish** [comment]
I'm going to close this in favor of #1076: this will remain a known issue for the moment, in the meantime we will work on #1076 and remove this problem by changing the way resource linking works.

**Comment by bobcatfish** [comment]
Okay so long story short, we've been working on completely overhauling PipelineResources #1673 by adding other features that may potentially replace them (e.g. workspaces + task results) - but this means we haven't addressed this issue and we definitely need to before beta, so I'm re-opening this.

**Comment by bobcatfish** [comment]
Oh! https://github.com/tektoncd/pipeline/pull/1545 fixed this after all (apparently causing sorrow for folks who were relying on this implementation detail 😅 ) but good in the long run!!!
