### ISSUE TITLE
Order TaskRun.Status.Steps same way as Task.Spec.Steps

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/pipeline#942]
Related to https://github.com/tektoncd/pipeline/pull/818#discussion_r288705407, the `TaskRun.Status.Steps` order is not the same as `Task.Spec.Steps`, as @hrishin commented.

> yeah its because of taskrun reconciler copies the `pod.status.containerStatus` for all steps. By default, k8s sort the `containerStatus` in alphabetically sorted order (which is wired don't know why).
> 
> While working on fetching the task logs, one has to either iterate through `pod.status.containerStatus` or `TaskRun.Status.Steps`. Now the issue is, steps order is not maintained anymore, it has to find the currently running container and rather simply iterate over `taskrun.status.steps` while printing the logs.

We feel it would be better if the order would be kept, to simplify iterating over the status and also because as a user it feels a bit weird to see status in a different order.

cc @hrishin @bobcatfish 

/kind enhancement

**Comment by hrishin** [comment]
Thank you! @vdemeester :+1:
