### ISSUE TITLE
TestHelmDeployPipelineRun is failing "a lot"

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/pipeline#943]
It is either flaky or something change in the image we use that makes the test fail on all PRs

```
I0604 07:01:08.915] --- FAIL: TestHelmDeployPipelineRun (95.57s)
I0604 07:01:08.916]     init_test.go:101: Create namespace arendelle-lpdmr to deploy to
I0604 07:01:08.916]     init_test.go:113: Verify SA "default" is created in namespace "arendelle-lpdmr"
I0604 07:01:08.916]     helm_task_test.go:230: Creating tiller service account
I0604 07:01:08.916]     helm_task_test.go:286: Creating Cluster Role binding tiller-6hb2d for helm
I0604 07:01:08.917]     helm_task_test.go:286: Creating Cluster Role binding default-tiller-pj2hh for helm
I0604 07:01:08.917]     helm_task_test.go:286: Creating Cluster Role binding default-tiller-c6wwv for helm
I0604 07:01:08.917]     helm_task_test.go:62: Creating Git PipelineResource go-helloworld-git
I0604 07:01:08.917]     helm_task_test.go:67: Creating Image PipelineResource go-helloworld-image
I0604 07:01:08.917]     helm_task_test.go:72: Creating Task create-image-task
I0604 07:01:08.917]     helm_task_test.go:77: Creating Task helm-deploy-task
I0604 07:01:08.917]     helm_task_test.go:82: Creating Pipeline helm-deploy-pipeline
I0604 07:01:08.917]     helm_task_test.go:87: Creating PipelineRun helm-deploy-pipeline-run
I0604 07:01:08.918]     helm_task_test.go:94: Error waiting for PipelineRun helm-deploy-pipeline-run to finish: pipeline run helm-deploy-pipeline-run failed!
I0604 07:01:08.918]     artifact_bucket_test.go:53: build logs {"level":"warn","ts":1559631657.6882505,"logger":"fallback-logger","caller":"logging/config.go:65","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/test\" is not a valid GitHub commit ID"}
I0604 07:01:08.918]         {"level":"info","ts":1559631657.6889648,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}
I0604 07:01:08.918]     artifact_bucket_test.go:53: build logs {"level":"warn","ts":1559631591.789462,"logger":"fallback-logger","caller":"logging/config.go:65","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/test\" is not a valid GitHub commit ID"}
I0604 07:01:08.918]         {"level":"info","ts":1559631591.7898474,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}
I0604 07:01:08.918]     helm_task_test.go:104: PipelineRun execution failed; helm may or may not have been installed :(
```

/area testing

**Comment by chmouel** [comment]
I can reproduce it every time when running it locally with : 

```sh
go test -failfast -v -count=1 -tags=e2e -ldflags '-X github.com/tektoncd/pipeline/test.missingKoFatal=false' ./test -timeout=20m --kubeconfig $KUBECONFIG -run TestHelmDeployPipelineRun 2>&1 |tee /tmp/log
```

<details>
  <summary>log output from help-deploy pod</summary>
<pre>
 % kubectl logs helm-deploy-pipeline-run-push-image-5sqgv-pod-11f226 --all-containers
{"level":"warn","ts":1559636604.083356,"logger":"fallback-logger","caller":"logging/config.go:65","msg":"Fetch GitHub commit ID from kodata failed: \"KO_DATA_PATH\" does not exist or is empty"}
{"level":"info","ts":1559636604.0847075,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}
{"level":"warn","ts":1559636605.884883,"logger":"fallback-logger","caller":"logging/config.go:65","msg":"Fetch GitHub commit ID from kodata failed: \"KO_DATA_PATH\" does not exist or is empty"}
{"level":"info","ts":1559636608.3365455,"logger":"fallback-logger","caller":"git/git.go:105","msg":"Successfully cloned https://github.com/tektoncd/pipeline @ master in path /workspace/gitsource"}
INFO[0000] Downloading base image golang
2019/06/04 08:23:30 No matching credentials were found, falling back on anonymous
INFO[0000] Unpacking rootfs as cmd RUN go install github.com/tektoncd/pipeline/test/gohelloworld requires it.
INFO[0021] Taking snapshot of full filesystem...
INFO[0031] Skipping paths under /kaniko, as it is a whitelisted directory
INFO[0031] Skipping paths under /proc, as it is a whitelisted directory
INFO[0031] Skipping paths under /dev, as it is a whitelisted directory
INFO[0031] Skipping paths under /sys, as it is a whitelisted directory
INFO[0031] Skipping paths under /builder/tools, as it is a whitelisted directory
INFO[0031] Skipping paths under /builder/home, as it is a whitelisted directory
INFO[0031] Skipping paths under /run/secrets, as it is a whitelisted directory
INFO[0031] Skipping paths under /var/run, as it is a whitelisted directory
INFO[0031] Skipping paths under /workspace, as it is a whitelisted directory
INFO[0037] Using files from context: [/workspace/gitsource]
INFO[0038] COPY . /go/src/github.com/tektoncd/pipeline/
INFO[0039] Taking snapshot of files...
INFO[0041] RUN go install github.com/tektoncd/pipeline/test/gohelloworld
INFO[0041] cmd: /bin/sh
INFO[0041] args: [-c go install github.com/tektoncd/pipeline/test/gohelloworld]
INFO[0042] Taking snapshot of full filesystem...
INFO[0051] Skipping paths under /kaniko, as it is a whitelisted directory
INFO[0051] Skipping paths under /proc, as it is a whitelisted directory
INFO[0051] Skipping paths under /dev, as it is a whitelisted directory
INFO[0051] Skipping paths under /sys, as it is a whitelisted directory
INFO[0051] Skipping paths under /builder/tools, as it is a whitelisted directory
INFO[0051] Skipping paths under /builder/home, as it is a whitelisted directory
INFO[0051] Skipping paths under /run/secrets, as it is a whitelisted directory
INFO[0051] Skipping paths under /var/run, as it is a whitelisted directory
INFO[0051] Skipping paths under /workspace, as it is a whitelisted directory
INFO[0056] ENTRYPOINT /go/bin/gohelloworld
INFO[0056] EXPOSE 8080
INFO[0056] cmd: EXPOSE
INFO[0056] Adding exposed port: 8080/tcp
error pushing image: failed to push to destination index.docker.io/chmouel/kanikotasktest/go-helloworld-image-28w88:latest: unsupported status code 401; body:
Error from server (BadRequest): container "build-step-image-digest-exporter-kaniko-85hvf" in pod "helm-deploy-pipeline-run-push-image-5sqgv-pod-11f226" is waiting to start: trying and failing to pull image
</pre>
</details>

**Comment by chmouel** [comment]
another note: unsetting `KO_DOCKER_REPO` would `SKIP` the test properly : 


```
% unset KO_DOCKER_REPO
 % go test -failfast -v -count=1 -tags=e2e -ldflags '-X github.com/tektoncd/pipeline/test.missingKoFatal=false' ./test -timeout=20m --kubeconfig $KUBECONFIG -run TestHelmDeployPipelineRun 2>&1 |tee /tmp/log
Using kubeconfig at `/Users/chmouel/.kube/config` with cluster ``=== RUN   TestHelmDeployPipelineRun
--- SKIP: TestHelmDeployPipelineRun (0.00s)
    ko_test.go:33: KO_DOCKER_REPO env variable is required
PASS
ok  	github.com/tektoncd/pipeline/test	0.035s
```

**Comment by vdemeester** [comment]
#946 fixes this problem (and will fix master and PRs). 2 days ago, `alpine/helm` was updated and `latest` now point to `3.0.0-alpha.1` which, doesn't work the same way as 2.x (make sense :angel:)
