### ISSUE TITLE
Why tekton?

### ISSUE THREAD

**Issue by emichaf** [tektoncd/pipeline#947]
reference:
https://github.com/tektoncd/pipeline/issues/907#issuecomment-498368697

Hi @bobcatfish
With Argo CI you can specify workflows with steps (like pipelines), also different gateways exist (rest, amqp..etc) to trigger workflows (pipelines), build steps are executed in containers. Possible to handle input/output in/between steps with different artifacts like git etc...

Hard to see the differences between Argo and Tekton (except that Tekton being part of the cd foundation)!

Q:
- What will Tekton solve which are not already included in Argo CI & CD ?

**Comment by vdemeester** [comment]
@emichaf it would have been possible to comment on the closed issue and we would have re-opened it :angel:

**Comment by abayer** [comment]
Tekton provides pieces that can be used by other CI/CD solutions, such as Jenkins X.

**Comment by chmouel** [comment]
Aside of the technical differentiations, having different implementations is generally what drives innovations among opensource project and I believe having multiple of them is healthy for Kubernetes and for argo and tekton,

**Comment by emichaf** [comment]
Thanks for your answers, I will test/evaluate Tekton the coming weeks!

**Comment by bobcatfish** [comment]
Thanks for the questions @emichaf !! :D

**Comment by prateekkhera** [comment]
@emichaf - did you reach any opinion? I am now at the same state where you were 2 years ago :sweat_smile:
