### ISSUE TITLE
Support local path as pipeline resource type

### ISSUE THREAD

**Issue by houshengbo** [tektoncd/pipeline#953]
We are now supporting "git", "storage", "image", and "cluster".
Shall we support an easier case to allow users develop and save code locally somewhere in order to build?

**Comment by bobcatfish** [comment]
Related discussions in:
- https://github.com/tektoncd/pipeline/issues/924 (about how to make local data available when triggering locally)
- https://github.com/tektoncd/pipeline/issues/235 (being able to "run locally")

**Comment by karlmutch** [comment]
Related Discussion at https://github.com/tektoncd/pipeline/issues/1438
