### ISSUE TITLE
The dollar sign $ creates trouble when running one test

### ISSUE THREAD

**Issue by houshengbo** [tektoncd/pipeline#956]
# Expected Behavior
We should be able to run a single test case by go test -v -tags=e2e -count=1 ./test -run ^TestTaskRun$.

# Actual Behavior
go test -v -tags=e2e -count=1 ./test -run ^TestTaskRun$
There is no test running.

# Steps to Reproduce the Problem

1. Run the command: go test -v -tags=e2e -count=1 ./test -run ^TestTaskRun$

I guess this may be a careless error. When I remove the dollar sign, it worked fine by running "Run the command: go test -v -tags=e2e -count=1 ./test -run ^TestTaskRun".
# Additional Info

**Comment by vdemeester** [comment]
@houshengbo right, I think it's becasue `TestTaskRun` test go renamed :sweat_smile:. The `$` is part of the support regular expression you can use with `-run` to filter tests to run.
