### ISSUE TITLE
kubeconfig does not show the correct information when running integration tests

### ISSUE THREAD

**Issue by houshengbo** [tektoncd/pipeline#958]
# Expected Behavior
Using kubeconfig at `/Users/vincent/.kube/config` with cluster ``
We expect this is a correct information regarding my current environment.

# Actual Behavior
It always shows "Using kubeconfig at `/Users/vincent/.kube/config` with cluster ``", even if I set kubeconfig and cluster to something else. I found the reason is that we print this message before we run c := m.Run(), so it will always print the default values instead of the real values.

# Steps to Reproduce the Problem

1. Run integration tests with the command go test -v -tags=e2e ./test

# Additional Info

**Comment by bobcatfish** [comment]
Nice catch!
