### ISSUE TITLE
There is no way to override default TaskRun timeout with "don't timeout at all"

### ISSUE THREAD

**Issue by abayer** [tektoncd/pipeline#978]
# Expected Behavior

There should be a way to say "don't ever timeout this `TaskRun`".

# Actual Behavior

There isn't. If no timeout is specified on the `PipelineRun`, the `TaskRun.Spec.Timeout` is set to `nil`, and if that's `nil`, then the default timeout of 10 minutes kicks in instead.

# Steps to Reproduce the Problem

1. Create a `PipelineRun` with a `Task` that runs indefinitely.
2. Don't specify a timeout on the `PipelineRun`.
3. Watch it timeout after 10 minutes anyway.

# Additional Info

Putting aside whether 10 minutes is actually an appropriate default timeout length (I'd lean strongly that it should be higher, but am creating a separate issue for that), the fact is that there is no way currently to create a `PipelineRun` that can, deliberately, run forever. That's a problem.

**Comment by bobcatfish** [comment]
Maybe a timeout setting of 0 to indicate no timeout?

**Comment by abayer** [comment]
That sounds perfect to me, yeah.

**Comment by houshengbo** [comment]
@bobcatfish 
It will be feasible that we set the timeout to 0, after we merge the PR: https://github.com/tektoncd/pipeline/pull/996.

**Comment by houshengbo** [comment]
We are able to set the timeout to the value 0, and we can also set the timeout to nil.
If the timeout value is 0, we can take it as no timeout.
If it is still nil, we fall back to use the default 60 mins.
@abayer @bobcatfish Does it sound a plan?

**Comment by abayer** [comment]
Perfect!
