### ISSUE TITLE
TaskRun conditions not fully set and printer fields missing values

### ISSUE THREAD

**Issue by steveodonovan** [tektoncd/pipeline#981]
Not sure if this is an issue. Opening a ticket to check. Seems like the values should be consistent between PipelineRuns and TaskRuns and for task runs at different stages.

# Expected Behavior

- Additional printer fields attached to taskRuns should always have a value.
- conditions reason and message should also always be set on a taskRun

# Actual Behavior

Because the [reason field is not set](https://github.com/tektoncd/pipeline/blob/master/pkg/reconciler/v1alpha1/taskrun/taskrun.go#L396) on a task run in the success case the printer column does not show a value

TaskRun output
```
stephen@stephens-mbp tektonResources $ k get taskRuns
NAME                                                              SUCCEEDED   REASON           STARTTIME   COMPLETIONTIME
cuttingdowntrees-gone-runnin-026-task1-8nfrz                      True                         7d          7d
cuttingdowntrees-gone-runnin-026-task2-cfgn4                      False       TaskRunTimeout   7d          7d
cuttingdowntrees-gone-runnin-0260-task1-w8b2s                     True                         6d          6d
```

PipelineRun output
```
NAME                                                   SUCCEEDED   REASON               STARTTIME   COMPLETIONTIME
output-pipeline-run22-secondnamespace778               True        Succeeded            8d          8d
output-pipeline-run22-secondnamespace970               True        Succeeded            8d          8d
```

Other condition fields are also not set for taskRuns such as message which is set on all pipelineRuns and in other taskRun stages. In the success case the pipeline run has the following under conditions.

```
  - lastTransitionTime: "2019-06-04T15:09:44Z"
    message: All Tasks have completed executing
    reason: Succeeded
    status: "True"
    type: Succeeded
```

taskRuns have this

```
  - lastTransitionTime: "2019-06-04T15:01:29Z"
    status: "True"
    type: Succeeded
```

# Steps to Reproduce the Problem

1. `kubectl get taskRuns` where there are success full task runs on the cluster. The printer column for reason is blank
2. Check the conditions field while the task is running. The message and reason can be added and removed depending on what state the pipelineRun is in.

# Additional Info

If this is an issue could I assign myself? I would like to address it.

**Comment by afrittoli** [comment]
Nice catch, thank you.
`message` and `reason` seem less relevant in case of success; however I agree we should be consistent across CRDs, so personally I think it would be nice to add them in https://github.com/tektoncd/pipeline/blob/fc6ef39101a1bbead39c8271d813ed0e70733cb1/pkg/status/taskrunpod.go#L65
