### ISSUE TITLE
Update release Task to prevent releases clobbering each other

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#983]
# Expected Behavior

If someone tries to use [the dogfood release Task](https://github.com/tektoncd/pipeline/blob/master/tekton/publish.yaml) to re-release a release that has already been created, execution of the Task should fail.

(One idea of how to do this is to add a first step to look in the buckets and the image repo to see if that versionTag has been used before, maybe even check for every single output image and also the yaml files.)

# Actual Behavior

If someone with sufficient permissions tried to run the release Task with a version that has previously been released, the previously released images and yaml file would be overwritten.

One good thing tho is that the digests would change, so the releases used in the yaml files attached to [our github releases](https://github.com/tektoncd/pipeline/releases) wouldn't be affected, however the tags would be updated and the yaml file in our release bucket would be updated.

And there wouldnt even be a warning :sob: 

# Additional Info

We saw something like this actually happen a while ago (pre-dogfooding) in https://github.com/tektoncd/pipeline/issues/253 :O

**Comment by houshengbo** [comment]
@bobcatfish Have we supported conditional execution yet?
If we have a step checking the image and the tags, how can we make sure next step is executed or terminated based on the result of the first step?
Is this what you mean to fix this issue?

**Comment by bobcatfish** [comment]
@houshengbo we _could_ use conditional execution but I think it might be simpler to do this via a step in the existing Task - that way the Task could fail early if a complete run would clobber an existing Task.

imo conditional execution would make sense if it wasn't considered an error to try to overwrite an existing release - but it is an error!
