### ISSUE TITLE
Re-re-add coverage automation

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#988]
# Expected Behavior

* For each PR, the author should get a report about:
  * Whether coverage has gone up and down
  * Which lines are covered and which arent 
* We should be able to track coverage over time
* The coverage check will also fail if the coverage goes down below a threshold

Example of the covbot feedback:

![image](https://user-images.githubusercontent.com/432502/54629334-99c39f80-4a34-11e9-841a-5b0955d05df5.png)

The file link above will link to a line by line coverage analysis.

# Actual Behavior

1. Our coverage reporting randomly stopped
2. I tried to add codecov but ran into two main problems:
  1. The tool expects to be able to have access to a git sha that exists upstream, but prow merges PRs with master before running tests etc., so codecov got upset that the sha was non-sense
  2. My attempts to make codecov ignore our generated files (seen in https://github.com/tektoncd/pipeline/blob/master/codecov.yml) did not work at all :(

# Additional info

Previously re-added in https://github.com/tektoncd/pipeline/issues/637 but I didn't have the heart to re-open the issue.

Since then it mysteriously stopped working.

**Comment by vdemeester** [comment]
It now works :tada: 
![2019-07-23-192242](https://user-images.githubusercontent.com/6508/61733067-4c0ec900-ad7f-11e9-869b-2731c6f0216d.png)

**Comment by bobcatfish** [comment]
woooot thanks @vdemeester !! 🎉
