### ISSUE TITLE
Are we missing the version for github.com/tektoncd/plumbing and github.com/knative/test-infra

### ISSUE THREAD

**Issue by houshengbo** [tektoncd/pipeline#990]
# Expected Behavior
When we update dependencies with ./hack/update-deps.sh, all the dependencies should be pinned to the versions we specified.

# Actual Behavior
github.com/tektoncd/plumbing and github.com/knative/test-infra have never been updated

# Steps to Reproduce the Problem

1. Run ./hack/update-deps.sh

# Additional Info
Are we really missing the versions defined for these two modules? 
I guess knative/test-infra is probably being deprecated, but if tektoncd/plumbing has new scripts, we definitely need them. We need to specify revision for at least tektoncd/plumbing in Gopkg.toml.

**Comment by houshengbo** [comment]
@vdemeester @bobcatfish Is this true?

**Comment by vdemeester** [comment]
@houshengbo we don't really need them, they are needed in `Gopkg.lock`.
Those are present in `Gopkg.toml` but not as dependencies entry. 
https://github.com/tektoncd/pipeline/blob/fc6ef39101a1bbead39c8271d813ed0e70733cb1/Gopkg.toml#L12-L13

https://github.com/tektoncd/pipeline/blob/fc6ef39101a1bbead39c8271d813ed0e70733cb1/Gopkg.lock#L553-L559

> all the dependencies should be pinned to the versions we specified.
All dependencies are *pinned* in the lock file. Only the dependency we need to *force* to a specific version/version-set need to but in the toml.

I feel `./hack/update-deps.sh` has not the right name. It will only fetch the current dependency, as "*update my vendor folder*". To **update a dependency** you need to use `dep` directly, e.g. `dep ensure -update github.com/tektoncd/plumbing`. This will update the `vendor` folder **and** the lock file.

/kind question

**Comment by houshengbo** [comment]
@vdemeester 
With that being said, it looks like we need to update the dependency individually with the command "dep ensure -update the_dep_package", if we would like to. And we are only able to update it to the latest commit.
Would it be better if we can specify which version or revision of that dependency we should update into? 
Maybe ./hack/update-deps.sh does not have a good name, but would it be better if we have a script, which is able to update all the dependencies to specified versions or revisions?

**Comment by vdemeester** [comment]
> Would it be better if we can specify which version or revision of that dependency we should update into?

You can do `dep ensure -update github.com/tektoncd/cli@v0.2.0` for example.

> Maybe ./hack/update-deps.sh does not have a good name, but would it be better if we have a script, which is able to update all the dependencies to specified versions or revisions?

Yeah I do agree on that, we could have something like : 
- `./hack/update-deps.sh` does `dep ensure`
- `./hack/update-deps.sh github.com/tektoncd/plumbing` does `dep ensure -update github.com/tektoncd/plumbing`
- `./hack/update-dep.sh --all` would update all (aka `dep ensure -update`)

@bobcatfish wdyt ?

**Comment by houshengbo** [comment]
Take the plumbing as example, we can take advantage of the file Gopkg.toml by defining

[[override]]
  name = "github.com/tektoncd/cli/plumbing"
  # HEAD as of 2019-0x-xx
  revision = "hash of the commit or version"

Then, run ./hack/update-deps.sh to update github.com/tektoncd/cli/plumbing and all other dependencies to the specified revisions. Gopkg.lock will be updated accordingly as well.

**Comment by vdemeester** [comment]
> Take the plumbing as example, we can take advantage of the file Gopkg.toml by defining
> 
> ```
> [[override]]
>   name = "github.com/tektoncd/cli/plumbing"
>   # HEAD as of 2019-0x-xx
>   revision = "hash of the commit or version"
> ```
> 
> Then, run ./hack/update-deps.sh to update github.com/tektoncd/cli/plumbing and all other dependencies to the specified revisions. Gopkg.lock will be updated accordingly as well.

@houshengbo this would be a `[[constraint]]` instead of `[[override]]` (see the [docs](https://golang.github.io/dep/docs/Gopkg.toml.html#constraint))
