### ISSUE TITLE
What is the intended usage of GetParams in CRDs?

### ISSUE THREAD

**Issue by wlynch** [tektoncd/pipeline#991]
Brought up in https://github.com/tektoncd/pipeline/pull/895#discussion_r289568126

In all Tekton CRDs, there is a func that looks like:

```go
func (s Resource) GetParams() []Param { return []Param{} }
```

https://github.com/tektoncd/pipeline/search?q=GetParams&type=Code

It looks like it is defined to satisfy the [PipelineResourceInterface](https://github.com/tektoncd/pipeline/blob/24c5516232edb04dd3d4ef2f4e3e05afa8958214/pkg/apis/pipeline/v1alpha1/resource_types.go#L49), but I can't find a place where this used meaningfully. What is the intended purpose of this func? Should we be populating this func with values for Tekton CRDs, or should we remove it?

/cc @bobcatfish @vdemeester

**Comment by dlorenc** [comment]
Yeah, looks like this is useless. Removing now.

**Comment by vincent-pli** [comment]
Maybe it's useful when we decide to implement `Variable substitution` of `PipelineResource`, I guess...

**Comment by bobcatfish** [comment]
Since this was removed I'm going to close this issue!
