### ISSUE TITLE
Add metadata to pipelinerun to capture the complete pipeline definition

### ISSUE THREAD

**Issue by siamaksade** [tektoncd/pipeline#994]
It's currently impossible to reason on the exact pipeline definition, conditions, git and image urls used when a pipelinerun is executed given that pipelinerun includes references to pipeline, condition and pipeline resources which all can change after pipeline execution is complete.

This is specially difficult for building tooling around Tekton, for example causing graph visualisation of a completed pipelinerun change when the referenced pipeline is modified.

Adding metadata to the pipelinerun including the exact pipeline, conditions, and resources would allow to capture the exact state of the pipelinerun which won't change even if those referenced resources change. This can be done for example via adding annotations to `PipelineRun`
```
pipelinerun.tekton.dev/pipeline-configuration
pipelinerun.tekton.dev/pipelineresource-configuration
pipelinerun.tekton.dev/condition-configuration
```

An example of this is Helm Releases which embed the generated manifests from the Helm Chart inside the Helm Release to capture the exact resource definitions that are associated with a particular Helm Release, instead of referring to the chart given that the chart can change after the release was created.

**Comment by vdemeester** [comment]
This is also kinda related to @afrittoli comment on #859 on how do we manage pipeline reference of a `PipelineRun` when the `Pipeline` changes (after the run)

> What happens when a PR that modifies the task/pipeline definition is merged? The desired behaviour would be that any running tasks/pipelines keep running on the old definition and any new task/pipeline uses the new definition. However if the new definition is applied to the cluster this would affect in-flight tasks/pipelines.

**Comment by siamaksade** [comment]
@vdemeester I have updated this issue to better capture the need

**Comment by vdemeester** [comment]
This is closed by https://github.com/tektoncd/pipeline/pull/2489 and https://github.com/tektoncd/pipeline/pull/2444
